In [1]:
# Low-RAM clone: run from the repo root (data/, runs/, experiments/ and the ember package are resolved from there).
import os
import sys
from pathlib import Path

_root = Path.cwd()
while not (_root / "ember").is_dir() and _root != _root.parent:
    _root = _root.parent
assert (_root / "ember").is_dir(), "repo root (the folder with ember/) not found above the cwd"
os.chdir(_root)
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))
print(f"cwd: {_root}")

cwd: /home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj

# EMBER §3.1–3.2, variable-width sparse MF — Harry Potter, whitened, variant `m1`

> **Concept:** Harry Potter · **model:** `google/gemma-2-2b-it` · **variant:** `m1` = `VWConfig(method="m1", refit=False)` · **seed:** 42
>
> Clone of `low_ram_demands/whitened.ipynb` (background-whitened + target-sharpened, low RAM) that keeps **only Steps 3.1
> (factorization) and 3.2 (feature identification)**. Step 3.3 (erasure), 3.4 and everything that needs the HF model were removed.
>
> **What changed vs. the source notebook**
> - 3.1.d fits the whitened matrix $A = X^\top$ with the shared variable-width loop `fit_varwidth(A, CFG, seed=SEED)` from
>   `experiments/varwidth/core.py` instead of `SparseMatrixFactorization` + WTA. The implementation and settings are the same as the
>   experiments in `results/varwidth/` (`python -m experiments.varwidth.run`), so this notebook reproduces their
>   `results/varwidth/Harry_Potter/<tag>/seed42/` runs (3.1.d prints the difference if that run exists).
> - 3.1.d′ fits the raw matrix $A_0 = E_{V^*}^\top$ with the **same** method and config (`fit_varwidth(A0, CFG, seed=SEED)`).
> - 3.2 runs the two-stage Gemini judge **only on the whitened fit**. For the original fit (3.2.e′) there are **no Gemini calls**: it
>   lists the $\rho \ge \tau$ candidates with their widths and top tokens, and those candidates stand in for `F_C0` in the
>   comparison cells (3.2.w).
>
> **Hyperparameters**
>
> | | value |
> |---|---|
> | sparse MF | `VWConfig(method="m1", refit=False)`; all other `VWConfig` fields at their defaults: rank 100, sparsity 0.01 (unless set above), floor 0.002, cap 0.03, ridge 1e-4, max_iter 20000, tol 1e-4, patience 200, churn_tol 0.005, init randn, m3_every 20, m3_window 0.02, m3_c 2.0 |
> | whitening | BACKGROUND `"wiki"`, TARGET `"page"`, GAMMA 1.0, ETA / EPS_REL from `experiments/whitening/data/gemma/defaults.json` (0.05 / 1e-4) — as `experiments/varwidth/prep.py` (the source notebook had GAMMA = 0) |
> | selection | TAU 2.0, CONFIDENCE 0.85, TOP_K_TOKENS 20, GEMINI_MODEL `models/gemini-3.5-flash-lite`, judge input = bare tokens |
>
> **Runs.** Caches go to `RUN_DIR = runs/variable_width/Harry_Potter/m1/` (`fit.pt`, `fit0.pt`, `judge.json`, `summary.json`);
> the extended sentences of 3.2.g to `runs/variable_width/Harry_Potter/ext_sentences.json` (shared by the five variants).

Paper: *Don't Forget Your Embeddings: Robust Knowledge Erasure via Precise Editing of Embeddings*
(Suslik, Shafran, Geva, EMNLP Findings 2026).

| Step | Paper section | What happens | Code |
|---|---|---|---|
| **3.1** | Finding Embedding Features with Sparse MF | factorize $X^\top \approx ZY$ with sparse $Y$ (variable width per feature) | `experiments/varwidth/core.py` `fit_varwidth` |
| **3.2** | Identifying Concept-Related Features | mass ratio $\rho_i \ge \tau$, then a two-stage Gemini judge → $F_C$ | `compute_embedding_stats`, prompts from `ember/interpret_features.py` |

**Notation.** `Z` $\in \mathbb R^{d\times k}$ and `Y` $\in \mathbb R^{k\times|V^*|}$ use the paper's shapes. The **width** of feature $i$ is
$|\{t : Y_{i,t} \neq 0\}|$, the number of tokens it uses.

**Requirements:** `HF_TOKEN` if the checkpoint is gated, and a Gemini API key for the judge on the whitened fit (3.2.d–e, 3.2.g neighbours).

---
## 0. Setup

### 0.1 Hyperparameters

| Symbol | Value | Source |
|---|---|---|
| $k$ (rank) | 100 (Gemma-2-2B-it) | App. A.1 |
| budget | $K = \lceil s\,|V^*| \rceil \cdot k$ nonzeros in $Y$, $s$ = `CFG.sparsity` (0.01, or 0.02 for `fixed2`) | App. A.1 / `VWConfig` |
| width bounds | $m_{min} = \lceil 0.002\,|V^*|\rceil$, $m_{max} = \lceil 0.03\,|V^*|\rceil$ (pooling methods and m3; `fixed` ignores them) | `VWConfig.floor`, `.cap` |
| $\lambda$ (ridge) | $10^{-4}$ | App. A.1 |
| $T$ / patience / tol | 20,000 iters / 200 iters (rel. error and support churn < 0.005) / $10^{-4}$ | `VWConfig` |
| refit | off: $Y = Y^{dense}\odot S$ (as the paper) | `VWConfig.refit` |
| $\|S_C\| = \|S_N\|$ | 300 sentences each (`data/*_sentences.json`) | §4.1 |
| $\tau$ (mass-ratio threshold) | 2.0 | App. A.3 |
| judge confidence | ≥ 0.85, with 20 tokens per feature | App. A.3 |

In [2]:
import gc
import json
import math
import os
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from dotenv import load_dotenv
from tqdm.auto import tqdm

load_dotenv()  # HF_TOKEN / GEMINI_API_KEY from .env, if present
pd.set_option("display.max_colwidth", 200)

# ---- what to erase ------------------------------------------------------
CONCEPT = "Harry Potter"
MODEL_NAME = "google/gemma-2-2b-it"     # or "meta-llama/Llama-3.1-8B-Instruct"
SEED = 42

# ==== VARIANT: variable-width sparse MF (experiments/varwidth/, same code and settings as results/varwidth/) ====
import dataclasses

from experiments.varwidth.common import VWConfig, budgets
from experiments.varwidth.core import fit_varwidth

VARIANT = "m1"
VARIANT_CONFIGS = {
    "fixed1": VWConfig(method="fixed", refit=False),                 # the paper: WTA, every feature keeps ceil(0.01 n) tokens
    "fixed2": VWConfig(method="fixed", refit=False, sparsity=0.02),  # WTA with 2%: every feature keeps ceil(0.02 n) tokens
    "m1": VWConfig(method="m1", refit=False),                        # contribution pooling: global top-K of |y_ij|*||z_i||, floor/cap
    "m3": VWConfig(method="m3", refit=False),                        # entropy-allocated widths (exp H of the noise-cut top 2% of |y_i|)
    "rn": VWConfig(method="rn", refit=False),                        # pooling on |y_ij| / ||y_i||, floor/cap
}
CFG = VARIANT_CONFIGS[VARIANT]   # m1: contribution pooling: global top-K of |y_ij| * ||z_i|| (K = ceil(0.01 n) * k), each row within [floor, cap]
SEED = 42
# all other VWConfig fields stay at their defaults (rank 100, floor 0.002, cap 0.03, ridge 1e-4, max_iter 20000, tol 1e-4,
# patience 200, churn_tol 0.005, init randn, m3_every 20, m3_window 0.02, m3_c 2.0)
# ===================================================================================================================

# ---- Step 3.1: names the cells below use, taken from CFG ----------------
RANK = CFG.rank          # k
SPARSITY = CFG.sparsity  # s: total budget K = ceil(s * |V*|) * k
RIDGE = CFG.ridge        # lambda
MAX_ITER = CFG.max_iter  # T
PATIENCE = CFG.patience

# ---- Step 3.2: feature selection (App. A.3) -----------------------------
TAU = 2.0
CONFIDENCE = 0.85
TOP_K_TOKENS = 20
GEMINI_MODEL = "models/gemini-3.5-flash-lite"   # repo default; the paper used Gemini-2.5-Flash-Lite
JUDGE_FORMAT = "tokens"   # Stage-1 judge input: "tokens" (bare tokens, paper; this notebook's original format)
                          # | "words" (token → the words it was cut from in S_C ∪ S_N, alphabetical)

# ---- background whitening + target sharpening (Instructions.txt, experiments/whitening/sharpen.py) ----
import re
import sys

sys.path.insert(0, "experiments/whitening")
from sharpen import BackgroundWhitener, Sharpener, Transform, principal_angle_sines

BACKGROUND = "wiki"      # "wiki" (Wikipedia token types) or "full" (whole vocabulary)
TARGET = "page"          # "page" (all tokens of the concept's English Wikipedia page) or "page_minus_wiki"
GAMMA = 1.0              # sharpening strength, as experiments/varwidth/prep.py (the source notebook had 0)
MODEL_SLUG = "gemma"     # "gemma" | "llama": selects experiments/whitening/data/<MODEL_SLUG>
SMOKE = False            # True: quick pass (short fit, 3 judged features)
assert BACKGROUND in ("wiki", "full"), BACKGROUND
assert TARGET in ("page", "page_minus_wiki"), TARGET
assert GAMMA >= 0, GAMMA
assert MODEL_SLUG == ("llama" if "llama" in MODEL_NAME.lower() else "gemma"), (MODEL_SLUG, MODEL_NAME)

WH_DIR = Path("experiments/whitening/data") / MODEL_SLUG
_defaults_path = WH_DIR / "defaults.json"     # the file experiments/varwidth/prep.py reads (no built-in fallback)
defaults = json.loads(_defaults_path.read_text())
ETA = defaults["eta"]            # target shrinkage (0.05)
EPS_REL = defaults["eps_rel"]    # eps = EPS_REL * mean(background eigenvalues) (1e-4)
print(f"whitening defaults from {_defaults_path}: eta={ETA:g} eps_rel={EPS_REL:g}")

if SMOKE:
    CFG = dataclasses.replace(CFG, max_iter=50, patience=5)
    MAX_ITER, PATIENCE = CFG.max_iter, CFG.patience

# ---- run directories: resume caches ----
concept_slug = re.sub(r"\W+", "_", CONCEPT).strip("_")
_smoke = "_smoke" if SMOKE else ""
RUN_DIR = Path("runs/variable_width") / concept_slug / f"{VARIANT}{_smoke}"   # fit.pt, fit0.pt, judge.json, summary.json
RUN_DIR.mkdir(parents=True, exist_ok=True)


def load_json(path: Path, default):
    return json.loads(path.read_text()) if path.exists() else default


def save_json(path: Path, obj) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")   # write then rename, so a crash never leaves a half file
    tmp.write_text(json.dumps(obj, indent=1, ensure_ascii=False, default=lambda o: o.item() if hasattr(o, "item") else str(o)))
    tmp.replace(path)


def invalidate(directory: Path, names) -> None:
    """Move stale cache files aside (<name>.stale) so they are recomputed."""
    for name in names:
        p = directory / name
        if p.exists():
            p.replace(p.with_name(p.name + ".stale"))
            print(f"  moved stale {p} -> {p.name}.stale")

concepts = [e["concept"] for e in json.loads(Path("data/concept_sentences.json").read_text())]
assert CONCEPT in concepts, f"{CONCEPT!r} is not one of: {concepts}"
print(f"concept={CONCEPT!r} | model={MODEL_NAME} | variant={VARIANT} | seed={SEED} | config={CFG}")
print(f"background={BACKGROUND} | target={TARGET} | gamma={GAMMA:g} | eta={ETA:g} | eps_rel={EPS_REL:g} | "
      f"smoke={SMOKE} | run dir={RUN_DIR}")

whitening defaults from experiments/whitening/data/gemma/defaults.json: eta=0.05 eps_rel=0.0001
concept='Harry Potter' | model=google/gemma-2-2b-it | variant=m1 | seed=42 | config=VWConfig(method='m1', rank=100, sparsity=0.01, floor=0.002, cap=0.05, ridge=0.0001, max_iter=20000, tol=0.0001, patience=200, churn_tol=0.005, init='randn', refit=False, floorcap=True, continuation=False, cont_start=0.05, cont_iters=2000, m3_every=20, m3_window=0.02, m3_c=2.0, m4_every=10)
background=wiki | target=page | gamma=1 | eta=0.05 | eps_rel=0.0001 | smoke=False | run dir=runs/variable_width/Harry_Potter/m1

/home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 0.2 Gemini API key

Step 3.2 is the only step that calls Gemini. You can paste your key below or put `GEMINI_API_KEY=...`
in `.env`. Clear the key from this cell before you commit or share the notebook.

In [3]:
GEMINI_API_KEY = ""  # paste here, or leave empty to use .env / the environment

if GEMINI_API_KEY:
    os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
assert any(os.getenv(k) for k in ("GOOGLE_API_KEY", "GEMINI_API_TOKEN", "GEMINI_API_KEY")), \
    "No Gemini key found: Step 3.2 needs one."
print("Gemini key found.")

Gemini key found.

### 0.3 Repo imports

These are the building blocks the paper's pipeline uses. Reusing them means the notebook gives the same
results as `ember.train_mf_features`, `ember.interpret_features`, and `ember.run_erasure`.

In [4]:
from llm_utils.activation_generator import ActivationGenerator, extract_token_ids_sample_ids_and_labels
from transformers import AutoTokenizer

from ember.interpret_features import (
    MEMBERSHIP_PROMPT,
    TOKENS_DESC_SYS,
    SimpleGeminiClient,
    classify_membership_with_desc,
    get_description,
)
from ember.local_datasets import ConceptDataset
from ember.timing import Timer
from ember.utils import (
    _safe_model_name,
    build_token_label_codes,
    collect_feature_rows_for_embeddings,
    compute_embedding_stats,
    get_special_token_ids,
    set_seed,
)

set_seed(SEED)
# DEVICE = resolve_device("auto")
# This host's vGPU reports CUDA as available but prohibits compute, so force CPU.
DEVICE = "cpu"   # the experiments (experiments/varwidth/run.py) also fit on CPU
print(f"device: {DEVICE}")

device: cpu

---
# Step 3.1: Finding embedding features with Sparse Matrix Factorization

**Goal:** split each token embedding $\mathbf e_t$ into a sum of a few shared directions, so that
semantically related tokens (e.g. *Harry*, *Hogwarts*, *wand*) share a feature:

$$E_{V^*}^\top \approx Z\,Y,\qquad Z\in\mathbb R^{d\times k}\ \text{(dense features)},\quad Y\in\mathbb R^{k\times|V^*|}\ \text{(sparse coefficients)}$$

In the paper a hard winner-takes-all (WTA) constraint on the rows of $Y$ makes each feature $\mathbf z_i$ use only
1% of the tokens in $V^*$. That is why a feature can be specific to one concept. **In this notebook** the support of $Y$ is
chosen by the variant's allocation rule (`CFG.method`, see 3.1.d): the total number of nonzeros is fixed at
$K = \lceil s|V^*|\rceil\cdot k$, but except for `fixed` the **width** (tokens per feature) can differ between features.

### 3.1.a Load the model (TransformerLens)

The pipeline reads $E$ through TransformerLens. **Note:** for Gemma, TL folds the $\sqrt{d}$ embedding
multiplier into `W_E`, so the factorization runs in this *scaled* space.

In [5]:
# Low-RAM: steps 3.1-3.2 use only W_E and the tokenizer, so no TransformerLens model is built.
# W_E is read straight from the checkpoint and matches TL's: Gemma = HF embedding * sqrt(d_model), Llama = as stored;
# TL skips writing-weight centering for RMSNorm models. E_DTYPE is the dtype this notebook's TL model used.
import json
import math
from types import SimpleNamespace

from huggingface_hub import hf_hub_download
from huggingface_hub.utils import EntryNotFoundError
from safetensors import safe_open

E_DTYPE = torch.float32

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if tokenizer.pad_token is None:  # Llama-3: TL also pads with eos
    tokenizer.pad_token = tokenizer.eos_token


def load_input_embeddings(model_name: str) -> torch.Tensor:
    """Reads only model.embed_tokens.weight from the checkpoint (no model is built)."""
    try:
        index = json.loads(Path(hf_hub_download(model_name, "model.safetensors.index.json")).read_text())
        shard = index["weight_map"]["model.embed_tokens.weight"]
    except EntryNotFoundError:  # single-file checkpoint
        shard = "model.safetensors"
    with safe_open(hf_hub_download(model_name, shard), framework="pt") as f:
        return f.get_tensor("model.embed_tokens.weight")


class TokenizerOnly:
    """The parts of a HookedTransformer that 3.1-3.2 use: tokenizer, to_tokens, to_str_tokens."""

    def __init__(self, tok):
        self.tokenizer = tok

    def to_tokens(self, prompts, padding_side="left"):
        self.tokenizer.padding_side = padding_side
        return self.tokenizer(prompts, return_tensors="pt", padding=True)["input_ids"]  # BOS added by the tokenizer

    def to_str_tokens(self, ids):
        return self.tokenizer.batch_decode(torch.as_tensor(ids).reshape(-1, 1), clean_up_tokenization_spaces=False)


tl_model = TokenizerOnly(tokenizer)  # keeps the old names, so the cells below run unchanged
act_generator = SimpleNamespace(model=tl_model, data_device="cpu")

E = load_input_embeddings(MODEL_NAME).to(E_DTYPE)  # (|V|, d)
if "gemma" in MODEL_NAME.lower():
    E.mul_(torch.tensor(math.sqrt(E.shape[1]), dtype=E_DTYPE))  # in place: no second (|V|, d) copy
VOCAB_SIZE, D_MODEL = E.shape
print(f"E: {tuple(E.shape)}  dtype={E.dtype}")

E: (256000, 2304)  dtype=torch.float32

### 3.1.b Build $S_C \cup S_N$ and the token set $V^*$

- $S_C$: 300 Wikipedia sentences about the concept. $S_N$: 300 neutral Wikipedia sentences.
- $V^*$: the unique non-special token ids in $S_C \cup S_N$. The model factorizes only these rows of $E$,
  which is cheaper and keeps the factorization focused on the concept. The neutral tokens let Step 3.2
  tell concept features apart from general ones.

In [6]:
dataset = ConceptDataset(concept_name=CONCEPT, neutral_sample_seed=42)
token_ids_all, sample_ids, labels_all = extract_token_ids_sample_ids_and_labels(dataset, act_generator)

special = get_special_token_ids(tl_model)
vstar_ids = sorted({int(t) for t in token_ids_all.tolist()} - special)

n_concept_sents = sum(lbl == CONCEPT for _, lbl in dataset)
print(f"|S_C| = {n_concept_sents}   |S_N| = {len(dataset) - n_concept_sents}")
print(f"token occurrences = {len(token_ids_all)}  ->  |V*| = {len(vstar_ids)} "
      f"({len(vstar_ids) / VOCAB_SIZE:.2%} of the vocabulary)")

Extracting token IDs: 100%|██████████| 120/120 [00:00<00:00, 943.14it/s]

|S_C| = 300   |S_N| = 300
token occurrences = 18611  ->  |V*| = 4780 (1.87% of the vocabulary)

### 3.1.c Build the data matrix $A = E_{V^*}^\top$

Each column of $A$ is one token's embedding.

In [7]:
E_vstar = E.index_select(0, torch.tensor(vstar_ids, device=E.device)).detach().float()  # (|V*|, d)
A = E_vstar.T.contiguous().to(DEVICE)                                                      # (d, |V*|)

print(f"A: {tuple(A.shape)}  (d x |V*|)")
K_BUDGET, M_MIN, M_MAX = budgets(len(vstar_ids), CFG)
if CFG.method == "fixed":
    print(f"{CFG.method}: every feature keeps ceil(s*|V*|) = {math.ceil(SPARSITY * len(vstar_ids))} tokens (K = {K_BUDGET})")
else:
    print(f"{CFG.method}: K = ceil(s*|V*|)*k = {K_BUDGET} nonzeros in total, widths in [{M_MIN}, {M_MAX}] "
          f"(mean {K_BUDGET / RANK:.1f} per feature)")

A: (2304, 4780)  (d x |V*|)
m1: K = ceil(s*|V*|)*k = 4800 nonzeros in total, widths in [10, 239] (mean 48.0 per feature)

### 3.1.c′ Background whitening and target sharpening

Instructions steps 1–4, in the row convention of the notebook (rows are tokens; `sharpen.py`):

$$U = (E_{V^*} - \mathbf 1\boldsymbol\mu_B^\top)\,W,\quad W = Q(\Lambda+\epsilon I)^{-1/2}Q^\top;\qquad
S_\eta = (1-\eta)\,\tfrac1m U_C^\top U_C + \eta I = P\,\mathrm{diag}(g)\,P^\top;\qquad X = U\,S_\eta^{\gamma/2}$$

1. **Background** ($\boldsymbol\mu_B$, $Q$, $\Lambda$ of $\Sigma_B$) is loaded from `WH_DIR/bg_<BACKGROUND>_stats.pt`. It was computed once per
   model, in the same space as `E` (TL `W_E`: Gemma rows already × $\sqrt d$; Llama unscaled). $\epsilon$ = `EPS_REL` × mean($\Lambda$).
   Check: $W\Sigma_B W = Q\,\mathrm{diag}\big(\lambda/(\lambda+\epsilon)\big)Q^\top \approx I$, except along the smallest
   eigenvalues, which $\epsilon$ deliberately damps.
2. **Whitening** centres on $\boldsymbol\mu_B$ (not on the mean of $V^*$), so the concept's shift away from the background stays in the data.
3. **Target**: the token ids of the concept's Wikipedia page (`WH_DIR/targets/<concept>.json`, key `TARGET`), whitened with the
   same $W$. The second moment is taken around 0, so it includes that shift. $g_j$ are **enrichment ratios** ($g_j > 1$: the target
   varies more than the background along $\mathbf p_j$); $\eta$ = `ETA` puts a floor under the directions the target does not use.
4. **Sharpening** with $S_\eta^{\gamma/2}$ applies one fixed map to every row of $V^*$, concept and neutral alike. `GAMMA = 0` skips it.

The combined map is `T` (`Transform`): `T.forward(rows)` $= (\text{rows}-\boldsymbol\mu_B)\,M$ with $M$ = `T.matrix` $= W S_\eta^{\gamma/2}$, and
`T.unmap(z)` $= z\,S_\eta^{-\gamma/2}W^{-1}$ maps directions back. `transform(rows)` is the float32 helper the analysis cells use.

**Diagnostics.** The largest enrichment ratios, and the contrastive-PCA directions $\mathbf p_1,\dots,\mathbf p_5$: the whitened
Wikipedia background token types (`bg_wiki_types.json`) projected on each, top 15 shown (`*` = in the target set). If they are
concept tokens, the signal is there before any factorization. With `GAMMA = 0` the same diagnostics use a $\gamma=1$ sharpener that is
not applied.

From here on `A` is $X^\top$; `E_vstar_orig` (= `E_vstar`) keeps the raw rows and `A0` the raw data matrix.

**Same as the experiments.** This cell is the code path of `experiments/varwidth/prep.py` (`whitening_transform` +
`prepare(matrix="whitened")`): background `bg_wiki_stats.pt` in float64, `BackgroundWhitener(stats, EPS_REL)`, target ids =
`targets/Harry_Potter.json["page"]` within the vocabulary minus special ids, `Sharpener(U_target, ETA, GAMMA)` with GAMMA = 1,
and `A = T.forward(E_vstar).float().T`. `A0 = E_vstar.T` is prep's `"plain"` matrix.

In [8]:
# Instructions steps 1-4: background whitening W, target second moment S_eta, sharpening S_eta^(gamma/2). float64, CPU.
E_vstar_orig = E_vstar                                    # raw rows (Gemma: TL-scaled), for the original fit 3.1.d'
A0 = E_vstar.T.contiguous().to(DEVICE)                    # (d, |V*|) raw

# ---- step 1: background statistics (built once per model by experiments/whitening) ----
BG_PATH = WH_DIR / f"bg_{BACKGROUND}_stats.pt"
TARGETS_PATH = WH_DIR / "targets" / f"{concept_slug}.json"
for _p, _what in [(BG_PATH, f"background statistics ({BACKGROUND})"), (TARGETS_PATH, f"target token ids for {CONCEPT!r}")]:
    if not _p.exists():
        raise FileNotFoundError(f"{_p} is missing: the {_what} must be built first (experiments/whitening)")
stats_bg = torch.load(BG_PATH, map_location="cpu")
missing_keys = {"mu", "lam", "Q"} - set(stats_bg)
assert not missing_keys, f"{BG_PATH} lacks {missing_keys}"
assert stats_bg["Q"].shape == (D_MODEL, D_MODEL), f"{BG_PATH}: Q is {tuple(stats_bg['Q'].shape)}, expected d = {D_MODEL}"
stats_bg = {k: (v.double() if torch.is_tensor(v) else v) for k, v in stats_bg.items()}
bw = BackgroundWhitener(stats_bg, EPS_REL)

lam_bg = stats_bg["lam"].clamp_min(0)
lam_desc = lam_bg.sort(descending=True).values
shrink = lam_desc / (lam_desc + bw.eps)                   # eigenvalues of W Sigma_B W
n95 = math.ceil(0.95 * len(lam_desc))
print(f"background {BACKGROUND}: n = {stats_bg.get('n', '?')} types, d = {D_MODEL}, eps = {EPS_REL:g} x mean(lam) = {bw.eps:.3e}")
print(f"W Sigma_B W ~ I: max |lam/(lam+eps) - 1| over the top 95% of directions = {(shrink[:n95] - 1).abs().max():.3e}, "
      f"overall = {(shrink - 1).abs().max():.3e} (the smallest eigenvalues are damped by eps on purpose)")
print(f"cond(Sigma_B) = {(lam_desc[0] / lam_desc[-1]).item() if lam_desc[-1] > 0 else float('inf'):.3e}   "
      f"cond(Sigma_B + eps I) = {((lam_desc[0] + bw.eps) / (lam_desc[-1] + bw.eps)).item():.3e}")

# ---- step 3: target rows, whitened ----
targets = json.loads(TARGETS_PATH.read_text())
assert TARGET in targets, f"{TARGETS_PATH} has keys {list(targets)}, not {TARGET!r}"
target_ids = sorted({int(t) for t in targets[TARGET] if 0 <= int(t) < VOCAB_SIZE} - set(special))
assert target_ids, f"{TARGETS_PATH}[{TARGET!r}] has no usable token ids"
E_target = E.index_select(0, torch.tensor(target_ids, device=E.device)).detach().double().cpu()   # (m, d), same space as E_vstar
U_target = bw.whiten(E_target)                                                                     # (m, d)
target_set, vstar_set = set(target_ids), set(vstar_ids)
_codes31 = build_token_label_codes(CONCEPT, dataset, tokenizer)
tc_ids = {t for t in vstar_ids if _codes31.get(t, 0) == 1}                                         # T_C (concept-only)
print(f"|target| = {len(target_ids)} ({TARGET})   in V*: {len(target_set & vstar_set)} / {len(vstar_ids)}   "
      f"concept-only T_C covered: {len(target_set & tc_ids)} / {len(tc_ids)}")

# ---- step 4: sharpening; T = whitening (+ sharpening) ----
sh = Sharpener(U_target, ETA, GAMMA) if GAMMA > 0 else None
sh_diag = sh if sh is not None else Sharpener(U_target, ETA, 1.0)   # gamma = 0: diagnostics only, never applied
T = Transform(bw, sh)


def transform(rows: torch.Tensor) -> torch.Tensor:
    """Rows (n, d) in the original (TL) space -> X-space: (rows - mu_B) W S_eta^(gamma/2), float32."""
    return T.forward(rows.detach().cpu()).float()


E_X = transform(E_vstar)                                  # (|V*|, d)
E_vstar_X = E_X                                           # all analysis cells use it
A = E_X.T.contiguous().to(DEVICE)                         # (d, |V*|): 3.1.d fits on this
m_tilde = U_target.mean(0)                                # whitened target mean (the whitened shift Delta)
m_X = m_tilde if sh is None else m_tilde @ sh.Sp          # its image in X-space (= mean of transform(E_target))

# ---- checks ----
I_d = torch.eye(D_MODEL, dtype=torch.float64)
T_inv = bw.W_inv if sh is None else sh.Sm @ bw.W_inv      # row form: z = z~ @ T_inv
print(f"inverse: max |T.matrix @ (Sm @ W_inv) - I| = {(T.matrix @ T_inv - I_d).abs().max():.2e}")
print(f"row norms: raw mean {E_vstar.norm(dim=1).mean():.3f}   X-space mean {E_X.norm(dim=1).mean():.3f}   "
      f"cond(S_eta) = {(sh_diag.g[0] / sh_diag.g[-1]).item():.3e}   cond(T.matrix) = {torch.linalg.cond(T.matrix).item():.3e}")
del I_d

# ---- diagnostics: enrichment ratios ----
g_top = sh_diag.g[:10].tolist()
print(f"\nenrichment ratios g (eta = {ETA:g}; directions the target does not use sit at g = eta): top 10 = {', '.join(f'{v:.2f}' for v in g_top)}")
print(f"directions with g > 1: {int((sh_diag.g > 1).sum())} / {D_MODEL}   g > 2: {int((sh_diag.g > 2).sum())}   "
      f"stretch range applied: g^(gamma/2) in [{sh_diag.g[-1].item() ** (GAMMA / 2):.3f}, {sh_diag.g[0].item() ** (GAMMA / 2):.3f}]")

# ---- diagnostics: contrastive PCA on the whitened Wikipedia background types ----
N_CPCA, N_CPCA_TOK = 5, 15
WIKI_TYPES_PATH = WH_DIR / "bg_wiki_types.json"
if WIKI_TYPES_PATH.exists():
    wiki_ids = [int(t) for t in json.loads(WIKI_TYPES_PATH.read_text()) if 0 <= int(t) < VOCAB_SIZE]
    P5 = sh_diag.P[:, :N_CPCA]                                         # (d, 5)
    signs = torch.sign(m_tilde @ P5)                                   # orient each p_j towards the target mean
    signs[signs == 0] = 1.0
    M5 = bw.W @ (P5 * signs)                                           # whiten + project in one (d, 5) map
    scores = torch.cat([(E.index_select(0, torch.tensor(wiki_ids[i:i + 20_000], device=E.device)).detach().double().cpu()
                         - bw.mu) @ M5 for i in range(0, len(wiki_ids), 20_000)])   # (N_wiki, 5)
    cpca = {}
    for j in range(N_CPCA):
        top = torch.argsort(scores[:, j], descending=True)[:N_CPCA_TOK].tolist()
        toks = tokenizer.convert_ids_to_tokens([wiki_ids[i] for i in top])
        cpca[f"p{j + 1} (g={sh_diag.g[j]:.2f})"] = [f"{t}{' *' if wiki_ids[i] in target_set else ''}  {scores[i, j]:.2f}"
                                                   for t, i in zip(toks, top)]
    hit = {k: sum(s.split("  ")[0].endswith(" *") for s in v) for k, v in cpca.items()}
    print(f"\ncPCA: top {N_CPCA_TOK} of {len(wiki_ids)} whitened Wikipedia types on p_1..p_{N_CPCA} "
          f"(* = in the target set; per direction: {hit})")
    cpca_df = pd.DataFrame(cpca)
    cpca_df.index += 1
    display(cpca_df)
    del scores
else:
    print(f"\n{WIKI_TYPES_PATH} not found: cPCA diagnostic skipped")

print(f"\nA (transformed): {tuple(A.shape)}   A0 (raw): {tuple(A0.shape)}")

background wiki: n = 107472 types, d = 2304, eps = 0.0001 x mean(lam) = 2.712e-04
W Sigma_B W ~ I: max |lam/(lam+eps) - 1| over the top 95% of directions = 3.525e-04, overall = 2.512e-02 (the smallest eigenvalues are damped by eps on purpose)
cond(Sigma_B) = 3.314e+04   cond(Sigma_B + eps I) = 3.231e+04
|target| = 3124 (page)   in V*: 2592 / 4780   concept-only T_C covered: 1832 / 1870
inverse: max |T.matrix @ (Sm @ W_inv) - I| = 2.50e-14
row norms: raw mean 81.424   X-space mean 61.443   cond(S_eta) = 2.394e+02   cond(T.matrix) = 3.805e+02

enrichment ratios g (eta = 0.05; directions the target does not use sit at g = eta): top 10 = 14.20, 9.84, 8.65, 7.86, 7.74, 7.12, 6.44, 6.18, 5.94, 5.67
directions with g > 1: 892 / 2304   g > 2: 367   stretch range applied: g^(gamma/2) in [0.244, 3.768]

experiments/whitening/data/gemma/bg_wiki_types.json not found: cPCA diagnostic skipped

A (transformed): (2304, 4780)   A0 (raw): (2304, 4780)

### 3.1.d Fit variable-width sparse MF (`fit_varwidth`, variant `m1`)

The shared loop of `experiments/varwidth/core.py`, one iteration ($\lambda$ = `CFG.ridge`):

$$Z \leftarrow A Y^\top (Y Y^\top + \lambda I)^{-1},\qquad Y^{dense} \leftarrow (Z^\top Z + \lambda I)^{-1} Z^\top A,\qquad
S \leftarrow \text{Allocate}(Y^{dense}, Z),\qquad Y \leftarrow Y^{dense}\odot S$$

then the rows of $Y$ are scaled to unit norm (the scale goes into $Z$'s columns). Initialization is the paper's $\mathcal N(0,1)$ from a
generator seeded with `SEED`.

**Allocation rule of this variant.** **m1, contribution pooling.** The score of entry $(i,t)$ is its contribution $|Y^{dense}_{i,t}|\,\|\mathbf z_i\|$. One global pool keeps exactly $K = \lceil 0.01\,|V^*|\rceil\cdot k$ entries (the paper's total budget): each feature first keeps its top $m_{min} = \lceil 0.002\,|V^*|\rceil$, the rest go to the highest scores overall, skipping features that reached $m_{max} = \lceil 0.03\,|V^*|\rceil$. Widths therefore differ per feature.

**Refit is off** (`refit=False`): the kept entries keep their dense values, $Y = Y^{dense}\odot S$, as in the paper; there is no
least-squares refit on the support.

**Stopping:** after `patience` = 200 iterations in which the relative error did not improve by ≥ `tol` = $10^{-4}$ **and** the
support churn stayed below 0.005; otherwise at `max_iter` = 20,000. The final iterate is returned.

`A` is $X^\top$ from 3.1.c′. The fit is cached in `RUN_DIR/fit.pt` (the `fit_varwidth` dict, the schema of `results/varwidth/*/fit.pt`,
plus a `meta` key); a cache made with another configuration (or another $V^*$) is moved aside as `*.stale` with the judge and summary
caches. If the experiments' run of the same config exists, the cell prints how far this fit is from it.

In [9]:
# Resume: RUN_DIR/fit.pt is loaded when its configuration matches; otherwise it (and the caches built on it) are moved aside.
from experiments.varwidth.common import run_dir as vw_run_dir

FIT_PATH = RUN_DIR / "fit.pt"
fit_meta = {"model": MODEL_NAME, "matrix": "whitened", "vstar_ids": vstar_ids, "background": BACKGROUND, "target": TARGET,
            "gamma": GAMMA, "eta": ETA, "eps_rel": EPS_REL, "n_target": len(target_ids), "config": CFG.to_dict(), "seed": SEED}
fit = torch.load(FIT_PATH, weights_only=False) if FIT_PATH.exists() else None
if fit is not None and fit.get("meta") != fit_meta:
    print(f"{FIT_PATH} was made with another configuration: re-fitting")
    invalidate(RUN_DIR, ["fit.pt", "judge.json", "summary.json"])
    fit = None
if fit is not None:
    print(f"loaded {FIT_PATH}")
else:
    fit = fit_varwidth(A, CFG, seed=SEED, device=DEVICE)
    fit["meta"] = fit_meta
    torch.save(fit, FIT_PATH)

Z = fit["Z"].float().cpu()      # (d, k)      X-space features z~_i (columns)
Y = fit["Y"].float().cpu()      # (k, |V*|)   sparse coefficients, variable width per row
widths = (Y != 0).sum(1)        # (k,)        tokens per feature
ridge_used = CFG.ridge          # fit_varwidth has no ridge back-off; 3.2.g reuses lambda
t_fit = {"elapsed": fit["elapsed"]}
print(f"\nfitted in {t_fit['elapsed']:.1f}s ({fit['n_iter']} iterations, stop: {fit['stop_reason']}, "
      f"lock-in at iteration {fit['lockin_iter']})  Z: {tuple(Z.shape)}  Y: {tuple(Y.shape)}  rel_err={fit['rel_err']:.4f}")

# Same run in the experiments (python -m experiments.varwidth.run ...): results/varwidth/<concept>/<tag>/seed<N>/fit.pt
EXP_FIT_PATH = vw_run_dir(CONCEPT, CFG.tag(), SEED) / "fit.pt"
if EXP_FIT_PATH.exists() and not SMOKE:
    _exp = torch.load(EXP_FIT_PATH, weights_only=False)
    print(f"experiments' fit {EXP_FIT_PATH}: rel_err={_exp['rel_err']:.4f}  n_iter={_exp['n_iter']}  "
          f"max|dZ|={(Z - _exp['Z'].float()).abs().max():.2e}  max|dY|={(Y - _exp['Y'].float()).abs().max():.2e}  "
          f"same supports: {torch.equal(Y != 0, _exp['Y'] != 0)}")
    del _exp
else:
    print(f"(no experiments' fit at {EXP_FIT_PATH} to compare with)")

fitted in 45.1s (436 iterations, stop: converged, lock-in at iteration 39)  Z: (2304, 100)  Y: (100, 4780)  rel_err=0.8510
experiments' fit /home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj/results/varwidth/Harry_Potter/m1_refit-False/seed42/fit.pt: rel_err=0.8510  n_iter=436  max|dZ|=6.96e-05  max|dY|=3.28e-07  same supports: True

#### 3.1.d-w Per-feature widths

The width of feature $i$ is the number of tokens with $Y_{i,t}\neq 0$. For `fixed` all widths are equal; for the other variants
the total is $K$ and each width lies in $[m_{min}, m_{max}]$. The widths of the concept features $F_C$ are shown in 3.2.f, after selection.

In [10]:
w = widths.double()
print(f"[{VARIANT}] widths: min={int(widths.min())}  median={int(widths.median())}  mean={w.mean():.1f}  max={int(widths.max())}  "
      f"sum={int(widths.sum())} (K = {K_BUDGET})  bounds [{M_MIN}, {M_MAX}]" + ("  (fixed: bounds unused)" if CFG.method == "fixed" else ""))
print(f"features at the floor: {int((widths == M_MIN).sum())}   at the cap: {int((widths == M_MAX).sum())}   "
      f"quantiles: " + "  ".join(f"q{int(q * 100)}={w.quantile(q):.0f}" for q in (0.1, 0.25, 0.5, 0.75, 0.9)))
_order = torch.sort(widths, descending=True, stable=True).indices.tolist()
print("widest 10 :", ", ".join(f"{f}:{int(widths[f])}" for f in _order[:10]))
print("narrowest 10:", ", ".join(f"{f}:{int(widths[f])}" for f in _order[::-1][:10]))
if widths.min() < widths.max():
    print("\nhistogram of widths:")
    print(pd.cut(widths.numpy(), bins=min(15, int(widths.max() - widths.min()) + 1)).value_counts().sort_index().to_string())

[m1] widths: min=10  median=29  mean=48.0  max=239  sum=4800 (K = 4800)  bounds [10, 239]
features at the floor: 3   at the cap: 2   quantiles: q10=14  q25=22  q50=30  q75=48  q90=106
widest 10 : 56:239, 66:239, 33:221, 86:220, 97:191, 82:171, 72:164, 95:123, 49:121, 93:117
narrowest 10: 84:10, 36:10, 27:10, 71:11, 60:11, 39:11, 65:12, 47:12, 44:12, 29:12

histogram of widths:
(9.771, 25.267]       45
(25.267, 40.533]      22
(40.533, 55.8]        15
(55.8, 71.067]         1
(71.067, 86.333]       3
(86.333, 101.6]        2
(101.6, 116.867]       2
(116.867, 132.133]     3
(132.133, 147.4]       0
(147.4, 162.667]       0
(162.667, 177.933]     2
(177.933, 193.2]       1
(193.2, 208.467]       0
(208.467, 223.733]     2
(223.733, 239.0]       2

### 3.1.d′ Reference fit on the original (untransformed) matrix

The **same method and config** (`CFG`, variant `m1`) and seed, `fit_varwidth(A0, CFG, seed=SEED)`, on the raw $A_0 = E_{V^*}^\top$
(prep's `"plain"` matrix; the experiments' `<tag>_plain` runs). `Z0` and `Y0` are used only for comparison: 3.1.e/f (errors),
3.2.e′ (the raw fit's $\rho\ge\tau$ candidates, **no Gemini calls**) and 3.2.w (feature matching). Cached in `RUN_DIR/fit0.pt`.

In [11]:
FIT0_PATH = RUN_DIR / "fit0.pt"
fit0_meta = {"model": MODEL_NAME, "matrix": "plain", "vstar_ids": vstar_ids, "config": CFG.to_dict(), "seed": SEED}
fit0 = torch.load(FIT0_PATH, weights_only=False) if FIT0_PATH.exists() else None
if fit0 is not None and fit0.get("meta") != fit0_meta:
    print(f"{FIT0_PATH} was made with another configuration: re-fitting")
    invalidate(RUN_DIR, ["fit0.pt"])
    fit0 = None
if fit0 is not None:
    print(f"loaded {FIT0_PATH}")
else:
    fit0 = fit_varwidth(A0, CFG, seed=SEED, device=DEVICE)
    fit0["meta"] = fit0_meta
    torch.save(fit0, FIT0_PATH)

Z0 = fit0["Z"].float().cpu()    # (d, k)      raw-space features
Y0 = fit0["Y"].float().cpu()    # (k, |V*|)   sparse coefficients
widths0 = (Y0 != 0).sum(1)      # (k,)
t_fit0 = {"elapsed": fit0["elapsed"]}
print(f"\nfitted in {t_fit0['elapsed']:.1f}s ({fit0['n_iter']} iterations, stop: {fit0['stop_reason']})  "
      f"Z0: {tuple(Z0.shape)}  Y0: {tuple(Y0.shape)}  rel_err={fit0['rel_err']:.4f}")
print(f"widths0: min={int(widths0.min())}  median={int(widths0.median())}  max={int(widths0.max())}  sum={int(widths0.sum())}")

EXP_FIT0_PATH = vw_run_dir(CONCEPT, CFG.tag() + "_plain", SEED) / "fit.pt"
if EXP_FIT0_PATH.exists() and not SMOKE:
    _exp = torch.load(EXP_FIT0_PATH, weights_only=False)
    print(f"experiments' fit {EXP_FIT0_PATH}: rel_err={_exp['rel_err']:.4f}  max|dY0|={(Y0 - _exp['Y'].float()).abs().max():.2e}  "
          f"same supports: {torch.equal(Y0 != 0, _exp['Y'] != 0)}")
    del _exp

fitted in 32.1s (312 iterations, stop: converged)  Z0: (2304, 100)  Y0: (100, 4780)  rel_err=0.8985
widths0: min=10  median=15  max=239  sum=4800
experiments' fit /home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj/results/varwidth/Harry_Potter/m1_refit-False_plain/seed42/fit.pt: rel_err=0.8985  max|dY0|=4.92e-07  same supports: True

### 3.1.e Check the factorization

Reconstruction quality and sparsity. The features use $K$ tokens in total: exactly $\lceil s|V^*|\rceil$ each for `fixed`,
otherwise between $m_{min}$ and $m_{max}$. Tokens that no feature covers are left as pure reconstruction error $\boldsymbol\varepsilon_t$.

Both fits are reported, each against its own data matrix. The two errors are not comparable in absolute terms: whitening
flattens the spectrum, so the transformed error is higher for any rank-$k$ model (the SVD baseline in 3.1.f shows by how much).

The second cell is the optional check of Instructions step 6: $|\cos(\tilde{\mathbf z}_i, \tilde{\mathbf m})|$ between each fitted factor
and the target mean in X-space ($\tilde{\mathbf m} = $ `m_X`). Concept factors should be among the highest; low values flag generic factors.

In [12]:
A_cpu, A0_cpu = A.cpu(), A0.cpu()
rel_err = (torch.norm(A_cpu - Z @ Y) / torch.norm(A_cpu)).item()        # transformed fit, X-space
rel_err0 = (torch.norm(A0_cpu - Z0 @ Y0) / torch.norm(A0_cpu)).item()   # original fit, raw space
nz = Y.abs() > 0
nz0 = Y0.abs() > 0

for name, err, mask in [("transformed", rel_err, nz), ("original", rel_err0, nz0)]:
    tokens_per_feature, features_per_token = mask.sum(1), mask.sum(0)
    print(f"[{name}] relative reconstruction error ||A - ZY||_F / ||A||_F = {err:.4f}")
    print(f"[{name}] tokens per feature : min={tokens_per_feature.min().item()}  median={int(tokens_per_feature.median())}  "
          f"max={tokens_per_feature.max().item()}  total={int(tokens_per_feature.sum())}")
    print(f"[{name}] features per token : mean={features_per_token.float().mean():.2f}  "
          f"max={features_per_token.max().item()}  uncovered tokens={int((features_per_token == 0).sum())}\n")

[transformed] relative reconstruction error ||A - ZY||_F / ||A||_F = 0.8510
[transformed] tokens per feature : min=10  median=29  max=239  total=4800
[transformed] features per token : mean=1.00  max=10  uncovered tokens=2024

[original] relative reconstruction error ||A - ZY||_F / ||A||_F = 0.8984
[original] tokens per feature : min=10  median=15  max=239  total=4800
[original] features per token : mean=1.00  max=4  uncovered tokens=1156

In [13]:
# Instructions step 6 (optional check): |cos| of each X-space factor with the target mean m_X.
cos_m = F.cosine_similarity(Z.double(), m_X.unsqueeze(1), dim=0).abs()       # (k,)
cos_m_order = torch.argsort(cos_m, descending=True).tolist()
print(f"|cos(z~_i, m_X)|: median={cos_m.median():.3f}  max={cos_m.max():.3f}  "
      f"(random-direction scale ~ {math.sqrt(2 / (math.pi * D_MODEL)):.3f})")
cos_m_df = pd.DataFrame({
    "feature": cos_m_order[:10],
    "|cos(z~, m_X)|": cos_m[cos_m_order[:10]].numpy(),
    "top tokens": [", ".join(tokenizer.convert_ids_to_tokens(
        [vstar_ids[j] for j in torch.argsort(Y[f].abs(), descending=True)[:8].tolist()])) for f in cos_m_order[:10]],
})
cos_m_df

|cos(z~_i, m_X)|: median=0.160  max=0.560  (random-direction scale ~ 0.017)

,feature,"|cos(z~, m_X)|",top tokens
0,86,0.559852,"▁high, ▁great, ▁big, ▁major, ▁important, ▁strong, ▁large, ▁real"
1,66,0.558904,"▁question, ▁site, ▁issue, ▁area, ▁process, ▁line, ▁story, ▁section"
2,56,0.460858,"▁created, ▁presented, ▁made, ▁designed, ▁described, ▁produced, ▁found, ▁released"
3,15,0.456191,"▁a, ▁the, ▁an, ▁its, ▁their, ▁his, the, ▁another"
4,82,0.432721,"▁take, ▁remain, ▁stay, ▁go, ▁have, ▁serve, ▁receive, ▁continue"
5,97,0.418283,"▁topics, ▁themes, ▁stories, ▁items, ▁elements, ▁issues, ▁scenes, ▁aspects"
6,49,0.412397,"▁speaking, ▁coming, ▁saying, ▁being, ▁talking, ▁taking, ▁showing, ▁seeing"
7,95,0.411722,"▁within, ▁in, ▁during, ▁with, ▁among, ▁for, ▁at, ▁from"
8,48,0.387319,"▁were, ▁could, ▁was, ▁would, ▁might, ▁did, ▁may, ▁had"
9,64,0.353578,"▁this, ▁these, These, This, ▁those, ▁the, the, The"

In [14]:
print(Z.size())
print(Y.size())
print(RANK)

torch.Size([2304, 100])
torch.Size([100, 4780])
100

### 3.1.f Baseline: truncated SVD with the same $k$

The rank-$k$ truncated SVD $A_k = U_k \Sigma_k V_k^\top$ is the best possible rank-$k$ approximation
(Eckart–Young theorem), so no rank-$k$ factorization can have a lower error, including Sparse MF.
The gap between the two errors is what the sparsity of $Y$ costs in reconstruction.

In [15]:
for name, A_mat, err, mask, Z_mat in [("transformed", A_cpu, rel_err, nz, Z), ("original", A0_cpu, rel_err0, nz0, Z0)]:
    U, S, Vh = torch.linalg.svd(A_mat, full_matrices=False)
    A_svd = U[:, :RANK] @ torch.diag(S[:RANK]) @ Vh[:RANK]
    svd_rel_err = (torch.norm(A_mat - A_svd) / torch.norm(A_mat)).item()

    svd_nnz = U[:, :RANK].numel() + RANK + Vh[:RANK].numel()
    smf_nnz = Z_mat.numel() + int(mask.sum())
    print(f"[{name}] rank-{RANK} truncated SVD : relative error = {svd_rel_err:.4f}   (parameters: {svd_nnz:,})")
    print(f"[{name}] rank-{RANK} Sparse MF     : relative error = {err:.4f}   (nonzero parameters: {smf_nnz:,})")

    # Smallest SVD rank whose error is no worse than Sparse MF's.
    tail = torch.sqrt(torch.flip(torch.cumsum(torch.flip(S ** 2, [0]), 0), [0]) / (S ** 2).sum())
    matching_rank = int((tail <= err).nonzero()[0]) if (tail <= err).any() else len(S)
    print(f"[{name}] SVD reaches the Sparse MF error ({err:.4f}) at rank {matching_rank}\n")
del U, S, Vh, A_svd

[transformed] rank-100 truncated SVD : relative error = 0.7917   (parameters: 708,500)
[transformed] rank-100 Sparse MF     : relative error = 0.8510   (nonzero parameters: 235,200)
[transformed] SVD reaches the Sparse MF error (0.8510) at rank 53

[original] rank-100 truncated SVD : relative error = 0.8219   (parameters: 708,500)
[original] rank-100 Sparse MF     : relative error = 0.8984   (nonzero parameters: 235,200)
[original] SVD reaches the Sparse MF error (0.8984) at rank 12

---
# Step 3.2: Identifying concept-related features

Most of the $k$ features are general (punctuation, function words, and so on). The selection runs in two filters:

1. **Mass ratio** $\rho_i$: is feature $i$ used mostly by concept tokens rather than neutral tokens? Keep the feature if $\rho_i \ge \tau = 2.0$.
2. **LLM judge** (Gemini, two stages): describe the feature's tokens *without* seeing the concept name,
   then ask whether that description is the concept. Keep the feature if `is_member` is true and confidence ≥ 0.85.

The features that pass both filters form $F_C$.

### 3.2.a Label every token in $V^*$

$\ell_t \in$ {concept, neutral, both}, depending on whether $t$ appears in $S_C$ only, $S_N$ only, or both.
Codes: `1` = concept, `0` = neutral, `2` = both.

In [16]:
token_to_code = build_token_label_codes(CONCEPT, dataset, tokenizer)
codes = np.array([token_to_code.get(t, 0) for t in vstar_ids])

print(f"T_C (concept-only) = {(codes == 1).sum()}   T_N (neutral-only) = {(codes == 0).sum()}   "
      f"both = {(codes == 2).sum()}")

T_C (concept-only) = 1870   T_N (neutral-only) = 2229   both = 681

### 3.2.b Score features by mass ratio and keep $\rho_i \ge \tau$

As implemented in `compute_embedding_stats` (column `ratio_abs`):

$$\rho_i = \frac{\operatorname{mean}_{t\in T_C} |Y_{i,t}|}{\operatorname{mean}_{t\in T_N} |Y_{i,t}|}$$

Tokens labeled *both* are excluded from the ratio. The threshold sweep below is the per-concept view of
Figure 6 in the paper.

In [17]:
stats = compute_embedding_stats(Y.T, vstar_ids, token_to_code, CONCEPT).sort_values("ratio_abs", ascending=False)

for thr in [1.0, 1.25, 1.5, 1.75, 2.0, 2.25]:
    print(f"rho >= {thr:<4}: {(stats['ratio_abs'] >= thr).sum():3d} / {RANK} features")

candidates = stats[stats["ratio_abs"] >= TAU]
print(f"\n{len(candidates)} candidate features pass tau = {TAU}")
candidates[["feature", "ratio_abs", "mean_abs_concept", "mean_abs_neutral", "num_concept", "num_neutral", "num_both"]]

rho >= 1.0 :  81 / 100 features
rho >= 1.25:  78 / 100 features
rho >= 1.5 :  74 / 100 features
rho >= 1.75:  67 / 100 features
rho >= 2.0 :  63 / 100 features
rho >= 2.25:  57 / 100 features

63 candidate features pass tau = 2.0

,feature,ratio_abs,mean_abs_concept,mean_abs_neutral,num_concept,num_neutral,num_both
46,46,129.348945,0.003137,0.000024,44,1,3
88,88,53.965477,0.002714,0.000050,49,2,4
71,71,44.848994,0.001346,0.000030,9,1,1
44,44,34.419179,0.001133,0.000033,10,1,1
47,47,28.225249,0.000981,0.000035,9,1,2
...,...,...,...,...,...,...,...
1,1,2.063697,0.001414,0.000685,18,12,13
42,42,2.038758,0.001076,0.000528,9,7,1
67,67,2.035762,0.000838,0.000411,10,7,3
86,86,2.020338,0.003426,0.001696,102,65,53
66,66,2.014319,0.003418,0.001697,103,68,68

### 3.2.c Collect the tokens the judge will see

For each candidate, the code takes the tokens with nonzero $Y_{i,t}$, sorted by $|Y_{i,t}|$, and keeps the top 20.
The paper text says "concept-labeled tokens", but the released code sends the top activating tokens
whatever their label. This notebook follows the code. The `labels` column shows each token's label.

In [18]:
token_label_map = {tid: "both" if c == 2 else CONCEPT if c == 1 else "Neutral" for tid, c in token_to_code.items()}
feature_rows = collect_feature_rows_for_embeddings(
    Y.T, vstar_ids, token_label_map, tl_model, _safe_model_name(MODEL_NAME), CONCEPT, RANK,
)
feat_tokens = pd.DataFrame(feature_rows).set_index("feature")[["activating_tokens", "labels"]]

cand = candidates[["feature", "ratio_abs"]].join(feat_tokens, on="feature").reset_index(drop=True)
if SMOKE:
    cand = cand.head(3)  # smoke: judge only the 3 highest-rho candidates
from ember.judge_words import desc_sys_prompt, judge_cache_name, judge_items, token_word_counts

DESC_SYS = desc_sys_prompt(JUDGE_FORMAT, multilingual=False)   # = TOKENS_DESC_SYS for "tokens"
jw_counts = token_word_counts(tokenizer, [s for s, _ in dataset]) if JUDGE_FORMAT == "words" else {}


def judge_input(Ymat: torch.Tensor, f: int, activating_tokens) -> list:
    """What Stage 1 sees for feature f of Ymat: "tokens" = the top activating tokens (as before); "words" = token → source words."""
    if JUDGE_FORMAT == "tokens":
        return list(activating_tokens[:TOP_K_TOKENS])
    mags = Ymat[f].abs()
    top = torch.argsort(mags, descending=True)[:TOP_K_TOKENS]
    top = top[mags[top] > 0].tolist()
    return judge_items([vstar_ids[j] for j in top], lambda t: tokenizer.decode([t]), jw_counts, JUDGE_FORMAT,
                       multilingual=False)


cand["judge_tokens"] = [judge_input(Y, int(f), toks) for f, toks in zip(cand["feature"], cand["activating_tokens"])]
cand[["feature", "ratio_abs", "judge_tokens"]]

,feature,ratio_abs,judge_tokens
0,46,129.348945,"[ffindor, therin, umbledore, Dumbledore, Weasley, Malfoy, Hogwarts, Rowling, Potter, Hermione, Hermione, demort, Voldemort, Potter, Harry, Snape, Harry, magic, Magic, magic]"
1,88,53.965477,"[ magic, magic, Magic, Magic, magical, magical, Magical, wizard, wizards, witchcraft, Wizard, wizard, Wizards, witch, witches, Witch, Sorcerer, fantasy, fairytale, wiz]"
2,71,44.848994,"[ entry, enter, enters, entering, entries, into, foray, nter, Entertainment, infiltr, joining]"
3,44,34.419179,"[ read, reads, Read, reading, learn, literacy, listened, ride, write, learns, czy, rides]"
4,47,28.225249,"[ world, World, World, worlds, universe, worldwide, internationally, International, word, Universal, nation, earth]"
...,...,...,...
58,1,2.063697,"[ previous, previously, originally, original, earlier, last, initially, first, initial, Originally, formerly, former, old, First, Last, past, precedent, already, inaugural, new]"
59,42,2.038758,"[ white, white, White, White, black, Black, dark, Dark, darker, red, silver, Brown, green, purple, Whit, red, yellowish]"
60,67,2.035762,"[ award, Award, awards, Awards, awarded, Prizes, winner, medal, grant, nominated, confer, nominations, recognition, praise, contest, praised, bery, ceremony, championship, AW]"
61,86,2.020338,"[ high, great, big, major, important, strong, large, real, long, main, significant, full, good, primary, high, key, fundamental, principal, general, new]"
62,66,2.014319,"[ question, site, issue, area, process, line, story, section, point, style, type, group, event, order, idea, course, category, place, range, pattern]"

### 3.2.d-0 Rate-limited Gemini client

The free tier allows **15 requests per minute per model**. Stage 1 and Stage 2 make one request per
candidate each, so 2 × (number of candidates) requests in total. This wrapper does three things:

- spaces requests at least `60 / RPM` seconds apart (with a 10% margin);
- on a per-minute 429, waits the `retry in Ns` delay the server reports, then retries;
- fails immediately on a *daily* quota error, because waiting would not help.

Answers are cached in `descriptions` and `verdicts`. Re-running a stage only queries the features that
are still missing, so a crash never wastes quota you already spent.

In [19]:
import re
import time

GEMINI_RPM = 15


class ThrottledGemini:
    def __init__(self, inner: SimpleGeminiClient, rpm: int = GEMINI_RPM, max_attempts: int = 6):
        inner.max_retries = 1  # retries are handled here, with the server's retry delay
        self.inner = inner
        self.interval = 60.0 / rpm * 1.1
        self.max_attempts = max_attempts
        self._last = 0.0

    def generate(self, prompt: str) -> str:
        for attempt in range(self.max_attempts):
            time.sleep(max(0.0, self._last + self.interval - time.monotonic()))
            self._last = time.monotonic()
            try:
                return self.inner.generate(prompt)
            except RuntimeError as e:
                msg = str(e)
                if "429" not in msg or "PerDay" in msg or attempt == self.max_attempts - 1:
                    raise
                m = re.search(r"retry in ([\d.]+)s", msg)
                time.sleep(float(m.group(1)) + 1 if m else 60)


USE_THROTTLE = False  # billing enabled; set True to go back to free-tier pacing

if USE_THROTTLE:
    client = ThrottledGemini(SimpleGeminiClient(model_name=GEMINI_MODEL))
else:
    client = SimpleGeminiClient(model_name=GEMINI_MODEL)

# Persisted in RUN_DIR/judge.json, saved after every Gemini call, so a restart re-queries nothing.
# 3.1.d moves judge.json aside whenever it re-fits.
JUDGE_PATH = RUN_DIR / judge_cache_name(JUDGE_FORMAT, "tokens")   # judge.json for the original format
_judge = load_json(JUDGE_PATH, {})
descriptions = {int(f): d for f, d in _judge.get("descriptions", {}).items()}
verdicts = {int(f): tuple(v) for f, v in _judge.get("verdicts", {}).items()}


def save_judge() -> None:
    save_json(JUDGE_PATH, {"descriptions": descriptions, "verdicts": verdicts})

print(f"{2 * len(cand)} requests needed, {len(descriptions)} descriptions and {len(verdicts)} verdicts cached; "
      f"throttle={'on' if USE_THROTTLE else 'off'}")

126 requests needed, 0 descriptions and 0 verdicts cached; throttle=off

### 3.2.d LLM judge, stage 1: describe each feature *without* the concept name

Stage 1 never sees the concept name. This avoids confirmation bias, where tokens like *wizard* could
look like "Harry Potter" just because the judge was told the concept.

In [20]:
print("---- Stage 1 prompt ----")
print(TOKENS_DESC_SYS.strip(), "\n\nTokens: {tokens}\nExplanation of feature behavior:")

todo = cand[~cand["feature"].astype(int).isin(descriptions)]
for _, row in tqdm(todo.iterrows(), total=len(todo), desc="Stage 1: describe"):
    descriptions[int(row["feature"])] = get_description(client, row["judge_tokens"], sys_prompt=DESC_SYS)
    save_judge()
cand["description"] = cand["feature"].map(descriptions)
cand[["feature", "ratio_abs", "description"]]

---- Stage 1 prompt ----
You get tokens that represent a single feature vector (with some noise).
Infer the single most specific, cohesive concept shared by the relevant tokens.
Return only one concise sentence. No preface, no list, no caveats.

Example:
Tokens: ['▁tomorrow','▁tonight','▁yesterday','▁today','▁demain']
Explanation of feature behavior: this vector is related to specific dates and times (e.g., today/tomorrow/yesterday).

Tokens: {tokens}
Explanation of feature behavior:

Stage 1: describe: 100%|██████████| 63/63 [00:39<00:00,  1.59it/s]

,feature,ratio_abs,description
0,46,129.348945,"This vector is related to characters, locations, and terminology from the Harry Potter universe."
1,88,53.965477,"This vector activates on words related to magic, sorcery, and fantasy folklore."
2,71,44.848994,"This feature vector represents the concept of entering or going into a space, state, or activity."
3,44,34.419179,"This vector activates for verbs and concepts related to acquiring knowledge, language skills, or literacy activities."
4,47,28.225249,"This feature vector represents the concept of the global earth, international scope, and the broader universe."
...,...,...,...
58,1,2.063697,"This vector represents concepts of prior occurrence, sequence, or historical precedence."
59,42,2.038758,This vector represents color descriptors and chromatic attributes.
60,67,2.035762,"This vector activates for terms related to honors, awards, and competitive recognition."
61,86,2.020338,"These tokens represent the concept of magnitude, importance, or scale."
62,66,2.014319,"This vector represents abstract nouns denoting general categories, classifications, or structural elements."

In [21]:
N_SHOW = 10
LABEL_TAG = {1: "C", 0: "N", 2: "B"}  # concept / neutral / both

for _, row in cand.sort_values("ratio_abs", ascending=False).iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini : {descriptions.get(feat, '<not described yet>')}")
    print("  tokens : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

=== feature 46  width=48  rho=129.35 ===
  Gemini : This vector is related to characters, locations, and terminology from the Harry Potter universe.
  tokens : 'ffindor'[C] 0.36, 'therin'[C] 0.30, 'umbledore'[C] 0.24, '▁Dumbledore'[C] 0.21, '▁Weasley'[C] 0.20, '▁Malfoy'[C] 0.19, '▁Hogwarts'[C] 0.19, '▁Rowling'[C] 0.19, '▁Potter'[C] 0.19, 'Hermione'[C] 0.18

=== feature 88  width=55  rho=53.97 ===
  Gemini : This vector activates on words related to magic, sorcery, and fantasy folklore.
  tokens : '▁magic'[C] 0.36, 'magic'[C] 0.35, 'Magic'[C] 0.34, '▁Magic'[B] 0.33, '▁magical'[C] 0.28, 'magical'[C] 0.26, '▁Magical'[C] 0.23, '▁wizard'[C] 0.18, '▁wizards'[C] 0.17, '▁witchcraft'[C] 0.15

=== feature 71  width=11  rho=44.85 ===
  Gemini : This feature vector represents the concept of entering or going into a space, state, or activity.
  tokens : '▁entry'[C] 0.47, '▁enter'[C] 0.45, '▁enters'[C] 0.43, '▁entering'[C] 0.43, '▁entries'[C] 0.40, '▁into'[B] 0.14, '▁foray'[C] 0.10, 'nter'[C] 0.09, '▁Entertainment'[C] 0.08, '▁infiltr'[C] 0.07

=== feature 44  width=12  rho=34.42 ===
  Gemini : This vector activates for verbs and concepts related to acquiring knowledge, language skills, or literacy activities.
  tokens : '▁read'[C] 0.56, '▁reads'[C] 0.48, '▁Read'[C] 0.47, '▁reading'[B] 0.43, '▁learn'[C] 0.10, '▁literacy'[C] 0.10, '▁listened'[C] 0.09, '▁ride'[C] 0.09, '▁write'[C] 0.08, '▁learns'[C] 0.08

=== feature 47  width=12  rho=28.23 ===
  Gemini : This feature vector represents the concept of the global earth, international scope, and the broader universe.
  tokens : '▁world'[B] 0.50, '▁World'[B] 0.47, 'World'[C] 0.47, '▁worlds'[C] 0.38, '▁universe'[C] 0.22, '▁worldwide'[C] 0.21, '▁internationally'[C] 0.17, '▁International'[C] 0.12, '▁word'[C] 0.12, '▁Universal'[C] 0.08

=== feature 25  width=23  rho=26.38 ===
  Gemini : This feature vector represents words related to contrast, comparison, and alternative choices.
  tokens : '▁rather'[C] 0.59, 'Rather'[C] 0.54, '▁instead'[B] 0.45, '▁than'[B] 0.15, '▁fairly'[C] 0.14, '▁vs'[C] 0.13, '▁somewhat'[C] 0.12, '▁opposed'[C] 0.12, '▁something'[C] 0.10, 'opposed'[N] 0.09

=== feature 29  width=12  rho=23.77 ===
  Gemini : This vector represents third-person masculine singular personal and possessive pronouns.
  tokens : '▁his'[B] 0.38, '▁He'[B] 0.38, 'He'[B] 0.36, '▁he'[B] 0.36, 'His'[C] 0.36, '▁His'[C] 0.35, '▁him'[B] 0.33, '▁himself'[C] 0.29, 'zyński'[N] 0.06, '▁Heli'[C] 0.05

=== feature 96  width=23  rho=21.86 ===
  Gemini : This vector represents the concept of comparison, contrast, and evaluation of differences between entities.
  tokens : '▁compared'[C] 0.39, '▁against'[B] 0.35, '▁Against'[C] 0.33, '▁vs'[C] 0.31, '▁comparing'[C] 0.29, 'Comparing'[C] 0.27, '▁opposed'[C] 0.25, '▁contrast'[C] 0.22, 'opposed'[N] 0.19, 'compar'[C] 0.19

=== feature 68  width=48  rho=16.56 ===
  Gemini : This feature vector represents the concept of books, reading, and literature.
  tokens : '▁book'[B] 0.38, 'book'[C] 0.35, '▁Book'[B] 0.34, '▁books'[C] 0.34, '▁Books'[C] 0.31, '▁novels'[C] 0.19, '▁bookstores'[C] 0.18, '▁novel'[B] 0.18, '▁ebooks'[C] 0.15, '▁Novel'[C] 0.15

=== feature 60  width=11  rho=14.69 ===
  Gemini : This vector represents the concept of completeness or fractional quantity.
  tokens : '▁half'[C] 0.54, 'half'[B] 0.52, '▁Half'[C] 0.50, '▁full'[C] 0.25, 'full'[C] 0.23, '▁partial'[C] 0.19, '▁whole'[B] 0.10, '▁almost'[C] 0.08, '▁complete'[N] 0.08, '▁fifty'[C] 0.08

=== feature 8  width=16  rho=14.25 ===
  Gemini : This vector represents the concept of physical motion and locomotion.
  tokens : '▁go'[C] 0.36, '▁goes'[B] 0.34, 'going'[C] 0.32, 'coming'[C] 0.32, '▁coming'[C] 0.31, '▁Go'[C] 0.30, '▁went'[B] 0.30, 'gone'[C] 0.28, '▁comes'[C] 0.23, '▁came'[N] 0.22

=== feature 32  width=33  rho=12.62 ===
  Gemini : This vector is related to particular iterations, instances, or variants of something.
  tokens : '▁version'[B] 0.42, '▁edition'[B] 0.38, '▁Version'[C] 0.35, '▁editions'[C] 0.33, '▁example'[C] 0.24, '▁instance'[C] 0.23, '▁rendition'[C] 0.22, '▁examples'[C] 0.20, '▁instances'[C] 0.18, '▁copies'[B] 0.17

=== feature 22  width=25  rho=11.99 ===
  Gemini : This feature vector represents the commercial concepts of buying, selling, and market transactions.
  tokens : '▁selling'[C] 0.39, '▁sold'[C] 0.38, 'selling'[C] 0.36, 'sold'[C] 0.35, '▁sale'[C] 0.35, '▁sales'[B] 0.31, 'seller'[C] 0.24, '▁buying'[C] 0.17, '▁purchasing'[C] 0.14, '▁bought'[N] 0.13

=== feature 3  width=34  rho=9.51 ===
  Gemini : This vector represents the concept of discovery, searching, and visual or conceptual finding.
  tokens : '▁find'[C] 0.37, '▁finding'[C] 0.34, '▁Find'[C] 0.32, '▁found'[B] 0.30, '▁discovering'[C] 0.24, '▁see'[B] 0.23, '▁discovers'[C] 0.23, '▁sees'[C] 0.22, '▁seeing'[C] 0.20, '▁discoveries'[N] 0.19

=== feature 50  width=39  rho=9.20 ===
  Gemini : This vector represents the concept of the written word and the practice or profession of writing.
  tokens : '▁writing'[B] 0.33, '▁written'[B] 0.33, 'writing'[C] 0.31, 'written'[C] 0.31, '▁writer'[B] 0.30, '▁writers'[C] 0.29, '▁write'[C] 0.29, '▁wrote'[B] 0.28, '▁author'[C] 0.19, '▁authors'[C] 0.19

=== feature 20  width=14  rho=8.28 ===
  Gemini : This feature vector activates on words representing units of time, temporal intervals, and calendar-related periods.
  tokens : '▁day'[C] 0.51, '▁Day'[C] 0.47, '▁days'[C] 0.37, '▁Days'[C] 0.36, '▁night'[C] 0.29, '▁Night'[C] 0.23, '▁morning'[N] 0.17, '▁date'[B] 0.14, '▁eve'[C] 0.13, '▁hours'[B] 0.13

=== feature 27  width=10  rho=8.03 ===
  Gemini : This vector represents bodily fluids and biological circulation systems.
  tokens : '▁blood'[C] 0.59, 'blood'[C] 0.57, 'Blood'[C] 0.53, '▁plasma'[N] 0.11, '▁circulatory'[N] 0.10, '▁veins'[N] 0.08, 'bread'[C] 0.08, '▁tears'[C] 0.08, '▁soul'[C] 0.07, '▁binary'[C] 0.07

=== feature 12  width=25  rho=7.55 ===
  Gemini : This feature vector represents concepts of similarity, comparison, and resemblance between things.
  tokens : '▁similar'[B] 0.44, '▁same'[B] 0.43, '▁identical'[B] 0.32, 'Similarly'[C] 0.32, '▁like'[B] 0.26, 'Like'[B] 0.23, '▁similarities'[C] 0.23, '▁resemble'[C] 0.22, '▁resembles'[C] 0.22, '▁parallels'[C] 0.16

=== feature 13  width=22  rho=6.99 ===
  Gemini : This feature vector represents common action verbs and their various inflectional forms.
  tokens : '▁make'[B] 0.43, '▁making'[C] 0.42, '▁made'[B] 0.39, '▁makes'[C] 0.39, 'made'[C] 0.37, '▁mak'[C] 0.27, '▁makeup'[N] 0.16, '▁giving'[N] 0.10, 'give'[C] 0.10, '▁gave'[B] 0.09

=== feature 19  width=44  rho=6.35 ===
  Gemini : This vector represents verbs and nouns associated with affection, preference, and psychological states.
  tokens : '▁love'[C] 0.36, '▁loves'[C] 0.32, '▁likes'[C] 0.30, '▁Love'[N] 0.28, 'Love'[C] 0.27, '▁loved'[C] 0.27, '▁like'[B] 0.27, 'Like'[B] 0.22, '▁wants'[C] 0.18, '▁Wants'[C] 0.16

=== feature 52  width=25  rho=6.12 ===
  Gemini : This vector represents quantifying words and universal determiners expressing totality or distribution.
  tokens : '▁every'[C] 0.40, '▁each'[B] 0.39, '▁all'[B] 0.38, 'every'[C] 0.37, 'all'[C] 0.33, 'Each'[B] 0.32, 'All'[B] 0.25, '▁any'[B] 0.15, 'alls'[N] 0.14, '▁ever'[B] 0.11

=== feature 64  width=20  rho=6.08 ===
  Gemini : This feature activates on demonstrative and definite determiners, pronouns, and related deictic words indicating specific entities or contexts.
  tokens : '▁this'[B] 0.52, '▁these'[B] 0.52, 'These'[B] 0.36, 'This'[B] 0.31, '▁those'[C] 0.22, '▁the'[B] 0.21, 'the'[B] 0.14, 'The'[B] 0.14, '▁The'[B] 0.13, '▁that'[B] 0.13

=== feature 93  width=117  rho=5.88 ===
  Gemini : These tokens represent third-person singular present tense action verbs.
  tokens : '▁is'[B] 0.18, '▁has'[B] 0.14, '▁gives'[C] 0.14, '▁comes'[C] 0.14, '▁allows'[C] 0.14, '▁goes'[B] 0.14, '▁takes'[C] 0.14, '▁does'[C] 0.13, '▁involves'[C] 0.13, '▁assumes'[C] 0.13

=== feature 39  width=11  rho=5.72 ===
  Gemini : This feature vector represents the concept of possessing, keeping, or containing something.
  tokens : '▁hold'[B] 0.47, '▁holding'[B] 0.43, '▁holds'[C] 0.41, '▁held'[B] 0.40, '▁holder'[C] 0.33, '▁Holden'[C] 0.23, '▁host'[B] 0.19, '▁hosts'[C] 0.18, '▁hosting'[N] 0.16, 'ghold'[N] 0.10

=== feature 78  width=48  rho=5.66 ===
  Gemini : This feature vector represents the concept of displaying, exhibiting, or visually presenting something.
  tokens : '▁show'[N] 0.33, 'show'[C] 0.31, '▁showing'[C] 0.30, '▁shown'[C] 0.29, '▁showed'[C] 0.28, '▁display'[N] 0.23, '▁displayed'[C] 0.22, '▁displays'[C] 0.21, '▁showcase'[C] 0.19, '▁depicted'[C] 0.15

=== feature 9  width=74  rho=5.61 ===
  Gemini : This vector activates on verbs and terms used to attribute speech, claims, or reports to a source.
  tokens : '▁stated'[C] 0.26, '▁said'[B] 0.25, '▁reported'[C] 0.21, '▁claimed'[C] 0.19, '▁stating'[B] 0.18, '▁saying'[C] 0.18, '▁noted'[B] 0.18, '▁reportedly'[C] 0.17, '▁argues'[C] 0.16, '▁described'[B] 0.15

=== feature 7  width=17  rho=4.96 ===
  Gemini : This vector represents first-, second-, and third-person personal and reflexive pronouns denoting individuals or groups.
  tokens : '▁himself'[C] 0.50, '▁herself'[C] 0.48, '▁themselves'[C] 0.47, '▁myself'[N] 0.34, '▁him'[B] 0.20, '▁own'[B] 0.17, '▁them'[B] 0.14, '▁me'[C] 0.13, '▁self'[C] 0.12, '▁his'[B] 0.12

=== feature 38  width=46  rho=4.79 ===
  Gemini : This feature vector activates on conjunctive and transitional adverbs used to connect clauses or indicate logical contrast and sequence.
  tokens : '▁however'[C] 0.41, '▁nonetheless'[C] 0.32, '▁meanwhile'[C] 0.31, '▁therefore'[B] 0.28, 'However'[B] 0.28, '▁though'[B] 0.23, '▁thus'[B] 0.20, '▁but'[B] 0.19, '▁still'[B] 0.19, 'Yet'[C] 0.18

=== feature 75  width=42  rho=4.46 ===
  Gemini : This vector represents the concept of film and theatrical production, encompassing cast members, crew, and cinematic works.
  tokens : '▁cast'[C] 0.42, '▁casting'[C] 0.34, 'Cast'[C] 0.33, '▁Cast'[N] 0.32, '▁production'[C] 0.22, 'Production'[C] 0.19, '▁productions'[C] 0.18, '▁actors'[B] 0.18, '▁actor'[B] 0.17, '▁producer'[B] 0.15

=== feature 82  width=171  rho=4.26 ===
  Gemini : This vector represents a set of common action verbs expressing various states, processes, and activities.
  tokens : '▁take'[B] 0.13, '▁remain'[C] 0.13, '▁stay'[B] 0.13, '▁go'[C] 0.12, '▁have'[B] 0.12, '▁serve'[C] 0.12, '▁receive'[C] 0.12, '▁continue'[C] 0.12, '▁provide'[C] 0.12, '▁become'[B] 0.12

=== feature 83  width=23  rho=4.04 ===
  Gemini : This vector represents the concept of mortality, death, and lethal acts.
  tokens : '▁death'[B] 0.33, '▁killed'[C] 0.32, '▁died'[B] 0.30, '▁kills'[C] 0.30, '▁killing'[C] 0.29, '▁dies'[C] 0.28, '▁dead'[C] 0.28, '▁Death'[C] 0.27, '▁die'[C] 0.26, '▁murdered'[C] 0.21

=== feature 5  width=31  rho=3.93 ===
  Gemini : This vector represents causal relationships, reasons, and attributions.
  tokens : '▁due'[B] 0.40, 'Due'[C] 0.34, '▁based'[B] 0.33, '▁because'[B] 0.31, 'based'[C] 0.30, 'because'[C] 0.30, 'Because'[N] 0.24, '▁since'[B] 0.21, '▁related'[B] 0.15, 'related'[N] 0.14

=== feature 65  width=12  rho=3.85 ===
  Gemini : This feature represents the concept of pulling, attracting, or rendering physically and conceptually.
  tokens : '▁draw'[C] 0.49, '▁drawn'[C] 0.47, '▁drawing'[C] 0.44, 'Draw'[N] 0.38, '▁attracted'[C] 0.24, '▁attraction'[C] 0.20, '▁Drew'[N] 0.17, '▁appeal'[B] 0.16, '▁attractions'[C] 0.14, '▁appealing'[C] 0.12

=== feature 26  width=54  rho=3.81 ===
  Gemini : This vector represents the concept of human age and developmental stages, encompassing terms for children, youth, and adults.
  tokens : '▁children'[B] 0.27, '▁kids'[C] 0.25, 'Children'[C] 0.22, '▁young'[B] 0.22, '▁kid'[C] 0.22, 'child'[C] 0.21, '▁Child'[B] 0.20, '▁adult'[C] 0.19, '▁adults'[C] 0.19, '▁age'[B] 0.18

=== feature 28  width=31  rho=3.70 ===
  Gemini : This feature vector activates strongly on number words and numerals representing quantities or numerical values.
  tokens : '▁four'[B] 0.31, '▁six'[B] 0.30, '▁five'[B] 0.30, '▁seven'[B] 0.30, '▁eight'[B] 0.29, '▁nine'[C] 0.28, '▁three'[B] 0.27, 'four'[C] 0.26, '▁eleven'[C] 0.24, '▁two'[B] 0.22

=== feature 87  width=35  rho=3.69 ===
  Gemini : This vector represents quantifiers and words denoting quantity, number, or diversity.
  tokens : '▁many'[B] 0.38, 'Many'[C] 0.31, '▁several'[B] 0.30, '▁Many'[C] 0.30, '▁numerous'[N] 0.29, '▁various'[B] 0.28, 'Various'[C] 0.27, '▁few'[C] 0.21, '▁some'[B] 0.20, '▁dozens'[C] 0.18

=== feature 6  width=79  rho=3.67 ===
  Gemini : This vector represents adverbs of frequency, degree, and typicality used to qualify statements and actions.
  tokens : '▁mainly'[C] 0.26, '▁primarily'[B] 0.25, '▁largely'[B] 0.24, '▁generally'[B] 0.24, '▁usually'[N] 0.24, '▁often'[C] 0.22, '▁predominantly'[C] 0.21, '▁essentially'[C] 0.19, 'larg'[C] 0.19, '▁originally'[C] 0.16

=== feature 98  width=25  rho=3.66 ===
  Gemini : This vector represents verbs and related forms associated with inclusion, containment, or comprising elements.
  tokens : '▁include'[B] 0.39, '▁includes'[C] 0.38, '▁including'[B] 0.33, '▁included'[B] 0.31, 'including'[C] 0.30, '▁inclusion'[C] 0.26, '▁contains'[B] 0.21, '▁contain'[C] 0.20, '▁consists'[N] 0.20, '▁consist'[C] 0.19

=== feature 37  width=23  rho=3.61 ===
  Gemini : This feature vector represents components, subdivisions, or individual parts of a whole.
  tokens : '▁part'[B] 0.47, 'part'[C] 0.46, '▁Part'[N] 0.41, '▁parts'[C] 0.39, '▁Parts'[C] 0.33, '▁section'[C] 0.16, '▁sections'[C] 0.15, '▁aspects'[C] 0.10, '▁components'[N] 0.10, '▁segment'[B] 0.09

=== feature 36  width=10  rho=3.50 ===
  Gemini : This feature activates for words related to the opening, closing, or accessibility of objects, spaces, or states.
  tokens : '▁open'[C] 0.52, 'open'[C] 0.49, '▁Open'[N] 0.43, '▁opened'[B] 0.35, '▁opening'[B] 0.30, '▁closed'[C] 0.26, '▁sealed'[C] 0.07, '▁enclosed'[N] 0.07, '▁op'[C] 0.06, '▁free'[C] 0.06

=== feature 97  width=191  rho=3.42 ===
  Gemini : This feature vector represents general plural nouns describing various subjects, elements, or categories of discussion.
  tokens : '▁topics'[C] 0.15, '▁themes'[C] 0.15, '▁stories'[B] 0.14, '▁items'[C] 0.13, '▁elements'[C] 0.13, '▁issues'[C] 0.13, '▁scenes'[C] 0.13, '▁aspects'[C] 0.12, '▁concepts'[C] 0.12, '▁characters'[C] 0.12

=== feature 55  width=38  rho=3.33 ===
  Gemini : This vector represents the concept of temporal sequence and chronological succession.
  tokens : '▁following'[B] 0.38, '▁follow'[C] 0.36, '▁follows'[C] 0.36, '▁followed'[C] 0.34, '▁afterwards'[C] 0.28, '▁after'[B] 0.23, '▁later'[B] 0.20, 'After'[N] 0.18, '▁followers'[C] 0.17, '▁then'[B] 0.17

=== feature 34  width=25  rho=3.15 ===
  Gemini : This vector represents superlative adjectives and adverbs indicating extreme degrees or quantities.
  tokens : '▁most'[B] 0.41, 'most'[C] 0.40, '▁Most'[N] 0.31, '▁best'[B] 0.27, '▁fastest'[C] 0.22, '▁funniest'[C] 0.21, '▁longest'[C] 0.21, 'liest'[C] 0.20, 'tiest'[C] 0.20, 'ariest'[C] 0.20

=== feature 49  width=121  rho=2.97 ===
  Gemini : These tokens represent continuous action or ongoing processes, typically expressed through present participles ending in "-ing".
  tokens : '▁speaking'[C] 0.17, '▁coming'[C] 0.17, '▁saying'[C] 0.17, '▁being'[B] 0.16, '▁talking'[C] 0.15, '▁taking'[C] 0.14, '▁showing'[C] 0.14, '▁seeing'[C] 0.14, '▁stating'[B] 0.13, '▁having'[N] 0.13

=== feature 24  width=21  rho=2.86 ===
  Gemini : This feature vector represents the concept of biological existence and living.
  tokens : '▁living'[B] 0.44, '▁lived'[C] 0.37, '▁live'[B] 0.35, '▁lives'[C] 0.34, 'lived'[N] 0.29, '▁life'[B] 0.27, '▁alive'[C] 0.26, 'life'[C] 0.24, '▁resided'[N] 0.16, '▁resides'[C] 0.16

=== feature 69  width=24  rho=2.85 ===
  Gemini : This vector represents temporal sequencing and the relative timing of events or actions.
  tokens : '▁late'[N] 0.36, '▁early'[B] 0.36, '▁later'[B] 0.35, '▁Later'[C] 0.32, 'late'[N] 0.30, '▁follows'[C] 0.26, '▁follow'[C] 0.26, '▁earlier'[C] 0.25, '▁following'[B] 0.24, '▁followed'[C] 0.20

=== feature 58  width=15  rho=2.79 ===
  Gemini : These tokens function as restrictive or limiting adverbial modifiers that constrain the scope, degree, or emphasis of a statement.
  tokens : '▁just'[B] 0.51, 'Just'[C] 0.42, '▁Just'[N] 0.41, '▁simply'[C] 0.35, '▁merely'[C] 0.35, '▁only'[B] 0.26, '▁Only'[N] 0.19, '▁even'[B] 0.10, '▁simple'[C] 0.10, '▁actually'[C] 0.09

=== feature 90  width=21  rho=2.72 ===
  Gemini : These tokens represent prepositions indicating instrumentality, direction, or agency.
  tokens : '▁by'[B] 0.43, '▁By'[C] 0.41, 'By'[B] 0.40, '▁Through'[C] 0.34, '▁through'[B] 0.34, 'through'[B] 0.32, 'From'[B] 0.14, '▁from'[B] 0.14, 'With'[B] 0.13, '▁with'[B] 0.12

=== feature 91  width=39  rho=2.69 ===
  Gemini : This feature vector represents concepts of addition, differentiation, and alternative or supplementary items.
  tokens : '▁other'[B] 0.49, 'Other'[C] 0.39, '▁others'[B] 0.39, '▁another'[B] 0.28, 'Another'[N] 0.22, '▁more'[B] 0.20, '▁further'[C] 0.19, 'more'[C] 0.17, '▁otherwise'[C] 0.13, '▁also'[B] 0.12

=== feature 59  width=23  rho=2.66 ===
  Gemini : This vector represents concepts related to methods, means, and ways of accomplishing something.
  tokens : 'means'[C] 0.41, '▁way'[B] 0.38, '▁mean'[C] 0.34, '▁ways'[B] 0.32, '▁meaning'[N] 0.31, 'way'[N] 0.25, '▁manner'[C] 0.25, '▁meant'[N] 0.23, '▁reason'[C] 0.19, '▁reasons'[B] 0.18

=== feature 18  width=51  rho=2.63 ===
  Gemini : This vector represents logical negation, exclusion, and quantifiers of duality or totality.
  tokens : '▁no'[B] 0.37, '▁neither'[C] 0.32, '▁not'[B] 0.32, '▁none'[C] 0.30, 'no'[B] 0.28, '▁NO'[N] 0.19, '▁Not'[N] 0.19, '▁never'[C] 0.19, '▁only'[B] 0.17, '▁all'[B] 0.15

=== feature 2  width=29  rho=2.51 ===
  Gemini : This vector represents ordinal numbers and sequential ranking terms.
  tokens : '▁fourth'[B] 0.40, '▁third'[B] 0.39, '▁fifth'[C] 0.38, '▁sixth'[B] 0.35, '▁seventh'[C] 0.32, '▁second'[B] 0.32, '▁first'[B] 0.21, '▁Second'[N] 0.20, '▁last'[B] 0.13, 'First'[C] 0.12

=== feature 17  width=67  rho=2.46 ===
  Gemini : This vector represents the domain of journalism, news dissemination, and publishing media.
  tokens : '▁publication'[B] 0.24, '▁press'[B] 0.23, '▁publishing'[C] 0.23, '▁media'[C] 0.21, '▁published'[B] 0.21, '▁publisher'[C] 0.21, '▁newspaper'[B] 0.20, '▁publishers'[C] 0.20, '▁publications'[N] 0.20, '▁Press'[C] 0.19

=== feature 21  width=50  rho=2.45 ===
  Gemini : This vector represents concessive and directional transition words, prepositions, and conjunctions.
  tokens : '▁though'[B] 0.37, '▁Though'[N] 0.28, 'Though'[C] 0.28, 'through'[B] 0.27, '▁through'[B] 0.26, '▁Through'[C] 0.26, '▁however'[C] 0.24, '▁although'[B] 0.23, 'However'[B] 0.17, '▁Although'[N] 0.17

=== feature 35  width=28  rho=2.35 ===
  Gemini : This vector is related to exemplification, demonstration, and pointing out similarities or specific instances.
  tokens : '▁such'[B] 0.61, 'such'[N] 0.55, '▁these'[B] 0.22, '▁like'[B] 0.19, '▁this'[B] 0.17, 'These'[B] 0.15, '▁tales'[C] 0.14, '▁including'[B] 0.13, '▁example'[C] 0.13, 'Like'[B] 0.12

=== feature 14  width=20  rho=2.32 ===
  Gemini : This feature vector activates on third-person pronouns and demonstrative determiners across multiple languages.
  tokens : '▁they'[B] 0.48, 'They'[B] 0.44, '▁their'[B] 0.41, '▁them'[B] 0.37, '▁themselves'[C] 0.32, '▁Them'[C] 0.29, '▁this'[B] 0.14, '▁ich'[N] 0.11, ')['[N] 0.10, 'This'[B] 0.08

=== feature 0  width=37  rho=2.29 ===
  Gemini : This feature vector represents units of time and temporal duration.
  tokens : '▁years'[B] 0.37, '▁Years'[C] 0.32, '▁year'[B] 0.31, '▁decades'[C] 0.29, '▁decade'[C] 0.28, 'year'[B] 0.27, '▁Year'[C] 0.26, '▁months'[B] 0.25, '▁centuries'[N] 0.22, '▁century'[B] 0.20

=== feature 16  width=32  rho=2.22 ===
  Gemini : This vector represents terms related to names, naming conventions, and linguistic identification.

### 3.2.e LLM judge, stage 2: is the description *the* concept?

Stage 2 sees only the concept name and the Stage 1 description. It returns `{"is_member", "confidence"}`.
A feature joins $F_C$ only if `is_member` is true **and** confidence ≥ 0.85.

In [22]:
print("---- Stage 2 prompt ----")
print(MEMBERSHIP_PROMPT.format(concept=CONCEPT, desc="{description}").strip())

todo = {f: descriptions[f] for f in cand["feature"].astype(int).tolist() if f in descriptions and f not in verdicts}
for feat, desc in tqdm(todo.items(), desc="Stage 2: classify"):
    verdicts[feat] = classify_membership_with_desc(client, CONCEPT, desc)
    save_judge()

cand["is_member"] = cand["feature"].map(lambda f: verdicts[int(f)][0])
cand["confidence"] = pd.to_numeric(cand["feature"].map(lambda f: verdicts[int(f)][1]), errors="coerce").fillna(0.0)
cand["selected"] = (cand["is_member"] == True) & (cand["confidence"] >= CONFIDENCE)

F_C = sorted(cand.loc[cand["selected"], "feature"].astype(int).tolist())
print(f"\nF_C = {F_C}  ({len(F_C)} concept-related features)")
cand[["feature", "ratio_abs", "is_member", "confidence", "selected", "description"]]

---- Stage 2 prompt ----
You get a concept name and a feature's description.
Decide if this feature describes the given concept. Consider if the feature is DISTINCTIVE for the concept (not broad like "sport" for "basketball") and not too noisy.
A feature should be marked true only if the concept is central and dominant in the description, not just one of several themes.
Return ONLY JSON: {"is_member": true|false, "confidence": 0..1}

Example 1:
Concept: Charity
Description: This vector represents elements related to giving and donations to charitable causes.
Answer: {"is_member": true, "confidence": 0.98}

Example 2:
Concept: Charity
Description: This vector represents elements related to money, such as gambling, investing and charity.
Answer: {"is_member": false, "confidence": 0.80}

Concept: Harry Potter
Description: {description}
Answer:

Stage 2: classify: 100%|██████████| 63/63 [00:37<00:00,  1.68it/s]

F_C = [46]  (1 concept-related features)

,feature,ratio_abs,is_member,confidence,selected,description
0,46,129.348945,True,1.00,True,"This vector is related to characters, locations, and terminology from the Harry Potter universe."
1,88,53.965477,False,0.90,False,"This vector activates on words related to magic, sorcery, and fantasy folklore."
2,71,44.848994,False,0.99,False,"This feature vector represents the concept of entering or going into a space, state, or activity."
3,44,34.419179,False,0.99,False,"This vector activates for verbs and concepts related to acquiring knowledge, language skills, or literacy activities."
4,47,28.225249,False,0.99,False,"This feature vector represents the concept of the global earth, international scope, and the broader universe."
...,...,...,...,...,...,...
58,1,2.063697,False,0.99,False,"This vector represents concepts of prior occurrence, sequence, or historical precedence."
59,42,2.038758,False,1.00,False,This vector represents color descriptors and chromatic attributes.
60,67,2.035762,False,0.99,False,"This vector activates for terms related to honors, awards, and competitive recognition."
61,86,2.020338,False,0.99,False,"These tokens represent the concept of magnitude, importance, or scale."
62,66,2.014319,False,0.99,False,"This vector represents abstract nouns denoting general categories, classifications, or structural elements."

### 3.2.e′ Original fit: $\rho \ge \tau$ candidates (no Gemini)

The mass ratio ($\tau$ = 2.0) on `Y0`, **without the judge**: no Gemini calls are made for the original fit. Every candidate is
listed with its width and its top-15 tokens by $|Y^0_{i,t}|$ with labels [C]/[N]/[B], to compare by eye with the whitened $F_C$
(3.2.e/f). In the comparison cells below (3.2.w), `F_C0` **is this candidate list** ($\rho\ge\tau$ on the original fit), not a
judged selection. The last line lists $|\cos(\tilde{\mathbf z}_i, \tilde{\mathbf m})|$ for $i\in F_C$.

In [23]:
# tau filter on the original fit (Y0), no judge. F_C0 below = the rho >= tau candidates (NOT judged by Gemini).
N_SHOW0 = 15
stats0 = compute_embedding_stats(Y0.T, vstar_ids, token_to_code, CONCEPT).sort_values("ratio_abs", ascending=False)
for thr in [1.0, 1.25, 1.5, 1.75, 2.0, 2.25]:
    print(f"original fit: rho >= {thr:<4}: {(stats0['ratio_abs'] >= thr).sum():3d} / {RANK} features")
cand0 = stats0[stats0["ratio_abs"] >= TAU][["feature", "ratio_abs", "num_concept", "num_neutral", "num_both"]].reset_index(drop=True)
cand0["width"] = cand0["feature"].map(lambda f: int(widths0[int(f)]))
F_C0 = sorted(cand0["feature"].astype(int).tolist())   # stand-in for the judged F_C0: rho >= tau candidates of the original fit
print(f"\noriginal fit: {len(cand0)} candidates pass tau = {TAU}  ->  F_C0 (rho candidates, no judge) = {F_C0}   "
      f"(whitened fit, judged: F_C = {F_C})\n")

for _, row in cand0.iterrows():
    feat = int(row["feature"])
    mags = Y0[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW0]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])
    print(f"=== original feature {feat}  width={int(widths0[feat])}  rho={row['ratio_abs']:.2f} ===")
    print("  tokens : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

print("|cos(z~_i, m_X)| for i in F_C: " + (", ".join(
    f"{f}: {cos_m[f]:.3f} (rank {cos_m_order.index(f) + 1}/{RANK})" for f in F_C) or "F_C is empty"))
cand0

original fit: rho >= 1.0 :  68 / 100 features
original fit: rho >= 1.25:  62 / 100 features
original fit: rho >= 1.5 :  54 / 100 features
original fit: rho >= 1.75:  49 / 100 features
original fit: rho >= 2.0 :  48 / 100 features
original fit: rho >= 2.25:  47 / 100 features

original fit: 48 candidates pass tau = 2.0  ->  F_C0 (rho candidates, no judge) = [3, 5, 6, 10, 12, 18, 20, 22, 23, 24, 27, 28, 29, 30, 32, 35, 36, 39, 40, 41, 43, 50, 51, 54, 57, 58, 59, 61, 67, 70, 71, 73, 76, 78, 80, 81, 82, 83, 84, 85, 86, 87, 89, 91, 93, 94, 96, 98]   (whitened fit, judged: F_C = [46])

=== original feature 82  width=13  rho=117025.56 ===
  tokens : '▁book'[B] 0.41, '▁Book'[B] 0.39, 'book'[C] 0.39, '▁books'[C] 0.38, '▁Books'[C] 0.36, '▁novels'[C] 0.21, '▁novel'[B] 0.21, '▁bookstores'[C] 0.20, '▁Novel'[C] 0.19, '▁textbook'[C] 0.18, '▁ebooks'[C] 0.17, '▁novelist'[C] 0.12, '▁literature'[B] 0.11

=== original feature 57  width=23  rho=46.27 ===
  tokens : '▁magic'[C] 0.34, 'Magic'[C] 0.33, '▁Magic'[B] 0.33, 'magic'[C] 0.33, '▁magical'[C] 0.28, 'magical'[C] 0.26, '▁Magical'[C] 0.25, '▁wizard'[C] 0.21, '▁wizards'[C] 0.20, '▁Wizard'[C] 0.19, '▁witchcraft'[C] 0.17, 'wizard'[C] 0.17, '▁Wizards'[C] 0.16, '▁witch'[C] 0.16, '▁Witch'[C] 0.16

=== original feature 50  width=10  rho=16.73 ===
  tokens : '▁master'[C] 0.58, 'master'[B] 0.56, '▁mastery'[C] 0.30, '▁Lord'[C] 0.27, 'Lord'[C] 0.25, '▁principal'[C] 0.20, '▁primary'[B] 0.17, '▁main'[C] 0.15, '▁principle'[C] 0.14, 'Chief'[N] 0.13

=== original feature 18  width=17  rho=12.56 ===
  tokens : '▁selling'[C] 0.39, '▁sold'[C] 0.37, 'selling'[C] 0.36, 'sold'[C] 0.34, '▁sale'[C] 0.32, '▁sales'[B] 0.29, 'seller'[C] 0.24, '▁buying'[C] 0.23, '▁purchasing'[C] 0.19, '▁bought'[N] 0.19, '▁marketing'[C] 0.14, '▁bestselling'[C] 0.11, '▁pricing'[C] 0.11, '▁retail'[N] 0.11, '▁market'[C] 0.10

=== original feature 39  width=15  rho=11.57 ===
  tokens : '▁version'[B] 0.33, '▁Version'[C] 0.30, '▁translation'[C] 0.29, '▁translations'[C] 0.29, '▁interpretation'[N] 0.28, '▁edition'[B] 0.28, '▁interpretations'[C] 0.27, '▁editions'[C] 0.27, '▁adaptations'[C] 0.26, '▁translated'[C] 0.25, '▁rendition'[C] 0.23, '▁adapted'[C] 0.22, '▁adapt'[C] 0.21, '▁copies'[B] 0.17, '▁replica'[C] 0.12

=== original feature 40  width=10  rho=9.09 ===
  tokens : '▁escape'[C] 0.51, '▁escapes'[C] 0.47, '▁escaped'[C] 0.45, '▁Escape'[C] 0.44, '▁survived'[N] 0.17, '▁Es'[B] 0.15, '▁surviving'[C] 0.15, '▁avoid'[C] 0.14, '▁slip'[N] 0.13, '▁ev'[C] 0.10

=== original feature 22  width=11  rho=7.69 ===
  tokens : '▁moral'[C] 0.50, 'moral'[C] 0.45, '▁ethical'[C] 0.39, '▁morality'[C] 0.37, '▁ethically'[C] 0.31, '▁Mor'[N] 0.24, '▁social'[C] 0.17, '▁emotional'[C] 0.15, '▁Social'[N] 0.15, '▁spiritual'[C] 0.14, '▁legal'[B] 0.14

=== original feature 23  width=16  rho=7.13 ===
  tokens : '▁acceptance'[C] 0.41, '▁accepted'[N] 0.39, '▁accept'[C] 0.38, '▁rejection'[C] 0.34, '▁rejected'[C] 0.33, '▁reject'[C] 0.32, '▁recognition'[C] 0.18, '▁acknowledged'[C] 0.17, '▁recognised'[C] 0.16, '▁denied'[C] 0.16, '▁declined'[C] 0.14, '▁refuses'[C] 0.14, '▁embrace'[N] 0.13, '▁tolerance'[C] 0.12, '▁decline'[C] 0.12

=== original feature 36  width=10  rho=6.51 ===
  tokens : '▁follow'[C] 0.50, '▁follows'[C] 0.48, '▁followed'[C] 0.44, '▁following'[B] 0.40, '▁followers'[C] 0.28, '▁sequel'[C] 0.16, '▁chase'[C] 0.15, '▁trailed'[N] 0.13, '▁accompanied'[N] 0.12, '▁pursuit'[N] 0.11

=== original feature 98  width=10  rho=6.27 ===
  tokens : '▁love'[C] 0.48, '▁Love'[N] 0.44, 'Love'[C] 0.43, '▁loves'[C] 0.40, '▁loved'[C] 0.36, '▁likes'[C] 0.18, '▁dislike'[C] 0.14, '▁favourite'[C] 0.12, '▁romance'[C] 0.10, '▁joy'[C] 0.10

=== original feature 93  width=11  rho=5.93 ===
  tokens : '▁possible'[N] 0.43, '▁possibility'[C] 0.39, '▁potential'[C] 0.36, '▁possibly'[C] 0.35, '▁likely'[C] 0.31, '▁might'[C] 0.30, '▁could'[B] 0.24, '▁may'[B] 0.24, '▁chances'[C] 0.21, '▁prospective'[C] 0.19, '▁would'[B] 0.17

=== original feature 3  width=16  rho=5.58 ===
  tokens : '▁teaching'[C] 0.43, '▁teach'[C] 0.43, '▁teaches'[C] 0.38, '▁teachings'[C] 0.32, '▁lessons'[C] 0.23, '▁teacher'[C] 0.23, '▁learn'[C] 0.23, '▁learns'[C] 0.20, '▁education'[N] 0.20, '▁educational'[N] 0.20, 'educational'[C] 0.17, '▁curriculum'[C] 0.15, '▁lectures'[C] 0.13, '▁instructions'[N] 0.12, '▁training'[N] 0.11

=== original feature 67  width=106  rho=5.16 ===
  tokens : '▁gives'[C] 0.13, '▁goes'[B] 0.13, '▁becomes'[B] 0.13, '▁allows'[C] 0.13, '▁takes'[C] 0.13, '▁delivers'[C] 0.13, '▁comes'[C] 0.12, '▁speaks'[C] 0.12, '▁feels'[C] 0.12, '▁tells'[C] 0.12, '▁enters'[C] 0.12, '▁learns'[C] 0.12, '▁makes'[C] 0.12, '▁undergoes'[C] 0.12, '▁assumes'[C] 0.12

=== original feature 89  width=11  rho=4.92 ===
  tokens : '▁news'[C] 0.37, '▁News'[N] 0.37, 'News'[C] 0.36, '▁press'[B] 0.36, '▁Press'[C] 0.34, '▁media'[C] 0.30, 'media'[C] 0.27, '▁newspapers'[C] 0.25, '▁newspaper'[B] 0.25, '▁journalists'[C] 0.21, '▁reporter'[N] 0.14

=== original feature 20  width=29  rho=4.73 ===
  tokens : '▁showing'[C] 0.29, '▁show'[N] 0.29, '▁display'[N] 0.28, 'show'[C] 0.26, '▁displays'[C] 0.26, '▁displayed'[C] 0.25, '▁shown'[C] 0.25, '▁showed'[C] 0.24, '▁showcase'[C] 0.23, '▁depicting'[C] 0.19, 'showcase'[C] 0.18, '▁portray'[C] 0.17, '▁portraying'[C] 0.17, '▁depicted'[C] 0.17, '▁exhibition'[C] 0.17

=== original feature 76  width=20  rho=4.63 ===
  tokens : '▁demand'[C] 0.32, '▁needs'[N] 0.30, '▁need'[C] 0.30, '▁move'[B] 0.29, '▁demanded'[C] 0.26, '▁request'[C] 0.25, '▁moving'[C] 0.24, '▁moved'[B] 0.24, '▁needed'[B] 0.24, '▁wants'[C] 0.24, '▁Wants'[C] 0.22, '▁desire'[C] 0.20, '▁Movement'[N] 0.19, '▁shift'[C] 0.19, '▁shifted'[B] 0.16

=== original feature 78  width=34  rho=4.61 ===
  tokens : '▁criticism'[C] 0.32, '▁criticisms'[C] 0.29, '▁criticized'[N] 0.27, '▁critics'[C] 0.26, '▁criticised'[C] 0.25, '▁critic'[B] 0.25, '▁controversy'[C] 0.20, '▁argue'[C] 0.19, '▁debate'[C] 0.19, '▁argument'[C] 0.19, '▁controversies'[C] 0.18, '▁arguing'[C] 0.18, '▁argues'[C] 0.17, '▁critical'[N] 0.17, '▁debated'[C] 0.16

=== original feature 30  width=10  rho=4.58 ===
  tokens : '▁cover'[C] 0.53, '▁covers'[C] 0.50, '▁covering'[C] 0.48, 'covered'[N] 0.41, '▁spanned'[N] 0.12, '▁hiding'[C] 0.11, '▁coats'[C] 0.11, '▁uncover'[C] 0.11, '▁hides'[C] 0.11, '▁shelters'[C] 0.08

=== original feature 81  width=10  rho=4.58 ===
  tokens : '▁note'[C] 0.47, '▁noting'[C] 0.41, '▁noted'[B] 0.39, '▁notice'[C] 0.34, '▁observing'[C] 0.29, '▁observation'[N] 0.28, '▁notable'[B] 0.26, 'Notable'[N] 0.21, 'remark'[C] 0.20, '▁Observer'[C] 0.18

=== original feature 96  width=10  rho=4.34 ===
  tokens : 'part'[C] 0.42, '▁part'[B] 0.42, '▁Part'[N] 0.40, '▁parts'[C] 0.36, '▁Parts'[C] 0.34, '▁half'[C] 0.27, 'half'[B] 0.26, '▁Half'[C] 0.25, '▁partial'[C] 0.19, '▁components'[N] 0.10

=== original feature 71  width=11  rho=4.20 ===
  tokens : '▁himself'[C] 0.49, '▁themselves'[C] 0.49, '▁herself'[C] 0.48, '▁myself'[N] 0.42, '▁him'[B] 0.16, '▁them'[B] 0.15, '▁Them'[C] 0.14, '▁own'[B] 0.14, '▁self'[C] 0.11, '▁me'[C] 0.10, '▁alone'[N] 0.10

=== original feature 83  width=12  rho=3.93 ===
  tokens : '▁fourth'[B] 0.42, '▁fifth'[C] 0.41, '▁third'[B] 0.40, '▁sixth'[B] 0.39, '▁seventh'[C] 0.38, '▁second'[B] 0.28, '▁Second'[N] 0.23, 'Forth'[C] 0.14, 'rd'[C] 0.13, 'th'[B] 0.11, '▁first'[B] 0.10, 'nd'[N] 0.10

=== original feature 84  width=11  rho=3.90 ===
  tokens : '▁reports'[C] 0.43, '▁report'[N] 0.42, '▁reported'[C] 0.41, '▁reporting'[C] 0.41, '▁reportedly'[C] 0.27, '▁reporter'[N] 0.22, '▁allegedly'[B] 0.21, '▁purported'[C] 0.19, '▁claims'[B] 0.19, 'ported'[C] 0.18, '▁claimed'[C] 0.18

=== original feature 86  width=10  rho=3.79 ===
  tokens : '▁hold'[B] 0.46, '▁holding'[B] 0.43, '▁holds'[C] 0.40, '▁held'[B] 0.37, '▁holder'[C] 0.31, '▁Holden'[C] 0.24, '▁host'[B] 0.21, '▁hosting'[N] 0.21, '▁hosts'[C] 0.20, 'ghold'[N] 0.15

=== original feature 61  width=10  rho=3.76 ===
  tokens : '▁because'[B] 0.43, 'because'[C] 0.42, '▁due'[B] 0.41, 'Because'[N] 0.36, 'Due'[C] 0.36, '▁since'[B] 0.25, '▁reason'[C] 0.23, '▁reasons'[B] 0.19, 'Since'[B] 0.18, '▁attributable'[C] 0.14

=== original feature 80  width=11  rho=3.73 ===
  tokens : '▁variety'[N] 0.41, '▁varied'[C] 0.38, '▁Variety'[C] 0.38, '▁diverse'[B] 0.35, '▁diversity'[C] 0.34, 'Various'[C] 0.28, '▁various'[B] 0.27, '▁different'[B] 0.25, '▁range'[C] 0.19, '▁differs'[C] 0.16, '▁eclectic'[N] 0.14

=== original feature 24  width=22  rho=3.26 ===
  tokens : '▁killed'[C] 0.32, '▁killing'[C] 0.31, '▁kills'[C] 0.30, '▁death'[B] 0.29, '▁killers'[N] 0.25, '▁died'[B] 0.24, '▁Death'[C] 0.24, '▁dead'[C] 0.24, '▁murdered'[C] 0.24, '▁killer'[N] 0.23, '▁murder'[C] 0.23, '▁dies'[C] 0.23, '▁die'[C] 0.20, '▁Die'[N] 0.16, '▁massacre'[N] 0.14

=== original feature 54  width=20  rho=3.24 ===
  tokens : '▁many'[B] 0.41, '▁Many'[C] 0.36, 'Many'[C] 0.35, '▁numerous'[N] 0.30, '▁several'[B] 0.27, '▁dozens'[C] 0.23, '▁few'[C] 0.20, '▁most'[B] 0.19, '▁multiple'[N] 0.19, '▁millions'[C] 0.19, '▁Most'[N] 0.18, '▁some'[B] 0.18, '▁various'[B] 0.17, 'most'[C] 0.16, 'Various'[C] 0.16

=== original feature 32  width=12  rho=3.20 ===
  tokens : '▁attend'[C] 0.47, '▁attended'[N] 0.44, '▁attending'[C] 0.44, '▁visit'[C] 0.25, '▁visited'[C] 0.25, '▁visits'[C] 0.24, '▁participated'[N] 0.22, '▁participate'[C] 0.21, 'att'[C] 0.20, '▁joining'[N] 0.17, '▁joined'[B] 0.16, '▁attention'[C] 0.15

=== original feature 73  width=25  rho=3.12 ===
  tokens : '▁discovering'[C] 0.35, '▁Discovery'[N] 0.34, '▁discoveries'[N] 0.33, 'Discovery'[C] 0.33, '▁discovers'[C] 0.31, '▁finding'[C] 0.23, '▁find'[C] 0.21, '▁Find'[C] 0.20, '▁exploration'[C] 0.19, '▁uncover'[C] 0.18, '▁explore'[N] 0.17, '▁found'[B] 0.17, '▁Experience'[N] 0.14, '▁encounter'[C] 0.13, '▁learns'[C] 0.13

=== original feature 94  width=28  rho=3.08 ===
  tokens : '▁assume'[C] 0.31, '▁intended'[N] 0.28, '▁expected'[N] 0.28, '▁assumption'[C] 0.27, '▁assumes'[C] 0.27, '▁expect'[C] 0.26, '▁supposed'[N] 0.24, '▁meant'[N] 0.23, '▁hope'[C] 0.22, '▁thought'[C] 0.19, '▁intends'[C] 0.18, '▁planned'[B] 0.18, '▁think'[C] 0.17, '▁Hope'[N] 0.16, '▁aimed'[C] 0.16

=== original feature 85  width=13  rho=2.99 ===
  tokens : '▁both'[B] 0.44, 'both'[N] 0.44, '▁neither'[C] 0.36, '▁each'[B] 0.34, '▁either'[B] 0.30, 'Each'[B] 0.26, '▁every'[C] 0.24, 'every'[C] 0.24, '▁respectively'[B] 0.18, '▁none'[C] 0.14, '▁all'[B] 0.14, 'all'[C] 0.13, '▁any'[B] 0.11

=== original feature 28  width=20  rho=2.98 ===
  tokens : '▁nine'[C] 0.29, '▁five'[B] 0.28, '▁seven'[B] 0.28, '▁eight'[B] 0.28, '▁six'[B] 0.27, '▁four'[B] 0.26, '▁eleven'[C] 0.26, 'four'[C] 0.24, '▁three'[B] 0.23, '▁Five'[N] 0.23, 'Nine'[C] 0.22, '▁nineteen'[C] 0.22, '▁Eleven'[N] 0.21, '▁twenty'[C] 0.20, 'Three'[C] 0.19

=== original feature 12  width=11  rho=2.91 ===
  tokens : '▁draw'[C] 0.48, '▁drawn'[C] 0.45, '▁drawing'[C] 0.43, 'Draw'[N] 0.42, '▁Drew'[N] 0.24, '▁attracted'[C] 0.21, '▁attraction'[C] 0.17, '▁sketch'[N] 0.16, '▁appeal'[B] 0.15, '▁attractions'[C] 0.13, '▁appealing'[C] 0.11

=== original feature 27  width=16  rho=2.91 ===
  tokens : '▁section'[C] 0.37, '▁sections'[C] 0.36, '▁piece'[N] 0.33, '▁pieces'[B] 0.32, '▁chapter'[C] 0.29, '▁article'[B] 0.28, '▁articles'[N] 0.27, '▁segment'[B] 0.24, '▁Chapter'[C] 0.23, '▁letters'[C] 0.19, '▁pages'[C] 0.18, '▁letter'[C] 0.18, '▁trust'[N] 0.14, '▁items'[C] 0.14, 'trust'[C] 0.14

=== original feature 35  width=10  rho=2.70 ===
  tokens : '▁open'[C] 0.49, 'open'[C] 0.46, '▁Open'[N] 0.45, '▁opened'[B] 0.37, '▁opening'[B] 0.34, '▁closed'[C] 0.26, '▁enclosed'[N] 0.10, '▁sealed'[C] 0.09, '▁op'[C] 0.08, 'berto'[N] 0.06

=== original feature 10  width=27  rho=2.69 ===
  tokens : '▁years'[B] 0.34, '▁Years'[C] 0.31, '▁decades'[C] 0.29, '▁decade'[C] 0.26, '▁year'[B] 0.26, '▁centuries'[N] 0.25, '▁months'[B] 0.24, '▁Year'[C] 0.23, 'year'[B] 0.23, '▁century'[B] 0.22, '▁days'[C] 0.20, 'century'[B] 0.17, '▁Days'[C] 0.17, '▁hours'[B] 0.16, '▁seasons'[C] 0.15

=== original feature 5  width=29  rho=2.69 ===
  tokens : '▁favourite'[C] 0.24, '▁organised'[N] 0.24, '▁favour'[C] 0.24, '▁recognised'[C] 0.24, '▁colour'[C] 0.24, '▁favourable'[N] 0.23, 'centred'[C] 0.23, 'centre'[N] 0.22, '▁humour'[C] 0.22, 'arised'[C] 0.22, 'isation'[C] 0.21, '▁neighbourhood'[N] 0.21, '▁watercolour'[C] 0.20, '▁Defence'[C] 0.19, '▁criticised'[C] 0.18

=== original feature 6  width=76  rho=2.69 ===
  tokens : '▁largely'[B] 0.20, '▁generally'[B] 0.20, '▁primarily'[B] 0.20, '▁predominantly'[C] 0.18, '▁essentially'[C] 0.17, '▁mainly'[C] 0.17, '▁broadly'[N] 0.16, '▁usually'[N] 0.15, '▁ostensibly'[C] 0.15, '▁initially'[C] 0.14, '▁specifically'[C] 0.14, '▁originally'[C] 0.14, 'larg'[C] 0.14, '▁substantially'[C] 0.14, '▁frequently'[C] 0.13

=== original feature 87  width=10  rho=2.61 ===
  tokens : '▁lead'[C] 0.55, '▁leads'[B] 0.49, '▁led'[B] 0.43, '▁leading'[B] 0.42, '▁leaders'[C] 0.23, '▁conduit'[N] 0.12, '▁trailed'[N] 0.11, '▁guide'[C] 0.10, '▁resulted'[N] 0.09, '▁prompted'[N] 0.08

=== original feature 70  width=15  rho=2.49 ===
  tokens : '▁include'[B] 0.38, '▁includes'[C] 0.36, '▁included'[B] 0.30, '▁including'[B] 0.29, '▁inclusion'[C] 0.28, 'including'[C] 0.27, '▁consist'[C] 0.25, '▁consists'[N] 0.25, '▁consisting'[N] 0.22, '▁comprise'[C] 0.21, '▁contains'[B] 0.21, '▁incorporates'[N] 0.20, '▁contain'[C] 0.20, '▁involves'[C] 0.16, '▁incorporated'[N] 0.16

=== original feature 51  width=18  rho=2.49 ===
  tokens : '▁longest'[C] 0.29, '▁fastest'[C] 0.29, '▁best'[B] 0.27, '▁largest'[N] 0.27, 'largest'[N] 0.26, '▁funniest'[C] 0.26, '▁highest'[N] 0.25, 'most'[C] 0.25, '▁most'[B] 0.25, 'tiest'[C] 0.23, 'Best'[C] 0.23, 'ariest'[C] 0.23, 'liest'[C] 0.22, '▁Best'[C] 0.22, '▁Most'[N] 0.21

=== original feature 59  width=10  rho=2.36 ===
  tokens : '▁cast'[C] 0.50, '▁Cast'[N] 0.48, 'Cast'[C] 0.47, '▁casting'[C] 0.42, 'caster'[N] 0.26, 'castle'[C] 0.16, '▁actors'[B] 0.11, '▁actor'[B] 0.09, 'ast'[N] 0.09, 'asting'[C] 0.08

=== original feature 43  width=239  rho=2.34 ===
  tokens : '▁tyranny'[C] 0.11, '▁paranoia'[C] 0.11, '▁sovereignty'[N] 0.10, '▁allegory'[C] 0.10, '▁resurrected'[C] 0.10, '▁symbolism'[C] 0.10, '▁innocence'[C] 0.10, '▁subordination'[C] 0.10, '▁benevolence'[C] 0.10, '▁nostalgic'[C] 0.09, '▁rubble'[N] 0.09, '▁haunted'[C] 0.09, '▁mythical'[C] 0.09, '▁sadness'[C] 0.09, '▁retaliation'[N] 0.09

=== original feature 58  width=10  rho=2.33 ===
  tokens : '▁just'[B] 0.46, '▁Just'[N] 0.44, 'Just'[C] 0.43, '▁simply'[C] 0.39, '▁merely'[C] 0.35, '▁only'[B] 0.21, '▁Only'[N] 0.21, '▁simple'[C] 0.16, 'Pure'[C] 0.10, '▁alone'[N] 0.08

=== original feature 41  width=239  rho=2.31 ===
  tokens : '▁that'[B] 0.11, '▁it'[B] 0.11, '▁in'[B] 0.11, '▁to'[B] 0.11, '▁with'[B] 0.11, '▁when'[B] 0.11, '▁on'[B] 0.10, '▁for'[B] 0.10, '▁the'[B] 0.10, '▁at'[B] 0.10, '▁as'[B] 0.10, '▁if'[B] 0.10, '▁from'[B] 0.10, '▁what'[B] 0.10, '▁there'[C] 0.10

=== original feature 29  width=20  rho=2.27 ===
  tokens : '▁race'[C] 0.34, '▁fight'[B] 0.29, '▁races'[B] 0.29, '▁battle'[C] 0.28, '▁chase'[C] 0.26, '▁struggle'[B] 0.24, '▁contest'[C] 0.24, '▁hunt'[N] 0.24, '▁competed'[N] 0.23, '▁competing'[N] 0.21, '▁search'[C] 0.21, '▁quest'[C] 0.20, '▁pursuit'[N] 0.19, '▁duel'[C] 0.19, '▁competitive'[N] 0.18

=== original feature 91  width=14  rho=2.15 ===
  tokens : '▁announced'[B] 0.37, '▁announcement'[C] 0.36, '▁announcing'[N] 0.35, '▁release'[B] 0.33, '▁released'[B] 0.32, '▁launch'[C] 0.32, '▁launched'[B] 0.29, '▁revealed'[C] 0.20, '▁reveal'[C] 0.19, '▁unleashed'[C] 0.17, '▁Ann'[N] 0.17, '▁introduced'[N] 0.17, '▁declared'[B] 0.15, '▁debut'[B] 0.15

|cos(z~_i, m_X)| for i in F_C: 46: 0.104 (rank 76/100)

    feature      ratio_abs  num_concept  num_neutral  num_both  width
0        82  117025.559302            9            0         4     13
1        57      46.272176           21            1         1     23
2        50      16.729407            7            1         2     10
3        18      12.558961           14            2         1     17
4        39      11.569518           11            1         3     15
5        40       9.087780            7            2         1     10
6        22       7.690376            8            2         1     11
7        23       7.132580           14            2         0     16
8        36       6.509302            6            3         1     10
9        98       6.266172            9            1         0     10
10       93       5.929408            7            1         3     11
11        3       5.576464           12            4         0     16
12       67       5.159511           76           19        11    106
13       89       4.922026            7            2         2     11
14       20       4.730543           20            6         3     29
15       76       4.632657           11            3         6     20
16       78       4.610472           24            7         3     34
17       30       4.583564            8            2         0     10
18       81       4.576489            6            2         2     10
19       96       4.336581            6            2         2     10
20       71       4.204650            6            2         3     11
21       83       3.925890            4            2         6     12
22       84       3.895453            7            2         2     11
23       86       3.786630            4            2         4     10
24       61       3.764776            4            1         5     10
25       80       3.733810            6            2         3     11
26       24       3.256829           14            6         2     22
27       54       3.242856           11            4         5     20
28       32       3.198958            8            3         1     12
29       73       3.118347           17            6         2     25
30       94       3.079014           20            6         2     28
31       85       2.992942            5            1         7     13
32       28       2.978596            9            4         7     20
33       12       2.910168            7            3         1     11
34       27       2.906107            9            4         3     16
35       35       2.701034            5            3         2     10
36       10       2.690084           10            7        10     27
37        5       2.687449           19           10         0     29
38        6       2.685449           47           21         8     76
39       87       2.609139            3            4         3     10
40       70       2.490134            7            4         4     15
41       51       2.486626           11            5         2     18
42       59       2.356234            5            3         2     10
43       43       2.340444          149           83         7    239
44       58       2.328948            5            3         2     10
45       41       2.314435           67           34       138    239
46       29       2.266756           11            6         3     20
47       91       2.148132            5            3         6     14

In [24]:
is_true = cand["is_member"] == True
ordered = cand.assign(
    _group=(~is_true).astype(int),
    _key=np.where(is_true, -cand["confidence"], cand["confidence"]),
).sort_values(["_group", "_key"])

for _, row in ordered.iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    is_member, conf = verdicts.get(feat, (None, None))
    verdict = "<not classified yet>" if feat not in verdicts else (
        f"is_member={is_member}  confidence={conf if conf is not None else 'n/a'}  "
        f"-> {'SELECTED' if row['selected'] else 'rejected'}"
    )

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini  : {descriptions.get(feat, '<not described yet>')}")
    print(f"  verdict : {verdict}")
    print("  tokens  : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

=== feature 46  width=48  rho=129.35 ===
  Gemini  : This vector is related to characters, locations, and terminology from the Harry Potter universe.
  verdict : is_member=True  confidence=1.0  -> SELECTED
  tokens  : 'ffindor'[C] 0.36, 'therin'[C] 0.30, 'umbledore'[C] 0.24, '▁Dumbledore'[C] 0.21, '▁Weasley'[C] 0.20, '▁Malfoy'[C] 0.19, '▁Hogwarts'[C] 0.19, '▁Rowling'[C] 0.19, '▁Potter'[C] 0.19, 'Hermione'[C] 0.18

=== feature 88  width=55  rho=53.97 ===
  Gemini  : This vector activates on words related to magic, sorcery, and fantasy folklore.
  verdict : is_member=False  confidence=0.9  -> rejected
  tokens  : '▁magic'[C] 0.36, 'magic'[C] 0.35, 'Magic'[C] 0.34, '▁Magic'[B] 0.33, '▁magical'[C] 0.28, 'magical'[C] 0.26, '▁Magical'[C] 0.23, '▁wizard'[C] 0.18, '▁wizards'[C] 0.17, '▁witchcraft'[C] 0.15

=== feature 68  width=48  rho=16.56 ===
  Gemini  : This feature vector represents the concept of books, reading, and literature.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁book'[B] 0.38, 'book'[C] 0.35, '▁Book'[B] 0.34, '▁books'[C] 0.34, '▁Books'[C] 0.31, '▁novels'[C] 0.19, '▁bookstores'[C] 0.18, '▁novel'[B] 0.18, '▁ebooks'[C] 0.15, '▁Novel'[C] 0.15

=== feature 3  width=34  rho=9.51 ===
  Gemini  : This vector represents the concept of discovery, searching, and visual or conceptual finding.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁find'[C] 0.37, '▁finding'[C] 0.34, '▁Find'[C] 0.32, '▁found'[B] 0.30, '▁discovering'[C] 0.24, '▁see'[B] 0.23, '▁discovers'[C] 0.23, '▁sees'[C] 0.22, '▁seeing'[C] 0.20, '▁discoveries'[N] 0.19

=== feature 75  width=42  rho=4.46 ===
  Gemini  : This vector represents the concept of film and theatrical production, encompassing cast members, crew, and cinematic works.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁cast'[C] 0.42, '▁casting'[C] 0.34, 'Cast'[C] 0.33, '▁Cast'[N] 0.32, '▁production'[C] 0.22, 'Production'[C] 0.19, '▁productions'[C] 0.18, '▁actors'[B] 0.18, '▁actor'[B] 0.17, '▁producer'[B] 0.15

=== feature 83  width=23  rho=4.04 ===
  Gemini  : This vector represents the concept of mortality, death, and lethal acts.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁death'[B] 0.33, '▁killed'[C] 0.32, '▁died'[B] 0.30, '▁kills'[C] 0.30, '▁killing'[C] 0.29, '▁dies'[C] 0.28, '▁dead'[C] 0.28, '▁Death'[C] 0.27, '▁die'[C] 0.26, '▁murdered'[C] 0.21

=== feature 71  width=11  rho=44.85 ===
  Gemini  : This feature vector represents the concept of entering or going into a space, state, or activity.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁entry'[C] 0.47, '▁enter'[C] 0.45, '▁enters'[C] 0.43, '▁entering'[C] 0.43, '▁entries'[C] 0.40, '▁into'[B] 0.14, '▁foray'[C] 0.10, 'nter'[C] 0.09, '▁Entertainment'[C] 0.08, '▁infiltr'[C] 0.07

=== feature 44  width=12  rho=34.42 ===
  Gemini  : This vector activates for verbs and concepts related to acquiring knowledge, language skills, or literacy activities.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁read'[C] 0.56, '▁reads'[C] 0.48, '▁Read'[C] 0.47, '▁reading'[B] 0.43, '▁learn'[C] 0.10, '▁literacy'[C] 0.10, '▁listened'[C] 0.09, '▁ride'[C] 0.09, '▁write'[C] 0.08, '▁learns'[C] 0.08

=== feature 47  width=12  rho=28.23 ===
  Gemini  : This feature vector represents the concept of the global earth, international scope, and the broader universe.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁world'[B] 0.50, '▁World'[B] 0.47, 'World'[C] 0.47, '▁worlds'[C] 0.38, '▁universe'[C] 0.22, '▁worldwide'[C] 0.21, '▁internationally'[C] 0.17, '▁International'[C] 0.12, '▁word'[C] 0.12, '▁Universal'[C] 0.08

=== feature 25  width=23  rho=26.38 ===
  Gemini  : This feature vector represents words related to contrast, comparison, and alternative choices.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁rather'[C] 0.59, 'Rather'[C] 0.54, '▁instead'[B] 0.45, '▁than'[B] 0.15, '▁fairly'[C] 0.14, '▁vs'[C] 0.13, '▁somewhat'[C] 0.12, '▁opposed'[C] 0.12, '▁something'[C] 0.10, 'opposed'[N] 0.09

=== feature 29  width=12  rho=23.77 ===
  Gemini  : This vector represents third-person masculine singular personal and possessive pronouns.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁his'[B] 0.38, '▁He'[B] 0.38, 'He'[B] 0.36, '▁he'[B] 0.36, 'His'[C] 0.36, '▁His'[C] 0.35, '▁him'[B] 0.33, '▁himself'[C] 0.29, 'zyński'[N] 0.06, '▁Heli'[C] 0.05

=== feature 32  width=33  rho=12.62 ===
  Gemini  : This vector is related to particular iterations, instances, or variants of something.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁version'[B] 0.42, '▁edition'[B] 0.38, '▁Version'[C] 0.35, '▁editions'[C] 0.33, '▁example'[C] 0.24, '▁instance'[C] 0.23, '▁rendition'[C] 0.22, '▁examples'[C] 0.20, '▁instances'[C] 0.18, '▁copies'[B] 0.17

=== feature 22  width=25  rho=11.99 ===
  Gemini  : This feature vector represents the commercial concepts of buying, selling, and market transactions.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁selling'[C] 0.39, '▁sold'[C] 0.38, 'selling'[C] 0.36, 'sold'[C] 0.35, '▁sale'[C] 0.35, '▁sales'[B] 0.31, 'seller'[C] 0.24, '▁buying'[C] 0.17, '▁purchasing'[C] 0.14, '▁bought'[N] 0.13

=== feature 50  width=39  rho=9.20 ===
  Gemini  : This vector represents the concept of the written word and the practice or profession of writing.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁writing'[B] 0.33, '▁written'[B] 0.33, 'writing'[C] 0.31, 'written'[C] 0.31, '▁writer'[B] 0.30, '▁writers'[C] 0.29, '▁write'[C] 0.29, '▁wrote'[B] 0.28, '▁author'[C] 0.19, '▁authors'[C] 0.19

=== feature 20  width=14  rho=8.28 ===
  Gemini  : This feature vector activates on words representing units of time, temporal intervals, and calendar-related periods.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁day'[C] 0.51, '▁Day'[C] 0.47, '▁days'[C] 0.37, '▁Days'[C] 0.36, '▁night'[C] 0.29, '▁Night'[C] 0.23, '▁morning'[N] 0.17, '▁date'[B] 0.14, '▁eve'[C] 0.13, '▁hours'[B] 0.13

=== feature 27  width=10  rho=8.03 ===
  Gemini  : This vector represents bodily fluids and biological circulation systems.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁blood'[C] 0.59, 'blood'[C] 0.57, 'Blood'[C] 0.53, '▁plasma'[N] 0.11, '▁circulatory'[N] 0.10, '▁veins'[N] 0.08, 'bread'[C] 0.08, '▁tears'[C] 0.08, '▁soul'[C] 0.07, '▁binary'[C] 0.07

=== feature 19  width=44  rho=6.35 ===
  Gemini  : This vector represents verbs and nouns associated with affection, preference, and psychological states.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁love'[C] 0.36, '▁loves'[C] 0.32, '▁likes'[C] 0.30, '▁Love'[N] 0.28, 'Love'[C] 0.27, '▁loved'[C] 0.27, '▁like'[B] 0.27, 'Like'[B] 0.22, '▁wants'[C] 0.18, '▁Wants'[C] 0.16

=== feature 52  width=25  rho=6.12 ===
  Gemini  : This vector represents quantifying words and universal determiners expressing totality or distribution.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁every'[C] 0.40, '▁each'[B] 0.39, '▁all'[B] 0.38, 'every'[C] 0.37, 'all'[C] 0.33, 'Each'[B] 0.32, 'All'[B] 0.25, '▁any'[B] 0.15, 'alls'[N] 0.14, '▁ever'[B] 0.11

=== feature 64  width=20  rho=6.08 ===
  Gemini  : This feature activates on demonstrative and definite determiners, pronouns, and related deictic words indicating specific entities or contexts.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁this'[B] 0.52, '▁these'[B] 0.52, 'These'[B] 0.36, 'This'[B] 0.31, '▁those'[C] 0.22, '▁the'[B] 0.21, 'the'[B] 0.14, 'The'[B] 0.14, '▁The'[B] 0.13, '▁that'[B] 0.13

=== feature 39  width=11  rho=5.72 ===
  Gemini  : This feature vector represents the concept of possessing, keeping, or containing something.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁hold'[B] 0.47, '▁holding'[B] 0.43, '▁holds'[C] 0.41, '▁held'[B] 0.40, '▁holder'[C] 0.33, '▁Holden'[C] 0.23, '▁host'[B] 0.19, '▁hosts'[C] 0.18, '▁hosting'[N] 0.16, 'ghold'[N] 0.10

=== feature 78  width=48  rho=5.66 ===
  Gemini  : This feature vector represents the concept of displaying, exhibiting, or visually presenting something.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁show'[N] 0.33, 'show'[C] 0.31, '▁showing'[C] 0.30, '▁shown'[C] 0.29, '▁showed'[C] 0.28, '▁display'[N] 0.23, '▁displayed'[C] 0.22, '▁displays'[C] 0.21, '▁showcase'[C] 0.19, '▁depicted'[C] 0.15

=== feature 65  width=12  rho=3.85 ===
  Gemini  : This feature represents the concept of pulling, attracting, or rendering physically and conceptually.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁draw'[C] 0.49, '▁drawn'[C] 0.47, '▁drawing'[C] 0.44, 'Draw'[N] 0.38, '▁attracted'[C] 0.24, '▁attraction'[C] 0.20, '▁Drew'[N] 0.17, '▁appeal'[B] 0.16, '▁attractions'[C] 0.14, '▁appealing'[C] 0.12

=== feature 26  width=54  rho=3.81 ===
  Gemini  : This vector represents the concept of human age and developmental stages, encompassing terms for children, youth, and adults.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁children'[B] 0.27, '▁kids'[C] 0.25, 'Children'[C] 0.22, '▁young'[B] 0.22, '▁kid'[C] 0.22, 'child'[C] 0.21, '▁Child'[B] 0.20, '▁adult'[C] 0.19, '▁adults'[C] 0.19, '▁age'[B] 0.18

=== feature 28  width=31  rho=3.70 ===
  Gemini  : This feature vector activates strongly on number words and numerals representing quantities or numerical values.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁four'[B] 0.31, '▁six'[B] 0.30, '▁five'[B] 0.30, '▁seven'[B] 0.30, '▁eight'[B] 0.29, '▁nine'[C] 0.28, '▁three'[B] 0.27, 'four'[C] 0.26, '▁eleven'[C] 0.24, '▁two'[B] 0.22

=== feature 98  width=25  rho=3.66 ===
  Gemini  : This vector represents verbs and related forms associated with inclusion, containment, or comprising elements.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁include'[B] 0.39, '▁includes'[C] 0.38, '▁including'[B] 0.33, '▁included'[B] 0.31, 'including'[C] 0.30, '▁inclusion'[C] 0.26, '▁contains'[B] 0.21, '▁contain'[C] 0.20, '▁consists'[N] 0.20, '▁consist'[C] 0.19

=== feature 37  width=23  rho=3.61 ===
  Gemini  : This feature vector represents components, subdivisions, or individual parts of a whole.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁part'[B] 0.47, 'part'[C] 0.46, '▁Part'[N] 0.41, '▁parts'[C] 0.39, '▁Parts'[C] 0.33, '▁section'[C] 0.16, '▁sections'[C] 0.15, '▁aspects'[C] 0.10, '▁components'[N] 0.10, '▁segment'[B] 0.09

=== feature 36  width=10  rho=3.50 ===
  Gemini  : This feature activates for words related to the opening, closing, or accessibility of objects, spaces, or states.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁open'[C] 0.52, 'open'[C] 0.49, '▁Open'[N] 0.43, '▁opened'[B] 0.35, '▁opening'[B] 0.30, '▁closed'[C] 0.26, '▁sealed'[C] 0.07, '▁enclosed'[N] 0.07, '▁op'[C] 0.06, '▁free'[C] 0.06

=== feature 97  width=191  rho=3.42 ===
  Gemini  : This feature vector represents general plural nouns describing various subjects, elements, or categories of discussion.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁topics'[C] 0.15, '▁themes'[C] 0.15, '▁stories'[B] 0.14, '▁items'[C] 0.13, '▁elements'[C] 0.13, '▁issues'[C] 0.13, '▁scenes'[C] 0.13, '▁aspects'[C] 0.12, '▁concepts'[C] 0.12, '▁characters'[C] 0.12

=== feature 34  width=25  rho=3.15 ===
  Gemini  : This vector represents superlative adjectives and adverbs indicating extreme degrees or quantities.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁most'[B] 0.41, 'most'[C] 0.40, '▁Most'[N] 0.31, '▁best'[B] 0.27, '▁fastest'[C] 0.22, '▁funniest'[C] 0.21, '▁longest'[C] 0.21, 'liest'[C] 0.20, 'tiest'[C] 0.20, 'ariest'[C] 0.20

=== feature 58  width=15  rho=2.79 ===
  Gemini  : These tokens function as restrictive or limiting adverbial modifiers that constrain the scope, degree, or emphasis of a statement.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁just'[B] 0.51, 'Just'[C] 0.42, '▁Just'[N] 0.41, '▁simply'[C] 0.35, '▁merely'[C] 0.35, '▁only'[B] 0.26, '▁Only'[N] 0.19, '▁even'[B] 0.10, '▁simple'[C] 0.10, '▁actually'[C] 0.09

=== feature 91  width=39  rho=2.69 ===
  Gemini  : This feature vector represents concepts of addition, differentiation, and alternative or supplementary items.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁other'[B] 0.49, 'Other'[C] 0.39, '▁others'[B] 0.39, '▁another'[B] 0.28, 'Another'[N] 0.22, '▁more'[B] 0.20, '▁further'[C] 0.19, 'more'[C] 0.17, '▁otherwise'[C] 0.13, '▁also'[B] 0.12

=== feature 59  width=23  rho=2.66 ===
  Gemini  : This vector represents concepts related to methods, means, and ways of accomplishing something.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : 'means'[C] 0.41, '▁way'[B] 0.38, '▁mean'[C] 0.34, '▁ways'[B] 0.32, '▁meaning'[N] 0.31, 'way'[N] 0.25, '▁manner'[C] 0.25, '▁meant'[N] 0.23, '▁reason'[C] 0.19, '▁reasons'[B] 0.18

=== feature 18  width=51  rho=2.63 ===
  Gemini  : This vector represents logical negation, exclusion, and quantifiers of duality or totality.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁no'[B] 0.37, '▁neither'[C] 0.32, '▁not'[B] 0.32, '▁none'[C] 0.30, 'no'[B] 0.28, '▁NO'[N] 0.19, '▁Not'[N] 0.19, '▁never'[C] 0.19, '▁only'[B] 0.17, '▁all'[B] 0.15

=== feature 2  width=29  rho=2.51 ===
  Gemini  : This vector represents ordinal numbers and sequential ranking terms.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁fourth'[B] 0.40, '▁third'[B] 0.39, '▁fifth'[C] 0.38, '▁sixth'[B] 0.35, '▁seventh'[C] 0.32, '▁second'[B] 0.32, '▁first'[B] 0.21, '▁Second'[N] 0.20, '▁last'[B] 0.13, 'First'[C] 0.12

=== feature 17  width=67  rho=2.46 ===
  Gemini  : This vector represents the domain of journalism, news dissemination, and publishing media.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁publication'[B] 0.24, '▁press'[B] 0.23, '▁publishing'[C] 0.23, '▁media'[C] 0.21, '▁published'[B] 0.21, '▁publisher'[C] 0.21, '▁newspaper'[B] 0.20, '▁publishers'[C] 0.20, '▁publications'[N] 0.20, '▁Press'[C] 0.19

=== feature 35  width=28  rho=2.35 ===
  Gemini  : This vector is related to exemplification, demonstration, and pointing out similarities or specific instances.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁such'[B] 0.61, 'such'[N] 0.55, '▁these'[B] 0.22, '▁like'[B] 0.19, '▁this'[B] 0.17, 'These'[B] 0.15, '▁tales'[C] 0.14, '▁including'[B] 0.13, '▁example'[C] 0.13, 'Like'[B] 0.12

=== feature 14  width=20  rho=2.32 ===
  Gemini  : This feature vector activates on third-person pronouns and demonstrative determiners across multiple languages.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁they'[B] 0.48, 'They'[B] 0.44, '▁their'[B] 0.41, '▁them'[B] 0.37, '▁themselves'[C] 0.32, '▁Them'[C] 0.29, '▁this'[B] 0.14, '▁ich'[N] 0.11, ')['[N] 0.10, 'This'[B] 0.08

=== feature 0  width=37  rho=2.29 ===
  Gemini  : This feature vector represents units of time and temporal duration.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁years'[B] 0.37, '▁Years'[C] 0.32, '▁year'[B] 0.31, '▁decades'[C] 0.29, '▁decade'[C] 0.28, 'year'[B] 0.27, '▁Year'[C] 0.26, '▁months'[B] 0.25, '▁centuries'[N] 0.22, '▁century'[B] 0.20

=== feature 16  width=32  rho=2.22 ===
  Gemini  : This vector represents terms related to names, naming conventions, and linguistic identification.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁named'[B] 0.35, '▁name'[B] 0.33, '▁called'[B] 0.30, '▁titled'[C] 0.30, '▁names'[N] 0.29, 'titled'[C] 0.29, 'called'[N] 0.26, '▁namesake'[B] 0.24, '▁known'[C] 0.24, '▁title'[B] 0.23

=== feature 1  width=43  rho=2.06 ===
  Gemini  : This vector represents concepts of prior occurrence, sequence, or historical precedence.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁previous'[C] 0.31, '▁previously'[N] 0.29, '▁originally'[C] 0.29, '▁original'[B] 0.27, '▁earlier'[C] 0.26, '▁last'[B] 0.24, '▁initially'[C] 0.24, '▁first'[B] 0.23, '▁initial'[C] 0.23, '▁Originally'[N] 0.21

=== feature 67  width=20  rho=2.04 ===
  Gemini  : This vector activates for terms related to honors, awards, and competitive recognition.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁award'[B] 0.46, '▁Award'[B] 0.43, '▁awards'[C] 0.43, '▁Awards'[C] 0.41, '▁awarded'[N] 0.32, '▁Prizes'[C] 0.17, '▁winner'[N] 0.14, '▁medal'[N] 0.13, '▁grant'[N] 0.11, '▁nominated'[C] 0.11

=== feature 86  width=220  rho=2.02 ===
  Gemini  : These tokens represent the concept of magnitude, importance, or scale.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁high'[C] 0.16, '▁great'[B] 0.15, '▁big'[N] 0.14, '▁major'[N] 0.14, '▁important'[C] 0.13, '▁strong'[C] 0.12, '▁large'[B] 0.12, '▁real'[C] 0.12, '▁long'[C] 0.12, '▁main'[C] 0.11

=== feature 66  width=239  rho=2.01 ===
  Gemini  : This vector represents abstract nouns denoting general categories, classifications, or structural elements.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁question'[N] 0.11, '▁site'[C] 0.11, '▁issue'[C] 0.11, '▁area'[B] 0.11, '▁process'[B] 0.11, '▁line'[B] 0.11, '▁story'[B] 0.11, '▁section'[C] 0.10, '▁point'[B] 0.10, '▁style'[B] 0.10

=== feature 96  width=23  rho=21.86 ===
  Gemini  : This vector represents the concept of comparison, contrast, and evaluation of differences between entities.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁compared'[C] 0.39, '▁against'[B] 0.35, '▁Against'[C] 0.33, '▁vs'[C] 0.31, '▁comparing'[C] 0.29, 'Comparing'[C] 0.27, '▁opposed'[C] 0.25, '▁contrast'[C] 0.22, 'opposed'[N] 0.19, 'compar'[C] 0.19

=== feature 60  width=11  rho=14.69 ===
  Gemini  : This vector represents the concept of completeness or fractional quantity.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁half'[C] 0.54, 'half'[B] 0.52, '▁Half'[C] 0.50, '▁full'[C] 0.25, 'full'[C] 0.23, '▁partial'[C] 0.19, '▁whole'[B] 0.10, '▁almost'[C] 0.08, '▁complete'[N] 0.08, '▁fifty'[C] 0.08

=== feature 8  width=16  rho=14.25 ===
  Gemini  : This vector represents the concept of physical motion and locomotion.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁go'[C] 0.36, '▁goes'[B] 0.34, 'going'[C] 0.32, 'coming'[C] 0.32, '▁coming'[C] 0.31, '▁Go'[C] 0.30, '▁went'[B] 0.30, 'gone'[C] 0.28, '▁comes'[C] 0.23, '▁came'[N] 0.22

=== feature 12  width=25  rho=7.55 ===
  Gemini  : This feature vector represents concepts of similarity, comparison, and resemblance between things.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁similar'[B] 0.44, '▁same'[B] 0.43, '▁identical'[B] 0.32, 'Similarly'[C] 0.32, '▁like'[B] 0.26, 'Like'[B] 0.23, '▁similarities'[C] 0.23, '▁resemble'[C] 0.22, '▁resembles'[C] 0.22, '▁parallels'[C] 0.16

=== feature 13  width=22  rho=6.99 ===
  Gemini  : This feature vector represents common action verbs and their various inflectional forms.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁make'[B] 0.43, '▁making'[C] 0.42, '▁made'[B] 0.39, '▁makes'[C] 0.39, 'made'[C] 0.37, '▁mak'[C] 0.27, '▁makeup'[N] 0.16, '▁giving'[N] 0.10, 'give'[C] 0.10, '▁gave'[B] 0.09

=== feature 93  width=117  rho=5.88 ===
  Gemini  : These tokens represent third-person singular present tense action verbs.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁is'[B] 0.18, '▁has'[B] 0.14, '▁gives'[C] 0.14, '▁comes'[C] 0.14, '▁allows'[C] 0.14, '▁goes'[B] 0.14, '▁takes'[C] 0.14, '▁does'[C] 0.13, '▁involves'[C] 0.13, '▁assumes'[C] 0.13

=== feature 9  width=74  rho=5.61 ===
  Gemini  : This vector activates on verbs and terms used to attribute speech, claims, or reports to a source.

In [25]:
members = cand[cand["is_member"] == True].sort_values("ratio_abs", ascending=False)
print(f"{len(members)} / {len(cand)} candidates have is_member=True\n")

for _, row in members.iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini  : {row['description']}")
    print(f"  verdict : confidence={row['confidence']:.2f}  -> {'SELECTED' if row['selected'] else 'rejected (confidence < ' + str(CONFIDENCE) + ')'}")
    print("  tokens  : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

1 / 63 candidates have is_member=True

=== feature 46  width=48  rho=129.35 ===
  Gemini  : This vector is related to characters, locations, and terminology from the Harry Potter universe.
  verdict : confidence=1.00  -> SELECTED
  tokens  : 'ffindor'[C] 0.36, 'therin'[C] 0.30, 'umbledore'[C] 0.24, '▁Dumbledore'[C] 0.21, '▁Weasley'[C] 0.20, '▁Malfoy'[C] 0.19, '▁Hogwarts'[C] 0.19, '▁Rowling'[C] 0.19, '▁Potter'[C] 0.19, 'Hermione'[C] 0.18

### 3.2.f Inspect the selected features

Table 3 of the paper reports only 1–3 embedding features per concept (Harry Potter on Gemma: 1).
Each selected feature should be a tight cluster of concept-specific tokens.

With variable widths a selected feature can be wider or narrower than the paper's $\lceil 0.01|V^*|\rceil$; its width is printed
with it, and 3.2.f-w compares the $F_C$ widths with the distribution over all $k$ features.

In [26]:
if not F_C:
    print("No feature passed both filters (F_C is empty).")

for feat in F_C:
    row = cand.loc[cand["feature"] == feat].iloc[0]
    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f}  conf={row['confidence']:.2f} ===")
    print(f"  {row['description']}")
    print("  tokens:", ", ".join(f"{t!r}[{l[0]}]" for t, l in zip(row["activating_tokens"][:30], row["labels"][:30])))
    print()

=== feature 46  width=48  rho=129.35  conf=1.00 ===
  This vector is related to characters, locations, and terminology from the Harry Potter universe.
  tokens: 'ffindor'[H], 'therin'[H], 'umbledore'[H], ' Dumbledore'[H], ' Weasley'[H], ' Malfoy'[H], ' Hogwarts'[H], ' Rowling'[H], ' Potter'[H], 'Hermione'[H], ' Hermione'[H], 'demort'[H], ' Voldemort'[H], 'Potter'[H], ' Harry'[H], ' Snape'[H], 'Harry'[H], 'magic'[H], 'Magic'[H], ' magic'[H], ' Draco'[H], 'Hog'[H], ' Severus'[H], ' Magic'[b], ' Gry'[H], ' Hog'[H], ' Ginny'[H], 'otts'[H], 'warts'[H], ' Granger'[H]

In [27]:
# 3.2.f-w Widths of the selected concept features vs. all k features of this fit
w_rank = torch.argsort(torch.argsort(-widths.double(), stable=True), stable=True)   # 0 = widest
print(f"[{VARIANT}] all features: widths min={int(widths.min())}  median={int(widths.median())}  max={int(widths.max())}")
if F_C:
    print(f"F_C widths: " + ", ".join(f"{f}: {int(widths[f])} (rank {int(w_rank[f]) + 1}/{RANK} by width, "
                                      f"{(widths < widths[f]).double().mean():.0%} of features narrower)" for f in F_C))
    print(f"F_C total width = {int(widths[F_C].sum())}   distinct tokens = "
          f"{len({j for f in F_C for j in torch.nonzero(Y[f]).flatten().tolist()})}")
    if len(cand):
        print(f"all rho >= tau candidates: median width = {int(widths[cand['feature'].astype(int).tolist()].median())}")
else:
    print("F_C is empty.")

[m1] all features: widths min=10  median=29  max=239
F_C widths: 46: 48 (rank 24/100 by width, 74% of features narrower)
F_C total width = 48   distinct tokens = 48
all rho >= tau candidates: median width = 28

In [28]:
# One column per selected feature: every token with nonzero Y_{i,t}, sorted by |Y_{i,t}|.
columns = {}
for feat in F_C:
    mags = Y[feat].abs()
    nz_idx = torch.nonzero(mags > 0).flatten()
    nz_idx = nz_idx[torch.argsort(mags[nz_idx], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in nz_idx])
    columns[f"feature {feat}"] = pd.Series(
        [f"{t} [{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, nz_idx)]
    )

wide = pd.DataFrame(columns).fillna("")
wide.index = range(1, len(wide) + 1)

all_cols = sorted({j for feat in F_C for j in torch.nonzero(Y[feat].abs() > 0).flatten().tolist()})
print(f"{len(F_C)} concept features, {len(all_cols)} distinct tokens "
      f"(C={sum(codes[j] == 1 for j in all_cols)}, N={sum(codes[j] == 0 for j in all_cols)}, "
      f"B={sum(codes[j] == 2 for j in all_cols)})")
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(wide)

1 concept features, 48 distinct tokens (C=44, N=1, B=3)

              feature 46
1       ffindor [C] 0.36
2        therin [C] 0.30
3     umbledore [C] 0.24
4   ▁Dumbledore [C] 0.21
5      ▁Weasley [C] 0.20
6       ▁Malfoy [C] 0.19
7     ▁Hogwarts [C] 0.19
8      ▁Rowling [C] 0.19
9       ▁Potter [C] 0.19
10     Hermione [C] 0.18
11    ▁Hermione [C] 0.18
12       demort [C] 0.18
13   ▁Voldemort [C] 0.17
14       Potter [C] 0.16
15       ▁Harry [C] 0.16
16       ▁Snape [C] 0.16
17        Harry [C] 0.15
18        magic [C] 0.14
19        Magic [C] 0.14
20       ▁magic [C] 0.13
21       ▁Draco [C] 0.13
22          Hog [C] 0.12
23     ▁Severus [C] 0.12
24       ▁Magic [B] 0.12
25         ▁Gry [C] 0.12
26         ▁Hog [C] 0.11
27       ▁Ginny [C] 0.11
28         otts [C] 0.10
29        warts [C] 0.10
30     ▁Granger [C] 0.09
31     ▁magical [C] 0.08
32       ▁Lupin [C] 0.08
33      magical [C] 0.08
34       ▁Remus [C] 0.08
35          ▁JK [C] 0.08
36         ▁Sly [C] 0.08
37      ▁Sirius [C] 0.07
38       ▁Beaux [B] 0.07
39    ▁Sherlock [C] 0.06
40         ▁McG [C] 0.06
41          idd [C] 0.06
42         ▁Hag [C] 0.06
43         ▁Ron [C] 0.06
44      ▁Holmes [C] 0.06
45         ▁Mug [B] 0.06
46        ▁wand [C] 0.06
47           HP [N] 0.05
48     ▁Magical [C] 0.05

In [29]:
TOP_N = 30
E_ref = E_vstar_X.float().cpu()  # X-space rows = transform(E_vstar): the space Z lives in
token_strs = tokenizer.convert_ids_to_tokens(vstar_ids)

group_masks = {
    "C": codes == 1,
    "C / B": (codes == 1) | (codes == 2),
    "C / B / N": np.ones_like(codes, dtype=bool),
}

for feat in F_C:
    y = Y[feat]
    # z's sign is arbitrary (Y can absorb it); orient it so its support tokens mostly have positive Y.
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots = E_ref @ z
    cos = dots / (E_ref.norm(dim=1) * z.norm())

    df = pd.DataFrame({
        "token": token_strs,
        "label": [LABEL_TAG[c] for c in codes],
        "dot": dots.numpy(),
        "cos": cos.numpy(),
        "Y": (sign * y).numpy(),
        "in_support": (y != 0).numpy(),
    })

    print(f"=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0} ===")
    for name, mask in group_masks.items():
        top = df[mask].sort_values("dot", ascending=False).head(TOP_N).reset_index(drop=True)
        top.index += 1
        print(f"\n-- {name}: {int(mask.sum())} tokens, top {TOP_N} by <e_t, z> --")
        display(top)

=== feature 46   ||z|| = 195.946   sign flipped: True ===

-- C: 1870 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  11879.779297  0.529105  0.361261        True
2        therin     C  10332.246094  0.528831  0.297708        True
3     umbledore     C   9059.843750  0.547460  0.238472        True
4     ▁Hogwarts     C   8154.627930  0.678740  0.192877        True
5   ▁Dumbledore     C   8027.695312  0.660264  0.208103        True
6      ▁Weasley     C   7336.247559  0.567936  0.203925        True
7       ▁Malfoy     C   7215.889648  0.595290  0.194578        True
8     ▁Hermione     C   7123.187500  0.641894  0.175686        True
9    ▁Voldemort     C   7105.919922  0.610808  0.168675        True
10     ▁Rowling     C   7003.209961  0.525450  0.188504        True
11      ▁Potter     C   6881.388184  0.541288  0.188472        True
12       demort     C   6836.748047  0.421732  0.175487        True
13     Hermione     C   6774.737305  0.533436  0.178623        True
14       ▁Harry     C   6265.991211  0.539285  0.162169        True
15       ▁Snape     C   5939.579102  0.520513  0.156795        True
16       Potter     C   5878.796875  0.474433  0.164065        True
17        Harry     C   5848.928711  0.531310  0.153121        True
18      ▁wizard     C   5664.578125  0.420167  0.000000       False
19     ▁wizards     C   5421.430664  0.426441  0.000000       False
20      ▁Wizard     C   4870.067383  0.377509  0.000000       False
21     ▁Severus     C   4805.299805  0.423506  0.122459        True
22       wizard     C   4685.658203  0.351760  0.000000       False
23       ▁Draco     C   4613.373535  0.436868  0.127116        True
24          Hog     C   4501.025391  0.341112  0.123218        True
25       ▁magic     C   4436.203613  0.253938 -0.133065        True
26     ▁Magical     C   4169.635742  0.313251 -0.051687        True
27     ▁magical     C   4133.061523  0.290915 -0.084425        True
28         ▁Gry     C   4095.434082  0.340348  0.120103        True
29         ▁Hog     C   3977.402832  0.296173  0.111003        True
30     ▁witches     C   3929.928223  0.317737  0.000000       False

-- C / B: 2551 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  11879.779297  0.529105  0.361261        True
2        therin     C  10332.246094  0.528831  0.297708        True
3     umbledore     C   9059.843750  0.547460  0.238472        True
4     ▁Hogwarts     C   8154.627930  0.678740  0.192877        True
5   ▁Dumbledore     C   8027.695312  0.660264  0.208103        True
6      ▁Weasley     C   7336.247559  0.567936  0.203925        True
7       ▁Malfoy     C   7215.889648  0.595290  0.194578        True
8     ▁Hermione     C   7123.187500  0.641894  0.175686        True
9    ▁Voldemort     C   7105.919922  0.610808  0.168675        True
10     ▁Rowling     C   7003.209961  0.525450  0.188504        True
11      ▁Potter     C   6881.388184  0.541288  0.188472        True
12       demort     C   6836.748047  0.421732  0.175487        True
13     Hermione     C   6774.737305  0.533436  0.178623        True
14       ▁Harry     C   6265.991211  0.539285  0.162169        True
15       ▁Snape     C   5939.579102  0.520513  0.156795        True
16       Potter     C   5878.796875  0.474433  0.164065        True
17        Harry     C   5848.928711  0.531310  0.153121        True
18      ▁wizard     C   5664.578125  0.420167  0.000000       False
19     ▁wizards     C   5421.430664  0.426441  0.000000       False
20      ▁Wizard     C   4870.067383  0.377509  0.000000       False
21     ▁Severus     C   4805.299805  0.423506  0.122459        True
22       wizard     C   4685.658203  0.351760  0.000000       False
23       ▁Draco     C   4613.373535  0.436868  0.127116        True
24          Hog     C   4501.025391  0.341112  0.123218        True
25       ▁magic     C   4436.203613  0.253938 -0.133065        True
26       ▁Magic     B   4209.687500  0.253265 -0.120966        True
27     ▁Magical     C   4169.635742  0.313251 -0.051687        True
28     ▁magical     C   4133.061523  0.290915 -0.084425        True
29         ▁Gry     C   4095.434082  0.340348  0.120103        True
30         ▁Hog     C   3977.402832  0.296173  0.111003        True

-- C / B / N: 4780 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  11879.779297  0.529105  0.361261        True
2        therin     C  10332.246094  0.528831  0.297708        True
3     umbledore     C   9059.843750  0.547460  0.238472        True
4     ▁Hogwarts     C   8154.627930  0.678740  0.192877        True
5   ▁Dumbledore     C   8027.695312  0.660264  0.208103        True
6      ▁Weasley     C   7336.247559  0.567936  0.203925        True
7       ▁Malfoy     C   7215.889648  0.595290  0.194578        True
8     ▁Hermione     C   7123.187500  0.641894  0.175686        True
9    ▁Voldemort     C   7105.919922  0.610808  0.168675        True
10     ▁Rowling     C   7003.209961  0.525450  0.188504        True
11      ▁Potter     C   6881.388184  0.541288  0.188472        True
12       demort     C   6836.748047  0.421732  0.175487        True
13     Hermione     C   6774.737305  0.533436  0.178623        True
14       ▁Harry     C   6265.991211  0.539285  0.162169        True
15       ▁Snape     C   5939.579102  0.520513  0.156795        True
16       Potter     C   5878.796875  0.474433  0.164065        True
17        Harry     C   5848.928711  0.531310  0.153121        True
18      ▁wizard     C   5664.578125  0.420167  0.000000       False
19     ▁wizards     C   5421.430664  0.426441  0.000000       False
20      ▁Wizard     C   4870.067383  0.377509  0.000000       False
21     ▁Severus     C   4805.299805  0.423506  0.122459        True
22       wizard     C   4685.658203  0.351760  0.000000       False
23       ▁Draco     C   4613.373535  0.436868  0.127116        True
24          Hog     C   4501.025391  0.341112  0.123218        True
25       ▁magic     C   4436.203613  0.253938 -0.133065        True
26       ▁Magic     B   4209.687500  0.253265 -0.120966        True
27     ▁Magical     C   4169.635742  0.313251 -0.051687        True
28     ▁magical     C   4133.061523  0.290915 -0.084425        True
29         ▁Gry     C   4095.434082  0.340348  0.120103        True
30         ▁Hog     C   3977.402832  0.296173  0.111003        True

In [30]:
E_unit = E_ref / E_ref.norm(dim=1, keepdim=True)

for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots_unit = E_unit @ z

    df_unit = pd.DataFrame({
        "token": token_strs,
        "label": [LABEL_TAG[c] for c in codes],
        "dot_unit": dots_unit.numpy(),
        "||e_t||": E_ref.norm(dim=1).numpy(),
        "Y": (sign * y).numpy(),
        "in_support": (y != 0).numpy(),
    })

    print(f"=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0} ===")
    for name, mask in group_masks.items():
        top = df_unit[mask].sort_values("dot_unit", ascending=False).head(TOP_N).reset_index(drop=True)
        top.index += 1
        print(f"\n-- {name}: {int(mask.sum())} tokens, top {TOP_N} by <e_t / ||e_t||, z> --")
        display(top)

=== feature 46   ||z|| = 195.946   sign flipped: True ===

-- C: 1870 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  132.996490   61.314606  0.192877        True
2   ▁Dumbledore     C  129.376083   62.049290  0.208103        True
3     ▁Hermione     C  125.776596   56.633656  0.175686        True
4    ▁Voldemort     C  119.685394   59.371643  0.168675        True
5       ▁Malfoy     C  116.644760   61.862099  0.194578        True
6      ▁Weasley     C  111.284821   65.923157  0.203925        True
7     umbledore     C  107.272659   84.456223  0.238472        True
8       ▁Potter     C  106.063316   64.879997  0.188472        True
9        ▁Harry     C  105.670853   59.297260  0.162169        True
10     Hermione     C  104.524612   64.814766  0.178623        True
11        Harry     C  104.108063   56.181328  0.153121        True
12      ffindor     C  103.676102  114.585510  0.361261        True
13       therin     C  103.622375   99.710571  0.297708        True
14     ▁Rowling     C  102.959946   68.018776  0.188504        True
15       ▁Snape     C  101.992447   58.235474  0.156795        True
16       Potter     C   92.963249   63.237858  0.164065        True
17       ▁Draco     C   85.602570   53.892937  0.127116        True
18     ▁wizards     C   83.559410   64.881165  0.000000       False
19     ▁Severus     C   82.984360   57.906090  0.122459        True
20       demort     C   82.636749   82.732544  0.175487        True
21      ▁wizard     C   82.330093   68.803253  0.000000       False
22      ▁Wizard     C   73.971481   65.837097  0.000000       False
23       ▁Ginny     C   73.497375   52.009193  0.107393        True
24       wizard     C   68.926010   67.980980  0.000000       False
25          Hog     C   66.839478   67.340813  0.123218        True
26         ▁Gry     C   66.689758   61.410217  0.120103        True
27        ▁wand     C   63.811214   59.361305  0.059630        True
28     ▁witches     C   62.259396   63.121853  0.000000       False
29     ▁Magical     C   61.380283   67.931183 -0.051687        True
30     ▁Wizards     C   60.547237   62.352810  0.000000       False

-- C / B: 2551 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  132.996490   61.314606  0.192877        True
2   ▁Dumbledore     C  129.376083   62.049290  0.208103        True
3     ▁Hermione     C  125.776596   56.633656  0.175686        True
4    ▁Voldemort     C  119.685394   59.371643  0.168675        True
5       ▁Malfoy     C  116.644760   61.862099  0.194578        True
6      ▁Weasley     C  111.284821   65.923157  0.203925        True
7     umbledore     C  107.272659   84.456223  0.238472        True
8       ▁Potter     C  106.063316   64.879997  0.188472        True
9        ▁Harry     C  105.670853   59.297260  0.162169        True
10     Hermione     C  104.524612   64.814766  0.178623        True
11        Harry     C  104.108063   56.181328  0.153121        True
12      ffindor     C  103.676102  114.585510  0.361261        True
13       therin     C  103.622375   99.710571  0.297708        True
14     ▁Rowling     C  102.959946   68.018776  0.188504        True
15       ▁Snape     C  101.992447   58.235474  0.156795        True
16       Potter     C   92.963249   63.237858  0.164065        True
17       ▁Draco     C   85.602570   53.892937  0.127116        True
18     ▁wizards     C   83.559410   64.881165  0.000000       False
19     ▁Severus     C   82.984360   57.906090  0.122459        True
20       demort     C   82.636749   82.732544  0.175487        True
21      ▁wizard     C   82.330093   68.803253  0.000000       False
22      ▁Wizard     C   73.971481   65.837097  0.000000       False
23       ▁Ginny     C   73.497375   52.009193  0.107393        True
24       wizard     C   68.926010   67.980980  0.000000       False
25          Hog     C   66.839478   67.340813  0.123218        True
26         ▁Gry     C   66.689758   61.410217  0.120103        True
27        ▁wand     C   63.811214   59.361305  0.059630        True
28     ▁witches     C   62.259396   63.121853  0.000000       False
29     ▁Magical     C   61.380283   67.931183 -0.051687        True
30     ▁Wizards     C   60.547237   62.352810  0.000000       False

-- C / B / N: 4780 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  132.996490   61.314606  0.192877        True
2   ▁Dumbledore     C  129.376083   62.049290  0.208103        True
3     ▁Hermione     C  125.776596   56.633656  0.175686        True
4    ▁Voldemort     C  119.685394   59.371643  0.168675        True
5       ▁Malfoy     C  116.644760   61.862099  0.194578        True
6      ▁Weasley     C  111.284821   65.923157  0.203925        True
7     umbledore     C  107.272659   84.456223  0.238472        True
8       ▁Potter     C  106.063316   64.879997  0.188472        True
9        ▁Harry     C  105.670853   59.297260  0.162169        True
10     Hermione     C  104.524612   64.814766  0.178623        True
11        Harry     C  104.108063   56.181328  0.153121        True
12      ffindor     C  103.676102  114.585510  0.361261        True
13       therin     C  103.622375   99.710571  0.297708        True
14     ▁Rowling     C  102.959946   68.018776  0.188504        True
15       ▁Snape     C  101.992447   58.235474  0.156795        True
16       Potter     C   92.963249   63.237858  0.164065        True
17       ▁Draco     C   85.602570   53.892937  0.127116        True
18     ▁wizards     C   83.559410   64.881165  0.000000       False
19     ▁Severus     C   82.984360   57.906090  0.122459        True
20       demort     C   82.636749   82.732544  0.175487        True
21      ▁wizard     C   82.330093   68.803253  0.000000       False
22      ▁Wizard     C   73.971481   65.837097  0.000000       False
23       ▁Ginny     C   73.497375   52.009193  0.107393        True
24       wizard     C   68.926010   67.980980  0.000000       False
25          Hog     C   66.839478   67.340813  0.123218        True
26         ▁Gry     C   66.689758   61.410217  0.120103        True
27        ▁wand     C   63.811214   59.361305  0.059630        True
28     ▁witches     C   62.259396   63.121853  0.000000       False
29     ▁Magical     C   61.380283   67.931183 -0.051687        True
30     ▁Wizards     C   60.547237   62.352810  0.000000       False

In [31]:
TOP_K_COUNT = 100

rows = []
for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    rankings = {
        "<e_t, z>": E_ref @ z,
        "<e_t / ||e_t||, z>": E_unit @ z,
    }
    for name, scores in rankings.items():
        top = torch.argsort(scores, descending=True)[:TOP_K_COUNT].numpy()
        rows.append({
            "feature": feat,
            "ranking": name,
            "C": int((codes[top] == 1).sum()),
            "B": int((codes[top] == 2).sum()),
            "N": int((codes[top] == 0).sum()),
            "C in support": int(((codes[top] == 1) & (y[top] != 0).numpy()).sum()),
        })

print(f"Label counts among the top {TOP_K_COUNT} of all {len(vstar_ids)} tokens in V* "
      f"(base rate: C={(codes == 1).mean():.1%}, B={(codes == 2).mean():.1%}, N={(codes == 0).mean():.1%})")
pd.DataFrame(rows)

Label counts among the top 100 of all 4780 tokens in V* (base rate: C=39.1%, B=14.2%, N=46.6%)

   feature             ranking   C  B  N  C in support
0       46            <e_t, z>  90  9  1            44
1       46  <e_t / ||e_t||, z>  90  5  5            44

### 3.2.g Extended token set: every sentence of the concept's Wikipedia page, $Z$ fixed
$S_C^{ext} = S_C \cup$ all sentences of the article, $S_N^{ext} = S_N \cup$ as many neutral sentences. The new rows go through the **same** transform $T$ fitted in 3.1.c′ (nothing re-estimated), then only a sparse $Y_{ext}$ is fitted against the frozen X-space $Z$; feature $i$ keeps its 3.1.d width scaled to the larger set, $m_i^{ext} = \mathrm{round}(m_i\,|V^*_{ext}|/|V^*|)$, by $|Y^{dense}_{ext}|$ (refit off, as in 3.1.d). Groups: C / B / N = label in the original $V^*$ (3.2.a), C\* / B\* / N\* = label on the extended sentences; a token gets the first group it matches in the order C, C\*, B, B\*, N, N\*.

In [32]:
# ---- Extended E*: all sentences of the concept's Wikipedia page, Z from 3.1.d fixed, only a sparse Y_ext refit ----
# S_C^ext = S_C + every sentence of the live English Wikipedia article; S_N^ext = S_N + as many neutral sentences
# (one per page of the local wikimedia/wikipedia sample). The new sentences are cached next to RUN_DIR, so re-runs
# use the same page revision and sample.
# Rows go to X-space with the transform T of 3.1.c' exactly as fitted there (same mu_B, W, S_eta: nothing re-estimated),
# then Y_ext = top-m_i per row of (Z^T Z + lambda I)^{-1} Z^T X_ext^T: the Y-step of 3.1.d with Z frozen and the same lambda;
# feature i keeps its 3.1.d width scaled to the larger set, m_i^ext = round(width_i * |V*_ext| / |V*|).
import random
import sys

from experiments.varwidth.common import mask_from_row_widths

sys.path.insert(0, "experiments/resample_sentences")
from fetch_en_sentences import neutral_sentences, page_paragraphs, split_sentences

EXT_PATH = RUN_DIR.parent / "ext_sentences.json"   # shared by the five variable-width variants of this concept
EXT_GROUPS = ["C", "C*", "B", "B*", "N", "N*"]

# 1) sentences
ext = load_json(EXT_PATH, None)
if ext is None:
    canon, revid, paras = page_paragraphs(CONCEPT)
    page_sents = split_sentences(paras)
    ext = {"title": canon, "revid": revid, "concept": page_sents,
           "neutral": [r["sentence"] for r in neutral_sentences(
               Path("experiments/resample_sentences/data/wiki_dump_pages.jsonl"), len(page_sents),
               random.Random(SEED), exclude=set(page_sents))]}
    save_json(EXT_PATH, ext)
ext_concept = list(dict.fromkeys([s for s, lbl in dataset if lbl == CONCEPT] + ext["concept"]))
ext_neutral = list(dict.fromkeys([s for s, lbl in dataset if lbl != CONCEPT] + ext["neutral"]))
print(f"'{ext['title']}' rev {ext['revid']}: {len(ext['concept'])} page sentences, {len(ext['neutral'])} new neutral "
      f"({EXT_PATH})\nS_C^ext = {len(ext_concept)} sentences   S_N^ext = {len(ext_neutral)} sentences")

# 2) extended token set (a superset of V*) and its groups
special_ext = set(tokenizer.all_special_ids)


def token_set(sents):
    return {int(t) for s in sents for t in tokenizer(s, add_special_tokens=False)["input_ids"]} - special_ext


c_ids, n_ids = token_set(ext_concept), token_set(ext_neutral)
vstar_ext = sorted(c_ids | n_ids | set(vstar_ids))
codes_ext = np.array([2 if t in c_ids and t in n_ids else 1 if t in c_ids else 0 for t in vstar_ext])
orig_code = dict(zip(vstar_ids, codes.tolist()))


def ext_group(t: int, c_ext: int) -> str:
    """First match in the order C, C*, B, B*, N, N* (C/B/N: label in V*, starred: label on the extended sentences)."""
    o = orig_code.get(t)
    for g, hit in [("C", o == 1), ("C*", c_ext == 1), ("B", o == 2), ("B*", c_ext == 2), ("N", o == 0), ("N*", c_ext == 0)]:
        if hit:
            return g


groups_ext = np.array([ext_group(t, int(c)) for t, c in zip(vstar_ext, codes_ext)])
print(f"|V*_ext| = {len(vstar_ext)}  (|V*| = {len(vstar_ids)}, {len(vstar_ext) - len(vstar_ids)} new)")
display(pd.Series(groups_ext).value_counts().reindex(EXT_GROUPS).fillna(0).astype(int).rename("tokens").to_frame().T)

# 3) X_ext = T(E_{V*_ext}): the 3.1.c' transform, unchanged
ids_ext = torch.tensor(vstar_ext)
E_ext = E.index_select(0, ids_ext.to(E.device)).detach().float().cpu()
X_ext = transform(E_ext)                                                   # (|V*_ext|, d), X-space
pos_ext = {t: j for j, t in enumerate(vstar_ext)}
in_vstar = [pos_ext[t] for t in vstar_ids]
print(f"check: max |X_ext[V*] - E_vstar_X| = {(X_ext[in_vstar] - E_vstar_X.float().cpu()).abs().max():.2e}")

# 4) Y-step with Z frozen (dense ridge solve as in fit_varwidth, then each row's top m_i^ext; no refit, as CFG.refit=False)
A_ext = X_ext.T.contiguous().to(DEVICE)                                    # (d, |V*_ext|)
Z_dev = Z.to(DEVICE)
with Timer() as t_ext:
    inv_Z = torch.linalg.inv(Z_dev.T @ Z_dev + torch.eye(Z_dev.shape[1], device=DEVICE) * ridge_used)
    G_ext = A_ext.T @ Z_dev @ inv_Z                                        # (|V*_ext|, k), the G_ layout
    m_ext = (widths.double() * len(vstar_ext) / len(vstar_ids)).round().long().clamp(1, len(vstar_ext))
    Yd_ext = G_ext.T.contiguous()                                          # (k, |V*_ext|) dense
    Y_ext = (Yd_ext * mask_from_row_widths(Yd_ext.abs(), m_ext.to(Yd_ext.device))).float().cpu()   # (k, |V*_ext|)
A_ext_cpu = A_ext.cpu()
ext_err = (torch.norm(A_ext_cpu - Z @ Y_ext) / torch.norm(A_ext_cpu)).item()
print(f"fixed-Z fit: {t_ext['elapsed']:.3f}s, each feature keeps its 3.1.d width x |V*_ext|/|V*|: "
      f"{int(m_ext.min())}-{int(m_ext.max())} tokens per feature, {int(m_ext.sum())} in total")
print(f"relative error: on X_ext (fixed Z) = {ext_err:.4f}   3.1.d joint fit on A = {rel_err:.4f}")
del A_ext, Z_dev, G_ext, Yd_ext, A_ext_cpu, E_ext

'Harry Potter' rev 1379437311: 403 page sentences, 403 new neutral (runs/variable_width/Harry_Potter/ext_sentences.json)
S_C^ext = 444 sentences   S_N^ext = 682 sentences
|V*_ext| = 7408  (|V*| = 4780, 2628 new)

           C   C*    B   B*     N    N*
tokens  1870  465  681  158  2138  2096

check: max |X_ext[V*] - E_vstar_X| = 0.00e+00
fixed-Z fit: 0.016s, each feature keeps its 3.1.d width x |V*_ext|/|V*|: 15-370 tokens per feature, 7441 in total
relative error: on X_ext (fixed Z) = 0.8773   3.1.d joint fit on A = 0.8510

In [33]:
# ---- Rate every token of V*_ext on each concept feature, then list the feature's Y_ext support (X-space, where Z lives) ----
#   <x_t, z~>            inner product of the transformed token row with the feature direction
#   <x_t / ||x_t||, z~>  the same with the token row normalized
#   words                whole words of S_C^ext and S_N^ext the token was cut from (most frequent first)
# z~'s sign is arbitrary (Y absorbs it): oriented as in 3.2.f, so its 3.1 support tokens mostly have positive Y.
# Support table: tokens with Y_ext[feat, t] != 0, by decreasing |Y_ext|; group = first match in C, C*, B, B*, N, N* (3.2.g);
# in V*: the token is in the original token set;  in original support: Y[feat, t] != 0 in the 3.1 fit.
import re
from collections import Counter, defaultdict

SHOW_ROWS = 100   # rows shown per ranking; None shows all |V*_ext| tokens (the full tables are in ext_rating)

WORD_RE = re.compile(r"\w+(?:['’-]\w+)*")
token_words_ext = defaultdict(Counter)  # token id -> Counter of source words
for sent in ext_concept + ext_neutral:
    enc = tokenizer(sent, add_special_tokens=False, return_offsets_mapping=True)
    words = [(m.start(), m.end(), m.group()) for m in WORD_RE.finditer(sent)]
    for tid, (s, e) in zip(enc["input_ids"], enc["offset_mapping"]):
        for ws, we, w in words:
            if ws < e and s < we:  # token's character span overlaps this word
                token_words_ext[tid][w] += 1
words_ext = [[w for w, _ in token_words_ext[t].most_common()] for t in vstar_ext]

ext_strs = tokenizer.convert_ids_to_tokens(vstar_ext)
x_norms = X_ext.norm(dim=1)
vstar_set = set(vstar_ids)
ext_rating, ext_support = {}, {}
for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots = X_ext @ z
    orig_sup = {vstar_ids[j] for j in torch.nonzero(y).flatten().tolist()}
    ext_sup = (Y_ext[feat] != 0).numpy()

    # 1) every token of V*_ext, ranked by the two inner products
    # support: first match of (original: in this direction's 3.1 support, extended: in its Y_ext support, none)
    df = pd.DataFrame({
        "token": ext_strs,
        "group": groups_ext,
        "words": words_ext,
        "support": ["original" if t in orig_sup else "extended" if e else "none" for t, e in zip(vstar_ext, ext_sup)],
        "<x_t, z>": dots.numpy(),
        "<x_t / ||x_t||, z>": (dots / x_norms).numpy(),
        "||x_t||": x_norms.numpy(),
        "Y_ext": (sign * Y_ext[feat]).numpy(),
        "in Y_ext support": (Y_ext[feat] != 0).numpy(),
    })
    ext_rating[feat] = df

    print(f"{'=' * 100}\n=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0}   "
          f"|V*_ext| = {len(df)}   Y_ext support = {int(df['in Y_ext support'].sum())} ===\n{'=' * 100}")
    by_group = df.groupby("group")[["<x_t, z>", "<x_t / ||x_t||, z>"]].agg(["mean", "median", "max"])
    by_group.insert(0, "tokens", df["group"].value_counts())
    display(by_group.reindex(EXT_GROUPS).style.format("{:.3f}", subset=by_group.columns[1:]))
    for col in ["<x_t, z>", "<x_t / ||x_t||, z>"]:
        ranked = df.sort_values(col, ascending=False, ignore_index=True)
        ranked.index += 1
        print(f"\n-- all {len(df)} tokens of V*_ext by {col} (top {SHOW_ROWS or len(df)} shown) --")
        with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
            display(ranked if SHOW_ROWS is None else ranked.head(SHOW_ROWS))

    # 2) the feature's Y_ext support, by decreasing |Y_ext|
    sup = torch.nonzero(Y_ext[feat]).flatten()
    sup = sup[torch.argsort(Y_ext[feat, sup].abs(), descending=True)].tolist()
    sup_df = pd.DataFrame({
        "token": [ext_strs[j] for j in sup],
        "group": groups_ext[sup],
        "words": [words_ext[j] for j in sup],
        "Y_ext": (sign * Y_ext[feat, sup]).numpy(),
        "in V*": [vstar_ext[j] in vstar_set for j in sup],
        "in original support": [vstar_ext[j] in orig_sup for j in sup],
        "<x_t, z>": dots[sup].numpy(),
        "<x_t / ||x_t||, z>": (dots[sup] / x_norms[sup]).numpy(),
    }, index=pd.RangeIndex(1, len(sup) + 1, name="rank"))
    ext_support[feat] = sup_df

    lost = sorted(orig_sup - {vstar_ext[j] for j in sup})
    counts = "  ".join(f"{g}: {int((sup_df['group'] == g).sum())}" for g in EXT_GROUPS)
    print(f"\n-- Y_ext support: {len(sup_df)} tokens [{counts}] | in V*: {int(sup_df['in V*'].sum())} | "
          f"in original support: {int(sup_df['in original support'].sum())}/{len(orig_sup)} --")
    if lost:
        print(f"original support tokens no longer in the support ({len(lost)}): {tokenizer.convert_ids_to_tokens(lost)}")
    with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
        display(sup_df.style.format({"Y_ext": "{:+.4f}", "<x_t, z>": "{:.2f}", "<x_t / ||x_t||, z>": "{:.3f}"}))

====================================================================================================
=== feature 46   ||z|| = 195.946   sign flipped: True   |V*_ext| = 7408   Y_ext support = 74 ===
====================================================================================================

-- all 7408 tokens of V*_ext by <x_t, z> (top 100 shown) --

,token,group,words,support,"<x_t, z>","<x_t / ||x_t||, z>",||x_t||,Y_ext,in Y_ext support
1,ffindor,C,[Gryffindor],original,11879.779297,103.676102,114.585510,0.361261,True
2,therin,C,[Slytherin's],original,10332.246094,103.622375,99.710571,0.297708,True
3,umbledore,C,"[Dumbledore's, Dumbledore]",original,9059.843750,107.272659,84.456223,0.238472,True
4,▁Hogwarts,C,[Hogwarts],original,8154.627930,132.996506,61.314606,0.192877,True
5,▁Dumbledore,C,"[Dumbledore, Dumbledore's]",original,8027.695312,129.376099,62.049290,0.208103,True
6,▁Weasley,C,[Weasley],original,7336.247559,111.284836,65.923157,0.203925,True
7,▁Malfoy,C,[Malfoy],original,7215.889648,116.644760,61.862099,0.194578,True
8,▁Hermione,C,"[Hermione, Hermione's]",original,7123.187500,125.776581,56.633656,0.175686,True
9,▁Voldemort,C,"[Voldemort, Voldemort's]",original,7105.919922,119.685417,59.371643,0.168675,True
10,▁Rowling,C,"[Rowling, Rowling's]",original,7003.209961,102.959953,68.018776,0.188504,True
11,▁Potter,C,"[Potter, Potter's, Potter-themed, Pottermore, Potter's's]",original,6881.388184,106.063324,64.879997,0.188472,True
12,demort,C,[Voldemort],original,6836.748047,82.636742,82.732544,0.175487,True
13,Hermione,C,[Hermione],original,6774.737305,104.524597,64.814766,0.178623,True
14,▁Harry,C,"[Harry, Harry's, Harryplax]",original,6265.991211,105.670837,59.297260,0.162169,True
15,▁Snape,C,"[Snape, Snape's]",original,5939.579102,101.992455,58.235474,0.156795,True
16,Potter,C,[Pottermore],original,5878.796875,92.963249,63.237858,0.164065,True
17,Harry,C,"[Harry, Harry's]",original,5848.928711,104.108055,56.181328,0.153121,True
18,▁wizard,C,"[wizard, wizarding]",none,5664.578125,82.330093,68.803253,0.000000,False
19,▁wizards,C,[wizards],none,5421.430664,83.559395,64.881165,0.000000,False
20,▁Wizard,C,"[Wizarding, Wizardry, WizardingWorld]",none,4870.067383,73.971481,65.837097,0.000000,False
21,▁Severus,C,[Severus],original,4805.299805,82.984360,57.906090,0.122459,True
22,wizard,C,[Triwizard],none,4685.658203,68.926018,67.980980,0.000000,False
23,▁Draco,C,[Draco],original,4613.373535,85.602562,53.892937,0.127116,True
24,Hog,C,[Hogwarts],original,4501.025391,66.839485,67.340813,0.123218,True
25,▁magic,C,[magic],original,4436.203613,49.758179,89.155266,-0.133065,True
26,▁Magic,B,[Magic],original,4209.687500,49.626301,84.827751,-0.120966,True
27,▁Magical,C,[Magical],original,4169.635742,61.380291,67.931183,-0.051687,True
28,▁magical,C,[magical],original,4133.061523,57.003654,72.505203,-0.084425,True
29,▁Gry,C,[Gryffindor],original,4095.434082,66.689781,61.410217,0.120103,True
30,▁Hog,C,[Hogsmeade],original,3977.402832,58.033875,68.535881,0.111003,True
31,▁witches,C,[witches],none,3929.928223,62.259392,63.121853,0.000000,False
32,warts,C,[Hogwarts],original,3834.716797,51.039993,75.131607,0.101129,True
33,▁Ginny,C,[Ginny],original,3822.539307,73.497375,52.009193,0.107393,True
34,▁wand,C,[wand],original,3787.916992,63.811214,59.361305,0.059630,True
35,▁Wizards,C,[Wizards],none,3775.289795,60.547230,62.352810,0.000000,False
36,▁witch,C,[witch],none,3738.960938,53.521141,69.859512,0.000000,False
37,Magic,C,[Magic],original,3733.947754,43.586025,85.668465,-0.137874,True
38,otts,C,[Gringotts],original,3674.495605,47.812065,76.852898,0.104232,True
39,magical,C,[non-magical],original,3640.880859,51.700199,70.422958,-0.081716,True
40,magic,C,[magic],original,3613.465088,42.239155,85.547760,-0.142666,True
41,▁witchcraft,C,[witchcraft],none,3566.260742,58.518898,60.942036,-0.000000,False
42,▁Witch,C,[Witchcraft],none,3486.630127,53.796112,64.811935,0.000000,False
43,▁Remus,C,[Remus],original,3344.109375,56.777096,58.898914,0.080787,True
44,▁Tolkien,C*,[Tolkien's],extended,3163.340332,61.073509,51.795620,0.074984,True
45,▁potions,C,[potions],extended,3048.092285,56.402004,54.042271,0.046163,True
46,▁Sirius,C,[Sirius],original,2967.168457,54.002670,54.944847,0.069944,True
47,▁Granger,C,[Granger],original,2957.634277,44.384533,66.636597,0.087492,True
48,▁Merlin,C,[Merlin],extended,2911.461670,48.580006,59.931274,0.043556,True
49,▁hog,C*,[hogwartsia],extended,2818.552979,41.877159,67.305260,0.085097,True
50,▁JK,C,"[JK's, JK]",original,2809.037109,55.123577,50.958904,0.079749,True
51,▁Sly,C,[Slytherin's],original,2802.038818,49.765717,56.304600,0.078565,True
52,▁Mug,B,"[Muggles, Muggle, Muggs]",original,2703.034424,47.060211,57.437790,0.059821,True
53,wiz,C,[wizards],none,2667.004395,41.302612,64.572296,0.000000,False
54,▁Lupin,C,"[Lupin, Lupin's]",original,2633.959473,42.514626,61.954197,0.083827,True
55,▁Sherlock,C,[Sherlock],original,2576.719727,50.593185,50.930172,0.063479,True
56,▁elves,C,[elves],none,2512.721924,46.072376,54.538578,0.000000,False
57,idd,C,[Quidditch],original,2451.365234,38.549339,63.590332,0.061517,True
58,▁McG,C,[McGonagall],original,2447.909912,46.353855,52.809196,0.063038,True
59,▁Ron,C,"[Ron, Ron's]",original,2447.692871,46.703220,52.409508,0.060338,True
60,▁Hag,C,"[Hagrid, Hagrid's]",original,2386.007812,39.647110,60.181126,0.061123,True
61,▁spells,C*,[spells],none,2381.810791,35.898739,66.348038,-0.000000,False
62,▁Sorcerer,C,[Sorcerer's],none,2373.651855,40.029465,59.297615,-0.000000,False
63,▁goblins,C*,[goblins],none,2315.351074,46.640213,49.642807,0.000000,False
64,▁Spells,C*,[Spells],none,2235.017090,35.914330,62.231903,-0.000000,False
65,▁Riddle,C,[Riddle],extended,2220.950195,37.056496,59.934170,0.045850,True
66,blet,C,[Goblet],extended,2157.951904,26.990013,79.953720,0.047637,True
67,▁werewolf,C,[werewolf],none,2126.057617,42.018723,50.597866,0.000000,False
68,▁fairy,C*,[fairy],none,2108.777832,36.173496,58.296215,-0.000000,False
69,▁dragons,C,[dragons],none,2075.192139,39.241661,52.882374,0.000000,False
70,▁Beaux,B,"[Beauxbatons, Beaux-Arts]",original,2058.691650,30.014994,68.588776,0.066274,True
71,▁Holmes,C,"[Holmes-style, Holmes]",original,2040.632690,37.488365,54.433762,0.059885,True
72,▁it,B,[it],none,1991.547119,14.681048,135.654282,0.000000,False
73,▁Quir,C,"[Quirrell, Quirinus]",none,1988.815186,27.636625,71.963028,0.000000,False
74,▁Cinderella,C,[Cinderella],none,1951.420654,34.352367,56.806004,0.000000,False
75,▁Grin,C,[Grindelwald],extended,1951.056641,31.229780,62.474236,0.048045,True
76,▁Warlock,C,[Warlock],none,1933.786621,33.009274,58.583134,0.000000,False
77,▁fantasy,C,[fantasy],none,1930.518066,33.620892,57.420193,-0.000000,False
78,▁owls,C,[owls],none,1842.177979,35.500114,51.892170,0.000000,False
79,▁Cursed,C,[Cursed],none,1827.770996,30.299986,60.322502,0.000000,False
80,▁Cedric,C,[Cedric],extended,1823.196289,31.823418,57.291027,0.045789,True
81,uggle,C,"[Muggle-born, anti-Muggle, Muggle]",none,1819.139160,24.144981,75.342331,0.000000,False
82,arnia,C,[Narnia],none,1818.109619,23.923367,75.997231,0.000000,False
83,HP,N,[NHP],original,1817.002686,47.114277,38.565861,0.054034,True
84,▁Bloomsbury,C,[Bloomsbury],none,1806.585815,29.348906,61.555473,0.000000,False
85,▁Disney,N*,[Disney],none,1796.303955,45.080143,39.846901,0.000000,False
86,Row,C,"[Rowling, Rowling's]",extended,1785.227539,30.297739,58.922798,0.048088,True
87,▁Minerva,C,[Minerva],extended,1723.349976,28.223822,61.060120,0.045095,True
88,▁Beowulf,C*,[Beowulf],extended,1704.323975,28.174026,60.492737,0.058699,True
89,▁them,B,[them],none,1695.041138,12.924729,131.147125,0.000000,False
90,▁Dragon,C,[Dragon],none,1671.085693,32.895290,50.800152,0.000000,False
91,▁fairytale,C,[fairytale],none,1665.898438,30.207216,55.149021,-0.000000,False
92,▁Wic,C,[Wicca],none,1662.881470,29.729364,55.933971,0.000000,False
93,▁Umb,C,[Umbridge],extended,1659.951782,27.161699,61.113693,0.042807,True
94,▁gry,C*,[gryffindori],extended,1628.441162,25.661694,63.458054,0.058438,True
95,▁professors,C,[professors],none,1608.686035,26.550373,60.589958,0.000000,False
96,▁knight,C,"[knight, knightly]",none,1606.153198,31.253330,51.391426,0.000000,False
97,▁herself,C,[herself],none,1598.708008,11.912223,134.207367,0.000000,False
98,▁Professor,B,[Professor],none,1588.838623,24.735502,64.233124,0.000000,False
99,Sna,C,[Snape],extended,1561.189453,29.132357,53.589535,0.043070,True
100,▁Marvel,N*,[Marvel],none,1533.506958,37.745964,40.627045,0.000000,False

-- all 7408 tokens of V*_ext by <x_t / ||x_t||, z> (top 100 shown) --

,token,group,words,support,"<x_t, z>","<x_t / ||x_t||, z>",||x_t||,Y_ext,in Y_ext support
1,▁Hogwarts,C,[Hogwarts],original,8154.627930,132.996506,61.314606,0.192877,True
2,▁Dumbledore,C,"[Dumbledore, Dumbledore's]",original,8027.695312,129.376099,62.049290,0.208103,True
3,▁Hermione,C,"[Hermione, Hermione's]",original,7123.187500,125.776581,56.633656,0.175686,True
4,▁Voldemort,C,"[Voldemort, Voldemort's]",original,7105.919922,119.685417,59.371643,0.168675,True
5,▁Malfoy,C,[Malfoy],original,7215.889648,116.644760,61.862099,0.194578,True
6,▁Weasley,C,[Weasley],original,7336.247559,111.284836,65.923157,0.203925,True
7,umbledore,C,"[Dumbledore's, Dumbledore]",original,9059.843750,107.272659,84.456223,0.238472,True
8,▁Potter,C,"[Potter, Potter's, Potter-themed, Pottermore, Potter's's]",original,6881.388184,106.063324,64.879997,0.188472,True
9,▁Harry,C,"[Harry, Harry's, Harryplax]",original,6265.991211,105.670837,59.297260,0.162169,True
10,Hermione,C,[Hermione],original,6774.737305,104.524597,64.814766,0.178623,True
11,Harry,C,"[Harry, Harry's]",original,5848.928711,104.108055,56.181328,0.153121,True
12,ffindor,C,[Gryffindor],original,11879.779297,103.676102,114.585510,0.361261,True
13,therin,C,[Slytherin's],original,10332.246094,103.622375,99.710571,0.297708,True
14,▁Rowling,C,"[Rowling, Rowling's]",original,7003.209961,102.959953,68.018776,0.188504,True
15,▁Snape,C,"[Snape, Snape's]",original,5939.579102,101.992455,58.235474,0.156795,True
16,Potter,C,[Pottermore],original,5878.796875,92.963249,63.237858,0.164065,True
17,▁Draco,C,[Draco],original,4613.373535,85.602562,53.892937,0.127116,True
18,▁wizards,C,[wizards],none,5421.430664,83.559395,64.881165,0.000000,False
19,▁Severus,C,[Severus],original,4805.299805,82.984360,57.906090,0.122459,True
20,demort,C,[Voldemort],original,6836.748047,82.636742,82.732544,0.175487,True
21,▁wizard,C,"[wizard, wizarding]",none,5664.578125,82.330093,68.803253,0.000000,False
22,▁Wizard,C,"[Wizarding, Wizardry, WizardingWorld]",none,4870.067383,73.971481,65.837097,0.000000,False
23,▁Ginny,C,[Ginny],original,3822.539307,73.497375,52.009193,0.107393,True
24,wizard,C,[Triwizard],none,4685.658203,68.926018,67.980980,0.000000,False
25,Hog,C,[Hogwarts],original,4501.025391,66.839485,67.340813,0.123218,True
26,▁Gry,C,[Gryffindor],original,4095.434082,66.689781,61.410217,0.120103,True
27,▁wand,C,[wand],original,3787.916992,63.811214,59.361305,0.059630,True
28,▁witches,C,[witches],none,3929.928223,62.259392,63.121853,0.000000,False
29,▁Magical,C,[Magical],original,4169.635742,61.380291,67.931183,-0.051687,True
30,▁Tolkien,C*,[Tolkien's],extended,3163.340332,61.073509,51.795620,0.074984,True
31,▁Wizards,C,[Wizards],none,3775.289795,60.547230,62.352810,0.000000,False
32,▁witchcraft,C,[witchcraft],none,3566.260742,58.518898,60.942036,-0.000000,False
33,▁Hog,C,[Hogsmeade],original,3977.402832,58.033875,68.535881,0.111003,True
34,▁magical,C,[magical],original,4133.061523,57.003654,72.505203,-0.084425,True
35,▁Remus,C,[Remus],original,3344.109375,56.777096,58.898914,0.080787,True
36,▁potions,C,[potions],extended,3048.092285,56.402004,54.042271,0.046163,True
37,▁JK,C,"[JK's, JK]",original,2809.037109,55.123577,50.958904,0.079749,True
38,▁Sirius,C,[Sirius],original,2967.168457,54.002670,54.944847,0.069944,True
39,▁Witch,C,[Witchcraft],none,3486.630127,53.796112,64.811935,0.000000,False
40,▁witch,C,[witch],none,3738.960938,53.521141,69.859512,0.000000,False
41,magical,C,[non-magical],original,3640.880859,51.700199,70.422958,-0.081716,True
42,warts,C,[Hogwarts],original,3834.716797,51.039993,75.131607,0.101129,True
43,▁Sherlock,C,[Sherlock],original,2576.719727,50.593185,50.930172,0.063479,True
44,▁Sly,C,[Slytherin's],original,2802.038818,49.765717,56.304600,0.078565,True
45,▁magic,C,[magic],original,4436.203613,49.758179,89.155266,-0.133065,True
46,▁Magic,B,[Magic],original,4209.687500,49.626301,84.827751,-0.120966,True
47,▁Merlin,C,[Merlin],extended,2911.461670,48.580006,59.931274,0.043556,True
48,otts,C,[Gringotts],original,3674.495605,47.812065,76.852898,0.104232,True
49,HP,N,[NHP],original,1817.002686,47.114277,38.565861,0.054034,True
50,▁Mug,B,"[Muggles, Muggle, Muggs]",original,2703.034424,47.060211,57.437790,0.059821,True
51,▁Ron,C,"[Ron, Ron's]",original,2447.692871,46.703220,52.409508,0.060338,True
52,▁goblins,C*,[goblins],none,2315.351074,46.640213,49.642807,0.000000,False
53,▁McG,C,[McGonagall],original,2447.909912,46.353855,52.809196,0.063038,True
54,▁elves,C,[elves],none,2512.721924,46.072376,54.538578,0.000000,False
55,▁Disney,N*,[Disney],none,1796.303955,45.080143,39.846901,0.000000,False
56,▁Granger,C,[Granger],original,2957.634277,44.384533,66.636597,0.087492,True
57,Magic,C,[Magic],original,3733.947754,43.586025,85.668465,-0.137874,True
58,▁Lupin,C,"[Lupin, Lupin's]",original,2633.959473,42.514626,61.954197,0.083827,True
59,magic,C,[magic],original,3613.465088,42.239155,85.547760,-0.142666,True
60,▁werewolf,C,[werewolf],none,2126.057617,42.018723,50.597866,0.000000,False
61,▁hog,C*,[hogwartsia],extended,2818.552979,41.877159,67.305260,0.085097,True
62,wiz,C,[wizards],none,2667.004395,41.302612,64.572296,0.000000,False
63,▁Sorcerer,C,[Sorcerer's],none,2373.651855,40.029465,59.297615,-0.000000,False
64,▁Hag,C,"[Hagrid, Hagrid's]",original,2386.007812,39.647110,60.181126,0.061123,True
65,▁dragons,C,[dragons],none,2075.192139,39.241661,52.882374,0.000000,False
66,idd,C,[Quidditch],original,2451.365234,38.549339,63.590332,0.061517,True
67,▁Marvel,N*,[Marvel],none,1533.506958,37.745964,40.627045,0.000000,False
68,▁Holmes,C,"[Holmes-style, Holmes]",original,2040.632690,37.488365,54.433762,0.059885,True
69,▁Riddle,C,[Riddle],extended,2220.950195,37.056496,59.934170,0.045850,True
70,▁Watson,N*,[Watson],none,1478.177490,36.582172,40.407043,0.000000,False
71,▁fairy,C*,[fairy],none,2108.777832,36.173496,58.296215,-0.000000,False
72,▁Spells,C*,[Spells],none,2235.017090,35.914330,62.231903,-0.000000,False
73,▁spells,C*,[spells],none,2381.810791,35.898739,66.348038,-0.000000,False
74,▁owls,C,[owls],none,1842.177979,35.500114,51.892170,0.000000,False
75,▁Cinderella,C,[Cinderella],none,1951.420654,34.352367,56.806004,0.000000,False
76,▁fantasy,C,[fantasy],none,1930.518066,33.620892,57.420193,-0.000000,False
77,▁Warlock,C,[Warlock],none,1933.786621,33.009274,58.583134,0.000000,False
78,▁Dragon,C,[Dragon],none,1671.085693,32.895290,50.800152,0.000000,False
79,▁Dwar,N*,[Dwaraka],none,1361.473145,32.667027,41.677288,0.000000,False
80,▁Shakespeare,N*,[Shakespeare],none,1352.226074,32.215458,41.974449,0.000000,False
81,▁Lily,C,[Lily],extended,1506.767944,32.139137,46.882652,0.042132,True
82,▁Charlie,N*,[Charlie],extended,1385.291504,32.132843,43.111389,0.048216,True
83,▁Santa,N*,[Santa],none,1317.799805,32.001232,41.179657,0.000000,False
84,▁Cedric,C,[Cedric],extended,1823.196289,31.823418,57.291027,0.045789,True
85,▁knight,C,"[knight, knightly]",none,1606.153198,31.253330,51.391426,0.000000,False
86,▁Grin,C,[Grindelwald],extended,1951.056641,31.229780,62.474236,0.048045,True
87,▁Cursed,C,[Cursed],none,1827.770996,30.299986,60.322502,0.000000,False
88,Row,C,"[Rowling, Rowling's]",extended,1785.227539,30.297739,58.922798,0.048088,True
89,▁fairytale,C,[fairytale],none,1665.898438,30.207216,55.149021,-0.000000,False
90,▁Thames,N*,[Thamesmead],none,1344.822388,30.166471,44.580036,0.000000,False
91,▁Beaux,B,"[Beauxbatons, Beaux-Arts]",original,2058.691650,30.014994,68.588776,0.066274,True
92,▁Wic,C,[Wicca],none,1662.881470,29.729364,55.933971,0.000000,False
93,▁Mag,N*,[Magatha],none,1310.101807,29.617064,44.234695,-0.000000,False
94,▁Bloomsbury,C,[Bloomsbury],none,1806.585815,29.348906,61.555473,0.000000,False
95,Sna,C,[Snape],extended,1561.189453,29.132357,53.589535,0.043070,True
96,▁Scotland,N*,[Scotland],none,1404.160400,28.619432,49.063183,0.000000,False
97,▁Minerva,C,[Minerva],extended,1723.349976,28.223822,61.060120,0.045095,True
98,▁Beowulf,C*,[Beowulf],extended,1704.323975,28.174026,60.492737,0.058699,True
99,▁Pirates,N,[Pirates],none,1017.846741,27.936638,36.434116,0.000000,False
100,▁Oxford,C,[Oxford],none,1437.370972,27.812325,51.681080,0.000000,False

-- Y_ext support: 74 tokens [C: 59  C*: 5  B: 5  B*: 1  N: 2  N*: 2] | in V*: 66 | in original support: 48/48 --

In [34]:
# ---- Dense refit: fix Z, solve Y' = argmin ||E*^T - Z Y'||_F (no sparsity) ----
TOP_DIRS = 5
HP_FEATS = list(F_C)          # the Harry Potter concept column(s) of Z; override e.g. [37] if you want one
HP_MARK = "★★★ HP ★★★"

A_ref = E_vstar_X.double().cpu().T                                                # (d, |V*|), X-space
Z64 = Z.double()                                                                    # (d, k)
Y_dense = torch.linalg.lstsq(Z64, A_ref).solution.float()                           # (k, |V*|)

dense_err = (torch.norm(A_ref - Z64 @ Y_dense.double()) / torch.norm(A_ref)).item()
sparse_err = (torch.norm(A_ref - Z64 @ Y.double()) / torch.norm(A_ref)).item()
print(f"relative error: sparse Y = {sparse_err:.4f}   dense Y' = {dense_err:.4f}")
print(f"HP feature(s): {HP_FEATS}   (||z|| = {[round(Z[:, f].norm().item(), 3) for f in HP_FEATS]})\n")

for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    print(f"{'=' * 100}\n=== HP feature {hp}: {len(support)} tokens with nonzero Y, by decreasing |Y| ===\n{'=' * 100}")
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        top = order[:TOP_DIRS]

        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}")
        for r, f in enumerate(top, 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        for f in HP_FEATS:
            if f not in top:
                print(f"       ..  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}   <-- {HP_MARK} (rank {order.index(f) + 1}/{len(order)})")

relative error: sparse Y = 0.8510   dense Y' = 0.8107
HP feature(s): [46]   (||z|| = [195.946])

====================================================================================================
=== HP feature 46: 48 tokens with nonzero Y, by decreasing |Y| ===
====================================================================================================

  1. 'ffindor' [C]   sparse Y[46] = -0.361
       #1  z_46   Y' = -0.361   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.119
       #3  z_51   Y' = -0.116
       #4  z_88   Y' = +0.080
       #5  z_85   Y' = +0.039

  2. 'therin' [C]   sparse Y[46] = -0.298
       #1  z_46   Y' = -0.298   <-- ★★★ HP ★★★
       #2  z_51   Y' = -0.071
       #3  z_88   Y' = +0.053
       #4  z_91   Y' = +0.046
       #5  z_80   Y' = +0.043

  3. 'umbledore' [C]   sparse Y[46] = -0.238
       #1  z_46   Y' = -0.238   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.040
       #3  z_8    Y' = -0.035
       #4  z_94   Y' = -0.033
       #5  z_44   Y' = +0.032

  4. '▁Dumbledore' [C]   sparse Y[46] = -0.208
       #1  z_46   Y' = -0.208   <-- ★★★ HP ★★★
       #2  z_71   Y' = +0.021
       #3  z_60   Y' = +0.021
       #4  z_37   Y' = -0.019
       #5  z_20   Y' = +0.019

  5. '▁Weasley' [C]   sparse Y[46] = -0.204
       #1  z_46   Y' = -0.204   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.023
       #3  z_31   Y' = +0.021
       #4  z_89   Y' = +0.020
       #5  z_16   Y' = -0.019

  6. '▁Malfoy' [C]   sparse Y[46] = -0.195
       #1  z_46   Y' = -0.195   <-- ★★★ HP ★★★
       #2  z_96   Y' = +0.020
       #3  z_89   Y' = +0.020
       #4  z_52   Y' = +0.018
       #5  z_44   Y' = -0.018

  7. '▁Hogwarts' [C]   sparse Y[46] = -0.193
       #1  z_46   Y' = -0.193   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.043
       #3  z_88   Y' = -0.025
       #4  z_85   Y' = -0.022
       #5  z_13   Y' = +0.021

  8. '▁Rowling' [C]   sparse Y[46] = -0.189
       #1  z_46   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.038
       #3  z_68   Y' = +0.026
       #4  z_44   Y' = +0.025
       #5  z_11   Y' = +0.023

  9. '▁Potter' [C]   sparse Y[46] = -0.188
       #1  z_46   Y' = -0.188   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.020
       #3  z_44   Y' = -0.019
       #4  z_60   Y' = +0.017
       #5  z_47   Y' = +0.017

 10. 'Hermione' [C]   sparse Y[46] = -0.179
       #1  z_46   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_36   Y' = +0.026
       #3  z_32   Y' = +0.025
       #4  z_91   Y' = -0.023
       #5  z_12   Y' = -0.021

 11. '▁Hermione' [C]   sparse Y[46] = -0.176
       #1  z_46   Y' = -0.176   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.020
       #3  z_88   Y' = -0.016
       #4  z_67   Y' = -0.015
       #5  z_84   Y' = -0.015

 12. 'demort' [C]   sparse Y[46] = -0.175
       #1  z_46   Y' = -0.175   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.036
       #3  z_16   Y' = +0.035
       #4  z_15   Y' = +0.032
       #5  z_91   Y' = +0.029

 13. '▁Voldemort' [C]   sparse Y[46] = -0.169
       #1  z_46   Y' = -0.169   <-- ★★★ HP ★★★
       #2  z_88   Y' = -0.026
       #3  z_83   Y' = -0.021
       #4  z_60   Y' = +0.020
       #5  z_32   Y' = +0.019

 14. 'Potter' [C]   sparse Y[46] = -0.164
       #1  z_46   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.029
       #3  z_44   Y' = -0.022
       #4  z_71   Y' = -0.022
       #5  z_47   Y' = +0.015

 15. '▁Harry' [C]   sparse Y[46] = -0.162
       #1  z_46   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.024
       #3  z_65   Y' = -0.023
       #4  z_40   Y' = +0.022
       #5  z_39   Y' = +0.019

 16. '▁Snape' [C]   sparse Y[46] = -0.157
       #1  z_46   Y' = -0.157   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.022
       #4  z_65   Y' = +0.019
       #5  z_90   Y' = -0.015

 17. 'Harry' [C]   sparse Y[46] = -0.153
       #1  z_46   Y' = -0.153   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.022
       #3  z_65   Y' = -0.021
       #4  z_17   Y' = -0.015
       #5  z_39   Y' = +0.015

 18. 'magic' [C]   sparse Y[46] = +0.143
       #1  z_88   Y' = -0.346
       #2  z_46   Y' = +0.143   <-- ★★★ HP ★★★
       #3  z_66   Y' = +0.016
       #4  z_39   Y' = +0.015
       #5  z_15   Y' = +0.013

 19. 'Magic' [C]   sparse Y[46] = +0.138
       #1  z_88   Y' = -0.340
       #2  z_46   Y' = +0.138   <-- ★★★ HP ★★★
       #3  z_65   Y' = -0.015
       #4  z_36   Y' = +0.014
       #5  z_32   Y' = +0.012

 20. '▁magic' [C]   sparse Y[46] = +0.133
       #1  z_88   Y' = -0.362
       #2  z_46   Y' = +0.133   <-- ★★★ HP ★★★
       #3  z_19   Y' = -0.013
       #4  z_86   Y' = +0.013
       #5  z_66   Y' = -0.010

 21. '▁Draco' [C]   sparse Y[46] = -0.127
       #1  z_46   Y' = -0.127   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.042
       #3  z_39   Y' = +0.024
       #4  z_87   Y' = +0.015
       #5  z_85   Y' = -0.015

 22. 'Hog' [C]   sparse Y[46] = -0.123
       #1  z_46   Y' = -0.123   <-- ★★★ HP ★★★
       #2  z_16   Y' = +0.021
       #3  z_10   Y' = -0.018
       #4  z_25   Y' = +0.018
       #5  z_67   Y' = -0.017

 23. '▁Severus' [C]   sparse Y[46] = -0.122
       #1  z_46   Y' = -0.122   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.026
       #3  z_71   Y' = +0.022
       #4  z_11   Y' = -0.021
       #5  z_94   Y' = -0.018

 24. '▁Magic' [B]   sparse Y[46] = +0.121
       #1  z_88   Y' = -0.333
       #2  z_46   Y' = +0.121   <-- ★★★ HP ★★★
       #3  z_32   Y' = +0.014
       #4  z_42   Y' = +0.012
       #5  z_65   Y' = -0.012

 25. '▁Gry' [C]   sparse Y[46] = -0.120
       #1  z_46   Y' = -0.120   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.027
       #3  z_96   Y' = +0.026
       #4  z_13   Y' = -0.021
       #5  z_24   Y' = -0.019

 26. '▁Hog' [C]   sparse Y[46] = -0.111
       #1  z_46   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.025
       #3  z_19   Y' = -0.022
       #4  z_2    Y' = +0.019
       #5  z_16   Y' = +0.017

 27. '▁Ginny' [C]   sparse Y[46] = -0.107
       #1  z_46   Y' = -0.107   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.029
       #3  z_42   Y' = -0.022
       #4  z_13   Y' = -0.015
       #5  z_15   Y' = +0.015

 28. 'otts' [C]   sparse Y[46] = -0.104
       #1  z_46   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.038
       #3  z_14   Y' = +0.033
       #4  z_96   Y' = -0.032
       #5  z_70   Y' = +0.027

 29. 'warts' [C]   sparse Y[46] = -0.101
       #1  z_46   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_1    Y' = -0.029
       #3  z_2    Y' = +0.027
       #4  z_24   Y' = -0.026
       #5  z_14   Y' = +0.025

 30. '▁Granger' [C]   sparse Y[46] = -0.087
       #1  z_46   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_49   Y' = +0.018
       #3  z_43   Y' = -0.018
       #4  z_9    Y' = +0.017
       #5  z_92   Y' = -0.016

 31. '▁magical' [C]   sparse Y[46] = +0.084
       #1  z_88   Y' = -0.277
       #2  z_46   Y' = +0.084   <-- ★★★ HP ★★★
       #3  z_86   Y' = +0.022
       #4  z_43   Y' = +0.014
       #5  z_27   Y' = -0.014

 32. '▁Lupin' [C]   sparse Y[46] = -0.084
       #1  z_46   Y' = -0.084   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.020
       #3  z_71   Y' = -0.020
       #4  z_52   Y' = -0.019
       #5  z_60   Y' = +0.019

 33. 'magical' [C]   sparse Y[46] = +0.082
       #1  z_88   Y' = -0.257
       #2  z_46   Y' = +0.082   <-- ★★★ HP ★★★
       #3  z_6    Y' = -0.019
       #4  z_27   Y' = -0.019
       #5  z_25   Y' = +0.018

 34. '▁Remus' [C]   sparse Y[46] = -0.081
       #1  z_46   Y' = -0.081   <-- ★★★ HP ★★★
       #2  z_26   Y' = -0.020
       #3  z_42   Y' = +0.020
       #4  z_30   Y' = +0.020
       #5  z_27   Y' = +0.019

 35. '▁JK' [C]   sparse Y[46] = -0.080
       #1  z_46   Y' = -0.080   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.023
       #3  z_10   Y' = -0.020
       #4  z_99   Y' = -0.018
       #5  z_38   Y' = -0.016

 36. '▁Sly' [C]   sparse Y[46] = -0.079
       #1  z_46   Y' = -0.079   <-- ★★★ HP ★★★
       #2  z_27   Y' = +0.037
       #3  z_44   Y' = +0.020
       #4  z_30   Y' = -0.018
       #5  z_43   Y' = +0.016

 37. '▁Sirius' [C]   sparse Y[46] = -0.070
       #1  z_46   Y' = -0.070   <-- ★★★ HP ★★★
       #2  z_60   Y' = +0.029
       #3  z_42   Y' = +0.025
       #4  z_21   Y' = -0.022
       #5  z_39   Y' = -0.020

 38. '▁Beaux' [B]   sparse Y[46] = -0.066
       #1  z_46   Y' = -0.066   <-- ★★★ HP ★★★
       #2  z_37   Y' = +0.033
       #3  z_39   Y' = +0.028
       #4  z_25   Y' = -0.027
       #5  z_67   Y' = +0.025

 39. '▁Sherlock' [C]   sparse Y[46] = -0.063
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_27   Y' = +0.021
       #4  z_50   Y' = -0.020
       #5  z_98   Y' = -0.018

 40. '▁McG' [C]   sparse Y[46] = -0.063
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.019
       #3  z_75   Y' = +0.019
       #4  z_27   Y' = -0.017
       #5  z_44   Y' = +0.016

 41. 'idd' [C]   sparse Y[46] = -0.062
       #1  z_46   Y' = -0.062   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.028
       #3  z_52   Y' = +0.026
       #4  z_26   Y' = +0.024
       #5  z_42   Y' = -0.022

 42. '▁Hag' [C]   sparse Y[46] = -0.061
       #1  z_46   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.026
       #3  z_96   Y' = +0.017
       #4  z_92   Y' = -0.017
       #5  z_76   Y' = +0.016

 43. '▁Ron' [C]   sparse Y[46] = -0.060
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_59   Y' = +0.026
       #3  z_53   Y' = +0.018
       #4  z_75   Y' = +0.017
       #5  z_34   Y' = +0.014

 44. '▁Holmes' [C]   sparse Y[46] = -0.060
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_8    Y' = +0.023
       #4  z_43   Y' = -0.022
       #5  z_83   Y' = -0.020

 45. '▁Mug' [B]   sparse Y[46] = -0.060
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_44   Y' = +0.025
       #3  z_42   Y' = +0.024
       #4  z_88   Y' = -0.022
       #5  z_10   Y' = -0.022

 46. '▁wand' [C]   sparse Y[46] = -0.060
       #1  z_88   Y' = -0.065
       #2  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #3  z_39   Y' = -0.017
       #4  z_3    Y' = -0.017
       #5  z_96   Y' = +0.015

 47. 'HP' [N]   sparse Y[46] = -0.054
       #1  z_46   Y' = -0.054   <-- ★★★ HP ★★★
       #2  z_39   Y' = +0.023
       #3  z_32   Y' = -0.015
       #4  z_13   Y' = -0.014
       #5  z_36   Y' = +0.012

 48. '▁Magical' [C]   sparse Y[46] = +0.052
       #1  z_88   Y' = -0.229
       #2  z_46   Y' = +0.052   <-- ★★★ HP ★★★
       #3  z_27   Y' = -0.016
       #4  z_30   Y' = +0.016
       #5  z_19   Y' = -0.016

In [35]:
# ---- Tokens where the HP direction dominates Y': top-1 is HP and |Y'_1| >= RATIO * |Y'_2| ----
RATIO = 2.0

for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    kept = []
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        first, second = y_dense_t[order[0]].abs().item(), y_dense_t[order[1]].abs().item()
        if order[0] == hp and first >= RATIO * second:
            kept.append((rank_t, j, tok, order, first / second))

    print(f"{'=' * 100}\n=== HP feature {hp}: {len(kept)} / {len(support)} tokens where z_{hp} is top-1 "
          f"and |Y'| >= {RATIO:g}x the runner-up ===\n{'=' * 100}")
    for rank_t, j, tok, order, ratio in kept:
        y_dense_t = Y_dense[:, j]
        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}   "
              f"top-1/top-2 = {ratio:.2f}x")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")

====================================================================================================
=== HP feature 46: 40 / 48 tokens where z_46 is top-1 and |Y'| >= 2x the runner-up ===
====================================================================================================

  1. 'ffindor' [C]   sparse Y[46] = -0.361   top-1/top-2 = 3.05x
       #1  z_46   Y' = -0.361   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.119
       #3  z_51   Y' = -0.116
       #4  z_88   Y' = +0.080
       #5  z_85   Y' = +0.039

  2. 'therin' [C]   sparse Y[46] = -0.298   top-1/top-2 = 4.19x
       #1  z_46   Y' = -0.298   <-- ★★★ HP ★★★
       #2  z_51   Y' = -0.071
       #3  z_88   Y' = +0.053
       #4  z_91   Y' = +0.046
       #5  z_80   Y' = +0.043

  3. 'umbledore' [C]   sparse Y[46] = -0.238   top-1/top-2 = 5.93x
       #1  z_46   Y' = -0.238   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.040
       #3  z_8    Y' = -0.035
       #4  z_94   Y' = -0.033
       #5  z_44   Y' = +0.032

  4. '▁Dumbledore' [C]   sparse Y[46] = -0.208   top-1/top-2 = 9.72x
       #1  z_46   Y' = -0.208   <-- ★★★ HP ★★★
       #2  z_71   Y' = +0.021
       #3  z_60   Y' = +0.021
       #4  z_37   Y' = -0.019
       #5  z_20   Y' = +0.019

  5. '▁Weasley' [C]   sparse Y[46] = -0.204   top-1/top-2 = 8.79x
       #1  z_46   Y' = -0.204   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.023
       #3  z_31   Y' = +0.021
       #4  z_89   Y' = +0.020
       #5  z_16   Y' = -0.019

  6. '▁Malfoy' [C]   sparse Y[46] = -0.195   top-1/top-2 = 9.52x
       #1  z_46   Y' = -0.195   <-- ★★★ HP ★★★
       #2  z_96   Y' = +0.020
       #3  z_89   Y' = +0.020
       #4  z_52   Y' = +0.018
       #5  z_44   Y' = -0.018

  7. '▁Hogwarts' [C]   sparse Y[46] = -0.193   top-1/top-2 = 4.46x
       #1  z_46   Y' = -0.193   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.043
       #3  z_88   Y' = -0.025
       #4  z_85   Y' = -0.022
       #5  z_13   Y' = +0.021

  8. '▁Rowling' [C]   sparse Y[46] = -0.189   top-1/top-2 = 4.95x
       #1  z_46   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.038
       #3  z_68   Y' = +0.026
       #4  z_44   Y' = +0.025
       #5  z_11   Y' = +0.023

  9. '▁Potter' [C]   sparse Y[46] = -0.188   top-1/top-2 = 9.39x
       #1  z_46   Y' = -0.188   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.020
       #3  z_44   Y' = -0.019
       #4  z_60   Y' = +0.017
       #5  z_47   Y' = +0.017

 10. 'Hermione' [C]   sparse Y[46] = -0.179   top-1/top-2 = 6.94x
       #1  z_46   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_36   Y' = +0.026
       #3  z_32   Y' = +0.025
       #4  z_91   Y' = -0.023
       #5  z_12   Y' = -0.021

 11. '▁Hermione' [C]   sparse Y[46] = -0.176   top-1/top-2 = 8.85x
       #1  z_46   Y' = -0.176   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.020
       #3  z_88   Y' = -0.016
       #4  z_67   Y' = -0.015
       #5  z_84   Y' = -0.015

 12. 'demort' [C]   sparse Y[46] = -0.175   top-1/top-2 = 4.83x
       #1  z_46   Y' = -0.175   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.036
       #3  z_16   Y' = +0.035
       #4  z_15   Y' = +0.032
       #5  z_91   Y' = +0.029

 13. '▁Voldemort' [C]   sparse Y[46] = -0.169   top-1/top-2 = 6.57x
       #1  z_46   Y' = -0.169   <-- ★★★ HP ★★★
       #2  z_88   Y' = -0.026
       #3  z_83   Y' = -0.021
       #4  z_60   Y' = +0.020
       #5  z_32   Y' = +0.019

 14. 'Potter' [C]   sparse Y[46] = -0.164   top-1/top-2 = 5.69x
       #1  z_46   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.029
       #3  z_44   Y' = -0.022
       #4  z_71   Y' = -0.022
       #5  z_47   Y' = +0.015

 15. '▁Harry' [C]   sparse Y[46] = -0.162   top-1/top-2 = 6.80x
       #1  z_46   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.024
       #3  z_65   Y' = -0.023
       #4  z_40   Y' = +0.022
       #5  z_39   Y' = +0.019

 16. '▁Snape' [C]   sparse Y[46] = -0.157   top-1/top-2 = 6.43x
       #1  z_46   Y' = -0.157   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.022
       #4  z_65   Y' = +0.019
       #5  z_90   Y' = -0.015

 17. 'Harry' [C]   sparse Y[46] = -0.153   top-1/top-2 = 6.98x
       #1  z_46   Y' = -0.153   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.022
       #3  z_65   Y' = -0.021
       #4  z_17   Y' = -0.015
       #5  z_39   Y' = +0.015

 21. '▁Draco' [C]   sparse Y[46] = -0.127   top-1/top-2 = 3.02x
       #1  z_46   Y' = -0.127   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.042
       #3  z_39   Y' = +0.024
       #4  z_87   Y' = +0.015
       #5  z_85   Y' = -0.015

 22. 'Hog' [C]   sparse Y[46] = -0.123   top-1/top-2 = 5.77x
       #1  z_46   Y' = -0.123   <-- ★★★ HP ★★★
       #2  z_16   Y' = +0.021
       #3  z_10   Y' = -0.018
       #4  z_25   Y' = +0.018
       #5  z_67   Y' = -0.017

 23. '▁Severus' [C]   sparse Y[46] = -0.122   top-1/top-2 = 4.80x
       #1  z_46   Y' = -0.122   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.026
       #3  z_71   Y' = +0.022
       #4  z_11   Y' = -0.021
       #5  z_94   Y' = -0.018

 25. '▁Gry' [C]   sparse Y[46] = -0.120   top-1/top-2 = 4.41x
       #1  z_46   Y' = -0.120   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.027
       #3  z_96   Y' = +0.026
       #4  z_13   Y' = -0.021
       #5  z_24   Y' = -0.019

 26. '▁Hog' [C]   sparse Y[46] = -0.111   top-1/top-2 = 4.42x
       #1  z_46   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.025
       #3  z_19   Y' = -0.022
       #4  z_2    Y' = +0.019
       #5  z_16   Y' = +0.017

 27. '▁Ginny' [C]   sparse Y[46] = -0.107   top-1/top-2 = 3.70x
       #1  z_46   Y' = -0.107   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.029
       #3  z_42   Y' = -0.022
       #4  z_13   Y' = -0.015
       #5  z_15   Y' = +0.015

 28. 'otts' [C]   sparse Y[46] = -0.104   top-1/top-2 = 2.77x
       #1  z_46   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.038
       #3  z_14   Y' = +0.033
       #4  z_96   Y' = -0.032
       #5  z_70   Y' = +0.027

 29. 'warts' [C]   sparse Y[46] = -0.101   top-1/top-2 = 3.46x
       #1  z_46   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_1    Y' = -0.029
       #3  z_2    Y' = +0.027
       #4  z_24   Y' = -0.026
       #5  z_14   Y' = +0.025

 30. '▁Granger' [C]   sparse Y[46] = -0.087   top-1/top-2 = 4.91x
       #1  z_46   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_49   Y' = +0.018
       #3  z_43   Y' = -0.018
       #4  z_9    Y' = +0.017
       #5  z_92   Y' = -0.016

 32. '▁Lupin' [C]   sparse Y[46] = -0.084   top-1/top-2 = 4.14x
       #1  z_46   Y' = -0.084   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.020
       #3  z_71   Y' = -0.020
       #4  z_52   Y' = -0.019
       #5  z_60   Y' = +0.019

 34. '▁Remus' [C]   sparse Y[46] = -0.081   top-1/top-2 = 3.98x
       #1  z_46   Y' = -0.081   <-- ★★★ HP ★★★
       #2  z_26   Y' = -0.020
       #3  z_42   Y' = +0.020
       #4  z_30   Y' = +0.020
       #5  z_27   Y' = +0.019

 35. '▁JK' [C]   sparse Y[46] = -0.080   top-1/top-2 = 3.53x
       #1  z_46   Y' = -0.080   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.023
       #3  z_10   Y' = -0.020
       #4  z_99   Y' = -0.018
       #5  z_38   Y' = -0.016

 36. '▁Sly' [C]   sparse Y[46] = -0.079   top-1/top-2 = 2.12x
       #1  z_46   Y' = -0.079   <-- ★★★ HP ★★★
       #2  z_27   Y' = +0.037
       #3  z_44   Y' = +0.020
       #4  z_30   Y' = -0.018
       #5  z_43   Y' = +0.016

 37. '▁Sirius' [C]   sparse Y[46] = -0.070   top-1/top-2 = 2.43x
       #1  z_46   Y' = -0.070   <-- ★★★ HP ★★★
       #2  z_60   Y' = +0.029
       #3  z_42   Y' = +0.025
       #4  z_21   Y' = -0.022
       #5  z_39   Y' = -0.020

 38. '▁Beaux' [B]   sparse Y[46] = -0.066   top-1/top-2 = 2.03x
       #1  z_46   Y' = -0.066   <-- ★★★ HP ★★★
       #2  z_37   Y' = +0.033
       #3  z_39   Y' = +0.028
       #4  z_25   Y' = -0.027
       #5  z_67   Y' = +0.025

 39. '▁Sherlock' [C]   sparse Y[46] = -0.063   top-1/top-2 = 2.28x
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_27   Y' = +0.021
       #4  z_50   Y' = -0.020
       #5  z_98   Y' = -0.018

 40. '▁McG' [C]   sparse Y[46] = -0.063   top-1/top-2 = 3.29x
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.019
       #3  z_75   Y' = +0.019
       #4  z_27   Y' = -0.017
       #5  z_44   Y' = +0.016

 41. 'idd' [C]   sparse Y[46] = -0.062   top-1/top-2 = 2.23x
       #1  z_46   Y' = -0.062   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.028
       #3  z_52   Y' = +0.026
       #4  z_26   Y' = +0.024
       #5  z_42   Y' = -0.022

 42. '▁Hag' [C]   sparse Y[46] = -0.061   top-1/top-2 = 2.31x
       #1  z_46   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.026
       #3  z_96   Y' = +0.017
       #4  z_92   Y' = -0.017
       #5  z_76   Y' = +0.016

 43. '▁Ron' [C]   sparse Y[46] = -0.060   top-1/top-2 = 2.30x
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_59   Y' = +0.026
       #3  z_53   Y' = +0.018
       #4  z_75   Y' = +0.017
       #5  z_34   Y' = +0.014

 44. '▁Holmes' [C]   sparse Y[46] = -0.060   top-1/top-2 = 2.16x
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_8    Y' = +0.023
       #4  z_43   Y' = -0.022
       #5  z_83   Y' = -0.020

 45. '▁Mug' [B]   sparse Y[46] = -0.060   top-1/top-2 = 2.35x
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_44   Y' = +0.025
       #3  z_42   Y' = +0.024
       #4  z_88   Y' = -0.022
       #5  z_10   Y' = -0.022

 47. 'HP' [N]   sparse Y[46] = -0.054   top-1/top-2 = 2.36x
       #1  z_46   Y' = -0.054   <-- ★★★ HP ★★★
       #2  z_39   Y' = +0.023
       #3  z_32   Y' = -0.015
       #4  z_13   Y' = -0.014
       #5  z_36   Y' = +0.012

In [36]:
# ---- Tokens skipped by the previous cell: HP is not top-1, or top-1 but < RATIO x the runner-up ----
for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    skipped = []
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        first, second = y_dense_t[order[0]].abs().item(), y_dense_t[order[1]].abs().item()
        if order[0] != hp:
            skipped.append((rank_t, j, tok, order, f"HP is not top-1 (rank {order.index(hp) + 1}/{len(order)})"))
        elif first < RATIO * second:
            skipped.append((rank_t, j, tok, order, f"HP is top-1 but only {first / second:.2f}x the runner-up"))

    n_not_top = sum(r.startswith("HP is not") for *_, r in skipped)
    print(f"{'=' * 100}\n=== HP feature {hp}: {len(skipped)} / {len(support)} tokens skipped "
          f"({n_not_top} HP not top-1, {len(skipped) - n_not_top} top-1 but < {RATIO:g}x) ===\n{'=' * 100}")
    for rank_t, j, tok, order, reason in skipped:
        y_dense_t = Y_dense[:, j]
        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}   -> {reason}")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        if hp not in order[:TOP_DIRS]:
            print(f"       ..  z_{hp:<4d} Y' = {y_dense_t[hp]:+.3f}   <-- {HP_MARK} (rank {order.index(hp) + 1}/{len(order)})")

====================================================================================================
=== HP feature 46: 8 / 48 tokens skipped (8 HP not top-1, 0 top-1 but < 2x) ===
====================================================================================================

 18. 'magic' [C]   sparse Y[46] = +0.143   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.346
       #2  z_46   Y' = +0.143   <-- ★★★ HP ★★★
       #3  z_66   Y' = +0.016
       #4  z_39   Y' = +0.015
       #5  z_15   Y' = +0.013

 19. 'Magic' [C]   sparse Y[46] = +0.138   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.340
       #2  z_46   Y' = +0.138   <-- ★★★ HP ★★★
       #3  z_65   Y' = -0.015
       #4  z_36   Y' = +0.014
       #5  z_32   Y' = +0.012

 20. '▁magic' [C]   sparse Y[46] = +0.133   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.362
       #2  z_46   Y' = +0.133   <-- ★★★ HP ★★★
       #3  z_19   Y' = -0.013
       #4  z_86   Y' = +0.013
       #5  z_66   Y' = -0.010

 24. '▁Magic' [B]   sparse Y[46] = +0.121   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.333
       #2  z_46   Y' = +0.121   <-- ★★★ HP ★★★
       #3  z_32   Y' = +0.014
       #4  z_42   Y' = +0.012
       #5  z_65   Y' = -0.012

 31. '▁magical' [C]   sparse Y[46] = +0.084   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.277
       #2  z_46   Y' = +0.084   <-- ★★★ HP ★★★
       #3  z_86   Y' = +0.022
       #4  z_43   Y' = +0.014
       #5  z_27   Y' = -0.014

 33. 'magical' [C]   sparse Y[46] = +0.082   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.257
       #2  z_46   Y' = +0.082   <-- ★★★ HP ★★★
       #3  z_6    Y' = -0.019
       #4  z_27   Y' = -0.019
       #5  z_25   Y' = +0.018

 46. '▁wand' [C]   sparse Y[46] = -0.060   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.065
       #2  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #3  z_39   Y' = -0.017
       #4  z_3    Y' = -0.017
       #5  z_96   Y' = +0.015

 48. '▁Magical' [C]   sparse Y[46] = +0.052   -> HP is not top-1 (rank 2/100)
       #1  z_88   Y' = -0.229
       #2  z_46   Y' = +0.052   <-- ★★★ HP ★★★
       #3  z_27   Y' = -0.016
       #4  z_30   Y' = +0.016
       #5  z_19   Y' = -0.016

In [37]:
# ---- All C-labelled tokens, sorted by |Y'_HP| / max_{i != HP} |Y'_i| (= top-1/top-2 when HP is top-1) ----
for hp in HP_FEATS:
    c_cols = np.where(codes == 1)[0].tolist()
    rows = []
    for j in c_cols:
        y_dense_t = Y_dense[:, j]
        others_max = torch.cat([y_dense_t[:hp], y_dense_t[hp + 1:]]).abs().max().item()
        rows.append((y_dense_t[hp].abs().item() / others_max, j))
    rows.sort(reverse=True)

    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for _, j in rows])
    n_pass = sum(r >= RATIO for r, _ in rows)
    n_top1 = sum(r >= 1.0 for r, _ in rows)
    print(f"{'=' * 100}\n=== HP feature {hp}: {len(rows)} C tokens | HP top-1: {n_top1} | "
          f"HP top-1 and >= {RATIO:g}x: {n_pass} ===\n{'=' * 100}")

    shown_ratio_line = shown_top1_line = False
    for rank_t, ((ratio, j), tok) in enumerate(zip(rows, toks), 1):
        if not shown_ratio_line and ratio < RATIO:
            print(f"\n{'-' * 40} below {RATIO:g}x {'-' * 40}")
            shown_ratio_line = True
        if not shown_top1_line and ratio < 1.0:
            print(f"\n{'-' * 36} HP no longer top-1 {'-' * 36}")
            shown_top1_line = True

        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        in_support = "in HP support" if Y[hp, j] != 0 else "not in HP support"
        print(f"\n{rank_t:3d}. {tok!r} [C]   ratio = {ratio:.2f}x   sparse Y[{hp}] = {Y[hp, j]:+.3f}  ({in_support})")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        if hp not in order[:TOP_DIRS]:
            print(f"       ..  z_{hp:<4d} Y' = {y_dense_t[hp]:+.3f}   <-- {HP_MARK} (rank {order.index(hp) + 1}/{len(order)})")

====================================================================================================
=== HP feature 46: 1870 C tokens | HP top-1: 95 | HP top-1 and >= 2x: 41 ===
====================================================================================================

  1. '▁Dumbledore' [C]   ratio = 9.72x   sparse Y[46] = -0.208  (in HP support)
       #1  z_46   Y' = -0.208   <-- ★★★ HP ★★★
       #2  z_71   Y' = +0.021
       #3  z_60   Y' = +0.021
       #4  z_37   Y' = -0.019
       #5  z_20   Y' = +0.019

  2. '▁Malfoy' [C]   ratio = 9.52x   sparse Y[46] = -0.195  (in HP support)
       #1  z_46   Y' = -0.195   <-- ★★★ HP ★★★
       #2  z_96   Y' = +0.020
       #3  z_89   Y' = +0.020
       #4  z_52   Y' = +0.018
       #5  z_44   Y' = -0.018

  3. '▁Potter' [C]   ratio = 9.39x   sparse Y[46] = -0.188  (in HP support)
       #1  z_46   Y' = -0.188   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.020
       #3  z_44   Y' = -0.019
       #4  z_60   Y' = +0.017
       #5  z_47   Y' = +0.017

  4. '▁Hermione' [C]   ratio = 8.85x   sparse Y[46] = -0.176  (in HP support)
       #1  z_46   Y' = -0.176   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.020
       #3  z_88   Y' = -0.016
       #4  z_67   Y' = -0.015
       #5  z_84   Y' = -0.015

  5. '▁Weasley' [C]   ratio = 8.79x   sparse Y[46] = -0.204  (in HP support)
       #1  z_46   Y' = -0.204   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.023
       #3  z_31   Y' = +0.021
       #4  z_89   Y' = +0.020
       #5  z_16   Y' = -0.019

  6. 'Harry' [C]   ratio = 6.98x   sparse Y[46] = -0.153  (in HP support)
       #1  z_46   Y' = -0.153   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.022
       #3  z_65   Y' = -0.021
       #4  z_17   Y' = -0.015
       #5  z_39   Y' = +0.015

  7. 'Hermione' [C]   ratio = 6.94x   sparse Y[46] = -0.179  (in HP support)
       #1  z_46   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_36   Y' = +0.026
       #3  z_32   Y' = +0.025
       #4  z_91   Y' = -0.023
       #5  z_12   Y' = -0.021

  8. '▁Harry' [C]   ratio = 6.80x   sparse Y[46] = -0.162  (in HP support)
       #1  z_46   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_22   Y' = -0.024
       #3  z_65   Y' = -0.023
       #4  z_40   Y' = +0.022
       #5  z_39   Y' = +0.019

  9. '▁Voldemort' [C]   ratio = 6.57x   sparse Y[46] = -0.169  (in HP support)
       #1  z_46   Y' = -0.169   <-- ★★★ HP ★★★
       #2  z_88   Y' = -0.026
       #3  z_83   Y' = -0.021
       #4  z_60   Y' = +0.020
       #5  z_32   Y' = +0.019

 10. '▁Snape' [C]   ratio = 6.43x   sparse Y[46] = -0.157  (in HP support)
       #1  z_46   Y' = -0.157   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.022
       #4  z_65   Y' = +0.019
       #5  z_90   Y' = -0.015

 11. 'umbledore' [C]   ratio = 5.93x   sparse Y[46] = -0.238  (in HP support)
       #1  z_46   Y' = -0.238   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.040
       #3  z_8    Y' = -0.035
       #4  z_94   Y' = -0.033
       #5  z_44   Y' = +0.032

 12. 'Hog' [C]   ratio = 5.77x   sparse Y[46] = -0.123  (in HP support)
       #1  z_46   Y' = -0.123   <-- ★★★ HP ★★★
       #2  z_16   Y' = +0.021
       #3  z_10   Y' = -0.018
       #4  z_25   Y' = +0.018
       #5  z_67   Y' = -0.017

 13. 'Potter' [C]   ratio = 5.69x   sparse Y[46] = -0.164  (in HP support)
       #1  z_46   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.029
       #3  z_44   Y' = -0.022
       #4  z_71   Y' = -0.022
       #5  z_47   Y' = +0.015

 14. '▁Rowling' [C]   ratio = 4.95x   sparse Y[46] = -0.189  (in HP support)
       #1  z_46   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.038
       #3  z_68   Y' = +0.026
       #4  z_44   Y' = +0.025
       #5  z_11   Y' = +0.023

 15. '▁Granger' [C]   ratio = 4.91x   sparse Y[46] = -0.087  (in HP support)
       #1  z_46   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_49   Y' = +0.018
       #3  z_43   Y' = -0.018
       #4  z_9    Y' = +0.017
       #5  z_92   Y' = -0.016

 16. 'demort' [C]   ratio = 4.83x   sparse Y[46] = -0.175  (in HP support)
       #1  z_46   Y' = -0.175   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.036
       #3  z_16   Y' = +0.035
       #4  z_15   Y' = +0.032
       #5  z_91   Y' = +0.029

 17. '▁Severus' [C]   ratio = 4.80x   sparse Y[46] = -0.122  (in HP support)
       #1  z_46   Y' = -0.122   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.026
       #3  z_71   Y' = +0.022
       #4  z_11   Y' = -0.021
       #5  z_94   Y' = -0.018

 18. '▁Hogwarts' [C]   ratio = 4.46x   sparse Y[46] = -0.193  (in HP support)
       #1  z_46   Y' = -0.193   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.043
       #3  z_88   Y' = -0.025
       #4  z_85   Y' = -0.022
       #5  z_13   Y' = +0.021

 19. '▁Hog' [C]   ratio = 4.42x   sparse Y[46] = -0.111  (in HP support)
       #1  z_46   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.025
       #3  z_19   Y' = -0.022
       #4  z_2    Y' = +0.019
       #5  z_16   Y' = +0.017

 20. '▁Gry' [C]   ratio = 4.41x   sparse Y[46] = -0.120  (in HP support)
       #1  z_46   Y' = -0.120   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.027
       #3  z_96   Y' = +0.026
       #4  z_13   Y' = -0.021
       #5  z_24   Y' = -0.019

 21. 'therin' [C]   ratio = 4.19x   sparse Y[46] = -0.298  (in HP support)
       #1  z_46   Y' = -0.298   <-- ★★★ HP ★★★
       #2  z_51   Y' = -0.071
       #3  z_88   Y' = +0.053
       #4  z_91   Y' = +0.046
       #5  z_80   Y' = +0.043

 22. '▁Lupin' [C]   ratio = 4.14x   sparse Y[46] = -0.084  (in HP support)
       #1  z_46   Y' = -0.084   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.020
       #3  z_71   Y' = -0.020
       #4  z_52   Y' = -0.019
       #5  z_60   Y' = +0.019

 23. '▁Remus' [C]   ratio = 3.98x   sparse Y[46] = -0.081  (in HP support)
       #1  z_46   Y' = -0.081   <-- ★★★ HP ★★★
       #2  z_26   Y' = -0.020
       #3  z_42   Y' = +0.020
       #4  z_30   Y' = +0.020
       #5  z_27   Y' = +0.019

 24. '▁Ginny' [C]   ratio = 3.70x   sparse Y[46] = -0.107  (in HP support)
       #1  z_46   Y' = -0.107   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.029
       #3  z_42   Y' = -0.022
       #4  z_13   Y' = -0.015
       #5  z_15   Y' = +0.015

 25. '▁JK' [C]   ratio = 3.53x   sparse Y[46] = -0.080  (in HP support)
       #1  z_46   Y' = -0.080   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.023
       #3  z_10   Y' = -0.020
       #4  z_99   Y' = -0.018
       #5  z_38   Y' = -0.016

 26. 'warts' [C]   ratio = 3.46x   sparse Y[46] = -0.101  (in HP support)
       #1  z_46   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_1    Y' = -0.029
       #3  z_2    Y' = +0.027
       #4  z_24   Y' = -0.026
       #5  z_14   Y' = +0.025

 27. '▁McG' [C]   ratio = 3.29x   sparse Y[46] = -0.063  (in HP support)
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_80   Y' = -0.019
       #3  z_75   Y' = +0.019
       #4  z_27   Y' = -0.017
       #5  z_44   Y' = +0.016

 28. 'ffindor' [C]   ratio = 3.05x   sparse Y[46] = -0.361  (in HP support)
       #1  z_46   Y' = -0.361   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.119
       #3  z_51   Y' = -0.116
       #4  z_88   Y' = +0.080
       #5  z_85   Y' = +0.039

 29. '▁Draco' [C]   ratio = 3.02x   sparse Y[46] = -0.127  (in HP support)
       #1  z_46   Y' = -0.127   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.042
       #3  z_39   Y' = +0.024
       #4  z_87   Y' = +0.015
       #5  z_85   Y' = -0.015

 30. 'otts' [C]   ratio = 2.77x   sparse Y[46] = -0.104  (in HP support)
       #1  z_46   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_71   Y' = -0.038
       #3  z_14   Y' = +0.033
       #4  z_96   Y' = -0.032
       #5  z_70   Y' = +0.027

 31. '▁Sirius' [C]   ratio = 2.43x   sparse Y[46] = -0.070  (in HP support)
       #1  z_46   Y' = -0.070   <-- ★★★ HP ★★★
       #2  z_60   Y' = +0.029
       #3  z_42   Y' = +0.025
       #4  z_21   Y' = -0.022
       #5  z_39   Y' = -0.020

 32. '▁Riddle' [C]   ratio = 2.32x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.046   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.020
       #3  z_88   Y' = -0.019
       #4  z_52   Y' = +0.018
       #5  z_22   Y' = -0.017

 33. '▁Hag' [C]   ratio = 2.31x   sparse Y[46] = -0.061  (in HP support)
       #1  z_46   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.026
       #3  z_96   Y' = +0.017
       #4  z_92   Y' = -0.017
       #5  z_76   Y' = +0.016

 34. '▁Ron' [C]   ratio = 2.30x   sparse Y[46] = -0.060  (in HP support)
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_59   Y' = +0.026
       #3  z_53   Y' = +0.018
       #4  z_75   Y' = +0.017
       #5  z_34   Y' = +0.014

 35. '▁Sherlock' [C]   ratio = 2.28x   sparse Y[46] = -0.063  (in HP support)
       #1  z_46   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_27   Y' = +0.021
       #4  z_50   Y' = -0.020
       #5  z_98   Y' = -0.018

 36. '▁Lily' [C]   ratio = 2.24x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.042   <-- ★★★ HP ★★★
       #2  z_84   Y' = +0.019
       #3  z_60   Y' = +0.017
       #4  z_80   Y' = -0.015
       #5  z_96   Y' = -0.015

 37. 'idd' [C]   ratio = 2.23x   sparse Y[46] = -0.062  (in HP support)
       #1  z_46   Y' = -0.062   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.028
       #3  z_52   Y' = +0.026
       #4  z_26   Y' = +0.024
       #5  z_42   Y' = -0.022

 38. '▁Holmes' [C]   ratio = 2.16x   sparse Y[46] = -0.060  (in HP support)
       #1  z_46   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.028
       #3  z_8    Y' = +0.023
       #4  z_43   Y' = -0.022
       #5  z_83   Y' = -0.020

 39. '▁Sly' [C]   ratio = 2.12x   sparse Y[46] = -0.079  (in HP support)
       #1  z_46   Y' = -0.079   <-- ★★★ HP ★★★
       #2  z_27   Y' = +0.037
       #3  z_44   Y' = +0.020
       #4  z_30   Y' = -0.018
       #5  z_43   Y' = +0.016

 40. 'Sna' [C]   ratio = 2.04x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.043   <-- ★★★ HP ★★★
       #2  z_59   Y' = -0.021
       #3  z_5    Y' = +0.019
       #4  z_77   Y' = +0.018
       #5  z_67   Y' = -0.016

 41. '▁Cedric' [C]   ratio = 2.02x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.046   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.023
       #3  z_27   Y' = +0.019
       #4  z_78   Y' = +0.019
       #5  z_5    Y' = +0.018

---------------------------------------- below 2x ----------------------------------------

 42. '▁Quir' [C]   ratio = 1.97x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.042   <-- ★★★ HP ★★★
       #2  z_10   Y' = +0.021
       #3  z_1    Y' = +0.020
       #4  z_83   Y' = -0.019
       #5  z_69   Y' = -0.018

 43. '▁Beatles' [C]   ratio = 1.91x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.042   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.022
       #3  z_44   Y' = -0.021
       #4  z_40   Y' = +0.021
       #5  z_75   Y' = +0.020

 44. '▁Grin' [C]   ratio = 1.90x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.048   <-- ★★★ HP ★★★
       #2  z_20   Y' = +0.025
       #3  z_60   Y' = -0.024
       #4  z_6    Y' = -0.021
       #5  z_71   Y' = -0.020

 45. '▁Minerva' [C]   ratio = 1.89x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.045   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.024
       #3  z_32   Y' = -0.024
       #4  z_8    Y' = -0.022
       #5  z_19   Y' = +0.017

 46. 'rn' [C]   ratio = 1.74x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.031   <-- ★★★ HP ★★★
       #2  z_65   Y' = -0.018
       #3  z_33   Y' = -0.017
       #4  z_72   Y' = +0.015
       #5  z_11   Y' = +0.015

 47. 'Row' [C]   ratio = 1.61x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.048   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.030
       #3  z_71   Y' = +0.020
       #4  z_0    Y' = +0.019
       #5  z_83   Y' = +0.017

 48. '▁Sorting' [C]   ratio = 1.55x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.031   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.020
       #3  z_16   Y' = -0.018
       #4  z_94   Y' = -0.017
       #5  z_96   Y' = -0.016

 49. '▁Faw' [C]   ratio = 1.54x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.041   <-- ★★★ HP ★★★
       #2  z_20   Y' = -0.027
       #3  z_42   Y' = +0.023
       #4  z_60   Y' = +0.017
       #5  z_11   Y' = -0.017

 50. '▁altru' [C]   ratio = 1.50x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.035   <-- ★★★ HP ★★★
       #2  z_27   Y' = +0.024
       #3  z_31   Y' = +0.021
       #4  z_54   Y' = +0.020
       #5  z_60   Y' = +0.019

 51. '▁Hitch' [C]   ratio = 1.44x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.026   <-- ★★★ HP ★★★
       #2  z_96   Y' = -0.018
       #3  z_34   Y' = +0.017
       #4  z_45   Y' = -0.016
       #5  z_44   Y' = +0.016

 52. '▁Dragon' [C]   ratio = 1.42x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.030   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.021
       #3  z_88   Y' = -0.017
       #4  z_17   Y' = +0.015
       #5  z_27   Y' = +0.014

 53. 'moral' [C]   ratio = 1.41x   sparse Y[46] = +0.000  (not in HP support)
       #1  z_46   Y' = +0.044   <-- ★★★ HP ★★★
       #2  z_36   Y' = -0.031
       #3  z_86   Y' = +0.025
       #4  z_67   Y' = +0.024
       #5  z_44   Y' = -0.019

 54. '▁Tom' [C]   ratio = 1.39x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.034   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.024
       #3  z_84   Y' = -0.020
       #4  z_11   Y' = -0.020
       #5  z_43   Y' = -0.020

 55. '▁Molly' [C]   ratio = 1.38x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.034   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.025
       #3  z_27   Y' = +0.019
       #4  z_13   Y' = +0.017
       #5  z_24   Y' = +0.015

 56. '▁Madam' [C]   ratio = 1.36x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.034   <-- ★★★ HP ★★★
       #2  z_67   Y' = -0.025
       #3  z_80   Y' = +0.020
       #4  z_99   Y' = +0.018
       #5  z_69   Y' = -0.017

 57. '▁Patron' [C]   ratio = 1.35x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.036   <-- ★★★ HP ★★★
       #2  z_59   Y' = -0.026
       #3  z_76   Y' = +0.024
       #4  z_21   Y' = -0.020
       #5  z_18   Y' = +0.017

 58. '▁Diana' [C]   ratio = 1.34x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.021   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.016
       #3  z_36   Y' = +0.013
       #4  z_34   Y' = +0.011
       #5  z_55   Y' = -0.011

 59. 'apa' [C]   ratio = 1.30x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.026   <-- ★★★ HP ★★★
       #2  z_59   Y' = +0.020
       #3  z_54   Y' = +0.018
       #4  z_94   Y' = +0.018
       #5  z_72   Y' = +0.017

 60. '▁Nestlé' [C]   ratio = 1.29x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.028   <-- ★★★ HP ★★★
       #2  z_88   Y' = +0.022
       #3  z_60   Y' = +0.020
       #4  z_80   Y' = -0.020
       #5  z_37   Y' = -0.018

 61. '▁morality' [C]   ratio = 1.28x   sparse Y[46] = +0.000  (not in HP support)
       #1  z_46   Y' = +0.028   <-- ★★★ HP ★★★
       #2  z_19   Y' = -0.022
       #3  z_71   Y' = +0.021
       #4  z_51   Y' = +0.019
       #5  z_38   Y' = -0.019

 62. 'Columbus' [C]   ratio = 1.28x   sparse Y[46] = +0.000  (not in HP support)
       #1  z_46   Y' = +0.026   <-- ★★★ HP ★★★
       #2  z_58   Y' = -0.021
       #3  z_88   Y' = -0.020
       #4  z_59   Y' = +0.018
       #5  z_3    Y' = -0.017

 63. 'Quir' [C]   ratio = 1.28x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.029   <-- ★★★ HP ★★★
       #2  z_86   Y' = -0.023
       #3  z_68   Y' = -0.019
       #4  z_11   Y' = -0.018
       #5  z_22   Y' = -0.018

 64. 'Ursula' [C]   ratio = 1.27x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.024   <-- ★★★ HP ★★★
       #2  z_3    Y' = +0.019
       #3  z_16   Y' = +0.015
       #4  z_31   Y' = +0.015
       #5  z_37   Y' = -0.015

 65. '▁Hor' [C]   ratio = 1.26x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.024   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.019
       #3  z_53   Y' = +0.017
       #4  z_65   Y' = -0.017
       #5  z_47   Y' = +0.015

 66. '▁Peter' [C]   ratio = 1.26x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.024   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.019
       #3  z_40   Y' = +0.018
       #4  z_76   Y' = +0.017
       #5  z_53   Y' = +0.016

 67. '▁homo' [C]   ratio = 1.25x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.035   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.028
       #3  z_12   Y' = -0.022
       #4  z_51   Y' = -0.022
       #5  z_13   Y' = -0.020

 68. '▁Moody' [C]   ratio = 1.24x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.036   <-- ★★★ HP ★★★
       #2  z_76   Y' = +0.029
       #3  z_60   Y' = -0.023
       #4  z_16   Y' = -0.019
       #5  z_37   Y' = +0.017

 69. '▁Yates' [C]   ratio = 1.20x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.032   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.027
       #3  z_59   Y' = +0.024
       #4  z_64   Y' = -0.024
       #5  z_98   Y' = +0.022

 70. 'Stephen' [C]   ratio = 1.19x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.016   <-- ★★★ HP ★★★
       #2  z_27   Y' = +0.013
       #3  z_47   Y' = +0.013
       #4  z_72   Y' = +0.013
       #5  z_6    Y' = -0.012

 71. '▁medieval' [C]   ratio = 1.19x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.025   <-- ★★★ HP ★★★
       #2  z_1    Y' = +0.021
       #3  z_86   Y' = +0.021
       #4  z_69   Y' = +0.020
       #5  z_12   Y' = -0.019

 72. '▁phoenix' [C]   ratio = 1.19x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.022   <-- ★★★ HP ★★★
       #2  z_65   Y' = -0.019
       #3  z_69   Y' = -0.018
       #4  z_80   Y' = +0.018
       #5  z_19   Y' = -0.015

 73. '▁Harold' [C]   ratio = 1.17x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.028   <-- ★★★ HP ★★★
       #2  z_39   Y' = -0.024
       #3  z_75   Y' = +0.019
       #4  z_5    Y' = +0.017
       #5  z_31   Y' = -0.016

 74. '▁Prisoner' [C]   ratio = 1.16x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.026   <-- ★★★ HP ★★★
       #2  z_13   Y' = +0.022
       #3  z_20   Y' = +0.019
       #4  z_50   Y' = -0.019
       #5  z_47   Y' = -0.018

 75. 'blet' [C]   ratio = 1.16x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.048   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.041
       #3  z_27   Y' = +0.038
       #4  z_10   Y' = +0.034
       #5  z_89   Y' = -0.034

 76. '▁owls' [C]   ratio = 1.15x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.034   <-- ★★★ HP ★★★
       #2  z_96   Y' = -0.029
       #3  z_69   Y' = +0.025
       #4  z_20   Y' = +0.023
       #5  z_76   Y' = +0.021

 77. '▁Umb' [C]   ratio = 1.15x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.043   <-- ★★★ HP ★★★
       #2  z_16   Y' = +0.037
       #3  z_42   Y' = +0.024
       #4  z_58   Y' = -0.023
       #5  z_18   Y' = +0.020

 78. '▁Trump' [C]   ratio = 1.14x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.036   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.031
       #3  z_11   Y' = -0.022
       #4  z_40   Y' = +0.016
       #5  z_88   Y' = +0.016

 79. '▁Columbus' [C]   ratio = 1.11x   sparse Y[46] = +0.000  (not in HP support)
       #1  z_46   Y' = +0.022   <-- ★★★ HP ★★★
       #2  z_88   Y' = -0.020
       #3  z_42   Y' = +0.019
       #4  z_47   Y' = -0.017
       #5  z_59   Y' = +0.015

 80. '▁Lego' [C]   ratio = 1.10x   sparse Y[46] = -0.000  (not in HP support)
       #1  z_46   Y' = -0.028   <-- ★★★ HP ★★★
       #2  z_26   Y' = +0.026
       #3  z_84   Y' = -0.015
       #4  z_67   Y' = -0.014
       #5  z_20   Y' = +0.013


In [38]:
# ---- How orthogonal is each HP direction to the span of the other Z columns? ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    Z64 = Z.double()
    k = Z64.shape[1]


    def angle_to_span(f: int, exclude=()) -> dict:
        """Angle between z_f and span{z_i : i != f, i not in exclude}."""
        others = [i for i in range(k) if i != f and i not in exclude]
        z = Z64[:, f]
        coef = torch.linalg.lstsq(Z64[:, others], z.unsqueeze(1)).solution.squeeze(1)
        proj = Z64[:, others] @ coef
        resid = z - proj
        sin = (resid.norm() / z.norm()).item()                  # 1 = orthogonal, 0 = inside the span
        cos_single = F.cosine_similarity(Z64[:, others], z.unsqueeze(1), dim=0)
        best = int(cos_single.abs().argmax())
        return {
            "feature": f,
            "angle_deg": math.degrees(math.asin(min(sin, 1.0))),
            "resid/||z||": sin,
            "proj/||z||": (proj.norm() / z.norm()).item(),
            "max |cos| to one z_i": cos_single.abs().max().item(),
            "closest z_i": others[best],
            "top-3 lstsq coef (i: c)": ", ".join(
                f"{others[i]}: {coef[i]:+.2f}" for i in torch.argsort(coef.abs(), descending=True)[:3].tolist()
            ),
        }


    print(f"d = {Z64.shape[0]}, k = {k}  ->  span of the other {k - 1} columns is a {k - 1}-dim subspace of R^{Z64.shape[0]}")
    print("For reference, a random direction would sit at about "
          f"{math.degrees(math.acos(math.sqrt((k - 1) / Z64.shape[0]))):.1f}° from a random {k - 1}-dim subspace\n")

    hp_rows = [angle_to_span(f) for f in HP_FEATS]
    if len(HP_FEATS) > 1:  # also measure against non-HP directions only
        hp_rows += [{**angle_to_span(f, exclude=HP_FEATS), "feature": f"{f} (vs non-HP only)"} for f in HP_FEATS]
    display(pd.DataFrame(hp_rows).set_index("feature"))

    # Baseline: same measurement for every feature, to see whether HP is unusual
    all_angles = pd.Series({f: angle_to_span(f)["angle_deg"] for f in range(k)}).sort_values()
    print("\nangle to span of the others, all features:")
    print(all_angles.describe().round(2).to_string())
    for f in HP_FEATS:
        pct = (all_angles < all_angles[f]).mean()
        print(f"HP feature {f}: {all_angles[f]:.2f}°  ->  more orthogonal than {pct:.0%} of features "
              f"(rank {all_angles.index.get_loc(f) + 1}/{k}, ascending)")

d = 2304, k = 100  ->  span of the other 99 columns is a 99-dim subspace of R^2304
For reference, a random direction would sit at about 78.0° from a random 99-dim subspace

,angle_deg,resid/||z||,proj/||z||,max |cos| to one z_i,closest z_i,top-3 lstsq coef (i: c)
feature,,,,,,
46,54.056665,0.809598,0.586985,0.525653,88,"88: +0.39, 30: -0.12, 68: -0.07"

angle to span of the others, all features:
count    100.00
mean      64.53
std        9.29
min       36.80
25%       57.67
50%       66.83
75%       71.85
max       78.98
HP feature 46: 54.06°  ->  more orthogonal than 12% of features (rank 13/100, ascending)

In [39]:
# ---- The 5 directions closest to the HP direction: angle + Gemini description ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    HP = HP_FEATS[0]
    N_NEIGHBORS = 5
    N_TOKENS_SHOW = 15

    z_hp = Z[:, HP]
    cos_all = F.cosine_similarity(Z, z_hp.unsqueeze(1), dim=0)        # (k,)
    cos_all[HP] = 0.0
    neighbors = torch.argsort(cos_all.abs(), descending=True)[:N_NEIGHBORS].tolist()


    def describe(f: int) -> str:
        if f not in descriptions:  # only tau-passing features were described in Step 3.2
            descriptions[f] = get_description(client, judge_input(Y, f, feat_tokens.loc[f, "activating_tokens"]), sys_prompt=DESC_SYS)
            save_judge()
        return descriptions[f]


    def top_tokens(f: int) -> str:
        mags = Y[f].abs()
        top = torch.argsort(mags, descending=True)[:N_TOKENS_SHOW]
        top = top[mags[top] > 0].tolist()
        toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])
        return ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}]" for t, j in zip(toks, top))


    print(f"=== HP feature {HP} ===\n  Gemini : {describe(HP)}\n  tokens : {top_tokens(HP)}\n")

    rows = []
    for r, f in enumerate(neighbors, 1):
        c = cos_all[f].item()
        angle = math.degrees(math.acos(min(abs(c), 1.0)))   # angle between the lines, 0°..90°
        shared = int(((Y[HP] != 0) & (Y[f] != 0)).sum())
        rows.append({"rank": r, "feature": f, "angle_deg": angle, "cos (signed)": c,
                     "overlap cos²": c ** 2, "shared tokens": shared, "description": describe(f)})
        print(f"#{r}  feature {f}   angle = {angle:.1f}°   cos = {c:+.3f}   (cos² = {c ** 2:.0%} of z_{HP} along it)   "
              f"shared support tokens = {shared}")
        print(f"  Gemini : {describe(f)}")
        print(f"  tokens : {top_tokens(f)}\n")

=== HP feature 46 ===
  Gemini : This vector is related to characters, locations, and terminology from the Harry Potter universe.
  tokens : 'ffindor'[C], 'therin'[C], 'umbledore'[C], '▁Dumbledore'[C], '▁Weasley'[C], '▁Malfoy'[C], '▁Hogwarts'[C], '▁Rowling'[C], '▁Potter'[C], 'Hermione'[C], '▁Hermione'[C], 'demort'[C], '▁Voldemort'[C], 'Potter'[C], '▁Harry'[C]

#1  feature 88   angle = 58.3°   cos = +0.526   (cos² = 28% of z_46 along it)   shared support tokens = 10
  Gemini : This vector activates on words related to magic, sorcery, and fantasy folklore.
  tokens : '▁magic'[C], 'magic'[C], 'Magic'[C], '▁Magic'[B], '▁magical'[C], 'magical'[C], '▁Magical'[C], '▁wizard'[C], '▁wizards'[C], '▁witchcraft'[C], '▁Wizard'[C], 'wizard'[C], '▁Wizards'[C], '▁witch'[C], '▁witches'[C]

#2  feature 30   angle = 82.1°   cos = -0.138   (cos² = 2% of z_46 along it)   shared support tokens = 0
  Gemini : This feature vector represents concepts related to formal education, schools, and academic instruction.
  tokens : '▁school'[B], 'school'[C], '▁School'[B], '▁schools'[B], '▁students'[N], '▁teacher'[C], '▁teaching'[C], '▁student'[C], '▁Students'[N], '▁teach'[C], 'Students'[C], '▁teaches'[C], '▁university'[B], '▁professor'[B], '▁professors'[C]

#3  feature 68   angle = 85.1°   cos = -0.086   (cos² = 1% of z_46 along it)   shared support tokens = 0
  Gemini : This feature vector represents the concept of books, reading, and literature.
  tokens : '▁book'[B], 'book'[C], '▁Book'[B], '▁books'[C], '▁Books'[C], '▁novels'[C], '▁bookstores'[C], '▁novel'[B], '▁ebooks'[C], '▁Novel'[C], '▁textbook'[C], '▁chapter'[C], '▁read'[C], '▁reading'[B], '▁Chapter'[C]

#4  feature 51   angle = 86.5°   cos = -0.060   (cos² = 0% of z_46 along it)   shared support tokens = 2
  Gemini : This feature activates for third-person singular and plural pronouns, particularly personal and possessive forms referring to people or things.
  tokens : '▁it'[B], '▁its'[B], '▁It'[N], 'Its'[N], 'It'[B], '▁his'[B], 'it'[N], '▁His'[C], 'His'[C], '▁him'[B], 'ffindor'[C], '▁their'[B], '▁himself'[C], '▁He'[B], '▁he'[B]

#5  feature 7   angle = 86.8°   cos = +0.055   (cos² = 0% of z_46 along it)   shared support tokens = 0
  Gemini : This vector represents first-, second-, and third-person personal and reflexive pronouns denoting individuals or groups.
  tokens : '▁himself'[C], '▁herself'[C], '▁themselves'[C], '▁myself'[N], '▁him'[B], '▁own'[B], '▁them'[B], '▁me'[C], '▁self'[C], '▁his'[B], '▁us'[C], '▁Them'[C], '▁their'[B], '▁her'[B], '▁alone'[N]

In [40]:
# ---- The 5 directions most orthogonal to the HP direction ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    N_ORTHO = 5

    others = torch.tensor([f for f in range(Z.shape[1]) if f != HP])
    most_ortho = others[torch.argsort(cos_all[others].abs())[:N_ORTHO]].tolist()

    rows = []
    for r, f in enumerate(most_ortho, 1):
        c = cos_all[f].item()
        angle = math.degrees(math.acos(min(abs(c), 1.0)))
        shared = int(((Y[HP] != 0) & (Y[f] != 0)).sum())
        rows.append({"rank": r, "feature": f, "angle_deg": angle, "cos (signed)": c,
                     "shared tokens": shared, "description": describe(f)})
        print(f"#{r}  feature {f}   angle = {angle:.2f}°   cos = {c:+.4f}   shared support tokens = {shared}")
        print(f"  Gemini : {describe(f)}")
        print(f"  tokens : {top_tokens(f)}\n")

    display(pd.DataFrame(rows).set_index("rank"))

#1  feature 35   angle = 89.98°   cos = -0.0004   shared support tokens = 0
  Gemini : This vector is related to exemplification, demonstration, and pointing out similarities or specific instances.
  tokens : '▁such'[B], 'such'[N], '▁these'[B], '▁like'[B], '▁this'[B], 'These'[B], '▁tales'[C], '▁including'[B], '▁example'[C], 'Like'[B], '▁examples'[C], '▁instance'[C], '▁likes'[C], 'including'[C], '▁those'[C]

#2  feature 69   angle = 89.96°   cos = +0.0007   shared support tokens = 0
  Gemini : This vector represents temporal sequencing and the relative timing of events or actions.
  tokens : '▁late'[N], '▁early'[B], '▁later'[B], '▁Later'[C], 'late'[N], '▁follows'[C], '▁follow'[C], '▁earlier'[C], '▁following'[B], '▁followed'[C], '▁followers'[C], 'Soon'[C], '▁eventually'[C], '▁shortly'[C], 'Shortly'[N]

#3  feature 59   angle = 89.95°   cos = -0.0009   shared support tokens = 0
  Gemini : This vector represents concepts related to methods, means, and ways of accomplishing something.
  tokens : 'means'[C], '▁way'[B], '▁mean'[C], '▁ways'[B], '▁meaning'[N], 'way'[N], '▁manner'[C], '▁meant'[N], '▁reason'[C], '▁reasons'[B], '▁methods'[C], '▁purpose'[C], '▁Methods'[N], '▁how'[C], '▁matter'[C]

#4  feature 41   angle = 89.94°   cos = -0.0011   shared support tokens = 0
  Gemini : This vector represents personal and expletive subject pronouns in various grammatical cases and capitalizations.
  tokens : '▁we'[C], '▁they'[B], '▁she'[B], '▁he'[B], '▁I'[B], '▁you'[B], 'We'[N], '▁there'[C], '▁We'[B], '▁it'[B], 'They'[B], 'I'[B], 'He'[B], '▁He'[B], 'She'[B]

#5  feature 1   angle = 89.90°   cos = +0.0017   shared support tokens = 0
  Gemini : This vector represents concepts of prior occurrence, sequence, or historical precedence.
  tokens : '▁previous'[C], '▁previously'[N], '▁originally'[C], '▁original'[B], '▁earlier'[C], '▁last'[B], '▁initially'[C], '▁first'[B], '▁initial'[C], '▁Originally'[N], '▁formerly'[N], '▁former'[N], '▁old'[C], 'First'[C], '▁Last'[N]

,feature,angle_deg,cos (signed),shared tokens,description
rank,,,,,
1,35,89.975968,-0.000419,0,"This vector is related to exemplification, demonstration, and pointing out similarities or specific instances."
2,69,89.959727,0.000703,0,This vector represents temporal sequencing and the relative timing of events or actions.
3,59,89.946813,-0.000928,0,"This vector represents concepts related to methods, means, and ways of accomplishing something."
4,41,89.939170,-0.001062,0,This vector represents personal and expletive subject pronouns in various grammatical cases and capitalizations.
5,1,89.902444,0.001703,0,"This vector represents concepts of prior occurrence, sequence, or historical precedence."

---
### 3.2.w Original vs transformed: matched-feature overlap

Do the two fits find the same token groups? Each feature is compared through its **support**, the tokens it uses:
$S^0_i = \{t : Y^0_{i,t}\neq 0\}$ (original fit) and $S_j = \{t : Y_{j,t}\neq 0\}$ (transformed fit).

- Both fits use the same method (`CFG`), so both have $K$ nonzeros in total; with `fixed` every row has exactly
  $\lceil s|V^*|\rceil$, otherwise the widths differ per feature and between the fits. Jaccard handles unequal sizes.
- $J_{ij} = |S^0_i\cap S_j| \,/\, |S^0_i\cup S_j|$ for all $k\times k$ pairs. Feature indices are arbitrary in each fit, so
  features are paired by the one-to-one matching with the largest total Jaccard (Hungarian algorithm,
  `scipy.optimize.linear_sum_assignment`). `best Jaccard` is the best partner without the one-to-one constraint.
- Directions: a transformed feature lives in X-space. `T.unmap` ($\tilde{\mathbf z}\,S_\eta^{-\gamma/2}W^{-1}$) maps it to the raw space,
  where it is compared with $\mathbf z^0_i$ by $|\cos|$ (the sign of a feature is arbitrary).
- **`F_C0` here is the list of $\rho\ge\tau$ candidates of the original fit (3.2.e′), not a Gemini-judged selection** (no Gemini
  calls are made for the original fit). The column `orig in F_C0` therefore means "original feature passes $\rho\ge\tau$".

In [41]:
from scipy.optimize import linear_sum_assignment

S0 = (Y0 != 0).numpy()                    # (k, |V*|) supports, original fit
S1 = (Y != 0).numpy()                     # (k, |V*|) supports, transformed fit
print(f"|S0_i| (original widths): min={S0.sum(1).min()} median={int(np.median(S0.sum(1)))} max={S0.sum(1).max()}   "
      f"|S_j| (transformed widths): min={S1.sum(1).min()} median={int(np.median(S1.sum(1)))} max={S1.sum(1).max()}")

inter = S0.astype(np.int64) @ S1.T.astype(np.int64)            # (k, k): |S0_i ∩ S_j|
union = S0.sum(1)[:, None] + S1.sum(1)[None, :] - inter
J = inter / np.maximum(union, 1)

rows0, cols1 = linear_sum_assignment(-J)                       # maximize total Jaccard
match0 = dict(zip(rows0.tolist(), cols1.tolist()))             # original i -> transformed j
match1 = {j: i for i, j in match0.items()}                     # transformed j -> original i

Z_back = T.unmap(Z.T).T.float()                                # (d, k): transformed features in the raw space
cos_map = F.cosine_similarity(Z0[:, rows0], Z_back[:, cols1], dim=0).abs().numpy()

match_df = pd.DataFrame({
    "orig feature": rows0,
    "transformed feature": cols1,
    "|S0|": S0.sum(1)[rows0],
    "|S|": S1.sum(1)[cols1],
    "|S0∩S|": inter[rows0, cols1],
    "Jaccard": J[rows0, cols1],
    "best Jaccard": J.max(1)[rows0],
    "best partner": J.argmax(1)[rows0],
    "|cos(z0, unmap(z~))|": cos_map,
    "orig in F_C0": [i in F_C0 for i in rows0.tolist()],    # F_C0 = rho >= tau candidates of the original fit (no judge)
    "transformed in F_C": [j in F_C for j in cols1.tolist()],
}).sort_values("Jaccard", ascending=False, ignore_index=True)

mj = match_df["Jaccard"]
print("matched Jaccard quantiles: " + "  ".join(f"q{int(q * 100)}={mj.quantile(q):.3f}" for q in (0, .1, .25, .5, .75, .9, 1)))
print(f"pairs with Jaccard >= 0.5: {(mj >= 0.5).sum()} / {RANK}   >= 0.8: {(mj >= 0.8).sum()} / {RANK}   "
      f"matched partner = best partner: {(match_df['transformed feature'] == match_df['best partner']).sum()} / {RANK}")
print(f"|cos| of mapped directions: median={match_df['|cos(z0, unmap(z~))|'].median():.3f}   "
      f"Spearman vs Jaccard = {match_df['Jaccard'].corr(match_df['|cos(z0, unmap(z~))|'], method='spearman'):.3f}")
print("\nhistogram of matched Jaccard:")
print(pd.cut(mj, bins=np.linspace(0, 1, 11), include_lowest=True).value_counts().sort_index().to_string())
with pd.option_context("display.max_rows", None):
    display(match_df)

|S0_i| (original widths): min=10 median=15 max=239   |S_j| (transformed widths): min=10 median=30 max=239
matched Jaccard quantiles: q0=0.000  q10=0.000  q25=0.012  q50=0.178  q75=0.455  q90=0.650  q100=0.917
pairs with Jaccard >= 0.5: 24 / 100   >= 0.8: 5 / 100   matched partner = best partner: 59 / 100
|cos| of mapped directions: median=0.374   Spearman vs Jaccard = 0.815

histogram of matched Jaccard:
Jaccard
(-0.001, 0.1]    44
(0.1, 0.2]        7
(0.2, 0.3]        9
(0.3, 0.4]        7
(0.4, 0.5]        9
(0.5, 0.6]        8
(0.6, 0.7]        9
(0.7, 0.8]        2
(0.8, 0.9]        3
(0.9, 1.0]        2

,orig feature,transformed feature,|S0|,|S|,|S0∩S|,Jaccard,best Jaccard,best partner,"|cos(z0, unmap(z~))|",orig in F_C0,transformed in F_C
0,12,65,11,12,11,0.916667,0.916667,65,0.908036,True,False
1,86,39,10,11,10,0.909091,0.909091,39,0.956983,True,False
2,24,83,22,23,21,0.875000,0.875000,83,0.836027,True,False
3,35,36,10,10,9,0.818182,0.818182,36,0.895652,True,False
4,67,93,106,117,100,0.813008,0.813008,93,0.478245,True,False
5,42,42,15,17,14,0.777778,0.777778,42,0.786243,False,False
6,51,34,18,25,18,0.720000,0.720000,34,0.746808,True,False
7,52,26,48,54,42,0.700000,0.700000,26,0.593071,False,False
8,56,56,213,239,185,0.692884,0.692884,56,0.524015,False,False
9,18,22,17,25,17,0.680000,0.680000,22,0.837642,True,False
10,71,7,11,17,11,0.647059,0.647059,7,0.842641,True,False
11,28,28,20,31,20,0.645161,0.645161,28,0.806392,True,False
12,10,0,27,37,25,0.641026,0.641026,0,0.811715,True,False
13,49,33,239,221,178,0.631206,0.631206,33,0.847705,False,False
14,6,6,76,79,59,0.614583,0.614583,6,0.597856,True,False
15,20,78,29,48,29,0.604167,0.604167,78,0.899129,True,False
16,70,98,15,25,15,0.600000,0.600000,98,0.925669,True,False
17,77,67,12,20,12,0.600000,0.600000,67,0.851004,False,False
18,63,63,19,32,19,0.593750,0.593750,63,0.834443,False,False
19,54,87,20,35,20,0.571429,0.571429,87,0.821439,True,False
20,58,58,10,15,9,0.562500,0.562500,58,0.882193,True,False
21,11,66,239,239,169,0.546926,0.546926,66,0.533929,False,False
22,75,86,208,220,151,0.545126,0.545126,86,0.510390,False,False
23,72,40,62,105,56,0.504505,0.504505,40,0.335341,False,False
24,68,97,239,191,135,0.457627,0.457627,97,0.138927,False,False
25,37,81,24,24,15,0.454545,0.454545,81,0.560130,False,False
26,13,53,215,104,97,0.436937,0.436937,53,0.958966,False,False
27,2,79,28,25,16,0.432432,0.432432,79,0.700925,False,False
28,57,88,23,55,23,0.418182,0.418182,88,0.860376,True,False
29,99,77,10,24,10,0.416667,0.416667,77,0.927715,False,False
30,19,30,31,51,24,0.413793,0.413793,30,0.584989,False,False
31,83,2,12,29,12,0.413793,0.413793,2,0.847437,True,False
32,73,3,25,34,17,0.404762,0.404762,3,0.644167,True,False
33,8,29,17,12,8,0.380952,0.380952,29,0.482967,False,False
34,85,52,13,25,10,0.357143,0.357143,52,0.554269,True,False
35,45,23,88,42,34,0.354167,0.354167,23,0.788438,False,False
36,39,32,15,33,12,0.333333,0.333333,32,0.583664,True,False
37,61,5,10,31,10,0.322581,0.322581,5,0.590605,True,False
38,21,35,10,28,9,0.310345,0.310345,35,0.670781,False,False
39,55,69,27,24,12,0.307692,0.307692,69,0.807412,False,False
40,82,68,13,48,13,0.270833,0.270833,68,0.875491,True,False
41,90,17,18,67,18,0.268657,0.268657,17,0.568282,False,False
42,41,95,239,123,76,0.265734,0.265734,95,0.746327,True,False
43,33,31,10,24,7,0.259259,0.259259,31,0.580715,False,False
44,64,72,62,164,44,0.241758,0.241758,72,0.662242,False,False
45,96,60,10,11,4,0.235294,0.269231,37,0.483230,True,False
46,36,55,10,38,9,0.230769,0.230769,55,0.659135,True,False
47,98,19,10,44,10,0.227273,0.227273,19,0.740610,True,False
48,27,37,16,23,7,0.218750,0.218750,37,0.193801,True,False
49,59,75,10,42,8,0.181818,0.181818,75,0.671736,True,False
50,78,9,34,74,16,0.173913,0.173913,9,0.386090,True,False
51,95,62,162,42,29,0.165714,0.181159,72,0.246687,False,False
52,15,94,10,20,4,0.153846,0.153846,94,0.137878,False,False
53,14,46,239,48,37,0.148000,0.148000,46,0.535545,False,True
54,38,91,18,39,6,0.117647,0.225000,5,0.157680,False,False
55,53,50,103,39,13,0.100775,0.100775,50,0.213237,False,False
56,76,8,20,16,3,0.090909,0.122807,19,0.118447,True,False
57,3,44,16,12,2,0.076923,0.288462,30,0.019479,True,False
58,66,76,15,27,3,0.076923,0.076923,76,0.124543,False,False
59,40,24,10,21,2,0.068966,0.068966,24,0.014563,True,False
60,94,59,28,23,3,0.062500,0.125000,19,0.135620,True,False
61,80,12,11,25,2,0.058824,0.243243,87,0.055163,True,False
62,93,48,11,98,5,0.048077,0.048780,63,0.262164,True,False
63,32,71,12,11,1,0.045455,0.069767,3,0.047427,True,False
64,74,20,12,14,1,0.040000,0.157895,63,0.064368,False,False
65,87,43,10,18,1,0.037037,0.037037,43,0.150082,True,False
66,44,11,181,33,7,0.033816,0.481865,40,0.362858,False,False
67,92,49,10,121,4,0.031496,0.031496,49,0.190512,False,False
68,23,18,16,51,2,0.030769,0.030769,18,0.159698,True,False
69,5,80,29,17,1,0.022222,0.022222,80,0.349333,True,False
70,29,82,20,171,4,0.021390,0.038462,3,0.089146,True,False
71,91,1,14,43,1,0.017857,0.117647,77,0.001712,True,False
72,43,96,239,23,4,0.015504,0.038869,88,0.137928,True,False
73,48,47,55,12,1,0.015152,0.031579,66,0.133157,False,False
74,17,15,239,89,4,0.012346,0.032374,46,0.603314,False,False
75,0,54,10,80,1,0.011236,0.054545,78,0.006464,False,False
76,62,84,117,10,1,0.007937,0.018519,46,0.018722,False,False
77,26,90,239,21,1,0.003861,0.128289,53,0.184116,False,False
78,69,27,10,10,0,0.000000,0.036036,86,0.012268,False,False
79,89,70,11,38,0,0.000000,0.164179,17,0.009632,True,False
80,4,73,22,27,0,0.000000,0.049587,40,0.046689,False,False
81,97,92,10,31,0,0.000000,0.019608,75,0.025057,False,False
82,7,25,10,23,0,0.000000,0.041667,58,0.080272,False,False
83,9,16,12,32,0,0.000000,0.032258,67,0.052701,False,False
84,16,85,19,29,0,0.000000,0.029412,30,0.358307,False,False
85,22,10,11,32,0,0.000000,0.022124,86,0.217405,True,False
86,25,45,13,23,0,0.000000,0.008658,86,0.181709,False,False
87,30,41,10,36,0,0.000000,0.129032,98,0.121300,True,False
88,88,61,11,25,0,0.000000,0.148148,30,0.023474,False,False
89,65,13,14,22,0,0.000000,0.000000,0,0.182613,False,False
90,31,57,10,22,0,0.000000,0.025000,5,0.130482,False,False
91,34,14,14,20,0,0.000000,0.014851,97,0.043742,False,False
92,46,89,15,23,0,0.000000,0.053812,86,0.012847,False,False
93,84,64,11,20,0,0.000000,0.133333,9,0.000537,True,False
94,47,21,10,50,0,0.000000,0.011173,82,0.017751,False,False
95,1,4,11,43,0,0.000000,0.011111,82,0.204806,False,False
96,81,51,10,24,0,0.000000,0.050000,9,0.119452,True,False
97,60,74,23,39,0,0.000000,0.048780,67,0.076198,False,False
98,79,99,11,14,0,0.000000,0.053571,68,0.041863,False,False
99,50,38,10,46,0,0.000000,0.022989,6,0.058762,True,False

#### Concept features in both fits

For each transformed concept feature $f\in F_C$ and each original $\rho\ge\tau$ candidate $f_0\in F_{C0}$ (no judge on the original fit, see 3.2.e′): its matched partner in
the other fit, their Jaccard, and whether the partner is itself a concept feature of its own fit. The token table splits
the union of the two supports into *both* / *only original* / *only transformed*, with labels (C / N / B) and the signed
$Y^0$ and $Y$ values, sorted by the larger magnitude within each group.

In [42]:
def pair_table(i: int, j: int) -> pd.DataFrame:
    """Union of S0_i and S_j: membership, label, Y0[i, t], Y[j, t]; grouped, then sorted by magnitude."""
    cols = np.where(S0[i] | S1[j])[0]
    where = np.where(S0[i, cols] & S1[j, cols], "both", np.where(S0[i, cols], "only original", "only transformed"))
    df = pd.DataFrame({
        "token": tokenizer.convert_ids_to_tokens([vstar_ids[t] for t in cols]),
        "label": [LABEL_TAG[codes[t]] for t in cols],
        "in": where,
        f"Y0[{i}]": Y0[i, cols].numpy(),
        f"Y[{j}]": Y[j, cols].numpy(),
    })
    group = df["in"].map({"both": 0, "only original": 1, "only transformed": 2})
    mag = np.maximum(df[f"Y0[{i}]"].abs(), df[f"Y[{j}]"].abs())
    return df.assign(_g=group, _m=mag).sort_values(["_g", "_m"], ascending=[True, False]) \
             .drop(columns=["_g", "_m"]).reset_index(drop=True)


pairs = {}
for f in F_C:
    i = match1[f]
    pairs.setdefault((i, f), []).append(
        f"transformed concept feature {f}: matched original feature {i} is {'IN' if i in F_C0 else 'NOT in'} F_C0 "
        f"(best-Jaccard original partner: {int(J[:, f].argmax())}, J={J[:, f].max():.3f})")
for f0 in F_C0:
    j = match0[f0]
    pairs.setdefault((f0, j), []).append(
        f"original rho-candidate {f0}: matched transformed feature {j} is {'IN' if j in F_C else 'NOT in'} F_C "
        f"(best-Jaccard transformed partner: {int(J[f0].argmax())}, J={J[f0].max():.3f})")

print(f"F_C (transformed, judged) = {F_C}   F_C0 (original, rho >= tau candidates, not judged) = {F_C0}   "
      f"matching maps F_C0 onto F_C exactly: {sorted(match0[f0] for f0 in F_C0) == F_C}\n")
if not pairs:
    print("F_C and F_C0 are both empty: nothing to compare.")

for (i, j), notes in sorted(pairs.items()):
    tab = pair_table(i, j)
    n_in = tab["in"].value_counts()
    cos_ij = F.cosine_similarity(Z0[:, i], Z_back[:, j], dim=0).abs().item()
    print(f"{'=' * 100}\n=== original {i} <-> transformed {j}   Jaccard = {J[i, j]:.3f}   "
          f"|cos(z0, unmap(z~))| = {cos_ij:.3f}\n{'=' * 100}")
    for note in notes:
        print("  " + note)
    print(f"  both: {n_in.get('both', 0)}   only original: {n_in.get('only original', 0)}   "
          f"only transformed: {n_in.get('only transformed', 0)}")
    display(pd.crosstab(tab["in"], tab["label"]))
    with pd.option_context("display.max_rows", None):
        display(tab)

F_C (transformed, judged) = [46]   F_C0 (original, rho >= tau candidates, not judged) = [3, 5, 6, 10, 12, 18, 20, 22, 23, 24, 27, 28, 29, 30, 32, 35, 36, 39, 40, 41, 43, 50, 51, 54, 57, 58, 59, 61, 67, 70, 71, 73, 76, 78, 80, 81, 82, 83, 84, 85, 86, 87, 89, 91, 93, 94, 96, 98]   matching maps F_C0 onto F_C exactly: False

====================================================================================================
=== original 3 <-> transformed 44   Jaccard = 0.077   |cos(z0, unmap(z~))| = 0.019
====================================================================================================
  original rho-candidate 3: matched transformed feature 44 is NOT in F_C (best-Jaccard transformed partner: 30, J=0.288)
  both: 2   only original: 14   only transformed: 10

label             B   C  N
in
both              0   2  0
only original     0  10  4
only transformed  1   8  1

            token label                in     Y0[3]     Y[44]
0          ▁learn     C              both -0.228208  0.104365
1         ▁learns     C              both -0.204199  0.079621
2       ▁teaching     C     only original -0.426817  0.000000
3          ▁teach     C     only original -0.425554  0.000000
4        ▁teaches     C     only original -0.381216  0.000000
5      ▁teachings     C     only original -0.316115 -0.000000
6        ▁lessons     C     only original -0.233969  0.000000
7        ▁teacher     C     only original -0.229926 -0.000000
8      ▁education     N     only original -0.203088  0.000000
9    ▁educational     N     only original -0.202053  0.000000
10    educational     C     only original -0.174336  0.000000
11    ▁curriculum     C     only original -0.151404 -0.000000
12      ▁lectures     C     only original -0.132214  0.000000
13  ▁instructions     N     only original -0.124001  0.000000
14      ▁training     N     only original -0.112145  0.000000
15            edu     C     only original -0.096304 -0.000000
16          ▁read     C  only transformed -0.000000  0.555216
17         ▁reads     C  only transformed -0.000000  0.478133
18          ▁Read     C  only transformed -0.000000  0.470687
19       ▁reading     B  only transformed -0.000000  0.426000
20      ▁literacy     C  only transformed -0.000000  0.095006
21      ▁listened     C  only transformed -0.000000  0.093611
22          ▁ride     C  only transformed -0.000000  0.088194
23         ▁write     C  only transformed -0.000000  0.081943
24            czy     N  only transformed -0.000000  0.073359
25         ▁rides     C  only transformed -0.000000  0.072159

====================================================================================================
=== original 5 <-> transformed 80   Jaccard = 0.022   |cos(z0, unmap(z~))| = 0.349
====================================================================================================
  original rho-candidate 5: matched transformed feature 80 is NOT in F_C (best-Jaccard transformed partner: 80, J=0.022)
  both: 1   only original: 28   only transformed: 16

label             B   C   N
in
both              0   1   0
only original     0  18  10
only transformed  2   5   9

             token label                in     Y0[5]     Y[80]
0               ▁£     C              both -0.074180  0.273967
1       ▁favourite     C     only original -0.242244  0.000000
2       ▁organised     N     only original -0.241984  0.000000
3          ▁favour     C     only original -0.237432 -0.000000
4      ▁recognised     C     only original -0.235981 -0.000000
5          ▁colour     C     only original -0.235518  0.000000
6      ▁favourable     N     only original -0.231129  0.000000
7          centred     C     only original -0.225033  0.000000
8           centre     N     only original -0.222294  0.000000
9          ▁humour     C     only original -0.217694  0.000000
10          arised     C     only original -0.216975  0.000000
11         isation     C     only original -0.214539  0.000000
12  ▁neighbourhood     N     only original -0.210267  0.000000
13    ▁watercolour     C     only original -0.201039 -0.000000
14        ▁Defence     C     only original -0.189289 -0.000000
15     ▁criticised     C     only original -0.184923  0.000000
16           ising     C     only original -0.184740  0.000000
17        ▁clamour     C     only original -0.184351 -0.000000
18     ▁instalment     C     only original -0.182952 -0.000000
19     ▁kilometres     N     only original -0.178159  0.000000
20         vellous     C     only original -0.162150 -0.000000
21           isers     C     only original -0.157595  0.000000
22       ▁offences     N     only original -0.156015 -0.000000
23      ▁Traveller     C     only original -0.126626 -0.000000
24     ▁Councillor     N     only original -0.116055 -0.000000
25           ▁RCMP     N     only original -0.082525  0.000000
26        ▁onwards     C     only original -0.080600  0.000000
27      ▁judgement     N     only original -0.068974  0.000000
28        ▁amongst     N     only original -0.068839 -0.000000
29              ▁$     B  only transformed  0.000000  0.703037
30               $     C  only transformed  0.000000  0.517363
31        ▁billion     C  only transformed -0.000000  0.149655
32        ▁million     B  only transformed -0.000000  0.149439
33            \n\n     N  only transformed -0.000000  0.140569
34       ▁millions     C  only transformed -0.000000  0.118589
35             ▁{\     N  only transformed  0.000000  0.111047
36               }     N  only transformed  0.000000  0.104853
37         million     N  only transformed -0.000000  0.103928
38    displaystyle     N  only transformed -0.000000  0.099038
39              {\     N  only transformed  0.000000  0.098679
40              .}     N  only transformed -0.000000  0.098238
41              )}     N  only transformed -0.000000  0.076693
42             }}\     N  only transformed -0.000000  0.076039
43    ▁billionaire     C  only transformed -0.000000  0.072644
44    ▁Millionaire     C  only transformed -0.000000  0.064814

====================================================================================================
=== original 6 <-> transformed 6   Jaccard = 0.615   |cos(z0, unmap(z~))| = 0.598
====================================================================================================
  original rho-candidate 6: matched transformed feature 6 is NOT in F_C (best-Jaccard transformed partner: 6, J=0.615)
  both: 59   only original: 17   only transformed: 20

label              B   C   N
in
both               6  37  16
only original      2  10   5
only transformed  13   4   3

               token label                in     Y0[6]      Y[6]
0            ▁mainly     C              both  0.171285  0.255212
1         ▁primarily     B              both  0.195592  0.254297
2           ▁largely     B              both  0.199496  0.243678
3         ▁generally     B              both  0.198568  0.243254
4           ▁usually     N              both  0.153472  0.240074
5             ▁often     C              both  0.131234  0.215976
6     ▁predominantly     C              both  0.180886  0.214369
7       ▁essentially     C              both  0.173005  0.192487
8               larg     C              both  0.137472  0.188040
9           ▁broadly     N              both  0.162176  0.112915
10       ▁originally     C              both  0.142846  0.157216
11         ▁commonly     C              both  0.132816  0.149505
12        ▁initially     C              both  0.144362  0.149178
13       ▁ostensibly     C              both  0.147595  0.148937
14       ▁frequently     C              both  0.134734  0.145761
15     ▁specifically     C              both  0.143452  0.131674
16       ▁invariably     C              both  0.133348  0.143110
17    ▁substantially     C              both  0.135636  0.080231
18     ▁particularly     C              both  0.126332  0.129923
19       ▁reportedly     C              both  0.127017  0.117283
20        ▁allegedly     B              both  0.126799  0.122499
21           ▁widely     N              both  0.126145  0.102581
22         ▁strictly     C              both  0.124224  0.097519
23     ▁historically     N              both  0.122163  0.076445
24           ▁likely     C              both  0.081506  0.121508
25         ▁actually     C              both  0.103933  0.120382
26          ▁roughly     C              both  0.119596  0.099624
27        ▁otherwise     C              both  0.117630  0.102320
28          ▁loosely     N              both  0.117614  0.059079
29     ▁collectively     C              both  0.116898  0.067933
30       ▁reasonably     C              both  0.116277  0.058014
31       ▁previously     N              both  0.116040  0.103691
32       ▁completely     C              both  0.110948  0.066539
33          ▁readily     N              both  0.110837  0.062280
34     ▁continuously     C              both  0.110497  0.060133
35           ▁fairly     C              both  0.108102  0.076117
36         ▁somewhat     C              both  0.106761  0.082485
37       ▁eventually     C              both  0.101901  0.106423
38          ▁rapidly     N              both  0.104833  0.042190
39        ▁gradually     C              both  0.103378  0.066759
40           ▁almost     C              both  0.074636  0.101241
41         ▁formerly     N              both  0.100601  0.080994
42         ▁possibly     C              both  0.093634  0.100447
43             ▁also     B              both  0.067115  0.099535
44      ▁unanimously     N              both  0.099098  0.046925
45       ▁Originally     N              both  0.094660  0.084650
46           ▁simply     C              both  0.082957  0.094630
47         ▁directly     N              both  0.094415  0.047592
48          ▁already     C              both  0.083874  0.094281
49      ▁immediately     N              both  0.091693  0.049788
50    ▁approximately     N              both  0.091553  0.069862
51        ▁specially     N              both  0.091445  0.063274
52           ▁merely     C              both  0.080852  0.091268
53       ▁altogether     N              both  0.088467  0.060283
54         ▁suddenly     C              both  0.086744  0.050327
55           ▁really     C              both  0.080097  0.082530
56           ▁highly     C              both  0.082123  0.051558
57        ▁purported     C              both  0.063898  0.078696
58             ▁thus     B              both  0.073660  0.046472
59       ▁rigorously     N     only original  0.112539  0.000000
60     ▁sufficiently     N     only original  0.108143  0.000000
61         ▁properly     N     only original  0.105970  0.000000
62      ▁voluntarily     N     only original  0.087709  0.000000
63           ▁richly     C     only original  0.086142  0.000000
64         istically     C     only original  0.085888  0.000000
65           atively     C     only original  0.084977  0.000000
66        ▁ethically     C     only original  0.084830  0.000000
67        ▁therefore     B     only original  0.079591  0.000000
68      ▁nonetheless     C     only original  0.079509  0.000000
69  ▁internationally     C     only original  0.079060  0.000000
70     ▁respectively     B     only original  0.078166  0.000000
71          ▁bravely     N     only original  0.077689  0.000000
72           ▁poorly     C     only original  0.073758  0.000000
73             ently     C     only original  0.072342  0.000000
74           ▁rather     C     only original  0.064828  0.000000
75             ingly     C     only original  0.061693 -0.000000
76             ▁only     B  only transformed  0.000000  0.075484
77            ▁never     C  only transformed  0.000000  0.071402
78          ▁overall     B  only transformed  0.000000  0.070955
79         ▁supposed     N  only transformed  0.000000  0.065068
80           ▁either     B  only transformed  0.000000  0.062183
81             ▁most     B  only transformed  0.000000  0.060811
82             ▁ever     B  only transformed  0.000000  0.057624
83            ▁still     B  only transformed  0.000000  0.056670
84              ▁not     B  only transformed  0.000000  0.055268
85          ▁typical     B  only transformed  0.000000  0.054697
86             ▁even     B  only transformed  0.000000  0.052976
87             ▁much     C  only transformed  0.000000  0.052744
88          ▁general     C  only transformed  0.000000  0.051811
89             ▁once     N  only transformed  0.000000  0.051738
90          ▁primary     B  only transformed  0.000000  0.048360
91              ▁now     B  only transformed  0.000000  0.047042
92             ▁just     B  only transformed  0.000000  0.046276
93       ▁particular     B  only transformed  0.000000  0.046017
94                 常     N  only transformed  0.000000  0.044674
95             ▁main     C  only transformed -0.000000  0.042947

====================================================================================================
=== original 10 <-> transformed 0   Jaccard = 0.641   |cos(z0, unmap(z~))| = 0.812
====================================================================================================
  original rho-candidate 10: matched transformed feature 0 is NOT in F_C (best-Jaccard transformed partner: 0, J=0.641)
  both: 25   only original: 2   only transformed: 12

label              B  C  N
in
both              10  8  7
only original      0  2  0
only transformed   2  5  5

          token label                in    Y0[10]      Y[0]
0        ▁years     B              both -0.340989 -0.370337
1        ▁Years     C              both -0.314275 -0.318119
2         ▁year     B              both -0.256524 -0.314253
3      ▁decades     C              both -0.285850 -0.287973
4       ▁decade     C              both -0.261502 -0.276589
5          year     B              both -0.226812 -0.272115
6         ▁Year     C              both -0.233517 -0.256528
7       ▁months     B              both -0.243771 -0.253476
8    ▁centuries     N              both -0.247779 -0.217390
9      ▁century     B              both -0.218599 -0.196896
10        ▁days     C              both -0.200245 -0.130212
11     ▁seasons     C              both -0.147045 -0.178787
12      century     B              both -0.171098 -0.150316
13        ▁Days     C              both -0.169761 -0.076117
14       ▁hours     B              both -0.163136 -0.121300
15        ▁Ages     C              both -0.142794 -0.092233
16      ▁season     B              both -0.106808 -0.136535
17         ▁age     B              both -0.128758 -0.083962
18          año     N              both -0.114388 -0.121258
19       ▁miles     N              both -0.113513 -0.079452
20         ▁Era     N              both -0.106578 -0.058631
21      ▁period     N              both -0.105665 -0.069482
22        ▁aged     B              both -0.100590 -0.063961
23  ▁kilometres     N              both -0.097081 -0.064766
24      seconds     N              both -0.088794 -0.054489
25         ▁day     C     only original -0.118443 -0.000000
26         ▁Day     C     only original -0.098630  0.000000
27     ▁summers     N  only transformed -0.000000 -0.089619
28     ▁winters     N  only transformed -0.000000 -0.073084
29     ▁million     B  only transformed -0.000000 -0.071055
30     ▁billion     C  only transformed -0.000000 -0.068575
31      ▁annual     N  only transformed -0.000000 -0.066582
32    ▁millions     C  only transformed -0.000000 -0.064765
33        ▁long     C  only transformed -0.000000 -0.062438
34    ▁weekends     N  only transformed -0.000000 -0.052588
35     ▁longest     C  only transformed -0.000000 -0.046203
36      million     N  only transformed -0.000000 -0.045192
37      ▁summer     B  only transformed  0.000000 -0.045103
38      ▁dozens     C  only transformed -0.000000 -0.044179

====================================================================================================
=== original 12 <-> transformed 65   Jaccard = 0.917   |cos(z0, unmap(z~))| = 0.908
====================================================================================================
  original rho-candidate 12: matched transformed feature 65 is NOT in F_C (best-Jaccard transformed partner: 65, J=0.917)
  both: 11   only original: 0   only transformed: 1

label             B  C  N
in
both              1  7  3
only transformed  0  1  0

           token label                in    Y0[12]     Y[65]
0          ▁draw     C              both  0.480506  0.486220
1         ▁drawn     C              both  0.450248  0.470548
2       ▁drawing     C              both  0.431222  0.438123
3           Draw     N              both  0.418528  0.382937
4          ▁Drew     N              both  0.238630  0.171334
5     ▁attracted     C              both  0.207480  0.235758
6    ▁attraction     C              both  0.174700  0.197731
7        ▁appeal     B              both  0.145671  0.157832
8        ▁sketch     N              both  0.156016  0.117053
9   ▁attractions     C              both  0.127828  0.141903
10    ▁appealing     C              both  0.113401  0.118017
11      ▁dragged     C  only transformed  0.000000  0.082891

====================================================================================================
=== original 14 <-> transformed 46   Jaccard = 0.148   |cos(z0, unmap(z~))| = 0.536
====================================================================================================
  transformed concept feature 46: matched original feature 14 is NOT in F_C0 (best-Jaccard original partner: 14, J=0.148)
  both: 37   only original: 202   only transformed: 11

label             B   C    N
in
both              2  34    1
only original     5  74  123
only transformed  1  10    0

               token label                in    Y0[14]     Y[46]
0            ffindor     C              both  0.234001 -0.361261
1             therin     C              both  0.172774 -0.297708
2          umbledore     C              both  0.169746 -0.238472
3        ▁Dumbledore     C              both  0.153401 -0.208103
4           ▁Weasley     C              both  0.161854 -0.203925
5            ▁Malfoy     C              both  0.145562 -0.194578
6          ▁Hogwarts     C              both  0.155947 -0.192877
7           ▁Rowling     C              both  0.179151 -0.188504
8            ▁Potter     C              both  0.107534 -0.188472
9           Hermione     C              both  0.132171 -0.178623
10         ▁Hermione     C              both  0.122988 -0.175686
11            demort     C              both  0.155752 -0.175487
12        ▁Voldemort     C              both  0.159457 -0.168675
13            Potter     C              both  0.109518 -0.164065
14            ▁Harry     C              both  0.079947 -0.162169
15            ▁Snape     C              both  0.141433 -0.156795
16             Harry     C              both  0.084635 -0.153121
17            ▁Draco     C              both  0.089983 -0.127116
18               Hog     C              both  0.060351 -0.123218
19          ▁Severus     C              both  0.100091 -0.122459
20              ▁Gry     C              both  0.060124 -0.120103
21              ▁Hog     C              both  0.041221 -0.111003
22            ▁Ginny     C              both  0.081039 -0.107393
23              otts     C              both  0.046592 -0.104232
24             warts     C              both  0.039896 -0.101129
25         ▁Sherlock     C              both  0.092155 -0.063479
26            ▁Lupin     C              both  0.087722 -0.083827
27          ▁Granger     C              both  0.045556 -0.087492
28            ▁Remus     C              both  0.075232 -0.080787
29               ▁JK     C              both  0.051673 -0.079749
30              ▁Sly     C              both  0.051054 -0.078565
31           ▁Sirius     C              both  0.062626 -0.069944
32            ▁Beaux     B              both  0.035510 -0.066274
33           ▁Holmes     C              both  0.044970 -0.059885
34              ▁Mug     B              both  0.039266 -0.059821
35             ▁wand     C              both  0.033852 -0.059630
36                HP     N              both  0.041565 -0.054034
37          ▁Kipling     C     only original  0.102673 -0.000000
38          ▁Beatles     C     only original  0.100083 -0.000000
39         ▁Steelers     N     only original  0.095178 -0.000000
40           ▁Kinect     N     only original  0.088258  0.000000
41   ▁Arrondissement     N     only original  0.087926 -0.000000
42          ▁Picasso     N     only original  0.087419 -0.000000
43           ▁Nestlé     C     only original  0.085728 -0.000000
44           condido     N     only original  0.083997 -0.000000
45            ▁tesla     N     only original  0.082096  0.000000
46     ▁Chhattisgarh     N     only original  0.081243 -0.000000
47           ▁Alamos     N     only original  0.078998 -0.000000
48            cellor     N     only original  0.078751 -0.000000
49             ▁Lego     C     only original  0.078450 -0.000000
50             ▁Cubs     N     only original  0.075853 -0.000000
51           ▁futsal     N     only original  0.072895  0.000000
52              ▁MBE     N     only original  0.072750 -0.000000
53           ▁Reagan     N     only original  0.070570 -0.000000
54            ▁Trump     C     only original  0.070487 -0.000000
55              ▁HBO     C     only original  0.069739 -0.000000
56           ▁Quaker     N     only original  0.069690 -0.000000
57         ▁Handball     N     only original  0.069544  0.000000
58          ▁Ramadan     N     only original  0.069258 -0.000000
59      ▁Premiership     N     only original  0.069205 -0.000000
60       ▁Bloomsbury     C     only original  0.068574 -0.000000
61             lidae     N     only original  0.068492 -0.000000
62           ▁Merlin     C     only original  0.068439 -0.000000
63             cidae     N     only original  0.068214 -0.000000
64              ▁Wic     C     only original  0.068085 -0.000000
65              ompi     N     only original  0.067262 -0.000000
66           ▁Revere     N     only original  0.066808 -0.000000
67             wurst     N     only original  0.066664 -0.000000
68          ▁Pontiac     N     only original  0.066186  0.000000
69            assins     N     only original  0.065449 -0.000000
70           ▁Lenovo     N     only original  0.065293  0.000000
71      ▁Corinthians     C     only original  0.063877 -0.000000
72          ▁Haryana     N     only original  0.061893 -0.000000
73             ▁Guin     C     only original  0.061880 -0.000000
74        ▁Afrikaans     C     only original  0.061111  0.000000
75             ghold     N     only original  0.061095 -0.000000
76              Azur     N     only original  0.061025  0.000000
77          ▁Warlock     C     only original  0.060417 -0.000000
78            ▁Betis     N     only original  0.060211 -0.000000
79             ridae     N     only original  0.060177 -0.000000
80             ▁RCMP     N     only original  0.060141  0.000000
81          ▁Wizards     C     only original  0.059736 -0.000000
82           ▁Inquis     C     only original  0.059272 -0.000000
83          ▁olympic     N     only original  0.058476  0.000000
84            iennes     N     only original  0.058450 -0.000000
85      ▁PlayStation     C     only original  0.058274 -0.000000
86           ▁Oblast     N     only original  0.058017 -0.000000
87           diocese     N     only original  0.057597  0.000000
88        ▁Cardinals     N     only original  0.057317 -0.000000
89        ▁Guildford     N     only original  0.056549 -0.000000
90       ▁Cinderella     C     only original  0.056229 -0.000000
91         ▁Guinness     C     only original  0.056028 -0.000000
92              ▁BBC     C     only original  0.055906 -0.000000
93            Warner     C     only original  0.054528 -0.000000
94          ▁Vikings     N     only original  0.054396 -0.000000
95          ▁potions     C     only original  0.053661 -0.000000
96               BBC     N     only original  0.053640 -0.000000
97          ▁Saginaw     N     only original  0.053090 -0.000000
98              ▁UCI     N     only original  0.053073  0.000000
99       ▁Scholastic     C     only original  0.052598 -0.000000
100         ▁Ceramby     N     only original  0.052538 -0.000000
101            ▁owls     C     only original  0.052416 -0.000000
102            ebrow     C     only original  0.052384 -0.000000
103          ▁Moines     N     only original  0.051998  0.000000
104           ▁Quill     N     only original  0.051827 -0.000000
105        ▁Scotsman     C     only original  0.051591 -0.000000
106         ▁Beckett     C     only original  0.051429 -0.000000
107            ▁Urdu     C     only original  0.051280  0.000000
108        ▁magnolia     N     only original  0.051216  0.000000
109            arnia     C     only original  0.051072 -0.000000
110         ▁Pullman     C     only original  0.050610 -0.000000
111            Gupta     C     only original  0.050608 -0.000000
112         ▁wizards     C     only original  0.050227 -0.000000
113        ▁werewolf     C     only original  0.050211 -0.000000
114       ▁Panchayat     N     only original  0.050158  0.000000
115       ▁Billboard     C     only original  0.050144 -0.000000
116         ▁Rangers     N     only original  0.049943 -0.000000
117            acles     N     only original  0.049620  0.000000
118        Academics     C     only original  0.049324 -0.000000
119         ▁Audible     C     only original  0.049284 -0.000000
120    ▁Palestinians     N     only original  0.049260  0.000000
121           ▁Argon     N     only original  0.049203 -0.000000
122           ▁elves     C     only original  0.048971 -0.000000
123       ▁Paramount     N     only original  0.048926 -0.000000
124             idae     N     only original  0.047326 -0.000000
125           ▁Lanka     N     only original  0.047163  0.000000
126        ▁coasters     C     only original  0.047081 -0.000000
127     ▁Rockefeller     N     only original  0.047034 -0.000000
128          ▁Andean     N     only original  0.046887 -0.000000
129          ▁Warner     B     only original  0.046869 -0.000000
130          ▁Cochin     C     only original  0.046756  0.000000
131        ▁Cascades     N     only original  0.046587  0.000000
132             Yale     C     only original  0.046346 -0.000000
133         ▁Pirates     N     only original  0.046118 -0.000000
134          ▁Cursed     C     only original  0.046115 -0.000000
135     ▁Philosopher     C     only original  0.046036 -0.000000
136       ▁Hollywood     C     only original  0.045925 -0.000000
137           ▁anime     C     only original  0.045909 -0.000000
138             ▁BPI     N     only original  0.045545  0.000000
139        ▁Olympics     B     only original  0.045443  0.000000
140           ilogue     C     only original  0.045323 -0.000000
141         ▁Bengali     C     only original  0.045260  0.000000
142            ▁Enid     C     only original  0.045234 -0.000000
143           ▁FedEx     C     only original  0.045198  0.000000
144           ▁Moshe     N     only original  0.045099 -0.000000
145        ▁Broadway     C     only original  0.044897 -0.000000
146      ▁Parliament     N     only original  0.044878 -0.000000
147           ▁Hindi     C     only original  0.044452 -0.000000
148             ▁NSF     N     only original  0.044383 -0.000000
149           liseum     C     only original  0.044232  0.000000
150        ▁Buddhist     N     only original  0.044200  0.000000
151        ▁Ghanaian     N     only original  0.044068 -0.000000
152            ▁Quir     C     only original  0.043708 -0.000000
153         ▁Minerva     C     only original  0.043688 -0.000000
154           ▁Hippo     C     only original  0.043592 -0.000000
155        ▁Sorcerer     C     only original  0.043556  0.000000
156           ▁chess     N     only original  0.043481 -0.000000
157           Ursula     C     only original  0.043329 -0.000000
158              ódź     N     only original  0.043314 -0.000000
159            ▁Bond     B     only original  0.043180 -0.000000
160         ▁beetles     N     only original  0.042989 -0.000000
161         ▁Maarten     N     only original  0.042969  0.000000
162          ▁Ankara     N     only original  0.042843 -0.000000
163          ▁Malawi     N     only original  0.042756  0.000000
164        ▁unicorns     C     only original  0.042262  0.000000
165         ometrics     N     only original  0.042218 -0.000000
166      ▁parliament     N     only original  0.042157 -0.000000
167            negan     N     only original  0.041948  0.000000
168          ▁Holden     C     only original  0.041861 -0.000000
169             USAL     N     only original  0.041605 -0.000000
170          ▁locket     C     only original  0.041523 -0.000000
171             ▁PDP     N     only original  0.041471  0.000000
172      ▁archbishop     N     only original  0.041032 -0.000000
173          ▁Amazon     C     only original  0.040744 -0.000000
174           ▁Busch     N     only original  0.040735 -0.000000
175     ▁periodontal     N     only original  0.040529 -0.000000
176      ▁gymnastics     N     only original  0.040327  0.000000
177       ▁Antarctic     N     only original  0.039759 -0.000000
178         ▁Jiangsu     N     only original  0.039700  0.000000
179         ▁witches     C     only original  0.039660 -0.000000
180            ▁Gaia     N     only original  0.039633 -0.000000
181       ▁Hampshire     N     only original  0.039624 -0.000000
182         ▁diocese     N     only original  0.039594  0.000000
183      ▁battalions     N     only original  0.039048  0.000000
184     ▁watercolour     C     only original  0.038780 -0.000000
185   ▁parliamentary     N     only original  0.038762 -0.000000
186      ▁Basketball     N     only original  0.038615  0.000000
187         ▁Santana     N     only original  0.038280 -0.000000
188          ▁beetle     N     only original  0.038266 -0.000000
189           ▁Gupta     C     only original  0.038200 -0.000000
190           stasia     N     only original  0.038131 -0.000000
191            ciech     N     only original  0.038020  0.000000
192          ▁desist     N     only original  0.037857  0.000000
193       ▁Salisbury     N     only original  0.037731 -0.000000
194         ▁Procter     N     only original  0.037524 -0.000000
195     ▁Palestinian     N     only original  0.037122  0.000000
196            griff     C     only original -0.037098 -0.000000
197      ▁volleyball     N     only original  0.037071  0.000000
198             ylus     N     only original  0.037050 -0.000000
199             idiv     N     only original  0.036954 -0.000000
200         ▁Palermo     N     only original  0.036953  0.000000
201          ▁Kerala     N     only original  0.036896 -0.000000
202             ICAO     N     only original  0.036895  0.000000
203         ▁Harvard     N     only original  0.036867 -0.000000
204           ▁Monza     N     only original  0.036842  0.000000
205      ▁footballer     N     only original  0.036545  0.000000
206            oyang     N     only original  0.036531 -0.000000
207           Arabic     N     only original  0.036430 -0.000000
208          ▁Muslim     N     only original  0.036419  0.000000
209         ▁rangers     N     only original  0.036363  0.000000
210             blet     C     only original  0.036337 -0.000000
211          ▁wizard     C     only original  0.035889 -0.000000
212           wizard     C     only original  0.035764 -0.000000
213          ▁dioces     N     only original  0.035692 -0.000000
214             ▁UAE     N     only original  0.035510 -0.000000
215             ▁Eid     N     only original  0.035454  0.000000
216            Dział     N     only original  0.035200 -0.000000
217        ▁Cornwall     N     only original  0.034997 -0.000000
218           ▁Serie     N     only original  0.034793 -0.000000
219         ▁coaster     B     only original  0.034673 -0.000000
220              Lup     C     only original  0.034242 -0.000000
221          ▁sharks     N     only original  0.034161 -0.000000
222      ▁Prefecture     N     only original  0.033802  0.000000
223     ▁imagination     C     only original -0.033791  0.000000
224     ▁Afghanistan     N     only original  0.033331 -0.000000
225           ▁Osaka     C     only original  0.033041 -0.000000
226             ▁the     B     only original -0.033011  0.000000
227          ▁Albums     N     only original  0.032902 -0.000000
228       ▁passports     N     only original  0.032532  0.000000
229       ▁militants     N     only original  0.032382 -0.000000
230            Jiang     N     only original  0.032269 -0.000000
231      ▁bookstores     C     only original  0.032153 -0.000000
232           ▁icons     C     only original -0.031975  0.000000
233       ▁imaginary     C     only original -0.031864  0.000000
234         ▁Commons     N     only original  0.031847 -0.000000
235          ▁Riddle     C     only original  0.031691 -0.000000
236      ▁referendum     N     only original  0.031408  0.000000
237                ʑ     N     only original -0.031380  0.000000
238          ▁Beasts     C     only original  0.031131 -0.000000
239            magic     C  only transformed -0.000000  0.142666
240            Magic     C  only transformed -0.000000  0.137874
241           ▁magic     C  only transformed -0.000000  0.133065
242           ▁Magic     B  only transformed -0.000000  0.120966
243         ▁magical     C  only transformed -0.000000  0.084425
244          magical     C  only transformed -0.000000  0.081716
245             ▁McG     C  only transformed  0.000000 -0.063038
246              idd     C  only transformed  0.000000 -0.061517
247             ▁Hag     C  only transformed  0.000000 -0.061123
248             ▁Ron     C  only transformed  0.000000 -0.060338
249         ▁Magical     C  only transformed  0.000000  0.051687

====================================================================================================
=== original 18 <-> transformed 22   Jaccard = 0.680   |cos(z0, unmap(z~))| = 0.838
====================================================================================================
  original rho-candidate 18: matched transformed feature 22 is NOT in F_C (best-Jaccard transformed partner: 22, J=0.680)
  both: 17   only original: 0   only transformed: 8

label             B   C  N
in
both              1  14  2
only transformed  0   6  2

           token label                in    Y0[18]     Y[22]
0       ▁selling     C              both -0.393752 -0.389474
1          ▁sold     C              both -0.369115 -0.380238
2        selling     C              both -0.364392 -0.358782
3           sold     C              both -0.344935 -0.346239
4          ▁sale     C              both -0.318687 -0.346002
5         ▁sales     B              both -0.294199 -0.314078
6         seller     C              both -0.240440 -0.243785
7        ▁buying     C              both -0.230201 -0.169195
8    ▁purchasing     C              both -0.194963 -0.143747
9        ▁bought     N              both -0.189998 -0.133493
10    ▁marketing     C              both -0.141326 -0.131111
11  ▁bestselling     C              both -0.109541 -0.123352
12      ▁pricing     C              both -0.107779 -0.083684
13       ▁retail     N              both -0.105222 -0.077982
14       ▁market     C              both -0.104323 -0.094801
15       Vendors     C              both -0.102089 -0.091692
16   ▁commercial     C              both -0.089205 -0.084436
17      ▁revenue     C  only transformed -0.000000 -0.084416
18   ▁popularity     C  only transformed -0.000000 -0.080586
19      ▁popular     C  only transformed -0.000000 -0.073361
20          ales     C  only transformed -0.000000 -0.072419
21    ▁promotion     N  only transformed -0.000000 -0.068885
22  ▁promotional     C  only transformed -0.000000 -0.065280
23      ▁product     N  only transformed -0.000000 -0.059665
24          selt     C  only transformed -0.000000 -0.058242

====================================================================================================
=== original 20 <-> transformed 78   Jaccard = 0.604   |cos(z0, unmap(z~))| = 0.899
====================================================================================================
  original rho-candidate 20: matched transformed feature 78 is NOT in F_C (best-Jaccard transformed partner: 78, J=0.604)
  both: 29   only original: 0   only transformed: 19

label             B   C  N
in
both              3  20  6
only transformed  4  13  2

            token label                in    Y0[20]     Y[78]
0           ▁show     N              both -0.286351  0.333311
1            show     C              both -0.262656  0.308430
2        ▁showing     C              both -0.287928  0.298955
3          ▁shown     C              both -0.248326  0.286274
4        ▁display     N              both -0.276309  0.225801
5         ▁showed     C              both -0.239647  0.276103
6       ▁displays     C              both -0.259146  0.209366
7      ▁displayed     C              both -0.252164  0.222406
8       ▁showcase     C              both -0.233098  0.187388
9      ▁depicting     C              both -0.188587  0.143387
10       showcase     C              both -0.183522  0.146631
11       ▁portray     C              both -0.174850  0.129397
12    ▁portraying     C              both -0.172169  0.118401
13      ▁depicted     C              both -0.170611  0.150134
14    ▁exhibition     C              both -0.168924  0.141521
15     ▁depiction     C              both -0.164210  0.131924
16     ▁portrayal     B              both -0.155381  0.118923
17    ▁depictions     C              both -0.142008  0.109029
18    ▁illustrate     C              both -0.140821  0.116866
19        ▁reveal     C              both -0.128152  0.104907
20     ▁presented     B              both -0.118283  0.097364
21     ▁highlight     C              both -0.114324  0.073525
22    ▁indicating     N              both -0.107078  0.054197
23    ▁exposition     C              both -0.103887  0.063447
24      ▁revealed     C              both -0.096804  0.081232
25     ▁indicated     N              both -0.094788  0.057366
26      ▁presents     N              both -0.090854  0.068287
27      ▁featured     B              both -0.088416  0.074069
28     ▁presenter     N              both -0.084927  0.055069
29          ▁seen     C  only transformed -0.000000  0.127224
30          ▁view     C  only transformed -0.000000  0.117740
31       ▁viewing     B  only transformed -0.000000  0.114823
32        ▁viewed     C  only transformed -0.000000  0.106257
33        ▁appear     C  only transformed -0.000000  0.099334
34      ▁appeared     B  only transformed -0.000000  0.091332
35         ▁views     C  only transformed -0.000000  0.089324
36       ▁appears     B  only transformed -0.000000  0.086593
37           ▁see     B  only transformed -0.000000  0.084106
38        ▁seeing     C  only transformed -0.000000  0.082560
39    ▁appearance     C  only transformed -0.000000  0.079978
40          ▁sees     C  only transformed -0.000000  0.075115
41   ▁represented     N  only transformed -0.000000  0.066922
42        ▁scenes     C  only transformed -0.000000  0.064517
43     ▁represent     C  only transformed -0.000000  0.060019
44  ▁representing     N  only transformed -0.000000  0.058093
45       ▁picture     C  only transformed -0.000000  0.057559
46     ▁manifests     C  only transformed -0.000000  0.052590
47       ▁present     C  only transformed -0.000000  0.050728

====================================================================================================
=== original 22 <-> transformed 10   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.217
====================================================================================================
  original rho-candidate 22: matched transformed feature 10 is NOT in F_C (best-Jaccard transformed partner: 86, J=0.022)
  both: 0   only original: 11   only transformed: 32

label              B  C  N
in
only original      1  8  2
only transformed  16  8  8

         token label                in    Y0[22]     Y[10]
0       ▁moral     C     only original  0.497684 -0.000000
1        moral     C     only original  0.446328  0.000000
2     ▁ethical     C     only original  0.391232 -0.000000
3    ▁morality     C     only original  0.366337 -0.000000
4   ▁ethically     C     only original  0.310538 -0.000000
5         ▁Mor     N     only original  0.237193 -0.000000
6      ▁social     C     only original  0.170373 -0.000000
7   ▁emotional     C     only original  0.154071 -0.000000
8      ▁Social     N     only original  0.147113 -0.000000
9   ▁spiritual     C     only original  0.143036 -0.000000
10      ▁legal     B     only original  0.135187  0.000000
11        ▁off     C  only transformed -0.000000  0.397094
12       ▁back     B  only transformed  0.000000  0.343205
13         off     C  only transformed -0.000000  0.327825
14        back     B  only transformed  0.000000  0.292548
15         ▁up     B  only transformed  0.000000  0.285002
16       ▁down     B  only transformed -0.000000  0.243066
17          up     B  only transformed -0.000000  0.227850
18        ▁out     B  only transformed  0.000000  0.212423
19       ▁away     B  only transformed  0.000000  0.194518
20         ▁on     B  only transformed -0.000000  0.192958
21          Up     N  only transformed -0.000000  0.181463
22       ▁onto     N  only transformed  0.000000  0.159718
23          on     C  only transformed -0.000000  0.145434
24          On     B  only transformed -0.000000  0.138921
25         ▁On     N  only transformed -0.000000  0.135866
26       ▁into     B  only transformed -0.000000  0.109095
27       front     C  only transformed  0.000000  0.106787
28    ▁onwards     C  only transformed  0.000000  0.099393
29      ▁front     N  only transformed  0.000000  0.099367
30       ▁over     B  only transformed  0.000000  0.087555
31       ▁upon     C  only transformed -0.000000  0.086700
32     ▁behind     N  only transformed -0.000000  0.077379
33          of     B  only transformed  0.000000  0.075566
34   ▁upstairs     N  only transformed  0.000000  0.073034
35         ▁of     B  only transformed -0.000000  0.071651
36       ▁home     B  only transformed  0.000000  0.062688
37      ▁right     B  only transformed  0.000000  0.060881
38         ▁in     B  only transformed -0.000000  0.054801
39       Forth     C  only transformed -0.000000  0.054247
40        bach     N  only transformed  0.000000  0.054003
41         ons     C  only transformed -0.000000  0.050250
42     ▁across     N  only transformed -0.000000  0.047731

====================================================================================================
=== original 23 <-> transformed 18   Jaccard = 0.031   |cos(z0, unmap(z~))| = 0.160
====================================================================================================
  original rho-candidate 23: matched transformed feature 18 is NOT in F_C (best-Jaccard transformed partner: 18, J=0.031)
  both: 2   only original: 14   only transformed: 49

label              B   C   N
in
both               0   2   0
only original      0  12   2
only transformed  22  17  10

            token label                in    Y0[23]     Y[18]
0         ▁denied     C              both  0.160405 -0.056034
1        ▁refuses     C              both  0.136360 -0.067675
2     ▁acceptance     C     only original  0.411604 -0.000000
3       ▁accepted     N     only original  0.386861 -0.000000
4         ▁accept     C     only original  0.377574 -0.000000
5      ▁rejection     C     only original  0.344167 -0.000000
6       ▁rejected     C     only original  0.326106 -0.000000
7         ▁reject     C     only original  0.320220 -0.000000
8    ▁recognition     C     only original  0.180879 -0.000000
9   ▁acknowledged     C     only original  0.170538 -0.000000
10    ▁recognised     C     only original  0.162129 -0.000000
11      ▁declined     C     only original  0.142256 -0.000000
12       ▁embrace     N     only original  0.128824  0.000000
13     ▁tolerance     C     only original  0.123065 -0.000000
14       ▁decline     C     only original  0.120162 -0.000000
15      ▁conceded     C     only original  0.110432 -0.000000
16            ▁no     B  only transformed  0.000000 -0.373559
17       ▁neither     C  only transformed  0.000000 -0.323730
18           ▁not     B  only transformed  0.000000 -0.315568
19          ▁none     C  only transformed  0.000000 -0.302970
20             no     B  only transformed  0.000000 -0.281812
21            ▁NO     N  only transformed  0.000000 -0.194433
22           ▁Not     N  only transformed  0.000000 -0.190309
23         ▁never     C  only transformed  0.000000 -0.185965
24          ▁only     B  only transformed  0.000000 -0.169328
25           ▁all     B  only transformed -0.000000 -0.153143
26        ▁cannot     C  only transformed  0.000000 -0.152096
27           ▁nor     C  only transformed  0.000000 -0.149762
28            all     C  only transformed -0.000000 -0.135856
29           ▁non     C  only transformed  0.000000 -0.131884
30          ▁both     B  only transformed -0.000000 -0.122774
31        ▁unable     C  only transformed  0.000000 -0.118890
32       ▁without     C  only transformed  0.000000 -0.118536
33           both     N  only transformed -0.000000 -0.114269
34          ▁Only     N  only transformed  0.000000 -0.113005
35            non     C  only transformed  0.000000 -0.108616
36          ▁does     C  only transformed  0.000000 -0.102628
37            All     B  only transformed -0.000000 -0.101565
38         ▁senza     N  only transformed  0.000000 -0.098621
39       ▁lacking     C  only transformed -0.000000 -0.097370
40        ▁either     B  only transformed  0.000000 -0.095083
41           alls     N  only transformed  0.000000 -0.092106
42          ▁less     B  only transformed  0.000000 -0.087257
43          ▁didn     N  only transformed  0.000000 -0.086145
44        ▁absent     C  only transformed  0.000000 -0.084676
45            ▁do     C  only transformed  0.000000 -0.084052
46       ▁Without     N  only transformed  0.000000 -0.078981
47           ▁did     B  only transformed -0.000000 -0.077496
48           ▁few     C  only transformed -0.000000 -0.067977
49        ▁little     B  only transformed -0.000000 -0.066918
50            ▁ni     N  only transformed  0.000000 -0.060993
51         ▁still     B  only transformed  0.000000 -0.059693
52     ▁inability     N  only transformed  0.000000 -0.059608
53              1     B  only transformed -0.000000 -0.057214
54       ▁refrain     C  only transformed  0.000000 -0.056351
55              9     B  only transformed -0.000000 -0.056249
56              3     B  only transformed -0.000000 -0.056198
57         ▁avoid     C  only transformed  0.000000 -0.056110
58              8     B  only transformed -0.000000 -0.055978
59              2     B  only transformed  0.000000 -0.054026
60              4     B  only transformed -0.000000 -0.052428
61              0     B  only transformed -0.000000 -0.052058
62              5     B  only transformed -0.000000 -0.051658
63              7     B  only transformed -0.000000 -0.050965
64              6     B  only transformed -0.000000 -0.048908

====================================================================================================
=== original 24 <-> transformed 83   Jaccard = 0.875   |cos(z0, unmap(z~))| = 0.836
====================================================================================================
  original rho-candidate 24: matched transformed feature 83 is NOT in F_C (best-Jaccard transformed partner: 83, J=0.875)
  both: 21   only original: 1   only transformed: 2

label             B   C  N
in
both              2  13  6
only original     0   1  0
only transformed  0   1  1

         token label                in    Y0[24]     Y[83]
0       ▁death     B              both -0.287417 -0.330328
1      ▁killed     C              both -0.319519 -0.322718
2     ▁killing     C              both -0.311413 -0.290234
3        ▁died     B              both -0.244994 -0.296156
4       ▁kills     C              both -0.295587 -0.295831
5        ▁dies     C              both -0.228770 -0.276081
6        ▁dead     C              both -0.238749 -0.275379
7       ▁Death     C              both -0.244519 -0.271237
8         ▁die     C              both -0.199797 -0.258064
9     ▁killers     N              both -0.247098 -0.172196
10   ▁murdered     C              both -0.237382 -0.212257
11     ▁killer     N              both -0.233723 -0.155836
12     ▁murder     C              both -0.232979 -0.199622
13        ▁Die     N              both -0.162627 -0.183590
14   ▁massacre     N              both -0.143373 -0.077788
15     ▁massac     N              both -0.133390 -0.078713
16      ▁alive     C              both -0.120243 -0.101038
17    ▁posthum     N              both -0.118583 -0.102602
18    ▁destroy     C              both -0.110726 -0.087567
19   ▁destroys     C              both -0.108102 -0.085760
20  ▁graveyard     C              both -0.103932 -0.081120
21     ▁graves     C     only original -0.086626 -0.000000
22     ▁tragic     C  only transformed -0.000000 -0.064196
23    ▁extinct     N  only transformed -0.000000 -0.061675

====================================================================================================
=== original 27 <-> transformed 37   Jaccard = 0.219   |cos(z0, unmap(z~))| = 0.194
====================================================================================================
  original rho-candidate 27: matched transformed feature 37 is NOT in F_C (best-Jaccard transformed partner: 37, J=0.219)
  both: 7   only original: 9   only transformed: 16

label             B  C  N
in
both              2  4  1
only original     1  5  3
only transformed  4  8  4

          token label                in    Y0[27]     Y[37]
0      ▁section     C              both -0.372243 -0.157317
1     ▁sections     C              both -0.363769 -0.151973
2        ▁piece     N              both -0.326203 -0.074405
3       ▁pieces     B              both -0.315849 -0.064384
4      ▁chapter     C              both -0.286890 -0.084230
5      ▁segment     B              both -0.244952 -0.086394
6      ▁Chapter     C              both -0.232267 -0.079127
7      ▁article     B     only original -0.284109 -0.000000
8     ▁articles     N     only original -0.267653 -0.000000
9      ▁letters     C     only original -0.186553 -0.000000
10       ▁pages     C     only original -0.180956 -0.000000
11      ▁letter     C     only original -0.180605  0.000000
12       ▁trust     N     only original  0.144950  0.000000
13       ▁items     C     only original -0.141462 -0.000000
14        trust     C     only original  0.140061  0.000000
15      ▁papers     N     only original -0.116282 -0.000000
16        ▁part     B  only transformed -0.000000 -0.473645
17         part     C  only transformed  0.000000 -0.456520
18        ▁Part     N  only transformed -0.000000 -0.410458
19       ▁parts     C  only transformed -0.000000 -0.391280
20       ▁Parts     C  only transformed -0.000000 -0.333535
21     ▁aspects     C  only transformed -0.000000 -0.102467
22  ▁components     N  only transformed -0.000000 -0.095669
23     ▁partial     C  only transformed  0.000000 -0.084545
24     ▁element     C  only transformed -0.000000 -0.079345
25    ▁elements     C  only transformed -0.000000 -0.074009
26      ▁member     B  only transformed -0.000000 -0.062482
27     ▁members     B  only transformed -0.000000 -0.058404
28        ▁side     B  only transformed -0.000000 -0.056224
29      ▁behalf     C  only transformed  0.000000 -0.049958
30      Members     N  only transformed -0.000000 -0.048310
31         ▁par     N  only transformed -0.000000 -0.046952

====================================================================================================
=== original 28 <-> transformed 28   Jaccard = 0.645   |cos(z0, unmap(z~))| = 0.806
====================================================================================================
  original rho-candidate 28: matched transformed feature 28 is NOT in F_C (best-Jaccard transformed partner: 28, J=0.645)
  both: 20   only original: 0   only transformed: 11

label             B  C  N
in
both              7  9  4
only transformed  5  4  2

        token label                in    Y0[28]     Y[28]
0       ▁four     B              both  0.264764  0.310159
1        ▁six     B              both  0.270460  0.298499
2       ▁five     B              both  0.279455  0.298015
3      ▁seven     B              both  0.277244  0.297833
4      ▁eight     B              both  0.275679  0.287431
5       ▁nine     C              both  0.285791  0.284923
6      ▁three     B              both  0.232904  0.274288
7        four     C              both  0.238201  0.257516
8     ▁eleven     C              both  0.256194  0.235166
9       ▁Five     N              both  0.225295  0.161487
10       Nine     C              both  0.223613  0.153393
11       ▁two     B              both  0.166137  0.217201
12  ▁nineteen     C              both  0.216471  0.183384
13    ▁Eleven     N              both  0.210052  0.121445
14    ▁twenty     C              both  0.195341  0.164637
15      Three     C              both  0.187366  0.157850
16       ▁Ten     N              both  0.165538  0.076919
17     ▁fifty     C              both  0.158213  0.119881
18       ▁Two     N              both  0.132155  0.107193
19       teen     C              both  0.070639  0.034484
20   ▁several     B  only transformed  0.000000  0.098160
21   ▁seventh     C  only transformed  0.000000  0.076255
22       ▁one     B  only transformed  0.000000  0.075423
23     ▁sixth     B  only transformed  0.000000  0.069117
24      ▁trio     N  only transformed  0.000000  0.066086
25     ▁fifth     C  only transformed  0.000000  0.061913
26    ▁dozens     C  only transformed  0.000000  0.058237
27  ▁multiple     N  only transformed  0.000000  0.055065
28    ▁fourth     B  only transformed -0.000000  0.054168
29       ▁few     C  only transformed  0.000000  0.040003
30          0     B  only transformed -0.000000 -0.036159

====================================================================================================
=== original 29 <-> transformed 82   Jaccard = 0.021   |cos(z0, unmap(z~))| = 0.089
====================================================================================================
  original rho-candidate 29: matched transformed feature 82 is NOT in F_C (best-Jaccard transformed partner: 3, J=0.038)
  both: 4   only original: 16   only transformed: 167

label              B   C   N
in
both               2   1   1
only original      1  10   5
only transformed  38  98  31

            token label                in    Y0[29]     Y[82]
0          ▁fight     B              both  0.293454 -0.067215
1          ▁chase     C              both  0.264051 -0.045499
2       ▁struggle     B              both  0.243893 -0.048290
3           ▁hunt     N              both  0.238710 -0.037632
4           ▁race     C     only original  0.343961 -0.000000
5          ▁races     B     only original  0.285167  0.000000
6         ▁battle     C     only original  0.284765 -0.000000
7        ▁contest     C     only original  0.242046 -0.000000
8       ▁competed     N     only original  0.226571  0.000000
9      ▁competing     N     only original  0.214879 -0.000000
10        ▁search     C     only original  0.207244 -0.000000
11         ▁quest     C     only original  0.200927 -0.000000
12       ▁pursuit     N     only original  0.193302 -0.000000
13          ▁duel     C     only original  0.186792 -0.000000
14   ▁competitive     N     only original  0.178982 -0.000000
15     ▁struggles     C     only original  0.155363 -0.000000
16        ▁racial     N     only original  0.153421  0.000000
17      ▁conflict     C     only original  0.142512 -0.000000
18      ▁searched     C     only original  0.136366  0.000000
19        ▁debate     C     only original  0.129178 -0.000000
20          ▁take     B  only transformed  0.000000 -0.132962
21        ▁remain     C  only transformed  0.000000 -0.129652
22          ▁stay     B  only transformed  0.000000 -0.125895
23            ▁go     C  only transformed  0.000000 -0.124506
24          ▁have     B  only transformed  0.000000 -0.124019
25         ▁serve     C  only transformed  0.000000 -0.120760
26       ▁receive     C  only transformed -0.000000 -0.119135
27      ▁continue     C  only transformed  0.000000 -0.117496
28       ▁provide     C  only transformed -0.000000 -0.117239
29        ▁become     B  only transformed  0.000000 -0.115201
30         ▁speak     C  only transformed  0.000000 -0.114517
31         ▁teach     C  only transformed  0.000000 -0.109835
32            ▁be     B  only transformed  0.000000 -0.107919
33         ▁reach     C  only transformed  0.000000 -0.106729
34          ▁rely     C  only transformed  0.000000 -0.105812
35          ▁make     B  only transformed  0.000000 -0.105744
36         ▁learn     C  only transformed  0.000000 -0.104389
37        ▁attend     C  only transformed  0.000000 -0.104042
38            ▁do     C  only transformed  0.000000 -0.103809
39   ▁participate     C  only transformed  0.000000 -0.102906
40        ▁assume     C  only transformed -0.000000 -0.102121
41          ▁know     C  only transformed -0.000000 -0.101048
42          ▁move     B  only transformed  0.000000 -0.100242
43    ▁contribute     N  only transformed  0.000000 -0.098480
44     ▁represent     C  only transformed  0.000000 -0.098308
45        ▁appear     C  only transformed  0.000000 -0.098176
46         ▁offer     N  only transformed  0.000000 -0.096218
47          ▁find     C  only transformed  0.000000 -0.095898
48         ▁occur     N  only transformed -0.000000 -0.095750
49        ▁belong     C  only transformed  0.000000 -0.095714
50          ▁turn     C  only transformed  0.000000 -0.095538
51           ▁use     B  only transformed  0.000000 -0.095450
52          ▁grow     C  only transformed  0.000000 -0.095199
53          ▁hold     B  only transformed  0.000000 -0.095009
54          ▁play     B  only transformed  0.000000 -0.094892
55           ▁run     B  only transformed  0.000000 -0.094287
56        ▁accept     C  only transformed  0.000000 -0.094215
57        ▁follow     C  only transformed  0.000000 -0.094096
58          ▁show     N  only transformed  0.000000 -0.093897
59    ▁understand     C  only transformed -0.000000 -0.093804
60          ▁help     B  only transformed  0.000000 -0.093175
61         ▁carry     N  only transformed  0.000000 -0.092584
62         ▁spend     C  only transformed  0.000000 -0.092429
63       ▁contain     C  only transformed  0.000000 -0.091438
64       ▁believe     C  only transformed  0.000000 -0.091184
65       ▁include     B  only transformed -0.000000 -0.090537
66         ▁avoid     C  only transformed -0.000000 -0.090449
67       ▁deliver     C  only transformed -0.000000 -0.090090
68          ▁call     B  only transformed  0.000000 -0.090038
69        ▁expect     C  only transformed -0.000000 -0.087507
70        ▁return     B  only transformed  0.000000 -0.087504
71         ▁think     C  only transformed  0.000000 -0.087268
72         ▁adopt     C  only transformed  0.000000 -0.086544
73         ▁argue     C  only transformed  0.000000 -0.086356
74         ▁exist     C  only transformed  0.000000 -0.085783
75         ▁visit     C  only transformed  0.000000 -0.085076
76       ▁qualify     C  only transformed  0.000000 -0.083931
77           ▁see     B  only transformed  0.000000 -0.083559
78       ▁succeed     B  only transformed  0.000000 -0.083472
79       ▁promote     B  only transformed  0.000000 -0.083127
80         ▁write     C  only transformed  0.000000 -0.083036
81       ▁improve     B  only transformed  0.000000 -0.082722
82          ▁rise     C  only transformed  0.000000 -0.081915
83          ▁deal     C  only transformed  0.000000 -0.081518
84          ▁pass     C  only transformed  0.000000 -0.080130
85      ▁maintain     B  only transformed  0.000000 -0.080114
86          ▁work     B  only transformed  0.000000 -0.079919
87         ▁start     B  only transformed  0.000000 -0.079750
88         ▁begin     N  only transformed  0.000000 -0.079662
89       ▁protect     C  only transformed  0.000000 -0.078576
90      ▁resemble     C  only transformed  0.000000 -0.078401
91           ▁pay     N  only transformed  0.000000 -0.077894
92           ▁are     B  only transformed  0.000000 -0.077224
93         ▁treat     C  only transformed  0.000000 -0.076670
94          ▁lead     C  only transformed  0.000000 -0.076495
95          ▁save     C  only transformed -0.000000 -0.075978
96      ▁comprise     C  only transformed  0.000000 -0.075036
97          ▁need     C  only transformed  0.000000 -0.074920
98          ▁fall     B  only transformed  0.000000 -0.074452
99         ▁drive     B  only transformed  0.000000 -0.072820
100     ▁conclude     N  only transformed  0.000000 -0.072738
101          have     N  only transformed -0.000000 -0.072117
102   ▁illustrate     C  only transformed -0.000000 -0.072096
103     ▁coincide     C  only transformed  0.000000 -0.071685
104       ▁reveal     C  only transformed  0.000000 -0.071037
105        ▁enter     C  only transformed  0.000000 -0.070116
106         ▁draw     C  only transformed  0.000000 -0.070022
107      ▁explore     N  only transformed  0.000000 -0.069882
108         ▁walk     N  only transformed  0.000000 -0.069792
109         ▁ride     C  only transformed  0.000000 -0.069663
110        ▁build     N  only transformed  0.000000 -0.069659
111      ▁consist     C  only transformed  0.000000 -0.069598
112         ▁live     B  only transformed  0.000000 -0.068753
113       ▁affect     N  only transformed  0.000000 -0.068482
114         ▁mean     C  only transformed -0.000000 -0.068289
115      ▁embrace     N  only transformed  0.000000 -0.068284
116      ▁violate     C  only transformed  0.000000 -0.068219
117       ▁change     C  only transformed  0.000000 -0.067044
118        ▁focus     B  only transformed  0.000000 -0.065325
119       ▁defend     N  only transformed  0.000000 -0.064568
120      ▁confirm     N  only transformed  0.000000 -0.064062
121      ▁collect     N  only transformed  0.000000 -0.062703
122     ▁escalate     C  only transformed  0.000000 -0.061274
123      ▁destroy     C  only transformed  0.000000 -0.060754
124         ▁feed     C  only transformed  0.000000 -0.060183
125          give     C  only transformed -0.000000 -0.059969
126        ▁steal     C  only transformed  0.000000 -0.059867
127      ▁emulate     C  only transformed  0.000000 -0.059568
128      ▁support     N  only transformed  0.000000 -0.059504
129    ▁negotiate     N  only transformed  0.000000 -0.059409
130        ▁cover     C  only transformed  0.000000 -0.059116
131       ▁travel     C  only transformed  0.000000 -0.058875
132          ▁put     C  only transformed  0.000000 -0.058657
133         ▁face     B  only transformed  0.000000 -0.058211
134          ▁let     N  only transformed -0.000000 -0.057941
135        ▁adapt     C  only transformed  0.000000 -0.057762
136       ▁reject     C  only transformed  0.000000 -0.057422
137       ▁depart     N  only transformed  0.000000 -0.056226
138         ▁pick     N  only transformed  0.000000 -0.056111
139    ▁encounter     C  only transformed  0.000000 -0.055078
140         ▁read     C  only transformed  0.000000 -0.054173
141      ▁uncover     C  only transformed -0.000000 -0.053884
142          ▁was     B  only transformed  0.000000  0.053587
143          ▁die     C  only transformed  0.000000 -0.052186
144          ▁own     B  only transformed  0.000000 -0.052159
145       ▁report     N  only transformed  0.000000 -0.051528
146      ▁display     N  only transformed  0.000000 -0.050834
147        ▁shift     C  only transformed  0.000000 -0.050739
148        ▁match     N  only transformed  0.000000 -0.049723
149       ▁launch     C  only transformed  0.000000 -0.048799
150         ▁lift     C  only transformed  0.000000 -0.048379
151   ▁experience     B  only transformed -0.000000 -0.048336
152          ▁hit     C  only transformed  0.000000 -0.048046
153      ▁release     B  only transformed  0.000000 -0.047664
154      ▁portray     C  only transformed  0.000000 -0.046856
155        ▁trust     N  only transformed  0.000000 -0.046517
156       ▁escape     C  only transformed  0.000000 -0.046461
157          show     C  only transformed  0.000000 -0.046349
158    ▁highlight     C  only transformed -0.000000 -0.046122
159       ▁appeal     B  only transformed  0.000000 -0.046103
160         ▁hope     C  only transformed  0.000000 -0.045962
161     ▁showcase     C  only transformed  0.000000 -0.045595
162      ▁contact     C  only transformed  0.000000 -0.045217
163          ▁end     B  only transformed -0.000000 -0.044828
164        ▁laugh     C  only transformed  0.000000 -0.044806
165         ▁form     B  only transformed  0.000000 -0.044246
166      ▁present     C  only transformed  0.000000 -0.042752
167    ▁influence     C  only transformed -0.000000 -0.042548
168       ▁demand     C  only transformed -0.000000 -0.042501
169      ▁control     B  only transformed  0.000000 -0.042422
170      ▁decline     C  only transformed  0.000000 -0.042346
171       ▁confer     C  only transformed  0.000000 -0.041923
172     ▁confront     C  only transformed  0.000000 -0.041519
173       ▁supply     N  only transformed  0.000000 -0.041500
174           ▁Go     C  only transformed -0.000000 -0.041344
175          ▁set     B  only transformed  0.000000 -0.040857
176      ▁refrain     C  only transformed  0.000000 -0.039392
177         ▁love     C  only transformed  0.000000 -0.039306
178       ▁ratify     N  only transformed -0.000000 -0.038587
179       ▁spread     C  only transformed  0.000000 -0.037996
180         ▁suit     C  only transformed  0.000000 -0.037624
181        ▁favor     N  only transformed  0.000000 -0.037504
182       ▁select     N  only transformed  0.000000 -0.037393
183         ▁weep     C  only transformed  0.000000 -0.036592
184          ▁mix     N  only transformed  0.000000 -0.036580
185        ▁blend     C  only transformed  0.000000 -0.036206
186         ▁were     B  only transformed  0.000000 -0.035850

====================================================================================================
=== original 30 <-> transformed 41   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.121
====================================================================================================
  original rho-candidate 30: matched transformed feature 41 is NOT in F_C (best-Jaccard transformed partner: 98, J=0.129)
  both: 0   only original: 10   only transformed: 36

label              B  C   N
in
only original      0  8   2
only transformed  18  5  13

        token label                in    Y0[30]     Y[41]
0      ▁cover     C     only original  0.528835  0.000000
1     ▁covers     C     only original  0.502246  0.000000
2   ▁covering     C     only original  0.476276  0.000000
3     covered     N     only original  0.413862  0.000000
4    ▁spanned     N     only original  0.115633  0.000000
5     ▁hiding     C     only original  0.114974  0.000000
6      ▁coats     C     only original  0.113399 -0.000000
7    ▁uncover     C     only original  0.108566  0.000000
8      ▁hides     C     only original  0.108540  0.000000
9   ▁shelters     C     only original  0.083335  0.000000
10        ▁we     C  only transformed -0.000000  0.383405
11      ▁they     B  only transformed -0.000000  0.319912
12       ▁she     B  only transformed -0.000000  0.270528
13        ▁he     B  only transformed -0.000000  0.267419
14         ▁I     B  only transformed -0.000000  0.261932
15       ▁you     B  only transformed -0.000000  0.257083
16         We     N  only transformed  0.000000  0.230701
17     ▁there     C  only transformed -0.000000  0.216565
18        ▁We     B  only transformed  0.000000  0.203128
19        ▁it     B  only transformed -0.000000  0.199959
20       They     B  only transformed  0.000000  0.192703
21          I     B  only transformed -0.000000  0.182375
22         He     B  only transformed -0.000000  0.171991
23        ▁He     B  only transformed  0.000000  0.150938
24        She     B  only transformed  0.000000  0.148182
25        You     N  only transformed  0.000000  0.147429
26       ▁You     N  only transformed  0.000000  0.139160
27         It     B  only transformed -0.000000  0.131608
28        ▁It     N  only transformed  0.000000  0.130216
29      There     B  only transformed  0.000000  0.129875
30       ▁She     N  only transformed  0.000000  0.116751
31         it     N  only transformed -0.000000  0.094243
32      ▁that     B  only transformed -0.000000  0.063386
33       ▁our     N  only transformed -0.000000  0.061348
34        ▁my     C  only transformed -0.000000  0.050790
35       ▁let     N  only transformed  0.000000  0.049674
36          i     N  only transformed -0.000000  0.046398
37       ▁ich     N  only transformed -0.000000  0.046004
38   ▁himself     C  only transformed -0.000000 -0.044570
39        Let     N  only transformed  0.000000  0.042089
40       rips     N  only transformed  0.000000  0.041447
41      ▁well     N  only transformed -0.000000  0.040969
42        ▁if     B  only transformed  0.000000  0.040741
43   ▁herself     C  only transformed -0.000000 -0.039117
44    ▁people     B  only transformed  0.000000  0.038627
45        ▁II     B  only transformed  0.000000  0.038493

====================================================================================================
=== original 32 <-> transformed 71   Jaccard = 0.045   |cos(z0, unmap(z~))| = 0.047
====================================================================================================
  original rho-candidate 32: matched transformed feature 71 is NOT in F_C (best-Jaccard transformed partner: 3, J=0.070)
  both: 1   only original: 11   only transformed: 10

label             B  C  N
in
both              0  0  1
only original     1  8  2
only transformed  1  9  0

             token label                in    Y0[32]     Y[71]
0         ▁joining     N              both -0.169939  0.066870
1          ▁attend     C     only original -0.470774  0.000000
2        ▁attended     N     only original -0.438578  0.000000
3       ▁attending     C     only original -0.437261  0.000000
4           ▁visit     C     only original -0.253711  0.000000
5         ▁visited     C     only original -0.253608  0.000000
6          ▁visits     C     only original -0.238167  0.000000
7    ▁participated     N     only original -0.216361  0.000000
8     ▁participate     C     only original -0.214995  0.000000
9              att     C     only original -0.200181 -0.000000
10         ▁joined     B     only original -0.162385  0.000000
11      ▁attention     C     only original -0.145117 -0.000000
12          ▁entry     C  only transformed -0.000000  0.468851
13          ▁enter     C  only transformed -0.000000  0.446898
14         ▁enters     C  only transformed -0.000000  0.432338
15       ▁entering     C  only transformed -0.000000  0.428456
16        ▁entries     C  only transformed -0.000000  0.395371
17           ▁into     B  only transformed  0.000000  0.137044
18          ▁foray     C  only transformed -0.000000  0.101315
19            nter     C  only transformed -0.000000  0.094910
20  ▁Entertainment     C  only transformed  0.000000  0.080194
21        ▁infiltr     C  only transformed -0.000000  0.068521

====================================================================================================
=== original 35 <-> transformed 36   Jaccard = 0.818   |cos(z0, unmap(z~))| = 0.896
====================================================================================================
  original rho-candidate 35: matched transformed feature 36 is NOT in F_C (best-Jaccard transformed partner: 36, J=0.818)
  both: 9   only original: 1   only transformed: 1

label             B  C  N
in
both              2  5  2
only original     0  0  1
only transformed  0  1  0

        token label                in    Y0[35]     Y[36]
0       ▁open     C              both -0.490647  0.523188
1        open     C              both -0.461682  0.490701
2       ▁Open     N              both -0.450756  0.432187
3     ▁opened     B              both -0.365279  0.353617
4    ▁opening     B              both -0.337312  0.295162
5     ▁closed     C              both -0.261767  0.263714
6   ▁enclosed     N              both -0.096343  0.068304
7     ▁sealed     C              both -0.090903  0.072377
8         ▁op     C              both -0.076004  0.063239
9       berto     N     only original -0.062322  0.000000
10      ▁free     C  only transformed -0.000000  0.055565

====================================================================================================
=== original 36 <-> transformed 55   Jaccard = 0.231   |cos(z0, unmap(z~))| = 0.659
====================================================================================================
  original rho-candidate 36: matched transformed feature 55 is NOT in F_C (best-Jaccard transformed partner: 55, J=0.231)
  both: 9   only original: 1   only transformed: 29

label             B   C   N
in
both              1   6   2
only original     0   0   1
only transformed  7  12  10

           token label                in    Y0[36]     Y[55]
0        ▁follow     C              both  0.495296 -0.361972
1       ▁follows     C              both  0.483580 -0.360087
2      ▁followed     C              both  0.437212 -0.337015
3     ▁following     B              both  0.401929 -0.376335
4     ▁followers     C              both  0.276128 -0.170646
5        ▁sequel     C              both  0.157816 -0.133600
6         ▁chase     C              both  0.148916 -0.060705
7       ▁trailed     N              both  0.129081 -0.065511
8   ▁accompanied     N              both  0.124409 -0.067670
9       ▁pursuit     N     only original  0.112533 -0.000000
10   ▁afterwards     C  only transformed  0.000000 -0.276985
11        ▁after     B  only transformed  0.000000 -0.226338
12        ▁later     B  only transformed -0.000000 -0.195103
13         After     N  only transformed  0.000000 -0.177899
14         ▁then     B  only transformed  0.000000 -0.165453
15    ▁aftermath     C  only transformed  0.000000 -0.155831
16        ▁Later     C  only transformed -0.000000 -0.150010
17         ▁next     C  only transformed  0.000000 -0.132250
18      ▁shortly     C  only transformed  0.000000 -0.128576
19   ▁succeeding     N  only transformed  0.000000 -0.112669
20   ▁eventually     C  only transformed -0.000000 -0.099881
21       ▁before     B  only transformed  0.000000 -0.099121
22       Shortly     N  only transformed  0.000000 -0.095142
23          Soon     C  only transformed -0.000000 -0.091238
24       ▁future     N  only transformed  0.000000 -0.086884
25        ▁below     N  only transformed  0.000000 -0.085238
26         ▁post     N  only transformed  0.000000 -0.081335
27      ▁further     C  only transformed  0.000000 -0.078754
28        ilogue     C  only transformed  0.000000 -0.071896
29  ▁immediately     N  only transformed  0.000000 -0.069335
30      ▁onwards     C  only transformed  0.000000 -0.069257
31         ▁upon     C  only transformed  0.000000 -0.067520
32         ▁than     B  only transformed  0.000000 -0.062845
33         ▁Post     B  only transformed  0.000000 -0.060830
34         ▁when     B  only transformed -0.000000 -0.057079
35    ▁resulting     N  only transformed  0.000000 -0.054460
36       ▁Future     N  only transformed  0.000000 -0.052680
37       ▁during     N  only transformed  0.000000 -0.051557
38    ▁gradually     C  only transformed  0.000000 -0.050916

====================================================================================================
=== original 39 <-> transformed 32   Jaccard = 0.333   |cos(z0, unmap(z~))| = 0.584
====================================================================================================
  original rho-candidate 39: matched transformed feature 32 is NOT in F_C (best-Jaccard transformed partner: 32, J=0.333)
  both: 12   only original: 3   only transformed: 21

label             B   C  N
in
both              3   8  1
only original     0   3  0
only transformed  2  16  3

               token label                in    Y0[39]     Y[32]
0           ▁version     B              both -0.331920  0.419489
1           ▁edition     B              both -0.279253  0.378600
2           ▁Version     C              both -0.302035  0.354356
3          ▁editions     C              both -0.270587  0.330832
4       ▁translation     C              both -0.293939  0.078385
5      ▁translations     C              both -0.290055  0.092509
6    ▁interpretation     N              both -0.281015  0.108719
7   ▁interpretations     C              both -0.274245  0.103543
8       ▁adaptations     C              both -0.263675  0.082165
9         ▁rendition     C              both -0.231437  0.216890
10           ▁copies     B              both -0.173037  0.165321
11          ▁replica     C              both -0.121861  0.091419
12       ▁translated     C     only original -0.247204  0.000000
13          ▁adapted     C     only original -0.222100  0.000000
14            ▁adapt     C     only original -0.210655  0.000000
15          ▁example     C  only transformed -0.000000  0.240551
16         ▁instance     C  only transformed -0.000000  0.234424
17         ▁examples     C  only transformed -0.000000  0.202732
18        ▁instances     C  only transformed -0.000000  0.179175
19            ▁model     C  only transformed -0.000000  0.133870
20           ▁models     C  only transformed -0.000000  0.125702
21       ▁instalment     C  only transformed -0.000000  0.101945
22       ▁precedents     C  only transformed -0.000000  0.101263
23        ▁precedent     C  only transformed  0.000000  0.100697
24        ▁depiction     C  only transformed -0.000000  0.094763
25       ▁depictions     C  only transformed -0.000000  0.094142
26           ▁sequel     C  only transformed -0.000000  0.077220
27           ▁option     N  only transformed -0.000000  0.076181
28        ▁portrayal     B  only transformed -0.000000  0.075855
29         ▁evidence     C  only transformed -0.000000  0.074343
30        ▁exception     C  only transformed -0.000000  0.073482
31           ▁cousin     B  only transformed -0.000000  0.070359
32            ▁cases     N  only transformed  0.000000  0.068611
33       ▁derivative     C  only transformed -0.000000  0.067928
34             ▁imit     C  only transformed -0.000000  0.065484
35            ▁remix     N  only transformed -0.000000  0.059725

====================================================================================================
=== original 40 <-> transformed 24   Jaccard = 0.069   |cos(z0, unmap(z~))| = 0.015
====================================================================================================
  original rho-candidate 40: matched transformed feature 24 is NOT in F_C (best-Jaccard transformed partner: 24, J=0.069)
  both: 2   only original: 8   only transformed: 19

label             B   C  N
in
both              0   1  1
only original     1   6  1
only transformed  4  10  5

           token label                in    Y0[40]     Y[24]
0      ▁survived     N              both -0.170706 -0.126661
1     ▁surviving     C              both -0.151315 -0.132468
2        ▁escape     C     only original -0.508268 -0.000000
3       ▁escapes     C     only original -0.467132 -0.000000
4       ▁escaped     C     only original -0.453066 -0.000000
5        ▁Escape     C     only original -0.443026 -0.000000
6            ▁Es     B     only original -0.151466 -0.000000
7         ▁avoid     C     only original -0.142213  0.000000
8          ▁slip     N     only original -0.126769  0.000000
9            ▁ev     C     only original -0.103133 -0.000000
10       ▁living     B  only transformed -0.000000 -0.437059
11        ▁lived     C  only transformed -0.000000 -0.372208
12         ▁live     B  only transformed -0.000000 -0.350732
13        ▁lives     C  only transformed -0.000000 -0.337137
14         lived     N  only transformed -0.000000 -0.288635
15         ▁life     B  only transformed -0.000000 -0.270502
16        ▁alive     C  only transformed -0.000000 -0.257573
17          life     C  only transformed -0.000000 -0.237846
18      ▁resided     N  only transformed -0.000000 -0.161194
19      ▁resides     C  only transformed -0.000000 -0.160031
20        ▁exist     C  only transformed -0.000000 -0.127211
21       ▁exists     C  only transformed -0.000000 -0.117289
22       ▁lively     C  only transformed  0.000000 -0.092624
23        ▁dwell     N  only transformed -0.000000 -0.091710
24     ▁Lifetime     N  only transformed -0.000000 -0.074826
25         ▁born     N  only transformed  0.000000 -0.072303
26         ▁real     C  only transformed  0.000000 -0.064554
27          born     B  only transformed  0.000000 -0.062221
28  ▁existential     C  only transformed -0.000000 -0.058238

====================================================================================================
=== original 41 <-> transformed 95   Jaccard = 0.266   |cos(z0, unmap(z~))| = 0.746
====================================================================================================
  original rho-candidate 41: matched transformed feature 95 is NOT in F_C (best-Jaccard transformed partner: 95, J=0.266)
  both: 76   only original: 163   only transformed: 47

label              B   C   N
in
both              46  16  14
only original     92  51  20
only transformed  14  17  16

             token label                in    Y0[41]     Y[95]
0          ▁within     B              both  0.076514 -0.211615
1              ▁in     B              both  0.110086 -0.188432
2          ▁during     N              both  0.075258 -0.179708
3            ▁with     B              both  0.107934 -0.179266
4           ▁among     C              both  0.084625 -0.167966
5             ▁for     B              both  0.103680 -0.164758
6              ▁at     B              both  0.102374 -0.162488
7            ▁from     B              both  0.100387 -0.157393
8       ▁alongside     B              both  0.063298 -0.152344
9         ▁against     B              both  0.086324 -0.149238
10        ▁amongst     N              both  0.075114 -0.147560
11             ▁on     B              both  0.104132 -0.146977
12        ▁between     B              both  0.076680 -0.146894
13     ▁throughout     B              both  0.054197 -0.145637
14          ▁along     B              both  0.083537 -0.142642
15         ▁before     B              both  0.088475 -0.142126
16          ▁after     B              both  0.090908 -0.139307
17        ▁without     C              both  0.086067 -0.139220
18             ▁as     B              both  0.102194 -0.136841
19         ▁inside     C              both  0.066204 -0.135368
20          ▁while     B              both  0.077352 -0.133908
21           ▁upon     C              both  0.065784 -0.132261
22           ▁when     B              both  0.107637 -0.129815
23         ▁across     N              both  0.072904 -0.127545
24        ▁towards     C              both  0.075188 -0.118280
25            ▁his     B              both  0.070814  0.117494
26      ▁according     B              both  0.059087 -0.117295
27         ▁around     B              both  0.084964 -0.116044
28            ▁him     B              both  0.051660  0.113447
29          ▁under     B              both  0.078263 -0.112681
30             ▁to     B              both  0.109201 -0.106846
31           ▁into     B              both  0.088630 -0.106940
32             ▁he     B              both  0.070823  0.102559
33             ▁if     B              both  0.102010 -0.057983
34         ▁beyond     B              both  0.072729 -0.099884
35          ▁there     C              both  0.099002 -0.040219
36          ▁where     B              both  0.096160 -0.049268
37         ▁behind     N              both  0.079482 -0.095583
38        ▁through     B              both  0.081845 -0.094577
39       ▁together     N              both  0.049861 -0.094445
40        ▁outside     B              both  0.061342 -0.094162
41             ▁by     B              both  0.090821 -0.091035
42             ▁of     B              both  0.082307 -0.089887
43          ▁about     B              both  0.086090 -0.053104
44          ▁until     N              both  0.076886 -0.083863
45          ▁since     B              both  0.066564 -0.082370
46           ▁near     B              both  0.044254 -0.082090
47        ▁because     B              both  0.080562 -0.053144
48           ▁like     B              both  0.078081 -0.069298
49           ▁over     B              both  0.077009 -0.072938
50          ▁again     N              both  0.075102 -0.045403
51            ▁too     C              both  0.069685 -0.030443
52          ▁using     C              both  0.068997 -0.056267
53       ▁anything     C              both  0.068451  0.033675
54           ▁once     N              both  0.066338 -0.041839
55        ▁instead     B              both  0.064567 -0.065313
56             ▁my     C              both  0.065081  0.027770
57            ▁off     C              both  0.063522  0.048582
58           ▁onto     N              both  0.063174 -0.051419
59          ▁below     N              both  0.058920 -0.061764
60           ▁back     B              both  0.059601  0.054618
61          ▁above     N              both  0.058734 -0.057301
62     ▁afterwards     C              both  0.033098 -0.057254
63           ▁them     B              both  0.055500  0.031782
64           ▁next     C              both  0.053662 -0.036943
65          ▁based     B              both  0.041513 -0.053640
66            ▁due     B              both  0.051081 -0.034018
67       ▁although     B              both  0.050735 -0.033549
68          ▁alone     N              both  0.039042 -0.050591
69          ▁senza     N              both  0.035247 -0.050197
70           ▁whom     N              both  0.048510  0.037422
71             ▁vs     C              both  0.037438 -0.044569
72             ▁me     C              both  0.043707  0.031202
73       ▁compared     C              both  0.043499 -0.040974
74      ▁including     B              both  0.039238 -0.032791
75            ▁per     B              both  0.034700 -0.037853
76           ▁that     B     only original  0.112833 -0.000000
77             ▁it     B     only original  0.110348 -0.000000
78            ▁the     B     only original  0.102920 -0.000000
79           ▁what     B     only original  0.100078  0.000000
80            ▁you     B     only original  0.098820  0.000000
81           ▁this     B     only original  0.095426  0.000000
82             ▁we     C     only original  0.094630 -0.000000
83           ▁they     B     only original  0.094063 -0.000000
84            ▁who     B     only original  0.089942 -0.000000
85            ▁how     C     only original  0.089552  0.000000
86             ▁so     B     only original  0.089367 -0.000000
87           ▁even     B     only original  0.085325 -0.000000
88              ▁a     B     only original  0.085223 -0.000000
89          ▁which     B     only original  0.083511  0.000000
90            ▁not     B     only original  0.083193 -0.000000
91           ▁some     B     only original  0.082214  0.000000
92      ▁something     C     only original  0.082011  0.000000
93            ▁can     B     only original  0.081383 -0.000000
94            ▁now     B     only original  0.080538 -0.000000
95            ▁and     B     only original  0.079178 -0.000000
96          ▁their     B     only original  0.078945  0.000000
97           ▁then     B     only original  0.078206  0.000000
98            ▁out     B     only original  0.078135 -0.000000
99             ▁is     B     only original  0.077590 -0.000000
100           ▁our     N     only original  0.077436  0.000000
101           ▁but     B     only original  0.077183 -0.000000
102        ▁having     N     only original  0.077142 -0.000000
103           ▁its     B     only original  0.076643  0.000000
104           ▁are     B     only original  0.075660 -0.000000
105          ▁have     B     only original  0.074452 -0.000000
106         ▁being     B     only original  0.074402 -0.000000
107            ▁an     B     only original  0.074240 -0.000000
108         ▁those     C     only original  0.073322  0.000000
109            ▁up     B     only original  0.072542  0.000000
110       ▁another     B     only original  0.071780  0.000000
111            ▁be     B     only original  0.071454  0.000000
112         ▁these     B     only original  0.070461  0.000000
113            ▁or     B     only original  0.070257 -0.000000
114          ▁just     B     only original  0.069988 -0.000000
115           ▁let     N     only original  0.068615  0.000000
116         ▁could     B     only original  0.068063 -0.000000
117           ▁one     B     only original  0.066945 -0.000000
118          ▁will     N     only original  0.066716 -0.000000
119          ▁than     B     only original  0.065702 -0.000000
120        ▁really     C     only original  0.065538  0.000000
121          ▁more     B     only original  0.065525 -0.000000
122        ▁making     C     only original  0.065469 -0.000000
123        ▁should     C     only original  0.065115 -0.000000
124         ▁would     B     only original  0.064780  0.000000
125          ▁away     B     only original  0.064302 -0.000000
126            ▁do     C     only original  0.064032  0.000000
127        ▁seeing     C     only original  0.063947  0.000000
128           both     N     only original -0.063912  0.000000
129           ▁has     B     only original  0.063702 -0.000000
130          ▁down     B     only original  0.063590  0.000000
131        ▁taking     C     only original  0.063506 -0.000000
132            ▁no     B     only original  0.063404 -0.000000
133        ▁giving     N     only original  0.063248 -0.000000
134         ▁doing     B     only original  0.063185  0.000000
135           ▁any     B     only original  0.062963  0.000000
136           ▁was     B     only original  0.062467  0.000000
137        ▁enough     B     only original  0.062459 -0.000000
138           ▁all     B     only original  0.062269  0.000000
139           ▁may     B     only original  0.062197  0.000000
140         ▁still     B     only original  0.059898  0.000000
141         ▁whose     C     only original  0.059876 -0.000000
142          ▁does     C     only original  0.059462 -0.000000
143           ▁did     B     only original  0.059170  0.000000
144          ▁also     B     only original  0.059047 -0.000000
145         ▁might     C     only original  0.057816  0.000000
146          ▁such     B     only original  0.057332 -0.000000
147          ▁were     B     only original  0.056795 -0.000000
148         ▁other     B     only original  0.056436  0.000000
149          ▁make     B     only original  0.056152 -0.000000
150         ▁never     C     only original  0.056034  0.000000
151        ▁rather     C     only original  0.055541 -0.000000
152           ▁see     B     only original  0.055113  0.000000
153           ▁had     B     only original  0.055057  0.000000
154      ▁actually     C     only original  0.054332  0.000000
155          ▁much     C     only original  0.054325  0.000000
156        ▁though     B     only original  0.053898 -0.000000
157           ▁she     B     only original  0.052942 -0.000000
158           ▁her     B     only original  0.052435  0.000000
159           Each     B     only original -0.052355  0.000000
160              ,     B     only original  0.052008 -0.000000
161        ▁saying     C     only original  0.051931  0.000000
162          ▁must     C     only original  0.051695 -0.000000
163          ▁take     B     only original  0.051659  0.000000
164         ▁right     B     only original  0.050618 -0.000000
165        ▁coming     C     only original  0.050320 -0.000000
166          ▁didn     N     only original  0.049642  0.000000
167           ▁won     B     only original  0.049118 -0.000000
168         ▁makes     C     only original  0.048777 -0.000000
169         ▁gives     C     only original  0.048325 -0.000000
170            ▁us     C     only original  0.047962  0.000000
171       ▁however     C     only original  0.047507 -0.000000
172           ▁put     C     only original  0.047211  0.000000
173          ▁made     B     only original  0.047099 -0.000000
174            ▁am     N     only original  0.047015 -0.000000
175            ▁go     C     only original  0.047004 -0.000000
176      ▁allowing     C     only original  0.046998 -0.000000
177             ▁I     B     only original  0.046228  0.000000
178          ▁many     B     only original  0.046078  0.000000
179          ▁only     B     only original  0.045730 -0.000000
180          ▁very     B     only original  0.045663 -0.000000
181          ▁ever     B     only original  0.045218  0.000000
182         ▁given     B     only original  0.044776 -0.000000
183           ▁far     C     only original  0.044579  0.000000
184     ▁therefore     B     only original  0.044227 -0.000000
185        ▁almost     C     only original  0.044204 -0.000000
186        ▁cannot     C     only original  0.044002 -0.000000
187         ▁think     C     only original  0.042680  0.000000
188          ▁goes     B     only original  0.042670 -0.000000
189          ▁gave     B     only original  0.042361  0.000000
190       ▁showing     C     only original  0.041876  0.000000
191       ▁leaving     N     only original  0.041465 -0.000000
192         ▁comes     C     only original  0.041109 -0.000000
193         ▁Later     C     only original -0.041029  0.000000
194          ▁most     B     only original  0.040989  0.000000
195          ▁last     B     only original  0.040741 -0.000000
196        ▁others     B     only original  0.040506  0.000000
197         ▁takes     C     only original  0.040140  0.000000
198          ▁thus     B     only original  0.039955 -0.000000
199           ▁way     B     only original  0.039935  0.000000
200        ▁people     B     only original  0.039908  0.000000
201          ▁less     B     only original  0.039884 -0.000000
202   \n\n\n\n\n\n     N     only original -0.039837 -0.000000
203         ▁stuff     C     only original  0.039742  0.000000
204          ▁know     C     only original  0.039677  0.000000
205       ▁already     C     only original  0.039605 -0.000000
206          ▁seen     C     only original  0.039331 -0.000000
207    ▁Originally     N     only original -0.039298  0.000000
208          ▁took     B     only original  0.038859  0.000000
209     \n\n\n\n\n     N     only original -0.038414 -0.000000
210       ▁wearing     C     only original  0.038361 -0.000000
211          ▁find     C     only original  0.038289 -0.000000
212          ▁went     B     only original  0.038104 -0.000000
213          ▁been     B     only original  0.037685  0.000000
214       ▁finding     C     only original  0.037658  0.000000
215            řez     N     only original  0.037455 -0.000000
216          ▁past     N     only original  0.037441 -0.000000
217        ▁become     B     only original  0.037315 -0.000000
218          ▁good     C     only original  0.037267  0.000000
219         ▁found     B     only original  0.037104 -0.000000
220        ▁called     B     only original  0.036759 -0.000000
221       \n\n\n\n     N     only original -0.036747 -0.000000
222          ▁said     B     only original  0.036110  0.000000
223       ▁talking     C     only original  0.036038  0.000000
224          ▁best     B     only original  0.035951 -0.000000
225          ▁came     N     only original  0.035888  0.000000
226     ▁comparing     C     only original  0.035262 -0.000000
227          ▁well     N     only original  0.035191  0.000000
228    ▁eventually     C     only original  0.034812 -0.000000
229         \n\n\n     N     only original -0.034657 -0.000000
230      ▁creating     B     only original  0.034479  0.000000
231         ▁often     C     only original  0.033629 -0.000000
232        ▁expect     C     only original  0.033375 -0.000000
233      ▁upstairs     N     only original  0.032485 -0.000000
234     ▁providing     N     only original  0.031992 -0.000000
235          ▁used     B     only original  0.031407 -0.000000
236     ▁otherwise     C     only original  0.031304 -0.000000
237         ▁looks     C     only original  0.031023  0.000000
238      ▁suddenly     C     only original  0.030448  0.000000
239         Within     C  only transformed  0.000000 -0.115812
240            ▁He     B  only transformed  0.000000  0.104488
241             He     B  only transformed  0.000000  0.098835
242           ▁His     C  only transformed  0.000000  0.095419
243            His     C  only transformed  0.000000  0.094435
244          along     N  only transformed  0.000000 -0.086650
245           with     N  only transformed  0.000000 -0.084937
246        ▁During     N  only transformed -0.000000 -0.083771
247            off     C  only transformed  0.000000  0.082752
248       ▁Against     C  only transformed  0.000000 -0.076301
249         During     N  only transformed -0.000000 -0.074638
250       ▁himself     C  only transformed  0.000000  0.074139
251           back     B  only transformed  0.000000  0.072093
252       ▁Without     N  only transformed  0.000000 -0.065292
253       ▁shortly     C  only transformed  0.000000 -0.065014
254           With     B  only transformed  0.000000 -0.059664
255             in     B  only transformed  0.000000 -0.056492
256             up     B  only transformed  0.000000  0.053108
257  ▁respectively     B  only transformed -0.000000 -0.050723
258          While     B  only transformed -0.000000 -0.049581
259             Up     N  only transformed  0.000000  0.046525
260    ▁concerning     C  only transformed  0.000000 -0.045992
261            ▁In     B  only transformed  0.000000 -0.043918
262          After     N  only transformed  0.000000 -0.043684
263          under     N  only transformed  0.000000 -0.042237
264      According     C  only transformed -0.000000 -0.040010
265           When     C  only transformed  0.000000 -0.038219
266          which     N  only transformed  0.000000  0.035689
267    ▁altogether     N  only transformed  0.000000 -0.035465
268             as     B  only transformed  0.000000 -0.035202
269            For     B  only transformed  0.000000 -0.034474
270  ▁collectively     C  only transformed  0.000000 -0.033844
271       Together     C  only transformed -0.000000 -0.033440
272           ▁wit     C  only transformed  0.000000 -0.033290
273     ▁meanwhile     C  only transformed  0.000000 -0.032748
274   ▁immediately     N  only transformed  0.000000 -0.032537
275             In     B  only transformed  0.000000 -0.032112
276         zyński     N  only transformed  0.000000  0.031329
277             on     C  only transformed  0.000000 -0.030757
278          nelle     N  only transformed  0.000000 -0.030669
279      ▁directly     N  only transformed  0.000000 -0.030131
280        ▁unable     C  only transformed  0.000000 -0.029022
281         ilogue     C  only transformed -0.000000 -0.028496
282            روج     N  only transformed  0.000000 -0.027791
283             my     N  only transformed  0.000000  0.027767
284           From     B  only transformed  0.000000 -0.026855
285             At     B  only transformed  0.000000 -0.025239

====================================================================================================
=== original 43 <-> transformed 96   Jaccard = 0.016   |cos(z0, unmap(z~))| = 0.138
====================================================================================================
  original rho-candidate 43: matched transformed feature 96 is NOT in F_C (best-Jaccard transformed partner: 88, J=0.039)
  both: 4   only original: 235   only transformed: 19

label             B    C   N
in
both              0    4   0
only original     7  145  83
only transformed  2   16   1

                token label                in    Y0[43]     Y[96]
0              ▁juxta     C              both -0.057516  0.138209
1       ▁similarities     C              both -0.056140  0.099119
2          ▁parallels     C              both -0.064802  0.085447
3        ▁superiority     C              both -0.068448  0.084952
4            ▁tyranny     C     only original -0.110229 -0.000000
5           ▁paranoia     C     only original -0.107079  0.000000
6        ▁sovereignty     N     only original -0.104736 -0.000000
7           ▁allegory     C     only original -0.104315  0.000000
8        ▁resurrected     C     only original -0.104168 -0.000000
9          ▁symbolism     C     only original -0.104163  0.000000
10         ▁innocence     C     only original -0.103771 -0.000000
11     ▁subordination     C     only original -0.098280  0.000000
12       ▁benevolence     C     only original -0.096990  0.000000
13         ▁nostalgic     C     only original -0.094633  0.000000
14            ▁rubble     N     only original -0.093323 -0.000000
15           ▁haunted     C     only original -0.092940  0.000000
16          ▁mythical     C     only original -0.092927 -0.000000
17           ▁sadness     C     only original -0.091470 -0.000000
18       ▁retaliation     N     only original -0.090943 -0.000000
19           ▁bigotry     C     only original -0.090726 -0.000000
20         ▁democracy     C     only original -0.090403  0.000000
21       ▁patriarchal     C     only original -0.089072  0.000000
22         ▁injustice     N     only original -0.088800  0.000000
23         ▁parentage     C     only original -0.088220  0.000000
24           ▁madness     C     only original -0.087757  0.000000
25          ▁namesake     B     only original -0.087260 -0.000000
26         ▁resurrect     C     only original -0.087116 -0.000000
27          ▁prophecy     C     only original -0.086567 -0.000000
28         ▁metaphors     C     only original -0.085811  0.000000
29           ▁slavery     C     only original -0.085568  0.000000
30           ▁secrecy     C     only original -0.085386  0.000000
31         ▁precedent     C     only original -0.084065  0.000000
32          ▁enslaved     C     only original -0.083094 -0.000000
33          ▁abducted     C     only original -0.081818 -0.000000
34        ▁redemption     C     only original -0.081131 -0.000000
35            ▁ratify     N     only original -0.081053  0.000000
36         ▁fictional     C     only original -0.080039 -0.000000
37         ▁fairytale     C     only original -0.077976  0.000000
38         ▁prejudice     C     only original -0.077816  0.000000
39      ▁undocumented     N     only original -0.077560 -0.000000
40          ▁massacre     N     only original -0.077179  0.000000
41      ▁horticulture     N     only original -0.077065  0.000000
42         ▁sociology     C     only original -0.076027  0.000000
43       ▁imagination     C     only original -0.075999  0.000000
44           ▁extinct     N     only original -0.075818 -0.000000
45        ▁precedents     C     only original -0.075713  0.000000
46         ▁overthrow     C     only original -0.075625  0.000000
47           ▁revived     N     only original -0.075311 -0.000000
48        ▁subversive     C     only original -0.075227 -0.000000
49     ▁reconstituted     N     only original -0.074158 -0.000000
50           ▁prequel     C     only original -0.073652  0.000000
51      ▁alphabetical     N     only original -0.073264  0.000000
52          ▁tortured     C     only original -0.073194  0.000000
53      ▁biographical     N     only original -0.072820  0.000000
54            ▁purity     C     only original -0.072693  0.000000
55       ▁hostilities     N     only original -0.072149  0.000000
56        ▁witchcraft     C     only original -0.071733  0.000000
57     ▁individuality     N     only original -0.070891  0.000000
58          ▁literacy     C     only original -0.070836  0.000000
59       ▁adolescence     C     only original -0.069361 -0.000000
60           ▁harmony     N     only original -0.068702  0.000000
61         ▁splashing     C     only original -0.068523 -0.000000
62             ▁muddy     N     only original -0.068010  0.000000
63          ▁dreaming     C     only original -0.067613 -0.000000
64     ▁stereotypical     C     only original -0.067554 -0.000000
65           ▁fiction     C     only original -0.067420 -0.000000
66        ▁portraying     C     only original -0.067264  0.000000
67    ▁stratification     C     only original -0.067208  0.000000
68         ▁depicting     C     only original -0.067206  0.000000
69             ▁windy     C     only original -0.067182  0.000000
70        ▁aggression     N     only original -0.067178 -0.000000
71         ▁relatable     C     only original -0.067155  0.000000
72            ▁flurry     C     only original -0.067087 -0.000000
73         ▁harrowing     C     only original -0.067016 -0.000000
74      ▁condemnation     C     only original -0.066852  0.000000
75            ▁clunky     N     only original -0.066806 -0.000000
76          ▁escalate     C     only original -0.066479 -0.000000
77          ▁playable     C     only original -0.066316 -0.000000
78        ▁corruption     C     only original -0.066229  0.000000
79         ▁sacrifice     C     only original -0.066169  0.000000
80          ▁invoking     C     only original -0.066061  0.000000
81         ▁hierarchy     C     only original -0.066021  0.000000
82          ▁heritage     N     only original -0.065772 -0.000000
83         ▁overgrown     N     only original -0.065590  0.000000
84         ▁imaginary     C     only original -0.065444 -0.000000
85             ▁limbo     C     only original -0.065064 -0.000000
86         ▁petrified     C     only original -0.064877 -0.000000
87              ▁roar     C     only original -0.064750 -0.000000
88              ▁myth     C     only original -0.064622  0.000000
89        ▁diplomatic     N     only original -0.064288 -0.000000
90          sacrifice     C     only original -0.064094 -0.000000
91          ▁funniest     C     only original -0.063809  0.000000
92           ▁imagery     C     only original -0.063735  0.000000
93          ▁equality     C     only original -0.063532  0.000000
94            ▁cocoon     N     only original -0.063022  0.000000
95          ▁detained     N     only original -0.062921 -0.000000
96        ▁historical     B     only original -0.062779  0.000000
97           ▁plucked     N     only original -0.062355 -0.000000
98            fiction     C     only original -0.062184 -0.000000
99           ▁bravely     N     only original -0.062163  0.000000
100        ▁legendary     C     only original -0.062138 -0.000000
101          ▁mastery     C     only original -0.062028  0.000000
102          ▁benthic     N     only original -0.061857  0.000000
103       ▁friendship     C     only original -0.061709  0.000000
104        ▁portrayal     B     only original -0.061703  0.000000
105             ▁weep     C     only original -0.061660 -0.000000
106           ▁heroic     C     only original -0.061550  0.000000
107        ▁nourished     C     only original -0.061421 -0.000000
108            ▁expel     N     only original -0.061060 -0.000000
109         ▁murdered     C     only original -0.061031 -0.000000
110        ▁depiction     C     only original -0.060647 -0.000000
111         ▁morality     C     only original -0.060495  0.000000
112          ▁romance     C     only original -0.060428 -0.000000
113         ▁seminary     N     only original -0.060228 -0.000000
114           ▁indict     N     only original -0.060223  0.000000
115          ▁drunken     C     only original -0.060180  0.000000
116         ▁refugees     N     only original -0.059969 -0.000000
117         ▁paycheck     N     only original -0.059882  0.000000
118          ▁mundane     C     only original -0.059792 -0.000000
119      ▁existential     C     only original -0.059709  0.000000
120          ▁emulate     C     only original -0.059643  0.000000
121         ▁politics     C     only original -0.059588 -0.000000
122       ▁enthusiasm     N     only original -0.059576 -0.000000
123          ▁fantasy     C     only original -0.059559  0.000000
124           ▁subjug     C     only original -0.059251 -0.000000
125        ▁shattered     B     only original -0.059206 -0.000000
126     ▁Epidemiology     N     only original -0.059152 -0.000000
127       ▁inequality     C     only original -0.058803  0.000000
128        ▁abolished     N     only original -0.058584  0.000000
129        ▁emigrated     N     only original -0.058517 -0.000000
130         ▁thriller     C     only original -0.058482 -0.000000
131      ▁billionaire     C     only original -0.058356  0.000000
132  ▁standardization     N     only original -0.058339  0.000000
133          ▁history     B     only original -0.058321  0.000000
134      ▁inspiration     C     only original -0.058020  0.000000
135             ▁saga     C     only original -0.057765 -0.000000
136          ▁wounded     N     only original -0.057392 -0.000000
137           ▁loaned     N     only original -0.057354 -0.000000
138         ▁blessing     N     only original -0.057288 -0.000000
139            ▁tears     C     only original -0.057251 -0.000000
140          ▁resurre     C     only original -0.057220 -0.000000
141       ▁referendum     N     only original -0.057034  0.000000
142     ▁presidential     C     only original -0.057029  0.000000
143        ▁happiness     C     only original -0.057001 -0.000000
144        ▁narrative     C     only original -0.056954 -0.000000
145        ▁aftermath     C     only original -0.056735  0.000000
146        ▁parchment     C     only original -0.056481  0.000000
147        ▁desperate     N     only original -0.056300 -0.000000
148          ▁banning     C     only original -0.055811  0.000000
149          ▁stalked     N     only original -0.055737  0.000000
150     ▁historically     N     only original -0.055562  0.000000
151             ▁fate     C     only original -0.055333  0.000000
152        ▁Forgotten     N     only original -0.055281 -0.000000
153      ▁sociologist     C     only original -0.055120  0.000000
154        ▁impatient     C     only original -0.054886 -0.000000
155      ▁terrestrial     N     only original -0.054877 -0.000000
156          ▁clichés     C     only original -0.054770 -0.000000
157      ▁renovations     C     only original -0.054769  0.000000
158            ▁sandy     N     only original -0.054614  0.000000
159           ▁richer     C     only original -0.054599 -0.000000
160       ▁appointing     C     only original -0.054495  0.000000
161        ▁neglected     N     only original -0.054428  0.000000
162          ▁cholera     N     only original -0.054145 -0.000000
163            ▁vanqu     C     only original -0.054023  0.000000
164         ▁vanished     N     only original -0.054016 -0.000000
165          ▁convict     C     only original -0.053867  0.000000
166       ▁reassuring     C     only original -0.053767 -0.000000
167        ▁graveyard     C     only original -0.053710  0.000000
168       ▁motivating     C     only original -0.053550 -0.000000
169         ▁botanist     N     only original -0.053508 -0.000000
170      Independence     N     only original -0.053366  0.000000
171         ▁flagship     C     only original -0.053322 -0.000000
172         ▁feminist     C     only original -0.053313  0.000000
173         ▁Historic     N     only original -0.053137 -0.000000
174          ▁fearing     C     only original -0.052958 -0.000000
175            ▁veins     N     only original -0.052357  0.000000
176        ▁Submarine     N     only original -0.052297  0.000000
177        ▁sculpture     N     only original -0.052274  0.000000
178       ▁misleading     C     only original -0.052237  0.000000
179        ▁negotiate     N     only original -0.052168  0.000000
180       ▁popularity     C     only original -0.052122  0.000000
181          ▁preface     N     only original -0.052090  0.000000
182         ▁restored     N     only original -0.051953 -0.000000
183          ▁mystery     C     only original -0.051869 -0.000000
184      ▁prestigious     N     only original -0.051562  0.000000
185      ▁cooperation     N     only original -0.051416 -0.000000
186        ▁unleashed     C     only original -0.051389 -0.000000
187            ▁suing     C     only original -0.051383  0.000000
188         ▁Honorary     N     only original -0.051325 -0.000000
189          ▁quoting     C     only original -0.051316  0.000000
190           ▁tenure     N     only original -0.051258 -0.000000
191        ▁yellowish     N     only original -0.051247 -0.000000
192       ▁depictions     C     only original -0.051233 -0.000000
193          ▁weakens     C     only original -0.051045 -0.000000
194        ▁inception     C     only original -0.050716 -0.000000
195           charity     C     only original -0.050601  0.000000
196           ▁tragic     C     only original -0.050416 -0.000000
197         ▁eclectic     N     only original -0.049994  0.000000
198          ▁violate     C     only original -0.049942  0.000000
199        ▁abandoned     B     only original -0.049932  0.000000
200       ▁Liberation     N     only original -0.049886  0.000000
201          ▁bounced     N     only original -0.049809 -0.000000
202           ▁lavish     C     only original -0.049765 -0.000000
203        ▁reprinted     C     only original -0.049687  0.000000
204         ▁midnight     C     only original -0.049546  0.000000
205       ▁rehearsals     N     only original -0.049526 -0.000000
206         ▁youthful     C     only original -0.049496  0.000000
207     ▁negotiations     C     only original -0.049494  0.000000
208      ▁periodontal     N     only original -0.049341 -0.000000
209     ▁productivity     N     only original -0.049305  0.000000
210       ▁unwavering     N     only original -0.049143 -0.000000
211            ▁tired     C     only original -0.049047  0.000000
212      ▁overarching     C     only original -0.048997 -0.000000
213          ▁reality     C     only original -0.048987  0.000000
214         ▁nautical     N     only original -0.048736 -0.000000
215        ▁malicious     C     only original -0.048602  0.000000
216      ▁circulatory     N     only original -0.048489 -0.000000
217       ▁filmmaking     C     only original -0.048395  0.000000
218        visibility     C     only original -0.048313 -0.000000
219         ▁starring     N     only original -0.048178 -0.000000
220     ▁unidentified     N     only original -0.047902 -0.000000
221        ▁suspended     N     only original -0.047632 -0.000000
222         ▁retiring     N     only original -0.047574 -0.000000
223         ▁textured     C     only original -0.047518  0.000000
224         ▁resemble     C     only original -0.047450  0.000000
225           ▁richly     C     only original -0.047197 -0.000000
226       ▁scholastic     N     only original -0.046962 -0.000000
227          ▁infiltr     C     only original -0.046759  0.000000
228          ▁dragged     C     only original -0.046689  0.000000
229        ▁passports     N     only original -0.046235 -0.000000
230       ▁separating     C     only original -0.046119  0.000000
231        ▁ambitious     N     only original -0.045964  0.000000
232         ▁resigned     N     only original -0.045927 -0.000000
233           ▁hiding     C     only original -0.045915 -0.000000
234          ▁grazing     N     only original -0.045693 -0.000000
235           ▁warmed     N     only original -0.044762 -0.000000
236         ▁horrible     C     only original -0.044560 -0.000000
237         ▁boarding     B     only original -0.044351 -0.000000
238            ▁steal     C     only original -0.044179 -0.000000
239         ▁compared     C  only transformed  0.000000  0.385573
240          ▁against     B  only transformed -0.000000  0.351796
241          ▁Against     C  only transformed -0.000000  0.326980
242               ▁vs     C  only transformed  0.000000  0.313885
243        ▁comparing     C  only transformed -0.000000  0.292764
244         Comparing     C  only transformed -0.000000  0.273237
245          ▁opposed     C  only transformed -0.000000  0.249568
246         ▁contrast     C  only transformed -0.000000  0.218691
247           opposed     N  only transformed -0.000000  0.192722
248            compar     C  only transformed -0.000000  0.191072
249          ▁opposes     C  only transformed -0.000000  0.182506
250             ▁than     B  only transformed -0.000000  0.162270
251          ▁likened     C  only transformed -0.000000  0.146042
252            Unlike     C  only transformed -0.000000  0.140980
253          ▁differs     C  only transformed -0.000000  0.102696
254    ▁distinguishes     C  only transformed -0.000000  0.082886
255             ▁anti     C  only transformed  0.000000  0.079042
256          ▁towards     C  only transformed -0.000000  0.071373
257    ▁disadvantages     C  only transformed -0.000000  0.070406

====================================================================================================
=== original 50 <-> transformed 38   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.059
====================================================================================================
  original rho-candidate 50: matched transformed feature 38 is NOT in F_C (best-Jaccard transformed partner: 6, J=0.023)
  both: 0   only original: 10   only transformed: 46

label              B   C  N
in
only original      2   7  1
only transformed  18  21  7

             token label                in    Y0[50]     Y[38]
0          ▁master     C     only original  0.582078 -0.000000
1           master     B     only original  0.556784  0.000000
2         ▁mastery     C     only original  0.297999  0.000000
3            ▁Lord     C     only original  0.267394 -0.000000
4             Lord     C     only original  0.252815 -0.000000
5       ▁principal     C     only original  0.199831  0.000000
6         ▁primary     B     only original  0.167568  0.000000
7            ▁main     C     only original  0.149432  0.000000
8       ▁principle     C     only original  0.136268 -0.000000
9            Chief     N     only original  0.134343  0.000000
10        ▁however     C  only transformed  0.000000 -0.411638
11    ▁nonetheless     C  only transformed  0.000000 -0.322986
12      ▁meanwhile     C  only transformed -0.000000 -0.308201
13      ▁therefore     B  only transformed  0.000000 -0.284668
14         However     B  only transformed  0.000000 -0.280581
15         ▁though     B  only transformed -0.000000 -0.225630
16           ▁thus     B  only transformed  0.000000 -0.203008
17            ▁but     B  only transformed  0.000000 -0.188309
18          ▁still     B  only transformed -0.000000 -0.187168
19             Yet     C  only transformed  0.000000 -0.175506
20           ▁then     B  only transformed  0.000000 -0.170851
21           Still     N  only transformed -0.000000 -0.167402
22           ▁also     B  only transformed -0.000000 -0.164029
23       ▁although     B  only transformed  0.000000 -0.137812
24            ▁now     B  only transformed -0.000000 -0.126278
25         ▁Though     N  only transformed -0.000000 -0.119946
26          Though     C  only transformed -0.000000 -0.118165
27      ▁otherwise     C  only transformed -0.000000 -0.112753
28   ▁respectively     B  only transformed -0.000000 -0.090098
29        ▁instead     B  only transformed  0.000000 -0.081896
30          ▁while     B  only transformed  0.000000 -0.081178
31           ▁fact     C  only transformed  0.000000 -0.080489
32            ▁too     C  only transformed -0.000000 -0.079301
33           ▁even     B  only transformed -0.000000 -0.072345
34       ▁Although     N  only transformed  0.000000 -0.072291
35       Similarly     C  only transformed -0.000000 -0.072246
36        ▁already     C  only transformed  0.000000 -0.072047
37         Despite     C  only transformed  0.000000 -0.071548
38      ▁exception     C  only transformed  0.000000 -0.066569
39             ▁so     B  only transformed  0.000000 -0.065999
40     ▁afterwards     C  only transformed  0.000000 -0.063302
41        ▁remains     N  only transformed  0.000000 -0.063163
42          ▁again     N  only transformed  0.000000 -0.062008
43        ▁further     C  only transformed -0.000000 -0.060970
44         ▁remain     C  only transformed  0.000000 -0.056553
45       ▁actually     C  only transformed  0.000000 -0.056461
46           ▁stil     N  only transformed -0.000000 -0.056006
47     ▁eventually     C  only transformed  0.000000 -0.055879
48           While     B  only transformed  0.000000 -0.054192
49  ▁predominantly     C  only transformed  0.000000  0.052877
50       ▁contrast     C  only transformed -0.000000 -0.052741
51       ▁remained     N  only transformed  0.000000 -0.052668
52          ▁which     B  only transformed  0.000000 -0.050656
53       ▁suddenly     C  only transformed -0.000000 -0.048718
54      ▁primarily     B  only transformed  0.000000  0.048490
55       ▁continue     C  only transformed -0.000000 -0.046982

====================================================================================================
=== original 51 <-> transformed 34   Jaccard = 0.720   |cos(z0, unmap(z~))| = 0.747
====================================================================================================
  original rho-candidate 51: matched transformed feature 34 is NOT in F_C (best-Jaccard transformed partner: 34, J=0.720)
  both: 18   only original: 0   only transformed: 7

label             B   C  N
in
both              2  11  5
only transformed  2   4  1

           token label                in    Y0[51]     Y[34]
0          ▁most     B              both  0.248643  0.409037
1           most     C              both  0.248964  0.399364
2          ▁Most     N              both  0.210645  0.309094
3       ▁longest     C              both  0.291313  0.209248
4       ▁fastest     C              both  0.288118  0.217532
5          ▁best     B              both  0.272784  0.273996
6       ▁largest     N              both  0.266607  0.158761
7        largest     N              both  0.258531  0.152000
8      ▁funniest     C              both  0.258295  0.214831
9       ▁highest     N              both  0.252618  0.170784
10         tiest     C              both  0.232989  0.201890
11          Best     C              both  0.230845  0.199591
12        ariest     C              both  0.228801  0.200240
13         liest     C              both  0.224466  0.203476
14         ▁Best     C              both  0.219141  0.194536
15        ▁least     N              both  0.187554  0.126053
16       ▁latest     C              both  0.138130  0.141955
17  ▁bestselling     C              both  0.092183  0.078688
18          more     C  only transformed  0.000000  0.102937
19         ▁more     B  only transformed  0.000000  0.101699
20         ▁last     B  only transformed  0.000000  0.085129
21         ▁next     C  only transformed  0.000000  0.074613
22       ▁almost     C  only transformed  0.000000  0.073525
23          ▁bes     C  only transformed  0.000000  0.057387
24           ost     N  only transformed  0.000000  0.056817

====================================================================================================
=== original 54 <-> transformed 87   Jaccard = 0.571   |cos(z0, unmap(z~))| = 0.821
====================================================================================================
  original rho-candidate 54: matched transformed feature 87 is NOT in F_C (best-Jaccard transformed partner: 87, J=0.571)
  both: 20   only original: 0   only transformed: 15

label             B   C  N
in
both              5  11  4
only transformed  6   7  2

          token label                in    Y0[54]     Y[87]
0         ▁many     B              both  0.407561  0.377059
1         ▁Many     C              both  0.359801  0.300572
2          Many     C              both  0.354859  0.306621
3      ▁several     B              both  0.266058  0.303951
4     ▁numerous     N              both  0.297464  0.292026
5      ▁various     B              both  0.165782  0.283254
6       Various     C              both  0.160388  0.271818
7       ▁dozens     C              both  0.234325  0.178675
8          ▁few     C              both  0.196768  0.209911
9         ▁some     B              both  0.175603  0.197490
10        ▁most     B              both  0.190740  0.119471
11    ▁multiple     N              both  0.188117  0.162730
12    ▁millions     C              both  0.185399  0.095952
13        ▁Most     N              both  0.176972  0.088436
14         most     C              both  0.163798  0.087974
15         Some     C              both  0.156256  0.163479
16        ▁tons     N              both  0.125547  0.057537
17        ▁much     C              both  0.123024  0.102824
18       ▁often     C              both  0.107740  0.073565
19      ▁almost     C              both  0.101779  0.073097
20   ▁different     B  only transformed  0.000000  0.156406
21      ▁varied     C  only transformed  0.000000  0.139329
22     ▁diverse     B  only transformed  0.000000  0.137522
23     ▁variety     N  only transformed -0.000000  0.109635
24     ▁Variety     C  only transformed -0.000000  0.074494
25      ▁number     B  only transformed  0.000000  0.067199
26     ▁differs     C  only transformed -0.000000  0.065004
27   ▁diversity     C  only transformed -0.000000  0.057843
28  ▁frequently     C  only transformed  0.000000  0.056967
29          ome     B  only transformed  0.000000  0.052692
30    ▁somewhat     C  only transformed  0.000000  0.050604
31   ▁extensive     N  only transformed  0.000000  0.049616
32         ▁two     B  only transformed  0.000000  0.048026
33        ▁very     B  only transformed  0.000000  0.046486
34      ▁flurry     C  only transformed  0.000000  0.043043

====================================================================================================
=== original 57 <-> transformed 88   Jaccard = 0.418   |cos(z0, unmap(z~))| = 0.860
====================================================================================================
  original rho-candidate 57: matched transformed feature 88 is NOT in F_C (best-Jaccard transformed partner: 88, J=0.418)
  both: 23   only original: 0   only transformed: 32

label             B   C  N
in
both              1  21  1
only transformed  3  28  1

           token label                in    Y0[57]     Y[88]
0         ▁magic     C              both -0.343427 -0.362256
1          magic     C              both -0.325816 -0.345920
2          Magic     C              both -0.334533 -0.339506
3         ▁Magic     B              both -0.331220 -0.333451
4       ▁magical     C              both -0.281051 -0.277401
5        magical     C              both -0.264028 -0.256776
6       ▁Magical     C              both -0.252347 -0.229215
7        ▁wizard     C              both -0.210354 -0.180082
8       ▁wizards     C              both -0.197760 -0.172296
9        ▁Wizard     C              both -0.192520 -0.153555
10   ▁witchcraft     C              both -0.173274 -0.154448
11        wizard     C              both -0.169429 -0.143560
12      ▁Wizards     C              both -0.160333 -0.134120
13        ▁witch     C              both -0.158638 -0.126260
14        ▁Witch     C              both -0.158340 -0.121542
15      ▁witches     C              both -0.150458 -0.124085
16     ▁Sorcerer     C              both -0.111635 -0.093913
17           wiz     C              both -0.107107 -0.082847
18           Mag     N              both -0.101356 -0.067279
19         ▁wand     C              both -0.100117 -0.065199
20      ▁fantasy     C              both -0.085129 -0.089991
21    ▁fairytale     C              both -0.083084 -0.085288
22     ▁mythical     C              both -0.076093 -0.078917
23       ffindor     C  only transformed  0.000000  0.080376
24      ▁mystery     C  only transformed -0.000000 -0.072953
25       ▁secret     C  only transformed -0.000000 -0.071763
26    ▁imaginary     C  only transformed -0.000000 -0.062094
27        ▁elves     C  only transformed -0.000000 -0.059688
28      ▁secrets     C  only transformed -0.000000 -0.058491
29        ▁charm     C  only transformed -0.000000 -0.057699
30     ▁unicorns     C  only transformed -0.000000 -0.057612
31      ▁potions     C  only transformed -0.000000 -0.054284
32      ▁Warlock     C  only transformed -0.000000 -0.053843
33        therin     C  only transformed  0.000000  0.053432
34   ▁Cinderella     C  only transformed -0.000000 -0.053310
35  ▁imagination     C  only transformed -0.000000 -0.052904
36        ▁power     B  only transformed -0.000000 -0.049904
37      ▁madness     C  only transformed -0.000000 -0.049114
38       ▁imagin     C  only transformed -0.000000 -0.049056
39       ▁powers     C  only transformed -0.000000 -0.047950
40      ▁monster     C  only transformed -0.000000 -0.046801
41         ▁myth     C  only transformed -0.000000 -0.046752
42       ▁Merlin     C  only transformed -0.000000 -0.046648
43      ▁Special     N  only transformed -0.000000 -0.044814
44      ▁Secrets     C  only transformed -0.000000 -0.044675
45       ▁dreams     B  only transformed -0.000000 -0.044554
46       ▁legend     C  only transformed -0.000000 -0.044178
47      ▁haunted     C  only transformed -0.000000 -0.043907
48         ▁evil     C  only transformed -0.000000 -0.043701
49        ▁curse     C  only transformed -0.000000 -0.042505
50    ▁Fantastic     C  only transformed -0.000000 -0.042187
51      ▁romance     C  only transformed -0.000000 -0.041897
52       vellous     C  only transformed -0.000000 -0.041282
53        ▁legal     B  only transformed -0.000000 -0.039966
54     ▁immortal     C  only transformed -0.000000 -0.039600

====================================================================================================
=== original 58 <-> transformed 58   Jaccard = 0.562   |cos(z0, unmap(z~))| = 0.882
====================================================================================================
  original rho-candidate 58: matched transformed feature 58 is NOT in F_C (best-Jaccard transformed partner: 58, J=0.562)
  both: 9   only original: 1   only transformed: 6

label             B  C  N
in
both              2  4  3
only original     0  1  0
only transformed  1  5  0

        token label                in    Y0[58]     Y[58]
0       ▁just     B              both -0.464218 -0.506407
1       ▁Just     N              both -0.441917 -0.411227
2        Just     C              both -0.428919 -0.418964
3     ▁simply     C              both -0.387632 -0.353214
4     ▁merely     C              both -0.349673 -0.345309
5       ▁only     B              both -0.214815 -0.262360
6       ▁Only     N              both -0.206234 -0.194861
7     ▁simple     C              both -0.161515 -0.100790
8      ▁alone     N              both -0.084553 -0.060516
9        Pure     C     only original -0.103902 -0.000000
10      ▁even     B  only transformed -0.000000 -0.102797
11  ▁actually     C  only transformed -0.000000 -0.085609
12    ▁really     C  only transformed -0.000000 -0.073411
13    ▁almost     C  only transformed -0.000000 -0.063145
14      urian     C  only transformed  0.000000  0.062879
15  ▁strictly     C  only transformed -0.000000 -0.055348

====================================================================================================
=== original 59 <-> transformed 75   Jaccard = 0.182   |cos(z0, unmap(z~))| = 0.672
====================================================================================================
  original rho-candidate 59: matched transformed feature 75 is NOT in F_C (best-Jaccard transformed partner: 75, J=0.182)
  both: 8   only original: 2   only transformed: 34

label             B   C  N
in
both              2   4  2
only original     0   1  1
only transformed  8  20  6

            token label                in    Y0[59]     Y[75]
0           ▁cast     C              both -0.500584  0.417310
1           ▁Cast     N              both -0.475471  0.324691
2            Cast     C              both -0.470135  0.328679
3        ▁casting     C              both -0.418949  0.342008
4          caster     N              both -0.261621  0.153806
5         ▁actors     B              both -0.106805  0.175009
6          ▁actor     B              both -0.088765  0.166493
7          castle     C              both -0.156721  0.093860
8             ast     N     only original -0.087199  0.000000
9          asting     C     only original -0.083066  0.000000
10    ▁production     C  only transformed -0.000000  0.219534
11     Production     C  only transformed -0.000000  0.188248
12   ▁productions     C  only transformed -0.000000  0.180654
13      ▁producer     B  only transformed -0.000000  0.154215
14          ▁film     B  only transformed -0.000000  0.141564
15       ▁filming     C  only transformed -0.000000  0.141448
16    ▁characters     C  only transformed -0.000000  0.132846
17       ▁actress     C  only transformed -0.000000  0.129083
18     ▁character     B  only transformed -0.000000  0.117402
19      ▁produced     B  only transformed -0.000000  0.116867
20         ▁films     B  only transformed -0.000000  0.111096
21         ▁movie     C  only transformed -0.000000  0.108415
22        ▁script     C  only transformed -0.000000  0.105775
23      ▁audition     B  only transformed -0.000000  0.105150
24    ▁filmmaking     C  only transformed -0.000000  0.097850
25       ▁Studios     C  only transformed -0.000000  0.094903
26        ▁acting     C  only transformed -0.000000  0.093124
27      ▁director     B  only transformed -0.000000  0.088677
28    ▁television     C  only transformed -0.000000  0.083336
29     ▁Hollywood     C  only transformed -0.000000  0.083218
30      ▁starring     N  only transformed -0.000000  0.083082
31     ▁streaming     C  only transformed -0.000000  0.082630
32       ▁cinemat     N  only transformed -0.000000  0.079600
33     ▁broadcast     C  only transformed -0.000000  0.076212
34            ▁TV     C  only transformed -0.000000  0.075460
35      ▁shooting     N  only transformed -0.000000  0.071269
36      ▁Broadway     C  only transformed -0.000000  0.067003
37  ▁performances     B  only transformed -0.000000  0.064602
38      ▁premiere     C  only transformed -0.000000  0.063174
39      ▁audience     C  only transformed -0.000000  0.062841
40       ▁villain     C  only transformed -0.000000  0.061434
41    ▁Television     N  only transformed -0.000000  0.059918
42      ▁Director     N  only transformed -0.000000  0.059435
43    ▁rehearsals     N  only transformed -0.000000  0.057349

====================================================================================================
=== original 61 <-> transformed 5   Jaccard = 0.323   |cos(z0, unmap(z~))| = 0.591
====================================================================================================
  original rho-candidate 61: matched transformed feature 5 is NOT in F_C (best-Jaccard transformed partner: 5, J=0.323)
  both: 10   only original: 0   only transformed: 21

label             B   C  N
in
both              5   4  1
only transformed  7  10  4

            token label                in    Y0[61]      Y[5]
0        ▁because     B              both  0.428120  0.312995
1         because     C              both  0.421907  0.298727
2            ▁due     B              both  0.412731  0.396239
3         Because     N              both  0.364959  0.240209
4             Due     C              both  0.358340  0.340615
5          ▁since     B              both  0.253467  0.205952
6         ▁reason     C              both  0.232477  0.106789
7        ▁reasons     B              both  0.189382  0.085080
8           Since     B              both  0.181626  0.141555
9   ▁attributable     C              both  0.140043  0.136900
10         ▁based     B  only transformed  0.000000  0.334378
11          based     C  only transformed  0.000000  0.301667
12       ▁related     B  only transformed -0.000000  0.154179
13        related     N  only transformed -0.000000  0.144789
14     ▁according     B  only transformed  0.000000  0.137177
15    ▁influenced     C  only transformed  0.000000  0.105166
16      According     C  only transformed  0.000000  0.101608
17     influenced     C  only transformed  0.000000  0.101078
18      ▁inspired     C  only transformed  0.000000  0.100656
19    ▁associated     C  only transformed -0.000000  0.096193
20         ▁given     B  only transformed  0.000000  0.088199
21          ▁base     N  only transformed -0.000000  0.084434
22       ▁judging     C  only transformed  0.000000  0.084140
23         themed     C  only transformed -0.000000  0.081623
24     ▁therefore     B  only transformed  0.000000  0.080863
25     ▁resulting     N  only transformed  0.000000  0.075609
26           ▁duo     B  only transformed  0.000000  0.075439
27      ▁instance     C  only transformed -0.000000 -0.072873
28          ▁owes     C  only transformed  0.000000  0.072242
29       ▁located     B  only transformed  0.000000  0.063300
30      ▁relating     N  only transformed -0.000000  0.061247

====================================================================================================
=== original 67 <-> transformed 93   Jaccard = 0.813   |cos(z0, unmap(z~))| = 0.478
====================================================================================================
  original rho-candidate 67: matched transformed feature 93 is NOT in F_C (best-Jaccard transformed partner: 93, J=0.813)
  both: 100   only original: 6   only transformed: 17

label              B   C   N
in
both              11  72  17
only original      0   4   2
only transformed   9   6   2

              token label                in    Y0[67]     Y[93]
0               ▁is     B              both -0.080424  0.180386
1              ▁has     B              both -0.086855  0.143747
2            ▁gives     C              both -0.132776  0.142261
3            ▁comes     C              both -0.123731  0.140514
4           ▁allows     C              both -0.127877  0.139901
5             ▁goes     B              both -0.129078  0.136675
6            ▁takes     C              both -0.127040  0.135944
7             ▁does     C              both -0.089669  0.131553
8         ▁involves     C              both -0.111733  0.131082
9          ▁assumes     C              both -0.120183  0.129062
10         ▁becomes     B              both -0.128383  0.127712
11        ▁contains     B              both -0.109777  0.127641
12           ▁makes     C              both -0.120795  0.126448
13        ▁delivers     C              both -0.126136  0.122052
14         ▁appears     B              both -0.105552  0.125337
15          ▁speaks     C              both -0.123087  0.116909
16         ▁extends     B              both -0.118112  0.122935
17           ▁feels     C              both -0.122069  0.121621
18        ▁includes     C              both -0.097193  0.122034
19           ▁tells     C              both -0.121870  0.121506
20          ▁enters     C              both -0.121427  0.106210
21          ▁learns     C              both -0.121184  0.105156
22       ▁undergoes     C              both -0.120630  0.108146
23          ▁serves     C              both -0.106320  0.120489
24         ▁teaches     C              both -0.116606  0.119890
25         ▁differs     C              both -0.113274  0.118891
26          ▁weighs     N              both -0.117784  0.094400
27          ▁exists     C              both -0.097045  0.117697
28           ▁wants     C              both -0.099761  0.116505
29        ▁suggests     C              both -0.104650  0.115566
30         ▁carries     C              both -0.115386  0.107819
31           ▁meets     C              both -0.113985  0.101984
32            ▁sees     C              both -0.113892  0.108609
33    ▁incorporates     N              both -0.113120  0.102671
34         ▁manages     C              both -0.113024  0.096486
35   ▁distinguishes     C              both -0.112905  0.103391
36           ▁looks     C              both -0.094369  0.112646
37        ▁consumes     N              both -0.111167  0.083564
38        ▁consists     N              both -0.097374  0.110932
39       ▁resembles     C              both -0.110728  0.108832
40         ▁engages     C              both -0.110682  0.092957
41           ▁lends     C              both -0.109198  0.100969
42        ▁destroys     C              both -0.108855  0.085888
43         ▁follows     C              both -0.102382  0.108753
44         ▁focuses     C              both -0.108661  0.100251
45       ▁describes     C              both -0.107107  0.108483
46           ▁fills     N              both -0.108156  0.066156
47           ▁emits     N              both -0.107962  0.075878
48           ▁holds     C              both -0.107950  0.097026
49          ▁offers     C              both -0.105023  0.107421
50         ▁opposes     C              both -0.106950  0.095785
51        ▁explains     C              both -0.106343  0.103068
52         ▁reaches     C              both -0.105924  0.096020
53           ▁plays     N              both -0.105153  0.082398
54       ▁publishes     N              both -0.104477  0.081096
55         ▁refuses     C              both -0.103078  0.096788
56            ▁owes     C              both -0.101855  0.098397
57           ▁rises     C              both -0.100956  0.068584
58           ▁reads     C              both -0.098958  0.070110
59         ▁intends     C              both -0.085378  0.098552
60          ▁stands     N              both -0.098441  0.084519
61       ▁discovers     C              both -0.097685  0.089665
62         ▁resides     C              both -0.096215  0.095686
63           allows     C              both -0.096004  0.084489
64          ▁argues     C              both -0.094516  0.095903
65         ▁weakens     C              both -0.095423  0.076427
66      ▁progresses     C              both -0.093342  0.070115
67         ▁remains     N              both -0.092584  0.084549
68           ▁leads     B              both -0.085748  0.091484
69         ▁divides     C              both -0.091254  0.065113
70        ▁presents     N              both -0.090369  0.085012
71           ▁turns     B              both -0.089909  0.068804
72           ▁loves     C              both -0.085876  0.086218
73       ▁increases     C              both -0.084667  0.058876
74           ▁needs     N              both -0.071549  0.080845
75           ▁kills     C              both -0.080640  0.048533
76           ▁Wants     C              both -0.078003  0.062751
77       ▁manifests     C              both -0.077820  0.063093
78           ▁hides     C              both -0.077555  0.065371
79        ▁respects     C              both -0.076125  0.054085
80            ▁lies     N              both -0.071785  0.075917
81          ▁covers     C              both -0.075556  0.068537
82          ▁breaks     N              both -0.073905  0.039344
83           ▁works     B              both -0.073712  0.072112
84          ▁leaves     C              both -0.073354  0.069701
85      ▁transforms     C              both -0.071944  0.040930
86            poses     C              both -0.070349  0.052083
87          ▁shares     N              both -0.069963  0.050110
88       ▁complains     N              both -0.069704  0.050473
89           ▁likes     C              both -0.063167  0.067249
90         ▁defeats     C              both -0.064950  0.037376
91            ▁dies     C              both -0.064659  0.044861
92         ▁escapes     C              both -0.063441  0.042505
93            means     C              both -0.063032  0.060149
94            ▁sets     B              both -0.061281  0.040184
95          ▁tastes     C              both -0.061253  0.055105
96           ▁faces     C              both -0.057859  0.052425
97            ishes     C              both -0.055605  0.045037
98        ▁outlines     N              both -0.054572  0.040825
99        ▁displays     C              both -0.054041  0.038880
100          ▁feeds     N     only original -0.071616  0.000000
101           plays     C     only original -0.067526  0.000000
102         renders     C     only original -0.056201  0.000000
103          ▁rides     C     only original -0.054424  0.000000
104          ▁gains     C     only original -0.054074  0.000000
105          ▁forms     N     only original -0.053363  0.000000
106           ▁will     N  only transformed -0.000000  0.097671
107            ▁can     B  only transformed -0.000000  0.092629
108         ▁cannot     C  only transformed -0.000000  0.075609
109            ▁may     B  only transformed -0.000000  0.069208
110            ▁was     B  only transformed -0.000000  0.067791
111           ▁must     C  only transformed -0.000000  0.061004
112          ▁might     C  only transformed -0.000000  0.060116
113          ▁lives     C  only transformed -0.000000  0.058947
114         ▁should     C  only transformed -0.000000  0.057840
115          ▁would     B  only transformed -0.000000  0.057155
116          ▁could     B  only transformed -0.000000  0.054094
117            ▁are     B  only transformed -0.000000  0.049411
118              is     B  only transformed -0.000000  0.048306
119           ▁were     B  only transformed  0.000000 -0.044001
120         ▁claims     B  only transformed -0.000000  0.038029
121          ▁flies     N  only transformed -0.000000  0.036142
122       ▁features     C  only transformed -0.000000  0.035967

====================================================================================================
=== original 70 <-> transformed 98   Jaccard = 0.600   |cos(z0, unmap(z~))| = 0.926
====================================================================================================
  original rho-candidate 70: matched transformed feature 98 is NOT in F_C (best-Jaccard transformed partner: 98, J=0.600)
  both: 15   only original: 0   only transformed: 10

label             B  C  N
in
both              4  7  4
only transformed  2  6  2

            token label                in    Y0[70]     Y[98]
0        ▁include     B              both  0.379105  0.394219
1       ▁includes     C              both  0.363315  0.382493
2      ▁including     B              both  0.292745  0.325816
3       ▁included     B              both  0.301433  0.307790
4       including     C              both  0.274060  0.296110
5      ▁inclusion     C              both  0.279302  0.256809
6        ▁consist     C              both  0.249762  0.191517
7       ▁consists     N              both  0.248682  0.196048
8     ▁consisting     N              both  0.223121  0.165137
9       ▁comprise     C              both  0.210554  0.165446
10      ▁contains     B              both  0.205503  0.208238
11  ▁incorporates     N              both  0.204043  0.138105
12       ▁contain     C              both  0.201098  0.200070
13      ▁involves     C              both  0.164176  0.147860
14  ▁incorporated     N              both  0.158122  0.077320
15       ▁feature     B  only transformed  0.000000  0.136683
16      ▁features     C  only transformed  0.000000  0.133033
17      ▁featured     B  only transformed  0.000000  0.125910
18        ▁covers     C  only transformed  0.000000  0.087861
19      ▁covering     C  only transformed  0.000000  0.073375
20         ▁cover     C  only transformed -0.000000  0.069939
21          ▁feat     C  only transformed  0.000000  0.061322
22       ▁spanned     N  only transformed  0.000000  0.060568
23  ▁particularly     C  only transformed  0.000000  0.056337
24      ▁enclosed     N  only transformed  0.000000  0.053626

====================================================================================================
=== original 71 <-> transformed 7   Jaccard = 0.647   |cos(z0, unmap(z~))| = 0.843
====================================================================================================
  original rho-candidate 71: matched transformed feature 7 is NOT in F_C (best-Jaccard transformed partner: 7, J=0.647)
  both: 11   only original: 0   only transformed: 6

label             B  C  N
in
both              3  6  2
only transformed  3  2  1

          token label                in    Y0[71]      Y[7]
0      ▁himself     C              both  0.493410 -0.499840
1   ▁themselves     C              both  0.486555 -0.471962
2      ▁herself     C              both  0.476203 -0.481276
3       ▁myself     N              both  0.418053 -0.336751
4          ▁him     B              both  0.157435 -0.196810
5          ▁own     B              both  0.142324 -0.168776
6         ▁them     B              both  0.145149 -0.143546
7         ▁Them     C              both  0.143275 -0.102909
8           ▁me     C              both  0.101584 -0.130831
9         ▁self     C              both  0.110469 -0.117463
10       ▁alone     N              both  0.095467 -0.075833
11         ▁his     B  only transformed  0.000000 -0.117285
12          ▁us     C  only transformed  0.000000 -0.104147
13       ▁their     B  only transformed  0.000000 -0.093469
14         ▁her     B  only transformed  0.000000 -0.081100
15          ▁we     C  only transformed -0.000000  0.061133
16           me     N  only transformed  0.000000 -0.060419

====================================================================================================
=== original 73 <-> transformed 3   Jaccard = 0.405   |cos(z0, unmap(z~))| = 0.644
====================================================================================================
  original rho-candidate 73: matched transformed feature 3 is NOT in F_C (best-Jaccard transformed partner: 3, J=0.405)
  both: 17   only original: 8   only transformed: 17

label             B   C  N
in
both              2  12  3
only original     0   5  3
only transformed  2  14  1

             token label                in    Y0[73]      Y[3]
0            ▁find     C              both  0.213079 -0.370913
1     ▁discovering     C              both  0.347465 -0.238906
2         ▁finding     C              both  0.231554 -0.344714
3       ▁Discovery     N              both  0.335314 -0.154849
4     ▁discoveries     N              both  0.331942 -0.185670
5        Discovery     C              both  0.328854 -0.156039
6            ▁Find     C              both  0.200378 -0.321909
7       ▁discovers     C              both  0.309611 -0.230240
8           ▁found     B              both  0.167847 -0.295969
9         ▁uncover     C              both  0.180459 -0.113273
10        ▁explore     N              both  0.169048 -0.073644
11          ▁learn     C              both  0.125745 -0.148117
12         ▁learns     C              both  0.132329 -0.144642
13      ▁encounter     C              both  0.133874 -0.114777
14     ▁experience     B              both  0.128417 -0.054823
15     ▁encounters     C              both  0.125771 -0.103209
16         ▁search     C              both  0.093763 -0.106653
17    ▁exploration     C     only original  0.188834 -0.000000
18     ▁Experience     N     only original  0.135889 -0.000000
19      ▁Adventure     C     only original  0.121868 -0.000000
20      ▁adventure     C     only original  0.121595 -0.000000
21  ▁investigation     N     only original  0.118253 -0.000000
22     ▁adventures     C     only original  0.115197 -0.000000
23    ▁Experiences     C     only original  0.113875 -0.000000
24    ▁experiments     N     only original  0.088477 -0.000000
25            ▁see     B  only transformed  0.000000 -0.234569
26           ▁sees     C  only transformed  0.000000 -0.217399
27         ▁seeing     C  only transformed  0.000000 -0.202656
28           ▁seen     C  only transformed  0.000000 -0.167021
29           ▁view     C  only transformed  0.000000 -0.139347
30          ▁views     C  only transformed  0.000000 -0.096039
31        ▁viewing     B  only transformed  0.000000 -0.091387
32         ▁viewed     C  only transformed -0.000000 -0.089004
33          ▁visit     C  only transformed  0.000000 -0.084745
34       ▁searched     C  only transformed  0.000000 -0.082034
35           ▁know     C  only transformed  0.000000 -0.073993
36         ▁figure     N  only transformed  0.000000 -0.069543
37           ▁knew     C  only transformed  0.000000 -0.069418
38     ▁understand     C  only transformed  0.000000 -0.066845
39         ▁visits     C  only transformed  0.000000 -0.063286
40        ▁visited     C  only transformed  0.000000 -0.057382
41         ▁notice     C  only transformed  0.000000 -0.056506

====================================================================================================
=== original 76 <-> transformed 8   Jaccard = 0.091   |cos(z0, unmap(z~))| = 0.118
====================================================================================================
  original rho-candidate 76: matched transformed feature 8 is NOT in F_C (best-Jaccard transformed partner: 19, J=0.123)
  both: 3   only original: 17   only transformed: 13

label             B   C  N
in
both              2   1  0
only original     4  10  3
only transformed  2  10  1

        token label                in    Y0[76]      Y[8]
0       ▁move     B              both  0.288430  0.110677
1     ▁moving     C              both  0.244207  0.105264
2      ▁moved     B              both  0.243762  0.091487
3     ▁demand     C     only original  0.321418 -0.000000
4      ▁needs     N     only original  0.301929  0.000000
5       ▁need     C     only original  0.300002 -0.000000
6   ▁demanded     C     only original  0.257426 -0.000000
7    ▁request     C     only original  0.247355  0.000000
8     ▁needed     B     only original  0.242521 -0.000000
9      ▁wants     C     only original  0.236628  0.000000
10     ▁Wants     C     only original  0.216626  0.000000
11    ▁desire     C     only original  0.199509 -0.000000
12  ▁Movement     N     only original  0.188082  0.000000
13     ▁shift     C     only original  0.186810  0.000000
14   ▁shifted     B     only original  0.160181  0.000000
15     ▁asked     B     only original  0.157939  0.000000
16    ▁wished     N     only original  0.140282 -0.000000
17      ▁plea     C     only original  0.127989 -0.000000
18      ▁call     B     only original  0.121898  0.000000
19   ▁clamour     C     only original  0.111770 -0.000000
20        ▁go     C  only transformed  0.000000  0.359800
21      ▁goes     B  only transformed  0.000000  0.342285
22      going     C  only transformed  0.000000  0.317377
23     coming     C  only transformed  0.000000  0.315020
24    ▁coming     C  only transformed  0.000000  0.310713
25        ▁Go     C  only transformed  0.000000  0.297268
26      ▁went     B  only transformed  0.000000  0.297232
27       gone     C  only transformed  0.000000  0.276412
28     ▁comes     C  only transformed -0.000000  0.228471
29      ▁came     N  only transformed  0.000000  0.222232
30      ▁Came     C  only transformed  0.000000  0.189960
31        gow     C  only transformed  0.000000  0.154730
32        got     C  only transformed  0.000000  0.102208

====================================================================================================
=== original 78 <-> transformed 9   Jaccard = 0.174   |cos(z0, unmap(z~))| = 0.386
====================================================================================================
  original rho-candidate 78: matched transformed feature 9 is NOT in F_C (best-Jaccard transformed partner: 9, J=0.174)
  both: 16   only original: 18   only transformed: 58

label              B   C  N
in
both               2  11  3
only original      1  13  4
only transformed  14  35  9

             token label                in    Y0[78]      Y[9]
0       ▁criticism     C              both  0.320648 -0.078438
1      ▁criticisms     C              both  0.294429 -0.075635
2      ▁criticized     N              both  0.273635 -0.111578
3         ▁critics     C              both  0.256779 -0.061670
4      ▁criticised     C              both  0.254317 -0.112155
5          ▁critic     B              both  0.251645 -0.070926
6           ▁argue     C              both  0.192366 -0.143784
7        ▁argument     C              both  0.189060 -0.112473
8         ▁arguing     C              both  0.178875 -0.121780
9          ▁argues     C              both  0.171772 -0.156227
10        ▁debated     C              both  0.161441 -0.062371
11    ▁accusations     C              both  0.158155 -0.064030
12      ▁complains     N              both  0.146242 -0.084846
13        ▁accused     N              both  0.142705 -0.096748
14        ▁praised     C              both  0.124849 -0.098440
15       ▁comments     B              both  0.104699 -0.106618
16    ▁controversy     C     only original  0.196149 -0.000000
17         ▁debate     C     only original  0.190224 -0.000000
18  ▁controversies     C     only original  0.182174 -0.000000
19       ▁critical     N     only original  0.168569 -0.000000
20       ▁concerns     C     only original  0.137960 -0.000000
21   ▁condemnation     C     only original  0.133862 -0.000000
22    ▁discussions     C     only original  0.116010 -0.000000
23         ▁praise     C     only original  0.114130 -0.000000
24       ▁question     N     only original  0.113087 -0.000000
25         ▁issues     C     only original  0.108038 -0.000000
26          ▁issue     C     only original  0.099882  0.000000
27        question     C     only original  0.096537 -0.000000
28        ▁opinion     C     only original  0.095160 -0.000000
29       ▁problems     B     only original  0.093384 -0.000000
30        ▁reviews     N     only original  0.086882 -0.000000
31       ▁lawsuits     N     only original  0.084522 -0.000000
32        ▁regrets     C     only original  0.080444 -0.000000
33        ▁opposes     C     only original  0.075237 -0.000000
34         ▁stated     C  only transformed  0.000000 -0.261792
35           ▁said     B  only transformed  0.000000 -0.254304
36       ▁reported     C  only transformed -0.000000 -0.208879
37        ▁claimed     C  only transformed  0.000000 -0.189289
38        ▁stating     B  only transformed  0.000000 -0.181636
39         ▁saying     C  only transformed  0.000000 -0.177286
40          ▁noted     B  only transformed  0.000000 -0.176994
41     ▁reportedly     C  only transformed  0.000000 -0.172380
42      ▁described     B  only transformed  0.000000 -0.150794
43      ▁statement     C  only transformed  0.000000 -0.148372
44         ▁claims     B  only transformed  0.000000 -0.146440
45        ▁reports     C  only transformed -0.000000 -0.144980
46      ▁allegedly     B  only transformed  0.000000 -0.141987
47     ▁statements     C  only transformed  0.000000 -0.140744
48      ▁suggested     C  only transformed  0.000000 -0.139768
49      ▁purported     C  only transformed  0.000000 -0.130701
50       ▁declared     B  only transformed  0.000000 -0.128960
51      ▁according     B  only transformed -0.000000 -0.126297
52      ▁indicated     N  only transformed -0.000000 -0.126265
53      ▁announced     B  only transformed  0.000000 -0.125956
54       According     C  only transformed -0.000000 -0.124459
55         ▁report     N  only transformed -0.000000 -0.120965
56         ▁listed     N  only transformed  0.000000 -0.112477
57     ▁speculated     C  only transformed  0.000000 -0.108389
58         ▁noting     C  only transformed  0.000000 -0.107585
59      ▁reporting     C  only transformed -0.000000 -0.105793
60        ▁pointed     C  only transformed  0.000000 -0.104053
61   ▁acknowledged     C  only transformed  0.000000 -0.099831
62      ▁specified     C  only transformed -0.000000 -0.099448
63          ▁state     B  only transformed  0.000000 -0.097553
64       ▁explains     C  only transformed  0.000000 -0.097386
65         ▁States     B  only transformed  0.000000 -0.097225
66       ▁suggests     C  only transformed  0.000000 -0.094709
67      ▁describes     C  only transformed  0.000000 -0.094336
68      ▁estimated     C  only transformed -0.000000 -0.087064
69      ▁confirmed     C  only transformed -0.000000 -0.084814
70       ▁revealed     C  only transformed -0.000000 -0.084176
71          ▁wrote     B  only transformed  0.000000 -0.083389
72           ▁note     C  only transformed -0.000000 -0.080221
73          ▁tells     C  only transformed  0.000000 -0.078451
74          ▁asked     B  only transformed  0.000000 -0.076947
75          ported     C  only transformed -0.000000 -0.072679
76          remark     C  only transformed  0.000000 -0.069832
77       ▁supposed     N  only transformed  0.000000 -0.069686
78     ▁identified     N  only transformed  0.000000 -0.067036
79          ▁State     N  only transformed  0.000000 -0.065671
80       ▁demanded     C  only transformed  0.000000 -0.065503
81        ▁quoting     C  only transformed  0.000000 -0.065033
82     ▁underlined     C  only transformed  0.000000 -0.064591
83        ▁likened     C  only transformed  0.000000 -0.064365
84       ▁attested     N  only transformed  0.000000 -0.063446
85     ▁ostensibly     C  only transformed  0.000000 -0.061017
86     ▁announcing     N  only transformed  0.000000 -0.060997
87   ▁announcement     C  only transformed  0.000000 -0.060070
88          ▁added     B  only transformed -0.000000 -0.058844
89     ▁indicating     N  only transformed  0.000000 -0.057344
90       ▁conceded     C  only transformed  0.000000 -0.054085
91         ▁urging     C  only transformed  0.000000 -0.052402

====================================================================================================
=== original 80 <-> transformed 12   Jaccard = 0.059   |cos(z0, unmap(z~))| = 0.055
====================================================================================================
  original rho-candidate 80: matched transformed feature 12 is NOT in F_C (best-Jaccard transformed partner: 87, J=0.243)
  both: 2   only original: 9   only transformed: 23

label             B   C  N
in
both              1   1  0
only original     2   5  2
only transformed  7  12  4

            token label                in    Y0[80]     Y[12]
0      ▁different     B              both -0.251804 -0.081685
1        ▁differs     C              both -0.161618 -0.112304
2        ▁variety     N     only original -0.413442 -0.000000
3         ▁varied     C     only original -0.381665 -0.000000
4        ▁Variety     C     only original -0.378210 -0.000000
5        ▁diverse     B     only original -0.354587 -0.000000
6      ▁diversity     C     only original -0.339941 -0.000000
7         Various     C     only original -0.283706 -0.000000
8        ▁various     B     only original -0.272901 -0.000000
9          ▁range     C     only original -0.187309  0.000000
10      ▁eclectic     N     only original -0.139602  0.000000
11       ▁similar     B  only transformed -0.000000 -0.436077
12          ▁same     B  only transformed -0.000000 -0.427518
13     ▁identical     B  only transformed -0.000000 -0.324413
14      Similarly     C  only transformed  0.000000 -0.318765
15          ▁like     B  only transformed  0.000000 -0.258056
16           Like     B  only transformed  0.000000 -0.230896
17  ▁similarities     C  only transformed -0.000000 -0.228579
18      ▁resemble     C  only transformed -0.000000 -0.222114
19     ▁resembles     C  only transformed -0.000000 -0.220770
20     ▁parallels     C  only transformed  0.000000 -0.156113
21         Unlike     C  only transformed -0.000000 -0.136871
22         ▁likes     C  only transformed -0.000000 -0.116453
23       ▁likened     C  only transformed  0.000000 -0.111482
24      ▁parallel     N  only transformed  0.000000 -0.093447
25       ▁emulate     C  only transformed -0.000000 -0.091004
26      ▁coincide     C  only transformed  0.000000 -0.089280
27       ▁related     B  only transformed -0.000000 -0.085899
28            lik     N  only transformed  0.000000 -0.072026
29        related     N  only transformed  0.000000 -0.071885
30           ames     C  only transformed -0.000000 -0.071704
31          oides     N  only transformed  0.000000 -0.069569
32          ▁imit     C  only transformed -0.000000 -0.068088
33       ▁typical     B  only transformed -0.000000 -0.065321

====================================================================================================
=== original 81 <-> transformed 51   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.119
====================================================================================================
  original rho-candidate 81: matched transformed feature 51 is NOT in F_C (best-Jaccard transformed partner: 9, J=0.050)
  both: 0   only original: 10   only transformed: 24

label              B  C  N
in
only original      2  6  2
only transformed  11  7  6

           token label                in    Y0[81]     Y[51]
0          ▁note     C     only original -0.465857 -0.000000
1        ▁noting     C     only original -0.405981 -0.000000
2         ▁noted     B     only original -0.388233 -0.000000
3        ▁notice     C     only original -0.342357  0.000000
4     ▁observing     C     only original -0.286682  0.000000
5   ▁observation     N     only original -0.278108  0.000000
6       ▁notable     B     only original -0.264565 -0.000000
7        Notable     N     only original -0.213551 -0.000000
8         remark     C     only original -0.204723 -0.000000
9      ▁Observer     C     only original -0.182162 -0.000000
10           ▁it     B  only transformed  0.000000  0.447463
11          ▁its     B  only transformed -0.000000  0.387225
12           ▁It     N  only transformed  0.000000  0.340716
13           Its     N  only transformed -0.000000  0.335760
14            It     B  only transformed  0.000000  0.320081
15          ▁his     B  only transformed  0.000000  0.252548
16            it     N  only transformed -0.000000  0.248653
17          ▁His     C  only transformed  0.000000  0.212955
18           His     C  only transformed  0.000000  0.208108
19          ▁him     B  only transformed  0.000000  0.122300
20       ffindor     C  only transformed -0.000000 -0.116207
21        ▁their     B  only transformed  0.000000  0.113558
22      ▁himself     C  only transformed -0.000000  0.103466
23           ▁He     B  only transformed  0.000000  0.101141
24           ▁he     B  only transformed  0.000000  0.078025
25            He     B  only transformed  0.000000  0.072385
26        therin     C  only transformed  0.000000 -0.071078
27          itch     C  only transformed -0.000000  0.070699
28             a     B  only transformed -0.000000 -0.064967
29            yt     C  only transformed -0.000000  0.061698
30           ▁is     B  only transformed  0.000000  0.060514
31            ło     N  only transformed  0.000000  0.059042
32           روج     N  only transformed -0.000000 -0.052633
33          itis     N  only transformed -0.000000  0.051748

====================================================================================================
=== original 82 <-> transformed 68   Jaccard = 0.271   |cos(z0, unmap(z~))| = 0.875
====================================================================================================
  original rho-candidate 82: matched transformed feature 68 is NOT in F_C (best-Jaccard transformed partner: 68, J=0.271)
  both: 13   only original: 0   only transformed: 35

label             B   C  N
in
both              4   9  0
only transformed  6  25  4

           token label                in    Y0[82]     Y[68]
0          ▁book     B              both  0.414657  0.384861
1          ▁Book     B              both  0.394202  0.343191
2           book     C              both  0.390948  0.352257
3         ▁books     C              both  0.375756  0.342694
4         ▁Books     C              both  0.358456  0.310898
5        ▁novels     C              both  0.208884  0.192710
6         ▁novel     B              both  0.208224  0.181610
7    ▁bookstores     C              both  0.196650  0.183062
8         ▁Novel     C              both  0.193383  0.150441
9      ▁textbook     C              both  0.178942  0.147161
10       ▁ebooks     C              both  0.170132  0.151060
11     ▁novelist     C              both  0.115226  0.105223
12   ▁literature     B              both  0.113315  0.102436
13      ▁chapter     C  only transformed  0.000000  0.114184
14         ▁read     C  only transformed  0.000000  0.109120
15      ▁reading     B  only transformed  0.000000  0.107854
16      ▁Chapter     C  only transformed  0.000000  0.105982
17          Libr     C  only transformed  0.000000  0.097384
18       ▁author     C  only transformed  0.000000  0.097214
19        ▁reads     C  only transformed  0.000000  0.097155
20     ▁literary     C  only transformed  0.000000  0.092506
21  ▁bestselling     C  only transformed  0.000000  0.089660
22      ▁authors     C  only transformed  0.000000  0.088079
23        ▁movie     C  only transformed  0.000000  0.086216
24      ▁fiction     C  only transformed  0.000000  0.086103
25      ▁library     N  only transformed  0.000000  0.083821
26       fiction     C  only transformed  0.000000  0.083256
27         ▁Read     C  only transformed  0.000000  0.082595
28        ▁album     N  only transformed  0.000000  0.077534
29      ▁Library     B  only transformed  0.000000  0.070846
30          ▁boo     C  only transformed  0.000000  0.068488
31         ▁film     B  only transformed  0.000000  0.068263
32       ▁albums     N  only transformed  0.000000  0.067620
33      ▁Audible     C  only transformed  0.000000  0.066831
34        ▁films     B  only transformed  0.000000  0.066048
35   ▁manuscript     C  only transformed  0.000000  0.059745
36        ▁pages     C  only transformed  0.000000  0.058374
37        ilogue     C  only transformed  0.000000  0.053544
38    ▁fictional     C  only transformed  0.000000  0.053297
39   ▁publishers     C  only transformed  0.000000  0.052666
40        ▁story     B  only transformed  0.000000  0.052246
41       ▁volume     C  only transformed  0.000000  0.050614
42      ▁stories     B  only transformed  0.000000  0.048730
43     ▁literacy     C  only transformed  0.000000  0.048608
44    ▁publisher     C  only transformed  0.000000  0.046758
45       ▁Albums     N  only transformed  0.000000  0.045395
46         ▁text     C  only transformed  0.000000  0.044526
47        ▁diary     C  only transformed  0.000000  0.044214

====================================================================================================
=== original 83 <-> transformed 2   Jaccard = 0.414   |cos(z0, unmap(z~))| = 0.847
====================================================================================================
  original rho-candidate 83: matched transformed feature 2 is NOT in F_C (best-Jaccard transformed partner: 2, J=0.414)
  both: 12   only original: 0   only transformed: 17

label             B  C  N
in
both              6  4  2
only transformed  4  7  6

         token label                in    Y0[83]      Y[2]
0      ▁fourth     B              both -0.419543 -0.396090
1       ▁fifth     C              both -0.411520 -0.376494
2       ▁third     B              both -0.396814 -0.389247
3       ▁sixth     B              both -0.394881 -0.352944
4     ▁seventh     C              both -0.379344 -0.322096
5      ▁second     B              both -0.278462 -0.316294
6      ▁Second     N              both -0.225938 -0.202575
7       ▁first     B              both -0.101163 -0.208775
8        Forth     C              both -0.135931 -0.086478
9           rd     C              both -0.133599 -0.108091
10          th     B              both -0.113915 -0.083298
11          nd     N              both -0.095997 -0.070686
12       ▁last     B  only transformed -0.000000 -0.125910
13       First     C  only transformed -0.000000 -0.122509
14       ▁next     C  only transformed -0.000000 -0.106067
15  ▁secondary     N  only transformed -0.000000 -0.092632
16      ▁final     B  only transformed -0.000000 -0.086766
17     ▁middle     B  only transformed -0.000000 -0.079441
18     seconds     N  only transformed -0.000000 -0.074537
19   ▁nineteen     C  only transformed  0.000000  0.070555
20        Nine     C  only transformed  0.000000  0.066893
21       ▁Last     N  only transformed -0.000000 -0.066296
22     ▁Eleven     N  only transformed  0.000000  0.064190
23     ▁eleven     C  only transformed  0.000000  0.061452
24        ▁Ten     N  only transformed  0.000000  0.054648
25  ▁inaugural     C  only transformed -0.000000 -0.054146
26         ▁IV     N  only transformed -0.000000 -0.052546
27     ▁latest     C  only transformed -0.000000 -0.052433
28           1     B  only transformed  0.000000  0.050132

====================================================================================================
=== original 84 <-> transformed 64   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.001
====================================================================================================
  original rho-candidate 84: matched transformed feature 64 is NOT in F_C (best-Jaccard transformed partner: 9, J=0.133)
  both: 0   only original: 11   only transformed: 20

label              B  C  N
in
only original      2  7  2
only transformed  16  3  1

          token label                in    Y0[84]     Y[64]
0      ▁reports     C     only original  0.430410 -0.000000
1       ▁report     N     only original  0.415051 -0.000000
2     ▁reported     C     only original  0.412218 -0.000000
3    ▁reporting     C     only original  0.411761  0.000000
4   ▁reportedly     C     only original  0.273711 -0.000000
5     ▁reporter     N     only original  0.221284 -0.000000
6    ▁allegedly     B     only original  0.207984 -0.000000
7    ▁purported     C     only original  0.191208 -0.000000
8       ▁claims     B     only original  0.185411  0.000000
9        ported     C     only original  0.182107  0.000000
10     ▁claimed     C     only original  0.178235 -0.000000
11        ▁this     B  only transformed  0.000000  0.522901
12       ▁these     B  only transformed  0.000000  0.521822
13        These     B  only transformed -0.000000  0.363586
14         This     B  only transformed -0.000000  0.311361
15       ▁those     C  only transformed -0.000000  0.216278
16         ▁the     B  only transformed  0.000000  0.213225
17          the     B  only transformed -0.000000  0.144402
18          The     B  only transformed  0.000000  0.142921
19         ▁The     B  only transformed  0.000000  0.133663
20        ▁that     B  only transformed -0.000000  0.132750
21        ▁thus     B  only transformed -0.000000  0.106037
22       ▁there     C  only transformed -0.000000  0.104016
23        ▁them     B  only transformed  0.000000  0.078985
24   ▁therefore     B  only transformed -0.000000  0.072496
25         ▁our     N  only transformed -0.000000  0.072404
26        There     B  only transformed  0.000000  0.066513
27        ▁then     B  only transformed -0.000000  0.059454
28        ▁each     B  only transformed -0.000000  0.059295
29         ▁now     B  only transformed  0.000000  0.058553
30       ariest     C  only transformed  0.000000 -0.049246

====================================================================================================
=== original 85 <-> transformed 52   Jaccard = 0.357   |cos(z0, unmap(z~))| = 0.554
====================================================================================================
  original rho-candidate 85: matched transformed feature 52 is NOT in F_C (best-Jaccard transformed partner: 52, J=0.357)
  both: 10   only original: 3   only transformed: 15

label             B  C  N
in
both              5  4  1
only original     2  1  0
only transformed  7  6  2

            token label                in    Y0[85]     Y[52]
0           ▁both     B              both  0.440261 -0.088743
1            both     N              both  0.438130 -0.089804
2          ▁every     C              both  0.242571 -0.404202
3           ▁each     B              both  0.336111 -0.390935
4            ▁all     B              both  0.137115 -0.376380
5           every     C              both  0.235261 -0.373788
6             all     C              both  0.126011 -0.329548
7            Each     B              both  0.256702 -0.316803
8            ▁any     B              both  0.114962 -0.148636
9           ▁none     C              both  0.138012 -0.080433
10       ▁neither     C     only original  0.358304  0.000000
11        ▁either     B     only original  0.304949 -0.000000
12  ▁respectively     B     only original  0.181216 -0.000000
13            All     B  only transformed  0.000000 -0.253356
14           alls     N  only transformed  0.000000 -0.142094
15          ▁ever     B  only transformed  0.000000 -0.112054
16    ▁throughout     B  only transformed  0.000000 -0.078810
17           ▁eve     C  only transformed  0.000000 -0.075303
18         ▁whole     B  only transformed  0.000000 -0.073957
19    ▁altogether     N  only transformed  0.000000 -0.071021
20          ▁even     B  only transformed  0.000000 -0.068428
21    ▁individual     B  only transformed  0.000000 -0.067832
22      ▁anything     C  only transformed  0.000000 -0.063388
23  ▁collectively     C  only transformed  0.000000 -0.063127
24        ▁almost     C  only transformed  0.000000 -0.056814
25       ▁overall     B  only transformed  0.000000 -0.056047
26            ▁ev     C  only transformed  0.000000 -0.055299
27           cled     C  only transformed -0.000000  0.053837

====================================================================================================
=== original 86 <-> transformed 39   Jaccard = 0.909   |cos(z0, unmap(z~))| = 0.957
====================================================================================================
  original rho-candidate 86: matched transformed feature 39 is NOT in F_C (best-Jaccard transformed partner: 39, J=0.909)
  both: 10   only original: 0   only transformed: 1

label             B  C  N
in
both              4  4  2
only transformed  0  1  0

        token label                in    Y0[86]     Y[39]
0       ▁hold     B              both -0.455804 -0.471077
1    ▁holding     B              both -0.431783 -0.430168
2      ▁holds     C              both -0.402672 -0.405985
3       ▁held     B              both -0.370075 -0.396392
4     ▁holder     C              both -0.305460 -0.334500
5     ▁Holden     C              both -0.242353 -0.230895
6       ▁host     B              both -0.214846 -0.185204
7    ▁hosting     N              both -0.212543 -0.156996
8      ▁hosts     C              both -0.201925 -0.181971
9       ghold     N              both -0.150197 -0.097284
10  ▁retained     C  only transformed -0.000000 -0.066056

====================================================================================================
=== original 87 <-> transformed 43   Jaccard = 0.037   |cos(z0, unmap(z~))| = 0.150
====================================================================================================
  original rho-candidate 87: matched transformed feature 43 is NOT in F_C (best-Jaccard transformed partner: 43, J=0.037)
  both: 1   only original: 9   only transformed: 17

label             B  C  N
in
both              1  0  0
only original     2  3  4
only transformed  3  8  6

        token label                in    Y0[87]     Y[43]
0    ▁leading     B              both  0.419474 -0.085731
1       ▁lead     C     only original  0.548276 -0.000000
2      ▁leads     B     only original  0.485332 -0.000000
3        ▁led     B     only original  0.428631 -0.000000
4    ▁leaders     C     only original  0.228764 -0.000000
5    ▁conduit     N     only original  0.116788  0.000000
6    ▁trailed     N     only original  0.109852 -0.000000
7      ▁guide     C     only original  0.103322 -0.000000
8   ▁resulted     N     only original  0.092391 -0.000000
9   ▁prompted     N     only original  0.083137 -0.000000
10       ▁top     B  only transformed  0.000000 -0.499136
11       ▁Top     N  only transformed  0.000000 -0.478165
12        Top     C  only transformed  0.000000 -0.471515
13       tops     C  only transformed  0.000000 -0.347356
14    ▁topped     C  only transformed  0.000000 -0.274409
15     bottom     N  only transformed -0.000000 -0.185551
16   ▁highest     N  only transformed -0.000000 -0.100234
17      ▁Best     C  only transformed -0.000000 -0.087762
18       Best     C  only transformed -0.000000 -0.085941
19    ▁ranked     C  only transformed  0.000000 -0.085660
20      ▁high     C  only transformed  0.000000 -0.076022
21      ▁High     B  only transformed -0.000000 -0.069566
22      ▁best     B  only transformed  0.000000 -0.067578
23       high     N  only transformed -0.000000 -0.067088
24     ▁Upper     N  only transformed -0.000000 -0.059079
25     ▁front     N  only transformed  0.000000 -0.058920
26      front     C  only transformed  0.000000 -0.055122

====================================================================================================
=== original 89 <-> transformed 70   Jaccard = 0.000   |cos(z0, unmap(z~))| = 0.010
====================================================================================================
  original rho-candidate 89: matched transformed feature 70 is NOT in F_C (best-Jaccard transformed partner: 17, J=0.164)
  both: 0   only original: 11   only transformed: 38

label              B   C  N
in
only original      2   7  2
only transformed  21  10  7

           token label                in    Y0[89]     Y[70]
0          ▁news     C     only original -0.370735 -0.000000
1          ▁News     N     only original -0.367655  0.000000
2           News     C     only original -0.363674  0.000000
3         ▁press     B     only original -0.360881  0.000000
4         ▁Press     C     only original -0.341636  0.000000
5         ▁media     C     only original -0.297627 -0.000000
6          media     C     only original -0.265421 -0.000000
7    ▁newspapers     C     only original -0.250665  0.000000
8     ▁newspaper     B     only original -0.246102 -0.000000
9   ▁journalists     C     only original -0.213689 -0.000000
10     ▁reporter     N     only original -0.141720  0.000000
11          ▁and     B  only transformed -0.000000  0.556082
12           ▁or     B  only transformed -0.000000  0.395893
13            ▁&     B  only transformed  0.000000  0.340680
14           and     B  only transformed -0.000000  0.329145
15          ▁but     B  only transformed  0.000000  0.206577
16            or     N  only transformed -0.000000  0.197658
17           ▁et     C  only transformed -0.000000  0.174255
18          ▁nor     C  only transformed -0.000000  0.162736
19             /     B  only transformed -0.000000  0.143265
20           ▁vs     C  only transformed  0.000000  0.138611
21            ▁/     N  only transformed -0.000000  0.121258
22           ▁to     B  only transformed  0.000000  0.092176
23           ▁of     B  only transformed  0.000000  0.087564
24         ▁then     B  only transformed -0.000000  0.085321
25         ▁than     B  only transformed -0.000000  0.084291
26           ▁as     B  only transformed -0.000000  0.083982
27    ▁including     B  only transformed  0.000000  0.078725
28            Or     N  only transformed -0.000000  0.077732
29            -,     N  only transformed -0.000000  0.073673
30     ▁followed     C  only transformed -0.000000  0.072864
31         aland     N  only transformed  0.000000  0.071163
32         ▁with     B  only transformed  0.000000  0.068548
33     including     C  only transformed  0.000000  0.066852
34           ors     B  only transformed  0.000000  0.061065
35            of     B  only transformed  0.000000  0.060397
36             ⁄     C  only transformed -0.000000  0.060259
37        Within     C  only transformed  0.000000 -0.056337
38       ▁within     B  only transformed  0.000000 -0.053644
39        ▁which     B  only transformed  0.000000  0.053091
40          ▁for     B  only transformed  0.000000  0.052719
41            as     B  only transformed -0.000000  0.051954
42            ▁e     N  only transformed -0.000000  0.050890
43             +     C  only transformed  0.000000  0.050854
44        ▁along     B  only transformed -0.000000  0.050363
45       ▁inside     C  only transformed -0.000000 -0.048565
46            to     B  only transformed -0.000000  0.046561
47          with     N  only transformed  0.000000  0.046197
48            —"     C  only transformed -0.000000 -0.045502

====================================================================================================
=== original 91 <-> transformed 1   Jaccard = 0.018   |cos(z0, unmap(z~))| = 0.002
====================================================================================================
  original rho-candidate 91: matched transformed feature 1 is NOT in F_C (best-Jaccard transformed partner: 77, J=0.118)
  both: 1   only original: 13   only transformed: 42

label              B   C   N
in
both               1   0   0
only original      5   5   3
only transformed  12  18  12

            token label                in    Y0[91]      Y[1]
0          ▁debut     B              both  0.154836  0.064546
1      ▁announced     B     only original  0.367417  0.000000
2   ▁announcement     C     only original  0.361392  0.000000
3     ▁announcing     N     only original  0.351209  0.000000
4        ▁release     B     only original  0.331063 -0.000000
5       ▁released     B     only original  0.322755  0.000000
6         ▁launch     C     only original  0.318382 -0.000000
7       ▁launched     B     only original  0.294145 -0.000000
8       ▁revealed     C     only original  0.196896 -0.000000
9         ▁reveal     C     only original  0.192904 -0.000000
10     ▁unleashed     C     only original  0.169761 -0.000000
11           ▁Ann     N     only original  0.169143  0.000000
12    ▁introduced     N     only original  0.167321  0.000000
13      ▁declared     B     only original  0.154962 -0.000000
14      ▁previous     C  only transformed -0.000000  0.309591
15    ▁previously     N  only transformed  0.000000  0.292581
16    ▁originally     C  only transformed -0.000000  0.288137
17      ▁original     B  only transformed -0.000000  0.266153
18       ▁earlier     C  only transformed  0.000000  0.262128
19          ▁last     B  only transformed  0.000000  0.242249
20     ▁initially     C  only transformed  0.000000  0.241721
21         ▁first     B  only transformed  0.000000  0.228958
22       ▁initial     C  only transformed  0.000000  0.228552
23    ▁Originally     N  only transformed -0.000000  0.206790
24      ▁formerly     N  only transformed  0.000000  0.178553
25        ▁former     N  only transformed  0.000000  0.158485
26           ▁old     C  only transformed -0.000000  0.145986
27          First     C  only transformed  0.000000  0.137057
28          ▁Last     N  only transformed  0.000000  0.136697
29          ▁past     N  only transformed -0.000000  0.131791
30     ▁precedent     C  only transformed -0.000000  0.125911
31       ▁already     C  only transformed  0.000000  0.121682
32     ▁inaugural     C  only transformed  0.000000  0.121523
33           ▁new     B  only transformed  0.000000  0.109762
34    ▁precedents     C  only transformed -0.000000  0.107470
35         ▁early     B  only transformed -0.000000  0.104241
36        ▁latest     C  only transformed  0.000000  0.101170
37           ▁Old     C  only transformed -0.000000  0.098198
38         ▁final     B  only transformed  0.000000  0.093169
39          ▁next     C  only transformed -0.000000  0.090032
40  ▁historically     N  only transformed  0.000000  0.089821
41        ▁before     B  only transformed -0.000000  0.087694
42         ▁newly     N  only transformed  0.000000  0.081780
43       ▁current     N  only transformed -0.000000  0.074686
44          ▁same     B  only transformed -0.000000  0.069143
45            New     C  only transformed -0.000000  0.068452
46       ▁ancient     C  only transformed  0.000000  0.068238
47           ▁New     B  only transformed -0.000000  0.068146
48          ▁once     N  only transformed  0.000000  0.067339
49           ▁now     B  only transformed  0.000000  0.065894
50    ▁historical     B  only transformed -0.000000  0.065627
51          Older     C  only transformed -0.000000  0.064602
52       ▁origins     C  only transformed  0.000000  0.063411
53       ▁history     B  only transformed -0.000000  0.059260
54         ▁above     N  only transformed -0.000000  0.055330
55     ▁ancestors     N  only transformed  0.000000  0.053204

====================================================================================================
=== original 93 <-> transformed 48   Jaccard = 0.048   |cos(z0, unmap(z~))| = 0.262
====================================================================================================
  original rho-candidate 93: matched transformed feature 48 is NOT in F_C (best-Jaccard transformed partner: 63, J=0.049)
  both: 5   only original: 6   only transformed: 93

label              B   C   N
in
both               3   2   0
only original      0   5   1
only transformed  30  36  27

             token label                in    Y0[93]     Y[48]
0        ▁possibly     C              both  0.353015  0.031026
1           ▁might     C              both  0.303174  0.207305
2           ▁could     B              both  0.243066  0.231525
3             ▁may     B              both  0.240829  0.198309
4           ▁would     B              both  0.167452  0.225347
5        ▁possible     N     only original  0.425124  0.000000
6     ▁possibility     C     only original  0.386110  0.000000
7       ▁potential     C     only original  0.364795  0.000000
8          ▁likely     C     only original  0.309533  0.000000
9         ▁chances     C     only original  0.212402 -0.000000
10    ▁prospective     C     only original  0.185831  0.000000
11           ▁were     B  only transformed  0.000000  0.233875
12            ▁was     B  only transformed  0.000000  0.230095
13            ▁did     B  only transformed  0.000000  0.199187
14            ▁had     B  only transformed  0.000000  0.195293
15           ▁will     N  only transformed  0.000000  0.185851
16            ▁are     B  only transformed  0.000000  0.179831
17            ▁can     B  only transformed  0.000000  0.177296
18         ▁should     C  only transformed  0.000000  0.174253
19             ▁is     B  only transformed  0.000000  0.158512
20           ▁must     C  only transformed  0.000000  0.156112
21         ▁became     B  only transformed  0.000000  0.153692
22            ▁has     B  only transformed  0.000000  0.150860
23           ▁have     B  only transformed  0.000000  0.150786
24         ▁seemed     C  only transformed  0.000000  0.150381
25           ▁didn     N  only transformed  0.000000  0.139976
26         ▁cannot     C  only transformed  0.000000  0.134994
27           ▁knew     C  only transformed  0.000000  0.130981
28       ▁appeared     B  only transformed  0.000000  0.130662
29           ▁took     B  only transformed  0.000000  0.128237
30           ▁came     N  only transformed  0.000000  0.127729
31           ▁grew     C  only transformed  0.000000  0.121159
32           ▁went     B  only transformed  0.000000  0.121120
33          ▁began     C  only transformed  0.000000  0.115775
34           ▁gave     B  only transformed  0.000000  0.108672
35           ▁does     C  only transformed  0.000000  0.101031
36       ▁remained     N  only transformed  0.000000  0.097759
37         ▁showed     C  only transformed  0.000000  0.092785
38            ▁won     B  only transformed  0.000000  0.084843
39           ▁died     B  only transformed  0.000000  0.084379
40        ▁appears     B  only transformed  0.000000  0.081638
41             ▁do     C  only transformed  0.000000  0.081337
42            have     N  only transformed  0.000000  0.079642
43          ▁wrote     B  only transformed -0.000000  0.078450
44           ▁been     B  only transformed  0.000000  0.071757
45         ▁appear     C  only transformed  0.000000  0.071495
46           ▁habe     N  only transformed  0.000000  0.069175
47           ▁need     C  only transformed  0.000000  0.066564
48          ▁ended     C  only transformed  0.000000  0.066474
49         ▁failed     C  only transformed  0.000000  0.062770
50          ▁chose     C  only transformed  0.000000  0.062457
51           ▁felt     N  only transformed -0.000000  0.061300
52        ▁started     B  only transformed -0.000000  0.061259
53         ▁worked     N  only transformed  0.000000  0.058858
54        ▁arrived     N  only transformed  0.000000  0.056945
55       ▁resulted     N  only transformed  0.000000  0.056577
56       ▁survived     N  only transformed  0.000000  0.051954
57      ▁responded     C  only transformed -0.000000  0.051076
58       ▁received     B  only transformed  0.000000  0.050769
59         ▁remain     C  only transformed  0.000000  0.049688
60             ▁be     B  only transformed  0.000000  0.049553
61        ▁becomes     B  only transformed  0.000000  0.049378
62            ▁ran     N  only transformed  0.000000  0.048280
63   ▁participated     N  only transformed -0.000000  0.047985
64             ▁am     N  only transformed  0.000000  0.047918
65             got     C  only transformed -0.000000  0.047735
66            fell     C  only transformed -0.000000  0.047064
67         ▁become     B  only transformed  0.000000  0.046311
68          ▁never     C  only transformed  0.000000  0.044896
69          ▁being     B  only transformed  0.000000  0.044851
70           ▁also     B  only transformed  0.000000  0.044771
71          ▁needs     N  only transformed  0.000000  0.043424
72         ▁having     N  only transformed  0.000000  0.041779
73              is     B  only transformed  0.000000  0.041386
74            ▁May     N  only transformed  0.000000  0.041378
75        ▁resided     N  only transformed -0.000000  0.040880
76          ▁tried     C  only transformed  0.000000  0.040470
77       ▁declined     C  only transformed  0.000000  0.040097
78             Can     N  only transformed  0.000000  0.040070
79          ▁lived     C  only transformed  0.000000  0.039984
80          failed     C  only transformed  0.000000  0.039740
81         ▁needed     B  only transformed  0.000000  0.039674
82             May     N  only transformed  0.000000  0.039269
83       ▁vanished     N  only transformed  0.000000  0.038815
84        ▁thought     C  only transformed  0.000000  0.038602
85        ▁remains     N  only transformed  0.000000  0.038242
86          ▁still     B  only transformed  0.000000  0.037995
87          ▁acted     N  only transformed -0.000000  0.037441
88           ▁said     B  only transformed -0.000000  0.036937
89           ▁rose     C  only transformed -0.000000  0.036784
90           ▁owes     C  only transformed  0.000000  0.036229
91       ▁competed     N  only transformed -0.000000  0.035508
92         ▁really     C  only transformed  0.000000  0.034938
93           ▁know     C  only transformed -0.000000  0.034409
94            ▁sat     C  only transformed  0.000000  0.034200
95            ▁doe     C  only transformed  0.000000  0.034032
96        ▁escaped     C  only transformed  0.000000  0.032813
97         ▁belong     C  only transformed -0.000000  0.032566
98       ▁werewolf     C  only transformed -0.000000  0.032359
99          ▁Wants     C  only transformed -0.000000 -0.032279
100         ▁feels     C  only transformed  0.000000  0.031523
101        ▁wished     N  only transformed  0.000000  0.030360
102        ▁turned     N  only transformed  0.000000  0.030124
103     ▁succeeded     N  only transformed  0.000000  0.030011

====================================================================================================
=== original 94 <-> transformed 59   Jaccard = 0.062   |cos(z0, unmap(z~))| = 0.136
====================================================================================================
  original rho-candidate 94: matched transformed feature 59 is NOT in F_C (best-Jaccard transformed partner: 19, J=0.125)
  both: 3   only original: 25   only transformed: 20

label             B   C  N
in
both              0   2  1
only original     2  18  5
only transformed  4  12  4

           token label                in    Y0[94]     Y[59]
0          ▁mean     C              both -0.138258 -0.343444
1         ▁meant     N              both -0.226572 -0.227095
2       ▁purpose     C              both -0.108046 -0.120936
3        ▁assume     C     only original -0.312454  0.000000
4      ▁intended     N     only original -0.284593 -0.000000
5      ▁expected     N     only original -0.283013 -0.000000
6    ▁assumption     C     only original -0.270513 -0.000000
7       ▁assumes     C     only original -0.268592  0.000000
8        ▁expect     C     only original -0.259093 -0.000000
9      ▁supposed     N     only original -0.240422 -0.000000
10         ▁hope     C     only original -0.220786 -0.000000
11      ▁thought     C     only original -0.187112 -0.000000
12      ▁intends     C     only original -0.182148 -0.000000
13      ▁planned     B     only original -0.178893 -0.000000
14        ▁think     C     only original -0.171700 -0.000000
15         ▁Hope     N     only original -0.163490 -0.000000
16        ▁aimed     C     only original -0.156289 -0.000000
17      ▁believe     C     only original -0.146510 -0.000000
18    ▁estimated     C     only original -0.142721  0.000000
19         ▁idea     C     only original -0.133981 -0.000000
20   ▁speculated     C     only original -0.132184  0.000000
21     ▁designed     B     only original -0.123617 -0.000000
22       ▁imagin     C     only original -0.113888 -0.000000
23   ▁considered     C     only original -0.111396 -0.000000
24    ▁suggested     C     only original -0.104488  0.000000
25       ▁wished     N     only original -0.102618  0.000000
26    ▁purported     C     only original -0.102327  0.000000
27     ▁targeted     C     only original -0.097447  0.000000
28         means     C  only transformed -0.000000 -0.408118
29          ▁way     B  only transformed -0.000000 -0.376150
30         ▁ways     B  only transformed -0.000000 -0.323574
31      ▁meaning     N  only transformed -0.000000 -0.309832
32           way     N  only transformed -0.000000 -0.252506
33       ▁manner     C  only transformed -0.000000 -0.249753
34       ▁reason     C  only transformed -0.000000 -0.189738
35      ▁reasons     B  only transformed -0.000000 -0.176399
36      ▁methods     C  only transformed -0.000000 -0.158223
37      ▁Methods     N  only transformed -0.000000 -0.117262
38          ▁how     C  only transformed -0.000000 -0.112325
39       ▁matter     C  only transformed  0.000000 -0.097187
40        ▁sense     C  only transformed -0.000000 -0.092907
41      ▁ability     C  only transformed -0.000000 -0.090707
42  ▁possibility     C  only transformed  0.000000 -0.086511
43         ▁fact     C  only transformed -0.000000 -0.082422
44       ▁amount     C  only transformed -0.000000 -0.076391
45         ▁away     B  only transformed  0.000000 -0.074590
46         ▁need     C  only transformed -0.000000 -0.072963
47   ▁importance     N  only transformed -0.000000 -0.071722

====================================================================================================
=== original 96 <-> transformed 60   Jaccard = 0.235   |cos(z0, unmap(z~))| = 0.483
====================================================================================================
  original rho-candidate 96: matched transformed feature 60 is NOT in F_C (best-Jaccard transformed partner: 37, J=0.269)
  both: 4   only original: 6   only transformed: 7

label             B  C  N
in
both              1  3  0
only original     1  3  2
only transformed  1  4  2

          token label                in    Y0[96]     Y[60]
0         ▁half     C              both  0.265123 -0.543030
1          half     B              both  0.257016 -0.516784
2         ▁Half     C              both  0.250305 -0.503380
3      ▁partial     C              both  0.188457 -0.193031
4          part     C     only original  0.424565 -0.000000
5         ▁part     B     only original  0.417570 -0.000000
6         ▁Part     N     only original  0.399360 -0.000000
7        ▁parts     C     only original  0.356414  0.000000
8        ▁Parts     C     only original  0.337679  0.000000
9   ▁components     N     only original  0.101572  0.000000
10        ▁full     C  only transformed  0.000000 -0.247783
11         full     C  only transformed  0.000000 -0.229883
12       ▁whole     B  only transformed  0.000000 -0.096208
13      ▁almost     C  only transformed  0.000000 -0.080092
14    ▁complete     N  only transformed  0.000000 -0.078131
15       ▁fifty     C  only transformed  0.000000 -0.076941
16         ▁Sem     N  only transformed  0.000000 -0.073913

====================================================================================================
=== original 98 <-> transformed 19   Jaccard = 0.227   |cos(z0, unmap(z~))| = 0.741
====================================================================================================
  original rho-candidate 98: matched transformed feature 19 is NOT in F_C (best-Jaccard transformed partner: 19, J=0.227)
  both: 10   only original: 0   only transformed: 34

label             B   C  N
in
both              0   9  1
only transformed  5  23  6

          token label                in    Y0[98]     Y[19]
0         ▁love     C              both  0.484838 -0.356023
1         ▁Love     N              both  0.443047 -0.276587
2          Love     C              both  0.433316 -0.272849
3        ▁loves     C              both  0.399589 -0.317589
4        ▁loved     C              both  0.364449 -0.269047
5        ▁likes     C              both  0.181497 -0.295180
6      ▁dislike     C              both  0.143854 -0.144932
7    ▁favourite     C              both  0.120298 -0.086338
8      ▁romance     C              both  0.102466 -0.092846
9          ▁joy     C              both  0.098889 -0.071809
10        ▁like     B  only transformed  0.000000 -0.267125
11         Like     B  only transformed  0.000000 -0.222479
12       ▁wants     C  only transformed  0.000000 -0.183441
13       ▁Wants     C  only transformed  0.000000 -0.164266
14        ▁hope     C  only transformed  0.000000 -0.144573
15      ▁desire     C  only transformed  0.000000 -0.122398
16        ▁need     C  only transformed  0.000000 -0.116354
17       ▁needs     N  only transformed  0.000000 -0.114247
18        ▁know     C  only transformed  0.000000 -0.107433
19     ▁friends     B  only transformed  0.000000 -0.103709
20     ▁thought     C  only transformed  0.000000 -0.101614
21  ▁friendship     C  only transformed  0.000000 -0.096066
22       ▁think     C  only transformed  0.000000 -0.095440
23        ▁knew     C  only transformed  0.000000 -0.095030
24      ▁friend     C  only transformed  0.000000 -0.093052
25     ▁believe     C  only transformed  0.000000 -0.092470
26  ▁interested     C  only transformed  0.000000 -0.088494
27   ▁interests     N  only transformed  0.000000 -0.086294
28        ▁Hope     N  only transformed  0.000000 -0.082821
29    ▁romances     C  only transformed  0.000000 -0.081689
30       Unlike     C  only transformed  0.000000 -0.081442
31      ▁expect     C  only transformed -0.000000 -0.081107
32          lik     N  only transformed  0.000000 -0.076169
33      ▁needed     B  only transformed  0.000000 -0.074980
34     ▁willing     C  only transformed  0.000000 -0.071382
35   ▁happiness     C  only transformed  0.000000 -0.070959
36      ▁wished     N  only transformed  0.000000 -0.069214
37      ▁dreams     B  only transformed  0.000000 -0.069207
38       ▁trust     N  only transformed  0.000000 -0.067733
39      ▁tastes     C  only transformed  0.000000 -0.066319
40     ▁intends     C  only transformed  0.000000 -0.065765
41  ▁understand     C  only transformed  0.000000 -0.064782
42    ▁romantic     C  only transformed  0.000000 -0.063881
43     ▁likened     C  only transformed  0.000000 -0.061473

#### Run summary → `RUN_DIR/summary.json`

Configuration (variant, `VWConfig`, whitening), $|V^*|$, relative errors and width statistics of both fits, $\rho_{\max}$, $F_C$
(judged, whitened fit) with each feature's width, `F_C0` (= $\rho\ge\tau$ candidates of the original fit, not judged), each $F_C$
feature's matched original partner (Jaccard, partner in `F_C0`?), and the number of concept-only tokens $F_C$ touches.

In [43]:
def write_summary(**extra) -> dict:
    """Write RUN_DIR/summary.json from the current state; `extra` adds or overrides fields."""
    eligible_cols = ((Y[F_C].abs() > 0).any(dim=0).numpy() & (codes == 1)) if F_C else np.zeros(len(vstar_ids), bool)
    summary = {
        "config": {"model": MODEL_NAME, "concept": CONCEPT, "variant": VARIANT, "vwconfig": CFG.to_dict(), "seed": SEED,
                   "background": BACKGROUND, "target": TARGET, "gamma": GAMMA, "eta": ETA, "eps_rel": EPS_REL,
                   "eps": float(bw.eps), "rank": RANK, "smoke": SMOKE, "n_target": len(target_ids)},
        "n_vstar": len(vstar_ids),
        "rel_err": {"original": rel_err0, "transformed": rel_err},
        "n_iter": {"original": fit0["n_iter"], "transformed": fit["n_iter"]},
        "widths": {"transformed": widths.tolist(), "original": widths0.tolist()},
        "F_C_widths": {str(f): int(widths[f]) for f in F_C},
        "rho_max": float(stats["ratio_abs"].max()),
        "rho_max_original": float(stats0["ratio_abs"].max()),
        "n_F_C": len(F_C),
        "F_C": F_C,
        "F_C0": F_C0,                     # rho >= tau candidates of the original fit (no judge)
        "F_C_matched": [{"feature": f, "partner": match1[f], "jaccard": float(J[match1[f], f]),
                         "partner_in_F_C0": match1[f] in F_C0, "cos_m": float(cos_m[f])} for f in F_C],
        "F_C0_matched": [{"feature": f0, "partner": match0[f0], "jaccard": float(J[f0, match0[f0]]),
                          "partner_in_F_C": match0[f0] in F_C} for f0 in F_C0],
        "matched_jaccard_median": float(np.median(J[rows0, cols1])),
        "n_edit": int(eligible_cols.sum()),
        **extra,
    }
    save_json(RUN_DIR / "summary.json", summary)
    print(f"wrote {RUN_DIR / 'summary.json'}: F_C={F_C} F_C0={F_C0} n_edit={summary['n_edit']} "
          f"rel_err={rel_err:.4f} (orig {rel_err0:.4f}) rho_max={summary['rho_max']:.2f}")
    return summary


summary = write_summary()

wrote runs/variable_width/Harry_Potter/m1/summary.json: F_C=[46] F_C0=[3, 5, 6, 10, 12, 18, 20, 22, 23, 24, 27, 28, 29, 30, 32, 35, 36, 39, 40, 41, 43, 50, 51, 54, 57, 58, 59, 61, 67, 70, 71, 73, 76, 78, 80, 81, 82, 83, 84, 85, 86, 87, 89, 91, 93, 94, 96, 98] n_edit=44 rel_err=0.8510 (orig 0.8984) rho_max=129.35