In [1]:
# Low-RAM clone: run from the repo root (data/, runs/, experiments/ and the ember package are resolved from there).
import os
import sys
from pathlib import Path

_root = Path.cwd()
while not (_root / "ember").is_dir() and _root != _root.parent:
    _root = _root.parent
assert (_root / "ember").is_dir(), "repo root (the folder with ember/) not found above the cwd"
os.chdir(_root)
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))
print(f"cwd: {_root}")

cwd: /home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj

# EMBER §3.1–3.2, variable-width sparse MF — Harry Potter, whitened, variant `rn`

> **Concept:** Harry Potter · **model:** `google/gemma-2-2b-it` · **variant:** `rn` = `VWConfig(method="rn", refit=False)` · **seed:** 42
>
> Clone of `low_ram_demands/whitened.ipynb` (background-whitened + target-sharpened, low RAM) that keeps **only Steps 3.1
> (factorization) and 3.2 (feature identification)**. Step 3.3 (erasure), 3.4 and everything that needs the HF model were removed.
>
> **What changed vs. the source notebook**
> - 3.1.d fits the whitened matrix $A = X^\top$ with the shared variable-width loop `fit_varwidth(A, CFG, seed=SEED)` from
>   `experiments/varwidth/core.py` instead of `SparseMatrixFactorization` + WTA. The implementation and settings are the same as the
>   experiments in `results/varwidth/` (`python -m experiments.varwidth.run`), so this notebook reproduces their
>   `results/varwidth/Harry_Potter/<tag>/seed42/` runs (3.1.d prints the difference if that run exists).
> - 3.1.d′ fits the raw matrix $A_0 = E_{V^*}^\top$ with the **same** method and config (`fit_varwidth(A0, CFG, seed=SEED)`).
> - 3.2 runs the two-stage Gemini judge **only on the whitened fit**. For the original fit (3.2.e′) there are **no Gemini calls**: it
>   lists the $\rho \ge \tau$ candidates with their widths and top tokens, and those candidates stand in for `F_C0` in the
>   comparison cells (3.2.w).
>
> **Hyperparameters**
>
> | | value |
> |---|---|
> | sparse MF | `VWConfig(method="rn", refit=False)`; all other `VWConfig` fields at their defaults: rank 100, sparsity 0.01 (unless set above), floor 0.002, cap 0.03, ridge 1e-4, max_iter 20000, tol 1e-4, patience 200, churn_tol 0.005, init randn, m3_every 20, m3_window 0.02, m3_c 2.0 |
> | whitening | BACKGROUND `"wiki"`, TARGET `"page"`, GAMMA 1.0, ETA / EPS_REL from `experiments/whitening/data/gemma/defaults.json` (0.05 / 1e-4) — as `experiments/varwidth/prep.py` (the source notebook had GAMMA = 0) |
> | selection | TAU 2.0, CONFIDENCE 0.85, TOP_K_TOKENS 20, GEMINI_MODEL `models/gemini-3.5-flash-lite`, judge input = bare tokens |
>
> **Runs.** Caches go to `RUN_DIR = runs/variable_width/Harry_Potter/rn/` (`fit.pt`, `fit0.pt`, `judge.json`, `summary.json`);
> the extended sentences of 3.2.g to `runs/variable_width/Harry_Potter/ext_sentences.json` (shared by the five variants).

Paper: *Don't Forget Your Embeddings: Robust Knowledge Erasure via Precise Editing of Embeddings*
(Suslik, Shafran, Geva, EMNLP Findings 2026).

| Step | Paper section | What happens | Code |
|---|---|---|---|
| **3.1** | Finding Embedding Features with Sparse MF | factorize $X^\top \approx ZY$ with sparse $Y$ (variable width per feature) | `experiments/varwidth/core.py` `fit_varwidth` |
| **3.2** | Identifying Concept-Related Features | mass ratio $\rho_i \ge \tau$, then a two-stage Gemini judge → $F_C$ | `compute_embedding_stats`, prompts from `ember/interpret_features.py` |

**Notation.** `Z` $\in \mathbb R^{d\times k}$ and `Y` $\in \mathbb R^{k\times|V^*|}$ use the paper's shapes. The **width** of feature $i$ is
$|\{t : Y_{i,t} \neq 0\}|$, the number of tokens it uses.

**Requirements:** `HF_TOKEN` if the checkpoint is gated, and a Gemini API key for the judge on the whitened fit (3.2.d–e, 3.2.g neighbours).

---
## 0. Setup

### 0.1 Hyperparameters

| Symbol | Value | Source |
|---|---|---|
| $k$ (rank) | 100 (Gemma-2-2B-it) | App. A.1 |
| budget | $K = \lceil s\,|V^*| \rceil \cdot k$ nonzeros in $Y$, $s$ = `CFG.sparsity` (0.01, or 0.02 for `fixed2`) | App. A.1 / `VWConfig` |
| width bounds | $m_{min} = \lceil 0.002\,|V^*|\rceil$, $m_{max} = \lceil 0.03\,|V^*|\rceil$ (pooling methods and m3; `fixed` ignores them) | `VWConfig.floor`, `.cap` |
| $\lambda$ (ridge) | $10^{-4}$ | App. A.1 |
| $T$ / patience / tol | 20,000 iters / 200 iters (rel. error and support churn < 0.005) / $10^{-4}$ | `VWConfig` |
| refit | off: $Y = Y^{dense}\odot S$ (as the paper) | `VWConfig.refit` |
| $\|S_C\| = \|S_N\|$ | 300 sentences each (`data/*_sentences.json`) | §4.1 |
| $\tau$ (mass-ratio threshold) | 2.0 | App. A.3 |
| judge confidence | ≥ 0.85, with 20 tokens per feature | App. A.3 |

In [2]:
import gc
import json
import math
import os
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from dotenv import load_dotenv
from tqdm.auto import tqdm

load_dotenv()  # HF_TOKEN / GEMINI_API_KEY from .env, if present
pd.set_option("display.max_colwidth", 200)

# ---- what to erase ------------------------------------------------------
CONCEPT = "Harry Potter"
MODEL_NAME = "google/gemma-2-2b-it"     # or "meta-llama/Llama-3.1-8B-Instruct"
SEED = 42

# ==== VARIANT: variable-width sparse MF (experiments/varwidth/, same code and settings as results/varwidth/) ====
import dataclasses

from experiments.varwidth.common import VWConfig, budgets
from experiments.varwidth.core import fit_varwidth

VARIANT = "rn"
VARIANT_CONFIGS = {
    "fixed1": VWConfig(method="fixed", refit=False),                 # the paper: WTA, every feature keeps ceil(0.01 n) tokens
    "fixed2": VWConfig(method="fixed", refit=False, sparsity=0.02),  # WTA with 2%: every feature keeps ceil(0.02 n) tokens
    "m1": VWConfig(method="m1", refit=False),                        # contribution pooling: global top-K of |y_ij|*||z_i||, floor/cap
    "m3": VWConfig(method="m3", refit=False),                        # entropy-allocated widths (exp H of the noise-cut top 2% of |y_i|)
    "rn": VWConfig(method="rn", refit=False),                        # pooling on |y_ij| / ||y_i||, floor/cap
}
CFG = VARIANT_CONFIGS[VARIANT]   # rn: row-normalized pooling: global top-K of |y_ij| / ||y_i|| (dense row norm), each row within [floor, cap]
SEED = 42
# all other VWConfig fields stay at their defaults (rank 100, floor 0.002, cap 0.03, ridge 1e-4, max_iter 20000, tol 1e-4,
# patience 200, churn_tol 0.005, init randn, m3_every 20, m3_window 0.02, m3_c 2.0)
# ===================================================================================================================

# ---- Step 3.1: names the cells below use, taken from CFG ----------------
RANK = CFG.rank          # k
SPARSITY = CFG.sparsity  # s: total budget K = ceil(s * |V*|) * k
RIDGE = CFG.ridge        # lambda
MAX_ITER = CFG.max_iter  # T
PATIENCE = CFG.patience

# ---- Step 3.2: feature selection (App. A.3) -----------------------------
TAU = 2.0
CONFIDENCE = 0.85
TOP_K_TOKENS = 20
GEMINI_MODEL = "models/gemini-3.5-flash-lite"   # repo default; the paper used Gemini-2.5-Flash-Lite
JUDGE_FORMAT = "tokens"   # Stage-1 judge input: "tokens" (bare tokens, paper; this notebook's original format)
                          # | "words" (token → the words it was cut from in S_C ∪ S_N, alphabetical)

# ---- background whitening + target sharpening (Instructions.txt, experiments/whitening/sharpen.py) ----
import re
import sys

sys.path.insert(0, "experiments/whitening")
from sharpen import BackgroundWhitener, Sharpener, Transform, principal_angle_sines

BACKGROUND = "wiki"      # "wiki" (Wikipedia token types) or "full" (whole vocabulary)
TARGET = "page"          # "page" (all tokens of the concept's English Wikipedia page) or "page_minus_wiki"
GAMMA = 1.0              # sharpening strength, as experiments/varwidth/prep.py (the source notebook had 0)
MODEL_SLUG = "gemma"     # "gemma" | "llama": selects experiments/whitening/data/<MODEL_SLUG>
SMOKE = False            # True: quick pass (short fit, 3 judged features)
assert BACKGROUND in ("wiki", "full"), BACKGROUND
assert TARGET in ("page", "page_minus_wiki"), TARGET
assert GAMMA >= 0, GAMMA
assert MODEL_SLUG == ("llama" if "llama" in MODEL_NAME.lower() else "gemma"), (MODEL_SLUG, MODEL_NAME)

WH_DIR = Path("experiments/whitening/data") / MODEL_SLUG
_defaults_path = WH_DIR / "defaults.json"     # the file experiments/varwidth/prep.py reads (no built-in fallback)
defaults = json.loads(_defaults_path.read_text())
ETA = defaults["eta"]            # target shrinkage (0.05)
EPS_REL = defaults["eps_rel"]    # eps = EPS_REL * mean(background eigenvalues) (1e-4)
print(f"whitening defaults from {_defaults_path}: eta={ETA:g} eps_rel={EPS_REL:g}")

if SMOKE:
    CFG = dataclasses.replace(CFG, max_iter=50, patience=5)
    MAX_ITER, PATIENCE = CFG.max_iter, CFG.patience

# ---- run directories: resume caches ----
concept_slug = re.sub(r"\W+", "_", CONCEPT).strip("_")
_smoke = "_smoke" if SMOKE else ""
RUN_DIR = Path("runs/variable_width") / concept_slug / f"{VARIANT}{_smoke}"   # fit.pt, fit0.pt, judge.json, summary.json
RUN_DIR.mkdir(parents=True, exist_ok=True)


def load_json(path: Path, default):
    return json.loads(path.read_text()) if path.exists() else default


def save_json(path: Path, obj) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")   # write then rename, so a crash never leaves a half file
    tmp.write_text(json.dumps(obj, indent=1, ensure_ascii=False, default=lambda o: o.item() if hasattr(o, "item") else str(o)))
    tmp.replace(path)


def invalidate(directory: Path, names) -> None:
    """Move stale cache files aside (<name>.stale) so they are recomputed."""
    for name in names:
        p = directory / name
        if p.exists():
            p.replace(p.with_name(p.name + ".stale"))
            print(f"  moved stale {p} -> {p.name}.stale")

concepts = [e["concept"] for e in json.loads(Path("data/concept_sentences.json").read_text())]
assert CONCEPT in concepts, f"{CONCEPT!r} is not one of: {concepts}"
print(f"concept={CONCEPT!r} | model={MODEL_NAME} | variant={VARIANT} | seed={SEED} | config={CFG}")
print(f"background={BACKGROUND} | target={TARGET} | gamma={GAMMA:g} | eta={ETA:g} | eps_rel={EPS_REL:g} | "
      f"smoke={SMOKE} | run dir={RUN_DIR}")

whitening defaults from experiments/whitening/data/gemma/defaults.json: eta=0.05 eps_rel=0.0001
concept='Harry Potter' | model=google/gemma-2-2b-it | variant=rn | seed=42 | config=VWConfig(method='rn', rank=100, sparsity=0.01, floor=0.002, cap=0.05, ridge=0.0001, max_iter=20000, tol=0.0001, patience=200, churn_tol=0.005, init='randn', refit=False, floorcap=True, continuation=False, cont_start=0.05, cont_iters=2000, m3_every=20, m3_window=0.02, m3_c=2.0, m4_every=10)
background=wiki | target=page | gamma=1 | eta=0.05 | eps_rel=0.0001 | smoke=False | run dir=runs/variable_width/Harry_Potter/rn

/home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 0.2 Gemini API key

Step 3.2 is the only step that calls Gemini. You can paste your key below or put `GEMINI_API_KEY=...`
in `.env`. Clear the key from this cell before you commit or share the notebook.

In [3]:
GEMINI_API_KEY = ""  # paste here, or leave empty to use .env / the environment

if GEMINI_API_KEY:
    os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
assert any(os.getenv(k) for k in ("GOOGLE_API_KEY", "GEMINI_API_TOKEN", "GEMINI_API_KEY")), \
    "No Gemini key found: Step 3.2 needs one."
print("Gemini key found.")

Gemini key found.

### 0.3 Repo imports

These are the building blocks the paper's pipeline uses. Reusing them means the notebook gives the same
results as `ember.train_mf_features`, `ember.interpret_features`, and `ember.run_erasure`.

In [4]:
from llm_utils.activation_generator import ActivationGenerator, extract_token_ids_sample_ids_and_labels
from transformers import AutoTokenizer

from ember.interpret_features import (
    MEMBERSHIP_PROMPT,
    TOKENS_DESC_SYS,
    SimpleGeminiClient,
    classify_membership_with_desc,
    get_description,
)
from ember.local_datasets import ConceptDataset
from ember.timing import Timer
from ember.utils import (
    _safe_model_name,
    build_token_label_codes,
    collect_feature_rows_for_embeddings,
    compute_embedding_stats,
    get_special_token_ids,
    set_seed,
)

set_seed(SEED)
# DEVICE = resolve_device("auto")
# This host's vGPU reports CUDA as available but prohibits compute, so force CPU.
DEVICE = "cpu"   # the experiments (experiments/varwidth/run.py) also fit on CPU
print(f"device: {DEVICE}")

device: cpu

---
# Step 3.1: Finding embedding features with Sparse Matrix Factorization

**Goal:** split each token embedding $\mathbf e_t$ into a sum of a few shared directions, so that
semantically related tokens (e.g. *Harry*, *Hogwarts*, *wand*) share a feature:

$$E_{V^*}^\top \approx Z\,Y,\qquad Z\in\mathbb R^{d\times k}\ \text{(dense features)},\quad Y\in\mathbb R^{k\times|V^*|}\ \text{(sparse coefficients)}$$

In the paper a hard winner-takes-all (WTA) constraint on the rows of $Y$ makes each feature $\mathbf z_i$ use only
1% of the tokens in $V^*$. That is why a feature can be specific to one concept. **In this notebook** the support of $Y$ is
chosen by the variant's allocation rule (`CFG.method`, see 3.1.d): the total number of nonzeros is fixed at
$K = \lceil s|V^*|\rceil\cdot k$, but except for `fixed` the **width** (tokens per feature) can differ between features.

### 3.1.a Load the model (TransformerLens)

The pipeline reads $E$ through TransformerLens. **Note:** for Gemma, TL folds the $\sqrt{d}$ embedding
multiplier into `W_E`, so the factorization runs in this *scaled* space.

In [5]:
# Low-RAM: steps 3.1-3.2 use only W_E and the tokenizer, so no TransformerLens model is built.
# W_E is read straight from the checkpoint and matches TL's: Gemma = HF embedding * sqrt(d_model), Llama = as stored;
# TL skips writing-weight centering for RMSNorm models. E_DTYPE is the dtype this notebook's TL model used.
import json
import math
from types import SimpleNamespace

from huggingface_hub import hf_hub_download
from huggingface_hub.utils import EntryNotFoundError
from safetensors import safe_open

E_DTYPE = torch.float32

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if tokenizer.pad_token is None:  # Llama-3: TL also pads with eos
    tokenizer.pad_token = tokenizer.eos_token


def load_input_embeddings(model_name: str) -> torch.Tensor:
    """Reads only model.embed_tokens.weight from the checkpoint (no model is built)."""
    try:
        index = json.loads(Path(hf_hub_download(model_name, "model.safetensors.index.json")).read_text())
        shard = index["weight_map"]["model.embed_tokens.weight"]
    except EntryNotFoundError:  # single-file checkpoint
        shard = "model.safetensors"
    with safe_open(hf_hub_download(model_name, shard), framework="pt") as f:
        return f.get_tensor("model.embed_tokens.weight")


class TokenizerOnly:
    """The parts of a HookedTransformer that 3.1-3.2 use: tokenizer, to_tokens, to_str_tokens."""

    def __init__(self, tok):
        self.tokenizer = tok

    def to_tokens(self, prompts, padding_side="left"):
        self.tokenizer.padding_side = padding_side
        return self.tokenizer(prompts, return_tensors="pt", padding=True)["input_ids"]  # BOS added by the tokenizer

    def to_str_tokens(self, ids):
        return self.tokenizer.batch_decode(torch.as_tensor(ids).reshape(-1, 1), clean_up_tokenization_spaces=False)


tl_model = TokenizerOnly(tokenizer)  # keeps the old names, so the cells below run unchanged
act_generator = SimpleNamespace(model=tl_model, data_device="cpu")

E = load_input_embeddings(MODEL_NAME).to(E_DTYPE)  # (|V|, d)
if "gemma" in MODEL_NAME.lower():
    E.mul_(torch.tensor(math.sqrt(E.shape[1]), dtype=E_DTYPE))  # in place: no second (|V|, d) copy
VOCAB_SIZE, D_MODEL = E.shape
print(f"E: {tuple(E.shape)}  dtype={E.dtype}")

E: (256000, 2304)  dtype=torch.float32

### 3.1.b Build $S_C \cup S_N$ and the token set $V^*$

- $S_C$: 300 Wikipedia sentences about the concept. $S_N$: 300 neutral Wikipedia sentences.
- $V^*$: the unique non-special token ids in $S_C \cup S_N$. The model factorizes only these rows of $E$,
  which is cheaper and keeps the factorization focused on the concept. The neutral tokens let Step 3.2
  tell concept features apart from general ones.

In [6]:
dataset = ConceptDataset(concept_name=CONCEPT, neutral_sample_seed=42)
token_ids_all, sample_ids, labels_all = extract_token_ids_sample_ids_and_labels(dataset, act_generator)

special = get_special_token_ids(tl_model)
vstar_ids = sorted({int(t) for t in token_ids_all.tolist()} - special)

n_concept_sents = sum(lbl == CONCEPT for _, lbl in dataset)
print(f"|S_C| = {n_concept_sents}   |S_N| = {len(dataset) - n_concept_sents}")
print(f"token occurrences = {len(token_ids_all)}  ->  |V*| = {len(vstar_ids)} "
      f"({len(vstar_ids) / VOCAB_SIZE:.2%} of the vocabulary)")

Extracting token IDs: 100%|██████████| 120/120 [00:00<00:00, 977.46it/s]

|S_C| = 300   |S_N| = 300
token occurrences = 18611  ->  |V*| = 4780 (1.87% of the vocabulary)

### 3.1.c Build the data matrix $A = E_{V^*}^\top$

Each column of $A$ is one token's embedding.

In [7]:
E_vstar = E.index_select(0, torch.tensor(vstar_ids, device=E.device)).detach().float()  # (|V*|, d)
A = E_vstar.T.contiguous().to(DEVICE)                                                      # (d, |V*|)

print(f"A: {tuple(A.shape)}  (d x |V*|)")
K_BUDGET, M_MIN, M_MAX = budgets(len(vstar_ids), CFG)
if CFG.method == "fixed":
    print(f"{CFG.method}: every feature keeps ceil(s*|V*|) = {math.ceil(SPARSITY * len(vstar_ids))} tokens (K = {K_BUDGET})")
else:
    print(f"{CFG.method}: K = ceil(s*|V*|)*k = {K_BUDGET} nonzeros in total, widths in [{M_MIN}, {M_MAX}] "
          f"(mean {K_BUDGET / RANK:.1f} per feature)")

A: (2304, 4780)  (d x |V*|)
rn: K = ceil(s*|V*|)*k = 4800 nonzeros in total, widths in [10, 239] (mean 48.0 per feature)

### 3.1.c′ Background whitening and target sharpening

Instructions steps 1–4, in the row convention of the notebook (rows are tokens; `sharpen.py`):

$$U = (E_{V^*} - \mathbf 1\boldsymbol\mu_B^\top)\,W,\quad W = Q(\Lambda+\epsilon I)^{-1/2}Q^\top;\qquad
S_\eta = (1-\eta)\,\tfrac1m U_C^\top U_C + \eta I = P\,\mathrm{diag}(g)\,P^\top;\qquad X = U\,S_\eta^{\gamma/2}$$

1. **Background** ($\boldsymbol\mu_B$, $Q$, $\Lambda$ of $\Sigma_B$) is loaded from `WH_DIR/bg_<BACKGROUND>_stats.pt`. It was computed once per
   model, in the same space as `E` (TL `W_E`: Gemma rows already × $\sqrt d$; Llama unscaled). $\epsilon$ = `EPS_REL` × mean($\Lambda$).
   Check: $W\Sigma_B W = Q\,\mathrm{diag}\big(\lambda/(\lambda+\epsilon)\big)Q^\top \approx I$, except along the smallest
   eigenvalues, which $\epsilon$ deliberately damps.
2. **Whitening** centres on $\boldsymbol\mu_B$ (not on the mean of $V^*$), so the concept's shift away from the background stays in the data.
3. **Target**: the token ids of the concept's Wikipedia page (`WH_DIR/targets/<concept>.json`, key `TARGET`), whitened with the
   same $W$. The second moment is taken around 0, so it includes that shift. $g_j$ are **enrichment ratios** ($g_j > 1$: the target
   varies more than the background along $\mathbf p_j$); $\eta$ = `ETA` puts a floor under the directions the target does not use.
4. **Sharpening** with $S_\eta^{\gamma/2}$ applies one fixed map to every row of $V^*$, concept and neutral alike. `GAMMA = 0` skips it.

The combined map is `T` (`Transform`): `T.forward(rows)` $= (\text{rows}-\boldsymbol\mu_B)\,M$ with $M$ = `T.matrix` $= W S_\eta^{\gamma/2}$, and
`T.unmap(z)` $= z\,S_\eta^{-\gamma/2}W^{-1}$ maps directions back. `transform(rows)` is the float32 helper the analysis cells use.

**Diagnostics.** The largest enrichment ratios, and the contrastive-PCA directions $\mathbf p_1,\dots,\mathbf p_5$: the whitened
Wikipedia background token types (`bg_wiki_types.json`) projected on each, top 15 shown (`*` = in the target set). If they are
concept tokens, the signal is there before any factorization. With `GAMMA = 0` the same diagnostics use a $\gamma=1$ sharpener that is
not applied.

From here on `A` is $X^\top$; `E_vstar_orig` (= `E_vstar`) keeps the raw rows and `A0` the raw data matrix.

**Same as the experiments.** This cell is the code path of `experiments/varwidth/prep.py` (`whitening_transform` +
`prepare(matrix="whitened")`): background `bg_wiki_stats.pt` in float64, `BackgroundWhitener(stats, EPS_REL)`, target ids =
`targets/Harry_Potter.json["page"]` within the vocabulary minus special ids, `Sharpener(U_target, ETA, GAMMA)` with GAMMA = 1,
and `A = T.forward(E_vstar).float().T`. `A0 = E_vstar.T` is prep's `"plain"` matrix.

In [8]:
# Instructions steps 1-4: background whitening W, target second moment S_eta, sharpening S_eta^(gamma/2). float64, CPU.
E_vstar_orig = E_vstar                                    # raw rows (Gemma: TL-scaled), for the original fit 3.1.d'
A0 = E_vstar.T.contiguous().to(DEVICE)                    # (d, |V*|) raw

# ---- step 1: background statistics (built once per model by experiments/whitening) ----
BG_PATH = WH_DIR / f"bg_{BACKGROUND}_stats.pt"
TARGETS_PATH = WH_DIR / "targets" / f"{concept_slug}.json"
for _p, _what in [(BG_PATH, f"background statistics ({BACKGROUND})"), (TARGETS_PATH, f"target token ids for {CONCEPT!r}")]:
    if not _p.exists():
        raise FileNotFoundError(f"{_p} is missing: the {_what} must be built first (experiments/whitening)")
stats_bg = torch.load(BG_PATH, map_location="cpu")
missing_keys = {"mu", "lam", "Q"} - set(stats_bg)
assert not missing_keys, f"{BG_PATH} lacks {missing_keys}"
assert stats_bg["Q"].shape == (D_MODEL, D_MODEL), f"{BG_PATH}: Q is {tuple(stats_bg['Q'].shape)}, expected d = {D_MODEL}"
stats_bg = {k: (v.double() if torch.is_tensor(v) else v) for k, v in stats_bg.items()}
bw = BackgroundWhitener(stats_bg, EPS_REL)

lam_bg = stats_bg["lam"].clamp_min(0)
lam_desc = lam_bg.sort(descending=True).values
shrink = lam_desc / (lam_desc + bw.eps)                   # eigenvalues of W Sigma_B W
n95 = math.ceil(0.95 * len(lam_desc))
print(f"background {BACKGROUND}: n = {stats_bg.get('n', '?')} types, d = {D_MODEL}, eps = {EPS_REL:g} x mean(lam) = {bw.eps:.3e}")
print(f"W Sigma_B W ~ I: max |lam/(lam+eps) - 1| over the top 95% of directions = {(shrink[:n95] - 1).abs().max():.3e}, "
      f"overall = {(shrink - 1).abs().max():.3e} (the smallest eigenvalues are damped by eps on purpose)")
print(f"cond(Sigma_B) = {(lam_desc[0] / lam_desc[-1]).item() if lam_desc[-1] > 0 else float('inf'):.3e}   "
      f"cond(Sigma_B + eps I) = {((lam_desc[0] + bw.eps) / (lam_desc[-1] + bw.eps)).item():.3e}")

# ---- step 3: target rows, whitened ----
targets = json.loads(TARGETS_PATH.read_text())
assert TARGET in targets, f"{TARGETS_PATH} has keys {list(targets)}, not {TARGET!r}"
target_ids = sorted({int(t) for t in targets[TARGET] if 0 <= int(t) < VOCAB_SIZE} - set(special))
assert target_ids, f"{TARGETS_PATH}[{TARGET!r}] has no usable token ids"
E_target = E.index_select(0, torch.tensor(target_ids, device=E.device)).detach().double().cpu()   # (m, d), same space as E_vstar
U_target = bw.whiten(E_target)                                                                     # (m, d)
target_set, vstar_set = set(target_ids), set(vstar_ids)
_codes31 = build_token_label_codes(CONCEPT, dataset, tokenizer)
tc_ids = {t for t in vstar_ids if _codes31.get(t, 0) == 1}                                         # T_C (concept-only)
print(f"|target| = {len(target_ids)} ({TARGET})   in V*: {len(target_set & vstar_set)} / {len(vstar_ids)}   "
      f"concept-only T_C covered: {len(target_set & tc_ids)} / {len(tc_ids)}")

# ---- step 4: sharpening; T = whitening (+ sharpening) ----
sh = Sharpener(U_target, ETA, GAMMA) if GAMMA > 0 else None
sh_diag = sh if sh is not None else Sharpener(U_target, ETA, 1.0)   # gamma = 0: diagnostics only, never applied
T = Transform(bw, sh)


def transform(rows: torch.Tensor) -> torch.Tensor:
    """Rows (n, d) in the original (TL) space -> X-space: (rows - mu_B) W S_eta^(gamma/2), float32."""
    return T.forward(rows.detach().cpu()).float()


E_X = transform(E_vstar)                                  # (|V*|, d)
E_vstar_X = E_X                                           # all analysis cells use it
A = E_X.T.contiguous().to(DEVICE)                         # (d, |V*|): 3.1.d fits on this
m_tilde = U_target.mean(0)                                # whitened target mean (the whitened shift Delta)
m_X = m_tilde if sh is None else m_tilde @ sh.Sp          # its image in X-space (= mean of transform(E_target))

# ---- checks ----
I_d = torch.eye(D_MODEL, dtype=torch.float64)
T_inv = bw.W_inv if sh is None else sh.Sm @ bw.W_inv      # row form: z = z~ @ T_inv
print(f"inverse: max |T.matrix @ (Sm @ W_inv) - I| = {(T.matrix @ T_inv - I_d).abs().max():.2e}")
print(f"row norms: raw mean {E_vstar.norm(dim=1).mean():.3f}   X-space mean {E_X.norm(dim=1).mean():.3f}   "
      f"cond(S_eta) = {(sh_diag.g[0] / sh_diag.g[-1]).item():.3e}   cond(T.matrix) = {torch.linalg.cond(T.matrix).item():.3e}")
del I_d

# ---- diagnostics: enrichment ratios ----
g_top = sh_diag.g[:10].tolist()
print(f"\nenrichment ratios g (eta = {ETA:g}; directions the target does not use sit at g = eta): top 10 = {', '.join(f'{v:.2f}' for v in g_top)}")
print(f"directions with g > 1: {int((sh_diag.g > 1).sum())} / {D_MODEL}   g > 2: {int((sh_diag.g > 2).sum())}   "
      f"stretch range applied: g^(gamma/2) in [{sh_diag.g[-1].item() ** (GAMMA / 2):.3f}, {sh_diag.g[0].item() ** (GAMMA / 2):.3f}]")

# ---- diagnostics: contrastive PCA on the whitened Wikipedia background types ----
N_CPCA, N_CPCA_TOK = 5, 15
WIKI_TYPES_PATH = WH_DIR / "bg_wiki_types.json"
if WIKI_TYPES_PATH.exists():
    wiki_ids = [int(t) for t in json.loads(WIKI_TYPES_PATH.read_text()) if 0 <= int(t) < VOCAB_SIZE]
    P5 = sh_diag.P[:, :N_CPCA]                                         # (d, 5)
    signs = torch.sign(m_tilde @ P5)                                   # orient each p_j towards the target mean
    signs[signs == 0] = 1.0
    M5 = bw.W @ (P5 * signs)                                           # whiten + project in one (d, 5) map
    scores = torch.cat([(E.index_select(0, torch.tensor(wiki_ids[i:i + 20_000], device=E.device)).detach().double().cpu()
                         - bw.mu) @ M5 for i in range(0, len(wiki_ids), 20_000)])   # (N_wiki, 5)
    cpca = {}
    for j in range(N_CPCA):
        top = torch.argsort(scores[:, j], descending=True)[:N_CPCA_TOK].tolist()
        toks = tokenizer.convert_ids_to_tokens([wiki_ids[i] for i in top])
        cpca[f"p{j + 1} (g={sh_diag.g[j]:.2f})"] = [f"{t}{' *' if wiki_ids[i] in target_set else ''}  {scores[i, j]:.2f}"
                                                   for t, i in zip(toks, top)]
    hit = {k: sum(s.split("  ")[0].endswith(" *") for s in v) for k, v in cpca.items()}
    print(f"\ncPCA: top {N_CPCA_TOK} of {len(wiki_ids)} whitened Wikipedia types on p_1..p_{N_CPCA} "
          f"(* = in the target set; per direction: {hit})")
    cpca_df = pd.DataFrame(cpca)
    cpca_df.index += 1
    display(cpca_df)
    del scores
else:
    print(f"\n{WIKI_TYPES_PATH} not found: cPCA diagnostic skipped")

print(f"\nA (transformed): {tuple(A.shape)}   A0 (raw): {tuple(A0.shape)}")

background wiki: n = 107472 types, d = 2304, eps = 0.0001 x mean(lam) = 2.712e-04
W Sigma_B W ~ I: max |lam/(lam+eps) - 1| over the top 95% of directions = 3.525e-04, overall = 2.512e-02 (the smallest eigenvalues are damped by eps on purpose)
cond(Sigma_B) = 3.314e+04   cond(Sigma_B + eps I) = 3.231e+04
|target| = 3124 (page)   in V*: 2592 / 4780   concept-only T_C covered: 1832 / 1870
inverse: max |T.matrix @ (Sm @ W_inv) - I| = 2.50e-14
row norms: raw mean 81.424   X-space mean 61.443   cond(S_eta) = 2.394e+02   cond(T.matrix) = 3.805e+02

enrichment ratios g (eta = 0.05; directions the target does not use sit at g = eta): top 10 = 14.20, 9.84, 8.65, 7.86, 7.74, 7.12, 6.44, 6.18, 5.94, 5.67
directions with g > 1: 892 / 2304   g > 2: 367   stretch range applied: g^(gamma/2) in [0.244, 3.768]

experiments/whitening/data/gemma/bg_wiki_types.json not found: cPCA diagnostic skipped

A (transformed): (2304, 4780)   A0 (raw): (2304, 4780)

### 3.1.d Fit variable-width sparse MF (`fit_varwidth`, variant `rn`)

The shared loop of `experiments/varwidth/core.py`, one iteration ($\lambda$ = `CFG.ridge`):

$$Z \leftarrow A Y^\top (Y Y^\top + \lambda I)^{-1},\qquad Y^{dense} \leftarrow (Z^\top Z + \lambda I)^{-1} Z^\top A,\qquad
S \leftarrow \text{Allocate}(Y^{dense}, Z),\qquad Y \leftarrow Y^{dense}\odot S$$

then the rows of $Y$ are scaled to unit norm (the scale goes into $Z$'s columns). Initialization is the paper's $\mathcal N(0,1)$ from a
generator seeded with `SEED`.

**Allocation rule of this variant.** **rn, row-normalized pooling.** The score of entry $(i,t)$ is $|Y^{dense}_{i,t}| / \|Y^{dense}_{i,:}\|$, so features compete on the shape of their rows, not their scale. One global pool keeps exactly $K = \lceil 0.01\,|V^*|\rceil\cdot k$ entries, each feature within $[m_{min}, m_{max}] = [\lceil 0.002\,|V^*|\rceil, \lceil 0.03\,|V^*|\rceil]$ (same floor/cap pooling as m1).

**Refit is off** (`refit=False`): the kept entries keep their dense values, $Y = Y^{dense}\odot S$, as in the paper; there is no
least-squares refit on the support.

**Stopping:** after `patience` = 200 iterations in which the relative error did not improve by ≥ `tol` = $10^{-4}$ **and** the
support churn stayed below 0.005; otherwise at `max_iter` = 20,000. The final iterate is returned.

`A` is $X^\top$ from 3.1.c′. The fit is cached in `RUN_DIR/fit.pt` (the `fit_varwidth` dict, the schema of `results/varwidth/*/fit.pt`,
plus a `meta` key); a cache made with another configuration (or another $V^*$) is moved aside as `*.stale` with the judge and summary
caches. If the experiments' run of the same config exists, the cell prints how far this fit is from it.

In [9]:
# Resume: RUN_DIR/fit.pt is loaded when its configuration matches; otherwise it (and the caches built on it) are moved aside.
from experiments.varwidth.common import run_dir as vw_run_dir

FIT_PATH = RUN_DIR / "fit.pt"
fit_meta = {"model": MODEL_NAME, "matrix": "whitened", "vstar_ids": vstar_ids, "background": BACKGROUND, "target": TARGET,
            "gamma": GAMMA, "eta": ETA, "eps_rel": EPS_REL, "n_target": len(target_ids), "config": CFG.to_dict(), "seed": SEED}
fit = torch.load(FIT_PATH, weights_only=False) if FIT_PATH.exists() else None
if fit is not None and fit.get("meta") != fit_meta:
    print(f"{FIT_PATH} was made with another configuration: re-fitting")
    invalidate(RUN_DIR, ["fit.pt", "judge.json", "summary.json"])
    fit = None
if fit is not None:
    print(f"loaded {FIT_PATH}")
else:
    fit = fit_varwidth(A, CFG, seed=SEED, device=DEVICE)
    fit["meta"] = fit_meta
    torch.save(fit, FIT_PATH)

Z = fit["Z"].float().cpu()      # (d, k)      X-space features z~_i (columns)
Y = fit["Y"].float().cpu()      # (k, |V*|)   sparse coefficients, variable width per row
widths = (Y != 0).sum(1)        # (k,)        tokens per feature
ridge_used = CFG.ridge          # fit_varwidth has no ridge back-off; 3.2.g reuses lambda
t_fit = {"elapsed": fit["elapsed"]}
print(f"\nfitted in {t_fit['elapsed']:.1f}s ({fit['n_iter']} iterations, stop: {fit['stop_reason']}, "
      f"lock-in at iteration {fit['lockin_iter']})  Z: {tuple(Z.shape)}  Y: {tuple(Y.shape)}  rel_err={fit['rel_err']:.4f}")

# Same run in the experiments (python -m experiments.varwidth.run ...): results/varwidth/<concept>/<tag>/seed<N>/fit.pt
EXP_FIT_PATH = vw_run_dir(CONCEPT, CFG.tag(), SEED) / "fit.pt"
if EXP_FIT_PATH.exists() and not SMOKE:
    _exp = torch.load(EXP_FIT_PATH, weights_only=False)
    print(f"experiments' fit {EXP_FIT_PATH}: rel_err={_exp['rel_err']:.4f}  n_iter={_exp['n_iter']}  "
          f"max|dZ|={(Z - _exp['Z'].float()).abs().max():.2e}  max|dY|={(Y - _exp['Y'].float()).abs().max():.2e}  "
          f"same supports: {torch.equal(Y != 0, _exp['Y'] != 0)}")
    del _exp
else:
    print(f"(no experiments' fit at {EXP_FIT_PATH} to compare with)")

fitted in 52.1s (527 iterations, stop: converged, lock-in at iteration 37)  Z: (2304, 100)  Y: (100, 4780)  rel_err=0.8528
experiments' fit /home/morg/NLP_2526b/oripetel/nlp_proj/nlp_proj/results/varwidth/Harry_Potter/rn_refit-False/seed42/fit.pt: rel_err=0.8528  n_iter=527  max|dZ|=5.87e-04  max|dY|=3.40e-06  same supports: True

#### 3.1.d-w Per-feature widths

The width of feature $i$ is the number of tokens with $Y_{i,t}\neq 0$. For `fixed` all widths are equal; for the other variants
the total is $K$ and each width lies in $[m_{min}, m_{max}]$. The widths of the concept features $F_C$ are shown in 3.2.f, after selection.

In [10]:
w = widths.double()
print(f"[{VARIANT}] widths: min={int(widths.min())}  median={int(widths.median())}  mean={w.mean():.1f}  max={int(widths.max())}  "
      f"sum={int(widths.sum())} (K = {K_BUDGET})  bounds [{M_MIN}, {M_MAX}]" + ("  (fixed: bounds unused)" if CFG.method == "fixed" else ""))
print(f"features at the floor: {int((widths == M_MIN).sum())}   at the cap: {int((widths == M_MAX).sum())}   "
      f"quantiles: " + "  ".join(f"q{int(q * 100)}={w.quantile(q):.0f}" for q in (0.1, 0.25, 0.5, 0.75, 0.9)))
_order = torch.sort(widths, descending=True, stable=True).indices.tolist()
print("widest 10 :", ", ".join(f"{f}:{int(widths[f])}" for f in _order[:10]))
print("narrowest 10:", ", ".join(f"{f}:{int(widths[f])}" for f in _order[::-1][:10]))
if widths.min() < widths.max():
    print("\nhistogram of widths:")
    print(pd.cut(widths.numpy(), bins=min(15, int(widths.max() - widths.min()) + 1)).value_counts().sort_index().to_string())

[rn] widths: min=10  median=37  mean=48.0  max=187  sum=4800 (K = 4800)  bounds [10, 239]
features at the floor: 1   at the cap: 0   quantiles: q10=22  q25=28  q50=38  q75=52  q90=94
widest 10 : 66:187, 77:143, 9:139, 59:135, 60:132, 33:124, 49:118, 86:108, 48:100, 98:98
narrowest 10: 39:10, 95:11, 62:16, 71:17, 19:17, 57:18, 22:18, 36:19, 58:20, 20:20

histogram of widths:
(9.823, 21.8]     10
(21.8, 33.6]      29
(33.6, 45.4]      30
(45.4, 57.2]       9
(57.2, 69.0]       5
(69.0, 80.8]       2
(80.8, 92.6]       3
(92.6, 104.4]      4
(104.4, 116.2]     1
(116.2, 128.0]     2
(128.0, 139.8]     3
(139.8, 151.6]     1
(151.6, 163.4]     0
(163.4, 175.2]     0
(175.2, 187.0]     1

### 3.1.d′ Reference fit on the original (untransformed) matrix

The **same method and config** (`CFG`, variant `rn`) and seed, `fit_varwidth(A0, CFG, seed=SEED)`, on the raw $A_0 = E_{V^*}^\top$
(prep's `"plain"` matrix; the experiments' `<tag>_plain` runs). `Z0` and `Y0` are used only for comparison: 3.1.e/f (errors),
3.2.e′ (the raw fit's $\rho\ge\tau$ candidates, **no Gemini calls**) and 3.2.w (feature matching). Cached in `RUN_DIR/fit0.pt`.

In [11]:
FIT0_PATH = RUN_DIR / "fit0.pt"
fit0_meta = {"model": MODEL_NAME, "matrix": "plain", "vstar_ids": vstar_ids, "config": CFG.to_dict(), "seed": SEED}
fit0 = torch.load(FIT0_PATH, weights_only=False) if FIT0_PATH.exists() else None
if fit0 is not None and fit0.get("meta") != fit0_meta:
    print(f"{FIT0_PATH} was made with another configuration: re-fitting")
    invalidate(RUN_DIR, ["fit0.pt"])
    fit0 = None
if fit0 is not None:
    print(f"loaded {FIT0_PATH}")
else:
    fit0 = fit_varwidth(A0, CFG, seed=SEED, device=DEVICE)
    fit0["meta"] = fit0_meta
    torch.save(fit0, FIT0_PATH)

Z0 = fit0["Z"].float().cpu()    # (d, k)      raw-space features
Y0 = fit0["Y"].float().cpu()    # (k, |V*|)   sparse coefficients
widths0 = (Y0 != 0).sum(1)      # (k,)
t_fit0 = {"elapsed": fit0["elapsed"]}
print(f"\nfitted in {t_fit0['elapsed']:.1f}s ({fit0['n_iter']} iterations, stop: {fit0['stop_reason']})  "
      f"Z0: {tuple(Z0.shape)}  Y0: {tuple(Y0.shape)}  rel_err={fit0['rel_err']:.4f}")
print(f"widths0: min={int(widths0.min())}  median={int(widths0.median())}  max={int(widths0.max())}  sum={int(widths0.sum())}")

EXP_FIT0_PATH = vw_run_dir(CONCEPT, CFG.tag() + "_plain", SEED) / "fit.pt"
if EXP_FIT0_PATH.exists() and not SMOKE:
    _exp = torch.load(EXP_FIT0_PATH, weights_only=False)
    print(f"experiments' fit {EXP_FIT0_PATH}: rel_err={_exp['rel_err']:.4f}  max|dY0|={(Y0 - _exp['Y'].float()).abs().max():.2e}  "
          f"same supports: {torch.equal(Y0 != 0, _exp['Y'] != 0)}")
    del _exp

fitted in 51.9s (474 iterations, stop: converged)  Z0: (2304, 100)  Y0: (100, 4780)  rel_err=0.9049
widths0: min=11  median=36  max=178  sum=4800

### 3.1.e Check the factorization

Reconstruction quality and sparsity. The features use $K$ tokens in total: exactly $\lceil s|V^*|\rceil$ each for `fixed`,
otherwise between $m_{min}$ and $m_{max}$. Tokens that no feature covers are left as pure reconstruction error $\boldsymbol\varepsilon_t$.

Both fits are reported, each against its own data matrix. The two errors are not comparable in absolute terms: whitening
flattens the spectrum, so the transformed error is higher for any rank-$k$ model (the SVD baseline in 3.1.f shows by how much).

The second cell is the optional check of Instructions step 6: $|\cos(\tilde{\mathbf z}_i, \tilde{\mathbf m})|$ between each fitted factor
and the target mean in X-space ($\tilde{\mathbf m} = $ `m_X`). Concept factors should be among the highest; low values flag generic factors.

In [12]:
A_cpu, A0_cpu = A.cpu(), A0.cpu()
rel_err = (torch.norm(A_cpu - Z @ Y) / torch.norm(A_cpu)).item()        # transformed fit, X-space
rel_err0 = (torch.norm(A0_cpu - Z0 @ Y0) / torch.norm(A0_cpu)).item()   # original fit, raw space
nz = Y.abs() > 0
nz0 = Y0.abs() > 0

for name, err, mask in [("transformed", rel_err, nz), ("original", rel_err0, nz0)]:
    tokens_per_feature, features_per_token = mask.sum(1), mask.sum(0)
    print(f"[{name}] relative reconstruction error ||A - ZY||_F / ||A||_F = {err:.4f}")
    print(f"[{name}] tokens per feature : min={tokens_per_feature.min().item()}  median={int(tokens_per_feature.median())}  "
          f"max={tokens_per_feature.max().item()}  total={int(tokens_per_feature.sum())}")
    print(f"[{name}] features per token : mean={features_per_token.float().mean():.2f}  "
          f"max={features_per_token.max().item()}  uncovered tokens={int((features_per_token == 0).sum())}\n")

[transformed] relative reconstruction error ||A - ZY||_F / ||A||_F = 0.8529
[transformed] tokens per feature : min=10  median=37  max=187  total=4800
[transformed] features per token : mean=1.00  max=34  uncovered tokens=2122

[original] relative reconstruction error ||A - ZY||_F / ||A||_F = 0.9047
[original] tokens per feature : min=11  median=36  max=178  total=4800
[original] features per token : mean=1.00  max=5  uncovered tokens=1186

In [13]:
# Instructions step 6 (optional check): |cos| of each X-space factor with the target mean m_X.
cos_m = F.cosine_similarity(Z.double(), m_X.unsqueeze(1), dim=0).abs()       # (k,)
cos_m_order = torch.argsort(cos_m, descending=True).tolist()
print(f"|cos(z~_i, m_X)|: median={cos_m.median():.3f}  max={cos_m.max():.3f}  "
      f"(random-direction scale ~ {math.sqrt(2 / (math.pi * D_MODEL)):.3f})")
cos_m_df = pd.DataFrame({
    "feature": cos_m_order[:10],
    "|cos(z~, m_X)|": cos_m[cos_m_order[:10]].numpy(),
    "top tokens": [", ".join(tokenizer.convert_ids_to_tokens(
        [vstar_ids[j] for j in torch.argsort(Y[f].abs(), descending=True)[:8].tolist()])) for f in cos_m_order[:10]],
})
cos_m_df

|cos(z~_i, m_X)|: median=0.181  max=0.545  (random-direction scale ~ 0.017)

,feature,"|cos(z~, m_X)|",top tokens
0,66,0.545408,"▁site, ▁name, ▁question, ▁line, ▁type, ▁process, ▁area, ▁style"
1,60,0.525780,"▁high, ▁great, ▁big, ▁major, high, ▁strong, ▁large, ▁long"
2,94,0.493754,"▁about, about, About, ▁around, ▁approximately, ▁concerning, ▁roughly, ffindor"
3,96,0.492697,"about, ▁about, About, ▁in, ▁with, ▁approximately, ▁within, ▁alongside"
4,77,0.449740,"▁known, ▁designed, ▁created, ▁named, ▁called, ▁chosen, ▁defined, ▁presented"
5,9,0.423924,"▁remain, ▁take, ▁have, ▁stay, ▁receive, ▁serve, ▁hold, ▁continue"
6,64,0.405560,"▁the, the, The, ▁The, ▁there, ▁those, ▁their, ▁these"
7,93,0.405535,"▁may, ▁might, ▁can, ▁could, ▁will, ▁would, ▁should, ▁are"
8,59,0.393011,"5, 2, 6, 8, 9, 4, 3, 7"
9,49,0.386324,"▁speaking, ▁saying, ▁coming, ▁talking, ▁being, ▁showing, ▁taking, ▁stating"

In [14]:
print(Z.size())
print(Y.size())
print(RANK)

torch.Size([2304, 100])
torch.Size([100, 4780])
100

### 3.1.f Baseline: truncated SVD with the same $k$

The rank-$k$ truncated SVD $A_k = U_k \Sigma_k V_k^\top$ is the best possible rank-$k$ approximation
(Eckart–Young theorem), so no rank-$k$ factorization can have a lower error, including Sparse MF.
The gap between the two errors is what the sparsity of $Y$ costs in reconstruction.

In [15]:
for name, A_mat, err, mask, Z_mat in [("transformed", A_cpu, rel_err, nz, Z), ("original", A0_cpu, rel_err0, nz0, Z0)]:
    U, S, Vh = torch.linalg.svd(A_mat, full_matrices=False)
    A_svd = U[:, :RANK] @ torch.diag(S[:RANK]) @ Vh[:RANK]
    svd_rel_err = (torch.norm(A_mat - A_svd) / torch.norm(A_mat)).item()

    svd_nnz = U[:, :RANK].numel() + RANK + Vh[:RANK].numel()
    smf_nnz = Z_mat.numel() + int(mask.sum())
    print(f"[{name}] rank-{RANK} truncated SVD : relative error = {svd_rel_err:.4f}   (parameters: {svd_nnz:,})")
    print(f"[{name}] rank-{RANK} Sparse MF     : relative error = {err:.4f}   (nonzero parameters: {smf_nnz:,})")

    # Smallest SVD rank whose error is no worse than Sparse MF's.
    tail = torch.sqrt(torch.flip(torch.cumsum(torch.flip(S ** 2, [0]), 0), [0]) / (S ** 2).sum())
    matching_rank = int((tail <= err).nonzero()[0]) if (tail <= err).any() else len(S)
    print(f"[{name}] SVD reaches the Sparse MF error ({err:.4f}) at rank {matching_rank}\n")
del U, S, Vh, A_svd

[transformed] rank-100 truncated SVD : relative error = 0.7917   (parameters: 708,500)
[transformed] rank-100 Sparse MF     : relative error = 0.8529   (nonzero parameters: 235,200)
[transformed] SVD reaches the Sparse MF error (0.8529) at rank 52

[original] rank-100 truncated SVD : relative error = 0.8219   (parameters: 708,500)
[original] rank-100 Sparse MF     : relative error = 0.9047   (nonzero parameters: 235,200)
[original] SVD reaches the Sparse MF error (0.9047) at rank 8

---
# Step 3.2: Identifying concept-related features

Most of the $k$ features are general (punctuation, function words, and so on). The selection runs in two filters:

1. **Mass ratio** $\rho_i$: is feature $i$ used mostly by concept tokens rather than neutral tokens? Keep the feature if $\rho_i \ge \tau = 2.0$.
2. **LLM judge** (Gemini, two stages): describe the feature's tokens *without* seeing the concept name,
   then ask whether that description is the concept. Keep the feature if `is_member` is true and confidence ≥ 0.85.

The features that pass both filters form $F_C$.

### 3.2.a Label every token in $V^*$

$\ell_t \in$ {concept, neutral, both}, depending on whether $t$ appears in $S_C$ only, $S_N$ only, or both.
Codes: `1` = concept, `0` = neutral, `2` = both.

In [16]:
token_to_code = build_token_label_codes(CONCEPT, dataset, tokenizer)
codes = np.array([token_to_code.get(t, 0) for t in vstar_ids])

print(f"T_C (concept-only) = {(codes == 1).sum()}   T_N (neutral-only) = {(codes == 0).sum()}   "
      f"both = {(codes == 2).sum()}")

T_C (concept-only) = 1870   T_N (neutral-only) = 2229   both = 681

### 3.2.b Score features by mass ratio and keep $\rho_i \ge \tau$

As implemented in `compute_embedding_stats` (column `ratio_abs`):

$$\rho_i = \frac{\operatorname{mean}_{t\in T_C} |Y_{i,t}|}{\operatorname{mean}_{t\in T_N} |Y_{i,t}|}$$

Tokens labeled *both* are excluded from the ratio. The threshold sweep below is the per-concept view of
Figure 6 in the paper.

In [17]:
stats = compute_embedding_stats(Y.T, vstar_ids, token_to_code, CONCEPT).sort_values("ratio_abs", ascending=False)

for thr in [1.0, 1.25, 1.5, 1.75, 2.0, 2.25]:
    print(f"rho >= {thr:<4}: {(stats['ratio_abs'] >= thr).sum():3d} / {RANK} features")

candidates = stats[stats["ratio_abs"] >= TAU]
print(f"\n{len(candidates)} candidate features pass tau = {TAU}")
candidates[["feature", "ratio_abs", "mean_abs_concept", "mean_abs_neutral", "num_concept", "num_neutral", "num_both"]]

rho >= 1.0 :  82 / 100 features
rho >= 1.25:  76 / 100 features
rho >= 1.5 :  71 / 100 features
rho >= 1.75:  63 / 100 features
rho >= 2.0 :  57 / 100 features
rho >= 2.25:  51 / 100 features

57 candidate features pass tau = 2.0

,feature,ratio_abs,mean_abs_concept,mean_abs_neutral,num_concept,num_neutral,num_both
88,88,287541.979924,0.002875,0.000000,50,0,11
46,46,44.699388,0.002239,0.000050,34,2,11
31,31,32.300446,0.000756,0.000023,9,1,12
32,32,25.175359,0.001610,0.000064,16,2,4
95,95,22.373198,0.000583,0.000026,5,1,5
44,44,20.405420,0.000993,0.000049,11,2,11
98,98,19.297753,0.003746,0.000194,77,6,15
68,68,18.239010,0.001877,0.000103,30,3,6
25,25,16.212689,0.001560,0.000096,19,2,13
8,8,11.926853,0.001743,0.000146,20,3,5
43,43,10.824707,0.001959,0.000181,24,5,2
17,17,9.253758,0.001938,0.000209,31,7,6
61,61,8.553843,0.001629,0.000190,20,6,6
47,47,8.510178,0.001192,0.000140,16,5,6
12,12,7.318519,0.001203,0.000164,21,6,20
50,50,6.703874,0.001647,0.000246,25,9,10
16,16,6.549108,0.002337,0.000357,50,10,26
86,86,6.475608,0.003896,0.000602,78,17,13
52,52,6.178044,0.000628,0.000102,8,3,21
10,10,5.413480,0.002460,0.000454,40,11,7
3,3,4.700763,0.001840,0.000391,24,10,4
13,13,4.688993,0.001220,0.000260,16,7,10
5,5,4.616347,0.001226,0.000266,20,5,17
9,9,4.555767,0.003541,0.000777,80,24,35
14,14,4.529929,0.002116,0.000467,29,9,7
83,83,4.203337,0.001765,0.000420,23,9,2
59,59,4.165718,0.003300,0.000792,81,27,27
71,71,4.140354,0.001004,0.000242,7,4,6
6,6,4.071793,0.002520,0.000619,43,18,22
38,38,3.981940,0.001094,0.000275,14,7,16
7,7,3.529070,0.001882,0.000533,28,14,11
37,37,3.483264,0.001059,0.000304,11,5,6
87,87,3.468193,0.001065,0.000307,16,6,21
26,26,3.434122,0.001940,0.000565,30,14,19
36,36,3.366060,0.000612,0.000182,5,2,12
28,28,3.361560,0.000909,0.000270,10,6,9
65,65,3.332753,0.001711,0.000513,23,10,4
53,53,3.115132,0.002057,0.000660,32,20,16
49,49,3.060333,0.003307,0.001081,70,31,17
82,82,3.019828,0.001225,0.000406,16,10,9
18,18,2.788840,0.001240,0.000445,21,10,22
0,0,2.748041,0.001152,0.000419,15,11,12
34,34,2.709658,0.001469,0.000542,19,9,7
58,58,2.630105,0.000892,0.000339,11,5,4
24,24,2.628124,0.001195,0.000455,17,10,9
21,21,2.589404,0.000875,0.000338,12,6,19
75,75,2.434641,0.001521,0.000625,29,18,19
90,90,2.384990,0.000515,0.000216,5,7,19
2,2,2.366889,0.000762,0.000322,11,9,11
20,20,2.315133,0.000401,0.000173,5,5,10
29,29,2.300741,0.001063,0.000462,19,12,19
60,60,2.211585,0.002628,0.001188,59,34,39
97,97,2.166296,0.002206,0.001018,41,27,18
93,93,2.127849,0.000841,0.000395,11,9,19
66,66,2.118284,0.002994,0.001413,79,50,58
72,72,2.094348,0.000786,0.000375,13,6,9
64,64,2.067052,0.000401,0.000194,7,6,22

### 3.2.c Collect the tokens the judge will see

For each candidate, the code takes the tokens with nonzero $Y_{i,t}$, sorted by $|Y_{i,t}|$, and keeps the top 20.
The paper text says "concept-labeled tokens", but the released code sends the top activating tokens
whatever their label. This notebook follows the code. The `labels` column shows each token's label.

In [18]:
token_label_map = {tid: "both" if c == 2 else CONCEPT if c == 1 else "Neutral" for tid, c in token_to_code.items()}
feature_rows = collect_feature_rows_for_embeddings(
    Y.T, vstar_ids, token_label_map, tl_model, _safe_model_name(MODEL_NAME), CONCEPT, RANK,
)
feat_tokens = pd.DataFrame(feature_rows).set_index("feature")[["activating_tokens", "labels"]]

cand = candidates[["feature", "ratio_abs"]].join(feat_tokens, on="feature").reset_index(drop=True)
if SMOKE:
    cand = cand.head(3)  # smoke: judge only the 3 highest-rho candidates
from ember.judge_words import desc_sys_prompt, judge_cache_name, judge_items, token_word_counts

DESC_SYS = desc_sys_prompt(JUDGE_FORMAT, multilingual=False)   # = TOKENS_DESC_SYS for "tokens"
jw_counts = token_word_counts(tokenizer, [s for s, _ in dataset]) if JUDGE_FORMAT == "words" else {}


def judge_input(Ymat: torch.Tensor, f: int, activating_tokens) -> list:
    """What Stage 1 sees for feature f of Ymat: "tokens" = the top activating tokens (as before); "words" = token → source words."""
    if JUDGE_FORMAT == "tokens":
        return list(activating_tokens[:TOP_K_TOKENS])
    mags = Ymat[f].abs()
    top = torch.argsort(mags, descending=True)[:TOP_K_TOKENS]
    top = top[mags[top] > 0].tolist()
    return judge_items([vstar_ids[j] for j in top], lambda t: tokenizer.decode([t]), jw_counts, JUDGE_FORMAT,
                       multilingual=False)


cand["judge_tokens"] = [judge_input(Y, int(f), toks) for f, toks in zip(cand["feature"], cand["activating_tokens"])]
cand[["feature", "ratio_abs", "judge_tokens"]]

,feature,ratio_abs,judge_tokens
0,88,287541.979924,"[ffindor, therin, umbledore, Dumbledore, Hogwarts, Weasley, Malfoy, 2, Potter, Hermione, 4, Rowling, Voldemort, Hermione, 3, 8, 6, 5, 1, 7]"
1,46,44.699388,"[ magic, magic, Magic, Magic, magical, magical, Magical, wizard, wizards, witchcraft, Wizard, wizard, Wizards, witch, witches, Witch, 4, 6, 5, 7]"
2,31,32.300446,"[ half, half, Half, 5, 6, 7, 3, 4, 8, 9, 2, 1, 0, full, full, partial, behalf, fifty, ⁄, almost]"
3,32,25.175359,"[ entry, enter, enters, entering, entries, into, reaching, reach, reaches, foray, nter, Entertainment, arrived, joining, returned, infiltr, return, descent, crossed, ently]"
4,95,22.373198,"[ He, his, he, He, His, His, him, himself, zyński, Heli, her]"
5,44,20.405420,"[ read, reads, Read, reading, 3, 6, 7, 4, 5, 8, 1, 2, 9, 0, learn, literacy, ride, listened, learns, write]"
6,98,19.297753,"[ stories, story, fiction, tales, novels, fictional, fiction, novel, Tales, narrative, characters, saga, romance, drama, themes, Novel, myth, character, dramas, fantasy]"
7,68,18.239010,"[ book, book, Book, books, Books, bookstores, novels, ebooks, textbook, novel, read, Novel, reading, chapter, reads, Chapter, Libr, Read, library, author]"
8,25,16.212689,"[ rather, Rather, instead, vs, compared, opposed, against, than, Against, opposed, comparing, 3, 5, 2, 7, 4, 6, Comparing, 8, 1]"
9,8,11.926853,"[ coming, coming, go, goes, going, Go, went, gone, comes, came, Came, gow, follows, follow, move, moving, following, next, got, moved]"
10,43,10.824707,"[ selling, sold, selling, sold, sale, sales, seller, buying, purchasing, marketing, bought, bestselling, market, Vendors, popularity, commercial, popular, revenue, pricing, promotion]"
11,17,9.253758,"[ version, edition, Version, editions, example, instance, rendition, examples, instances, copies, model, models, instalment, interpretation, interpretations, translations, preceden..."
12,61,8.553843,"[ view, see, sees, seen, views, viewed, seeing, viewing, perspective, her, she, visit, opinion, her, Her, She, visits, visited, Her, observing]"
13,47,8.510178,"[ world, World, World, worlds, universe, worldwide, internationally, word, International, nation, Universal, Lord, Lord, words, country, Kingdom, countries, National, earth, national]"
14,12,7.318519,"[ similar, same, identical, Similarly, like, similarities, resemble, resembles, Like, parallels, Unlike, 6, 5, 7, 4, 9, 8, 3, 1, 2]"
15,50,6.703874,"[ writing, written, writing, written, writer, writers, write, wrote, author, authors, scribe, manuscript, novelist, publishing, literary, published, pen, poet, letter, letters]"
16,16,6.549108,"[ said, stated, 3, 5, reported, 4, 2, 6, 1, 8, claimed, 7, 9, noted, reportedly, 0, saying, argues, stating, described]"
17,86,6.475608,"[ gives, takes, goes, comes, allows, becomes, is, assumes, teaches, tells, delivers, involves, serves, speaks, feels, appears, makes, extends, learns, contains]"
18,52,6.178044,"[ every, each, every, all, Each, all, All, 5, 7, 6, 8, 3, 4, 2, 9, 1, 0, alls, any, ever]"
19,10,5.413480,"[ love, loves, likes, loved, Love, Love, like, Like, wants, Wants, hope, dislike, need, desire, know, needs, thought, knew, believe, think]"
20,3,4.700763,"[ find, finding, Find, found, discovering, discovers, discoveries, Discovery, Discovery, learn, learns, uncover, search, encounter, see, encounters, sees, seeing, searched, explore]"
21,13,4.688993,"[ make, making, made, makes, made, mak, makeup, giving, give, gave, gives, creating, set, take, taking, allowed, allowing, sets, allows, put]"
22,5,4.616347,"[ due, because, Due, because, based, Because, based, since, Since, according, instance, attributable, reason, related, therefore, related, though, According, given, Though]"
23,9,4.555767,"[ remain, take, have, stay, receive, serve, hold, continue, become, go, provide, speak, be, attend, participate, teach, assume, rely, occur, do]"
24,14,4.529929,"[ show, show, showing, showed, shown, display, displayed, displays, showcase, showcase, exhibition, depicted, depicting, illustrate, portray, reveal, depiction, portraying, portray..."
25,83,4.203337,"[ death, killed, kills, killing, died, dead, Death, dies, die, murdered, murder, Die, killers, killer, alive, posthum, destroy, destroys, graveyard, massac]"
26,59,4.165718,"[5, 2, 6, 8, 9, 4, 3, 7, 1, issues, topics, 0, examples, items, reasons, aspects, elements, themes, concepts, details]"
27,71,4.140354,"[ himself, herself, themselves, myself, him, own, me, self, they, his, us, They, her, alone, me, selt, altogether]"
28,6,4.071793,"[ mainly, primarily, generally, largely, usually, often, predominantly, essentially, larg, invariably, ostensibly, originally, frequently, commonly, initially, actually, particularl..."
29,38,3.981940,"[ however, nonetheless, meanwhile, However, therefore, though, but, thus, Yet, although, still, Though, Though, Still, also, then, now, otherwise, while, Although]"
30,7,3.529070,"[ cast, casting, Cast, Cast, production, Production, productions, actors, actor, producer, caster, filming, film, produced, actress, characters, audition, films, acting, character]"
31,37,3.483264,"[ part, part, Part, parts, Parts, section, sections, aspects, components, partial, segment, chapter, element, Chapter, elements, piece, pieces, member, members, side]"
32,87,3.468193,"[ many, Many, several, Many, numerous, various, Various, few, some, dozens, multiple, 9, 6, 1, 4, 8, 3, 7, Some, 5]"
33,26,3.434122,"[ children, kids, Children, kid, child, Child, young, adults, adult, girls, youth, women, female, Young, younger, youthful, females, boy, Girls, age]"
34,36,3.366060,"[ open, open, Open, opened, opening, closed, 3, 6, 4, 5, 1, 2, 8, 7, 9, 0, enclosed, sealed, op]"
35,28,3.361560,"[ four, seven, six, five, eight, nine, three, four, eleven, two, nineteen, twenty, Five, Three, Nine, Eleven, fifty, Two, several, Ten]"
36,65,3.332753,"[ draw, drawn, drawing, Draw, attracted, attraction, appeal, Drew, art, attractions, artwork, Art, appealing, sketch, artistic, Arts, Arts, watercolour, raw, illustrator]"
37,53,3.115132,"[ old, age, aged, Old, Older, ancient, age, younger, young, Ages, Ancient, modern, contemporary, youthful, Young, contemporary, century, historical, century, centuries]"
38,49,3.060333,"[ speaking, saying, coming, talking, being, showing, taking, stating, having, seeing, doing, using, making, dealing, playing, comparing, representing, holding, attending, wearing]"
39,82,3.019828,"[ include, includes, including, including, included, inclusion, contains, consists, contain, consist, consisting, comprise, involves, incorporates, feature, features, featured, cov..."
40,18,2.788840,"[ no, not, none, no, neither, NO, Not, never, all, only, all, cannot, non, 3, 4, 8, 5, 1, 9, nor]"
41,0,2.748041,"[ years, year, Years, year, months, decades, Year, decade, days, centuries, seasons, century, Days, hours, season, century, day, año, summers, miles]"
42,34,2.709658,"[ most, most, Most, best, fastest, funniest, longest, tiest, liest, Best, ariest, Best, highest, she, largest, her, largest, latest, her, She]"
43,58,2.630105,"[ just, Just, Just, simply, merely, only, Only, even, simple, actually, really, almost, urian, already, alone, shortly, strictly, ęcz, still, lone]"
44,24,2.628124,"[ living, lived, live, lives, lived, life, alive, life, resides, resided, surviving, exist, survived, exists, lively, dwell, working, Lifetime, born, real]"
45,21,2.589404,"[ place, places, Places, placing, placed, locations, location, 5, 4, 8, 6, 9, 1, 7, 3, where, 2, 0, way, ways]"
46,75,2.434641,"[5, 4, 3, 6, 8, 7, 1, 2, 9, press, publication, 0, publishing, media, newspaper, Press, news, publisher, published, publications]"
47,90,2.384990,"[ through, Through, through, by, By, By, though, Though, Though, 7, 4, 5, 6, 3, 1, 8, 2, 9, 0, From]"
48,2,2.366889,"[ fourth, third, fifth, sixth, seventh, second, Second, first, last, First, next, rd, secondary, Forth, final, th, middle, seconds, nd, nineteen]"
49,20,2.315133,"[ they, They, their, them, themselves, Them, this, ich, )[, This, sie, respectively, are, were, duo, los, heir, aban, trio, les]"
50,29,2.300741,"[ other, others, Other, another, Another, more, further, more, otherwise, also, beyond, similar, broader, related, anything, late, neighboring, late, Similarly, even]"
51,60,2.211585,"[ high, great, big, major, high, strong, large, long, important, good, significant, full, main, low, key, primary, High, short, deep, real]"
52,97,2.166296,"[ing, ings, ism, ists, ingly, ist, izing, ments, ising, ment, isation, ations, able, ed, istically, ement, ly, ors, ies, ates]"
53,93,2.127849,"[ may, might, can, could, will, would, should, are, must, is, cannot, were, has, was, does, have, did, do, need, had]"
54,66,2.118284,"[ site, name, question, line, type, process, area, style, section, point, term, issue, list, group, word, form, category, number, order, story]"
55,72,2.094348,"[ such, such, like, example, instance, including, examples, Like, likes, including, tales, instances, precedent, similar, particularly, precedents, so, include, e, exception]"
56,64,2.067052,"[ the, the, The, The, there, those, their, these, this, ffindor, our, There, his, its, of, what, I, how, I, therin]"

### 3.2.d-0 Rate-limited Gemini client

The free tier allows **15 requests per minute per model**. Stage 1 and Stage 2 make one request per
candidate each, so 2 × (number of candidates) requests in total. This wrapper does three things:

- spaces requests at least `60 / RPM` seconds apart (with a 10% margin);
- on a per-minute 429, waits the `retry in Ns` delay the server reports, then retries;
- fails immediately on a *daily* quota error, because waiting would not help.

Answers are cached in `descriptions` and `verdicts`. Re-running a stage only queries the features that
are still missing, so a crash never wastes quota you already spent.

In [19]:
import re
import time

GEMINI_RPM = 15


class ThrottledGemini:
    def __init__(self, inner: SimpleGeminiClient, rpm: int = GEMINI_RPM, max_attempts: int = 6):
        inner.max_retries = 1  # retries are handled here, with the server's retry delay
        self.inner = inner
        self.interval = 60.0 / rpm * 1.1
        self.max_attempts = max_attempts
        self._last = 0.0

    def generate(self, prompt: str) -> str:
        for attempt in range(self.max_attempts):
            time.sleep(max(0.0, self._last + self.interval - time.monotonic()))
            self._last = time.monotonic()
            try:
                return self.inner.generate(prompt)
            except RuntimeError as e:
                msg = str(e)
                if "429" not in msg or "PerDay" in msg or attempt == self.max_attempts - 1:
                    raise
                m = re.search(r"retry in ([\d.]+)s", msg)
                time.sleep(float(m.group(1)) + 1 if m else 60)


USE_THROTTLE = False  # billing enabled; set True to go back to free-tier pacing

if USE_THROTTLE:
    client = ThrottledGemini(SimpleGeminiClient(model_name=GEMINI_MODEL))
else:
    client = SimpleGeminiClient(model_name=GEMINI_MODEL)

# Persisted in RUN_DIR/judge.json, saved after every Gemini call, so a restart re-queries nothing.
# 3.1.d moves judge.json aside whenever it re-fits.
JUDGE_PATH = RUN_DIR / judge_cache_name(JUDGE_FORMAT, "tokens")   # judge.json for the original format
_judge = load_json(JUDGE_PATH, {})
descriptions = {int(f): d for f, d in _judge.get("descriptions", {}).items()}
verdicts = {int(f): tuple(v) for f, v in _judge.get("verdicts", {}).items()}


def save_judge() -> None:
    save_json(JUDGE_PATH, {"descriptions": descriptions, "verdicts": verdicts})

print(f"{2 * len(cand)} requests needed, {len(descriptions)} descriptions and {len(verdicts)} verdicts cached; "
      f"throttle={'on' if USE_THROTTLE else 'off'}")

114 requests needed, 0 descriptions and 0 verdicts cached; throttle=off

### 3.2.d LLM judge, stage 1: describe each feature *without* the concept name

Stage 1 never sees the concept name. This avoids confirmation bias, where tokens like *wizard* could
look like "Harry Potter" just because the judge was told the concept.

In [20]:
print("---- Stage 1 prompt ----")
print(TOKENS_DESC_SYS.strip(), "\n\nTokens: {tokens}\nExplanation of feature behavior:")

todo = cand[~cand["feature"].astype(int).isin(descriptions)]
for _, row in tqdm(todo.iterrows(), total=len(todo), desc="Stage 1: describe"):
    descriptions[int(row["feature"])] = get_description(client, row["judge_tokens"], sys_prompt=DESC_SYS)
    save_judge()
cand["description"] = cand["feature"].map(descriptions)
cand[["feature", "ratio_abs", "description"]]

---- Stage 1 prompt ----
You get tokens that represent a single feature vector (with some noise).
Infer the single most specific, cohesive concept shared by the relevant tokens.
Return only one concise sentence. No preface, no list, no caveats.

Example:
Tokens: ['▁tomorrow','▁tonight','▁yesterday','▁today','▁demain']
Explanation of feature behavior: this vector is related to specific dates and times (e.g., today/tomorrow/yesterday).

Tokens: {tokens}
Explanation of feature behavior:

Stage 1: describe: 100%|██████████| 57/57 [00:36<00:00,  1.57it/s]

,feature,ratio_abs,description
0,88,287541.979924,The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
1,46,44.699388,"This feature vector activates strongly in contexts involving magic, wizards, and witchcraft."
2,31,32.300446,"This vector represents numerical digits, fractions, and quantifiers denoting portions or amounts."
3,32,25.175359,"This feature activates for words related to physical or conceptual movement, arrival, and entry."
4,95,22.373198,This vector is related to third-person masculine singular personal and possessive pronouns.
5,44,20.405420,"This vector represents numbers and actions related to learning, literacy, and communication."
6,98,19.297753,"This vector is related to written or spoken works of creative literature, narrative, and storytelling."
7,68,18.239010,"This feature vector represents the concept of literature, books, and the act of reading."
8,25,16.212689,"This vector is related to contrast, comparison, and alternative options, occasionally blending with numeric digits."
9,8,11.926853,This vector represents verbs of physical motion and directional progression.
10,43,10.824707,"This vector represents commercial transactions, trade, and the buying and selling of goods or services."
11,17,9.253758,"This vector represents distinct iterations, occurrences, or variations of a particular entity or work."
12,61,8.553843,"This feature vector represents the concept of visual perception, observation, and feminine third-person reference."
13,47,8.510178,"This vector is related to global, planetary, and national geographical or geopolitical entities and concepts."
14,12,7.318519,"This vector represents concepts of comparison, similarity, and numerical digits."
15,50,6.703874,"This vector represents concepts and terminology related to the act, tools, and professions of writing and literature."
16,16,6.549108,This vector activates for communication verbs and numeric digits often used to attribute statements and data.
17,86,6.475608,This vector represents singular third-person present tense action verbs.
18,52,6.178044,"This vector represents quantification, totality, and numeric digits."
19,10,5.413480,"This vector represents common present and past tense mental, emotional, and preference-based action verbs."
20,3,4.700763,"The vector represents the concept of searching for, discovering, and encountering information or objects."
21,13,4.688993,This vector represents common transitive action verbs across various conjugations and tenses.
22,5,4.616347,"This vector represents causal relationships, justifications, and logical connections between events or statements."
23,9,4.555767,"These tokens represent core action verbs encompassing states of being, occurrences, and dynamic activities."
24,14,4.529929,"This vector is related to displaying, presenting, or visually representing something."
25,83,4.203337,"This vector represents the concepts of mortality, death, and killing."
26,59,4.165718,"The feature vector represents plural nouns and numerals denoting countable items, subjects, or quantities."
27,71,4.140354,This vector represents reflexive and personal pronouns related to self-reference and identity.
28,6,4.071793,"This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement."
29,38,3.981940,"These tokens function as transitional adverbs and conjunctions used to connect clauses and indicate logical relationships like contrast, consequence, or time."
30,7,3.529070,"This vector represents the concept of film and theatrical casting, production, and acting."
31,37,3.483264,"This vector represents sub-units, components, or divisions of a whole."
32,87,3.468193,"This vector represents quantification, encompassing words and numerals that denote amounts, numbers, and frequencies."
33,26,3.434122,This vector represents human demographic categories related to age and gender.
34,36,3.366060,"This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities."
35,28,3.361560,This vector represents numeric quantity words and number names.
36,65,3.332753,"This feature vector represents the concepts of drawing, visual art, and aesthetic attraction."
37,53,3.115132,"This vector represents the concept of time, age, and historical epochs."
38,49,3.060333,This feature vector activates strongly on present participles and continuous action verbs.
39,82,3.019828,"This feature vector activates on verbs and grammatical forms associated with containment, inclusion, and the listing of component parts."
40,18,2.788840,This feature activates for explicit negation words and negative prefixes.
41,0,2.748041,This vector represents units of time and temporal duration.
42,34,2.709658,This vector encodes superlative adjectives and third-person singular feminine pronouns.
43,58,2.630105,"This feature vector represents restrictive or limiting adverbs and modifiers emphasizing exclusivity, degree, or exactness."
44,24,2.628124,"This vector is related to the concepts of living, existence, and vitality."
45,21,2.589404,"This feature vector activates on tokens related to numerical digits, specific quantities, and spatial positioning or locations."
46,75,2.434641,"This vector represents the concept of the news and publishing industry, encompassing digits, media, and printed matter."
47,90,2.384990,This vector represents common grammatical prepositions and numerals.
48,2,2.366889,This vector represents ordinal numbers and sequential positions in a series.
49,20,2.315133,This feature vector represents third-person plural pronouns and related grammatical markers across multiple languages.
50,29,2.300741,"This feature activates for words indicating addition, alternative options, or concepts related to ""otherness"" and extension."
51,60,2.211585,"These tokens represent primary adjectives of scale, intensity, importance, and value."
52,97,2.166296,"These tokens represent common English derivational suffixes used to form nouns, verbs, adjectives, and adverbs."
53,93,2.127849,"These tokens represent modal and auxiliary verbs used to express tense, possibility, necessity, or grammatical mood."
54,66,2.118284,"This vector represents common, abstract nouns used to categorize or describe general concepts and entities."
55,72,2.094348,"This feature activates on words and phrases used to introduce examples, similarities, or illustrations."
56,64,2.067052,"This vector activates on common English pronouns, articles, and determiners, with some noisy subword fragments."

In [21]:
N_SHOW = 10
LABEL_TAG = {1: "C", 0: "N", 2: "B"}  # concept / neutral / both

for _, row in cand.sort_values("ratio_abs", ascending=False).iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini : {descriptions.get(feat, '<not described yet>')}")
    print("  tokens : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

=== feature 88  width=61  rho=287541.98 ===
  Gemini : The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
  tokens : 'ffindor'[C] 0.31, 'therin'[C] 0.26, 'umbledore'[C] 0.21, '▁Dumbledore'[C] 0.19, '▁Hogwarts'[C] 0.18, '▁Weasley'[C] 0.18, '▁Malfoy'[C] 0.17, '2'[B] 0.17, '▁Potter'[C] 0.17, 'Hermione'[C] 0.16

=== feature 46  width=47  rho=44.70 ===
  Gemini : This feature vector activates strongly in contexts involving magic, wizards, and witchcraft.
  tokens : '▁magic'[C] 0.34, 'magic'[C] 0.33, 'Magic'[C] 0.32, '▁Magic'[B] 0.32, '▁magical'[C] 0.26, 'magical'[C] 0.24, '▁Magical'[C] 0.22, '▁wizard'[C] 0.17, '▁wizards'[C] 0.17, '▁witchcraft'[C] 0.15

=== feature 31  width=22  rho=32.30 ===
  Gemini : This vector represents numerical digits, fractions, and quantifiers denoting portions or amounts.
  tokens : '▁half'[C] 0.39, 'half'[B] 0.38, '▁Half'[C] 0.36, '5'[B] 0.25, '6'[B] 0.23, '7'[B] 0.22, '3'[B] 0.22, '4'[B] 0.22, '8'[B] 0.22, '9'[B] 0.22

=== feature 32  width=22  rho=25.18 ===
  Gemini : This feature activates for words related to physical or conceptual movement, arrival, and entry.
  tokens : '▁entry'[C] 0.44, '▁enter'[C] 0.43, '▁enters'[C] 0.42, '▁entering'[C] 0.42, '▁entries'[C] 0.38, '▁into'[B] 0.13, '▁reaching'[C] 0.11, '▁reach'[C] 0.11, '▁reaches'[C] 0.11, '▁foray'[C] 0.10

=== feature 95  width=11  rho=22.37 ===
  Gemini : This vector is related to third-person masculine singular personal and possessive pronouns.
  tokens : '▁He'[B] 0.38, '▁his'[B] 0.38, '▁he'[B] 0.37, 'He'[B] 0.36, 'His'[C] 0.35, '▁His'[C] 0.35, '▁him'[B] 0.33, '▁himself'[C] 0.29, 'zyński'[N] 0.06, '▁Heli'[C] 0.05

=== feature 44  width=24  rho=20.41 ===
  Gemini : This vector represents numbers and actions related to learning, literacy, and communication.
  tokens : '▁read'[C] 0.47, '▁reads'[C] 0.40, '▁Read'[C] 0.40, '▁reading'[B] 0.36, '3'[B] 0.18, '6'[B] 0.17, '7'[B] 0.17, '4'[B] 0.17, '5'[B] 0.17, '8'[B] 0.17

=== feature 98  width=98  rho=19.30 ===
  Gemini : This vector is related to written or spoken works of creative literature, narrative, and storytelling.
  tokens : '▁stories'[B] 0.24, '▁story'[B] 0.23, '▁fiction'[C] 0.22, '▁tales'[C] 0.21, '▁novels'[C] 0.17, '▁fictional'[C] 0.17, 'fiction'[C] 0.17, '▁novel'[B] 0.16, '▁Tales'[C] 0.16, '▁narrative'[C] 0.16

=== feature 68  width=39  rho=18.24 ===
  Gemini : This feature vector represents the concept of literature, books, and the act of reading.
  tokens : '▁book'[B] 0.41, 'book'[C] 0.38, '▁Book'[B] 0.37, '▁books'[C] 0.36, '▁Books'[C] 0.33, '▁bookstores'[C] 0.19, '▁novels'[C] 0.15, '▁ebooks'[C] 0.15, '▁textbook'[C] 0.15, '▁novel'[B] 0.14

=== feature 25  width=34  rho=16.21 ===
  Gemini : This vector is related to contrast, comparison, and alternative options, occasionally blending with numeric digits.
  tokens : '▁rather'[C] 0.37, 'Rather'[C] 0.33, '▁instead'[B] 0.29, '▁vs'[C] 0.27, '▁compared'[C] 0.26, '▁opposed'[C] 0.22, '▁against'[B] 0.19, '▁than'[B] 0.19, '▁Against'[C] 0.17, 'opposed'[N] 0.17

=== feature 8  width=28  rho=11.93 ===
  Gemini : This vector represents verbs of physical motion and directional progression.
  tokens : '▁coming'[C] 0.34, 'coming'[C] 0.34, '▁go'[C] 0.33, '▁goes'[B] 0.32, 'going'[C] 0.30, '▁Go'[C] 0.27, '▁went'[B] 0.26, 'gone'[C] 0.25, '▁comes'[C] 0.24, '▁came'[N] 0.22

=== feature 43  width=31  rho=10.82 ===
  Gemini : This vector represents commercial transactions, trade, and the buying and selling of goods or services.
  tokens : '▁selling'[C] 0.38, '▁sold'[C] 0.38, 'selling'[C] 0.35, 'sold'[C] 0.34, '▁sale'[C] 0.34, '▁sales'[B] 0.31, 'seller'[C] 0.24, '▁buying'[C] 0.16, '▁purchasing'[C] 0.14, '▁marketing'[C] 0.13

=== feature 17  width=44  rho=9.25 ===
  Gemini : This vector represents distinct iterations, occurrences, or variations of a particular entity or work.
  tokens : '▁version'[B] 0.42, '▁edition'[B] 0.38, '▁Version'[C] 0.35, '▁editions'[C] 0.33, '▁example'[C] 0.22, '▁instance'[C] 0.22, '▁rendition'[C] 0.21, '▁examples'[C] 0.19, '▁instances'[C] 0.17, '▁copies'[B] 0.16

=== feature 61  width=32  rho=8.55 ===
  Gemini : This feature vector represents the concept of visual perception, observation, and feminine third-person reference.
  tokens : '▁view'[C] 0.37, '▁see'[B] 0.34, '▁sees'[C] 0.33, '▁seen'[C] 0.32, '▁views'[C] 0.32, '▁viewed'[C] 0.31, '▁seeing'[C] 0.30, '▁viewing'[B] 0.27, '▁perspective'[B] 0.13, '▁her'[B] 0.13

=== feature 47  width=27  rho=8.51 ===
  Gemini : This vector is related to global, planetary, and national geographical or geopolitical entities and concepts.
  tokens : '▁world'[B] 0.48, '▁World'[B] 0.46, 'World'[C] 0.45, '▁worlds'[C] 0.37, '▁universe'[C] 0.21, '▁worldwide'[C] 0.21, '▁internationally'[C] 0.16, '▁word'[C] 0.13, '▁International'[C] 0.13, '▁nation'[N] 0.09

=== feature 12  width=47  rho=7.32 ===
  Gemini : This vector represents concepts of comparison, similarity, and numerical digits.
  tokens : '▁similar'[B] 0.39, '▁same'[B] 0.38, '▁identical'[B] 0.29, 'Similarly'[C] 0.28, '▁like'[B] 0.22, '▁similarities'[C] 0.22, '▁resemble'[C] 0.20, '▁resembles'[C] 0.20, 'Like'[B] 0.20, '▁parallels'[C] 0.15

=== feature 50  width=44  rho=6.70 ===
  Gemini : This vector represents concepts and terminology related to the act, tools, and professions of writing and literature.
  tokens : '▁writing'[B] 0.33, '▁written'[B] 0.32, 'writing'[C] 0.31, 'written'[C] 0.30, '▁writer'[B] 0.30, '▁writers'[C] 0.29, '▁write'[C] 0.29, '▁wrote'[B] 0.27, '▁author'[C] 0.19, '▁authors'[C] 0.19

=== feature 16  width=86  rho=6.55 ===
  Gemini : This vector activates for communication verbs and numeric digits often used to attribute statements and data.
  tokens : '▁said'[B] 0.23, '▁stated'[C] 0.21, '3'[B] 0.18, '5'[B] 0.17, '▁reported'[C] 0.17, '4'[B] 0.17, '2'[B] 0.17, '6'[B] 0.17, '1'[B] 0.17, '8'[B] 0.17

=== feature 86  width=108  rho=6.48 ===
  Gemini : This vector represents singular third-person present tense action verbs.
  tokens : '▁gives'[C] 0.15, '▁takes'[C] 0.14, '▁goes'[B] 0.14, '▁comes'[C] 0.14, '▁allows'[C] 0.14, '▁becomes'[B] 0.13, '▁is'[B] 0.13, '▁assumes'[C] 0.13, '▁teaches'[C] 0.13, '▁tells'[C] 0.13

=== feature 52  width=32  rho=6.18 ===
  Gemini : This vector represents quantification, totality, and numeric digits.
  tokens : '▁every'[C] 0.33, '▁each'[B] 0.32, 'every'[C] 0.31, '▁all'[B] 0.30, 'Each'[B] 0.26, 'all'[C] 0.26, 'All'[B] 0.20, '5'[B] 0.20, '7'[B] 0.19, '6'[B] 0.19

=== feature 10  width=58  rho=5.41 ===
  Gemini : This vector represents common present and past tense mental, emotional, and preference-based action verbs.
  tokens : '▁love'[C] 0.34, '▁loves'[C] 0.30, '▁likes'[C] 0.28, '▁loved'[C] 0.26, '▁Love'[N] 0.26, 'Love'[C] 0.25, '▁like'[B] 0.25, 'Like'[B] 0.20, '▁wants'[C] 0.19, '▁Wants'[C] 0.16

=== feature 3  width=38  rho=4.70 ===
  Gemini : The vector represents the concept of searching for, discovering, and encountering information or objects.
  tokens : '▁find'[C] 0.40, '▁finding'[C] 0.38, '▁Find'[C] 0.36, '▁found'[B] 0.31, '▁discovering'[C] 0.28, '▁discovers'[C] 0.26, '▁discoveries'[N] 0.22, 'Discovery'[C] 0.19, '▁Discovery'[N] 0.19, '▁learn'[C] 0.16

=== feature 13  width=33  rho=4.69 ===
  Gemini : This vector represents common transitive action verbs across various conjugations and tenses.
  tokens : '▁make'[B] 0.41, '▁making'[C] 0.40, '▁made'[B] 0.38, '▁makes'[C] 0.38, 'made'[C] 0.35, '▁mak'[C] 0.26, '▁makeup'[N] 0.16, '▁giving'[N] 0.12, 'give'[C] 0.12, '▁gave'[B] 0.12

=== feature 5  width=42  rho=4.62 ===
  Gemini : This vector represents causal relationships, justifications, and logical connections between events or statements.
  tokens : '▁due'[B] 0.40, '▁because'[B] 0.33, 'Due'[C] 0.33, 'because'[C] 0.32, '▁based'[B] 0.28, 'Because'[N] 0.25, 'based'[C] 0.25, '▁since'[B] 0.22, 'Since'[B] 0.15, '▁according'[B] 0.13

=== feature 9  width=139  rho=4.56 ===
  Gemini : These tokens represent core action verbs encompassing states of being, occurrences, and dynamic activities.
  tokens : '▁remain'[C] 0.14, '▁take'[B] 0.14, '▁have'[B] 0.13, '▁stay'[B] 0.13, '▁receive'[C] 0.13, '▁serve'[C] 0.13, '▁hold'[B] 0.13, '▁continue'[C] 0.12, '▁become'[B] 0.12, '▁go'[C] 0.12

=== feature 14  width=45  rho=4.53 ===
  Gemini : This vector is related to displaying, presenting, or visually representing something.
  tokens : '▁show'[N] 0.36, 'show'[C] 0.33, '▁showing'[C] 0.31, '▁showed'[C] 0.29, '▁shown'[C] 0.28, '▁display'[N] 0.24, '▁displayed'[C] 0.23, '▁displays'[C] 0.22, '▁showcase'[C] 0.20, 'showcase'[C] 0.17

=== feature 83  width=34  rho=4.20 ===
  Gemini : This vector represents the concepts of mortality, death, and killing.
  tokens : '▁death'[B] 0.32, '▁killed'[C] 0.32, '▁kills'[C] 0.29, '▁killing'[C] 0.29, '▁died'[B] 0.28, '▁dead'[C] 0.27, '▁Death'[C] 0.27, '▁dies'[C] 0.26, '▁die'[C] 0.25, '▁murdered'[C] 0.21

=== feature 59  width=135  rho=4.17 ===
  Gemini : The feature vector represents plural nouns and numerals denoting countable items, subjects, or quantities.
  tokens : '5'[B] 0.16, '2'[B] 0.16, '6'[B] 0.16, '8'[B] 0.15, '9'[B] 0.15, '4'[B] 0.15, '3'[B] 0.15, '7'[B] 0.15, '1'[B] 0.15, '▁issues'[C] 0.15

=== feature 71  width=17  rho=4.14 ===
  Gemini : This vector represents reflexive and personal pronouns related to self-reference and identity.
  tokens : '▁himself'[C] 0.52, '▁herself'[C] 0.51, '▁themselves'[C] 0.42, '▁myself'[N] 0.35, '▁him'[B] 0.18, '▁own'[B] 0.18, '▁me'[C] 0.13, '▁self'[C] 0.13, '▁they'[B] 0.13, '▁his'[B] 0.12

=== feature 6  width=83  rho=4.07 ===
  Gemini : This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement.
  tokens : '▁mainly'[C] 0.24, '▁primarily'[B] 0.24, '▁generally'[B] 0.24, '▁largely'[B] 0.24, '▁usually'[N] 0.23, '▁often'[C] 0.21, '▁predominantly'[C] 0.20, '▁essentially'[C] 0.20, 'larg'[C] 0.18, '▁invariably'[C] 0.15

=== feature 38  width=37  rho=3.98 ===
  Gemini : These tokens function as transitional adverbs and conjunctions used to connect clauses and indicate logical relationships like contrast, consequence, or time.
  tokens : '▁however'[C] 0.43, '▁nonetheless'[C] 0.32, '▁meanwhile'[C] 0.30, 'However'[B] 0.30, '▁therefore'[B] 0.27, '▁though'[B] 0.27, '▁but'[B] 0.20, '▁thus'[B] 0.19, 'Yet'[C] 0.18, '▁although'[B] 0.16

=== feature 7  width=53  rho=3.53 ===
  Gemini : This vector represents the concept of film and theatrical casting, production, and acting.
  tokens : '▁cast'[C] 0.40, '▁casting'[C] 0.34, 'Cast'[C] 0.32, '▁Cast'[N] 0.31, '▁production'[C] 0.23, 'Production'[C] 0.20, '▁productions'[C] 0.19, '▁actors'[B] 0.17, '▁actor'[B] 0.16, '▁producer'[B] 0.16

=== feature 37  width=22  rho=3.48 ===
  Gemini : This vector represents sub-units, components, or divisions of a whole.
  tokens : '▁part'[B] 0.47, 'part'[C] 0.46, '▁Part'[N] 0.41, '▁parts'[C] 0.39, '▁Parts'[C] 0.34, '▁section'[C] 0.15, '▁sections'[C] 0.15, '▁aspects'[C] 0.10, '▁components'[N] 0.10, '▁partial'[C] 0.09

=== feature 87  width=43  rho=3.47 ===
  Gemini : This vector represents quantification, encompassing words and numerals that denote amounts, numbers, and frequencies.
  tokens : '▁many'[B] 0.34, 'Many'[C] 0.28, '▁several'[B] 0.28, '▁Many'[C] 0.27, '▁numerous'[N] 0.26, '▁various'[B] 0.25, 'Various'[C] 0.24, '▁few'[C] 0.18, '▁some'[B] 0.18, '▁dozens'[C] 0.16

=== feature 26  width=63  rho=3.43 ===
  Gemini : This vector represents human demographic categories related to age and gender.
  tokens : '▁children'[B] 0.28, '▁kids'[C] 0.25, 'Children'[C] 0.23, '▁kid'[C] 0.22, 'child'[C] 0.21, '▁Child'[B] 0.20, '▁young'[B] 0.19, '▁adults'[C] 0.18, '▁adult'[C] 0.18, '▁girls'[N] 0.16

=== feature 36  width=19  rho=3.37 ===
  Gemini : This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities.
  tokens : '▁open'[C] 0.42, 'open'[C] 0.40, '▁Open'[N] 0.35, '▁opened'[B] 0.29, '▁opening'[B] 0.24, '▁closed'[C] 0.21, '3'[B] 0.19, '6'[B] 0.19, '4'[B] 0.19, '5'[B] 0.19

=== feature 28  width=25  rho=3.36 ===
  Gemini : This vector represents numeric quantity words and number names.
  tokens : '▁four'[B] 0.31, '▁seven'[B] 0.30, '▁six'[B] 0.30, '▁five'[B] 0.30, '▁eight'[B] 0.29, '▁nine'[C] 0.29, '▁three'[B] 0.27, 'four'[C] 0.26, '▁eleven'[C] 0.24, '▁two'[B] 0.22

=== feature 65  width=37  rho=3.33 ===
  Gemini : This feature vector represents the concepts of drawing, visual art, and aesthetic attraction.
  tokens : '▁draw'[C] 0.44, '▁drawn'[C] 0.42, '▁drawing'[C] 0.40, 'Draw'[N] 0.35, '▁attracted'[C] 0.22, '▁attraction'[C] 0.20, '▁appeal'[B] 0.16, '▁Drew'[N] 0.15, '▁art'[C] 0.15, '▁attractions'[C] 0.14

=== feature 53  width=68  rho=3.12 ===
  Gemini : This vector represents the concept of time, age, and historical epochs.
  tokens : '▁old'[C] 0.29, '▁age'[B] 0.27, '▁aged'[B] 0.25, '▁Old'[C] 0.23, 'Older'[C] 0.23, '▁ancient'[C] 0.22, 'age'[C] 0.20, '▁younger'[C] 0.20, '▁young'[B] 0.18, '▁Ages'[C] 0.18

=== feature 49  width=118  rho=3.06 ===
  Gemini : This feature vector activates strongly on present participles and continuous action verbs.
  tokens : '▁speaking'[C] 0.18, '▁saying'[C] 0.17, '▁coming'[C] 0.16, '▁talking'[C] 0.16, '▁being'[B] 0.15, '▁showing'[C] 0.15, '▁taking'[C] 0.14, '▁stating'[B] 0.14, '▁having'[N] 0.13, '▁seeing'[C] 0.13

=== feature 82  width=35  rho=3.02 ===
  Gemini : This feature vector activates on verbs and grammatical forms associated with containment, inclusion, and the listing of component parts.
  tokens : '▁include'[B] 0.38, '▁includes'[C] 0.38, '▁including'[B] 0.33, 'including'[C] 0.30, '▁included'[B] 0.29, '▁inclusion'[C] 0.25, '▁contains'[B] 0.21, '▁consists'[N] 0.20, '▁contain'[C] 0.19, '▁consist'[C] 0.19

=== feature 18  width=53  rho=2.79 ===
  Gemini : This feature activates for explicit negation words and negative prefixes.
  tokens : '▁no'[B] 0.37, '▁not'[B] 0.31, '▁none'[C] 0.28, 'no'[B] 0.28, '▁neither'[C] 0.23, '▁NO'[N] 0.19, '▁Not'[N] 0.19, '▁never'[C] 0.18, '▁all'[B] 0.17, '▁only'[B] 0.15

=== feature 0  width=38  rho=2.75 ===
  Gemini : This vector represents units of time and temporal duration.
  tokens : '▁years'[B] 0.36, '▁year'[B] 0.32, '▁Years'[C] 0.31, 'year'[B] 0.27, '▁months'[B] 0.27, '▁decades'[C] 0.27, '▁Year'[C] 0.26, '▁decade'[C] 0.25, '▁days'[C] 0.20, '▁centuries'[N] 0.19

=== feature 34  width=35  rho=2.71 ===
  Gemini : This vector encodes superlative adjectives and third-person singular feminine pronouns.
  tokens : '▁most'[B] 0.39, 'most'[C] 0.38, '▁Most'[N] 0.29, '▁best'[B] 0.26, '▁fastest'[C] 0.20, '▁funniest'[C] 0.20, '▁longest'[C] 0.19, 'tiest'[C] 0.19, 'liest'[C] 0.19, 'Best'[C] 0.19

=== feature 58  width=20  rho=2.63 ===
  Gemini : This feature vector represents restrictive or limiting adverbs and modifiers emphasizing exclusivity, degree, or exactness.
  tokens : '▁just'[B] 0.50, 'Just'[C] 0.41, '▁Just'[N] 0.41, '▁simply'[C] 0.35, '▁merely'[C] 0.34, '▁only'[B] 0.26, '▁Only'[N] 0.19, '▁even'[B] 0.11, '▁simple'[C] 0.10, '▁actually'[C] 0.09

=== feature 24  width=36  rho=2.63 ===
  Gemini : This vector is related to the concepts of living, existence, and vitality.
  tokens : '▁living'[B] 0.43, '▁lived'[C] 0.36, '▁live'[B] 0.34, '▁lives'[C] 0.33, 'lived'[N] 0.28, '▁life'[B] 0.26, '▁alive'[C] 0.25, 'life'[C] 0.23, '▁resides'[C] 0.15, '▁resided'[N] 0.15

=== feature 21  width=37  rho=2.59 ===
  Gemini : This feature vector activates on tokens related to numerical digits, specific quantities, and spatial positioning or locations.
  tokens : '▁place'[B] 0.38, '▁places'[C] 0.37, '▁Places'[N] 0.31, '▁placing'[C] 0.24, '▁placed'[B] 0.24, '▁locations'[C] 0.22, '▁location'[B] 0.22, '5'[B] 0.16, '4'[B] 0.15, '8'[B] 0.15

=== feature 75  width=66  rho=2.43 ===
  Gemini : This vector represents the concept of the news and publishing industry, encompassing digits, media, and printed matter.
  tokens : '5'[B] 0.21, '4'[B] 0.21, '3'[B] 0.20, '6'[B] 0.20, '8'[B] 0.20, '7'[B] 0.20, '1'[B] 0.20, '2'[B] 0.20, '9'[B] 0.19, '▁press'[B] 0.19

=== feature 90  width=31  rho=2.38 ===
  Gemini : This vector represents common grammatical prepositions and numerals.
  tokens : '▁through'[B] 0.38, '▁Through'[C] 0.38, 'through'[B] 0.37, '▁by'[B] 0.33, '▁By'[C] 0.32, 'By'[B] 0.30, '▁though'[B] 0.16, '▁Though'[N] 0.14, 'Though'[C] 0.14, '7'[B] 0.13

=== feature 2  width=31  rho=2.37 ===
  Gemini : This vector represents ordinal numbers and sequential positions in a series.
  tokens : '▁fourth'[B] 0.40, '▁third'[B] 0.39, '▁fifth'[C] 0.38, '▁sixth'[B] 0.35, '▁seventh'[C] 0.32, '▁second'[B] 0.32, '▁Second'[N] 0.20, '▁first'[B] 0.20, '▁last'[B] 0.12, 'First'[C] 0.12

=== feature 20  width=20  rho=2.32 ===
  Gemini : This feature vector represents third-person plural pronouns and related grammatical markers across multiple languages.
  tokens : '▁they'[B] 0.48, 'They'[B] 0.44, '▁their'[B] 0.42, '▁them'[B] 0.37, '▁themselves'[C] 0.32, '▁Them'[C] 0.29, '▁this'[B] 0.14, '▁ich'[N] 0.12, ')['[N] 0.10, 'This'[B] 0.08

=== feature 29  width=50  rho=2.30 ===
  Gemini : This feature activates for words indicating addition, alternative options, or concepts related to "otherness" and extension.
  tokens : '▁other'[B] 0.48, '▁others'[B] 0.37, 'Other'[C] 0.37, '▁another'[B] 0.28, 'Another'[N] 0.20, '▁more'[B] 0.20, '▁further'[C] 0.18, 'more'[C] 0.16, '▁otherwise'[C] 0.13, '▁also'[B] 0.11

=== feature 60  width=132  rho=2.21 ===
  Gemini : These tokens represent primary adjectives of scale, intensity, importance, and value.
  tokens : '▁high'[C] 0.20, '▁great'[B] 0.18, '▁big'[N] 0.17, '▁major'[N] 0.15, 'high'[N] 0.15, '▁strong'[C] 0.15, '▁large'[B] 0.15, '▁long'[C] 0.14, '▁important'[C] 0.14, '▁good'[C] 0.13

=== feature 97  width=86  rho=2.17 ===
  Gemini : These tokens represent common English derivational suffixes used to form nouns, verbs, adjectives, and adverbs.
  tokens : 'ing'[B] 0.23, 'ings'[C] 0.22, 'ism'[B] 0.21, 'ists'[C] 0.20, 'ingly'[C] 0.20, 'ist'[N] 0.19, 'izing'[N] 0.19, 'ments'[N] 0.18, 'ising'[C] 0.18, 'ment'[C] 0.17

=== feature 93  width=39  rho=2.13 ===
  Gemini : These tokens represent modal and auxiliary verbs used to express tense, possibility, necessity, or grammatical mood.
  tokens : '▁may'[B] 0.30, '▁might'[C] 0.29, '▁can'[B] 0.28, '▁could'[B] 0.28, '▁will'[N] 0.27, '▁would'[B] 0.27, '▁should'[C] 0.24, '▁are'[B] 0.24, '▁must'[C] 0.23, '▁is'[B] 0.22

=== feature 66  width=187  rho=2.12 ===
  Gemini : This vector represents common, abstract nouns used to categorize or describe general concepts and entities.
  tokens : '▁site'[C] 0.12, '▁name'[B] 0.12, '▁question'[N] 0.12, '▁line'[B] 0.11, '▁type'[C] 0.11, '▁process'[B] 0.11, '▁area'[B] 0.11, '▁style'[B] 0.11, '▁section'[C] 0.11, '▁point'[B] 0.11

=== feature 72  width=28  rho=2.09 ===
  Gemini : This feature activates on words and phrases used to introduce examples, similarities, or illustrations.
  tokens : '▁such'[B] 0.60, 'such'[N] 0.55, '▁like'[B] 0.24, '▁example'[C] 0.19, '▁instance'[C] 0.17, '▁including'[B] 0.17, '▁examples'[C] 0.16, 'Like'[B] 0.15, '▁likes'[C] 0.15, 'including'[C] 0.14

=== feature 64  width=35  rho=2.07 ===
  Gemini : This vector activates on common English pronouns, articles, and determiners, with some noisy subword fragments.
  tokens : '▁the'[B] 0.54, 'the'[B] 0.41, 'The'[B] 0.35, '▁The'[B] 0.34, '▁there'[C] 0.16, '▁those'[C] 0.16, '▁their'[B] 0.15, '▁these'[B] 0.14, '▁this'[B] 0.14, 'ffindor'[C] 0.14

### 3.2.e LLM judge, stage 2: is the description *the* concept?

Stage 2 sees only the concept name and the Stage 1 description. It returns `{"is_member", "confidence"}`.
A feature joins $F_C$ only if `is_member` is true **and** confidence ≥ 0.85.

In [22]:
print("---- Stage 2 prompt ----")
print(MEMBERSHIP_PROMPT.format(concept=CONCEPT, desc="{description}").strip())

todo = {f: descriptions[f] for f in cand["feature"].astype(int).tolist() if f in descriptions and f not in verdicts}
for feat, desc in tqdm(todo.items(), desc="Stage 2: classify"):
    verdicts[feat] = classify_membership_with_desc(client, CONCEPT, desc)
    save_judge()

cand["is_member"] = cand["feature"].map(lambda f: verdicts[int(f)][0])
cand["confidence"] = pd.to_numeric(cand["feature"].map(lambda f: verdicts[int(f)][1]), errors="coerce").fillna(0.0)
cand["selected"] = (cand["is_member"] == True) & (cand["confidence"] >= CONFIDENCE)

F_C = sorted(cand.loc[cand["selected"], "feature"].astype(int).tolist())
print(f"\nF_C = {F_C}  ({len(F_C)} concept-related features)")
cand[["feature", "ratio_abs", "is_member", "confidence", "selected", "description"]]

---- Stage 2 prompt ----
You get a concept name and a feature's description.
Decide if this feature describes the given concept. Consider if the feature is DISTINCTIVE for the concept (not broad like "sport" for "basketball") and not too noisy.
A feature should be marked true only if the concept is central and dominant in the description, not just one of several themes.
Return ONLY JSON: {"is_member": true|false, "confidence": 0..1}

Example 1:
Concept: Charity
Description: This vector represents elements related to giving and donations to charitable causes.
Answer: {"is_member": true, "confidence": 0.98}

Example 2:
Concept: Charity
Description: This vector represents elements related to money, such as gambling, investing and charity.
Answer: {"is_member": false, "confidence": 0.80}

Concept: Harry Potter
Description: {description}
Answer:

Stage 2: classify: 100%|██████████| 57/57 [00:34<00:00,  1.65it/s]

F_C = [88]  (1 concept-related features)

,feature,ratio_abs,is_member,confidence,selected,description
0,88,287541.979924,True,0.99,True,The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
1,46,44.699388,False,0.85,False,"This feature vector activates strongly in contexts involving magic, wizards, and witchcraft."
2,31,32.300446,False,1.00,False,"This vector represents numerical digits, fractions, and quantifiers denoting portions or amounts."
3,32,25.175359,False,0.99,False,"This feature activates for words related to physical or conceptual movement, arrival, and entry."
4,95,22.373198,False,0.99,False,This vector is related to third-person masculine singular personal and possessive pronouns.
5,44,20.405420,False,0.99,False,"This vector represents numbers and actions related to learning, literacy, and communication."
6,98,19.297753,False,0.95,False,"This vector is related to written or spoken works of creative literature, narrative, and storytelling."
7,68,18.239010,False,0.95,False,"This feature vector represents the concept of literature, books, and the act of reading."
8,25,16.212689,False,0.99,False,"This vector is related to contrast, comparison, and alternative options, occasionally blending with numeric digits."
9,8,11.926853,False,0.99,False,This vector represents verbs of physical motion and directional progression.
10,43,10.824707,False,1.00,False,"This vector represents commercial transactions, trade, and the buying and selling of goods or services."
11,17,9.253758,False,0.99,False,"This vector represents distinct iterations, occurrences, or variations of a particular entity or work."
12,61,8.553843,False,0.99,False,"This feature vector represents the concept of visual perception, observation, and feminine third-person reference."
13,47,8.510178,False,0.99,False,"This vector is related to global, planetary, and national geographical or geopolitical entities and concepts."
14,12,7.318519,False,0.99,False,"This vector represents concepts of comparison, similarity, and numerical digits."
15,50,6.703874,False,0.99,False,"This vector represents concepts and terminology related to the act, tools, and professions of writing and literature."
16,16,6.549108,False,0.99,False,This vector activates for communication verbs and numeric digits often used to attribute statements and data.
17,86,6.475608,False,1.00,False,This vector represents singular third-person present tense action verbs.
18,52,6.178044,False,1.00,False,"This vector represents quantification, totality, and numeric digits."
19,10,5.413480,False,0.99,False,"This vector represents common present and past tense mental, emotional, and preference-based action verbs."
20,3,4.700763,False,0.99,False,"The vector represents the concept of searching for, discovering, and encountering information or objects."
21,13,4.688993,False,1.00,False,This vector represents common transitive action verbs across various conjugations and tenses.
22,5,4.616347,False,0.99,False,"This vector represents causal relationships, justifications, and logical connections between events or statements."
23,9,4.555767,False,0.99,False,"These tokens represent core action verbs encompassing states of being, occurrences, and dynamic activities."
24,14,4.529929,False,0.99,False,"This vector is related to displaying, presenting, or visually representing something."
25,83,4.203337,False,0.95,False,"This vector represents the concepts of mortality, death, and killing."
26,59,4.165718,False,1.00,False,"The feature vector represents plural nouns and numerals denoting countable items, subjects, or quantities."
27,71,4.140354,False,1.00,False,This vector represents reflexive and personal pronouns related to self-reference and identity.
28,6,4.071793,False,1.00,False,"This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement."
29,38,3.981940,False,1.00,False,"These tokens function as transitional adverbs and conjunctions used to connect clauses and indicate logical relationships like contrast, consequence, or time."
30,7,3.529070,False,0.99,False,"This vector represents the concept of film and theatrical casting, production, and acting."
31,37,3.483264,False,0.99,False,"This vector represents sub-units, components, or divisions of a whole."
32,87,3.468193,False,1.00,False,"This vector represents quantification, encompassing words and numerals that denote amounts, numbers, and frequencies."
33,26,3.434122,False,0.99,False,This vector represents human demographic categories related to age and gender.
34,36,3.366060,False,0.99,False,"This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities."
35,28,3.361560,False,0.99,False,This vector represents numeric quantity words and number names.
36,65,3.332753,False,0.99,False,"This feature vector represents the concepts of drawing, visual art, and aesthetic attraction."
37,53,3.115132,False,0.99,False,"This vector represents the concept of time, age, and historical epochs."
38,49,3.060333,False,1.00,False,This feature vector activates strongly on present participles and continuous action verbs.
39,82,3.019828,False,0.99,False,"This feature vector activates on verbs and grammatical forms associated with containment, inclusion, and the listing of component parts."
40,18,2.788840,False,1.00,False,This feature activates for explicit negation words and negative prefixes.
41,0,2.748041,False,1.00,False,This vector represents units of time and temporal duration.
42,34,2.709658,False,0.99,False,This vector encodes superlative adjectives and third-person singular feminine pronouns.
43,58,2.630105,False,0.99,False,"This feature vector represents restrictive or limiting adverbs and modifiers emphasizing exclusivity, degree, or exactness."
44,24,2.628124,False,0.99,False,"This vector is related to the concepts of living, existence, and vitality."
45,21,2.589404,False,1.00,False,"This feature vector activates on tokens related to numerical digits, specific quantities, and spatial positioning or locations."
46,75,2.434641,False,0.99,False,"This vector represents the concept of the news and publishing industry, encompassing digits, media, and printed matter."
47,90,2.384990,False,0.99,False,This vector represents common grammatical prepositions and numerals.
48,2,2.366889,False,0.99,False,This vector represents ordinal numbers and sequential positions in a series.
49,20,2.315133,False,1.00,False,This feature vector represents third-person plural pronouns and related grammatical markers across multiple languages.
50,29,2.300741,False,0.99,False,"This feature activates for words indicating addition, alternative options, or concepts related to ""otherness"" and extension."
51,60,2.211585,False,0.99,False,"These tokens represent primary adjectives of scale, intensity, importance, and value."
52,97,2.166296,False,1.00,False,"These tokens represent common English derivational suffixes used to form nouns, verbs, adjectives, and adverbs."
53,93,2.127849,False,1.00,False,"These tokens represent modal and auxiliary verbs used to express tense, possibility, necessity, or grammatical mood."
54,66,2.118284,False,0.99,False,"This vector represents common, abstract nouns used to categorize or describe general concepts and entities."
55,72,2.094348,False,0.99,False,"This feature activates on words and phrases used to introduce examples, similarities, or illustrations."
56,64,2.067052,False,0.99,False,"This vector activates on common English pronouns, articles, and determiners, with some noisy subword fragments."

### 3.2.e′ Original fit: $\rho \ge \tau$ candidates (no Gemini)

The mass ratio ($\tau$ = 2.0) on `Y0`, **without the judge**: no Gemini calls are made for the original fit. Every candidate is
listed with its width and its top-15 tokens by $|Y^0_{i,t}|$ with labels [C]/[N]/[B], to compare by eye with the whitened $F_C$
(3.2.e/f). In the comparison cells below (3.2.w), `F_C0` **is this candidate list** ($\rho\ge\tau$ on the original fit), not a
judged selection. The last line lists $|\cos(\tilde{\mathbf z}_i, \tilde{\mathbf m})|$ for $i\in F_C$.

In [23]:
# tau filter on the original fit (Y0), no judge. F_C0 below = the rho >= tau candidates (NOT judged by Gemini).
N_SHOW0 = 15
stats0 = compute_embedding_stats(Y0.T, vstar_ids, token_to_code, CONCEPT).sort_values("ratio_abs", ascending=False)
for thr in [1.0, 1.25, 1.5, 1.75, 2.0, 2.25]:
    print(f"original fit: rho >= {thr:<4}: {(stats0['ratio_abs'] >= thr).sum():3d} / {RANK} features")
cand0 = stats0[stats0["ratio_abs"] >= TAU][["feature", "ratio_abs", "num_concept", "num_neutral", "num_both"]].reset_index(drop=True)
cand0["width"] = cand0["feature"].map(lambda f: int(widths0[int(f)]))
F_C0 = sorted(cand0["feature"].astype(int).tolist())   # stand-in for the judged F_C0: rho >= tau candidates of the original fit
print(f"\noriginal fit: {len(cand0)} candidates pass tau = {TAU}  ->  F_C0 (rho candidates, no judge) = {F_C0}   "
      f"(whitened fit, judged: F_C = {F_C})\n")

for _, row in cand0.iterrows():
    feat = int(row["feature"])
    mags = Y0[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW0]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])
    print(f"=== original feature {feat}  width={int(widths0[feat])}  rho={row['ratio_abs']:.2f} ===")
    print("  tokens : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

print("|cos(z~_i, m_X)| for i in F_C: " + (", ".join(
    f"{f}: {cos_m[f]:.3f} (rank {cos_m_order.index(f) + 1}/{RANK})" for f in F_C) or "F_C is empty"))
cand0

original fit: rho >= 1.0 :  67 / 100 features
original fit: rho >= 1.25:  60 / 100 features
original fit: rho >= 1.5 :  52 / 100 features
original fit: rho >= 1.75:  43 / 100 features
original fit: rho >= 2.0 :  37 / 100 features
original fit: rho >= 2.25:  33 / 100 features

original fit: 37 candidates pass tau = 2.0  ->  F_C0 (rho candidates, no judge) = [3, 6, 9, 11, 12, 14, 16, 18, 20, 22, 23, 24, 25, 28, 33, 35, 36, 38, 51, 52, 54, 58, 59, 62, 67, 71, 73, 78, 80, 84, 85, 87, 88, 91, 92, 93, 98]   (whitened fit, judged: F_C = [88])

=== original feature 22  width=32  rho=53.91 ===
  tokens : '▁magic'[C] 0.34, 'Magic'[C] 0.33, '▁Magic'[B] 0.32, 'magic'[C] 0.32, '▁magical'[C] 0.27, 'magical'[C] 0.26, '▁Magical'[C] 0.24, '▁wizard'[C] 0.21, '▁wizards'[C] 0.20, '▁Wizard'[C] 0.19, '▁witchcraft'[C] 0.17, 'wizard'[C] 0.17, '▁Wizards'[C] 0.16, '▁witch'[C] 0.16, '▁Witch'[C] 0.16

=== original feature 38  width=28  rho=43.80 ===
  tokens : '▁writing'[B] 0.34, '▁written'[B] 0.34, 'written'[C] 0.33, 'writing'[C] 0.33, '▁write'[C] 0.32, '▁wrote'[B] 0.30, '▁writers'[C] 0.26, '▁writer'[B] 0.26, '▁reads'[C] 0.16, '▁read'[C] 0.15, '▁reading'[B] 0.15, '▁authors'[C] 0.13, '▁author'[C] 0.13, '▁scribe'[C] 0.12, '▁Read'[C] 0.11

=== original feature 62  width=81  rho=14.94 ===
  tokens : '▁fiction'[C] 0.22, '▁tales'[C] 0.20, '▁stories'[B] 0.20, '▁fictional'[C] 0.19, '▁story'[B] 0.19, 'fiction'[C] 0.18, '▁drama'[N] 0.16, '▁narrative'[C] 0.16, '▁Tales'[C] 0.15, '▁dramas'[C] 0.15, '▁novels'[C] 0.15, '▁saga'[C] 0.14, '▁thriller'[C] 0.14, '▁movie'[C] 0.14, '▁film'[B] 0.14

=== original feature 52  width=33  rho=11.04 ===
  tokens : '▁young'[B] 0.27, '▁youth'[N] 0.25, '▁younger'[C] 0.24, '▁age'[B] 0.24, '▁youthful'[C] 0.24, '▁Young'[B] 0.23, '▁aged'[B] 0.22, '▁kid'[C] 0.21, '▁kids'[C] 0.21, '▁adult'[C] 0.20, '▁children'[B] 0.20, '▁adults'[C] 0.19, 'child'[C] 0.19, '▁teen'[C] 0.18, 'age'[C] 0.18

=== original feature 18  width=29  rho=7.27 ===
  tokens : '▁selling'[C] 0.37, '▁sold'[C] 0.36, 'selling'[C] 0.35, 'sold'[C] 0.33, '▁sale'[C] 0.31, '▁sales'[B] 0.30, 'seller'[C] 0.23, '▁buying'[C] 0.19, '▁bought'[N] 0.17, '▁purchasing'[C] 0.16, '▁marketing'[C] 0.16, '▁bestselling'[C] 0.12, '▁promotion'[N] 0.11, '▁retail'[N] 0.11, '▁market'[C] 0.11

=== original feature 73  width=27  rho=6.22 ===
  tokens : '▁book'[B] 0.39, '▁Book'[B] 0.37, 'book'[C] 0.36, '▁books'[C] 0.35, '▁Books'[C] 0.34, '▁bookstores'[C] 0.20, '▁novels'[C] 0.17, '▁novel'[B] 0.16, '▁textbook'[C] 0.16, '▁ebooks'[C] 0.16, '▁Novel'[C] 0.15, '▁album'[N] 0.15, '▁albums'[N] 0.14, 'Libr'[C] 0.13, '▁library'[N] 0.13

=== original feature 67  width=104  rho=5.13 ===
  tokens : '▁teaches'[C] 0.14, '▁learns'[C] 0.13, '▁gives'[C] 0.13, '▁goes'[B] 0.13, '▁allows'[C] 0.13, '▁tells'[C] 0.13, '▁speaks'[C] 0.13, '▁takes'[C] 0.12, '▁becomes'[B] 0.12, '▁delivers'[C] 0.12, '▁undergoes'[C] 0.12, '▁assumes'[C] 0.12, '▁enters'[C] 0.12, '▁comes'[C] 0.12, '▁weighs'[N] 0.12

=== original feature 84  width=45  rho=4.77 ===
  tokens : '▁compared'[C] 0.31, '▁comparing'[C] 0.28, 'Comparing'[C] 0.27, '▁similarities'[C] 0.23, '▁contrast'[C] 0.22, '▁vs'[C] 0.21, 'compar'[C] 0.21, '▁parallels'[C] 0.20, '▁similar'[B] 0.19, '▁likened'[C] 0.18, '▁opposed'[C] 0.18, 'Unlike'[C] 0.17, 'opposed'[N] 0.16, '▁resemble'[C] 0.16, '▁resembles'[C] 0.15

=== original feature 98  width=32  rho=4.57 ===
  tokens : '▁love'[C] 0.42, '▁Love'[N] 0.38, 'Love'[C] 0.37, '▁loves'[C] 0.34, '▁loved'[C] 0.30, '▁likes'[C] 0.19, '▁hope'[C] 0.17, '▁Hope'[N] 0.15, '▁dislike'[C] 0.14, '▁joy'[C] 0.14, '▁desire'[C] 0.14, '▁Wants'[C] 0.13, 'Wish'[N] 0.12, '▁wants'[C] 0.12, '▁happiness'[C] 0.12

=== original feature 88  width=25  rho=4.40 ===
  tokens : '▁part'[B] 0.40, 'part'[C] 0.40, '▁Part'[N] 0.37, '▁parts'[C] 0.36, '▁Parts'[C] 0.33, '▁half'[C] 0.20, 'half'[B] 0.19, '▁Half'[C] 0.19, '▁partial'[C] 0.16, '▁sections'[C] 0.15, '▁section'[C] 0.15, '▁piece'[N] 0.13, '▁pieces'[B] 0.13, '▁components'[N] 0.12, '▁segment'[B] 0.11

=== original feature 20  width=41  rho=4.28 ===
  tokens : '▁display'[N] 0.25, '▁showing'[C] 0.25, '▁show'[N] 0.25, '▁displayed'[C] 0.24, '▁displays'[C] 0.24, 'show'[C] 0.23, '▁showed'[C] 0.22, '▁shown'[C] 0.22, '▁showcase'[C] 0.22, '▁depicting'[C] 0.19, '▁portray'[C] 0.18, '▁depiction'[C] 0.18, '▁portraying'[C] 0.17, 'showcase'[C] 0.17, '▁depicted'[C] 0.17

=== original feature 71  width=15  rho=3.98 ===
  tokens : '▁himself'[C] 0.49, '▁themselves'[C] 0.48, '▁herself'[C] 0.46, '▁myself'[N] 0.41, '▁him'[B] 0.17, '▁them'[B] 0.15, '▁Them'[C] 0.15, '▁own'[B] 0.14, '▁me'[C] 0.12, '▁self'[C] 0.11, '▁us'[C] 0.10, '▁alone'[N] 0.09, '▁their'[B] 0.07, 'me'[N] 0.07, '▁his'[B] 0.06

=== original feature 87  width=53  rho=3.83 ===
  tokens : 'ffindor'[C] 0.33, 'therin'[C] 0.25, 'umbledore'[C] 0.25, '▁Rowling'[C] 0.23, 'demort'[C] 0.21, '▁Voldemort'[C] 0.21, '▁Dumbledore'[C] 0.21, '▁Weasley'[C] 0.20, '▁Malfoy'[C] 0.20, '▁Hogwarts'[C] 0.19, 'Hermione'[C] 0.19, '▁Snape'[C] 0.18, '▁Hermione'[C] 0.18, '▁Potter'[C] 0.15, 'Potter'[C] 0.15

=== original feature 12  width=49  rho=3.60 ===
  tokens : '▁criticism'[C] 0.30, '▁criticisms'[C] 0.28, '▁criticized'[N] 0.25, '▁critics'[C] 0.24, '▁criticised'[C] 0.23, '▁critic'[B] 0.23, '▁debate'[C] 0.19, '▁argue'[C] 0.19, '▁argument'[C] 0.19, '▁controversy'[C] 0.18, '▁arguing'[C] 0.17, '▁argues'[C] 0.17, '▁controversies'[C] 0.17, '▁accusations'[C] 0.17, '▁debated'[C] 0.16

=== original feature 23  width=120  rho=3.58 ===
  tokens : '▁learn'[C] 0.13, '▁improve'[B] 0.13, '▁promote'[B] 0.12, '▁contribute'[N] 0.12, '▁receive'[C] 0.12, '▁take'[B] 0.12, '▁participate'[C] 0.12, '▁adopt'[C] 0.12, '▁provide'[C] 0.12, '▁teach'[C] 0.12, '▁continue'[C] 0.12, '▁understand'[C] 0.11, '▁avoid'[C] 0.11, '▁assume'[C] 0.11, '▁accept'[C] 0.11

=== original feature 54  width=22  rho=3.23 ===
  tokens : '▁draw'[C] 0.46, '▁drawn'[C] 0.44, '▁drawing'[C] 0.41, 'Draw'[N] 0.40, '▁Drew'[N] 0.24, '▁attracted'[C] 0.21, '▁attraction'[C] 0.18, '▁sketch'[N] 0.16, '▁appeal'[B] 0.15, '▁attractions'[C] 0.13, '▁appealing'[C] 0.11, '▁dragged'[C] 0.09, '▁Dre'[N] 0.08, 'raw'[C] 0.08, 'rew'[C] 0.08

=== original feature 91  width=30  rho=3.01 ===
  tokens : '▁announcement'[C] 0.36, '▁announced'[B] 0.34, '▁announcing'[N] 0.33, '▁released'[B] 0.27, '▁release'[B] 0.27, '▁launch'[C] 0.25, '▁launched'[B] 0.23, '▁revealed'[C] 0.17, '▁reveal'[C] 0.17, '▁statement'[C] 0.17, '▁Ann'[N] 0.16, '▁news'[C] 0.16, '▁declared'[B] 0.15, '▁debut'[B] 0.14, '▁unleashed'[C] 0.14

=== original feature 28  width=24  rho=2.93 ===
  tokens : '▁nine'[C] 0.28, '▁five'[B] 0.28, '▁seven'[B] 0.27, '▁eight'[B] 0.27, '▁six'[B] 0.27, '▁four'[B] 0.26, '▁eleven'[C] 0.25, 'four'[C] 0.23, '▁three'[B] 0.23, '▁Five'[N] 0.22, 'Nine'[C] 0.22, '▁nineteen'[C] 0.22, '▁Eleven'[N] 0.21, '▁twenty'[C] 0.20, 'Three'[C] 0.19

=== original feature 36  width=28  rho=2.92 ===
  tokens : '▁lead'[C] 0.34, '▁follow'[C] 0.34, '▁follows'[C] 0.32, '▁followed'[C] 0.31, '▁leads'[B] 0.30, '▁led'[B] 0.29, '▁leading'[B] 0.26, '▁following'[B] 0.26, '▁followers'[C] 0.21, '▁trailed'[N] 0.17, '▁leaders'[C] 0.14, '▁open'[C] 0.13, '▁chase'[C] 0.12, '▁sequel'[C] 0.11, 'open'[C] 0.11

=== original feature 35  width=12  rho=2.91 ===
  tokens : '▁open'[C] 0.49, 'open'[C] 0.46, '▁Open'[N] 0.44, '▁opened'[B] 0.36, '▁opening'[B] 0.34, '▁closed'[C] 0.26, '▁enclosed'[N] 0.10, '▁expanded'[C] 0.09, '▁sealed'[C] 0.09, '▁expanding'[N] 0.08, '▁expansion'[C] 0.08, '▁op'[C] 0.07

=== original feature 6  width=81  rho=2.83 ===
  tokens : '▁largely'[B] 0.20, '▁primarily'[B] 0.20, '▁generally'[B] 0.19, '▁predominantly'[C] 0.18, '▁essentially'[C] 0.17, '▁mainly'[C] 0.17, '▁broadly'[N] 0.16, '▁ostensibly'[C] 0.15, '▁usually'[N] 0.15, '▁specifically'[C] 0.15, '▁initially'[C] 0.14, 'larg'[C] 0.14, '▁originally'[C] 0.13, '▁substantially'[C] 0.13, '▁invariably'[C] 0.13

=== original feature 24  width=45  rho=2.77 ===
  tokens : '▁killed'[C] 0.31, '▁killing'[C] 0.30, '▁kills'[C] 0.28, '▁death'[B] 0.25, '▁murdered'[C] 0.25, '▁killers'[N] 0.24, '▁murder'[C] 0.23, '▁killer'[N] 0.23, '▁Death'[C] 0.21, '▁dead'[C] 0.21, '▁died'[B] 0.21, '▁dies'[C] 0.20, '▁die'[C] 0.17, '▁massacre'[N] 0.16, '▁massac'[N] 0.15

=== original feature 85  width=25  rho=2.72 ===
  tokens : '▁both'[B] 0.38, 'both'[N] 0.38, '▁neither'[C] 0.38, '▁each'[B] 0.28, '▁either'[B] 0.28, '▁every'[C] 0.23, 'every'[C] 0.22, 'Each'[B] 0.22, '▁none'[C] 0.19, '▁all'[B] 0.18, 'all'[C] 0.17, '▁any'[B] 0.14, '▁no'[B] 0.14, 'All'[B] 0.12, '▁only'[B] 0.12

=== original feature 16  width=17  rho=2.71 ===
  tokens : '▁hold'[B] 0.44, '▁holding'[B] 0.41, '▁holds'[C] 0.39, '▁held'[B] 0.36, '▁holder'[C] 0.30, '▁Holden'[C] 0.24, '▁host'[B] 0.22, '▁hosts'[C] 0.21, '▁hosting'[N] 0.21, 'ghold'[N] 0.16, 'hang'[N] 0.09, '▁hanging'[C] 0.09, '▁retained'[C] 0.08, '▁grasp'[C] 0.08, '▁owner'[N] 0.07

=== original feature 3  width=37  rho=2.61 ===
  tokens : '▁discovering'[C] 0.35, '▁Discovery'[N] 0.33, '▁discoveries'[N] 0.33, 'Discovery'[C] 0.32, '▁discovers'[C] 0.32, '▁finding'[C] 0.24, '▁find'[C] 0.21, '▁Find'[C] 0.20, '▁uncover'[C] 0.19, '▁found'[B] 0.18, '▁exploration'[C] 0.16, '▁search'[C] 0.14, '▁learns'[C] 0.14, '▁explore'[N] 0.14, '▁learn'[C] 0.12

=== original feature 78  width=32  rho=2.58 ===
  tokens : '▁succeed'[B] 0.35, '▁successful'[C] 0.34, '▁success'[C] 0.32, '▁succeeded'[N] 0.32, '▁failed'[C] 0.29, '▁succeeding'[N] 0.28, 'failed'[C] 0.27, '▁rejected'[C] 0.20, '▁rejection'[C] 0.19, '▁accepted'[N] 0.17, '▁acceptance'[C] 0.17, '▁reject'[C] 0.17, '▁accept'[C] 0.13, '▁denied'[C] 0.12, '▁declined'[C] 0.11

=== original feature 14  width=30  rho=2.58 ===
  tokens : '▁favourite'[C] 0.24, '▁organised'[N] 0.24, '▁favour'[C] 0.24, '▁colour'[C] 0.23, '▁recognised'[C] 0.23, '▁favourable'[N] 0.23, 'centred'[C] 0.23, 'centre'[N] 0.22, '▁humour'[C] 0.22, 'arised'[C] 0.22, '▁neighbourhood'[N] 0.21, 'isation'[C] 0.21, '▁watercolour'[C] 0.20, '▁Defence'[C] 0.19, '▁instalment'[C] 0.19

=== original feature 51  width=21  rho=2.44 ===
  tokens : '▁longest'[C] 0.29, '▁fastest'[C] 0.29, '▁best'[B] 0.27, '▁funniest'[C] 0.26, '▁largest'[N] 0.26, '▁most'[B] 0.26, 'most'[C] 0.25, 'largest'[N] 0.25, '▁highest'[N] 0.24, 'ariest'[C] 0.23, 'tiest'[C] 0.23, 'liest'[C] 0.22, 'Best'[C] 0.22, '▁Most'[N] 0.22, '▁Best'[C] 0.21

=== original feature 80  width=37  rho=2.40 ===
  tokens : '▁various'[B] 0.29, '▁many'[B] 0.29, 'Various'[C] 0.29, '▁numerous'[N] 0.27, '▁several'[B] 0.24, '▁Many'[C] 0.24, 'Many'[C] 0.24, '▁varied'[C] 0.21, '▁multiple'[N] 0.21, '▁diverse'[B] 0.21, '▁different'[B] 0.20, '▁variety'[N] 0.19, '▁dozens'[C] 0.18, '▁Variety'[C] 0.16, '▁other'[B] 0.15

=== original feature 9  width=116  rho=2.39 ===
  tokens : '▁making'[C] 0.13, '▁taking'[C] 0.13, '▁giving'[N] 0.12, '▁saying'[C] 0.12, '▁showing'[C] 0.12, '▁dealing'[C] 0.12, '▁seeing'[C] 0.12, '▁doing'[B] 0.12, '▁talking'[C] 0.12, '▁providing'[N] 0.12, '▁creating'[B] 0.12, '▁addressing'[C] 0.11, '▁stating'[B] 0.11, '▁speaking'[C] 0.11, '▁seeking'[C] 0.11

=== original feature 59  width=14  rho=2.38 ===
  tokens : '▁cast'[C] 0.50, '▁Cast'[N] 0.47, 'Cast'[C] 0.46, '▁casting'[C] 0.41, 'caster'[N] 0.26, 'castle'[C] 0.15, '▁actors'[B] 0.11, '▁actor'[B] 0.10, 'ast'[N] 0.09, '▁broadcast'[C] 0.08, 'asting'[C] 0.08, '▁audition'[B] 0.08, '▁actress'[C] 0.07, '▁starring'[N] 0.07

=== original feature 25  width=87  rho=2.32 ===
  tokens : '▁great'[B] 0.21, '▁high'[C] 0.18, '▁strong'[C] 0.18, '▁rich'[N] 0.17, '▁good'[C] 0.17, '▁low'[N] 0.17, '▁fantastic'[C] 0.16, '▁poor'[B] 0.16, '▁very'[B] 0.15, 'high'[N] 0.14, '▁terrible'[C] 0.14, '▁powerful'[B] 0.14, '▁weak'[C] 0.14, '▁deep'[C] 0.13, '▁highly'[C] 0.13

=== original feature 58  width=17  rho=2.27 ===
  tokens : '▁fourth'[B] 0.41, '▁fifth'[C] 0.40, '▁third'[B] 0.39, '▁sixth'[B] 0.38, '▁seventh'[C] 0.37, '▁second'[B] 0.29, '▁Second'[N] 0.24, 'Forth'[C] 0.13, 'rd'[C] 0.13, '▁first'[B] 0.11, 'th'[B] 0.11, '▁secondary'[N] 0.10, 'nd'[N] 0.10, 'seconds'[N] 0.09, 'First'[C] 0.08

=== original feature 11  width=111  rho=2.21 ===
  tokens : '▁pattern'[C] 0.14, '▁style'[B] 0.14, '▁type'[C] 0.13, '▁model'[C] 0.13, '▁category'[N] 0.12, '▁label'[N] 0.12, '▁term'[B] 0.12, '▁scale'[B] 0.12, '▁range'[C] 0.12, '▁form'[B] 0.12, '▁process'[B] 0.12, '▁line'[B] 0.12, '▁figure'[N] 0.11, '▁name'[B] 0.11, '▁version'[B] 0.11

=== original feature 93  width=54  rho=2.20 ===
  tokens : '▁might'[C] 0.28, '▁may'[B] 0.26, '▁could'[B] 0.26, '▁can'[B] 0.23, '▁would'[B] 0.22, '▁should'[C] 0.21, '▁must'[C] 0.20, '▁will'[N] 0.20, '▁cannot'[C] 0.18, '▁need'[C] 0.17, '▁likely'[C] 0.16, '▁did'[B] 0.14, '▁possibly'[C] 0.14, '▁needs'[N] 0.14, '▁still'[B] 0.14

=== original feature 33  width=86  rho=2.09 ===
  tokens : 'izing'[N] 0.21, 'ingly'[C] 0.19, 'ising'[C] 0.19, 'istically'[C] 0.17, 'ing'[B] 0.17, 'isation'[C] 0.17, 'ings'[C] 0.16, 'ism'[B] 0.15, 'ists'[C] 0.15, 'ations'[C] 0.15, 'ments'[N] 0.15, 'isers'[C] 0.14, 'nesses'[N] 0.14, 'able'[C] 0.14, 'uality'[N] 0.13

=== original feature 92  width=23  rho=2.09 ===
  tokens : '▁lived'[C] 0.36, '▁lives'[C] 0.34, '▁living'[B] 0.34, '▁live'[B] 0.33, 'lived'[N] 0.32, '▁life'[B] 0.27, '▁alive'[C] 0.25, 'life'[C] 0.24, '▁resided'[N] 0.19, '▁resides'[C] 0.18, '▁dwell'[N] 0.15, '▁exist'[C] 0.15, '▁exists'[C] 0.14, '▁Lifetime'[N] 0.14, '▁surviving'[C] 0.12

|cos(z~_i, m_X)| for i in F_C: 88: 0.079 (rank 91/100)

    feature  ratio_abs  num_concept  num_neutral  num_both  width
0        22  53.912773           30            1         1     32
1        38  43.796393           20            1         7     28
2        62  14.937271           64            6        11     81
3        52  11.043993           24            3         6     33
4        18   7.270857           21            6         2     29
5        73   6.215309           18            4         5     27
6        67   5.127092           74           19        11    104
7        84   4.772367           27           11         7     45
8        98   4.565261           23            6         3     32
9        88   4.404793           15            4         6     25
10       20   4.278146           28            8         5     41
11       71   3.981854            7            3         5     15
12       87   3.830363           34           19         0     53
13       12   3.598782           30           13         6     49
14       23   3.583527           71           23        26    120
15       54   3.234519           16            5         1     22
16       91   3.009016           16            6         8     30
17       28   2.930477           11            5         8     24
18       36   2.915119           12            9         7     28
19       35   2.911511            7            3         2     12
20        6   2.830665           50           21        10     81
21       24   2.771468           29           14         2     45
22       85   2.717461            8            4        13     25
23       16   2.714829            7            5         5     17
24        3   2.608670           22           12         3     37
25       78   2.581159           19           11         2     32
26       14   2.578225           19           11         0     30
27       51   2.438905           12            6         3     21
28       80   2.398587           16            9        12     37
29        9   2.391933           67           35        14    116
30       59   2.382842            7            4         3     14
31       25   2.321591           45           24        18     87
32       58   2.274338            5            5         7     17
33       11   2.206453           50           27        34    111
34       93   2.200784           19           13        22     54
35       33   2.093291           46           27        13     86
36       92   2.089217           11            8         4     23

In [24]:
is_true = cand["is_member"] == True
ordered = cand.assign(
    _group=(~is_true).astype(int),
    _key=np.where(is_true, -cand["confidence"], cand["confidence"]),
).sort_values(["_group", "_key"])

for _, row in ordered.iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    is_member, conf = verdicts.get(feat, (None, None))
    verdict = "<not classified yet>" if feat not in verdicts else (
        f"is_member={is_member}  confidence={conf if conf is not None else 'n/a'}  "
        f"-> {'SELECTED' if row['selected'] else 'rejected'}"
    )

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini  : {descriptions.get(feat, '<not described yet>')}")
    print(f"  verdict : {verdict}")
    print("  tokens  : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

=== feature 88  width=61  rho=287541.98 ===
  Gemini  : The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
  verdict : is_member=True  confidence=0.99  -> SELECTED
  tokens  : 'ffindor'[C] 0.31, 'therin'[C] 0.26, 'umbledore'[C] 0.21, '▁Dumbledore'[C] 0.19, '▁Hogwarts'[C] 0.18, '▁Weasley'[C] 0.18, '▁Malfoy'[C] 0.17, '2'[B] 0.17, '▁Potter'[C] 0.17, 'Hermione'[C] 0.16

=== feature 46  width=47  rho=44.70 ===
  Gemini  : This feature vector activates strongly in contexts involving magic, wizards, and witchcraft.
  verdict : is_member=False  confidence=0.85  -> rejected
  tokens  : '▁magic'[C] 0.34, 'magic'[C] 0.33, 'Magic'[C] 0.32, '▁Magic'[B] 0.32, '▁magical'[C] 0.26, 'magical'[C] 0.24, '▁Magical'[C] 0.22, '▁wizard'[C] 0.17, '▁wizards'[C] 0.17, '▁witchcraft'[C] 0.15

=== feature 98  width=98  rho=19.30 ===
  Gemini  : This vector is related to written or spoken works of creative literature, narrative, and storytelling.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁stories'[B] 0.24, '▁story'[B] 0.23, '▁fiction'[C] 0.22, '▁tales'[C] 0.21, '▁novels'[C] 0.17, '▁fictional'[C] 0.17, 'fiction'[C] 0.17, '▁novel'[B] 0.16, '▁Tales'[C] 0.16, '▁narrative'[C] 0.16

=== feature 68  width=39  rho=18.24 ===
  Gemini  : This feature vector represents the concept of literature, books, and the act of reading.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁book'[B] 0.41, 'book'[C] 0.38, '▁Book'[B] 0.37, '▁books'[C] 0.36, '▁Books'[C] 0.33, '▁bookstores'[C] 0.19, '▁novels'[C] 0.15, '▁ebooks'[C] 0.15, '▁textbook'[C] 0.15, '▁novel'[B] 0.14

=== feature 83  width=34  rho=4.20 ===
  Gemini  : This vector represents the concepts of mortality, death, and killing.
  verdict : is_member=False  confidence=0.95  -> rejected
  tokens  : '▁death'[B] 0.32, '▁killed'[C] 0.32, '▁kills'[C] 0.29, '▁killing'[C] 0.29, '▁died'[B] 0.28, '▁dead'[C] 0.27, '▁Death'[C] 0.27, '▁dies'[C] 0.26, '▁die'[C] 0.25, '▁murdered'[C] 0.21

=== feature 32  width=22  rho=25.18 ===
  Gemini  : This feature activates for words related to physical or conceptual movement, arrival, and entry.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁entry'[C] 0.44, '▁enter'[C] 0.43, '▁enters'[C] 0.42, '▁entering'[C] 0.42, '▁entries'[C] 0.38, '▁into'[B] 0.13, '▁reaching'[C] 0.11, '▁reach'[C] 0.11, '▁reaches'[C] 0.11, '▁foray'[C] 0.10

=== feature 95  width=11  rho=22.37 ===
  Gemini  : This vector is related to third-person masculine singular personal and possessive pronouns.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁He'[B] 0.38, '▁his'[B] 0.38, '▁he'[B] 0.37, 'He'[B] 0.36, 'His'[C] 0.35, '▁His'[C] 0.35, '▁him'[B] 0.33, '▁himself'[C] 0.29, 'zyński'[N] 0.06, '▁Heli'[C] 0.05

=== feature 44  width=24  rho=20.41 ===
  Gemini  : This vector represents numbers and actions related to learning, literacy, and communication.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁read'[C] 0.47, '▁reads'[C] 0.40, '▁Read'[C] 0.40, '▁reading'[B] 0.36, '3'[B] 0.18, '6'[B] 0.17, '7'[B] 0.17, '4'[B] 0.17, '5'[B] 0.17, '8'[B] 0.17

=== feature 25  width=34  rho=16.21 ===
  Gemini  : This vector is related to contrast, comparison, and alternative options, occasionally blending with numeric digits.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁rather'[C] 0.37, 'Rather'[C] 0.33, '▁instead'[B] 0.29, '▁vs'[C] 0.27, '▁compared'[C] 0.26, '▁opposed'[C] 0.22, '▁against'[B] 0.19, '▁than'[B] 0.19, '▁Against'[C] 0.17, 'opposed'[N] 0.17

=== feature 8  width=28  rho=11.93 ===
  Gemini  : This vector represents verbs of physical motion and directional progression.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁coming'[C] 0.34, 'coming'[C] 0.34, '▁go'[C] 0.33, '▁goes'[B] 0.32, 'going'[C] 0.30, '▁Go'[C] 0.27, '▁went'[B] 0.26, 'gone'[C] 0.25, '▁comes'[C] 0.24, '▁came'[N] 0.22

=== feature 17  width=44  rho=9.25 ===
  Gemini  : This vector represents distinct iterations, occurrences, or variations of a particular entity or work.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁version'[B] 0.42, '▁edition'[B] 0.38, '▁Version'[C] 0.35, '▁editions'[C] 0.33, '▁example'[C] 0.22, '▁instance'[C] 0.22, '▁rendition'[C] 0.21, '▁examples'[C] 0.19, '▁instances'[C] 0.17, '▁copies'[B] 0.16

=== feature 61  width=32  rho=8.55 ===
  Gemini  : This feature vector represents the concept of visual perception, observation, and feminine third-person reference.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁view'[C] 0.37, '▁see'[B] 0.34, '▁sees'[C] 0.33, '▁seen'[C] 0.32, '▁views'[C] 0.32, '▁viewed'[C] 0.31, '▁seeing'[C] 0.30, '▁viewing'[B] 0.27, '▁perspective'[B] 0.13, '▁her'[B] 0.13

=== feature 47  width=27  rho=8.51 ===
  Gemini  : This vector is related to global, planetary, and national geographical or geopolitical entities and concepts.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁world'[B] 0.48, '▁World'[B] 0.46, 'World'[C] 0.45, '▁worlds'[C] 0.37, '▁universe'[C] 0.21, '▁worldwide'[C] 0.21, '▁internationally'[C] 0.16, '▁word'[C] 0.13, '▁International'[C] 0.13, '▁nation'[N] 0.09

=== feature 12  width=47  rho=7.32 ===
  Gemini  : This vector represents concepts of comparison, similarity, and numerical digits.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁similar'[B] 0.39, '▁same'[B] 0.38, '▁identical'[B] 0.29, 'Similarly'[C] 0.28, '▁like'[B] 0.22, '▁similarities'[C] 0.22, '▁resemble'[C] 0.20, '▁resembles'[C] 0.20, 'Like'[B] 0.20, '▁parallels'[C] 0.15

=== feature 50  width=44  rho=6.70 ===
  Gemini  : This vector represents concepts and terminology related to the act, tools, and professions of writing and literature.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁writing'[B] 0.33, '▁written'[B] 0.32, 'writing'[C] 0.31, 'written'[C] 0.30, '▁writer'[B] 0.30, '▁writers'[C] 0.29, '▁write'[C] 0.29, '▁wrote'[B] 0.27, '▁author'[C] 0.19, '▁authors'[C] 0.19

=== feature 16  width=86  rho=6.55 ===
  Gemini  : This vector activates for communication verbs and numeric digits often used to attribute statements and data.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁said'[B] 0.23, '▁stated'[C] 0.21, '3'[B] 0.18, '5'[B] 0.17, '▁reported'[C] 0.17, '4'[B] 0.17, '2'[B] 0.17, '6'[B] 0.17, '1'[B] 0.17, '8'[B] 0.17

=== feature 10  width=58  rho=5.41 ===
  Gemini  : This vector represents common present and past tense mental, emotional, and preference-based action verbs.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁love'[C] 0.34, '▁loves'[C] 0.30, '▁likes'[C] 0.28, '▁loved'[C] 0.26, '▁Love'[N] 0.26, 'Love'[C] 0.25, '▁like'[B] 0.25, 'Like'[B] 0.20, '▁wants'[C] 0.19, '▁Wants'[C] 0.16

=== feature 3  width=38  rho=4.70 ===
  Gemini  : The vector represents the concept of searching for, discovering, and encountering information or objects.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁find'[C] 0.40, '▁finding'[C] 0.38, '▁Find'[C] 0.36, '▁found'[B] 0.31, '▁discovering'[C] 0.28, '▁discovers'[C] 0.26, '▁discoveries'[N] 0.22, 'Discovery'[C] 0.19, '▁Discovery'[N] 0.19, '▁learn'[C] 0.16

=== feature 5  width=42  rho=4.62 ===
  Gemini  : This vector represents causal relationships, justifications, and logical connections between events or statements.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁due'[B] 0.40, '▁because'[B] 0.33, 'Due'[C] 0.33, 'because'[C] 0.32, '▁based'[B] 0.28, 'Because'[N] 0.25, 'based'[C] 0.25, '▁since'[B] 0.22, 'Since'[B] 0.15, '▁according'[B] 0.13

=== feature 9  width=139  rho=4.56 ===
  Gemini  : These tokens represent core action verbs encompassing states of being, occurrences, and dynamic activities.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁remain'[C] 0.14, '▁take'[B] 0.14, '▁have'[B] 0.13, '▁stay'[B] 0.13, '▁receive'[C] 0.13, '▁serve'[C] 0.13, '▁hold'[B] 0.13, '▁continue'[C] 0.12, '▁become'[B] 0.12, '▁go'[C] 0.12

=== feature 14  width=45  rho=4.53 ===
  Gemini  : This vector is related to displaying, presenting, or visually representing something.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁show'[N] 0.36, 'show'[C] 0.33, '▁showing'[C] 0.31, '▁showed'[C] 0.29, '▁shown'[C] 0.28, '▁display'[N] 0.24, '▁displayed'[C] 0.23, '▁displays'[C] 0.22, '▁showcase'[C] 0.20, 'showcase'[C] 0.17

=== feature 7  width=53  rho=3.53 ===
  Gemini  : This vector represents the concept of film and theatrical casting, production, and acting.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁cast'[C] 0.40, '▁casting'[C] 0.34, 'Cast'[C] 0.32, '▁Cast'[N] 0.31, '▁production'[C] 0.23, 'Production'[C] 0.20, '▁productions'[C] 0.19, '▁actors'[B] 0.17, '▁actor'[B] 0.16, '▁producer'[B] 0.16

=== feature 37  width=22  rho=3.48 ===
  Gemini  : This vector represents sub-units, components, or divisions of a whole.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁part'[B] 0.47, 'part'[C] 0.46, '▁Part'[N] 0.41, '▁parts'[C] 0.39, '▁Parts'[C] 0.34, '▁section'[C] 0.15, '▁sections'[C] 0.15, '▁aspects'[C] 0.10, '▁components'[N] 0.10, '▁partial'[C] 0.09

=== feature 26  width=63  rho=3.43 ===
  Gemini  : This vector represents human demographic categories related to age and gender.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁children'[B] 0.28, '▁kids'[C] 0.25, 'Children'[C] 0.23, '▁kid'[C] 0.22, 'child'[C] 0.21, '▁Child'[B] 0.20, '▁young'[B] 0.19, '▁adults'[C] 0.18, '▁adult'[C] 0.18, '▁girls'[N] 0.16

=== feature 36  width=19  rho=3.37 ===
  Gemini  : This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁open'[C] 0.42, 'open'[C] 0.40, '▁Open'[N] 0.35, '▁opened'[B] 0.29, '▁opening'[B] 0.24, '▁closed'[C] 0.21, '3'[B] 0.19, '6'[B] 0.19, '4'[B] 0.19, '5'[B] 0.19

=== feature 28  width=25  rho=3.36 ===
  Gemini  : This vector represents numeric quantity words and number names.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁four'[B] 0.31, '▁seven'[B] 0.30, '▁six'[B] 0.30, '▁five'[B] 0.30, '▁eight'[B] 0.29, '▁nine'[C] 0.29, '▁three'[B] 0.27, 'four'[C] 0.26, '▁eleven'[C] 0.24, '▁two'[B] 0.22

=== feature 65  width=37  rho=3.33 ===
  Gemini  : This feature vector represents the concepts of drawing, visual art, and aesthetic attraction.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁draw'[C] 0.44, '▁drawn'[C] 0.42, '▁drawing'[C] 0.40, 'Draw'[N] 0.35, '▁attracted'[C] 0.22, '▁attraction'[C] 0.20, '▁appeal'[B] 0.16, '▁Drew'[N] 0.15, '▁art'[C] 0.15, '▁attractions'[C] 0.14

=== feature 53  width=68  rho=3.12 ===
  Gemini  : This vector represents the concept of time, age, and historical epochs.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁old'[C] 0.29, '▁age'[B] 0.27, '▁aged'[B] 0.25, '▁Old'[C] 0.23, 'Older'[C] 0.23, '▁ancient'[C] 0.22, 'age'[C] 0.20, '▁younger'[C] 0.20, '▁young'[B] 0.18, '▁Ages'[C] 0.18

=== feature 82  width=35  rho=3.02 ===
  Gemini  : This feature vector activates on verbs and grammatical forms associated with containment, inclusion, and the listing of component parts.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁include'[B] 0.38, '▁includes'[C] 0.38, '▁including'[B] 0.33, 'including'[C] 0.30, '▁included'[B] 0.29, '▁inclusion'[C] 0.25, '▁contains'[B] 0.21, '▁consists'[N] 0.20, '▁contain'[C] 0.19, '▁consist'[C] 0.19

=== feature 34  width=35  rho=2.71 ===
  Gemini  : This vector encodes superlative adjectives and third-person singular feminine pronouns.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁most'[B] 0.39, 'most'[C] 0.38, '▁Most'[N] 0.29, '▁best'[B] 0.26, '▁fastest'[C] 0.20, '▁funniest'[C] 0.20, '▁longest'[C] 0.19, 'tiest'[C] 0.19, 'liest'[C] 0.19, 'Best'[C] 0.19

=== feature 58  width=20  rho=2.63 ===
  Gemini  : This feature vector represents restrictive or limiting adverbs and modifiers emphasizing exclusivity, degree, or exactness.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁just'[B] 0.50, 'Just'[C] 0.41, '▁Just'[N] 0.41, '▁simply'[C] 0.35, '▁merely'[C] 0.34, '▁only'[B] 0.26, '▁Only'[N] 0.19, '▁even'[B] 0.11, '▁simple'[C] 0.10, '▁actually'[C] 0.09

=== feature 24  width=36  rho=2.63 ===
  Gemini  : This vector is related to the concepts of living, existence, and vitality.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁living'[B] 0.43, '▁lived'[C] 0.36, '▁live'[B] 0.34, '▁lives'[C] 0.33, 'lived'[N] 0.28, '▁life'[B] 0.26, '▁alive'[C] 0.25, 'life'[C] 0.23, '▁resides'[C] 0.15, '▁resided'[N] 0.15

=== feature 75  width=66  rho=2.43 ===
  Gemini  : This vector represents the concept of the news and publishing industry, encompassing digits, media, and printed matter.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '5'[B] 0.21, '4'[B] 0.21, '3'[B] 0.20, '6'[B] 0.20, '8'[B] 0.20, '7'[B] 0.20, '1'[B] 0.20, '2'[B] 0.20, '9'[B] 0.19, '▁press'[B] 0.19

=== feature 90  width=31  rho=2.38 ===
  Gemini  : This vector represents common grammatical prepositions and numerals.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁through'[B] 0.38, '▁Through'[C] 0.38, 'through'[B] 0.37, '▁by'[B] 0.33, '▁By'[C] 0.32, 'By'[B] 0.30, '▁though'[B] 0.16, '▁Though'[N] 0.14, 'Though'[C] 0.14, '7'[B] 0.13

=== feature 2  width=31  rho=2.37 ===
  Gemini  : This vector represents ordinal numbers and sequential positions in a series.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁fourth'[B] 0.40, '▁third'[B] 0.39, '▁fifth'[C] 0.38, '▁sixth'[B] 0.35, '▁seventh'[C] 0.32, '▁second'[B] 0.32, '▁Second'[N] 0.20, '▁first'[B] 0.20, '▁last'[B] 0.12, 'First'[C] 0.12

=== feature 29  width=50  rho=2.30 ===
  Gemini  : This feature activates for words indicating addition, alternative options, or concepts related to "otherness" and extension.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁other'[B] 0.48, '▁others'[B] 0.37, 'Other'[C] 0.37, '▁another'[B] 0.28, 'Another'[N] 0.20, '▁more'[B] 0.20, '▁further'[C] 0.18, 'more'[C] 0.16, '▁otherwise'[C] 0.13, '▁also'[B] 0.11

=== feature 60  width=132  rho=2.21 ===
  Gemini  : These tokens represent primary adjectives of scale, intensity, importance, and value.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁high'[C] 0.20, '▁great'[B] 0.18, '▁big'[N] 0.17, '▁major'[N] 0.15, 'high'[N] 0.15, '▁strong'[C] 0.15, '▁large'[B] 0.15, '▁long'[C] 0.14, '▁important'[C] 0.14, '▁good'[C] 0.13

=== feature 66  width=187  rho=2.12 ===
  Gemini  : This vector represents common, abstract nouns used to categorize or describe general concepts and entities.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁site'[C] 0.12, '▁name'[B] 0.12, '▁question'[N] 0.12, '▁line'[B] 0.11, '▁type'[C] 0.11, '▁process'[B] 0.11, '▁area'[B] 0.11, '▁style'[B] 0.11, '▁section'[C] 0.11, '▁point'[B] 0.11

=== feature 72  width=28  rho=2.09 ===
  Gemini  : This feature activates on words and phrases used to introduce examples, similarities, or illustrations.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁such'[B] 0.60, 'such'[N] 0.55, '▁like'[B] 0.24, '▁example'[C] 0.19, '▁instance'[C] 0.17, '▁including'[B] 0.17, '▁examples'[C] 0.16, 'Like'[B] 0.15, '▁likes'[C] 0.15, 'including'[C] 0.14

=== feature 64  width=35  rho=2.07 ===
  Gemini  : This vector activates on common English pronouns, articles, and determiners, with some noisy subword fragments.
  verdict : is_member=False  confidence=0.99  -> rejected
  tokens  : '▁the'[B] 0.54, 'the'[B] 0.41, 'The'[B] 0.35, '▁The'[B] 0.34, '▁there'[C] 0.16, '▁those'[C] 0.16, '▁their'[B] 0.15, '▁these'[B] 0.14, '▁this'[B] 0.14, 'ffindor'[C] 0.14

=== feature 31  width=22  rho=32.30 ===
  Gemini  : This vector represents numerical digits, fractions, and quantifiers denoting portions or amounts.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁half'[C] 0.39, 'half'[B] 0.38, '▁Half'[C] 0.36, '5'[B] 0.25, '6'[B] 0.23, '7'[B] 0.22, '3'[B] 0.22, '4'[B] 0.22, '8'[B] 0.22, '9'[B] 0.22

=== feature 43  width=31  rho=10.82 ===
  Gemini  : This vector represents commercial transactions, trade, and the buying and selling of goods or services.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁selling'[C] 0.38, '▁sold'[C] 0.38, 'selling'[C] 0.35, 'sold'[C] 0.34, '▁sale'[C] 0.34, '▁sales'[B] 0.31, 'seller'[C] 0.24, '▁buying'[C] 0.16, '▁purchasing'[C] 0.14, '▁marketing'[C] 0.13

=== feature 86  width=108  rho=6.48 ===
  Gemini  : This vector represents singular third-person present tense action verbs.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁gives'[C] 0.15, '▁takes'[C] 0.14, '▁goes'[B] 0.14, '▁comes'[C] 0.14, '▁allows'[C] 0.14, '▁becomes'[B] 0.13, '▁is'[B] 0.13, '▁assumes'[C] 0.13, '▁teaches'[C] 0.13, '▁tells'[C] 0.13

=== feature 52  width=32  rho=6.18 ===
  Gemini  : This vector represents quantification, totality, and numeric digits.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁every'[C] 0.33, '▁each'[B] 0.32, 'every'[C] 0.31, '▁all'[B] 0.30, 'Each'[B] 0.26, 'all'[C] 0.26, 'All'[B] 0.20, '5'[B] 0.20, '7'[B] 0.19, '6'[B] 0.19

=== feature 13  width=33  rho=4.69 ===
  Gemini  : This vector represents common transitive action verbs across various conjugations and tenses.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁make'[B] 0.41, '▁making'[C] 0.40, '▁made'[B] 0.38, '▁makes'[C] 0.38, 'made'[C] 0.35, '▁mak'[C] 0.26, '▁makeup'[N] 0.16, '▁giving'[N] 0.12, 'give'[C] 0.12, '▁gave'[B] 0.12

=== feature 59  width=135  rho=4.17 ===
  Gemini  : The feature vector represents plural nouns and numerals denoting countable items, subjects, or quantities.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '5'[B] 0.16, '2'[B] 0.16, '6'[B] 0.16, '8'[B] 0.15, '9'[B] 0.15, '4'[B] 0.15, '3'[B] 0.15, '7'[B] 0.15, '1'[B] 0.15, '▁issues'[C] 0.15

=== feature 71  width=17  rho=4.14 ===
  Gemini  : This vector represents reflexive and personal pronouns related to self-reference and identity.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁himself'[C] 0.52, '▁herself'[C] 0.51, '▁themselves'[C] 0.42, '▁myself'[N] 0.35, '▁him'[B] 0.18, '▁own'[B] 0.18, '▁me'[C] 0.13, '▁self'[C] 0.13, '▁they'[B] 0.13, '▁his'[B] 0.12

=== feature 6  width=83  rho=4.07 ===
  Gemini  : This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁mainly'[C] 0.24, '▁primarily'[B] 0.24, '▁generally'[B] 0.24, '▁largely'[B] 0.24, '▁usually'[N] 0.23, '▁often'[C] 0.21, '▁predominantly'[C] 0.20, '▁essentially'[C] 0.20, 'larg'[C] 0.18, '▁invariably'[C] 0.15

=== feature 38  width=37  rho=3.98 ===
  Gemini  : These tokens function as transitional adverbs and conjunctions used to connect clauses and indicate logical relationships like contrast, consequence, or time.
  verdict : is_member=False  confidence=1.0  -> rejected
  tokens  : '▁however'[C] 0.43, '▁nonetheless'[C] 0.32, '▁meanwhile'[C] 0.30, 'However'[B] 0.30, '▁therefore'[B] 0.27, '▁though'[B] 0.27, '▁but'[B] 0.20, '▁thus'[B] 0.19, 'Yet'[C] 0.18, '▁although'[B] 0.16

=== feature 87  width=43  rho=3.47 ===
  Gemini  : This vector represents quantification, encompassing words and numerals that denote amounts, numbers, and frequencies.
  verdict : is_member=False  confidence=1.0  -> rejected

In [25]:
members = cand[cand["is_member"] == True].sort_values("ratio_abs", ascending=False)
print(f"{len(members)} / {len(cand)} candidates have is_member=True\n")

for _, row in members.iterrows():
    feat = int(row["feature"])
    mags = Y[feat].abs()
    top = torch.argsort(mags, descending=True)[:N_SHOW]
    top = top[mags[top] > 0].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])

    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f} ===")
    print(f"  Gemini  : {row['description']}")
    print(f"  verdict : confidence={row['confidence']:.2f}  -> {'SELECTED' if row['selected'] else 'rejected (confidence < ' + str(CONFIDENCE) + ')'}")
    print("  tokens  : " + ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, top)))
    print()

1 / 57 candidates have is_member=True

=== feature 88  width=61  rho=287541.98 ===
  Gemini  : The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
  verdict : confidence=0.99  -> SELECTED
  tokens  : 'ffindor'[C] 0.31, 'therin'[C] 0.26, 'umbledore'[C] 0.21, '▁Dumbledore'[C] 0.19, '▁Hogwarts'[C] 0.18, '▁Weasley'[C] 0.18, '▁Malfoy'[C] 0.17, '2'[B] 0.17, '▁Potter'[C] 0.17, 'Hermione'[C] 0.16

### 3.2.f Inspect the selected features

Table 3 of the paper reports only 1–3 embedding features per concept (Harry Potter on Gemma: 1).
Each selected feature should be a tight cluster of concept-specific tokens.

With variable widths a selected feature can be wider or narrower than the paper's $\lceil 0.01|V^*|\rceil$; its width is printed
with it, and 3.2.f-w compares the $F_C$ widths with the distribution over all $k$ features.

In [26]:
if not F_C:
    print("No feature passed both filters (F_C is empty).")

for feat in F_C:
    row = cand.loc[cand["feature"] == feat].iloc[0]
    print(f"=== feature {feat}  width={int(widths[feat])}  rho={row['ratio_abs']:.2f}  conf={row['confidence']:.2f} ===")
    print(f"  {row['description']}")
    print("  tokens:", ", ".join(f"{t!r}[{l[0]}]" for t, l in zip(row["activating_tokens"][:30], row["labels"][:30])))
    print()

=== feature 88  width=61  rho=287541.98  conf=0.99 ===
  The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
  tokens: 'ffindor'[H], 'therin'[H], 'umbledore'[H], ' Dumbledore'[H], ' Hogwarts'[H], ' Weasley'[H], ' Malfoy'[H], '2'[b], ' Potter'[H], 'Hermione'[H], '4'[b], ' Rowling'[H], ' Voldemort'[H], ' Hermione'[H], '3'[b], '8'[b], '6'[b], '5'[b], '1'[b], '7'[b], 'demort'[H], ' Harry'[H], '9'[b], '0'[b], 'Potter'[H], 'Harry'[H], ' Snape'[H], ' Draco'[H], ' Severus'[H], 'Hog'[H]

In [27]:
# 3.2.f-w Widths of the selected concept features vs. all k features of this fit
w_rank = torch.argsort(torch.argsort(-widths.double(), stable=True), stable=True)   # 0 = widest
print(f"[{VARIANT}] all features: widths min={int(widths.min())}  median={int(widths.median())}  max={int(widths.max())}")
if F_C:
    print(f"F_C widths: " + ", ".join(f"{f}: {int(widths[f])} (rank {int(w_rank[f]) + 1}/{RANK} by width, "
                                      f"{(widths < widths[f]).double().mean():.0%} of features narrower)" for f in F_C))
    print(f"F_C total width = {int(widths[F_C].sum())}   distinct tokens = "
          f"{len({j for f in F_C for j in torch.nonzero(Y[f]).flatten().tolist()})}")
    if len(cand):
        print(f"all rho >= tau candidates: median width = {int(widths[cand['feature'].astype(int).tolist()].median())}")
else:
    print("F_C is empty.")

[rn] all features: widths min=10  median=37  max=187
F_C widths: 88: 61 (rank 21/100 by width, 79% of features narrower)
F_C total width = 61   distinct tokens = 61
all rho >= tau candidates: median width = 38

In [28]:
# One column per selected feature: every token with nonzero Y_{i,t}, sorted by |Y_{i,t}|.
columns = {}
for feat in F_C:
    mags = Y[feat].abs()
    nz_idx = torch.nonzero(mags > 0).flatten()
    nz_idx = nz_idx[torch.argsort(mags[nz_idx], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in nz_idx])
    columns[f"feature {feat}"] = pd.Series(
        [f"{t} [{LABEL_TAG[codes[j]]}] {mags[j]:.2f}" for t, j in zip(toks, nz_idx)]
    )

wide = pd.DataFrame(columns).fillna("")
wide.index = range(1, len(wide) + 1)

all_cols = sorted({j for feat in F_C for j in torch.nonzero(Y[feat].abs() > 0).flatten().tolist()})
print(f"{len(F_C)} concept features, {len(all_cols)} distinct tokens "
      f"(C={sum(codes[j] == 1 for j in all_cols)}, N={sum(codes[j] == 0 for j in all_cols)}, "
      f"B={sum(codes[j] == 2 for j in all_cols)})")
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(wide)

1 concept features, 61 distinct tokens (C=50, N=0, B=11)

              feature 88
1       ffindor [C] 0.31
2        therin [C] 0.26
3     umbledore [C] 0.21
4   ▁Dumbledore [C] 0.19
5     ▁Hogwarts [C] 0.18
6      ▁Weasley [C] 0.18
7       ▁Malfoy [C] 0.17
8             2 [B] 0.17
9       ▁Potter [C] 0.17
10     Hermione [C] 0.16
11            4 [B] 0.16
12     ▁Rowling [C] 0.16
13   ▁Voldemort [C] 0.16
14    ▁Hermione [C] 0.16
15            3 [B] 0.16
16            8 [B] 0.16
17            6 [B] 0.15
18            5 [B] 0.15
19            1 [B] 0.15
20            7 [B] 0.15
21       demort [C] 0.15
22       ▁Harry [C] 0.15
23            9 [B] 0.14
24            0 [B] 0.14
25       Potter [C] 0.14
26        Harry [C] 0.14
27       ▁Snape [C] 0.14
28       ▁Draco [C] 0.11
29     ▁Severus [C] 0.11
30          Hog [C] 0.11
31         ▁Gry [C] 0.10
32       ▁Ginny [C] 0.10
33         ▁Hog [C] 0.10
34         otts [C] 0.10
35        warts [C] 0.09
36       ▁Remus [C] 0.07
37     ▁Granger [C] 0.07
38       ▁Lupin [C] 0.07
39        ▁wand [C] 0.07
40         ▁Sly [C] 0.07
41          ▁JK [C] 0.07
42      ▁wizard [C] 0.07
43      ▁Sirius [C] 0.07
44         ▁Mug [B] 0.06
45     ▁wizards [C] 0.06
46         blet [C] 0.06
47         ▁McG [C] 0.06
48     ▁potions [C] 0.06
49        ▁Grin [C] 0.06
50    ▁Sherlock [C] 0.06
51          idd [C] 0.06
52      ▁Merlin [C] 0.06
53      ▁Riddle [C] 0.06
54         ▁Ron [C] 0.06
55        ▁Quir [C] 0.06
56       wizard [C] 0.06
57      ▁Holmes [C] 0.05
58      ▁Wizard [C] 0.05
59         ▁Hag [C] 0.05
60          Row [C] 0.05
61      ▁Cedric [C] 0.05

In [29]:
TOP_N = 30
E_ref = E_vstar_X.float().cpu()  # X-space rows = transform(E_vstar): the space Z lives in
token_strs = tokenizer.convert_ids_to_tokens(vstar_ids)

group_masks = {
    "C": codes == 1,
    "C / B": (codes == 1) | (codes == 2),
    "C / B / N": np.ones_like(codes, dtype=bool),
}

for feat in F_C:
    y = Y[feat]
    # z's sign is arbitrary (Y can absorb it); orient it so its support tokens mostly have positive Y.
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots = E_ref @ z
    cos = dots / (E_ref.norm(dim=1) * z.norm())

    df = pd.DataFrame({
        "token": token_strs,
        "label": [LABEL_TAG[c] for c in codes],
        "dot": dots.numpy(),
        "cos": cos.numpy(),
        "Y": (sign * y).numpy(),
        "in_support": (y != 0).numpy(),
    })

    print(f"=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0} ===")
    for name, mask in group_masks.items():
        top = df[mask].sort_values("dot", ascending=False).head(TOP_N).reset_index(drop=True)
        top.index += 1
        print(f"\n-- {name}: {int(mask.sum())} tokens, top {TOP_N} by <e_t, z> --")
        display(top)

=== feature 88   ||z|| = 216.161   sign flipped: True ===

-- C: 1870 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  12732.517578  0.514052  0.310478        True
2        therin     C  11181.388672  0.518773  0.259958        True
3     umbledore     C  10097.919922  0.553125  0.212199        True
4   ▁Dumbledore     C   8930.062500  0.665795  0.188911        True
5     ▁Hogwarts     C   8904.632812  0.671854  0.179498        True
6      ▁Weasley     C   8174.834961  0.573672  0.178177        True
7       ▁Malfoy     C   7991.605469  0.597630  0.173265        True
8     ▁Hermione     C   7918.831055  0.646858  0.161442        True
9    ▁Voldemort     C   7913.580078  0.616619  0.161648        True
10     ▁Rowling     C   7658.938965  0.520910  0.162695        True
11     Hermione     C   7607.458008  0.542986  0.163772        True
12       demort     C   7591.455566  0.424494  0.151681        True
13      ▁Potter     C   7587.131836  0.540990  0.166467        True
14       ▁Harry     C   6938.243164  0.541300  0.148712        True
15       ▁Snape     C   6597.719238  0.524118  0.135932        True
16        Harry     C   6514.040039  0.536391  0.140369        True
17       Potter     C   6511.855469  0.476377  0.142912        True
18      ▁wizard     C   5930.111328  0.398728  0.066222        True
19     ▁wizards     C   5667.367676  0.404097  0.062322        True
20     ▁Severus     C   5354.985840  0.427816  0.111156        True
21       ▁Draco     C   5141.699219  0.441365  0.113829        True
22      ▁Wizard     C   5136.450684  0.360924  0.054313        True
23       wizard     C   5032.016602  0.342434  0.055944        True
24          Hog     C   4915.014648  0.337652  0.108963        True
25       ▁magic     C   4803.588379  0.249254 -0.000000       False
26         ▁Gry     C   4526.190430  0.340969  0.104352        True
27     ▁Magical     C   4444.542969  0.302678  0.000000       False
28         ▁Hog     C   4383.062012  0.295857  0.097193        True
29     ▁magical     C   4313.639160  0.275231 -0.000000       False
30       ▁Ginny     C   4311.050293  0.383465  0.100680        True

-- C / B: 2551 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  12732.517578  0.514052  0.310478        True
2        therin     C  11181.388672  0.518773  0.259958        True
3     umbledore     C  10097.919922  0.553125  0.212199        True
4   ▁Dumbledore     C   8930.062500  0.665795  0.188911        True
5     ▁Hogwarts     C   8904.632812  0.671854  0.179498        True
6      ▁Weasley     C   8174.834961  0.573672  0.178177        True
7       ▁Malfoy     C   7991.605469  0.597630  0.173265        True
8     ▁Hermione     C   7918.831055  0.646858  0.161442        True
9    ▁Voldemort     C   7913.580078  0.616619  0.161648        True
10     ▁Rowling     C   7658.938965  0.520910  0.162695        True
11     Hermione     C   7607.458008  0.542986  0.163772        True
12       demort     C   7591.455566  0.424494  0.151681        True
13      ▁Potter     C   7587.131836  0.540990  0.166467        True
14       ▁Harry     C   6938.243164  0.541300  0.148712        True
15       ▁Snape     C   6597.719238  0.524118  0.135932        True
16        Harry     C   6514.040039  0.536391  0.140369        True
17       Potter     C   6511.855469  0.476377  0.142912        True
18      ▁wizard     C   5930.111328  0.398728  0.066222        True
19     ▁wizards     C   5667.367676  0.404097  0.062322        True
20     ▁Severus     C   5354.985840  0.427816  0.111156        True
21       ▁Draco     C   5141.699219  0.441365  0.113829        True
22      ▁Wizard     C   5136.450684  0.360924  0.054313        True
23       wizard     C   5032.016602  0.342434  0.055944        True
24          Hog     C   4915.014648  0.337652  0.108963        True
25       ▁magic     C   4803.588379  0.249254 -0.000000       False
26       ▁Magic     B   4650.935547  0.253644 -0.000000       False
27         ▁Gry     C   4526.190430  0.340969  0.104352        True
28     ▁Magical     C   4444.542969  0.302678  0.000000       False
29         ▁Hog     C   4383.062012  0.295857  0.097193        True
30     ▁magical     C   4313.639160  0.275231 -0.000000       False

-- C / B / N: 4780 tokens, top 30 by <e_t, z> --

          token label           dot       cos         Y  in_support
1       ffindor     C  12732.517578  0.514052  0.310478        True
2        therin     C  11181.388672  0.518773  0.259958        True
3     umbledore     C  10097.919922  0.553125  0.212199        True
4   ▁Dumbledore     C   8930.062500  0.665795  0.188911        True
5     ▁Hogwarts     C   8904.632812  0.671854  0.179498        True
6      ▁Weasley     C   8174.834961  0.573672  0.178177        True
7       ▁Malfoy     C   7991.605469  0.597630  0.173265        True
8     ▁Hermione     C   7918.831055  0.646858  0.161442        True
9    ▁Voldemort     C   7913.580078  0.616619  0.161648        True
10     ▁Rowling     C   7658.938965  0.520910  0.162695        True
11     Hermione     C   7607.458008  0.542986  0.163772        True
12       demort     C   7591.455566  0.424494  0.151681        True
13      ▁Potter     C   7587.131836  0.540990  0.166467        True
14       ▁Harry     C   6938.243164  0.541300  0.148712        True
15       ▁Snape     C   6597.719238  0.524118  0.135932        True
16        Harry     C   6514.040039  0.536391  0.140369        True
17       Potter     C   6511.855469  0.476377  0.142912        True
18      ▁wizard     C   5930.111328  0.398728  0.066222        True
19     ▁wizards     C   5667.367676  0.404097  0.062322        True
20     ▁Severus     C   5354.985840  0.427816  0.111156        True
21       ▁Draco     C   5141.699219  0.441365  0.113829        True
22      ▁Wizard     C   5136.450684  0.360924  0.054313        True
23       wizard     C   5032.016602  0.342434  0.055944        True
24          Hog     C   4915.014648  0.337652  0.108963        True
25       ▁magic     C   4803.588379  0.249254 -0.000000       False
26       ▁Magic     B   4650.935547  0.253644 -0.000000       False
27         ▁Gry     C   4526.190430  0.340969  0.104352        True
28     ▁Magical     C   4444.542969  0.302678  0.000000       False
29         ▁Hog     C   4383.062012  0.295857  0.097193        True
30     ▁magical     C   4313.639160  0.275231 -0.000000       False

In [30]:
E_unit = E_ref / E_ref.norm(dim=1, keepdim=True)

for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots_unit = E_unit @ z

    df_unit = pd.DataFrame({
        "token": token_strs,
        "label": [LABEL_TAG[c] for c in codes],
        "dot_unit": dots_unit.numpy(),
        "||e_t||": E_ref.norm(dim=1).numpy(),
        "Y": (sign * y).numpy(),
        "in_support": (y != 0).numpy(),
    })

    print(f"=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0} ===")
    for name, mask in group_masks.items():
        top = df_unit[mask].sort_values("dot_unit", ascending=False).head(TOP_N).reset_index(drop=True)
        top.index += 1
        print(f"\n-- {name}: {int(mask.sum())} tokens, top {TOP_N} by <e_t / ||e_t||, z> --")
        display(top)

=== feature 88   ||z|| = 216.161   sign flipped: True ===

-- C: 1870 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  145.228577   61.314606  0.179498        True
2   ▁Dumbledore     C  143.918839   62.049290  0.188911        True
3     ▁Hermione     C  139.825531   56.633656  0.161442        True
4    ▁Voldemort     C  133.288879   59.371643  0.161648        True
5       ▁Malfoy     C  129.184189   61.862099  0.173265        True
6      ▁Weasley     C  124.005531   65.923157  0.178177        True
7     umbledore     C  119.563965   84.456223  0.212199        True
8      Hermione     C  117.372299   64.814766  0.163772        True
9        ▁Harry     C  117.007812   59.297260  0.148712        True
10      ▁Potter     C  116.941010   64.879997  0.166467        True
11        Harry     C  115.946686   56.181328  0.140369        True
12       ▁Snape     C  113.293831   58.235474  0.135932        True
13     ▁Rowling     C  112.600372   68.018776  0.162695        True
14       therin     C  112.138458   99.710571  0.259958        True
15      ffindor     C  111.118034  114.585510  0.310478        True
16       Potter     C  102.974022   63.237858  0.142912        True
17       ▁Draco     C   95.405823   53.892937  0.113829        True
18     ▁Severus     C   92.477058   57.906090  0.111156        True
19       demort     C   91.758995   82.732544  0.151681        True
20     ▁wizards     C   87.349960   64.881165  0.062322        True
21      ▁wizard     C   86.189392   68.803253  0.066222        True
22       ▁Ginny     C   82.890160   52.009193  0.100680        True
23      ▁Wizard     C   78.017563   65.837097  0.054313        True
24       wizard     C   74.020958   67.980980  0.055944        True
25         ▁Gry     C   73.704193   61.410217  0.104352        True
26          Hog     C   72.987152   67.340813  0.108963        True
27        ▁wand     C   70.070488   59.361305  0.068261        True
28     ▁Magical     C   65.427155   67.931183  0.000000       False
29         ▁Hog     C   63.952824   68.535881  0.097193        True
30       ▁Remus     C   63.122406   58.898914  0.073495        True

-- C / B: 2551 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  145.228577   61.314606  0.179498        True
2   ▁Dumbledore     C  143.918839   62.049290  0.188911        True
3     ▁Hermione     C  139.825531   56.633656  0.161442        True
4    ▁Voldemort     C  133.288879   59.371643  0.161648        True
5       ▁Malfoy     C  129.184189   61.862099  0.173265        True
6      ▁Weasley     C  124.005531   65.923157  0.178177        True
7     umbledore     C  119.563965   84.456223  0.212199        True
8      Hermione     C  117.372299   64.814766  0.163772        True
9        ▁Harry     C  117.007812   59.297260  0.148712        True
10      ▁Potter     C  116.941010   64.879997  0.166467        True
11        Harry     C  115.946686   56.181328  0.140369        True
12       ▁Snape     C  113.293831   58.235474  0.135932        True
13     ▁Rowling     C  112.600372   68.018776  0.162695        True
14       therin     C  112.138458   99.710571  0.259958        True
15      ffindor     C  111.118034  114.585510  0.310478        True
16       Potter     C  102.974022   63.237858  0.142912        True
17       ▁Draco     C   95.405823   53.892937  0.113829        True
18     ▁Severus     C   92.477058   57.906090  0.111156        True
19       demort     C   91.758995   82.732544  0.151681        True
20     ▁wizards     C   87.349960   64.881165  0.062322        True
21      ▁wizard     C   86.189392   68.803253  0.066222        True
22       ▁Ginny     C   82.890160   52.009193  0.100680        True
23      ▁Wizard     C   78.017563   65.837097  0.054313        True
24       wizard     C   74.020958   67.980980  0.055944        True
25         ▁Gry     C   73.704193   61.410217  0.104352        True
26          Hog     C   72.987152   67.340813  0.108963        True
27        ▁wand     C   70.070488   59.361305  0.068261        True
28     ▁Magical     C   65.427155   67.931183  0.000000       False
29         ▁Hog     C   63.952824   68.535881  0.097193        True
30       ▁Remus     C   63.122406   58.898914  0.073495        True

-- C / B / N: 4780 tokens, top 30 by <e_t / ||e_t||, z> --

          token label    dot_unit     ||e_t||         Y  in_support
1     ▁Hogwarts     C  145.228577   61.314606  0.179498        True
2   ▁Dumbledore     C  143.918839   62.049290  0.188911        True
3     ▁Hermione     C  139.825531   56.633656  0.161442        True
4    ▁Voldemort     C  133.288879   59.371643  0.161648        True
5       ▁Malfoy     C  129.184189   61.862099  0.173265        True
6      ▁Weasley     C  124.005531   65.923157  0.178177        True
7     umbledore     C  119.563965   84.456223  0.212199        True
8      Hermione     C  117.372299   64.814766  0.163772        True
9        ▁Harry     C  117.007812   59.297260  0.148712        True
10      ▁Potter     C  116.941010   64.879997  0.166467        True
11        Harry     C  115.946686   56.181328  0.140369        True
12       ▁Snape     C  113.293831   58.235474  0.135932        True
13     ▁Rowling     C  112.600372   68.018776  0.162695        True
14       therin     C  112.138458   99.710571  0.259958        True
15      ffindor     C  111.118034  114.585510  0.310478        True
16       Potter     C  102.974022   63.237858  0.142912        True
17       ▁Draco     C   95.405823   53.892937  0.113829        True
18     ▁Severus     C   92.477058   57.906090  0.111156        True
19       demort     C   91.758995   82.732544  0.151681        True
20     ▁wizards     C   87.349960   64.881165  0.062322        True
21      ▁wizard     C   86.189392   68.803253  0.066222        True
22       ▁Ginny     C   82.890160   52.009193  0.100680        True
23      ▁Wizard     C   78.017563   65.837097  0.054313        True
24       wizard     C   74.020958   67.980980  0.055944        True
25         ▁Gry     C   73.704193   61.410217  0.104352        True
26          Hog     C   72.987152   67.340813  0.108963        True
27        ▁wand     C   70.070488   59.361305  0.068261        True
28     ▁Magical     C   65.427155   67.931183  0.000000       False
29         ▁Hog     C   63.952824   68.535881  0.097193        True
30       ▁Remus     C   63.122406   58.898914  0.073495        True

In [31]:
TOP_K_COUNT = 100

rows = []
for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    rankings = {
        "<e_t, z>": E_ref @ z,
        "<e_t / ||e_t||, z>": E_unit @ z,
    }
    for name, scores in rankings.items():
        top = torch.argsort(scores, descending=True)[:TOP_K_COUNT].numpy()
        rows.append({
            "feature": feat,
            "ranking": name,
            "C": int((codes[top] == 1).sum()),
            "B": int((codes[top] == 2).sum()),
            "N": int((codes[top] == 0).sum()),
            "C in support": int(((codes[top] == 1) & (y[top] != 0).numpy()).sum()),
        })

print(f"Label counts among the top {TOP_K_COUNT} of all {len(vstar_ids)} tokens in V* "
      f"(base rate: C={(codes == 1).mean():.1%}, B={(codes == 2).mean():.1%}, N={(codes == 0).mean():.1%})")
pd.DataFrame(rows)

Label counts among the top 100 of all 4780 tokens in V* (base rate: C=39.1%, B=14.2%, N=46.6%)

   feature             ranking   C  B  N  C in support
0       88            <e_t, z>  90  9  1            50
1       88  <e_t / ||e_t||, z>  91  4  5            50

### 3.2.g Extended token set: every sentence of the concept's Wikipedia page, $Z$ fixed
$S_C^{ext} = S_C \cup$ all sentences of the article, $S_N^{ext} = S_N \cup$ as many neutral sentences. The new rows go through the **same** transform $T$ fitted in 3.1.c′ (nothing re-estimated), then only a sparse $Y_{ext}$ is fitted against the frozen X-space $Z$; feature $i$ keeps its 3.1.d width scaled to the larger set, $m_i^{ext} = \mathrm{round}(m_i\,|V^*_{ext}|/|V^*|)$, by $|Y^{dense}_{ext}|$ (refit off, as in 3.1.d). Groups: C / B / N = label in the original $V^*$ (3.2.a), C\* / B\* / N\* = label on the extended sentences; a token gets the first group it matches in the order C, C\*, B, B\*, N, N\*.

In [32]:
# ---- Extended E*: all sentences of the concept's Wikipedia page, Z from 3.1.d fixed, only a sparse Y_ext refit ----
# S_C^ext = S_C + every sentence of the live English Wikipedia article; S_N^ext = S_N + as many neutral sentences
# (one per page of the local wikimedia/wikipedia sample). The new sentences are cached next to RUN_DIR, so re-runs
# use the same page revision and sample.
# Rows go to X-space with the transform T of 3.1.c' exactly as fitted there (same mu_B, W, S_eta: nothing re-estimated),
# then Y_ext = top-m_i per row of (Z^T Z + lambda I)^{-1} Z^T X_ext^T: the Y-step of 3.1.d with Z frozen and the same lambda;
# feature i keeps its 3.1.d width scaled to the larger set, m_i^ext = round(width_i * |V*_ext| / |V*|).
import random
import sys

from experiments.varwidth.common import mask_from_row_widths

sys.path.insert(0, "experiments/resample_sentences")
from fetch_en_sentences import neutral_sentences, page_paragraphs, split_sentences

EXT_PATH = RUN_DIR.parent / "ext_sentences.json"   # shared by the five variable-width variants of this concept
EXT_GROUPS = ["C", "C*", "B", "B*", "N", "N*"]

# 1) sentences
ext = load_json(EXT_PATH, None)
if ext is None:
    canon, revid, paras = page_paragraphs(CONCEPT)
    page_sents = split_sentences(paras)
    ext = {"title": canon, "revid": revid, "concept": page_sents,
           "neutral": [r["sentence"] for r in neutral_sentences(
               Path("experiments/resample_sentences/data/wiki_dump_pages.jsonl"), len(page_sents),
               random.Random(SEED), exclude=set(page_sents))]}
    save_json(EXT_PATH, ext)
ext_concept = list(dict.fromkeys([s for s, lbl in dataset if lbl == CONCEPT] + ext["concept"]))
ext_neutral = list(dict.fromkeys([s for s, lbl in dataset if lbl != CONCEPT] + ext["neutral"]))
print(f"'{ext['title']}' rev {ext['revid']}: {len(ext['concept'])} page sentences, {len(ext['neutral'])} new neutral "
      f"({EXT_PATH})\nS_C^ext = {len(ext_concept)} sentences   S_N^ext = {len(ext_neutral)} sentences")

# 2) extended token set (a superset of V*) and its groups
special_ext = set(tokenizer.all_special_ids)


def token_set(sents):
    return {int(t) for s in sents for t in tokenizer(s, add_special_tokens=False)["input_ids"]} - special_ext


c_ids, n_ids = token_set(ext_concept), token_set(ext_neutral)
vstar_ext = sorted(c_ids | n_ids | set(vstar_ids))
codes_ext = np.array([2 if t in c_ids and t in n_ids else 1 if t in c_ids else 0 for t in vstar_ext])
orig_code = dict(zip(vstar_ids, codes.tolist()))


def ext_group(t: int, c_ext: int) -> str:
    """First match in the order C, C*, B, B*, N, N* (C/B/N: label in V*, starred: label on the extended sentences)."""
    o = orig_code.get(t)
    for g, hit in [("C", o == 1), ("C*", c_ext == 1), ("B", o == 2), ("B*", c_ext == 2), ("N", o == 0), ("N*", c_ext == 0)]:
        if hit:
            return g


groups_ext = np.array([ext_group(t, int(c)) for t, c in zip(vstar_ext, codes_ext)])
print(f"|V*_ext| = {len(vstar_ext)}  (|V*| = {len(vstar_ids)}, {len(vstar_ext) - len(vstar_ids)} new)")
display(pd.Series(groups_ext).value_counts().reindex(EXT_GROUPS).fillna(0).astype(int).rename("tokens").to_frame().T)

# 3) X_ext = T(E_{V*_ext}): the 3.1.c' transform, unchanged
ids_ext = torch.tensor(vstar_ext)
E_ext = E.index_select(0, ids_ext.to(E.device)).detach().float().cpu()
X_ext = transform(E_ext)                                                   # (|V*_ext|, d), X-space
pos_ext = {t: j for j, t in enumerate(vstar_ext)}
in_vstar = [pos_ext[t] for t in vstar_ids]
print(f"check: max |X_ext[V*] - E_vstar_X| = {(X_ext[in_vstar] - E_vstar_X.float().cpu()).abs().max():.2e}")

# 4) Y-step with Z frozen (dense ridge solve as in fit_varwidth, then each row's top m_i^ext; no refit, as CFG.refit=False)
A_ext = X_ext.T.contiguous().to(DEVICE)                                    # (d, |V*_ext|)
Z_dev = Z.to(DEVICE)
with Timer() as t_ext:
    inv_Z = torch.linalg.inv(Z_dev.T @ Z_dev + torch.eye(Z_dev.shape[1], device=DEVICE) * ridge_used)
    G_ext = A_ext.T @ Z_dev @ inv_Z                                        # (|V*_ext|, k), the G_ layout
    m_ext = (widths.double() * len(vstar_ext) / len(vstar_ids)).round().long().clamp(1, len(vstar_ext))
    Yd_ext = G_ext.T.contiguous()                                          # (k, |V*_ext|) dense
    Y_ext = (Yd_ext * mask_from_row_widths(Yd_ext.abs(), m_ext.to(Yd_ext.device))).float().cpu()   # (k, |V*_ext|)
A_ext_cpu = A_ext.cpu()
ext_err = (torch.norm(A_ext_cpu - Z @ Y_ext) / torch.norm(A_ext_cpu)).item()
print(f"fixed-Z fit: {t_ext['elapsed']:.3f}s, each feature keeps its 3.1.d width x |V*_ext|/|V*|: "
      f"{int(m_ext.min())}-{int(m_ext.max())} tokens per feature, {int(m_ext.sum())} in total")
print(f"relative error: on X_ext (fixed Z) = {ext_err:.4f}   3.1.d joint fit on A = {rel_err:.4f}")
del A_ext, Z_dev, G_ext, Yd_ext, A_ext_cpu, E_ext

'Harry Potter' rev 1379437311: 403 page sentences, 403 new neutral (runs/variable_width/Harry_Potter/ext_sentences.json)
S_C^ext = 444 sentences   S_N^ext = 682 sentences
|V*_ext| = 7408  (|V*| = 4780, 2628 new)

           C   C*    B   B*     N    N*
tokens  1870  465  681  158  2138  2096

check: max |X_ext[V*] - E_vstar_X| = 0.00e+00
fixed-Z fit: 0.023s, each feature keeps its 3.1.d width x |V*_ext|/|V*|: 15-290 tokens per feature, 7438 in total
relative error: on X_ext (fixed Z) = 0.8788   3.1.d joint fit on A = 0.8529

In [33]:
# ---- Rate every token of V*_ext on each concept feature, then list the feature's Y_ext support (X-space, where Z lives) ----
#   <x_t, z~>            inner product of the transformed token row with the feature direction
#   <x_t / ||x_t||, z~>  the same with the token row normalized
#   words                whole words of S_C^ext and S_N^ext the token was cut from (most frequent first)
# z~'s sign is arbitrary (Y absorbs it): oriented as in 3.2.f, so its 3.1 support tokens mostly have positive Y.
# Support table: tokens with Y_ext[feat, t] != 0, by decreasing |Y_ext|; group = first match in C, C*, B, B*, N, N* (3.2.g);
# in V*: the token is in the original token set;  in original support: Y[feat, t] != 0 in the 3.1 fit.
import re
from collections import Counter, defaultdict

SHOW_ROWS = 100   # rows shown per ranking; None shows all |V*_ext| tokens (the full tables are in ext_rating)

WORD_RE = re.compile(r"\w+(?:['’-]\w+)*")
token_words_ext = defaultdict(Counter)  # token id -> Counter of source words
for sent in ext_concept + ext_neutral:
    enc = tokenizer(sent, add_special_tokens=False, return_offsets_mapping=True)
    words = [(m.start(), m.end(), m.group()) for m in WORD_RE.finditer(sent)]
    for tid, (s, e) in zip(enc["input_ids"], enc["offset_mapping"]):
        for ws, we, w in words:
            if ws < e and s < we:  # token's character span overlaps this word
                token_words_ext[tid][w] += 1
words_ext = [[w for w, _ in token_words_ext[t].most_common()] for t in vstar_ext]

ext_strs = tokenizer.convert_ids_to_tokens(vstar_ext)
x_norms = X_ext.norm(dim=1)
vstar_set = set(vstar_ids)
ext_rating, ext_support = {}, {}
for feat in F_C:
    y = Y[feat]
    sign = 1.0 if y[y != 0].sum() >= 0 else -1.0
    z = sign * Z[:, feat]
    dots = X_ext @ z
    orig_sup = {vstar_ids[j] for j in torch.nonzero(y).flatten().tolist()}
    ext_sup = (Y_ext[feat] != 0).numpy()

    # 1) every token of V*_ext, ranked by the two inner products
    # support: first match of (original: in this direction's 3.1 support, extended: in its Y_ext support, none)
    df = pd.DataFrame({
        "token": ext_strs,
        "group": groups_ext,
        "words": words_ext,
        "support": ["original" if t in orig_sup else "extended" if e else "none" for t, e in zip(vstar_ext, ext_sup)],
        "<x_t, z>": dots.numpy(),
        "<x_t / ||x_t||, z>": (dots / x_norms).numpy(),
        "||x_t||": x_norms.numpy(),
        "Y_ext": (sign * Y_ext[feat]).numpy(),
        "in Y_ext support": (Y_ext[feat] != 0).numpy(),
    })
    ext_rating[feat] = df

    print(f"{'=' * 100}\n=== feature {feat}   ||z|| = {z.norm():.3f}   sign flipped: {sign < 0}   "
          f"|V*_ext| = {len(df)}   Y_ext support = {int(df['in Y_ext support'].sum())} ===\n{'=' * 100}")
    by_group = df.groupby("group")[["<x_t, z>", "<x_t / ||x_t||, z>"]].agg(["mean", "median", "max"])
    by_group.insert(0, "tokens", df["group"].value_counts())
    display(by_group.reindex(EXT_GROUPS).style.format("{:.3f}", subset=by_group.columns[1:]))
    for col in ["<x_t, z>", "<x_t / ||x_t||, z>"]:
        ranked = df.sort_values(col, ascending=False, ignore_index=True)
        ranked.index += 1
        print(f"\n-- all {len(df)} tokens of V*_ext by {col} (top {SHOW_ROWS or len(df)} shown) --")
        with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
            display(ranked if SHOW_ROWS is None else ranked.head(SHOW_ROWS))

    # 2) the feature's Y_ext support, by decreasing |Y_ext|
    sup = torch.nonzero(Y_ext[feat]).flatten()
    sup = sup[torch.argsort(Y_ext[feat, sup].abs(), descending=True)].tolist()
    sup_df = pd.DataFrame({
        "token": [ext_strs[j] for j in sup],
        "group": groups_ext[sup],
        "words": [words_ext[j] for j in sup],
        "Y_ext": (sign * Y_ext[feat, sup]).numpy(),
        "in V*": [vstar_ext[j] in vstar_set for j in sup],
        "in original support": [vstar_ext[j] in orig_sup for j in sup],
        "<x_t, z>": dots[sup].numpy(),
        "<x_t / ||x_t||, z>": (dots[sup] / x_norms[sup]).numpy(),
    }, index=pd.RangeIndex(1, len(sup) + 1, name="rank"))
    ext_support[feat] = sup_df

    lost = sorted(orig_sup - {vstar_ext[j] for j in sup})
    counts = "  ".join(f"{g}: {int((sup_df['group'] == g).sum())}" for g in EXT_GROUPS)
    print(f"\n-- Y_ext support: {len(sup_df)} tokens [{counts}] | in V*: {int(sup_df['in V*'].sum())} | "
          f"in original support: {int(sup_df['in original support'].sum())}/{len(orig_sup)} --")
    if lost:
        print(f"original support tokens no longer in the support ({len(lost)}): {tokenizer.convert_ids_to_tokens(lost)}")
    with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
        display(sup_df.style.format({"Y_ext": "{:+.4f}", "<x_t, z>": "{:.2f}", "<x_t / ||x_t||, z>": "{:.3f}"}))

====================================================================================================
=== feature 88   ||z|| = 216.161   sign flipped: True   |V*_ext| = 7408   Y_ext support = 95 ===
====================================================================================================

-- all 7408 tokens of V*_ext by <x_t, z> (top 100 shown) --

,token,group,words,support,"<x_t, z>","<x_t / ||x_t||, z>",||x_t||,Y_ext,in Y_ext support
1,ffindor,C,[Gryffindor],original,12732.517578,111.118042,114.585510,0.310478,True
2,therin,C,[Slytherin's],original,11181.388672,112.138451,99.710571,0.259958,True
3,umbledore,C,"[Dumbledore's, Dumbledore]",original,10097.919922,119.563957,84.456223,0.212199,True
4,▁Dumbledore,C,"[Dumbledore, Dumbledore's]",original,8930.062500,143.918854,62.049290,0.188911,True
5,▁Hogwarts,C,[Hogwarts],original,8904.632812,145.228577,61.314606,0.179498,True
6,▁Weasley,C,[Weasley],original,8174.834961,124.005516,65.923157,0.178177,True
7,▁Malfoy,C,[Malfoy],original,7991.605469,129.184189,61.862099,0.173265,True
8,▁Hermione,C,"[Hermione, Hermione's]",original,7918.831055,139.825531,56.633656,0.161442,True
9,▁Voldemort,C,"[Voldemort, Voldemort's]",original,7913.580078,133.288879,59.371643,0.161648,True
10,▁Rowling,C,"[Rowling, Rowling's]",original,7658.938965,112.600365,68.018776,0.162695,True
11,Hermione,C,[Hermione],original,7607.458008,117.372299,64.814766,0.163772,True
12,demort,C,[Voldemort],original,7591.455566,91.759003,82.732544,0.151681,True
13,▁Potter,C,"[Potter, Potter's, Potter-themed, Pottermore, Potter's's]",original,7587.131836,116.941002,64.879997,0.166467,True
14,▁Harry,C,"[Harry, Harry's, Harryplax]",original,6938.243164,117.007820,59.297260,0.148712,True
15,▁Snape,C,"[Snape, Snape's]",original,6597.719238,113.293823,58.235474,0.135932,True
16,Harry,C,"[Harry, Harry's]",original,6514.040039,115.946709,56.181328,0.140369,True
17,Potter,C,[Pottermore],original,6511.855469,102.974007,63.237858,0.142912,True
18,▁wizard,C,"[wizard, wizarding]",original,5930.111328,86.189400,68.803253,0.066222,True
19,▁wizards,C,[wizards],original,5667.367676,87.349968,64.881165,0.062323,True
20,▁Severus,C,[Severus],original,5354.985840,92.477074,57.906090,0.111156,True
21,▁Draco,C,[Draco],original,5141.699219,95.405807,53.892937,0.113829,True
22,▁Wizard,C,"[Wizarding, Wizardry, WizardingWorld]",original,5136.450684,78.017578,65.837097,0.054313,True
23,wizard,C,[Triwizard],original,5032.016602,74.020950,67.980980,0.055944,True
24,Hog,C,[Hogwarts],original,4915.014648,72.987160,67.340813,0.108963,True
25,▁magic,C,[magic],none,4803.588379,53.878910,89.155266,-0.000000,False
26,▁Magic,B,[Magic],none,4650.935547,54.827995,84.827751,-0.000000,False
27,▁Gry,C,[Gryffindor],original,4526.190430,73.704193,61.410217,0.104352,True
28,▁Magical,C,[Magical],none,4444.542969,65.427139,67.931183,0.000000,False
29,▁Hog,C,[Hogsmeade],original,4383.062012,63.952808,68.535881,0.097193,True
30,▁magical,C,[magical],none,4313.639160,59.494202,72.505203,-0.000000,False
31,▁Ginny,C,[Ginny],original,4311.050293,82.890160,52.009193,0.100680,True
32,warts,C,[Hogwarts],original,4252.854004,56.605392,75.131607,0.086719,True
33,Magic,C,[Magic],none,4179.029785,48.781425,85.668465,-0.000000,False
34,otts,C,[Gringotts],original,4177.020508,54.350853,76.852898,0.095830,True
35,▁wand,C,[wand],original,4159.475586,70.070488,59.361305,0.068261,True
36,magic,C,[magic],none,4045.007812,47.283619,85.547760,-0.000000,False
37,magical,C,[non-magical],none,3923.512451,55.713543,70.422958,-0.000000,False
38,▁Wizards,C,[Wizards],extended,3919.849121,62.865639,62.352810,0.039290,True
39,▁witches,C,[witches],extended,3744.652832,59.324192,63.121853,0.038607,True
40,▁Remus,C,[Remus],original,3717.840820,63.122398,58.898914,0.073495,True
41,▁Tolkien,C*,[Tolkien's],extended,3458.571777,66.773438,51.795620,0.067368,True
42,▁witchcraft,C,[witchcraft],none,3414.228516,56.024197,60.942036,0.000000,False
43,▁witch,C,[witch],none,3414.028809,48.869919,69.859512,0.000000,False
44,▁Merlin,C,[Merlin],original,3367.241211,56.185043,59.931274,0.057543,True
45,▁potions,C,[potions],original,3347.462402,61.941559,54.042271,0.059631,True
46,▁Sirius,C,[Sirius],original,3313.619629,60.308105,54.944847,0.065989,True
47,▁Granger,C,[Granger],original,3279.628418,49.216625,66.636597,0.072985,True
48,▁Witch,C,[Witchcraft],none,3197.287598,49.331772,64.811935,0.000000,False
49,▁Sly,C,[Slytherin's],original,3119.539062,55.404694,56.304600,0.068012,True
50,▁hog,C*,[hogwartsia],extended,3094.583008,45.978325,67.305260,0.067935,True
51,▁Mug,B,"[Muggles, Muggle, Muggs]",original,3088.866211,53.777596,57.437790,0.063299,True
52,▁JK,C,"[JK's, JK]",original,3052.595459,59.903084,50.958904,0.066945,True
53,▁Lupin,C,"[Lupin, Lupin's]",original,2987.613770,48.222942,61.954197,0.072085,True
54,▁Sherlock,C,[Sherlock],original,2847.778320,55.915348,50.930172,0.058746,True
55,▁McG,C,[McGonagall],original,2775.113525,52.549816,52.809196,0.060375,True
56,▁Ron,C,"[Ron, Ron's]",original,2756.764648,52.600468,52.409508,0.056796,True
57,blet,C,[Goblet],original,2746.663818,34.353172,79.953720,0.060788,True
58,▁Riddle,C,[Riddle],original,2741.238037,45.737484,59.934170,0.057011,True
59,wiz,C,[wizards],none,2731.500732,42.301434,64.572296,0.000000,False
60,idd,C,[Quidditch],original,2711.027832,42.632706,63.590332,0.057946,True
61,▁Quir,C,"[Quirrell, Quirinus]",original,2658.195557,36.938351,71.963028,0.056406,True
62,▁Hag,C,"[Hagrid, Hagrid's]",original,2621.806885,43.565269,60.181126,0.053988,True
63,▁spells,C*,[spells],none,2567.478516,38.697128,66.348038,0.000000,False
64,▁elves,C,[elves],extended,2532.488525,46.434811,54.538578,0.036412,True
65,▁Grin,C,[Grindelwald],original,2481.941650,39.727444,62.474236,0.058970,True
66,▁goblins,C*,[goblins],extended,2431.403809,48.977966,49.642807,0.039078,True
67,▁Spells,C*,[Spells],none,2426.187500,38.986233,62.231903,0.000000,False
68,▁Sorcerer,C,[Sorcerer's],none,2425.721191,40.907566,59.297615,0.000000,False
69,▁Holmes,C,"[Holmes-style, Holmes]",original,2304.705322,42.339630,54.433762,0.054985,True
70,▁Cedric,C,[Cedric],original,2238.200195,39.067204,57.291027,0.049141,True
71,Row,C,"[Rowling, Rowling's]",original,2222.445801,37.717926,58.922798,0.051296,True
72,▁dragons,C,[dragons],extended,2127.543457,40.231617,52.882374,0.035407,True
73,arnia,C,[Narnia],extended,2124.394531,27.953579,75.997231,0.037019,True
74,▁Bloomsbury,C,[Bloomsbury],extended,2080.242676,33.794601,61.555473,0.036861,True
75,▁werewolf,C,[werewolf],extended,2067.451904,40.860458,50.597866,0.034587,True
76,uggle,C,"[Muggle-born, anti-Muggle, Muggle]",none,2026.390015,26.895771,75.342331,0.000000,False
77,▁Cursed,C,[Cursed],none,2003.861816,33.219143,60.322502,0.000000,False
78,▁Cinderella,C,[Cinderella],none,1994.697388,35.114201,56.806004,0.000000,False
79,▁fairy,C*,[fairy],none,1975.369141,33.885033,58.296215,0.000000,False
80,Quir,C,[Quirrell],extended,1969.660400,28.192686,69.864235,0.039953,True
81,▁Beaux,B,"[Beauxbatons, Beaux-Arts]",extended,1922.525024,28.029732,68.588776,0.041980,True
82,▁Disney,N*,[Disney],none,1919.849609,48.180649,39.846901,0.000000,False
83,HP,N,[NHP],extended,1912.499268,49.590473,38.565861,0.040646,True
84,▁Minerva,C,[Minerva],extended,1910.433228,31.287741,61.060120,0.044297,True
85,▁owls,C,[owls],extended,1878.261963,36.195480,51.892170,0.034874,True
86,▁Umb,C,[Umbridge],extended,1877.275635,30.717758,61.113693,0.040371,True
87,▁Warlock,C,[Warlock],none,1862.377930,31.790342,58.583134,0.000000,False
88,▁Beowulf,C*,[Beowulf],extended,1828.993042,30.234921,60.492737,0.046709,True
89,▁gry,C*,[gryffindori],extended,1822.946167,28.726789,63.458054,0.045350,True
90,▁professors,C,[professors],none,1787.376953,29.499557,60.589958,0.000000,False
91,.,B,[],none,1773.700928,9.177809,193.259735,-0.000000,False
92,▁fantasy,C,[fantasy],none,1749.600464,30.470125,57.420193,0.000000,False
93,▁Wic,C,[Wicca],none,1742.967529,31.161161,55.933971,0.000000,False
94,▁Professor,B,[Professor],none,1738.883301,27.071442,64.233124,0.000000,False
95,Sna,C,[Snape],extended,1737.177979,32.416367,53.589535,0.037021,True
96,▁Lily,C,[Lily],extended,1733.429932,36.973804,46.882652,0.035920,True
97,▁herself,C,[herself],none,1732.715942,12.910736,134.207367,0.000000,False
98,▁Dragon,C,[Dragon],none,1727.331787,34.002491,50.800152,0.000000,False
99,▁knight,C,"[knight, knightly]",none,1710.899780,33.291542,51.391426,0.000000,False
100,▁himself,C,[himself],none,1698.442627,13.195525,128.713531,0.000000,False

-- all 7408 tokens of V*_ext by <x_t / ||x_t||, z> (top 100 shown) --

,token,group,words,support,"<x_t, z>","<x_t / ||x_t||, z>",||x_t||,Y_ext,in Y_ext support
1,▁Hogwarts,C,[Hogwarts],original,8904.632812,145.228577,61.314606,0.179498,True
2,▁Dumbledore,C,"[Dumbledore, Dumbledore's]",original,8930.062500,143.918854,62.049290,0.188911,True
3,▁Hermione,C,"[Hermione, Hermione's]",original,7918.831055,139.825531,56.633656,0.161442,True
4,▁Voldemort,C,"[Voldemort, Voldemort's]",original,7913.580078,133.288879,59.371643,0.161648,True
5,▁Malfoy,C,[Malfoy],original,7991.605469,129.184189,61.862099,0.173265,True
6,▁Weasley,C,[Weasley],original,8174.834961,124.005516,65.923157,0.178177,True
7,umbledore,C,"[Dumbledore's, Dumbledore]",original,10097.919922,119.563957,84.456223,0.212199,True
8,Hermione,C,[Hermione],original,7607.458008,117.372299,64.814766,0.163772,True
9,▁Harry,C,"[Harry, Harry's, Harryplax]",original,6938.243164,117.007820,59.297260,0.148712,True
10,▁Potter,C,"[Potter, Potter's, Potter-themed, Pottermore, Potter's's]",original,7587.131836,116.941002,64.879997,0.166467,True
11,Harry,C,"[Harry, Harry's]",original,6514.040039,115.946709,56.181328,0.140369,True
12,▁Snape,C,"[Snape, Snape's]",original,6597.719238,113.293823,58.235474,0.135932,True
13,▁Rowling,C,"[Rowling, Rowling's]",original,7658.938965,112.600365,68.018776,0.162695,True
14,therin,C,[Slytherin's],original,11181.388672,112.138451,99.710571,0.259958,True
15,ffindor,C,[Gryffindor],original,12732.517578,111.118042,114.585510,0.310478,True
16,Potter,C,[Pottermore],original,6511.855469,102.974007,63.237858,0.142912,True
17,▁Draco,C,[Draco],original,5141.699219,95.405807,53.892937,0.113829,True
18,▁Severus,C,[Severus],original,5354.985840,92.477074,57.906090,0.111156,True
19,demort,C,[Voldemort],original,7591.455566,91.759003,82.732544,0.151681,True
20,▁wizards,C,[wizards],original,5667.367676,87.349968,64.881165,0.062323,True
21,▁wizard,C,"[wizard, wizarding]",original,5930.111328,86.189400,68.803253,0.066222,True
22,▁Ginny,C,[Ginny],original,4311.050293,82.890160,52.009193,0.100680,True
23,▁Wizard,C,"[Wizarding, Wizardry, WizardingWorld]",original,5136.450684,78.017578,65.837097,0.054313,True
24,wizard,C,[Triwizard],original,5032.016602,74.020950,67.980980,0.055944,True
25,▁Gry,C,[Gryffindor],original,4526.190430,73.704193,61.410217,0.104352,True
26,Hog,C,[Hogwarts],original,4915.014648,72.987160,67.340813,0.108963,True
27,▁wand,C,[wand],original,4159.475586,70.070488,59.361305,0.068261,True
28,▁Tolkien,C*,[Tolkien's],extended,3458.571777,66.773438,51.795620,0.067368,True
29,▁Magical,C,[Magical],none,4444.542969,65.427139,67.931183,0.000000,False
30,▁Hog,C,[Hogsmeade],original,4383.062012,63.952808,68.535881,0.097193,True
31,▁Remus,C,[Remus],original,3717.840820,63.122398,58.898914,0.073495,True
32,▁Wizards,C,[Wizards],extended,3919.849121,62.865639,62.352810,0.039290,True
33,▁potions,C,[potions],original,3347.462402,61.941559,54.042271,0.059631,True
34,▁Sirius,C,[Sirius],original,3313.619629,60.308105,54.944847,0.065989,True
35,▁JK,C,"[JK's, JK]",original,3052.595459,59.903084,50.958904,0.066945,True
36,▁magical,C,[magical],none,4313.639160,59.494202,72.505203,-0.000000,False
37,▁witches,C,[witches],extended,3744.652832,59.324192,63.121853,0.038607,True
38,warts,C,[Hogwarts],original,4252.854004,56.605392,75.131607,0.086719,True
39,▁Merlin,C,[Merlin],original,3367.241211,56.185043,59.931274,0.057543,True
40,▁witchcraft,C,[witchcraft],none,3414.228516,56.024197,60.942036,0.000000,False
41,▁Sherlock,C,[Sherlock],original,2847.778320,55.915348,50.930172,0.058746,True
42,magical,C,[non-magical],none,3923.512451,55.713543,70.422958,-0.000000,False
43,▁Sly,C,[Slytherin's],original,3119.539062,55.404694,56.304600,0.068012,True
44,▁Magic,B,[Magic],none,4650.935547,54.827995,84.827751,-0.000000,False
45,otts,C,[Gringotts],original,4177.020508,54.350853,76.852898,0.095830,True
46,▁magic,C,[magic],none,4803.588379,53.878910,89.155266,-0.000000,False
47,▁Mug,B,"[Muggles, Muggle, Muggs]",original,3088.866211,53.777596,57.437790,0.063299,True
48,▁Ron,C,"[Ron, Ron's]",original,2756.764648,52.600468,52.409508,0.056796,True
49,▁McG,C,[McGonagall],original,2775.113525,52.549816,52.809196,0.060375,True
50,HP,N,[NHP],extended,1912.499268,49.590473,38.565861,0.040646,True
51,▁Witch,C,[Witchcraft],none,3197.287598,49.331772,64.811935,0.000000,False
52,▁Granger,C,[Granger],original,3279.628418,49.216625,66.636597,0.072985,True
53,▁goblins,C*,[goblins],extended,2431.403809,48.977966,49.642807,0.039078,True
54,▁witch,C,[witch],none,3414.028809,48.869919,69.859512,0.000000,False
55,Magic,C,[Magic],none,4179.029785,48.781425,85.668465,-0.000000,False
56,▁Lupin,C,"[Lupin, Lupin's]",original,2987.613770,48.222942,61.954197,0.072085,True
57,▁Disney,N*,[Disney],none,1919.849609,48.180649,39.846901,0.000000,False
58,magic,C,[magic],none,4045.007812,47.283619,85.547760,-0.000000,False
59,▁elves,C,[elves],extended,2532.488525,46.434811,54.538578,0.036412,True
60,▁hog,C*,[hogwartsia],extended,3094.583008,45.978325,67.305260,0.067935,True
61,▁Riddle,C,[Riddle],original,2741.238037,45.737484,59.934170,0.057011,True
62,▁Hag,C,"[Hagrid, Hagrid's]",original,2621.806885,43.565269,60.181126,0.053988,True
63,idd,C,[Quidditch],original,2711.027832,42.632706,63.590332,0.057946,True
64,▁Holmes,C,"[Holmes-style, Holmes]",original,2304.705322,42.339630,54.433762,0.054985,True
65,wiz,C,[wizards],none,2731.500732,42.301434,64.572296,0.000000,False
66,▁Watson,N*,[Watson],extended,1657.996582,41.032364,40.407043,0.036111,True
67,▁Sorcerer,C,[Sorcerer's],none,2425.721191,40.907566,59.297615,0.000000,False
68,▁werewolf,C,[werewolf],extended,2067.451904,40.860458,50.597866,0.034587,True
69,▁dragons,C,[dragons],extended,2127.543457,40.231617,52.882374,0.035407,True
70,▁Grin,C,[Grindelwald],original,2481.941650,39.727444,62.474236,0.058970,True
71,▁Marvel,N*,[Marvel],none,1606.590332,39.544849,40.627045,0.000000,False
72,▁Cedric,C,[Cedric],original,2238.200195,39.067204,57.291027,0.049141,True
73,▁Spells,C*,[Spells],none,2426.187500,38.986233,62.231903,0.000000,False
74,▁spells,C*,[spells],none,2567.478516,38.697128,66.348038,0.000000,False
75,Row,C,"[Rowling, Rowling's]",original,2222.445801,37.717926,58.922798,0.051296,True
76,▁Lily,C,[Lily],extended,1733.429932,36.973804,46.882652,0.035920,True
77,▁Quir,C,"[Quirrell, Quirinus]",original,2658.195557,36.938351,71.963028,0.056406,True
78,▁owls,C,[owls],extended,1878.261963,36.195480,51.892170,0.034874,True
79,▁Charlie,N*,[Charlie],extended,1533.489990,35.570415,43.111389,0.037861,True
80,▁Cinderella,C,[Cinderella],none,1994.697388,35.114201,56.806004,0.000000,False
81,▁Dwar,N*,[Dwaraka],none,1447.094360,34.721413,41.677288,0.000000,False
82,▁Shakespeare,N*,[Shakespeare],none,1457.009766,34.711826,41.974449,0.000000,False
83,blet,C,[Goblet],original,2746.663818,34.353172,79.953720,0.060788,True
84,▁Thames,N*,[Thamesmead],none,1530.607910,34.333931,44.580036,0.000000,False
85,▁Dragon,C,[Dragon],none,1727.331787,34.002491,50.800152,0.000000,False
86,▁fairy,C*,[fairy],none,1975.369141,33.885033,58.296215,0.000000,False
87,▁Bloomsbury,C,[Bloomsbury],extended,2080.242676,33.794601,61.555473,0.036861,True
88,▁Santa,N*,[Santa],none,1390.802856,33.774029,41.179657,0.000000,False
89,▁knight,C,"[knight, knightly]",none,1710.899780,33.291542,51.391426,0.000000,False
90,▁Cursed,C,[Cursed],none,2003.861816,33.219143,60.322502,0.000000,False
91,Sna,C,[Snape],extended,1737.177979,32.416367,53.589535,0.037021,True
92,▁Mag,N*,[Magatha],none,1433.875244,32.415173,44.234695,0.000000,False
93,▁Warlock,C,[Warlock],none,1862.377930,31.790342,58.583134,0.000000,False
94,▁Oxford,C,[Oxford],none,1636.348511,31.662428,51.681080,0.000000,False
95,▁Cumbria,N*,[Cumbria],none,1160.278687,31.326754,37.037949,0.000000,False
96,▁Minerva,C,[Minerva],extended,1910.433228,31.287741,61.060120,0.044297,True
97,▁Wic,C,[Wicca],none,1742.967529,31.161161,55.933971,0.000000,False
98,▁Umb,C,[Umbridge],extended,1877.275635,30.717758,61.113693,0.040371,True
99,▁fantasy,C,[fantasy],none,1749.600464,30.470125,57.420193,0.000000,False
100,▁Beowulf,C*,[Beowulf],extended,1828.993042,30.234921,60.492737,0.046709,True

-- Y_ext support: 95 tokens [C: 68  C*: 8  B: 14  B*: 0  N: 2  N*: 3] | in V*: 84 | in original support: 61/61 --

In [34]:
# ---- Dense refit: fix Z, solve Y' = argmin ||E*^T - Z Y'||_F (no sparsity) ----
TOP_DIRS = 5
HP_FEATS = list(F_C)          # the Harry Potter concept column(s) of Z; override e.g. [37] if you want one
HP_MARK = "★★★ HP ★★★"

A_ref = E_vstar_X.double().cpu().T                                                # (d, |V*|), X-space
Z64 = Z.double()                                                                    # (d, k)
Y_dense = torch.linalg.lstsq(Z64, A_ref).solution.float()                           # (k, |V*|)

dense_err = (torch.norm(A_ref - Z64 @ Y_dense.double()) / torch.norm(A_ref)).item()
sparse_err = (torch.norm(A_ref - Z64 @ Y.double()) / torch.norm(A_ref)).item()
print(f"relative error: sparse Y = {sparse_err:.4f}   dense Y' = {dense_err:.4f}")
print(f"HP feature(s): {HP_FEATS}   (||z|| = {[round(Z[:, f].norm().item(), 3) for f in HP_FEATS]})\n")

for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    print(f"{'=' * 100}\n=== HP feature {hp}: {len(support)} tokens with nonzero Y, by decreasing |Y| ===\n{'=' * 100}")
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        top = order[:TOP_DIRS]

        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}")
        for r, f in enumerate(top, 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        for f in HP_FEATS:
            if f not in top:
                print(f"       ..  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}   <-- {HP_MARK} (rank {order.index(f) + 1}/{len(order)})")

relative error: sparse Y = 0.8528   dense Y' = 0.8103
HP feature(s): [88]   (||z|| = [216.161])

====================================================================================================
=== HP feature 88: 61 tokens with nonzero Y, by decreasing |Y| ===
====================================================================================================

  1. 'ffindor' [C]   sparse Y[88] = -0.310
       #1  z_88   Y' = -0.310   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.141
       #3  z_94   Y' = +0.123
       #4  z_15   Y' = +0.122
       #5  z_96   Y' = +0.090

  2. 'therin' [C]   sparse Y[88] = -0.260
       #1  z_88   Y' = -0.260   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.085
       #3  z_15   Y' = +0.082
       #4  z_85   Y' = -0.081
       #5  z_29   Y' = -0.067

  3. 'umbledore' [C]   sparse Y[88] = -0.212
       #1  z_88   Y' = -0.212   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.036
       #3  z_8    Y' = -0.034
       #4  z_94   Y' = -0.033
       #5  z_96   Y' = -0.031

  4. '▁Dumbledore' [C]   sparse Y[88] = -0.189
       #1  z_88   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_32   Y' = -0.019
       #3  z_37   Y' = -0.017
       #4  z_8    Y' = -0.016
       #5  z_98   Y' = -0.014

  5. '▁Hogwarts' [C]   sparse Y[88] = -0.179
       #1  z_88   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.034
       #3  z_46   Y' = +0.028
       #4  z_64   Y' = +0.025
       #5  z_13   Y' = +0.021

  6. '▁Weasley' [C]   sparse Y[88] = -0.178
       #1  z_88   Y' = -0.178   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.028
       #3  z_89   Y' = +0.020
       #4  z_97   Y' = +0.019
       #5  z_98   Y' = -0.018

  7. '▁Malfoy' [C]   sparse Y[88] = -0.173
       #1  z_88   Y' = -0.173   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.020
       #3  z_11   Y' = +0.018
       #4  z_44   Y' = -0.017
       #5  z_24   Y' = -0.015

  8. '2' [B]   sparse Y[88] = +0.172
       #1  z_39   Y' = -0.314
       #2  z_62   Y' = -0.292
       #3  z_92   Y' = -0.261
       #4  z_22   Y' = +0.252
       #5  z_76   Y' = +0.242
       ..  z_88   Y' = +0.172   <-- ★★★ HP ★★★ (rank 17/100)

  9. '▁Potter' [C]   sparse Y[88] = -0.166
       #1  z_88   Y' = -0.166   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.019
       #3  z_44   Y' = -0.016
       #4  z_67   Y' = -0.016
       #5  z_47   Y' = +0.013

 10. 'Hermione' [C]   sparse Y[88] = -0.164
       #1  z_88   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.025
       #3  z_98   Y' = -0.020
       #4  z_12   Y' = -0.019
       #5  z_29   Y' = +0.019

 11. '4' [B]   sparse Y[88] = +0.164
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.304
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.263
       #5  z_76   Y' = +0.248
       ..  z_88   Y' = +0.164   <-- ★★★ HP ★★★ (rank 19/100)

 12. '▁Rowling' [C]   sparse Y[88] = -0.163
       #1  z_88   Y' = -0.163   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.036
       #3  z_44   Y' = +0.026
       #4  z_68   Y' = +0.023
       #5  z_10   Y' = +0.023

 13. '▁Voldemort' [C]   sparse Y[88] = -0.162
       #1  z_88   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.027
       #3  z_83   Y' = -0.022
       #4  z_31   Y' = -0.017
       #5  z_17   Y' = -0.016

 14. '▁Hermione' [C]   sparse Y[88] = -0.161
       #1  z_88   Y' = -0.161   <-- ★★★ HP ★★★
       #2  z_67   Y' = -0.016
       #3  z_46   Y' = +0.016
       #4  z_35   Y' = -0.013
       #5  z_21   Y' = -0.013

 15. '3' [B]   sparse Y[88] = +0.158
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.303
       #3  z_92   Y' = -0.270
       #4  z_22   Y' = +0.262
       #5  z_76   Y' = +0.246
       ..  z_88   Y' = +0.158   <-- ★★★ HP ★★★ (rank 19/100)

 16. '8' [B]   sparse Y[88] = +0.158
       #1  z_39   Y' = -0.319
       #2  z_62   Y' = -0.298
       #3  z_92   Y' = -0.267
       #4  z_22   Y' = +0.257
       #5  z_76   Y' = +0.239
       ..  z_88   Y' = +0.158   <-- ★★★ HP ★★★ (rank 18/100)

 17. '6' [B]   sparse Y[88] = +0.155
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.301
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.262
       #5  z_76   Y' = +0.247
       ..  z_88   Y' = +0.155   <-- ★★★ HP ★★★ (rank 20/100)

 18. '5' [B]   sparse Y[88] = +0.155
       #1  z_39   Y' = -0.329
       #2  z_62   Y' = -0.312
       #3  z_92   Y' = -0.274
       #4  z_22   Y' = +0.265
       #5  z_76   Y' = +0.256
       ..  z_88   Y' = +0.155   <-- ★★★ HP ★★★ (rank 21/100)

 19. '1' [B]   sparse Y[88] = +0.153
       #1  z_39   Y' = -0.313
       #2  z_62   Y' = -0.288
       #3  z_92   Y' = -0.257
       #4  z_22   Y' = +0.253
       #5  z_76   Y' = +0.238
       ..  z_88   Y' = +0.153   <-- ★★★ HP ★★★ (rank 19/100)

 20. '7' [B]   sparse Y[88] = +0.153
       #1  z_39   Y' = -0.321
       #2  z_62   Y' = -0.305
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.261
       #5  z_76   Y' = +0.246
       ..  z_88   Y' = +0.153   <-- ★★★ HP ★★★ (rank 19/100)

 21. 'demort' [C]   sparse Y[88] = -0.152
       #1  z_88   Y' = -0.152   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.033
       #3  z_21   Y' = -0.028
       #4  z_12   Y' = +0.028
       #5  z_59   Y' = +0.026

 22. '▁Harry' [C]   sparse Y[88] = -0.149
       #1  z_88   Y' = -0.149   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.024
       #3  z_98   Y' = +0.023
       #4  z_40   Y' = +0.021
       #5  z_47   Y' = -0.016

 23. '9' [B]   sparse Y[88] = +0.145
       #1  z_39   Y' = -0.313
       #2  z_62   Y' = -0.292
       #3  z_92   Y' = -0.264
       #4  z_22   Y' = +0.252
       #5  z_76   Y' = +0.238
       ..  z_88   Y' = +0.145   <-- ★★★ HP ★★★ (rank 23/100)

 24. '0' [B]   sparse Y[88] = +0.143
       #1  z_39   Y' = -0.282
       #2  z_62   Y' = -0.270
       #3  z_92   Y' = -0.236
       #4  z_22   Y' = +0.229
       #5  z_76   Y' = +0.215
       ..  z_88   Y' = +0.143   <-- ★★★ HP ★★★ (rank 19/100)

 25. 'Potter' [C]   sparse Y[88] = -0.143
       #1  z_88   Y' = -0.143   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.024
       #3  z_32   Y' = +0.021
       #4  z_44   Y' = -0.015
       #5  z_60   Y' = +0.014

 26. 'Harry' [C]   sparse Y[88] = -0.140
       #1  z_88   Y' = -0.140   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.022
       #3  z_98   Y' = +0.016
       #4  z_47   Y' = -0.015
       #5  z_65   Y' = -0.015

 27. '▁Snape' [C]   sparse Y[88] = -0.136
       #1  z_88   Y' = -0.136   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.020
       #4  z_65   Y' = +0.020
       #5  z_90   Y' = -0.020

 28. '▁Draco' [C]   sparse Y[88] = -0.114
       #1  z_88   Y' = -0.114   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.032
       #3  z_64   Y' = -0.015
       #4  z_89   Y' = -0.014
       #5  z_85   Y' = -0.014

 29. '▁Severus' [C]   sparse Y[88] = -0.111
       #1  z_88   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.024
       #3  z_32   Y' = -0.021
       #4  z_96   Y' = -0.021
       #5  z_94   Y' = -0.019

 30. 'Hog' [C]   sparse Y[88] = -0.109
       #1  z_88   Y' = -0.109   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.019
       #3  z_67   Y' = -0.017
       #4  z_94   Y' = +0.017
       #5  z_42   Y' = -0.015

 31. '▁Gry' [C]   sparse Y[88] = -0.104
       #1  z_88   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.026
       #3  z_24   Y' = -0.020
       #4  z_13   Y' = -0.019
       #5  z_73   Y' = +0.018

 32. '▁Ginny' [C]   sparse Y[88] = -0.101
       #1  z_88   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.028
       #3  z_42   Y' = -0.023
       #4  z_51   Y' = +0.016
       #5  z_97   Y' = -0.016

 33. '▁Hog' [C]   sparse Y[88] = -0.097
       #1  z_88   Y' = -0.097   <-- ★★★ HP ★★★
       #2  z_10   Y' = -0.021
       #3  z_85   Y' = +0.020
       #4  z_43   Y' = -0.019
       #5  z_2    Y' = +0.017

 34. 'otts' [C]   sparse Y[88] = -0.096
       #1  z_88   Y' = -0.096   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.035
       #3  z_20   Y' = +0.030
       #4  z_51   Y' = -0.029
       #5  z_58   Y' = +0.027

 35. 'warts' [C]   sparse Y[88] = -0.087
       #1  z_88   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_69   Y' = -0.027
       #3  z_18   Y' = -0.026
       #4  z_2    Y' = +0.025
       #5  z_24   Y' = -0.025

 36. '▁Remus' [C]   sparse Y[88] = -0.073
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.027
       #3  z_50   Y' = -0.019
       #4  z_26   Y' = -0.018
       #5  z_82   Y' = -0.018

 37. '▁Granger' [C]   sparse Y[88] = -0.073
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_98   Y' = -0.023
       #3  z_11   Y' = +0.022
       #4  z_51   Y' = -0.019
       #5  z_7    Y' = -0.018

 38. '▁Lupin' [C]   sparse Y[88] = -0.072
       #1  z_88   Y' = -0.072   <-- ★★★ HP ★★★
       #2  z_61   Y' = -0.025
       #3  z_32   Y' = +0.023
       #4  z_46   Y' = -0.015
       #5  z_52   Y' = -0.015

 39. '▁wand' [C]   sparse Y[88] = -0.068
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.064
       #3  z_14   Y' = +0.014
       #4  z_3    Y' = -0.014
       #5  z_98   Y' = -0.014

 40. '▁Sly' [C]   sparse Y[88] = -0.068
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.015
       #3  z_19   Y' = +0.015
       #4  z_44   Y' = +0.015
       #5  z_53   Y' = +0.015

 41. '▁JK' [C]   sparse Y[88] = -0.067
       #1  z_88   Y' = -0.067   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.017
       #3  z_55   Y' = -0.015
       #4  z_29   Y' = +0.015
       #5  z_1    Y' = +0.014

 42. '▁wizard' [C]   sparse Y[88] = -0.066
       #1  z_46   Y' = +0.175
       #2  z_88   Y' = -0.066   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.026
       #4  z_66   Y' = -0.016
       #5  z_60   Y' = +0.015

 43. '▁Sirius' [C]   sparse Y[88] = -0.066
       #1  z_88   Y' = -0.066   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.025
       #3  z_31   Y' = -0.019
       #4  z_10   Y' = +0.019
       #5  z_44   Y' = -0.016

 44. '▁Mug' [B]   sparse Y[88] = -0.063
       #1  z_88   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.024
       #3  z_27   Y' = -0.023
       #4  z_42   Y' = +0.023
       #5  z_43   Y' = -0.021

 45. '▁wizards' [C]   sparse Y[88] = -0.062
       #1  z_46   Y' = +0.169
       #2  z_88   Y' = -0.062   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.017
       #4  z_60   Y' = +0.017
       #5  z_67   Y' = +0.011

 46. 'blet' [C]   sparse Y[88] = -0.061
       #1  z_88   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.038
       #3  z_96   Y' = +0.037
       #4  z_89   Y' = -0.034
       #5  z_37   Y' = +0.030

 47. '▁McG' [C]   sparse Y[88] = -0.060
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_72   Y' = -0.021
       #3  z_7    Y' = -0.021
       #4  z_85   Y' = +0.017
       #5  z_1    Y' = +0.016

 48. '▁potions' [C]   sparse Y[88] = -0.060
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.054
       #3  z_37   Y' = -0.023
       #4  z_42   Y' = -0.022
       #5  z_64   Y' = +0.016

 49. '▁Grin' [C]   sparse Y[88] = -0.059
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_51   Y' = +0.024
       #3  z_6    Y' = -0.021
       #4  z_27   Y' = -0.017
       #5  z_85   Y' = +0.017

 50. '▁Sherlock' [C]   sparse Y[88] = -0.059
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.020
       #3  z_50   Y' = -0.020
       #4  z_82   Y' = +0.019
       #5  z_32   Y' = +0.017

 51. 'idd' [C]   sparse Y[88] = -0.058
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.030
       #3  z_29   Y' = -0.025
       #4  z_26   Y' = +0.023
       #5  z_42   Y' = -0.021

 52. '▁Merlin' [C]   sparse Y[88] = -0.058
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.046
       #3  z_54   Y' = -0.019
       #4  z_65   Y' = +0.017
       #5  z_24   Y' = +0.017

 53. '▁Riddle' [C]   sparse Y[88] = -0.057
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.021
       #3  z_50   Y' = -0.018
       #4  z_99   Y' = -0.017
       #5  z_18   Y' = +0.016

 54. '▁Ron' [C]   sparse Y[88] = -0.057
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_7    Y' = -0.018
       #3  z_1    Y' = +0.017
       #4  z_34   Y' = +0.014
       #5  z_32   Y' = +0.012

 55. '▁Quir' [C]   sparse Y[88] = -0.056
       #1  z_88   Y' = -0.056   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.019
       #3  z_47   Y' = -0.019
       #4  z_83   Y' = -0.019
       #5  z_65   Y' = +0.017

 56. 'wizard' [C]   sparse Y[88] = -0.056
       #1  z_46   Y' = +0.141
       #2  z_88   Y' = -0.056   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.028
       #4  z_17   Y' = +0.021
       #5  z_67   Y' = +0.021

 57. '▁Holmes' [C]   sparse Y[88] = -0.055
       #1  z_88   Y' = -0.055   <-- ★★★ HP ★★★
       #2  z_19   Y' = -0.021
       #3  z_8    Y' = +0.021
       #4  z_0    Y' = +0.020
       #5  z_71   Y' = -0.018

 58. '▁Wizard' [C]   sparse Y[88] = -0.054
       #1  z_46   Y' = +0.150
       #2  z_88   Y' = -0.054   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.028
       #4  z_83   Y' = +0.018
       #5  z_32   Y' = -0.015

 59. '▁Hag' [C]   sparse Y[88] = -0.054
       #1  z_88   Y' = -0.054   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.025
       #3  z_17   Y' = +0.016
       #4  z_81   Y' = -0.014
       #5  z_14   Y' = +0.014

 60. 'Row' [C]   sparse Y[88] = -0.051
       #1  z_88   Y' = -0.051   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.018
       #3  z_32   Y' = -0.018
       #4  z_83   Y' = +0.016
       #5  z_21   Y' = +0.015

 61. '▁Cedric' [C]   sparse Y[88] = -0.049
       #1  z_88   Y' = -0.049   <-- ★★★ HP ★★★
       #2  z_21   Y' = +0.028
       #3  z_2    Y' = -0.022
       #4  z_14   Y' = -0.019
       #5  z_47   Y' = +0.018

In [35]:
# ---- Tokens where the HP direction dominates Y': top-1 is HP and |Y'_1| >= RATIO * |Y'_2| ----
RATIO = 2.0

for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    kept = []
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        first, second = y_dense_t[order[0]].abs().item(), y_dense_t[order[1]].abs().item()
        if order[0] == hp and first >= RATIO * second:
            kept.append((rank_t, j, tok, order, first / second))

    print(f"{'=' * 100}\n=== HP feature {hp}: {len(kept)} / {len(support)} tokens where z_{hp} is top-1 "
          f"and |Y'| >= {RATIO:g}x the runner-up ===\n{'=' * 100}")
    for rank_t, j, tok, order, ratio in kept:
        y_dense_t = Y_dense[:, j]
        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}   "
              f"top-1/top-2 = {ratio:.2f}x")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")

====================================================================================================
=== HP feature 88: 41 / 61 tokens where z_88 is top-1 and |Y'| >= 2x the runner-up ===
====================================================================================================

  1. 'ffindor' [C]   sparse Y[88] = -0.310   top-1/top-2 = 2.21x
       #1  z_88   Y' = -0.310   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.141
       #3  z_94   Y' = +0.123
       #4  z_15   Y' = +0.122
       #5  z_96   Y' = +0.090

  2. 'therin' [C]   sparse Y[88] = -0.260   top-1/top-2 = 3.04x
       #1  z_88   Y' = -0.260   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.085
       #3  z_15   Y' = +0.082
       #4  z_85   Y' = -0.081
       #5  z_29   Y' = -0.067

  3. 'umbledore' [C]   sparse Y[88] = -0.212   top-1/top-2 = 5.90x
       #1  z_88   Y' = -0.212   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.036
       #3  z_8    Y' = -0.034
       #4  z_94   Y' = -0.033
       #5  z_96   Y' = -0.031

  4. '▁Dumbledore' [C]   sparse Y[88] = -0.189   top-1/top-2 = 10.12x
       #1  z_88   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_32   Y' = -0.019
       #3  z_37   Y' = -0.017
       #4  z_8    Y' = -0.016
       #5  z_98   Y' = -0.014

  5. '▁Hogwarts' [C]   sparse Y[88] = -0.179   top-1/top-2 = 5.31x
       #1  z_88   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.034
       #3  z_46   Y' = +0.028
       #4  z_64   Y' = +0.025
       #5  z_13   Y' = +0.021

  6. '▁Weasley' [C]   sparse Y[88] = -0.178   top-1/top-2 = 6.29x
       #1  z_88   Y' = -0.178   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.028
       #3  z_89   Y' = +0.020
       #4  z_97   Y' = +0.019
       #5  z_98   Y' = -0.018

  7. '▁Malfoy' [C]   sparse Y[88] = -0.173   top-1/top-2 = 8.63x
       #1  z_88   Y' = -0.173   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.020
       #3  z_11   Y' = +0.018
       #4  z_44   Y' = -0.017
       #5  z_24   Y' = -0.015

  9. '▁Potter' [C]   sparse Y[88] = -0.166   top-1/top-2 = 8.61x
       #1  z_88   Y' = -0.166   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.019
       #3  z_44   Y' = -0.016
       #4  z_67   Y' = -0.016
       #5  z_47   Y' = +0.013

 10. 'Hermione' [C]   sparse Y[88] = -0.164   top-1/top-2 = 6.61x
       #1  z_88   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.025
       #3  z_98   Y' = -0.020
       #4  z_12   Y' = -0.019
       #5  z_29   Y' = +0.019

 12. '▁Rowling' [C]   sparse Y[88] = -0.163   top-1/top-2 = 4.51x
       #1  z_88   Y' = -0.163   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.036
       #3  z_44   Y' = +0.026
       #4  z_68   Y' = +0.023
       #5  z_10   Y' = +0.023

 13. '▁Voldemort' [C]   sparse Y[88] = -0.162   top-1/top-2 = 5.91x
       #1  z_88   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.027
       #3  z_83   Y' = -0.022
       #4  z_31   Y' = -0.017
       #5  z_17   Y' = -0.016

 14. '▁Hermione' [C]   sparse Y[88] = -0.161   top-1/top-2 = 10.41x
       #1  z_88   Y' = -0.161   <-- ★★★ HP ★★★
       #2  z_67   Y' = -0.016
       #3  z_46   Y' = +0.016
       #4  z_35   Y' = -0.013
       #5  z_21   Y' = -0.013

 21. 'demort' [C]   sparse Y[88] = -0.152   top-1/top-2 = 4.56x
       #1  z_88   Y' = -0.152   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.033
       #3  z_21   Y' = -0.028
       #4  z_12   Y' = +0.028
       #5  z_59   Y' = +0.026

 22. '▁Harry' [C]   sparse Y[88] = -0.149   top-1/top-2 = 6.21x
       #1  z_88   Y' = -0.149   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.024
       #3  z_98   Y' = +0.023
       #4  z_40   Y' = +0.021
       #5  z_47   Y' = -0.016

 25. 'Potter' [C]   sparse Y[88] = -0.143   top-1/top-2 = 6.02x
       #1  z_88   Y' = -0.143   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.024
       #3  z_32   Y' = +0.021
       #4  z_44   Y' = -0.015
       #5  z_60   Y' = +0.014

 26. 'Harry' [C]   sparse Y[88] = -0.140   top-1/top-2 = 6.37x
       #1  z_88   Y' = -0.140   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.022
       #3  z_98   Y' = +0.016
       #4  z_47   Y' = -0.015
       #5  z_65   Y' = -0.015

 27. '▁Snape' [C]   sparse Y[88] = -0.136   top-1/top-2 = 5.62x
       #1  z_88   Y' = -0.136   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.020
       #4  z_65   Y' = +0.020
       #5  z_90   Y' = -0.020

 28. '▁Draco' [C]   sparse Y[88] = -0.114   top-1/top-2 = 3.59x
       #1  z_88   Y' = -0.114   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.032
       #3  z_64   Y' = -0.015
       #4  z_89   Y' = -0.014
       #5  z_85   Y' = -0.014

 29. '▁Severus' [C]   sparse Y[88] = -0.111   top-1/top-2 = 4.68x
       #1  z_88   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.024
       #3  z_32   Y' = -0.021
       #4  z_96   Y' = -0.021
       #5  z_94   Y' = -0.019

 30. 'Hog' [C]   sparse Y[88] = -0.109   top-1/top-2 = 5.86x
       #1  z_88   Y' = -0.109   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.019
       #3  z_67   Y' = -0.017
       #4  z_94   Y' = +0.017
       #5  z_42   Y' = -0.015

 31. '▁Gry' [C]   sparse Y[88] = -0.104   top-1/top-2 = 4.04x
       #1  z_88   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.026
       #3  z_24   Y' = -0.020
       #4  z_13   Y' = -0.019
       #5  z_73   Y' = +0.018

 32. '▁Ginny' [C]   sparse Y[88] = -0.101   top-1/top-2 = 3.56x
       #1  z_88   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.028
       #3  z_42   Y' = -0.023
       #4  z_51   Y' = +0.016
       #5  z_97   Y' = -0.016

 33. '▁Hog' [C]   sparse Y[88] = -0.097   top-1/top-2 = 4.63x
       #1  z_88   Y' = -0.097   <-- ★★★ HP ★★★
       #2  z_10   Y' = -0.021
       #3  z_85   Y' = +0.020
       #4  z_43   Y' = -0.019
       #5  z_2    Y' = +0.017

 34. 'otts' [C]   sparse Y[88] = -0.096   top-1/top-2 = 2.74x
       #1  z_88   Y' = -0.096   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.035
       #3  z_20   Y' = +0.030
       #4  z_51   Y' = -0.029
       #5  z_58   Y' = +0.027

 35. 'warts' [C]   sparse Y[88] = -0.087   top-1/top-2 = 3.18x
       #1  z_88   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_69   Y' = -0.027
       #3  z_18   Y' = -0.026
       #4  z_2    Y' = +0.025
       #5  z_24   Y' = -0.025

 36. '▁Remus' [C]   sparse Y[88] = -0.073   top-1/top-2 = 2.68x
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.027
       #3  z_50   Y' = -0.019
       #4  z_26   Y' = -0.018
       #5  z_82   Y' = -0.018

 37. '▁Granger' [C]   sparse Y[88] = -0.073   top-1/top-2 = 3.17x
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_98   Y' = -0.023
       #3  z_11   Y' = +0.022
       #4  z_51   Y' = -0.019
       #5  z_7    Y' = -0.018

 38. '▁Lupin' [C]   sparse Y[88] = -0.072   top-1/top-2 = 2.90x
       #1  z_88   Y' = -0.072   <-- ★★★ HP ★★★
       #2  z_61   Y' = -0.025
       #3  z_32   Y' = +0.023
       #4  z_46   Y' = -0.015
       #5  z_52   Y' = -0.015

 40. '▁Sly' [C]   sparse Y[88] = -0.068   top-1/top-2 = 4.44x
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.015
       #3  z_19   Y' = +0.015
       #4  z_44   Y' = +0.015
       #5  z_53   Y' = +0.015

 41. '▁JK' [C]   sparse Y[88] = -0.067   top-1/top-2 = 4.00x
       #1  z_88   Y' = -0.067   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.017
       #3  z_55   Y' = -0.015
       #4  z_29   Y' = +0.015
       #5  z_1    Y' = +0.014

 43. '▁Sirius' [C]   sparse Y[88] = -0.066   top-1/top-2 = 2.69x
       #1  z_88   Y' = -0.066   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.025
       #3  z_31   Y' = -0.019
       #4  z_10   Y' = +0.019
       #5  z_44   Y' = -0.016

 44. '▁Mug' [B]   sparse Y[88] = -0.063   top-1/top-2 = 2.59x
       #1  z_88   Y' = -0.063   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.024
       #3  z_27   Y' = -0.023
       #4  z_42   Y' = +0.023
       #5  z_43   Y' = -0.021

 47. '▁McG' [C]   sparse Y[88] = -0.060   top-1/top-2 = 2.81x
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_72   Y' = -0.021
       #3  z_7    Y' = -0.021
       #4  z_85   Y' = +0.017
       #5  z_1    Y' = +0.016

 49. '▁Grin' [C]   sparse Y[88] = -0.059   top-1/top-2 = 2.51x
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_51   Y' = +0.024
       #3  z_6    Y' = -0.021
       #4  z_27   Y' = -0.017
       #5  z_85   Y' = +0.017

 50. '▁Sherlock' [C]   sparse Y[88] = -0.059   top-1/top-2 = 2.93x
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.020
       #3  z_50   Y' = -0.020
       #4  z_82   Y' = +0.019
       #5  z_32   Y' = +0.017

 53. '▁Riddle' [C]   sparse Y[88] = -0.057   top-1/top-2 = 2.69x
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.021
       #3  z_50   Y' = -0.018
       #4  z_99   Y' = -0.017
       #5  z_18   Y' = +0.016

 54. '▁Ron' [C]   sparse Y[88] = -0.057   top-1/top-2 = 3.15x
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_7    Y' = -0.018
       #3  z_1    Y' = +0.017
       #4  z_34   Y' = +0.014
       #5  z_32   Y' = +0.012

 55. '▁Quir' [C]   sparse Y[88] = -0.056   top-1/top-2 = 2.91x
       #1  z_88   Y' = -0.056   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.019
       #3  z_47   Y' = -0.019
       #4  z_83   Y' = -0.019
       #5  z_65   Y' = +0.017

 57. '▁Holmes' [C]   sparse Y[88] = -0.055   top-1/top-2 = 2.58x
       #1  z_88   Y' = -0.055   <-- ★★★ HP ★★★
       #2  z_19   Y' = -0.021
       #3  z_8    Y' = +0.021
       #4  z_0    Y' = +0.020
       #5  z_71   Y' = -0.018

 59. '▁Hag' [C]   sparse Y[88] = -0.054   top-1/top-2 = 2.12x
       #1  z_88   Y' = -0.054   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.025
       #3  z_17   Y' = +0.016
       #4  z_81   Y' = -0.014
       #5  z_14   Y' = +0.014

 60. 'Row' [C]   sparse Y[88] = -0.051   top-1/top-2 = 2.81x
       #1  z_88   Y' = -0.051   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.018
       #3  z_32   Y' = -0.018
       #4  z_83   Y' = +0.016
       #5  z_21   Y' = +0.015

In [36]:
# ---- Tokens skipped by the previous cell: HP is not top-1, or top-1 but < RATIO x the runner-up ----
for hp in HP_FEATS:
    mags = Y[hp].abs()
    support = torch.nonzero(mags > 0).flatten()
    support = support[torch.argsort(mags[support], descending=True)].tolist()
    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in support])

    skipped = []
    for rank_t, (j, tok) in enumerate(zip(support, toks), 1):
        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        first, second = y_dense_t[order[0]].abs().item(), y_dense_t[order[1]].abs().item()
        if order[0] != hp:
            skipped.append((rank_t, j, tok, order, f"HP is not top-1 (rank {order.index(hp) + 1}/{len(order)})"))
        elif first < RATIO * second:
            skipped.append((rank_t, j, tok, order, f"HP is top-1 but only {first / second:.2f}x the runner-up"))

    n_not_top = sum(r.startswith("HP is not") for *_, r in skipped)
    print(f"{'=' * 100}\n=== HP feature {hp}: {len(skipped)} / {len(support)} tokens skipped "
          f"({n_not_top} HP not top-1, {len(skipped) - n_not_top} top-1 but < {RATIO:g}x) ===\n{'=' * 100}")
    for rank_t, j, tok, order, reason in skipped:
        y_dense_t = Y_dense[:, j]
        print(f"\n{rank_t:3d}. {tok!r} [{LABEL_TAG[codes[j]]}]   sparse Y[{hp}] = {Y[hp, j]:+.3f}   -> {reason}")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        if hp not in order[:TOP_DIRS]:
            print(f"       ..  z_{hp:<4d} Y' = {y_dense_t[hp]:+.3f}   <-- {HP_MARK} (rank {order.index(hp) + 1}/{len(order)})")

====================================================================================================
=== HP feature 88: 20 / 61 tokens skipped (14 HP not top-1, 6 top-1 but < 2x) ===
====================================================================================================

  8. '2' [B]   sparse Y[88] = +0.172   -> HP is not top-1 (rank 17/100)
       #1  z_39   Y' = -0.314
       #2  z_62   Y' = -0.292
       #3  z_92   Y' = -0.261
       #4  z_22   Y' = +0.252
       #5  z_76   Y' = +0.242
       ..  z_88   Y' = +0.172   <-- ★★★ HP ★★★ (rank 17/100)

 11. '4' [B]   sparse Y[88] = +0.164   -> HP is not top-1 (rank 19/100)
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.304
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.263
       #5  z_76   Y' = +0.248
       ..  z_88   Y' = +0.164   <-- ★★★ HP ★★★ (rank 19/100)

 15. '3' [B]   sparse Y[88] = +0.158   -> HP is not top-1 (rank 19/100)
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.303
       #3  z_92   Y' = -0.270
       #4  z_22   Y' = +0.262
       #5  z_76   Y' = +0.246
       ..  z_88   Y' = +0.158   <-- ★★★ HP ★★★ (rank 19/100)

 16. '8' [B]   sparse Y[88] = +0.158   -> HP is not top-1 (rank 18/100)
       #1  z_39   Y' = -0.319
       #2  z_62   Y' = -0.298
       #3  z_92   Y' = -0.267
       #4  z_22   Y' = +0.257
       #5  z_76   Y' = +0.239
       ..  z_88   Y' = +0.158   <-- ★★★ HP ★★★ (rank 18/100)

 17. '6' [B]   sparse Y[88] = +0.155   -> HP is not top-1 (rank 20/100)
       #1  z_39   Y' = -0.323
       #2  z_62   Y' = -0.301
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.262
       #5  z_76   Y' = +0.247
       ..  z_88   Y' = +0.155   <-- ★★★ HP ★★★ (rank 20/100)

 18. '5' [B]   sparse Y[88] = +0.155   -> HP is not top-1 (rank 21/100)
       #1  z_39   Y' = -0.329
       #2  z_62   Y' = -0.312
       #3  z_92   Y' = -0.274
       #4  z_22   Y' = +0.265
       #5  z_76   Y' = +0.256
       ..  z_88   Y' = +0.155   <-- ★★★ HP ★★★ (rank 21/100)

 19. '1' [B]   sparse Y[88] = +0.153   -> HP is not top-1 (rank 19/100)
       #1  z_39   Y' = -0.313
       #2  z_62   Y' = -0.288
       #3  z_92   Y' = -0.257
       #4  z_22   Y' = +0.253
       #5  z_76   Y' = +0.238
       ..  z_88   Y' = +0.153   <-- ★★★ HP ★★★ (rank 19/100)

 20. '7' [B]   sparse Y[88] = +0.153   -> HP is not top-1 (rank 19/100)
       #1  z_39   Y' = -0.321
       #2  z_62   Y' = -0.305
       #3  z_92   Y' = -0.271
       #4  z_22   Y' = +0.261
       #5  z_76   Y' = +0.246
       ..  z_88   Y' = +0.153   <-- ★★★ HP ★★★ (rank 19/100)

 23. '9' [B]   sparse Y[88] = +0.145   -> HP is not top-1 (rank 23/100)
       #1  z_39   Y' = -0.313
       #2  z_62   Y' = -0.292
       #3  z_92   Y' = -0.264
       #4  z_22   Y' = +0.252
       #5  z_76   Y' = +0.238
       ..  z_88   Y' = +0.145   <-- ★★★ HP ★★★ (rank 23/100)

 24. '0' [B]   sparse Y[88] = +0.143   -> HP is not top-1 (rank 19/100)
       #1  z_39   Y' = -0.282
       #2  z_62   Y' = -0.270
       #3  z_92   Y' = -0.236
       #4  z_22   Y' = +0.229
       #5  z_76   Y' = +0.215
       ..  z_88   Y' = +0.143   <-- ★★★ HP ★★★ (rank 19/100)

 39. '▁wand' [C]   sparse Y[88] = -0.068   -> HP is top-1 but only 1.06x the runner-up
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.064
       #3  z_14   Y' = +0.014
       #4  z_3    Y' = -0.014
       #5  z_98   Y' = -0.014

 42. '▁wizard' [C]   sparse Y[88] = -0.066   -> HP is not top-1 (rank 2/100)
       #1  z_46   Y' = +0.175
       #2  z_88   Y' = -0.066   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.026
       #4  z_66   Y' = -0.016
       #5  z_60   Y' = +0.015

 45. '▁wizards' [C]   sparse Y[88] = -0.062   -> HP is not top-1 (rank 2/100)
       #1  z_46   Y' = +0.169
       #2  z_88   Y' = -0.062   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.017
       #4  z_60   Y' = +0.017
       #5  z_67   Y' = +0.011

 46. 'blet' [C]   sparse Y[88] = -0.061   -> HP is top-1 but only 1.59x the runner-up
       #1  z_88   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.038
       #3  z_96   Y' = +0.037
       #4  z_89   Y' = -0.034
       #5  z_37   Y' = +0.030

 48. '▁potions' [C]   sparse Y[88] = -0.060   -> HP is top-1 but only 1.10x the runner-up
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.054
       #3  z_37   Y' = -0.023
       #4  z_42   Y' = -0.022
       #5  z_64   Y' = +0.016

 51. 'idd' [C]   sparse Y[88] = -0.058   -> HP is top-1 but only 1.93x the runner-up
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.030
       #3  z_29   Y' = -0.025
       #4  z_26   Y' = +0.023
       #5  z_42   Y' = -0.021

 52. '▁Merlin' [C]   sparse Y[88] = -0.058   -> HP is top-1 but only 1.26x the runner-up
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.046
       #3  z_54   Y' = -0.019
       #4  z_65   Y' = +0.017
       #5  z_24   Y' = +0.017

 56. 'wizard' [C]   sparse Y[88] = -0.056   -> HP is not top-1 (rank 2/100)
       #1  z_46   Y' = +0.141
       #2  z_88   Y' = -0.056   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.028
       #4  z_17   Y' = +0.021
       #5  z_67   Y' = +0.021

 58. '▁Wizard' [C]   sparse Y[88] = -0.054   -> HP is not top-1 (rank 2/100)
       #1  z_46   Y' = +0.150
       #2  z_88   Y' = -0.054   <-- ★★★ HP ★★★
       #3  z_10   Y' = +0.028
       #4  z_83   Y' = +0.018
       #5  z_32   Y' = -0.015

 61. '▁Cedric' [C]   sparse Y[88] = -0.049   -> HP is top-1 but only 1.78x the runner-up
       #1  z_88   Y' = -0.049   <-- ★★★ HP ★★★
       #2  z_21   Y' = +0.028
       #3  z_2    Y' = -0.022
       #4  z_14   Y' = -0.019
       #5  z_47   Y' = +0.018

In [37]:
# ---- All C-labelled tokens, sorted by |Y'_HP| / max_{i != HP} |Y'_i| (= top-1/top-2 when HP is top-1) ----
for hp in HP_FEATS:
    c_cols = np.where(codes == 1)[0].tolist()
    rows = []
    for j in c_cols:
        y_dense_t = Y_dense[:, j]
        others_max = torch.cat([y_dense_t[:hp], y_dense_t[hp + 1:]]).abs().max().item()
        rows.append((y_dense_t[hp].abs().item() / others_max, j))
    rows.sort(reverse=True)

    toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for _, j in rows])
    n_pass = sum(r >= RATIO for r, _ in rows)
    n_top1 = sum(r >= 1.0 for r, _ in rows)
    print(f"{'=' * 100}\n=== HP feature {hp}: {len(rows)} C tokens | HP top-1: {n_top1} | "
          f"HP top-1 and >= {RATIO:g}x: {n_pass} ===\n{'=' * 100}")

    shown_ratio_line = shown_top1_line = False
    for rank_t, ((ratio, j), tok) in enumerate(zip(rows, toks), 1):
        if not shown_ratio_line and ratio < RATIO:
            print(f"\n{'-' * 40} below {RATIO:g}x {'-' * 40}")
            shown_ratio_line = True
        if not shown_top1_line and ratio < 1.0:
            print(f"\n{'-' * 36} HP no longer top-1 {'-' * 36}")
            shown_top1_line = True

        y_dense_t = Y_dense[:, j]
        order = torch.argsort(y_dense_t.abs(), descending=True).tolist()
        in_support = "in HP support" if Y[hp, j] != 0 else "not in HP support"
        print(f"\n{rank_t:3d}. {tok!r} [C]   ratio = {ratio:.2f}x   sparse Y[{hp}] = {Y[hp, j]:+.3f}  ({in_support})")
        for r, f in enumerate(order[:TOP_DIRS], 1):
            mark = f"   <-- {HP_MARK}" if f in HP_FEATS else ""
            print(f"       #{r}  z_{f:<4d} Y' = {y_dense_t[f]:+.3f}{mark}")
        if hp not in order[:TOP_DIRS]:
            print(f"       ..  z_{hp:<4d} Y' = {y_dense_t[hp]:+.3f}   <-- {HP_MARK} (rank {order.index(hp) + 1}/{len(order)})")

====================================================================================================
=== HP feature 88: 1870 C tokens | HP top-1: 92 | HP top-1 and >= 2x: 42 ===
====================================================================================================

  1. '▁Hermione' [C]   ratio = 10.41x   sparse Y[88] = -0.161  (in HP support)
       #1  z_88   Y' = -0.161   <-- ★★★ HP ★★★
       #2  z_67   Y' = -0.016
       #3  z_46   Y' = +0.016
       #4  z_35   Y' = -0.013
       #5  z_21   Y' = -0.013

  2. '▁Dumbledore' [C]   ratio = 10.12x   sparse Y[88] = -0.189  (in HP support)
       #1  z_88   Y' = -0.189   <-- ★★★ HP ★★★
       #2  z_32   Y' = -0.019
       #3  z_37   Y' = -0.017
       #4  z_8    Y' = -0.016
       #5  z_98   Y' = -0.014

  3. '▁Malfoy' [C]   ratio = 8.63x   sparse Y[88] = -0.173  (in HP support)
       #1  z_88   Y' = -0.173   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.020
       #3  z_11   Y' = +0.018
       #4  z_44   Y' = -0.017
       #5  z_24   Y' = -0.015

  4. '▁Potter' [C]   ratio = 8.61x   sparse Y[88] = -0.166  (in HP support)
       #1  z_88   Y' = -0.166   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.019
       #3  z_44   Y' = -0.016
       #4  z_67   Y' = -0.016
       #5  z_47   Y' = +0.013

  5. 'Hermione' [C]   ratio = 6.61x   sparse Y[88] = -0.164  (in HP support)
       #1  z_88   Y' = -0.164   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.025
       #3  z_98   Y' = -0.020
       #4  z_12   Y' = -0.019
       #5  z_29   Y' = +0.019

  6. 'Harry' [C]   ratio = 6.37x   sparse Y[88] = -0.140  (in HP support)
       #1  z_88   Y' = -0.140   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.022
       #3  z_98   Y' = +0.016
       #4  z_47   Y' = -0.015
       #5  z_65   Y' = -0.015

  7. '▁Weasley' [C]   ratio = 6.29x   sparse Y[88] = -0.178  (in HP support)
       #1  z_88   Y' = -0.178   <-- ★★★ HP ★★★
       #2  z_84   Y' = -0.028
       #3  z_89   Y' = +0.020
       #4  z_97   Y' = +0.019
       #5  z_98   Y' = -0.018

  8. '▁Harry' [C]   ratio = 6.21x   sparse Y[88] = -0.149  (in HP support)
       #1  z_88   Y' = -0.149   <-- ★★★ HP ★★★
       #2  z_43   Y' = +0.024
       #3  z_98   Y' = +0.023
       #4  z_40   Y' = +0.021
       #5  z_47   Y' = -0.016

  9. 'Potter' [C]   ratio = 6.02x   sparse Y[88] = -0.143  (in HP support)
       #1  z_88   Y' = -0.143   <-- ★★★ HP ★★★
       #2  z_5    Y' = -0.024
       #3  z_32   Y' = +0.021
       #4  z_44   Y' = -0.015
       #5  z_60   Y' = +0.014

 10. '▁Voldemort' [C]   ratio = 5.91x   sparse Y[88] = -0.162  (in HP support)
       #1  z_88   Y' = -0.162   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.027
       #3  z_83   Y' = -0.022
       #4  z_31   Y' = -0.017
       #5  z_17   Y' = -0.016

 11. 'umbledore' [C]   ratio = 5.90x   sparse Y[88] = -0.212  (in HP support)
       #1  z_88   Y' = -0.212   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.036
       #3  z_8    Y' = -0.034
       #4  z_94   Y' = -0.033
       #5  z_96   Y' = -0.031

 12. 'Hog' [C]   ratio = 5.86x   sparse Y[88] = -0.109  (in HP support)
       #1  z_88   Y' = -0.109   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.019
       #3  z_67   Y' = -0.017
       #4  z_94   Y' = +0.017
       #5  z_42   Y' = -0.015

 13. '▁Snape' [C]   ratio = 5.62x   sparse Y[88] = -0.136  (in HP support)
       #1  z_88   Y' = -0.136   <-- ★★★ HP ★★★
       #2  z_2    Y' = -0.024
       #3  z_47   Y' = +0.020
       #4  z_65   Y' = +0.020
       #5  z_90   Y' = -0.020

 14. '▁Hogwarts' [C]   ratio = 5.31x   sparse Y[88] = -0.179  (in HP support)
       #1  z_88   Y' = -0.179   <-- ★★★ HP ★★★
       #2  z_30   Y' = +0.034
       #3  z_46   Y' = +0.028
       #4  z_64   Y' = +0.025
       #5  z_13   Y' = +0.021

 15. '▁Severus' [C]   ratio = 4.68x   sparse Y[88] = -0.111  (in HP support)
       #1  z_88   Y' = -0.111   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.024
       #3  z_32   Y' = -0.021
       #4  z_96   Y' = -0.021
       #5  z_94   Y' = -0.019

 16. '▁Hog' [C]   ratio = 4.63x   sparse Y[88] = -0.097  (in HP support)
       #1  z_88   Y' = -0.097   <-- ★★★ HP ★★★
       #2  z_10   Y' = -0.021
       #3  z_85   Y' = +0.020
       #4  z_43   Y' = -0.019
       #5  z_2    Y' = +0.017

 17. 'demort' [C]   ratio = 4.56x   sparse Y[88] = -0.152  (in HP support)
       #1  z_88   Y' = -0.152   <-- ★★★ HP ★★★
       #2  z_17   Y' = -0.033
       #3  z_21   Y' = -0.028
       #4  z_12   Y' = +0.028
       #5  z_59   Y' = +0.026

 18. '▁Rowling' [C]   ratio = 4.51x   sparse Y[88] = -0.163  (in HP support)
       #1  z_88   Y' = -0.163   <-- ★★★ HP ★★★
       #2  z_50   Y' = +0.036
       #3  z_44   Y' = +0.026
       #4  z_68   Y' = +0.023
       #5  z_10   Y' = +0.023

 19. '▁Sly' [C]   ratio = 4.44x   sparse Y[88] = -0.068  (in HP support)
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.015
       #3  z_19   Y' = +0.015
       #4  z_44   Y' = +0.015
       #5  z_53   Y' = +0.015

 20. '▁Gry' [C]   ratio = 4.04x   sparse Y[88] = -0.104  (in HP support)
       #1  z_88   Y' = -0.104   <-- ★★★ HP ★★★
       #2  z_50   Y' = -0.026
       #3  z_24   Y' = -0.020
       #4  z_13   Y' = -0.019
       #5  z_73   Y' = +0.018

 21. '▁JK' [C]   ratio = 4.00x   sparse Y[88] = -0.067  (in HP support)
       #1  z_88   Y' = -0.067   <-- ★★★ HP ★★★
       #2  z_27   Y' = -0.017
       #3  z_55   Y' = -0.015
       #4  z_29   Y' = +0.015
       #5  z_1    Y' = +0.014

 22. '▁Draco' [C]   ratio = 3.59x   sparse Y[88] = -0.114  (in HP support)
       #1  z_88   Y' = -0.114   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.032
       #3  z_64   Y' = -0.015
       #4  z_89   Y' = -0.014
       #5  z_85   Y' = -0.014

 23. '▁Ginny' [C]   ratio = 3.56x   sparse Y[88] = -0.101  (in HP support)
       #1  z_88   Y' = -0.101   <-- ★★★ HP ★★★
       #2  z_25   Y' = -0.028
       #3  z_42   Y' = -0.023
       #4  z_51   Y' = +0.016
       #5  z_97   Y' = -0.016

 24. 'warts' [C]   ratio = 3.18x   sparse Y[88] = -0.087  (in HP support)
       #1  z_88   Y' = -0.087   <-- ★★★ HP ★★★
       #2  z_69   Y' = -0.027
       #3  z_18   Y' = -0.026
       #4  z_2    Y' = +0.025
       #5  z_24   Y' = -0.025

 25. '▁Granger' [C]   ratio = 3.17x   sparse Y[88] = -0.073  (in HP support)
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_98   Y' = -0.023
       #3  z_11   Y' = +0.022
       #4  z_51   Y' = -0.019
       #5  z_7    Y' = -0.018

 26. '▁Ron' [C]   ratio = 3.15x   sparse Y[88] = -0.057  (in HP support)
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_7    Y' = -0.018
       #3  z_1    Y' = +0.017
       #4  z_34   Y' = +0.014
       #5  z_32   Y' = +0.012

 27. 'therin' [C]   ratio = 3.04x   sparse Y[88] = -0.260  (in HP support)
       #1  z_88   Y' = -0.260   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.085
       #3  z_15   Y' = +0.082
       #4  z_85   Y' = -0.081
       #5  z_29   Y' = -0.067

 28. '▁Sherlock' [C]   ratio = 2.93x   sparse Y[88] = -0.059  (in HP support)
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.020
       #3  z_50   Y' = -0.020
       #4  z_82   Y' = +0.019
       #5  z_32   Y' = +0.017

 29. '▁Quir' [C]   ratio = 2.91x   sparse Y[88] = -0.056  (in HP support)
       #1  z_88   Y' = -0.056   <-- ★★★ HP ★★★
       #2  z_69   Y' = +0.019
       #3  z_47   Y' = -0.019
       #4  z_83   Y' = -0.019
       #5  z_65   Y' = +0.017

 30. '▁Lupin' [C]   ratio = 2.90x   sparse Y[88] = -0.072  (in HP support)
       #1  z_88   Y' = -0.072   <-- ★★★ HP ★★★
       #2  z_61   Y' = -0.025
       #3  z_32   Y' = +0.023
       #4  z_46   Y' = -0.015
       #5  z_52   Y' = -0.015

 31. 'Row' [C]   ratio = 2.81x   sparse Y[88] = -0.051  (in HP support)
       #1  z_88   Y' = -0.051   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.018
       #3  z_32   Y' = -0.018
       #4  z_83   Y' = +0.016
       #5  z_21   Y' = +0.015

 32. '▁McG' [C]   ratio = 2.81x   sparse Y[88] = -0.060  (in HP support)
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_72   Y' = -0.021
       #3  z_7    Y' = -0.021
       #4  z_85   Y' = +0.017
       #5  z_1    Y' = +0.016

 33. 'otts' [C]   ratio = 2.74x   sparse Y[88] = -0.096  (in HP support)
       #1  z_88   Y' = -0.096   <-- ★★★ HP ★★★
       #2  z_32   Y' = +0.035
       #3  z_20   Y' = +0.030
       #4  z_51   Y' = -0.029
       #5  z_58   Y' = +0.027

 34. '▁Sirius' [C]   ratio = 2.69x   sparse Y[88] = -0.066  (in HP support)
       #1  z_88   Y' = -0.066   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.025
       #3  z_31   Y' = -0.019
       #4  z_10   Y' = +0.019
       #5  z_44   Y' = -0.016

 35. '▁Riddle' [C]   ratio = 2.69x   sparse Y[88] = -0.057  (in HP support)
       #1  z_88   Y' = -0.057   <-- ★★★ HP ★★★
       #2  z_8    Y' = +0.021
       #3  z_50   Y' = -0.018
       #4  z_99   Y' = -0.017
       #5  z_18   Y' = +0.016

 36. '▁Remus' [C]   ratio = 2.68x   sparse Y[88] = -0.073  (in HP support)
       #1  z_88   Y' = -0.073   <-- ★★★ HP ★★★
       #2  z_53   Y' = +0.027
       #3  z_50   Y' = -0.019
       #4  z_26   Y' = -0.018
       #5  z_82   Y' = -0.018

 37. '▁Holmes' [C]   ratio = 2.58x   sparse Y[88] = -0.055  (in HP support)
       #1  z_88   Y' = -0.055   <-- ★★★ HP ★★★
       #2  z_19   Y' = -0.021
       #3  z_8    Y' = +0.021
       #4  z_0    Y' = +0.020
       #5  z_71   Y' = -0.018

 38. '▁Grin' [C]   ratio = 2.51x   sparse Y[88] = -0.059  (in HP support)
       #1  z_88   Y' = -0.059   <-- ★★★ HP ★★★
       #2  z_51   Y' = +0.024
       #3  z_6    Y' = -0.021
       #4  z_27   Y' = -0.017
       #5  z_85   Y' = +0.017

 39. '▁Lily' [C]   ratio = 2.43x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.036   <-- ★★★ HP ★★★
       #2  z_84   Y' = +0.015
       #3  z_85   Y' = +0.014
       #4  z_42   Y' = +0.012
       #5  z_24   Y' = +0.012

 40. 'Sna' [C]   ratio = 2.29x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.037   <-- ★★★ HP ★★★
       #2  z_67   Y' = -0.016
       #3  z_50   Y' = -0.014
       #4  z_57   Y' = +0.014
       #5  z_58   Y' = +0.013

 41. 'ffindor' [C]   ratio = 2.21x   sparse Y[88] = -0.310  (in HP support)
       #1  z_88   Y' = -0.310   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.141
       #3  z_94   Y' = +0.123
       #4  z_15   Y' = +0.122
       #5  z_96   Y' = +0.090

 42. '▁Hag' [C]   ratio = 2.12x   sparse Y[88] = -0.054  (in HP support)
       #1  z_88   Y' = -0.054   <-- ★★★ HP ★★★
       #2  z_24   Y' = -0.025
       #3  z_17   Y' = +0.016
       #4  z_81   Y' = -0.014
       #5  z_14   Y' = +0.014

---------------------------------------- below 2x ----------------------------------------

 43. 'idd' [C]   ratio = 1.93x   sparse Y[88] = -0.058  (in HP support)
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_89   Y' = +0.030
       #3  z_29   Y' = -0.025
       #4  z_26   Y' = +0.023
       #5  z_42   Y' = -0.021

 44. '▁Umb' [C]   ratio = 1.85x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.040   <-- ★★★ HP ★★★
       #2  z_58   Y' = -0.022
       #3  z_42   Y' = +0.021
       #4  z_18   Y' = +0.021
       #5  z_3    Y' = -0.019

 45. '▁Cedric' [C]   ratio = 1.78x   sparse Y[88] = -0.049  (in HP support)
       #1  z_88   Y' = -0.049   <-- ★★★ HP ★★★
       #2  z_21   Y' = +0.028
       #3  z_2    Y' = -0.022
       #4  z_14   Y' = -0.019
       #5  z_47   Y' = +0.018

 46. '▁Beatles' [C]   ratio = 1.75x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.035   <-- ★★★ HP ★★★
       #2  z_40   Y' = +0.020
       #3  z_7    Y' = -0.019
       #4  z_53   Y' = -0.018
       #5  z_90   Y' = -0.017

 47. '▁Minerva' [C]   ratio = 1.66x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.044   <-- ★★★ HP ★★★
       #2  z_8    Y' = -0.027
       #3  z_17   Y' = +0.021
       #4  z_5    Y' = -0.021
       #5  z_10   Y' = +0.018

 48. '▁Patron' [C]   ratio = 1.62x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.031   <-- ★★★ HP ★★★
       #2  z_76   Y' = +0.019
       #3  z_32   Y' = +0.019
       #4  z_85   Y' = +0.016
       #5  z_89   Y' = +0.015

 49. '▁Harold' [C]   ratio = 1.60x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.026   <-- ★★★ HP ★★★
       #2  z_7    Y' = -0.016
       #3  z_53   Y' = -0.013
       #4  z_5    Y' = +0.013
       #5  z_83   Y' = -0.013

 50. 'blet' [C]   ratio = 1.59x   sparse Y[88] = -0.061  (in HP support)
       #1  z_88   Y' = -0.061   <-- ★★★ HP ★★★
       #2  z_94   Y' = +0.038
       #3  z_96   Y' = +0.037
       #4  z_89   Y' = -0.034
       #5  z_37   Y' = +0.030

 51. '▁Faw' [C]   ratio = 1.56x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.038   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.024
       #3  z_51   Y' = +0.019
       #4  z_68   Y' = -0.017
       #5  z_47   Y' = +0.017

 52. '▁Moody' [C]   ratio = 1.55x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.031   <-- ★★★ HP ★★★
       #2  z_76   Y' = +0.020
       #3  z_42   Y' = +0.016
       #4  z_37   Y' = +0.016
       #5  z_31   Y' = +0.016

 53. '▁Sorting' [C]   ratio = 1.52x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.027   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.018
       #3  z_84   Y' = -0.016
       #4  z_94   Y' = -0.016
       #5  z_49   Y' = -0.013

 54. 'Quir' [C]   ratio = 1.50x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.040   <-- ★★★ HP ★★★
       #2  z_60   Y' = +0.027
       #3  z_56   Y' = +0.026
       #4  z_68   Y' = -0.020
       #5  z_43   Y' = +0.016

 55. '▁Molly' [C]   ratio = 1.37x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.032   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.023
       #3  z_24   Y' = +0.015
       #4  z_13   Y' = +0.014
       #5  z_52   Y' = -0.013

 56. '▁Tom' [C]   ratio = 1.35x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.032   <-- ★★★ HP ★★★
       #2  z_1    Y' = +0.024
       #3  z_19   Y' = -0.021
       #4  z_42   Y' = +0.017
       #5  z_11   Y' = -0.017

 57. '▁Dolores' [C]   ratio = 1.33x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.024   <-- ★★★ HP ★★★
       #2  z_24   Y' = +0.018
       #3  z_26   Y' = +0.018
       #4  z_12   Y' = +0.018
       #5  z_42   Y' = -0.016

 58. '▁Thomas' [C]   ratio = 1.33x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.028   <-- ★★★ HP ★★★
       #2  z_1    Y' = +0.021
       #3  z_42   Y' = +0.020
       #4  z_47   Y' = -0.018
       #5  z_31   Y' = +0.015

 59. 'moral' [C]   ratio = 1.29x   sparse Y[88] = +0.000  (not in HP support)
       #1  z_88   Y' = +0.033   <-- ★★★ HP ★★★
       #2  z_36   Y' = -0.026
       #3  z_98   Y' = +0.023
       #4  z_67   Y' = +0.023
       #5  z_44   Y' = -0.019

 60. '▁Merlin' [C]   ratio = 1.26x   sparse Y[88] = -0.058  (in HP support)
       #1  z_88   Y' = -0.058   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.046
       #3  z_54   Y' = -0.019
       #4  z_65   Y' = +0.017
       #5  z_24   Y' = +0.017

 61. 'rn' [C]   ratio = 1.24x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.023   <-- ★★★ HP ★★★
       #2  z_65   Y' = -0.019
       #3  z_33   Y' = -0.016
       #4  z_90   Y' = -0.015
       #5  z_46   Y' = -0.014

 62. '▁Dragon' [C]   ratio = 1.20x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.028   <-- ★★★ HP ★★★
       #2  z_65   Y' = +0.023
       #3  z_46   Y' = +0.016
       #4  z_85   Y' = -0.016
       #5  z_75   Y' = -0.014

 63. '▁reversed' [C]   ratio = 1.18x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.021   <-- ★★★ HP ★★★
       #2  z_89   Y' = -0.018
       #3  z_48   Y' = +0.018
       #4  z_32   Y' = -0.017
       #5  z_25   Y' = -0.014

 64. '▁knight' [C]   ratio = 1.17x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.030   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.026
       #3  z_42   Y' = +0.026
       #4  z_67   Y' = +0.023
       #5  z_27   Y' = -0.016

 65. 'Stephen' [C]   ratio = 1.17x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.013   <-- ★★★ HP ★★★
       #2  z_68   Y' = +0.012
       #3  z_64   Y' = +0.010
       #4  z_33   Y' = +0.010
       #5  z_6    Y' = -0.010

 66. '▁Hitch' [C]   ratio = 1.16x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.019   <-- ★★★ HP ★★★
       #2  z_44   Y' = +0.017
       #3  z_34   Y' = +0.016
       #4  z_66   Y' = -0.014
       #5  z_9    Y' = +0.014

 67. '▁Orlando' [C]   ratio = 1.16x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.025   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.021
       #3  z_67   Y' = +0.016
       #4  z_8    Y' = -0.015
       #5  z_34   Y' = +0.015

 68. '▁homo' [C]   ratio = 1.15x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.026   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.023
       #3  z_12   Y' = -0.020
       #4  z_13   Y' = -0.019
       #5  z_71   Y' = +0.018

 69. '▁Lego' [C]   ratio = 1.15x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.027   <-- ★★★ HP ★★★
       #2  z_26   Y' = +0.024
       #3  z_67   Y' = -0.014
       #4  z_61   Y' = -0.014
       #5  z_7    Y' = -0.011

 70. '▁Peter' [C]   ratio = 1.14x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.023   <-- ★★★ HP ★★★
       #2  z_42   Y' = +0.020
       #3  z_40   Y' = +0.018
       #4  z_1    Y' = +0.017
       #5  z_2    Y' = +0.014

 71. '▁Nancy' [C]   ratio = 1.13x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.020   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.018
       #3  z_8    Y' = +0.016
       #4  z_10   Y' = +0.013
       #5  z_13   Y' = +0.012

 72. '▁owls' [C]   ratio = 1.13x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.035   <-- ★★★ HP ★★★
       #2  z_64   Y' = +0.031
       #3  z_13   Y' = -0.022
       #4  z_46   Y' = +0.021
       #5  z_55   Y' = -0.020

 73. '▁phoenix' [C]   ratio = 1.11x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.022   <-- ★★★ HP ★★★
       #2  z_85   Y' = -0.019
       #3  z_53   Y' = -0.017
       #4  z_89   Y' = +0.017
       #5  z_3    Y' = +0.016

 74. '▁potions' [C]   ratio = 1.10x   sparse Y[88] = -0.060  (in HP support)
       #1  z_88   Y' = -0.060   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.054
       #3  z_37   Y' = -0.023
       #4  z_42   Y' = -0.022
       #5  z_64   Y' = +0.016

 75. '▁Diana' [C]   ratio = 1.10x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.022   <-- ★★★ HP ★★★
       #2  z_21   Y' = -0.020
       #3  z_8    Y' = +0.013
       #4  z_34   Y' = +0.013
       #5  z_14   Y' = +0.013

 76. '▁Bloomsbury' [C]   ratio = 1.08x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.037   <-- ★★★ HP ★★★
       #2  z_68   Y' = +0.034
       #3  z_58   Y' = +0.028
       #4  z_43   Y' = +0.026
       #5  z_84   Y' = +0.019

 77. '▁dragons' [C]   ratio = 1.08x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.035   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.033
       #3  z_65   Y' = +0.031
       #4  z_98   Y' = +0.027
       #5  z_47   Y' = -0.016

 78. '▁Hor' [C]   ratio = 1.07x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.024   <-- ★★★ HP ★★★
       #2  z_83   Y' = -0.022
       #3  z_1    Y' = +0.017
       #4  z_51   Y' = +0.016
       #5  z_25   Y' = +0.016

 79. '▁wand' [C]   ratio = 1.06x   sparse Y[88] = -0.068  (in HP support)
       #1  z_88   Y' = -0.068   <-- ★★★ HP ★★★
       #2  z_46   Y' = +0.064
       #3  z_14   Y' = +0.014
       #4  z_3    Y' = -0.014
       #5  z_98   Y' = -0.014

 80. '▁hands' [C]   ratio = 1.06x   sparse Y[88] = -0.000  (not in HP support)
       #1  z_88   Y' = -0.025   <-- ★★★ HP ★★★
       #2  z_60   Y' = -0.023
       #3  z_32   Y' = +0.021
       #4  z_66   Y' = -0.019
       #5  z_59   Y' = -0.019


In [38]:
# ---- How orthogonal is each HP direction to the span of the other Z columns? ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    Z64 = Z.double()
    k = Z64.shape[1]


    def angle_to_span(f: int, exclude=()) -> dict:
        """Angle between z_f and span{z_i : i != f, i not in exclude}."""
        others = [i for i in range(k) if i != f and i not in exclude]
        z = Z64[:, f]
        coef = torch.linalg.lstsq(Z64[:, others], z.unsqueeze(1)).solution.squeeze(1)
        proj = Z64[:, others] @ coef
        resid = z - proj
        sin = (resid.norm() / z.norm()).item()                  # 1 = orthogonal, 0 = inside the span
        cos_single = F.cosine_similarity(Z64[:, others], z.unsqueeze(1), dim=0)
        best = int(cos_single.abs().argmax())
        return {
            "feature": f,
            "angle_deg": math.degrees(math.asin(min(sin, 1.0))),
            "resid/||z||": sin,
            "proj/||z||": (proj.norm() / z.norm()).item(),
            "max |cos| to one z_i": cos_single.abs().max().item(),
            "closest z_i": others[best],
            "top-3 lstsq coef (i: c)": ", ".join(
                f"{others[i]}: {coef[i]:+.2f}" for i in torch.argsort(coef.abs(), descending=True)[:3].tolist()
            ),
        }


    print(f"d = {Z64.shape[0]}, k = {k}  ->  span of the other {k - 1} columns is a {k - 1}-dim subspace of R^{Z64.shape[0]}")
    print("For reference, a random direction would sit at about "
          f"{math.degrees(math.acos(math.sqrt((k - 1) / Z64.shape[0]))):.1f}° from a random {k - 1}-dim subspace\n")

    hp_rows = [angle_to_span(f) for f in HP_FEATS]
    if len(HP_FEATS) > 1:  # also measure against non-HP directions only
        hp_rows += [{**angle_to_span(f, exclude=HP_FEATS), "feature": f"{f} (vs non-HP only)"} for f in HP_FEATS]
    display(pd.DataFrame(hp_rows).set_index("feature"))

    # Baseline: same measurement for every feature, to see whether HP is unusual
    all_angles = pd.Series({f: angle_to_span(f)["angle_deg"] for f in range(k)}).sort_values()
    print("\nangle to span of the others, all features:")
    print(all_angles.describe().round(2).to_string())
    for f in HP_FEATS:
        pct = (all_angles < all_angles[f]).mean()
        print(f"HP feature {f}: {all_angles[f]:.2f}°  ->  more orthogonal than {pct:.0%} of features "
              f"(rank {all_angles.index.get_loc(f) + 1}/{k}, ascending)")

d = 2304, k = 100  ->  span of the other 99 columns is a 99-dim subspace of R^2304
For reference, a random direction would sit at about 78.0° from a random 99-dim subspace

,angle_deg,resid/||z||,proj/||z||,max |cos| to one z_i,closest z_i,top-3 lstsq coef (i: c)
feature,,,,,,
88,62.913534,0.89032,0.455335,0.31576,46,"46: -0.25, 30: -0.16, 75: +0.11"

angle to span of the others, all features:
count    100.00
mean      60.85
std       12.09
min       18.65
25%       55.97
50%       62.16
75%       69.19
max       77.62
HP feature 88: 62.91°  ->  more orthogonal than 53% of features (rank 54/100, ascending)

In [39]:
# ---- The 5 directions closest to the HP direction: angle + Gemini description ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    HP = HP_FEATS[0]
    N_NEIGHBORS = 5
    N_TOKENS_SHOW = 15

    z_hp = Z[:, HP]
    cos_all = F.cosine_similarity(Z, z_hp.unsqueeze(1), dim=0)        # (k,)
    cos_all[HP] = 0.0
    neighbors = torch.argsort(cos_all.abs(), descending=True)[:N_NEIGHBORS].tolist()


    def describe(f: int) -> str:
        if f not in descriptions:  # only tau-passing features were described in Step 3.2
            descriptions[f] = get_description(client, judge_input(Y, f, feat_tokens.loc[f, "activating_tokens"]), sys_prompt=DESC_SYS)
            save_judge()
        return descriptions[f]


    def top_tokens(f: int) -> str:
        mags = Y[f].abs()
        top = torch.argsort(mags, descending=True)[:N_TOKENS_SHOW]
        top = top[mags[top] > 0].tolist()
        toks = tokenizer.convert_ids_to_tokens([vstar_ids[j] for j in top])
        return ", ".join(f"{t!r}[{LABEL_TAG[codes[j]]}]" for t, j in zip(toks, top))


    print(f"=== HP feature {HP} ===\n  Gemini : {describe(HP)}\n  tokens : {top_tokens(HP)}\n")

    rows = []
    for r, f in enumerate(neighbors, 1):
        c = cos_all[f].item()
        angle = math.degrees(math.acos(min(abs(c), 1.0)))   # angle between the lines, 0°..90°
        shared = int(((Y[HP] != 0) & (Y[f] != 0)).sum())
        rows.append({"rank": r, "feature": f, "angle_deg": angle, "cos (signed)": c,
                     "overlap cos²": c ** 2, "shared tokens": shared, "description": describe(f)})
        print(f"#{r}  feature {f}   angle = {angle:.1f}°   cos = {c:+.3f}   (cos² = {c ** 2:.0%} of z_{HP} along it)   "
              f"shared support tokens = {shared}")
        print(f"  Gemini : {describe(f)}")
        print(f"  tokens : {top_tokens(f)}\n")

=== HP feature 88 ===
  Gemini : The feature represents proper nouns and key terms specifically associated with the Harry Potter universe.
  tokens : 'ffindor'[C], 'therin'[C], 'umbledore'[C], '▁Dumbledore'[C], '▁Hogwarts'[C], '▁Weasley'[C], '▁Malfoy'[C], '2'[B], '▁Potter'[C], 'Hermione'[C], '4'[B], '▁Rowling'[C], '▁Voldemort'[C], '▁Hermione'[C], '3'[B]

#1  feature 46   angle = 71.6°   cos = -0.316   (cos² = 10% of z_88 along it)   shared support tokens = 18
  Gemini : This feature vector activates strongly in contexts involving magic, wizards, and witchcraft.
  tokens : '▁magic'[C], 'magic'[C], 'Magic'[C], '▁Magic'[B], '▁magical'[C], 'magical'[C], '▁Magical'[C], '▁wizard'[C], '▁wizards'[C], '▁witchcraft'[C], '▁Wizard'[C], 'wizard'[C], '▁Wizards'[C], '▁witch'[C], '▁witches'[C]

#2  feature 30   angle = 82.4°   cos = -0.132   (cos² = 2% of z_88 along it)   shared support tokens = 10
  Gemini : This vector represents the concept of formal education, encompassing students, teachers, and numerical digits.
  tokens : '▁school'[B], '5'[B], '2'[B], '3'[B], '4'[B], 'school'[C], '8'[B], '1'[B], '6'[B], '9'[B], '7'[B], '▁School'[B], '▁schools'[B], '0'[B], '▁students'[N]

#3  feature 68   angle = 85.7°   cos = -0.075   (cos² = 1% of z_88 along it)   shared support tokens = 0
  Gemini : This feature vector represents the concept of literature, books, and the act of reading.
  tokens : '▁book'[B], 'book'[C], '▁Book'[B], '▁books'[C], '▁Books'[C], '▁bookstores'[C], '▁novels'[C], '▁ebooks'[C], '▁textbook'[C], '▁novel'[B], '▁read'[C], '▁Novel'[C], '▁reading'[B], '▁chapter'[C], '▁reads'[C]

#4  feature 39   angle = 86.4°   cos = +0.064   (cos² = 0% of z_88 along it)   shared support tokens = 10
  Gemini : This vector represents the set of single-digit Arabic numerals.
  tokens : '5'[B], '3'[B], '6'[B], '4'[B], '7'[B], '8'[B], '2'[B], '9'[B], '1'[B], '0'[B]

#5  feature 16   angle = 86.6°   cos = +0.059   (cos² = 0% of z_88 along it)   shared support tokens = 10
  Gemini : This vector activates for communication verbs and numeric digits often used to attribute statements and data.
  tokens : '▁said'[B], '▁stated'[C], '3'[B], '5'[B], '▁reported'[C], '4'[B], '2'[B], '6'[B], '1'[B], '8'[B], '▁claimed'[C], '7'[B], '9'[B], '▁noted'[B], '▁reportedly'[C]

In [40]:
# ---- The 5 directions most orthogonal to the HP direction ----
if not F_C:
    print("F_C is empty: nothing to analyse in this cell.")
else:
    N_ORTHO = 5

    others = torch.tensor([f for f in range(Z.shape[1]) if f != HP])
    most_ortho = others[torch.argsort(cos_all[others].abs())[:N_ORTHO]].tolist()

    rows = []
    for r, f in enumerate(most_ortho, 1):
        c = cos_all[f].item()
        angle = math.degrees(math.acos(min(abs(c), 1.0)))
        shared = int(((Y[HP] != 0) & (Y[f] != 0)).sum())
        rows.append({"rank": r, "feature": f, "angle_deg": angle, "cos (signed)": c,
                     "shared tokens": shared, "description": describe(f)})
        print(f"#{r}  feature {f}   angle = {angle:.2f}°   cos = {c:+.4f}   shared support tokens = {shared}")
        print(f"  Gemini : {describe(f)}")
        print(f"  tokens : {top_tokens(f)}\n")

    display(pd.DataFrame(rows).set_index("rank"))

#1  feature 36   angle = 89.91°   cos = +0.0016   shared support tokens = 10
  Gemini : This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities.
  tokens : '▁open'[C], 'open'[C], '▁Open'[N], '▁opened'[B], '▁opening'[B], '▁closed'[C], '3'[B], '6'[B], '4'[B], '5'[B], '1'[B], '2'[B], '8'[B], '7'[B], '9'[B]

#2  feature 84   angle = 89.85°   cos = +0.0026   shared support tokens = 0
  Gemini : This feature vector represents temporal concepts related to units of time, duration, and chronological periods.
  tokens : '▁time'[B], 'Time'[C], 'time'[N], '▁times'[N], '▁Times'[C], '▁day'[C], '▁days'[C], '▁Day'[C], '▁Days'[C], '▁hours'[B], '▁night'[C], '▁moment'[C], '▁date'[B], '▁Night'[C], 'tim'[N]

#3  feature 67   angle = 89.85°   cos = -0.0027   shared support tokens = 0
  Gemini : This feature represents the concept of awards, honors, and recognition for achievements.
  tokens : '▁award'[B], '▁Award'[B], '▁awards'[C], '▁Awards'[C], '▁awarded'[N], '▁Prizes'[C], '▁winner'[N], '▁medal'[N], '▁grant'[N], '▁nominated'[C], '▁confer'[C], '▁nominations'[N], '▁recognition'[C], '▁praise'[C], '▁praised'[C]

#4  feature 6   angle = 89.82°   cos = +0.0031   shared support tokens = 0
  Gemini : This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement.
  tokens : '▁mainly'[C], '▁primarily'[B], '▁generally'[B], '▁largely'[B], '▁usually'[N], '▁often'[C], '▁predominantly'[C], '▁essentially'[C], 'larg'[C], '▁invariably'[C], '▁ostensibly'[C], '▁originally'[C], '▁frequently'[C], '▁commonly'[C], '▁initially'[C]

#5  feature 35   angle = 89.82°   cos = +0.0031   shared support tokens = 10
  Gemini : This vector activates on feminine third-person singular pronouns and demonstrative determiners used in reference to people.
  tokens : '▁these'[B], '▁she'[B], '▁this'[B], '▁her'[B], 'her'[C], 'These'[B], 'She'[B], '▁herself'[C], 'Her'[N], '3'[B], '5'[B], '4'[B], '▁She'[N], '8'[B], '6'[B]

,feature,angle_deg,cos (signed),shared tokens,description
rank,,,,,
1,36,89.908906,0.001590,10,"This vector represents the concept of opening, closing, and numerical digits, indicating states of access and quantities."
2,84,89.852838,0.002568,0,"This feature vector represents temporal concepts related to units of time, duration, and chronological periods."
3,67,89.845722,-0.002693,0,"This feature represents the concept of awards, honors, and recognition for achievements."
4,6,89.824656,0.003060,0,"This vector represents adverbs of frequency, generality, and qualification that modify the extent or typicality of an action or statement."
5,35,89.821689,0.003112,10,This vector activates on feminine third-person singular pronouns and demonstrative determiners used in reference to people.

---
### 3.2.w Original vs transformed: matched-feature overlap

Do the two fits find the same token groups? Each feature is compared through its **support**, the tokens it uses:
$S^0_i = \{t : Y^0_{i,t}\neq 0\}$ (original fit) and $S_j = \{t : Y_{j,t}\neq 0\}$ (transformed fit).

- Both fits use the same method (`CFG`), so both have $K$ nonzeros in total; with `fixed` every row has exactly
  $\lceil s|V^*|\rceil$, otherwise the widths differ per feature and between the fits. Jaccard handles unequal sizes.
- $J_{ij} = |S^0_i\cap S_j| \,/\, |S^0_i\cup S_j|$ for all $k\times k$ pairs. Feature indices are arbitrary in each fit, so
  features are paired by the one-to-one matching with the largest total Jaccard (Hungarian algorithm,
  `scipy.optimize.linear_sum_assignment`). `best Jaccard` is the best partner without the one-to-one constraint.
- Directions: a transformed feature lives in X-space. `T.unmap` ($\tilde{\mathbf z}\,S_\eta^{-\gamma/2}W^{-1}$) maps it to the raw space,
  where it is compared with $\mathbf z^0_i$ by $|\cos|$ (the sign of a feature is arbitrary).
- **`F_C0` here is the list of $\rho\ge\tau$ candidates of the original fit (3.2.e′), not a Gemini-judged selection** (no Gemini
  calls are made for the original fit). The column `orig in F_C0` therefore means "original feature passes $\rho\ge\tau$".

In [41]:
from scipy.optimize import linear_sum_assignment

S0 = (Y0 != 0).numpy()                    # (k, |V*|) supports, original fit
S1 = (Y != 0).numpy()                     # (k, |V*|) supports, transformed fit
print(f"|S0_i| (original widths): min={S0.sum(1).min()} median={int(np.median(S0.sum(1)))} max={S0.sum(1).max()}   "
      f"|S_j| (transformed widths): min={S1.sum(1).min()} median={int(np.median(S1.sum(1)))} max={S1.sum(1).max()}")

inter = S0.astype(np.int64) @ S1.T.astype(np.int64)            # (k, k): |S0_i ∩ S_j|
union = S0.sum(1)[:, None] + S1.sum(1)[None, :] - inter
J = inter / np.maximum(union, 1)

rows0, cols1 = linear_sum_assignment(-J)                       # maximize total Jaccard
match0 = dict(zip(rows0.tolist(), cols1.tolist()))             # original i -> transformed j
match1 = {j: i for i, j in match0.items()}                     # transformed j -> original i

Z_back = T.unmap(Z.T).T.float()                                # (d, k): transformed features in the raw space
cos_map = F.cosine_similarity(Z0[:, rows0], Z_back[:, cols1], dim=0).abs().numpy()

match_df = pd.DataFrame({
    "orig feature": rows0,
    "transformed feature": cols1,
    "|S0|": S0.sum(1)[rows0],
    "|S|": S1.sum(1)[cols1],
    "|S0∩S|": inter[rows0, cols1],
    "Jaccard": J[rows0, cols1],
    "best Jaccard": J.max(1)[rows0],
    "best partner": J.argmax(1)[rows0],
    "|cos(z0, unmap(z~))|": cos_map,
    "orig in F_C0": [i in F_C0 for i in rows0.tolist()],    # F_C0 = rho >= tau candidates of the original fit (no judge)
    "transformed in F_C": [j in F_C for j in cols1.tolist()],
}).sort_values("Jaccard", ascending=False, ignore_index=True)

mj = match_df["Jaccard"]
print("matched Jaccard quantiles: " + "  ".join(f"q{int(q * 100)}={mj.quantile(q):.3f}" for q in (0, .1, .25, .5, .75, .9, 1)))
print(f"pairs with Jaccard >= 0.5: {(mj >= 0.5).sum()} / {RANK}   >= 0.8: {(mj >= 0.8).sum()} / {RANK}   "
      f"matched partner = best partner: {(match_df['transformed feature'] == match_df['best partner']).sum()} / {RANK}")
print(f"|cos| of mapped directions: median={match_df['|cos(z0, unmap(z~))|'].median():.3f}   "
      f"Spearman vs Jaccard = {match_df['Jaccard'].corr(match_df['|cos(z0, unmap(z~))|'], method='spearman'):.3f}")
print("\nhistogram of matched Jaccard:")
print(pd.cut(mj, bins=np.linspace(0, 1, 11), include_lowest=True).value_counts().sort_index().to_string())
with pd.option_context("display.max_rows", None):
    display(match_df)

|S0_i| (original widths): min=11 median=36 max=178   |S_j| (transformed widths): min=10 median=37 max=187
matched Jaccard quantiles: q0=0.000  q10=0.000  q25=0.026  q50=0.382  q75=0.574  q90=0.706  q100=0.927
pairs with Jaccard >= 0.5: 34 / 100   >= 0.8: 6 / 100   matched partner = best partner: 64 / 100
|cos| of mapped directions: median=0.556   Spearman vs Jaccard = 0.709

histogram of matched Jaccard:
Jaccard
(-0.001, 0.1]    39
(0.1, 0.2]        1
(0.2, 0.3]        5
(0.3, 0.4]        8
(0.4, 0.5]       14
(0.5, 0.6]       13
(0.6, 0.7]        8
(0.7, 0.8]        6
(0.8, 0.9]        4
(0.9, 1.0]        2

,orig feature,transformed feature,|S0|,|S|,|S0∩S|,Jaccard,best Jaccard,best partner,"|cos(z0, unmap(z~))|",orig in F_C0,transformed in F_C
0,67,86,104,108,102,0.927273,0.927273,86,0.596439,True,False
1,95,39,11,10,10,0.909091,0.909091,39,0.242379,False,False
2,20,14,41,45,39,0.829787,0.829787,14,0.900218,True,False
3,9,49,116,118,106,0.828125,0.828125,49,0.593673,True,False
4,18,43,29,31,27,0.818182,0.818182,43,0.797459,True,False
5,28,28,24,25,22,0.814815,0.814815,28,0.811454,True,False
6,42,42,24,29,23,0.766667,0.766667,42,0.776717,False,False
7,23,9,120,139,110,0.738255,0.738255,9,0.654269,True,False
8,83,57,13,18,13,0.722222,0.722222,57,0.838832,False,False
9,24,83,45,34,33,0.717391,0.717391,83,0.700241,True,False
10,19,30,48,56,43,0.704918,0.704918,30,0.710469,False,False
11,3,3,37,38,31,0.704545,0.704545,3,0.814245,True,False
12,70,82,29,35,26,0.684211,0.684211,82,0.929958,False,False
13,47,48,113,100,85,0.664062,0.664062,48,0.690632,False,False
14,90,75,52,66,47,0.661972,0.661972,75,0.611285,False,False
15,64,91,82,94,70,0.660377,0.660377,91,0.845291,False,False
16,73,68,27,39,26,0.650000,0.650000,68,0.837873,True,False
17,6,6,81,83,63,0.623762,0.623762,6,0.591250,True,False
18,88,37,25,22,18,0.620690,0.620690,37,0.853771,True,False
19,22,46,32,47,30,0.612245,0.612245,46,0.772081,True,False
20,71,71,15,17,12,0.600000,0.600000,71,0.882325,True,False
21,92,24,23,36,22,0.594595,0.594595,24,0.823371,True,False
22,33,97,86,86,64,0.592593,0.592593,97,0.379155,True,False
23,62,98,81,98,66,0.584071,0.584071,98,0.690326,True,False
24,56,77,118,143,96,0.581818,0.581818,77,0.523747,False,False
25,5,84,30,25,20,0.571429,0.571429,84,0.567621,False,False
26,44,40,64,93,56,0.554455,0.554455,40,0.476542,False,False
27,93,93,54,39,33,0.550000,0.550000,93,0.913212,True,False
28,58,2,17,31,17,0.548387,0.548387,2,0.825867,True,False
29,80,87,37,43,28,0.538462,0.538462,87,0.840291,True,False
30,11,66,111,187,104,0.536082,0.536082,66,0.635406,True,False
31,51,34,21,35,19,0.513514,0.513514,34,0.730968,True,False
32,96,0,42,38,27,0.509434,0.509434,0,0.594892,False,False
33,8,95,16,11,9,0.500000,0.500000,95,0.562876,False,False
34,54,65,22,37,19,0.475000,0.475000,65,0.758168,True,False
35,21,19,11,17,9,0.473684,0.473684,19,0.831783,False,False
36,38,50,28,44,23,0.469388,0.469388,50,0.878445,True,False
37,99,63,19,41,19,0.463415,0.463415,63,0.832022,False,False
38,72,96,77,75,48,0.461538,0.461538,96,0.879755,False,False
39,27,59,144,135,88,0.460733,0.460733,59,0.387226,False,False
40,66,21,27,37,20,0.454545,0.454545,21,0.859368,False,False
41,55,55,57,52,34,0.453333,0.453333,55,0.734811,False,False
42,77,67,29,31,18,0.428571,0.428571,67,0.790063,False,False
43,25,60,87,132,65,0.422078,0.422078,60,0.592270,True,False
44,37,81,30,25,16,0.410256,0.410256,81,0.420689,False,False
45,35,36,12,19,9,0.409091,0.409091,36,0.870709,True,False
46,45,23,52,42,27,0.402985,0.402985,23,0.910362,False,False
47,39,79,28,35,18,0.400000,0.400000,79,0.834282,False,False
48,41,41,66,33,28,0.394366,0.394366,41,0.394771,False,False
49,84,25,45,34,22,0.385965,0.385965,25,0.511054,True,False
50,49,33,178,124,83,0.378995,0.378995,33,0.828758,False,False
51,98,10,32,58,24,0.363636,0.363636,10,0.668616,True,False
52,75,1,52,75,32,0.336842,0.336842,1,0.947290,False,False
53,2,92,21,27,12,0.333333,0.333333,92,0.835521,False,False
54,87,88,53,61,27,0.310345,0.310345,88,0.718488,True,True
55,85,52,25,32,13,0.295455,0.295455,52,0.582512,True,False
56,89,26,28,63,19,0.263889,0.263889,26,0.380483,False,False
57,7,62,14,16,6,0.250000,0.250000,62,0.820640,False,False
58,59,7,14,53,13,0.240741,0.240741,7,0.642189,True,False
59,52,53,33,68,19,0.231707,0.411765,26,0.290190,True,False
60,12,16,49,86,21,0.184211,0.184211,16,0.303106,True,False
61,36,8,28,28,5,0.098039,0.146341,36,0.127051,True,False
62,50,94,49,26,6,0.086957,0.160256,60,0.082853,False,False
63,57,32,17,22,3,0.083333,0.083333,32,0.037443,False,False
64,91,99,30,39,5,0.078125,0.116279,75,0.077111,True,False
65,15,17,95,44,9,0.069231,0.069231,17,0.160872,False,False
66,30,47,35,27,3,0.050847,0.050847,47,0.017459,False,False
67,13,51,61,43,5,0.050505,0.209150,33,0.245181,False,False
68,78,18,32,53,4,0.049383,0.056000,48,0.231214,True,False
69,32,61,32,32,3,0.049180,0.058824,37,0.022633,False,False
70,81,11,50,34,3,0.037037,0.153226,40,0.271713,False,False
71,40,38,51,37,3,0.035294,0.055944,48,0.157407,False,False
72,97,13,26,33,2,0.035088,0.044304,9,0.056347,False,False
73,0,76,36,23,2,0.035088,0.035088,76,0.094232,False,False
74,46,29,29,50,2,0.025974,0.095238,60,0.057428,False,False
75,82,44,55,24,2,0.025974,0.037383,30,0.116162,False,False
76,16,90,17,31,1,0.021277,0.022727,49,0.047141,True,False
77,68,72,92,28,2,0.016949,0.037313,46,0.548333,False,False
78,79,20,41,20,1,0.016667,0.195402,26,0.089989,False,False
79,14,45,30,42,1,0.014085,0.026549,97,0.499307,True,False
80,60,12,40,47,1,0.011628,0.075758,67,0.113790,False,False
81,31,5,48,42,1,0.011236,0.044444,66,0.111899,False,False
82,29,85,89,27,1,0.008696,0.108333,50,0.210428,False,False
83,17,56,95,28,1,0.008197,0.009524,95,0.093059,False,False
84,10,69,90,46,1,0.007407,0.035461,30,0.205033,False,False
85,26,31,127,22,1,0.006757,0.154286,1,0.092033,False,False
86,4,80,25,41,0,0.000000,0.035088,40,0.069787,False,False
87,65,15,37,44,0,0.000000,0.004484,66,0.414655,False,False
88,94,70,34,41,0,0.000000,0.140351,67,0.229541,False,False
89,69,22,11,18,0,0.000000,0.051471,60,0.034115,False,False
90,74,89,24,31,0,0.000000,0.347826,0,0.125041,False,False
91,43,58,79,20,0,0.000000,0.021898,88,0.037137,False,False
92,86,54,60,51,0,0.000000,0.035714,47,0.226490,False,False
93,53,73,12,33,0,0.000000,0.021739,34,0.080355,False,False
94,1,74,16,43,0,0.000000,0.041667,83,0.098173,False,False
95,61,27,61,43,0,0.000000,0.016667,88,0.235459,False,False
96,34,78,20,29,0,0.000000,0.053571,98,0.087584,False,False
97,48,4,74,27,0,0.000000,0.050314,40,0.354592,False,False
98,76,64,37,35,0,0.000000,0.017241,32,0.491931,False,False
99,63,35,14,25,0,0.000000,0.016667,86,0.073291,False,False

#### Concept features in both fits

For each transformed concept feature $f\in F_C$ and each original $\rho\ge\tau$ candidate $f_0\in F_{C0}$ (no judge on the original fit, see 3.2.e′): its matched partner in
the other fit, their Jaccard, and whether the partner is itself a concept feature of its own fit. The token table splits
the union of the two supports into *both* / *only original* / *only transformed*, with labels (C / N / B) and the signed
$Y^0$ and $Y$ values, sorted by the larger magnitude within each group.

In [42]:
def pair_table(i: int, j: int) -> pd.DataFrame:
    """Union of S0_i and S_j: membership, label, Y0[i, t], Y[j, t]; grouped, then sorted by magnitude."""
    cols = np.where(S0[i] | S1[j])[0]
    where = np.where(S0[i, cols] & S1[j, cols], "both", np.where(S0[i, cols], "only original", "only transformed"))
    df = pd.DataFrame({
        "token": tokenizer.convert_ids_to_tokens([vstar_ids[t] for t in cols]),
        "label": [LABEL_TAG[codes[t]] for t in cols],
        "in": where,
        f"Y0[{i}]": Y0[i, cols].numpy(),
        f"Y[{j}]": Y[j, cols].numpy(),
    })
    group = df["in"].map({"both": 0, "only original": 1, "only transformed": 2})
    mag = np.maximum(df[f"Y0[{i}]"].abs(), df[f"Y[{j}]"].abs())
    return df.assign(_g=group, _m=mag).sort_values(["_g", "_m"], ascending=[True, False]) \
             .drop(columns=["_g", "_m"]).reset_index(drop=True)


pairs = {}
for f in F_C:
    i = match1[f]
    pairs.setdefault((i, f), []).append(
        f"transformed concept feature {f}: matched original feature {i} is {'IN' if i in F_C0 else 'NOT in'} F_C0 "
        f"(best-Jaccard original partner: {int(J[:, f].argmax())}, J={J[:, f].max():.3f})")
for f0 in F_C0:
    j = match0[f0]
    pairs.setdefault((f0, j), []).append(
        f"original rho-candidate {f0}: matched transformed feature {j} is {'IN' if j in F_C else 'NOT in'} F_C "
        f"(best-Jaccard transformed partner: {int(J[f0].argmax())}, J={J[f0].max():.3f})")

print(f"F_C (transformed, judged) = {F_C}   F_C0 (original, rho >= tau candidates, not judged) = {F_C0}   "
      f"matching maps F_C0 onto F_C exactly: {sorted(match0[f0] for f0 in F_C0) == F_C}\n")
if not pairs:
    print("F_C and F_C0 are both empty: nothing to compare.")

for (i, j), notes in sorted(pairs.items()):
    tab = pair_table(i, j)
    n_in = tab["in"].value_counts()
    cos_ij = F.cosine_similarity(Z0[:, i], Z_back[:, j], dim=0).abs().item()
    print(f"{'=' * 100}\n=== original {i} <-> transformed {j}   Jaccard = {J[i, j]:.3f}   "
          f"|cos(z0, unmap(z~))| = {cos_ij:.3f}\n{'=' * 100}")
    for note in notes:
        print("  " + note)
    print(f"  both: {n_in.get('both', 0)}   only original: {n_in.get('only original', 0)}   "
          f"only transformed: {n_in.get('only transformed', 0)}")
    display(pd.crosstab(tab["in"], tab["label"]))
    with pd.option_context("display.max_rows", None):
        display(tab)

F_C (transformed, judged) = [88]   F_C0 (original, rho >= tau candidates, not judged) = [3, 6, 9, 11, 12, 14, 16, 18, 20, 22, 23, 24, 25, 28, 33, 35, 36, 38, 51, 52, 54, 58, 59, 62, 67, 71, 73, 78, 80, 84, 85, 87, 88, 91, 92, 93, 98]   matching maps F_C0 onto F_C exactly: False

====================================================================================================
=== original 3 <-> transformed 3   Jaccard = 0.705   |cos(z0, unmap(z~))| = 0.814
====================================================================================================
  original rho-candidate 3: matched transformed feature 3 is NOT in F_C (best-Jaccard transformed partner: 3, J=0.705)
  both: 31   only original: 6   only transformed: 7

label             B   C  N
in
both              3  20  8
only original     0   2  4
only transformed  1   4  2

             token label                in     Y0[3]      Y[3]
0            ▁find     C              both -0.213919 -0.397290
1         ▁finding     C              both -0.236653 -0.381204
2            ▁Find     C              both -0.202146 -0.358675
3     ▁discovering     C              both -0.350393 -0.277062
4       ▁Discovery     N              both -0.328779 -0.188175
5     ▁discoveries     N              both -0.325900 -0.219370
6        Discovery     C              both -0.324601 -0.191064
7       ▁discovers     C              both -0.318477 -0.262864
8           ▁found     B              both -0.178569 -0.314812
9         ▁uncover     C              both -0.194403 -0.138150
10    ▁exploration     C              both -0.158667 -0.066706
11          ▁learn     C              both -0.123754 -0.156361
12         ▁learns     C              both -0.138115 -0.155338
13         ▁search     C              both -0.141897 -0.120282
14        ▁explore     N              both -0.137982 -0.080142
15       ▁searched     C              both -0.116450 -0.088865
16  ▁investigation     N              both -0.116106 -0.048691
17      ▁encounter     C              both -0.096494 -0.109727
18            ▁see     B              both -0.052964 -0.104973
19         ▁reveal     C              both -0.104877 -0.061730
20       ▁revealed     C              both -0.103345 -0.054299
21    ▁identifying     N              both -0.097528 -0.064168
22     ▁encounters     C              both -0.090589 -0.094974
23           ▁sees     C              both -0.055587 -0.093380
24         ▁seeing     C              both -0.063168 -0.092113
25           ▁hunt     N              both -0.084585 -0.054276
26     ▁identified     N              both -0.082536 -0.051208
27       ▁research     B              both -0.078941 -0.052245
28       ▁realized     N              both -0.077886 -0.045624
29        ▁seeking     C              both -0.063875 -0.053235
30         ▁notice     C              both -0.062701 -0.044247
31    ▁observation     N     only original -0.076619 -0.000000
32      ▁observing     C     only original -0.067565 -0.000000
33         covered     N     only original -0.065794 -0.000000
34          ▁quest     C     only original -0.065192 -0.000000
35    ▁examination     N     only original -0.056934 -0.000000
36       ▁studying     N     only original -0.053938 -0.000000
37         ▁figure     N  only transformed -0.000000 -0.071473
38           ▁know     C  only transformed -0.000000 -0.067214
39           ▁knew     C  only transformed -0.000000 -0.064950
40     ▁understand     C  only transformed -0.000000 -0.058700
41           ▁seen     C  only transformed -0.000000 -0.052594
42      ▁knowledge     N  only transformed -0.000000 -0.049395
43     ▁experience     B  only transformed -0.000000 -0.045721

====================================================================================================
=== original 6 <-> transformed 6   Jaccard = 0.624   |cos(z0, unmap(z~))| = 0.591
====================================================================================================
  original rho-candidate 6: matched transformed feature 6 is NOT in F_C (best-Jaccard transformed partner: 6, J=0.624)
  both: 63   only original: 18   only transformed: 20

label              B   C   N
in
both               9  39  15
only original      1  11   6
only transformed  13   4   3

                token label                in     Y0[6]      Y[6]
0             ▁mainly     C              both  0.173781  0.240763
1          ▁primarily     B              both  0.195343  0.236589
2          ▁generally     B              both  0.193468  0.235932
3            ▁largely     B              both  0.197650  0.235754
4            ▁usually     N              both  0.150946  0.232801
5              ▁often     C              both  0.126826  0.211613
6      ▁predominantly     C              both  0.179491  0.201756
7        ▁essentially     C              both  0.174427  0.198345
8                larg     C              both  0.136102  0.179223
9            ▁broadly     N              both  0.160626  0.107460
10        ▁ostensibly     C              both  0.153978  0.144204
11      ▁specifically     C              both  0.148214  0.126486
12        ▁invariably     C              both  0.133319  0.145406
13        ▁originally     C              both  0.134745  0.142650
14        ▁frequently     C              both  0.129241  0.140644
15          ▁commonly     C              both  0.127491  0.140136
16         ▁initially     C              both  0.138332  0.136523
17          ▁actually     C              both  0.106977  0.135568
18     ▁substantially     C              both  0.133535  0.079248
19      ▁particularly     C              both  0.129783  0.130791
20         ▁allegedly     B              both  0.129800  0.119919
21        ▁reportedly     C              both  0.126895  0.111086
22           ▁roughly     C              both  0.124850  0.098735
23          ▁strictly     C              both  0.124555  0.092472
24            ▁widely     N              both  0.120017  0.095049
25           ▁loosely     N              both  0.118529  0.055329
26      ▁collectively     C              both  0.115986  0.065949
27      ▁historically     N              both  0.114668  0.074880
28        ▁reasonably     C              both  0.113373  0.069209
29            ▁likely     C              both  0.077440  0.113161
30         ▁otherwise     C              both  0.113050  0.111597
31        ▁eventually     C              both  0.100600  0.111859
32        ▁completely     C              both  0.109683  0.070436
33          ▁somewhat     C              both  0.108977  0.100456
34            ▁rather     C              both  0.066155  0.107850
35            ▁fairly     C              both  0.106497  0.096225
36              ▁also     B              both  0.065656  0.106387
37            ▁almost     C              both  0.080249  0.106379
38            ▁simply     C              both  0.105858  0.101596
39      ▁continuously     C              both  0.105557  0.060624
40           ▁readily     N              both  0.104832  0.061634
41        ▁previously     N              both  0.103067  0.093463
42         ▁gradually     C              both  0.100921  0.071528
43           ▁rapidly     N              both  0.100651  0.046020
44            ▁merely     C              both  0.099679  0.097057
45            ▁really     C              both  0.078944  0.097798
46           ▁already     C              both  0.075781  0.096318
47          ▁possibly     C              both  0.093707  0.096001
48          ▁directly     N              both  0.094682  0.048733
49     ▁approximately     N              both  0.093948  0.068891
50          ▁formerly     N              both  0.092676  0.076982
51       ▁immediately     N              both  0.092146  0.054606
52        ▁Originally     N              both  0.092020  0.071469
53         ▁specially     N              both  0.091561  0.059563
54          ▁suddenly     C              both  0.091090  0.062013
55       ▁nonetheless     C              both  0.090038  0.055206
56        ▁altogether     N              both  0.089647  0.067253
57         ▁therefore     B              both  0.085160  0.058433
58              ▁thus     B              both  0.078906  0.069146
59            ▁highly     C              both  0.077020  0.053545
60         ▁purported     C              both  0.067624  0.074411
61             ▁still     B              both  0.053261  0.071233
62            ▁either     B              both  0.051549  0.062326
63        ▁rigorously     N     only original  0.110355  0.000000
64      ▁sufficiently     N     only original  0.105311  0.000000
65          ▁properly     N     only original  0.102857  0.000000
66       ▁unanimously     N     only original  0.097650  0.000000
67       ▁voluntarily     N     only original  0.087802  0.000000
68      ▁respectively     B     only original  0.085120  0.000000
69          istically     C     only original  0.082123  0.000000
70            ▁richly     C     only original  0.082076  0.000000
71           ▁bravely     N     only original  0.080417  0.000000
72            atively     C     only original  0.079135  0.000000
73         ▁ethically     C     only original  0.074005  0.000000
74   ▁internationally     C     only original  0.073797  0.000000
75            ▁poorly     C     only original  0.070370  0.000000
76              ently     C     only original  0.066356  0.000000
77          Similarly     C     only original  0.058726 -0.000000
78           ▁however     C     only original  0.058112  0.000000
79           ▁shortly     C     only original  0.054789  0.000000
80              ingly     C     only original  0.054738 -0.000000
81              ▁only     B  only transformed  0.000000  0.079337
82             ▁never     C  only transformed  0.000000  0.074700
83           ▁instead     B  only transformed  0.000000  0.072791
84           ▁overall     B  only transformed  0.000000  0.068862
85               ▁not     B  only transformed  0.000000  0.063990
86          ▁supposed     N  only transformed  0.000000  0.063396
87               ▁now     B  only transformed  0.000000  0.063079
88              ▁then     B  only transformed  0.000000  0.061883
89              ▁most     B  only transformed  0.000000  0.061852
90              ▁even     B  only transformed  0.000000  0.061793
91              ▁ever     B  only transformed  0.000000  0.061485
92              ▁once     N  only transformed  0.000000  0.058228
93              ▁much     C  only transformed  0.000000  0.056420
94           ▁typical     B  only transformed  0.000000  0.056105
95             Rather     C  only transformed  0.000000  0.055805
96           ▁general     C  only transformed  0.000000  0.050194
97        ▁particular     B  only transformed  0.000000  0.046932
98              ▁just     B  only transformed  0.000000  0.046926
99              ▁very     B  only transformed  0.000000  0.044476
100                 常     N  only transformed  0.000000  0.043611

====================================================================================================
=== original 9 <-> transformed 49   Jaccard = 0.828   |cos(z0, unmap(z~))| = 0.594
====================================================================================================
  original rho-candidate 9: matched transformed feature 49 is NOT in F_C (best-Jaccard transformed partner: 49, J=0.828)
  both: 106   only original: 10   only transformed: 12

label              B   C   N
in
both              14  64  28
only original      0   3   7
only transformed   3   6   3

             token label                in     Y0[9]     Y[49]
0        ▁speaking     C              both  0.113397  0.177090
1          ▁saying     C              both  0.123678  0.172310
2          ▁coming     C              both  0.101120  0.156958
3         ▁talking     C              both  0.117324  0.156022
4           ▁being     B              both  0.090382  0.154661
5         ▁showing     C              both  0.123344  0.147172
6          ▁taking     C              both  0.126936  0.142105
7         ▁stating     B              both  0.113652  0.137792
8          ▁having     N              both  0.102141  0.131910
9          ▁seeing     C              both  0.119968  0.130113
10         ▁making     C              both  0.129878  0.125095
11          ▁doing     B              both  0.119176  0.126199
12          ▁using     C              both  0.085708  0.126066
13         ▁giving     N              both  0.124121  0.112636
14        ▁dealing     C              both  0.120722  0.122375
15        ▁playing     B              both  0.112043  0.122053
16      ▁comparing     C              both  0.110585  0.121698
17   ▁representing     N              both  0.097842  0.119759
18      ▁providing     N              both  0.116649  0.104540
19       ▁creating     B              both  0.116226  0.096473
20        ▁holding     B              both  0.109490  0.116033
21      ▁attending     C              both  0.092056  0.115657
22     ▁addressing     C              both  0.114610  0.102089
23        ▁wearing     C              both  0.092908  0.114415
24        ▁seeking     C              both  0.113365  0.091738
25     ▁attempting     N              both  0.113225  0.081898
26       ▁starting     N              both  0.090224  0.112330
27     ▁committing     N              both  0.112222  0.057371
28         ▁noting     C              both  0.100885  0.111514
29     ▁portraying     C              both  0.111386  0.104227
30       ▁reaching     C              both  0.110510  0.110596
31        ▁placing     C              both  0.109625  0.093521
32          coming     C              both  0.068761  0.109343
33      ▁observing     C              both  0.108974  0.090737
34        ▁serving     B              both  0.100272  0.108858
35       ▁studying     N              both  0.107724  0.090042
36        ▁leaving     N              both  0.107444  0.102720
37       ▁covering     C              both  0.101070  0.107439
38        ▁finding     C              both  0.106895  0.104739
39     ▁announcing     N              both  0.106871  0.076969
40        ▁working     N              both  0.093739  0.106604
41      ▁receiving     N              both  0.106507  0.103925
42        ▁joining     N              both  0.105450  0.092555
43       ▁entering     C              both  0.104029  0.089712
44    ▁discovering     C              both  0.103780  0.084484
45     ▁indicating     N              both  0.097074  0.103572
46       ▁allowing     C              both  0.101209  0.102822
47        ▁arguing     C              both  0.102086  0.099781
48        ▁reading     B              both  0.094206  0.101840
49      ▁promoting     C              both  0.101426  0.076103
50      ▁replacing     N              both  0.100721  0.069470
51     ▁connecting     C              both  0.100205  0.083318
52        ▁quoting     C              both  0.100175  0.096385
53      ▁depicting     C              both  0.096778  0.100101
54        ▁writing     B              both  0.088792  0.099862
55         ▁buying     C              both  0.097861  0.095085
56         ▁moving     C              both  0.096541  0.082539
57        ▁marking     C              both  0.096313  0.066747
58         ▁acting     C              both  0.077507  0.094161
59      ▁reporting     C              both  0.092754  0.081574
60    ▁identifying     N              both  0.092605  0.067016
61      ▁targeting     C              both  0.090651  0.066673
62     ▁appointing     C              both  0.090243  0.059596
63        ▁viewing     B              both  0.090216  0.074441
64        ▁setting     C              both  0.089661  0.077197
65       ▁relating     N              both  0.068650  0.089562
66       ▁counting     C              both  0.088993  0.087083
67        ▁hosting     N              both  0.088891  0.066617
68       ▁invoking     C              both  0.087612  0.078310
69     ▁separating     C              both  0.086694  0.054372
70          ▁suing     C              both  0.085773  0.071633
71     ▁supporting     C              both  0.085604  0.076109
72        ▁jumping     N              both  0.085442  0.046856
73       ▁teaching     C              both  0.083411  0.085415
74        ▁leading     B              both  0.059761  0.085203
75        ▁selling     C              both  0.085160  0.076463
76        ▁driving     C              both  0.084863  0.078298
77       ▁building     N              both  0.084513  0.065966
78        ▁banning     C              both  0.084390  0.044957
79       ▁shooting     N              both  0.083408  0.072328
80         ▁urging     C              both  0.082894  0.069127
81        ▁drawing     C              both  0.080895  0.082844
82      ▁finishing     N              both  0.081661  0.048303
83      ▁recording     N              both  0.081114  0.060458
84         ▁hiding     C              both  0.080197  0.061141
85       ▁dreaming     C              both  0.080171  0.059448
86        ▁fearing     C              both  0.077791  0.072789
87      ▁attacking     C              both  0.077196  0.054359
88         ▁living     B              both  0.064421  0.076463
89       ▁printing     C              both  0.076428  0.058074
90        ▁judging     C              both  0.076413  0.067163
91        ▁filming     C              both  0.075141  0.057066
92     ▁purchasing     C              both  0.074916  0.065679
93        ▁killing     C              both  0.074610  0.056749
94       ▁pitching     N              both  0.074017  0.042840
95        ▁opening     B              both  0.073580  0.072638
96        ▁testing     N              both  0.073139  0.048693
97        ▁hanging     C              both  0.072600  0.063977
98        carrying     N              both  0.069552  0.045501
99      ▁beginning     B              both  0.059826  0.069356
100      Comparing     C              both  0.067716  0.063924
101    ▁publishing     C              both  0.067483  0.049289
102      ▁starring     N              both  0.059209  0.064914
103          going     C              both  0.058274  0.056565
104        writing     C              both  0.056393  0.054854
105    ▁succeeding     N              both  0.054185  0.048626
106      ▁settling     N     only original  0.092162  0.000000
107      ▁climbing     N     only original  0.073391  0.000000
108      ▁retiring     N     only original  0.072099  0.000000
109      ▁fielding     N     only original  0.071244  0.000000
110      ▁tracking     N     only original  0.070293  0.000000
111       ▁casting     C     only original  0.069250  0.000000
112     ▁expanding     N     only original  0.065461  0.000000
113     ▁splashing     C     only original  0.059889  0.000000
114    ▁motivating     C     only original  0.059284  0.000000
115     ▁competing     N     only original  0.059157  0.000000
116     ▁including     B  only transformed  0.000000  0.098102
117     ▁belonging     B  only transformed  0.000000  0.084545
118     ▁following     B  only transformed  0.000000  0.079663
119       ▁meaning     N  only transformed  0.000000  0.074086
120         ▁speak     C  only transformed  0.000000  0.069884
121      including     C  only transformed  0.000000  0.066576
122        ▁speaks     C  only transformed  0.000000  0.063245
123    ▁consisting     N  only transformed  0.000000  0.056340
124    ▁concerning     C  only transformed  0.000000  0.053850
125        ▁speech     C  only transformed  0.000000  0.051835
126     ▁resulting     N  only transformed  0.000000  0.044518
127       ▁lacking     C  only transformed  0.000000  0.044438

====================================================================================================
=== original 11 <-> transformed 66   Jaccard = 0.536   |cos(z0, unmap(z~))| = 0.635
====================================================================================================
  original rho-candidate 11: matched transformed feature 66 is NOT in F_C (best-Jaccard transformed partner: 66, J=0.536)
  both: 104   only original: 7   only transformed: 83

label              B   C   N
in
both              34  46  24
only original      0   4   3
only transformed  24  33  26

             token label                in    Y0[11]     Y[66]
0         ▁pattern     C              both -0.144447 -0.095755
1           ▁style     B              both -0.142321 -0.109186
2            ▁type     C              both -0.130007 -0.112181
3           ▁model     C              both -0.125467 -0.086376
4        ▁category     N              both -0.123846 -0.100145
5           ▁label     N              both -0.123701 -0.077209
6            ▁term     B              both -0.122935 -0.104880
7           ▁scale     B              both -0.121189 -0.077892
8           ▁range     C              both -0.121056 -0.097942
9            ▁site     C              both -0.083944 -0.119493
10           ▁form     B              both -0.118674 -0.100633
11        ▁process     B              both -0.118548 -0.109669
12           ▁name     B              both -0.112815 -0.117394
13           ▁line     B              both -0.116691 -0.113935
14       ▁question     N              both -0.099912 -0.116587
15         ▁figure     N              both -0.113104 -0.090358
16        ▁version     B              both -0.112515 -0.058936
17         ▁number     B              both -0.111055 -0.098919
18        ▁message     C              both -0.110722 -0.096522
19           ▁list     B              both -0.109818 -0.103713
20           ▁area     B              both -0.083651 -0.109512
21          ▁point     B              both -0.109384 -0.105762
22          ▁theme     C              both -0.108620 -0.084865
23         ▁series     B              both -0.107947 -0.094606
24         ▁system     N              both -0.107082 -0.079918
25        ▁section     C              both -0.102090 -0.106325
26          ▁issue     C              both -0.105442 -0.104318
27         ▁degree     C              both -0.104532 -0.075751
28          ▁route     B              both -0.103998 -0.095259
29           ▁tone     C              both -0.103480 -0.077610
30          ▁stage     C              both -0.103404 -0.080787
31          ▁group     B              both -0.101587 -0.103339
32         ▁period     N              both -0.102526 -0.074367
33       ▁position     N              both -0.102523 -0.088674
34      ▁statement     C              both -0.102473 -0.094074
35           ▁word     C              both -0.097132 -0.101873
36        ▁package     N              both -0.101239 -0.061566
37        ▁formula     C              both -0.099881 -0.066150
38         ▁source     N              both -0.099598 -0.066488
39          ▁trend     C              both -0.099206 -0.085905
40          ▁order     B              both -0.081658 -0.098758
41          ▁story     B              both -0.085640 -0.098718
42         ▁course     B              both -0.096304 -0.098199
43         ▁amount     C              both -0.097550 -0.082690
44           ▁idea     C              both -0.092756 -0.097494
45           ▁note     C              both -0.096165 -0.071980
46         ▁matter     C              both -0.096090 -0.086097
47          ▁class     B              both -0.092063 -0.094465
48        ▁variety     N              both -0.094391 -0.058947
49           ▁zone     N              both -0.094108 -0.073058
50          ▁value     C              both -0.093984 -0.083896
51        ▁subject     C              both -0.092965 -0.081152
52            ▁set     B              both -0.092586 -0.054577
53         ▁letter     C              both -0.092229 -0.084435
54         ▁record     B              both -0.091910 -0.065260
55           ▁role     B              both -0.091717 -0.083651
56          ▁title     B              both -0.091571 -0.089675
57          ▁piece     N              both -0.091417 -0.068724
58        ▁product     N              both -0.090478 -0.064678
59          ▁state     B              both -0.077099 -0.090436
60        ▁segment     B              both -0.090173 -0.079751
61          ▁sense     C              both -0.089242 -0.064204
62        ▁feature     B              both -0.088978 -0.068256
63        ▁picture     C              both -0.088677 -0.068853
64           ▁fact     C              both -0.088427 -0.087562
65        ▁purpose     C              both -0.088361 -0.076983
66        ▁element     C              both -0.088008 -0.068921
67           ▁view     C              both -0.087962 -0.065782
68         ▁circle     N              both -0.087615 -0.055333
69         ▁volume     C              both -0.087599 -0.069337
70         ▁manner     C              both -0.087472 -0.074308
71          ▁field     B              both -0.087120 -0.084538
72            ▁way     B              both -0.087104 -0.076107
73       ▁sentence     N              both -0.087055 -0.071014
74         ▁reason     C              both -0.087021 -0.066128
75          ▁brand     C              both -0.086936 -0.072877
76         ▁report     N              both -0.086784 -0.062707
77         ▁theory     C              both -0.086506 -0.070603
78        ▁article     B              both -0.079690 -0.086438
79         ▁design     B              both -0.085701 -0.062801
80         ▁domain     C              both -0.085091 -0.081775
81         ▁device     C              both -0.084755 -0.067008
82           style     C              both -0.084536 -0.052501
83        ▁project     N              both -0.084222 -0.081752
84          ▁genre     B              both -0.083997 -0.070441
85         ▁length     N              both -0.083938 -0.051804
86           ▁date     B              both -0.083433 -0.082106
87          ▁score     N              both -0.082782 -0.053444
88           ▁band     N              both -0.082388 -0.062112
89        ▁network     N              both -0.081548 -0.056050
90      ▁character     B              both -0.081213 -0.064084
91         ▁screen     C              both -0.081128 -0.063635
92         ▁status     C              both -0.080050 -0.067113
93      ▁principle     C              both -0.079994 -0.065749
94           ▁text     C              both -0.079833 -0.069981
95         ▁colour     C              both -0.078883 -0.054161
96         ▁option     N              both -0.077894 -0.072463
97        ▁account     C              both -0.074473 -0.077888
98         ▁signal     N              both -0.075963 -0.059939
99           ▁team     N              both -0.071153 -0.074049
100        ▁script     C              both -0.072193 -0.058419
101       ▁history     B              both -0.070464 -0.050062
102    ▁phenomenon     C              both -0.064515 -0.067857
103          ▁deal     C              both -0.066846 -0.054450
104           ▁mix     N     only original -0.087740 -0.000000
105       ▁setting     C     only original -0.073733 -0.000000
106         ▁blend     C     only original -0.072294 -0.000000
107          ▁base     N     only original -0.072157 -0.000000
108   ▁combination     N     only original -0.068589 -0.000000
109          scale     C     only original -0.067506 -0.000000
110        ▁change     C     only original -0.063482 -0.000000
111         ▁event     B  only transformed -0.000000 -0.094690
112         ▁place     B  only transformed -0.000000 -0.085029
113          ▁game     B  only transformed -0.000000 -0.084639
114       ▁station     B  only transformed -0.000000 -0.082063
115        ▁season     B  only transformed -0.000000 -0.078926
116       ▁website     C  only transformed -0.000000 -0.075726
117          ▁race     C  only transformed -0.000000 -0.073996
118       ▁service     N  only transformed -0.000000 -0.072890
119      ▁location     B  only transformed -0.000000 -0.071987
120         ▁house     C  only transformed -0.000000 -0.071876
121      ▁campaign     C  only transformed -0.000000 -0.071659
122          ▁body     C  only transformed -0.000000 -0.071132
123         ▁board     N  only transformed -0.000000 -0.068444
124        ▁moment     C  only transformed -0.000000 -0.067908
125          ▁book     B  only transformed -0.000000 -0.065958
126        ▁market     C  only transformed -0.000000 -0.065715
127         ▁voice     N  only transformed -0.000000 -0.065058
128       ▁company     N  only transformed -0.000000 -0.064604
129       ▁country     B  only transformed -0.000000 -0.062624
130          ▁plot     C  only transformed -0.000000 -0.062456
131        ▁family     B  only transformed -0.000000 -0.062172
132       ▁request     C  only transformed -0.000000 -0.062001
133      ▁argument     C  only transformed -0.000000 -0.061828
134   ▁application     C  only transformed -0.000000 -0.061666
135       question     C  only transformed -0.000000 -0.061559
136        ▁survey     C  only transformed -0.000000 -0.061321
137          ▁side     B  only transformed -0.000000 -0.061184
138          ▁song     N  only transformed -0.000000 -0.060741
139         ▁store     N  only transformed -0.000000 -0.060657
140        ▁action     N  only transformed -0.000000 -0.059464
141       ▁surface     B  only transformed -0.000000 -0.059441
142        ▁battle     C  only transformed -0.000000 -0.059039
143      ▁language     C  only transformed -0.000000 -0.058931
144         ▁fight     B  only transformed -0.000000 -0.058757
145          ▁film     B  only transformed -0.000000 -0.058660
146       ▁chapter     C  only transformed -0.000000 -0.058577
147        ▁spirit     C  only transformed -0.000000 -0.058413
148         ▁sound     C  only transformed -0.000000 -0.057649
149          ▁year     B  only transformed -0.000000 -0.057447
150    ▁collection     N  only transformed -0.000000 -0.057253
151        ▁search     C  only transformed -0.000000 -0.057230
152        ▁agency     C  only transformed -0.000000 -0.057121
153      ▁division     N  only transformed -0.000000 -0.056734
154          ▁face     B  only transformed -0.000000 -0.056550
155          ▁city     N  only transformed -0.000000 -0.056520
156       ▁contest     C  only transformed -0.000000 -0.056259
157      ▁reaction     C  only transformed -0.000000 -0.055855
158      ▁district     N  only transformed -0.000000 -0.055561
159          ▁sign     C  only transformed -0.000000 -0.055267
160           ▁age     B  only transformed -0.000000 -0.055224
161       ▁passage     C  only transformed -0.000000 -0.055154
162          ▁town     N  only transformed -0.000000 -0.055022
163         ▁space     N  only transformed -0.000000 -0.054553
164      ▁attitude     C  only transformed -0.000000 -0.054124
165         ▁movie     C  only transformed -0.000000 -0.054107
166   ▁perspective     B  only transformed -0.000000 -0.054066
167         ▁agent     C  only transformed -0.000000 -0.053914
168      ▁response     N  only transformed -0.000000 -0.053435
169         ▁power     B  only transformed -0.000000 -0.052366
170     ▁community     C  only transformed -0.000000 -0.051982
171          ▁post     N  only transformed -0.000000 -0.051865
172     ▁operation     N  only transformed -0.000000 -0.051546
173         ▁train     B  only transformed -0.000000 -0.051351
174          ▁call     B  only transformed -0.000000 -0.051131
175        ▁office     N  only transformed -0.000000 -0.051009
176          ▁host     B  only transformed -0.000000 -0.050918
177   ▁possibility     C  only transformed -0.000000 -0.050506
178         ▁video     B  only transformed -0.000000 -0.050227
179      ▁decision     N  only transformed -0.000000 -0.050024
180        ▁debate     C  only transformed -0.000000 -0.049974
181          ▁wall     C  only transformed -0.000000 -0.049718
182          ▁seat     N  only transformed -0.000000 -0.049026
183      ▁property     N  only transformed -0.000000 -0.048776
184          ▁shop     B  only transformed -0.000000 -0.048416
185      ▁ceremony     B  only transformed -0.000000 -0.048314
186          ▁suit     C  only transformed -0.000000 -0.048226
187         ▁guide     C  only transformed -0.000000 -0.048138
188  ▁organization     N  only transformed -0.000000 -0.048033
189          ▁land     N  only transformed -0.000000 -0.047825
190         ▁album     N  only transformed -0.000000 -0.047819
191      ▁business     N  only transformed -0.000000 -0.047693
192          ▁club     N  only transformed -0.000000 -0.047305
193          ▁test     N  only transformed -0.000000 -0.047232

====================================================================================================
=== original 12 <-> transformed 16   Jaccard = 0.184   |cos(z0, unmap(z~))| = 0.303
====================================================================================================
  original rho-candidate 12: matched transformed feature 16 is NOT in F_C (best-Jaccard transformed partner: 16, J=0.184)
  both: 21   only original: 28   only transformed: 65

label              B   C   N
in
both               3  15   3
only original      3  15  10
only transformed  23  35   7

              token label                in    Y0[12]     Y[16]
0        ▁criticism     C              both  0.296168  0.073192
1       ▁criticisms     C              both  0.275977  0.067286
2       ▁criticized     N              both  0.249487  0.106346
3          ▁critics     C              both  0.236009  0.059188
4       ▁criticised     C              both  0.231997  0.109129
5           ▁critic     B              both  0.226679  0.068819
6           ▁debate     C              both  0.193860  0.052778
7            ▁argue     C              both  0.192993  0.127031
8         ▁argument     C              both  0.185018  0.103259
9          ▁arguing     C              both  0.172339  0.102652
10          ▁argues     C              both  0.169768  0.136745
11     ▁accusations     C              both  0.167593  0.056764
12         ▁claimed     C              both  0.061691  0.167146
13         ▁debated     C              both  0.161368  0.068604
14       ▁complains     N              both  0.158367  0.071105
15         ▁accused     N              both  0.140367  0.090727
16        ▁comments     B              both  0.120197  0.085724
17          ▁claims     B              both  0.093368  0.119773
18         ▁praised     C              both  0.109167  0.093607
19     ▁discussions     C              both  0.107425  0.046703
20      ▁speculated     C              both  0.070314  0.099138
21     ▁controversy     C     only original  0.184404  0.000000
22   ▁controversies     C     only original  0.168965  0.000000
23        ▁critical     N     only original  0.139228  0.000000
24        ▁concerns     C     only original  0.133863  0.000000
25    ▁condemnation     C     only original  0.122970  0.000000
26        ▁question     N     only original  0.113192  0.000000
27          ▁issues     C     only original  0.110323  0.000000
28          ▁praise     C     only original  0.110139  0.000000
29           ▁issue     C     only original  0.108945  0.000000
30         ▁reviews     N     only original  0.100172  0.000000
31         ▁succeed     B     only original -0.098262 -0.000000
32         ▁opinion     C     only original  0.097473  0.000000
33      ▁successful     C     only original -0.094855 -0.000000
34         question     C     only original  0.093494  0.000000
35        ▁lawsuits     N     only original  0.090151  0.000000
36        ▁problems     B     only original  0.087971  0.000000
37       ▁succeeded     N     only original -0.084568 -0.000000
38          ▁review     C     only original  0.084463  0.000000
39         ▁regrets     C     only original  0.083539  0.000000
40         ▁success     C     only original -0.079994  0.000000
41        ▁feedback     N     only original  0.077295  0.000000
42           ▁fault     C     only original  0.071961 -0.000000
43           ▁jokes     B     only original  0.071506  0.000000
44          ▁indict     N     only original  0.067093  0.000000
45         ▁dislike     C     only original  0.066426  0.000000
46      ▁succeeding     N     only original -0.065272 -0.000000
47        ▁activist     N     only original  0.062130  0.000000
48         ▁crucial     N     only original  0.058176  0.000000
49            ▁said     B  only transformed  0.000000  0.226355
50          ▁stated     C  only transformed  0.000000  0.211623
51                3     B  only transformed -0.000000 -0.177673
52                5     B  only transformed -0.000000 -0.172876
53        ▁reported     C  only transformed  0.000000  0.172439
54                4     B  only transformed  0.000000 -0.171758
55                2     B  only transformed -0.000000 -0.169969
56                6     B  only transformed  0.000000 -0.169478
57                1     B  only transformed -0.000000 -0.169285
58                8     B  only transformed -0.000000 -0.169108
59                7     B  only transformed  0.000000 -0.166935
60                9     B  only transformed  0.000000 -0.162579
61           ▁noted     B  only transformed  0.000000  0.154844
62      ▁reportedly     C  only transformed  0.000000  0.146512
63                0     B  only transformed -0.000000 -0.146163
64          ▁saying     C  only transformed  0.000000  0.140709
65         ▁stating     B  only transformed  0.000000  0.130710
66       ▁described     B  only transformed  0.000000  0.130133
67       ▁suggested     C  only transformed  0.000000  0.124557
68       ▁allegedly     B  only transformed  0.000000  0.121139
69         ▁reports     C  only transformed  0.000000  0.112776
70       ▁purported     C  only transformed  0.000000  0.108769
71        ▁declared     B  only transformed  0.000000  0.108508
72       ▁indicated     N  only transformed -0.000000  0.107311
73       ▁statement     C  only transformed  0.000000  0.105922
74       ▁announced     B  only transformed -0.000000  0.102521
75       ▁according     B  only transformed  0.000000  0.101697
76        According     C  only transformed -0.000000  0.100987
77      ▁statements     C  only transformed  0.000000  0.098795
78          ▁report     N  only transformed  0.000000  0.094710
79    ▁acknowledged     C  only transformed  0.000000  0.094464
80         ▁pointed     C  only transformed  0.000000  0.092408
81          ▁listed     N  only transformed  0.000000  0.089300
82       ▁estimated     C  only transformed  0.000000  0.083606
83          ▁noting     C  only transformed  0.000000  0.081559
84       ▁specified     C  only transformed -0.000000  0.081439
85        ▁explains     C  only transformed  0.000000  0.080670
86       ▁confirmed     C  only transformed -0.000000  0.080061
87        ▁suggests     C  only transformed  0.000000  0.079413
88           ▁asked     B  only transformed  0.000000  0.078026
89       ▁describes     C  only transformed  0.000000  0.076862
90        ▁revealed     C  only transformed -0.000000  0.075429
91       ▁reporting     C  only transformed  0.000000  0.074363
92        ▁demanded     C  only transformed  0.000000  0.067601
93          ▁States     B  only transformed  0.000000  0.067018
94           ▁tells     C  only transformed  0.000000  0.065753
95           ▁wrote     B  only transformed  0.000000  0.065628
96      ▁underlined     C  only transformed  0.000000  0.064670
97            ▁note     C  only transformed  0.000000  0.063818
98         ▁likened     C  only transformed  0.000000  0.063244
99           ▁state     B  only transformed  0.000000  0.063008
100       ▁supposed     N  only transformed  0.000000  0.062695
101     ▁identified     N  only transformed -0.000000  0.062621
102          remark     C  only transformed  0.000000  0.061415
103       ▁attested     N  only transformed  0.000000  0.056954
104          ▁added     B  only transformed -0.000000  0.056022
105       ▁expected     N  only transformed  0.000000  0.053591
106       ▁conceded     C  only transformed  0.000000  0.052787
107     ▁ostensibly     C  only transformed  0.000000  0.052557
108     ▁recognised     C  only transformed -0.000000  0.049870
109        ▁thought     C  only transformed  0.000000  0.049537
110          ported     C  only transformed  0.000000  0.049084
111     ▁considered     C  only transformed  0.000000  0.049084
112        ▁believe     C  only transformed  0.000000  0.049023
113         ▁denied     C  only transformed  0.000000  0.045056

====================================================================================================
=== original 14 <-> transformed 45   Jaccard = 0.014   |cos(z0, unmap(z~))| = 0.499
====================================================================================================
  original rho-candidate 14: matched transformed feature 45 is NOT in F_C (best-Jaccard transformed partner: 97, J=0.027)
  both: 1   only original: 29   only transformed: 41

label              B   C   N
in
both               0   1   0
only original      0  18  11
only transformed  15   3  23

             token label                in    Y0[14]     Y[45]
0               ▁£     C              both  0.075694  0.067634
1       ▁favourite     C     only original  0.242569  0.000000
2       ▁organised     N     only original  0.239984  0.000000
3          ▁favour     C     only original  0.235022 -0.000000
4          ▁colour     C     only original  0.234159  0.000000
5      ▁recognised     C     only original  0.232410 -0.000000
6      ▁favourable     N     only original  0.232006 -0.000000
7          centred     C     only original  0.228000 -0.000000
8           centre     N     only original  0.222810  0.000000
9          ▁humour     C     only original  0.219280 -0.000000
10          arised     C     only original  0.215101  0.000000
11  ▁neighbourhood     N     only original  0.214198  0.000000
12         isation     C     only original  0.207676  0.000000
13    ▁watercolour     C     only original  0.203972 -0.000000
14        ▁Defence     C     only original  0.189209 -0.000000
15     ▁instalment     C     only original  0.186240 -0.000000
16        ▁clamour     C     only original  0.185310 -0.000000
17     ▁criticised     C     only original  0.184423  0.000000
18     ▁kilometres     N     only original  0.177666  0.000000
19           ising     C     only original  0.177662 -0.000000
20         vellous     C     only original  0.162409 -0.000000
21       ▁offences     N     only original  0.158537  0.000000
22           isers     C     only original  0.153597  0.000000
23      ▁Traveller     C     only original  0.128265 -0.000000
24     ▁Councillor     N     only original  0.118892 -0.000000
25           ▁RCMP     N     only original  0.085503  0.000000
26        ▁onwards     C     only original  0.080526  0.000000
27      ▁judgement     N     only original  0.069054  0.000000
28        ▁amongst     N     only original  0.065481 -0.000000
29     ▁footballer     N     only original  0.053182  0.000000
30               ▁     B  only transformed -0.000000  0.437916
31              ▁(     B  only transformed -0.000000  0.362468
32            \n\n     N  only transformed  0.000000  0.287602
33             ▁("     B  only transformed -0.000000  0.241173
34              \n     N  only transformed  0.000000  0.225888
35              ▁"     B  only transformed -0.000000  0.198786
36          \n\n\n     N  only transformed  0.000000  0.192090
37              ▁$     B  only transformed -0.000000  0.181342
38            ▁...     C  only transformed -0.000000  0.179078
39        \n\n\n\n     N  only transformed  0.000000  0.162547
40              ▁[     N  only transformed -0.000000  0.156536
41              ▁-     N  only transformed  0.000000  0.147641
42      \n\n\n\n\n     N  only transformed  0.000000  0.143080
43               (     N  only transformed -0.000000  0.142129
44          ▁[...]     C  only transformed  0.000000  0.132792
45               :     B  only transformed -0.000000  0.131817
46              ▁'     B  only transformed  0.000000  0.129094
47             ▁(-     N  only transformed -0.000000  0.126257
48              ▁/     N  only transformed  0.000000  0.123642
49             ...     C  only transformed  0.000000  0.111301
50              ▁{     N  only transformed -0.000000  0.109523
51    \n\n\n\n\n\n     N  only transformed -0.000000  0.107373
52              ▁▁     N  only transformed  0.000000  0.105632
53              ▁–     N  only transformed  0.000000  0.097441
54              ▁.     B  only transformed -0.000000  0.095065
55             }}(     N  only transformed -0.000000  0.089096
56              ▁*     N  only transformed -0.000000  0.087811
57               ,     B  only transformed -0.000000  0.083750
58               ;     B  only transformed -0.000000  0.080838
59              ▁&     B  only transformed  0.000000  0.080364
60              ▁#     N  only transformed -0.000000  0.079945
61               %     B  only transformed  0.000000 -0.066516
62               /     B  only transformed  0.000000  0.066315
63               ′     N  only transformed -0.000000 -0.064457
64             ▁{\     N  only transformed -0.000000  0.063589
65            ▁The     B  only transformed -0.000000  0.059723
66              ":     B  only transformed -0.000000  0.059472
67              :[     N  only transformed  0.000000  0.057901
68              ▁>     N  only transformed  0.000000  0.057344
69          ▁https     N  only transformed  0.000000  0.046530
70               ″     N  only transformed -0.000000 -0.046055

====================================================================================================
=== original 16 <-> transformed 90   Jaccard = 0.021   |cos(z0, unmap(z~))| = 0.047
====================================================================================================
  original rho-candidate 16: matched transformed feature 90 is NOT in F_C (best-Jaccard transformed partner: 49, J=0.023)
  both: 1   only original: 16   only transformed: 30

label              B  C  N
in
both               0  0  1
only original      5  7  4
only transformed  19  5  6

          token label                in    Y0[16]     Y[90]
0         ghold     N              both  0.164926 -0.067817
1         ▁hold     B     only original  0.437892 -0.000000
2      ▁holding     B     only original  0.410343 -0.000000
3        ▁holds     C     only original  0.390235 -0.000000
4         ▁held     B     only original  0.363963 -0.000000
5       ▁holder     C     only original  0.302337 -0.000000
6       ▁Holden     C     only original  0.242072 -0.000000
7         ▁host     B     only original  0.218935 -0.000000
8        ▁hosts     C     only original  0.206806 -0.000000
9      ▁hosting     N     only original  0.205919 -0.000000
10         hang     N     only original  0.094188  0.000000
11     ▁hanging     C     only original  0.088171 -0.000000
12    ▁retained     C     only original  0.081869 -0.000000
13       ▁grasp     C     only original  0.079484 -0.000000
14       ▁owner     N     only original  0.073183 -0.000000
15    ▁detained     N     only original  0.072487 -0.000000
16      ▁owners     B     only original  0.067304 -0.000000
17     ▁through     B  only transformed -0.000000  0.382335
18     ▁Through     C  only transformed -0.000000  0.381314
19      through     B  only transformed -0.000000  0.369809
20          ▁by     B  only transformed -0.000000  0.327732
21          ▁By     C  only transformed -0.000000  0.324555
22           By     B  only transformed -0.000000  0.303401
23      ▁though     B  only transformed  0.000000  0.162700
24      ▁Though     N  only transformed  0.000000  0.144630
25       Though     C  only transformed  0.000000  0.137869
26            7     B  only transformed  0.000000 -0.129975
27            4     B  only transformed  0.000000 -0.129311
28            5     B  only transformed -0.000000 -0.129111
29            6     B  only transformed  0.000000 -0.128759
30            3     B  only transformed  0.000000 -0.122786
31            1     B  only transformed -0.000000 -0.121796
32            8     B  only transformed  0.000000 -0.120152
33            2     B  only transformed -0.000000 -0.118964
34            9     B  only transformed  0.000000 -0.118224
35            0     B  only transformed -0.000000 -0.106527
36         From     B  only transformed -0.000000  0.086381
37  ▁throughout     B  only transformed -0.000000  0.083479
38        ▁from     B  only transformed -0.000000  0.070826
39    ▁Although     N  only transformed  0.000000  0.066412
40       ▁using     C  only transformed -0.000000  0.065542
41    ▁although     B  only transformed  0.000000  0.062037
42         augh     C  only transformed -0.000000  0.054021
43          rou     N  only transformed -0.000000  0.051636
44         bole     N  only transformed -0.000000  0.051137
45      ▁across     N  only transformed  0.000000  0.049993
46         ▁par     N  only transformed  0.000000  0.049794

====================================================================================================
=== original 18 <-> transformed 43   Jaccard = 0.818   |cos(z0, unmap(z~))| = 0.797
====================================================================================================
  original rho-candidate 18: matched transformed feature 43 is NOT in F_C (best-Jaccard transformed partner: 43, J=0.818)
  both: 27   only original: 2   only transformed: 4

label             B   C  N
in
both              2  21  4
only original     0   0  2
only transformed  0   3  1

           token label                in    Y0[18]     Y[43]
0       ▁selling     C              both -0.367265  0.383514
1          ▁sold     C              both -0.356350  0.375206
2        selling     C              both -0.345568  0.352436
3           sold     C              both -0.332679  0.341030
4          ▁sale     C              both -0.313728  0.340931
5         ▁sales     B              both -0.298785  0.309585
6         seller     C              both -0.233597  0.240022
7        ▁buying     C              both -0.187721  0.164793
8        ▁bought     N              both -0.166125  0.130279
9    ▁purchasing     C              both -0.163364  0.139761
10    ▁marketing     C              both -0.156449  0.133413
11  ▁bestselling     C              both -0.119365  0.124179
12    ▁promotion     N              both -0.112056  0.081020
13       ▁retail     N              both -0.109782  0.077467
14       ▁market     C              both -0.108456  0.096110
15  ▁promotional     C              both -0.099915  0.073342
16      ▁pricing     C              both -0.098708  0.082444
17      ▁popular     C              both -0.098632  0.083586
18       Vendors     C              both -0.096858  0.089455
19   ▁popularity     C              both -0.095757  0.085939
20   ▁commercial     C              both -0.095059  0.084927
21    ▁promoting     C              both -0.085655  0.060531
22      ▁revenue     C              both -0.084829  0.082991
23      ▁Popular     N              both -0.080690  0.055259
24      ▁promote     B              both -0.077699  0.050953
25          ales     C              both -0.072301  0.071570
26  ▁distributor     C              both -0.069040  0.057795
27     ▁pitching     N     only original -0.062603  0.000000
28         gross     N     only original -0.055836  0.000000
29        ▁agent     C  only transformed -0.000000  0.070471
30       ▁agents     C  only transformed -0.000000  0.069883
31      ▁product     N  only transformed -0.000000  0.059323
32          selt     C  only transformed -0.000000  0.058795

====================================================================================================
=== original 20 <-> transformed 14   Jaccard = 0.830   |cos(z0, unmap(z~))| = 0.900
====================================================================================================
  original rho-candidate 20: matched transformed feature 14 is NOT in F_C (best-Jaccard transformed partner: 14, J=0.830)
  both: 39   only original: 2   only transformed: 6

label             B   C  N
in
both              5  26  8
only original     0   2  0
only transformed  2   3  1

            token label                in    Y0[20]     Y[14]
0           ▁show     N              both -0.249136 -0.355586
1            show     C              both -0.227196 -0.327731
2        ▁showing     C              both -0.253096 -0.309136
3         ▁showed     C              both -0.219540 -0.290975
4          ▁shown     C              both -0.218164 -0.281359
5        ▁display     N              both -0.253762 -0.239747
6      ▁displayed     C              both -0.242620 -0.231731
7       ▁displays     C              both -0.242270 -0.221520
8       ▁showcase     C              both -0.215088 -0.204944
9      ▁depicting     C              both -0.191842 -0.139371
10       ▁portray     C              both -0.179097 -0.123964
11     ▁depiction     C              both -0.176932 -0.118806
12    ▁portraying     C              both -0.174735 -0.112564
13       showcase     C              both -0.172634 -0.168124
14      ▁depicted     C              both -0.172171 -0.143269
15     ▁portrayal     B              both -0.168341 -0.110445
16    ▁depictions     C              both -0.153899 -0.096846
17    ▁exhibition     C              both -0.152371 -0.151930
18     ▁presented     B              both -0.138307 -0.105196
19    ▁illustrate     C              both -0.135587 -0.131669
20  ▁representing     N              both -0.133846 -0.059502
21   ▁represented     N              both -0.129236 -0.064378
22     ▁represent     C              both -0.127107 -0.064015
23        ▁reveal     C              both -0.115824 -0.120511
24      ▁presents     N              both -0.116034 -0.077818
25    ▁indicating     N              both -0.101871 -0.063998
26        ▁appear     C              both -0.100533 -0.094041
27     ▁highlight     C              both -0.100223 -0.081056
28    ▁exposition     C              both -0.095854 -0.073890
29     ▁presenter     N              both -0.095666 -0.058461
30      ▁revealed     C              both -0.090612 -0.093922
31      ▁appeared     B              both -0.089950 -0.085980
32     ▁indicated     N              both -0.087193 -0.067839
33       ▁appears     B              both -0.086135 -0.077931
34    ▁appearance     C              both -0.084273 -0.071573
35       ▁present     C              both -0.083207 -0.062453
36      ▁featured     B              both -0.077652 -0.074240
37     ▁manifests     C              both -0.072392 -0.059261
38       ▁picture     C              both -0.057744 -0.043714
39     ▁reflected     C     only original -0.071696 -0.000000
40     ▁rendition     C     only original -0.060950 -0.000000
41        ▁listed     N  only transformed -0.000000 -0.053855
42          ▁disp     C  only transformed -0.000000 -0.047904
43         ▁teach     C  only transformed -0.000000 -0.046395
44     ▁described     B  only transformed -0.000000 -0.045848
45         ▁debut     B  only transformed -0.000000 -0.045483
46        ▁screen     C  only transformed -0.000000 -0.044268

====================================================================================================
=== original 22 <-> transformed 46   Jaccard = 0.612   |cos(z0, unmap(z~))| = 0.772
====================================================================================================
  original rho-candidate 22: matched transformed feature 46 is NOT in F_C (best-Jaccard transformed partner: 46, J=0.612)
  both: 30   only original: 2   only transformed: 17

label              B   C  N
in
both               1  28  1
only original      0   2  0
only transformed  10   6  1

          token label                in    Y0[22]     Y[46]
0        ▁magic     C              both -0.335203  0.343738
1         magic     C              both -0.318595  0.328887
2         Magic     C              both -0.325404  0.324246
3        ▁Magic     B              both -0.321181  0.319039
4      ▁magical     C              both -0.272586  0.261656
5       magical     C              both -0.255612  0.243915
6      ▁Magical     C              both -0.243084  0.218895
7       ▁wizard     C              both -0.210105  0.174679
8      ▁wizards     C              both -0.200820  0.168750
9       ▁Wizard     C              both -0.189358  0.149757
10  ▁witchcraft     C              both -0.173728  0.151361
11       wizard     C              both -0.165673  0.140820
12     ▁Wizards     C              both -0.162359  0.134422
13       ▁witch     C              both -0.159153  0.129492
14       ▁Witch     C              both -0.159083  0.124829
15     ▁witches     C              both -0.153685  0.126556
16    ▁Sorcerer     C              both -0.114455  0.093125
17          wiz     C              both -0.108997  0.082182
18        ▁wand     C              both -0.100099  0.064307
19          Mag     N              both -0.098430  0.066188
20     ▁fantasy     C              both -0.086542  0.075637
21   ▁fairytale     C              both -0.082084  0.075040
22    ▁mythical     C              both -0.078143  0.064336
23     ▁Warlock     C              both -0.067568  0.054337
24      ▁Merlin     C              both -0.066612  0.045824
25       ▁charm     C              both -0.065922  0.055919
26     ▁potions     C              both -0.064128  0.054235
27       ▁elves     C              both -0.061515  0.055752
28    ▁unicorns     C              both -0.059956  0.055111
29   ▁imaginary     C              both -0.057382  0.049514
30   ▁Fantastic     C     only original -0.059474  0.000000
31         ▁Wic     C     only original -0.055630  0.000000
32            4     B  only transformed  0.000000 -0.116042
33            6     B  only transformed  0.000000 -0.115412
34            5     B  only transformed -0.000000 -0.113997
35            7     B  only transformed -0.000000 -0.112836
36            9     B  only transformed -0.000000 -0.109076
37            8     B  only transformed -0.000000 -0.108913
38            3     B  only transformed -0.000000 -0.105391
39            0     B  only transformed  0.000000 -0.104475
40            2     B  only transformed -0.000000 -0.104036
41            1     B  only transformed -0.000000 -0.102327
42      ffindor     C  only transformed  0.000000 -0.065970
43      ▁secret     C  only transformed -0.000000  0.064259
44     ▁mystery     C  only transformed -0.000000  0.060200
45  ▁Cinderella     C  only transformed -0.000000  0.050658
46     ▁secrets     C  only transformed -0.000000  0.050076
47     ▁madness     C  only transformed -0.000000  0.048016
48     ▁Special     N  only transformed -0.000000  0.045429

====================================================================================================
=== original 23 <-> transformed 9   Jaccard = 0.738   |cos(z0, unmap(z~))| = 0.654
====================================================================================================
  original rho-candidate 23: matched transformed feature 9 is NOT in F_C (best-Jaccard transformed partner: 9, J=0.738)
  both: 110   only original: 10   only transformed: 29

label              B   C   N
in
both              26  64  20
only original      0   7   3
only transformed   9  16   4

            token label                in    Y0[23]      Y[9]
0         ▁remain     C              both  0.102930 -0.140493
1           ▁take     B              both  0.120262 -0.137534
2           ▁have     B              both  0.087286 -0.134300
3           ▁stay     B              both  0.103800 -0.130770
4        ▁receive     C              both  0.120348 -0.129154
5          ▁learn     C              both  0.128936 -0.104757
6          ▁serve     C              both  0.095420 -0.127120
7        ▁improve     B              both  0.125445 -0.085301
8           ▁hold     B              both  0.089271 -0.125000
9       ▁continue     C              both  0.115023 -0.124636
10       ▁promote     B              both  0.124416 -0.087386
11        ▁become     B              both  0.098546 -0.124364
12            ▁go     C              both  0.099336 -0.122138
13       ▁provide     C              both  0.116231 -0.121356
14    ▁contribute     N              both  0.121311 -0.103299
15   ▁participate     C              both  0.118731 -0.110369
16         ▁speak     C              both  0.111553 -0.118614
17         ▁adopt     C              both  0.117764 -0.091346
18            ▁be     B              both  0.084047 -0.117250
19         ▁teach     C              both  0.115581 -0.110114
20    ▁understand     C              both  0.114404 -0.095210
21         ▁avoid     C              both  0.114271 -0.092483
22        ▁assume     C              both  0.113282 -0.110080
23        ▁accept     C              both  0.112326 -0.099997
24          ▁make     B              both  0.112199 -0.105067
25         ▁begin     N              both  0.111793 -0.079683
26        ▁attend     C              both  0.102096 -0.111684
27       ▁explore     N              both  0.111412 -0.070922
28      ▁maintain     B              both  0.110790 -0.087899
29       ▁protect     C              both  0.109660 -0.083597
30     ▁negotiate     N              both  0.109268 -0.062986
31          ▁rely     C              both  0.108627 -0.108092
32         ▁occur     N              both  0.090379 -0.106893
33            ▁do     C              both  0.081969 -0.106646
34        ▁appear     C              both  0.088214 -0.106396
35       ▁collect     N              both  0.105072 -0.065410
36         ▁adapt     C              both  0.104245 -0.060379
37         ▁reach     C              both  0.097613 -0.104053
38          ▁grow     C              both  0.103908 -0.101316
39          ▁find     C              both  0.103602 -0.098802
40          ▁know     C              both  0.082783 -0.103330
41        ▁belong     C              both  0.075441 -0.103171
42     ▁represent     C              both  0.091235 -0.103109
43       ▁contain     C              both  0.080810 -0.102463
44      ▁conclude     N              both  0.101866 -0.076675
45         ▁argue     C              both  0.101271 -0.091530
46       ▁confirm     N              both  0.101099 -0.065765
47          ▁move     B              both  0.100248 -0.098088
48      ▁escalate     C              both  0.100042 -0.062913
49       ▁emulate     C              both  0.099979 -0.061487
50         ▁carry     N              both  0.094899 -0.099789
51       ▁qualify     C              both  0.099113 -0.088924
52         ▁start     B              both  0.098989 -0.071990
53         ▁offer     N              both  0.085259 -0.098285
54        ▁follow     C              both  0.084530 -0.097386
55       ▁deliver     C              both  0.097338 -0.094196
56       ▁include     B              both  0.081826 -0.097187
57        ▁defend     N              both  0.096946 -0.068971
58         ▁spend     C              both  0.093325 -0.096002
59          ▁play     B              both  0.087053 -0.095772
60           ▁see     B              both  0.095719 -0.084428
61         ▁enter     C              both  0.095462 -0.070030
62       ▁believe     C              both  0.079136 -0.095190
63           ▁run     B              both  0.075080 -0.095002
64          ▁turn     C              both  0.087008 -0.094849
65       ▁embrace     N              both  0.094703 -0.068538
66       ▁violate     C              both  0.094246 -0.073598
67         ▁exist     C              both  0.076141 -0.093967
68        ▁expect     C              both  0.093429 -0.090881
69       ▁destroy     C              both  0.092658 -0.062671
70    ▁illustrate     C              both  0.092168 -0.067289
71           ▁pay     N              both  0.092087 -0.078497
72           ▁use     B              both  0.079324 -0.091133
73         ▁write     C              both  0.089986 -0.081957
74       ▁succeed     B              both  0.089782 -0.088039
75          ▁help     B              both  0.084880 -0.089539
76         ▁build     N              both  0.089030 -0.068665
77         ▁think     C              both  0.087860 -0.088446
78         ▁treat     C              both  0.085365 -0.075017
79          ▁save     C              both  0.085310 -0.075842
80          ▁call     B              both  0.071196 -0.085115
81         ▁visit     C              both  0.069109 -0.084418
82        ▁return     B              both  0.075521 -0.083718
83        ▁reject     C              both  0.083397 -0.058076
84      ▁resemble     C              both  0.079964 -0.083221
85      ▁comprise     C              both  0.067352 -0.083038
86          ▁deal     C              both  0.070253 -0.083035
87      ▁coincide     C              both  0.081791 -0.077924
88          ▁pass     C              both  0.076135 -0.080377
89        ▁reveal     C              both  0.080121 -0.062149
90          ▁walk     N              both  0.079875 -0.069083
91        ▁depart     N              both  0.079826 -0.057259
92         ▁steal     C              both  0.079747 -0.059894
93          ▁work     B              both  0.061945 -0.079651
94          ▁rise     C              both  0.075608 -0.079466
95          ▁pick     N              both  0.078387 -0.054588
96          ▁draw     C              both  0.077805 -0.069804
97        ▁affect     N              both  0.076988 -0.070054
98          ▁fall     B              both  0.071176 -0.076425
99         ▁focus     B              both  0.075698 -0.061884
100        ▁drive     B              both  0.068228 -0.074123
101      ▁uncover     C              both  0.073825 -0.055403
102         ▁show     N              both  0.071376 -0.071842
103      ▁support     N              both  0.069480 -0.058677
104        ▁shift     C              both  0.068451 -0.049355
105        ▁fight     B              both  0.068320 -0.067328
106         ▁feed     C              both  0.064963 -0.057923
107         ▁lift     C              both  0.064094 -0.047254
108       ▁change     C              both  0.063603 -0.064037
109      ▁portray     C              both  0.060136 -0.044360
110       ▁ratify     N     only original  0.092611 -0.000000
111        ▁expel     N     only original  0.075452 -0.000000
112       ▁select     N     only original  0.068807 -0.000000
113    ▁highlight     C     only original  0.063580 -0.000000
114       ▁launch     C     only original  0.062318 -0.000000
115         ▁read     C     only original  0.058767 -0.000000
116     ▁showcase     C     only original  0.058422 -0.000000
117      ▁refrain     C     only original  0.057537 -0.000000
118        ▁grasp     C     only original  0.055411 -0.000000
119      ▁decline     C     only original  0.054109 -0.000000
120          ▁are     B  only transformed  0.000000 -0.085359
121          have     N  only transformed  0.000000 -0.079135
122      ▁consist     C  only transformed  0.000000 -0.077584
123         ▁lead     C  only transformed  0.000000 -0.077127
124         ▁ride     C  only transformed  0.000000 -0.069083
125         ▁need     C  only transformed  0.000000 -0.068309
126         ▁live     B  only transformed  0.000000 -0.065972
127         ▁mean     C  only transformed  0.000000 -0.062703
128         ▁face     B  only transformed  0.000000 -0.062317
129        ▁cover     C  only transformed  0.000000 -0.060265
130       ▁travel     C  only transformed  0.000000 -0.058416
131    ▁encounter     C  only transformed  0.000000 -0.058012
132          ▁put     C  only transformed  0.000000 -0.057043
133          give     C  only transformed  0.000000 -0.057007
134          ▁let     N  only transformed  0.000000 -0.056976
135          ▁own     B  only transformed  0.000000 -0.053704
136          ▁die     C  only transformed  0.000000 -0.053521
137       ▁report     N  only transformed  0.000000 -0.050352
138        ▁match     N  only transformed  0.000000 -0.050107
139     ▁struggle     B  only transformed  0.000000 -0.049855
140          ▁was     B  only transformed -0.000000  0.049362
141   ▁experience     B  only transformed  0.000000 -0.048469
142          ▁hit     C  only transformed  0.000000 -0.047612
143        ▁chase     C  only transformed  0.000000 -0.046957
144         ▁form     B  only transformed  0.000000 -0.046550
145      ▁contact     C  only transformed  0.000000 -0.045811
146         ▁were     B  only transformed  0.000000 -0.045112
147     ▁confront     C  only transformed  0.000000 -0.044740
148       ▁confer     C  only transformed  0.000000 -0.044547

====================================================================================================
=== original 24 <-> transformed 83   Jaccard = 0.717   |cos(z0, unmap(z~))| = 0.700
====================================================================================================
  original rho-candidate 24: matched transformed feature 83 is NOT in F_C (best-Jaccard transformed partner: 83, J=0.717)
  both: 33   only original: 12   only transformed: 1

label             B   C  N
in
both              2  22  9
only original     0   7  5
only transformed  0   1  0

           token label                in    Y0[24]     Y[83]
0         ▁death     B              both -0.250940 -0.324217
1        ▁killed     C              both -0.310320 -0.320730
2       ▁killing     C              both -0.297756 -0.287384
3         ▁kills     C              both -0.283489 -0.292996
4          ▁died     B              both -0.210847 -0.281517
5          ▁dead     C              both -0.211203 -0.271282
6         ▁Death     C              both -0.211940 -0.265287
7          ▁dies     C              both -0.196686 -0.263695
8      ▁murdered     C              both -0.248971 -0.213845
9           ▁die     C              both -0.168056 -0.246927
10      ▁killers     N              both -0.237188 -0.171040
11       ▁murder     C              both -0.229338 -0.199114
12       ▁killer     N              both -0.225219 -0.155635
13          ▁Die     N              both -0.137895 -0.173684
14     ▁massacre     N              both -0.161113 -0.081188
15       ▁massac     N              both -0.151936 -0.082223
16      ▁destroy     C              both -0.119314 -0.088373
17     ▁destroys     C              both -0.116722 -0.085290
18      ▁posthum     N              both -0.113498 -0.102503
19        ▁alive     C              both -0.094932 -0.111260
20    ▁graveyard     C              both -0.099690 -0.082651
21       ▁tragic     C              both -0.092394 -0.061588
22       ▁graves     C              both -0.082855 -0.053733
23  ▁resurrected     C              both -0.078072 -0.065348
24     ▁attacked     C              both -0.077200 -0.062322
25      ▁extinct     N              both -0.074441 -0.062457
26      ▁wounded     N              both -0.070680 -0.047246
27      ▁attacks     C              both -0.070529 -0.053877
28    ▁resurrect     C              both -0.068349 -0.056521
29      ▁resurre     C              both -0.065769 -0.062289
30    ▁sacrifice     C              both -0.065335 -0.051386
31    ▁surviving     C              both -0.064249 -0.053842
32     ▁survived     N              both -0.057770 -0.059999
33     ▁shooting     N     only original -0.080616 -0.000000
34         ▁mour     N     only original -0.078298 -0.000000
35        assins     N     only original -0.077623 -0.000000
36     ▁tortured     C     only original -0.076409 -0.000000
37     ▁horrible     C     only original -0.073912 -0.000000
38    ▁attacking     C     only original -0.068725 -0.000000
39     ▁terrible     C     only original -0.066218 -0.000000
40         ▁shot     N     only original -0.065636 -0.000000
41       ▁terror     N     only original -0.065016 -0.000000
42       ▁horror     C     only original -0.060832 -0.000000
43     sacrifice     C     only original -0.058915 -0.000000
44     ▁abducted     C     only original -0.054890 -0.000000
45      ▁defeats     C  only transformed -0.000000 -0.050917

====================================================================================================
=== original 25 <-> transformed 60   Jaccard = 0.422   |cos(z0, unmap(z~))| = 0.592
====================================================================================================
  original rho-candidate 25: matched transformed feature 60 is NOT in F_C (best-Jaccard transformed partner: 60, J=0.422)
  both: 65   only original: 22   only transformed: 67

label              B   C   N
in
both              18  32  15
only original      0  13   9
only transformed  21  27  19

              token label                in    Y0[25]     Y[60]
0            ▁great     B              both -0.206997 -0.181474
1             ▁high     C              both -0.182827 -0.202040
2           ▁strong     C              both -0.181225 -0.151735
3             ▁rich     N              both -0.174719 -0.097745
4              ▁big     N              both -0.092687 -0.169765
5             ▁good     C              both -0.168258 -0.132365
6              ▁low     N              both -0.166018 -0.127080
7        ▁fantastic     C              both -0.159272 -0.076590
8             ▁poor     B              both -0.157103 -0.093159
9              high     N              both -0.140732 -0.152989
10            ▁very     B              both -0.151939 -0.105047
11           ▁large     B              both -0.103206 -0.151077
12        ▁terrible     C              both -0.140565 -0.064611
13            ▁long     C              both -0.097698 -0.138770
14        ▁powerful     B              both -0.138241 -0.106833
15            ▁weak     C              both -0.136572 -0.094378
16            ▁deep     C              both -0.133945 -0.115106
17     ▁significant     C              both -0.078957 -0.130192
18            ▁full     C              both -0.124758 -0.128995
19          ▁highly     C              both -0.128038 -0.097313
20            ▁easy     C              both -0.127371 -0.094954
21            ▁High     B              both -0.109630 -0.122481
22           ▁Great     B              both -0.122020 -0.102727
23           ▁short     B              both -0.114387 -0.121884
24             rich     N              both -0.118331 -0.056297
25              low     C              both -0.116374 -0.080657
26            ▁hard     C              both -0.114666 -0.085991
27            ▁real     C              both -0.089909 -0.113183
28            ▁well     N              both -0.112812 -0.104486
29          ▁little     B              both -0.112241 -0.112016
30           ▁clear     N              both -0.112052 -0.075663
31           ▁small     N              both -0.111361 -0.100430
32            ▁fair     B              both -0.111249 -0.055778
33            ▁cool     N              both -0.110099 -0.053447
34           ▁tight     C              both -0.108698 -0.065831
35            ▁much     C              both -0.104562 -0.081073
36   ▁extraordinary     C              both -0.104200 -0.057352
37          ▁fairly     C              both -0.102271 -0.048734
38          ▁simple     C              both -0.102044 -0.085556
39            ▁tall     C              both -0.101552 -0.093210
40            ▁rare     C              both -0.099328 -0.072053
41         ▁immense     C              both -0.098895 -0.070388
42           ▁brief     N              both -0.098154 -0.058050
43          ▁really     C              both -0.097761 -0.066733
44         ▁serious     C              both -0.091171 -0.097129
45        ▁complete     N              both -0.093384 -0.080427
46           ▁whole     B              both -0.081717 -0.089516
47       ▁difficult     B              both -0.087857 -0.060375
48             ▁far     C              both -0.087772 -0.085021
49          ▁poorly     C              both -0.086122 -0.051511
50           ▁fresh     N              both -0.084721 -0.051223
51       ▁realistic     B              both -0.083758 -0.048624
52       ▁extensive     N              both -0.083493 -0.069402
53        ▁superior     C              both -0.082463 -0.061621
54             ▁hot     N              both -0.079309 -0.055639
55            ▁less     B              both -0.077094 -0.051414
56             full     C              both -0.076636 -0.076551
57        ▁absolute     C              both -0.073639 -0.074358
58             ▁new     B              both -0.069176 -0.071850
59            ▁more     B              both -0.071396 -0.057005
60   ▁comprehensive     N              both -0.070855 -0.050695
61            ▁free     C              both -0.070211 -0.061687
62             ▁few     C              both -0.069385 -0.051026
63        ▁negative     B              both -0.063135 -0.057623
64           ▁young     B              both -0.058480 -0.050788
65        ▁horrible     C     only original -0.115186 -0.000000
66            ▁mild     N     only original -0.112650 -0.000000
67          ▁richer     C     only original -0.112405 -0.000000
68      ▁delightful     N     only original -0.109258 -0.000000
69          ▁richly     C     only original -0.105897 -0.000000
70       ▁Fantastic     C     only original -0.091360 -0.000000
71        ▁friendly     N     only original -0.088591 -0.000000
72          ▁lively     C     only original -0.083952 -0.000000
73      ▁reasonably     C     only original -0.082141 -0.000000
74            ▁Nice     N     only original -0.082003 -0.000000
75          ▁wealth     C     only original -0.078188 -0.000000
76             ▁fun     C     only original -0.074764 -0.000000
77        ▁cheerful     C     only original -0.071294 -0.000000
78      ▁completely     C     only original -0.070376 -0.000000
79      ▁favourable     N     only original -0.070294 -0.000000
80          ▁lavish     C     only original -0.070017 -0.000000
81             ▁sad     N     only original -0.069598 -0.000000
82        ▁flexible     N     only original -0.069293 -0.000000
83        ▁somewhat     C     only original -0.065096 -0.000000
84            ▁dark     C     only original -0.064371 -0.000000
85       ▁ambitious     N     only original -0.062792 -0.000000
86            mense     N     only original -0.059954 -0.000000
87           ▁major     N  only transformed -0.000000 -0.154698
88       ▁important     C  only transformed -0.000000 -0.135643
89            ▁main     C  only transformed  0.000000 -0.127733
90             ▁key     B  only transformed  0.000000 -0.123084
91         ▁primary     B  only transformed  0.000000 -0.122956
92       ▁principal     C  only transformed  0.000000 -0.105843
93     ▁fundamental     C  only transformed -0.000000 -0.103534
94          ▁direct     B  only transformed -0.000000 -0.103206
95         ▁general     C  only transformed -0.000000 -0.094494
96             ▁Big     C  only transformed -0.000000 -0.094094
97           ▁total     B  only transformed -0.000000 -0.092710
98         ▁crucial     N  only transformed -0.000000 -0.092046
99         ▁central     C  only transformed  0.000000 -0.090927
100        ▁notable     B  only transformed -0.000000 -0.089632
101             Big     C  only transformed -0.000000 -0.087309
102      ▁essential     C  only transformed  0.000000 -0.086618
103     ▁particular     B  only transformed -0.000000 -0.083826
104         ▁actual     N  only transformed -0.000000 -0.082093
105        ▁highest     N  only transformed -0.000000 -0.081635
106       ▁critical     N  only transformed -0.000000 -0.081559
107           Major     C  only transformed  0.000000 -0.079179
108          ▁Major     N  only transformed  0.000000 -0.078644
109       ▁dominant     C  only transformed -0.000000 -0.078318
110      ▁secondary     N  only transformed -0.000000 -0.077508
111        ▁popular     C  only transformed -0.000000 -0.076437
112         ▁common     N  only transformed -0.000000 -0.075130
113     ▁successful     C  only transformed -0.000000 -0.073098
114       ▁specific     N  only transformed -0.000000 -0.070891
115         ▁famous     B  only transformed -0.000000 -0.067737
116         ▁public     C  only transformed -0.000000 -0.066824
117           ▁late     N  only transformed -0.000000 -0.066691
118      ▁practical     B  only transformed -0.000000 -0.065960
119          ▁extra     B  only transformed -0.000000 -0.064963
120        ▁leading     B  only transformed -0.000000 -0.064769
121         ▁larger     N  only transformed -0.000000 -0.064413
122           ▁best     B  only transformed -0.000000 -0.064319
123          ▁early     B  only transformed -0.000000 -0.064193
124        ▁overall     B  only transformed -0.000000 -0.064058
125         ▁active     B  only transformed -0.000000 -0.063598
126       ▁indirect     C  only transformed -0.000000 -0.062222
127         ▁Little     C  only transformed -0.000000 -0.061496
128     ▁individual     B  only transformed -0.000000 -0.060563
129        ▁classic     C  only transformed -0.000000 -0.060187
130          ▁local     N  only transformed -0.000000 -0.059831
131        ▁private     B  only transformed -0.000000 -0.059263
132      ▁paramount     C  only transformed  0.000000 -0.059188
133         ▁widely     N  only transformed -0.000000 -0.059106
134      ▁different     B  only transformed -0.000000 -0.058493
135        ▁typical     B  only transformed -0.000000 -0.058170
136        ▁partial     C  only transformed -0.000000 -0.058166
137          ▁final     B  only transformed -0.000000 -0.057973
138    ▁influential     N  only transformed -0.000000 -0.057853
139          ▁valid     C  only transformed -0.000000 -0.057075
140           ▁near     B  only transformed -0.000000 -0.055029
141       ▁original     B  only transformed -0.000000 -0.054755
142         ▁formal     N  only transformed -0.000000 -0.052219
143    ▁independent     C  only transformed -0.000000 -0.052213
144         ▁lesser     C  only transformed -0.000000 -0.052077
145   ▁particularly     C  only transformed -0.000000 -0.050759
146            ▁non     C  only transformed -0.000000 -0.049588
147         ▁single     N  only transformed -0.000000 -0.049550
148       ▁explicit     C  only transformed -0.000000 -0.049356
149        ▁distant     C  only transformed -0.000000 -0.049071
150        ▁eminent     N  only transformed -0.000000 -0.047700
151            ▁mid     N  only transformed -0.000000 -0.047175
152    ▁prestigious     N  only transformed -0.000000 -0.046997
153    ▁overarching     C  only transformed  0.000000 -0.046951

====================================================================================================
=== original 28 <-> transformed 28   Jaccard = 0.815   |cos(z0, unmap(z~))| = 0.811
====================================================================================================
  original rho-candidate 28: matched transformed feature 28 is NOT in F_C (best-Jaccard transformed partner: 28, J=0.815)
  both: 22   only original: 2   only transformed: 3

label             B  C  N
in
both              8  9  5
only original     0  2  0
only transformed  1  1  1

        token label                in    Y0[28]     Y[28]
0       ▁four     B              both  0.263204  0.309798
1      ▁seven     B              both  0.274705  0.299432
2        ▁six     B              both  0.267988  0.297615
3       ▁five     B              both  0.277432  0.297564
4      ▁eight     B              both  0.273145  0.290999
5       ▁nine     C              both  0.282803  0.290363
6      ▁three     B              both  0.234034  0.274789
7        four     C              both  0.234845  0.258387
8     ▁eleven     C              both  0.253639  0.242350
9       ▁Five     N              both  0.221376  0.164181
10       Nine     C              both  0.220552  0.161051
11       ▁two     B              both  0.167020  0.215651
12  ▁nineteen     C              both  0.215025  0.191733
13    ▁Eleven     N              both  0.206694  0.128361
14    ▁twenty     C              both  0.195624  0.169001
15      Three     C              both  0.186024  0.162061
16       ▁Ten     N              both  0.163567  0.082321
17     ▁fifty     C              both  0.158619  0.120624
18       ▁Two     N              both  0.130341  0.110087
19   ▁several     B              both  0.071384  0.094382
20    ▁dozens     C              both  0.066466  0.056503
21      ▁trio     N              both  0.065435  0.064322
22       teen     C     only original  0.067312  0.000000
23      ▁half     C     only original  0.055000  0.000000
24       ▁one     B  only transformed  0.000000  0.070252
25  ▁multiple     N  only transformed  0.000000  0.053533
26   ▁seventh     C  only transformed  0.000000  0.047992

====================================================================================================
=== original 33 <-> transformed 97   Jaccard = 0.593   |cos(z0, unmap(z~))| = 0.379
====================================================================================================
  original rho-candidate 33: matched transformed feature 97 is NOT in F_C (best-Jaccard transformed partner: 97, J=0.593)
  both: 64   only original: 22   only transformed: 22

label              B   C   N
in
both              13  34  17
only original      0  12  10
only transformed   5   7  10

         token label                in    Y0[33]     Y[97]
0          ing     B              both -0.171343 -0.227568
1         ings     C              both -0.157075 -0.216350
2          ism     B              both -0.154723 -0.211255
3        izing     N              both -0.205028 -0.186561
4         ists     C              both -0.151653 -0.202478
5        ingly     C              both -0.193334 -0.196036
6          ist     N              both -0.111587 -0.194515
7        ising     C              both -0.185580 -0.175555
8        ments     N              both -0.149730 -0.181479
9         ment     C              both -0.126012 -0.173136
10   istically     C              both -0.172654 -0.146168
11     isation     C              both -0.167558 -0.169477
12      ations     C              both -0.149961 -0.161821
13        able     C              both -0.137021 -0.156244
14          ed     B              both -0.121454 -0.151384
15       ement     C              both -0.121544 -0.143337
16          ly     B              both -0.119721 -0.142557
17       isers     C              both -0.142173 -0.111006
18      nesses     N              both -0.137714 -0.054834
19         ors     B              both -0.117582 -0.135189
20         ies     B              both -0.085532 -0.132565
21       ering     N              both -0.124529 -0.092861
22        ates     B              both -0.105709 -0.123118
23     atively     C              both -0.122461 -0.072673
24         ary     N              both -0.108028 -0.121619
25        ning     C              both -0.120475 -0.115418
26       ative     N              both -0.119679 -0.089980
27   ification     N              both -0.117692 -0.057748
28       oring     C              both -0.114138 -0.066360
29       ently     C              both -0.113445 -0.080113
30         ate     B              both -0.087313 -0.112698
31         ted     N              both -0.109556 -0.088522
32        ures     C              both -0.107928 -0.105680
33         ish     N              both -0.085505 -0.107068
34          es     B              both -0.062407 -0.106465
35        ious     C              both -0.106329 -0.071548
36         ely     C              both -0.106141 -0.106028
37         ous     N              both -0.106044 -0.097377
38       tions     C              both -0.105756 -0.084617
39       ishes     C              both -0.104270 -0.081059
40       ators     C              both -0.104091 -0.100209
41        ring     B              both -0.099903 -0.092464
42          ry     C              both -0.067112 -0.099434
43          er     B              both -0.067521 -0.095888
44         hip     N              both -0.094170 -0.091971
45        ling     C              both -0.093944 -0.088420
46        ical     N              both -0.091991 -0.065727
47      isters     N              both -0.091302 -0.064014
48       aters     C              both -0.090100 -0.066805
49        bles     C              both -0.089707 -0.051909
50         ory     B              both -0.072417 -0.088491
51        ties     C              both -0.088271 -0.084787
52        ance     N              both -0.087092 -0.078052
53       arian     C              both -0.083606 -0.072073
54         age     C              both -0.075237 -0.083529
55         sed     C              both -0.082308 -0.066756
56        teen     C              both -0.080894 -0.081588
57         ets     N              both -0.081471 -0.054864
58         cts     B              both -0.078039 -0.055297
59         ian     N              both -0.066619 -0.077459
60        ards     C              both -0.076044 -0.052854
61         ens     C              both -0.066310 -0.074807
62         ons     C              both -0.067000 -0.071941
63         med     C              both -0.068202 -0.050745
64      uality     N     only original -0.131486 -0.000000
65     ography     N     only original -0.105100 -0.000000
66      arised     C     only original -0.096243 -0.000000
67       oning     N     only original -0.089528 -0.000000
68       liest     C     only original -0.089171 -0.000000
69         née     N     only original -0.087018 -0.000000
70       isons     C     only original -0.085669 -0.000000
71        cked     C     only original -0.085244 -0.000000
72      asting     C     only original -0.081851 -0.000000
73       acles     N     only original -0.078186 -0.000000
74         xes     C     only original -0.077937 -0.000000
75        eses     N     only original -0.077643 -0.000000
76        cled     C     only original -0.074852  0.000000
77     matical     C     only original -0.073768 -0.000000
78        leys     C     only original -0.072355 -0.000000
79        lets     N     only original -0.071652 -0.000000
80        bery     C     only original -0.068459 -0.000000
81        ined     C     only original -0.066904 -0.000000
82    ographer     N     only original -0.065031  0.000000
83       eking     C     only original -0.062835 -0.000000
84       aches     N     only original -0.062552 -0.000000
85        kers     N     only original -0.062281 -0.000000
86         men     N  only transformed -0.000000 -0.080911
87       inger     C  only transformed -0.000000 -0.077107
88           a     B  only transformed -0.000000  0.073807
89          ys     C  only transformed -0.000000 -0.073182
90         man     B  only transformed -0.000000 -0.067237
91         urs     C  only transformed -0.000000 -0.063351
92         isk     C  only transformed -0.000000 -0.063012
93         ine     N  only transformed -0.000000 -0.061580
94          ic     C  only transformed -0.000000 -0.059016
95         aly     N  only transformed -0.000000 -0.057947
96           k     B  only transformed  0.000000  0.057513
97         ars     N  only transformed -0.000000 -0.056445
98         ler     N  only transformed -0.000000 -0.055983
99         ans     N  only transformed -0.000000 -0.055554
100        les     C  only transformed -0.000000 -0.055536
101        way     N  only transformed -0.000000 -0.052954
102         al     B  only transformed -0.000000 -0.052892
103        ves     C  only transformed -0.000000 -0.052239
104        ati     N  only transformed -0.000000 -0.049117
105        iss     N  only transformed -0.000000 -0.048538
106         is     B  only transformed -0.000000 -0.047703
107         ls     N  only transformed -0.000000 -0.045704

====================================================================================================
=== original 35 <-> transformed 36   Jaccard = 0.409   |cos(z0, unmap(z~))| = 0.871
====================================================================================================
  original rho-candidate 35: matched transformed feature 36 is NOT in F_C (best-Jaccard transformed partner: 36, J=0.409)
  both: 9   only original: 3   only transformed: 10

label              B  C  N
in
both               2  5  2
only original      0  2  1
only transformed  10  0  0

         token label                in    Y0[35]     Y[36]
0        ▁open     C              both -0.485531  0.424430
1         open     C              both -0.456490  0.403250
2        ▁Open     N              both -0.443943  0.350423
3      ▁opened     B              both -0.364800  0.290021
4     ▁opening     B              both -0.336315  0.239580
5      ▁closed     C              both -0.261273  0.212926
6    ▁enclosed     N              both -0.098670  0.054976
7      ▁sealed     C              both -0.090083  0.054317
8          ▁op     C              both -0.070360  0.049956
9    ▁expanded     C     only original -0.093224  0.000000
10  ▁expanding     N     only original -0.084693  0.000000
11  ▁expansion     C     only original -0.075343  0.000000
12           3     B  only transformed -0.000000  0.192896
13           6     B  only transformed -0.000000  0.189816
14           4     B  only transformed  0.000000  0.189764
15           5     B  only transformed  0.000000  0.187606
16           1     B  only transformed  0.000000  0.185390
17           2     B  only transformed  0.000000  0.183441
18           8     B  only transformed -0.000000  0.182505
19           7     B  only transformed  0.000000  0.182440
20           9     B  only transformed  0.000000  0.176749
21           0     B  only transformed  0.000000  0.169817

====================================================================================================
=== original 36 <-> transformed 8   Jaccard = 0.098   |cos(z0, unmap(z~))| = 0.127
====================================================================================================
  original rho-candidate 36: matched transformed feature 8 is NOT in F_C (best-Jaccard transformed partner: 36, J=0.146)
  both: 5   only original: 23   only transformed: 23

label             B   C  N
in
both              1   4  0
only original     6   8  9
only transformed  4  16  3

           token label                in    Y0[36]      Y[8]
0        ▁follow     C              both  0.337463  0.114154
1       ▁follows     C              both  0.316833  0.117055
2      ▁followed     C              both  0.314228  0.058737
3     ▁following     B              both  0.260917  0.095743
4        ▁sequel     C              both  0.113558  0.052957
5          ▁lead     C     only original  0.340382 -0.000000
6         ▁leads     B     only original  0.304501 -0.000000
7           ▁led     B     only original  0.291213 -0.000000
8       ▁leading     B     only original  0.261298 -0.000000
9     ▁followers     C     only original  0.213191  0.000000
10      ▁trailed     N     only original  0.168344 -0.000000
11      ▁leaders     C     only original  0.140936 -0.000000
12         ▁open     C     only original  0.127718  0.000000
13        ▁chase     C     only original  0.119371  0.000000
14          open     C     only original  0.111087  0.000000
15         ▁Open     N     only original  0.111014  0.000000
16  ▁accompanied     N     only original  0.109888  0.000000
17     ▁resulted     N     only original  0.101764 -0.000000
18      ▁opening     B     only original  0.095193  0.000000
19    ▁resulting     N     only original  0.094849  0.000000
20       ▁opened     B     only original  0.093100 -0.000000
21     ▁prompted     N     only original  0.092123 -0.000000
22      ▁pursuit     N     only original  0.090586  0.000000
23     ▁tracking     N     only original  0.083552 -0.000000
24      ▁stalked     N     only original  0.083189 -0.000000
25       ▁closed     C     only original  0.077696 -0.000000
26        ▁guide     C     only original  0.075001  0.000000
27     ▁directed     B     only original  0.063788  0.000000
28       ▁coming     C  only transformed  0.000000  0.340253
29        coming     C  only transformed -0.000000  0.339084
30           ▁go     C  only transformed  0.000000  0.332937
31         ▁goes     B  only transformed  0.000000  0.317612
32         going     C  only transformed -0.000000  0.298544
33           ▁Go     C  only transformed  0.000000  0.273864
34         ▁went     B  only transformed  0.000000  0.259625
35          gone     C  only transformed -0.000000  0.247002
36        ▁comes     C  only transformed  0.000000  0.243049
37         ▁came     N  only transformed  0.000000  0.216956
38         ▁Came     C  only transformed -0.000000  0.185534
39           gow     C  only transformed  0.000000  0.148351
40         ▁move     B  only transformed  0.000000  0.100244
41       ▁moving     C  only transformed  0.000000  0.098995
42         ▁next     C  only transformed  0.000000  0.093839
43           got     C  only transformed -0.000000  0.083209
44        ▁moved     B  only transformed -0.000000  0.072018
45        ▁visit     C  only transformed -0.000000  0.066726
46       ▁future     N  only transformed -0.000000  0.059219
47         Forth     C  only transformed  0.000000  0.059100
48       ▁visits     C  only transformed  0.000000  0.053982
49    ▁undergoes     C  only transformed -0.000000  0.051660
50      ▁arrived     N  only transformed -0.000000  0.049512

====================================================================================================
=== original 38 <-> transformed 50   Jaccard = 0.469   |cos(z0, unmap(z~))| = 0.878
====================================================================================================
  original rho-candidate 38: matched transformed feature 50 is NOT in F_C (best-Jaccard transformed partner: 50, J=0.469)
  both: 23   only original: 5   only transformed: 21

label             B   C  N
in
both              6  16  1
only original     1   4  0
only transformed  4   9  8

            token label                in    Y0[38]     Y[50]
0        ▁writing     B              both -0.344599  0.327740
1        ▁written     B              both -0.338865  0.322754
2         written     C              both -0.329211  0.303999
3         writing     C              both -0.328144  0.305133
4          ▁write     C              both -0.321078  0.286575
5         ▁writer     B              both -0.261005  0.299389
6          ▁wrote     B              both -0.295483  0.272584
7        ▁writers     C              both -0.261689  0.287138
8         ▁author     C              both -0.125602  0.193447
9        ▁authors     C              both -0.129533  0.190382
10        ▁scribe     C              both -0.117099  0.126424
11    ▁manuscript     C              both -0.091752  0.109249
12       ▁letters     C              both -0.101610  0.084288
13      ▁literary     C              both -0.101184  0.099441
14      ▁novelist     C              both -0.069711  0.100560
15        ▁letter     C              both -0.095356  0.084631
16           ▁pen     C              both -0.074651  0.093785
17          ▁poet     B              both -0.064788  0.092696
18    ▁literature     B              both -0.087319  0.078625
19        ▁script     C              both -0.086407  0.074519
20         ▁prose     C              both -0.078853  0.073230
21          ▁oral     N              both -0.078638  0.049221
22          ▁text     C              both -0.068139  0.077702
23         ▁reads     C     only original -0.157337  0.000000
24          ▁read     C     only original -0.154988 -0.000000
25       ▁reading     B     only original -0.153444  0.000000
26          ▁Read     C     only original -0.112356 -0.000000
27      ▁literacy     C     only original -0.085477  0.000000
28    ▁publishing     C  only transformed -0.000000  0.100515
29     ▁published     B  only transformed -0.000000  0.096441
30   ▁publication     B  only transformed -0.000000  0.080756
31      ▁composer     N  only transformed -0.000000  0.080115
32        ▁editor     N  only transformed -0.000000  0.079379
33     ▁publisher     C  only transformed  0.000000  0.076911
34    ▁publishers     C  only transformed -0.000000  0.076756
35     ▁publishes     N  only transformed -0.000000  0.073901
36         ▁words     C  only transformed -0.000000  0.067225
37      ▁language     C  only transformed -0.000000  0.062524
38     ▁dramatist     N  only transformed -0.000000  0.059779
39       ▁article     B  only transformed -0.000000  0.056678
40        ▁Editor     N  only transformed -0.000000  0.056658
41          ▁word     C  only transformed -0.000000  0.056256
42           ▁Pen     B  only transformed -0.000000  0.056235
43  ▁publications     N  only transformed -0.000000  0.056041
44       language     C  only transformed -0.000000  0.051531
45        ▁pencil     C  only transformed -0.000000  0.050850
46      ▁printing     C  only transformed -0.000000  0.047438
47        ▁edited     N  only transformed -0.000000  0.046696
48      ▁articles     N  only transformed -0.000000  0.045915

====================================================================================================
=== original 51 <-> transformed 34   Jaccard = 0.514   |cos(z0, unmap(z~))| = 0.731
====================================================================================================
  original rho-candidate 51: matched transformed feature 34 is NOT in F_C (best-Jaccard transformed partner: 34, J=0.514)
  both: 19   only original: 2   only transformed: 16

label             B   C  N
in
both              2  12  5
only original     1   0  1
only transformed  5   7  4

           token label                in    Y0[51]     Y[34]
0          ▁most     B              both  0.256093  0.389634
1           most     C              both  0.253766  0.377504
2       ▁longest     C              both  0.292167  0.191911
3          ▁Most     N              both  0.215476  0.289509
4       ▁fastest     C              both  0.287410  0.203151
5          ▁best     B              both  0.266392  0.256596
6      ▁funniest     C              both  0.262571  0.201665
7       ▁largest     N              both  0.261737  0.145288
8        largest     N              both  0.253452  0.138861
9       ▁highest     N              both  0.241103  0.159589
10        ariest     C              both  0.229478  0.181422
11         tiest     C              both  0.229318  0.189532
12         liest     C              both  0.222645  0.186813
13          Best     C              both  0.222117  0.185983
14         ▁Best     C              both  0.209042  0.180392
15        ▁least     N              both  0.188980  0.115382
16       ▁latest     C              both  0.135524  0.135465
17  ▁bestselling     C              both  0.089002  0.072035
18    ▁favourite     C              both  0.075947  0.053224
19         ▁same     B     only original  0.070237  0.000000
20         wurst     N     only original  0.065460  0.000000
21          ▁she     B  only transformed  0.000000  0.149225
22          ▁her     B  only transformed -0.000000  0.143289
23           her     C  only transformed -0.000000  0.118916
24           She     B  only transformed -0.000000  0.116231
25      ▁herself     C  only transformed -0.000000  0.111702
26           Her     N  only transformed  0.000000  0.109695
27         ▁more     B  only transformed  0.000000  0.100557
28          more     C  only transformed  0.000000  0.100256
29          ▁She     N  only transformed -0.000000  0.099186
30          ▁Her     N  only transformed  0.000000  0.097565
31         ▁last     B  only transformed  0.000000  0.082519
32       ▁almost     C  only transformed  0.000000  0.074609
33         ▁next     C  only transformed  0.000000  0.071301
34          ▁bes     C  only transformed  0.000000  0.058496
35           ost     N  only transformed  0.000000  0.052918
36          tier     C  only transformed  0.000000  0.051736

====================================================================================================
=== original 52 <-> transformed 53   Jaccard = 0.232   |cos(z0, unmap(z~))| = 0.290
====================================================================================================
  original rho-candidate 52: matched transformed feature 53 is NOT in F_C (best-Jaccard transformed partner: 26, J=0.412)
  both: 19   only original: 14   only transformed: 49

label              B   C   N
in
both               4  14   1
only original      2  10   2
only transformed  12  18  19

            token label                in    Y0[52]     Y[53]
0            ▁old     C              both -0.125755 -0.292247
1            ▁age     B              both -0.240170 -0.271989
2          ▁young     B              both -0.267155 -0.184159
3          ▁youth     N              both -0.251814 -0.091893
4           ▁aged     B              both -0.221074 -0.249446
5        ▁younger     C              both -0.240946 -0.198603
6       ▁youthful     C              both -0.237705 -0.149163
7          ▁Young     B              both -0.231615 -0.144914
8            ▁Old     C              both -0.104487 -0.230204
9           Older     C              both -0.173125 -0.226305
10       ▁ancient     C              both -0.070726 -0.221884
11            age     C              both -0.178540 -0.204159
12         ▁adult     C              both -0.201579 -0.088268
13        ▁adults     C              both -0.191080 -0.070723
14          ▁Ages     C              both -0.173036 -0.177998
15   ▁adolescence     C              both -0.169645 -0.060311
16       ▁Ancient     C              both -0.065856 -0.166309
17     ▁childhood     C              both -0.156120 -0.084477
18        ▁mature     C              both -0.141419 -0.112931
19           ▁kid     C     only original -0.206166 -0.000000
20          ▁kids     C     only original -0.205839  0.000000
21      ▁children     B     only original -0.195674  0.000000
22          child     C     only original -0.185735  0.000000
23          ▁teen     C     only original -0.179166 -0.000000
24         ▁Child     B     only original -0.178079  0.000000
25       Children     C     only original -0.171531  0.000000
26           teen     C     only original -0.129970 -0.000000
27          ▁baby     C     only original -0.106903  0.000000
28           ▁boy     C     only original -0.098487  0.000000
29     ▁innocence     C     only original -0.083603 -0.000000
30       ▁parents     C     only original -0.076748 -0.000000
31         ▁larva     N     only original -0.076381 -0.000000
32        ▁Senior     N     only original -0.068335 -0.000000
33        ▁modern     N  only transformed -0.000000 -0.156001
34  ▁contemporary     C  only transformed -0.000000 -0.151110
35   contemporary     C  only transformed -0.000000 -0.140876
36       ▁century     B  only transformed -0.000000 -0.131578
37    ▁historical     B  only transformed  0.000000 -0.125395
38        century     B  only transformed -0.000000 -0.121608
39     ▁centuries     N  only transformed -0.000000 -0.117802
40           ▁new     B  only transformed -0.000000 -0.113633
41      ▁previous     C  only transformed  0.000000 -0.112504
42          ▁past     N  only transformed -0.000000 -0.105957
43      ▁medieval     C  only transformed -0.000000 -0.103854
44       ▁classic     C  only transformed -0.000000 -0.103636
45       ▁earlier     C  only transformed -0.000000 -0.100965
46           ▁New     B  only transformed -0.000000 -0.095335
47        ▁former     N  only transformed -0.000000 -0.092831
48            New     C  only transformed -0.000000 -0.092346
49       ▁present     C  only transformed -0.000000 -0.089903
50       ▁decades     C  only transformed -0.000000 -0.087037
51       ▁current     N  only transformed -0.000000 -0.085480
52         ▁early     B  only transformed -0.000000 -0.082093
53      ▁Historic     N  only transformed -0.000000 -0.081626
54        ▁decade     C  only transformed -0.000000 -0.081536
55        ▁latest     C  only transformed -0.000000 -0.080009
56       ▁history     B  only transformed  0.000000 -0.077997
57  ▁historically     N  only transformed  0.000000 -0.075371
58      ▁classics     C  only transformed -0.000000 -0.070576
59        ▁future     N  only transformed -0.000000 -0.069618
60  ▁conventional     C  only transformed -0.000000 -0.065322
61          ▁late     N  only transformed -0.000000 -0.064256
62         ▁newly     N  only transformed -0.000000 -0.064210
63        ▁famous     B  only transformed -0.000000 -0.063772
64     ▁nostalgic     C  only transformed -0.000000 -0.063453
65           ▁Era     N  only transformed -0.000000 -0.062271
66     ▁precedent     C  only transformed  0.000000 -0.060630
67    ▁precedents     C  only transformed  0.000000 -0.060157
68   ▁established     N  only transformed -0.000000 -0.058665
69      ▁original     B  only transformed -0.000000 -0.055106
70     ▁Victorian     B  only transformed -0.000000 -0.054792
71      ▁heritage     N  only transformed -0.000000 -0.054616
72        Current     N  only transformed -0.000000 -0.054377
73      ▁ordinary     C  only transformed -0.000000 -0.052373
74    established     B  only transformed -0.000000 -0.051946
75       ▁extinct     N  only transformed -0.000000 -0.050949
76    ▁previously     N  only transformed  0.000000 -0.050926
77     ▁legendary     C  only transformed  0.000000 -0.046065
78      ▁formerly     N  only transformed  0.000000 -0.045776
79       ▁typical     B  only transformed -0.000000 -0.045469
80        ▁Future     N  only transformed -0.000000 -0.044524
81         ▁fresh     N  only transformed -0.000000 -0.044443

====================================================================================================
=== original 54 <-> transformed 65   Jaccard = 0.475   |cos(z0, unmap(z~))| = 0.758
====================================================================================================
  original rho-candidate 54: matched transformed feature 65 is NOT in F_C (best-Jaccard transformed partner: 65, J=0.475)
  both: 19   only original: 3   only transformed: 18

label             B   C  N
in
both              1  15  3
only original     0   1  2
only transformed  3   8  7

           token label                in    Y0[54]     Y[65]
0          ▁draw     C              both  0.456127  0.437802
1         ▁drawn     C              both  0.437064  0.420296
2       ▁drawing     C              both  0.409600  0.403111
3           Draw     N              both  0.403323  0.345618
4          ▁Drew     N              both  0.238012  0.151915
5     ▁attracted     C              both  0.206563  0.221185
6    ▁attraction     C              both  0.176405  0.197102
7        ▁sketch     N              both  0.162049  0.112345
8        ▁appeal     B              both  0.150366  0.161800
9   ▁attractions     C              both  0.131518  0.141268
10    ▁appealing     C              both  0.113301  0.117935
11      ▁dragged     C              both  0.090117  0.076620
12  ▁watercolour     C              both  0.073319  0.081014
13           raw     C              both  0.079975  0.080513
14  ▁illustrator     C              both  0.065822  0.078188
15        ▁charm     C              both  0.075636  0.076093
16           rew     C              both  0.075927  0.053953
17      ▁painted     C              both  0.066056  0.073941
18      ▁aroused     C              both  0.070063  0.072367
19          ▁Dre     N     only original  0.081524  0.000000
20         rafts     N     only original  0.070900  0.000000
21       ▁pencil     C     only original  0.066224  0.000000
22          ▁art     C  only transformed  0.000000  0.145495
23      ▁artwork     C  only transformed  0.000000  0.131948
24          ▁Art     N  only transformed  0.000000  0.121928
25     ▁artistic     N  only transformed  0.000000  0.089589
26         ▁Arts     B  only transformed  0.000000  0.088214
27          Arts     N  only transformed  0.000000  0.081617
28   ▁popularity     C  only transformed  0.000000  0.077863
29       ▁artist     N  only transformed  0.000000  0.068568
30    ▁attention     C  only transformed  0.000000  0.067609
31  ▁inspiration     C  only transformed  0.000000  0.067371
32     ▁Artistic     N  only transformed  0.000000  0.064005
33           ▁By     C  only transformed  0.000000  0.062562
34     ▁inspired     C  only transformed  0.000000  0.059035
35      ▁painter     N  only transformed  0.000000  0.057033
36            By     B  only transformed  0.000000  0.056660
37       renders     C  only transformed  0.000000  0.056323
38     ▁painters     N  only transformed  0.000000  0.051713
39           ▁by     B  only transformed -0.000000  0.046743

====================================================================================================
=== original 58 <-> transformed 2   Jaccard = 0.548   |cos(z0, unmap(z~))| = 0.826
====================================================================================================
  original rho-candidate 58: matched transformed feature 2 is NOT in F_C (best-Jaccard transformed partner: 2, J=0.548)
  both: 17   only original: 0   only transformed: 14

label             B  C  N
in
both              7  5  5
only transformed  4  6  4

         token label                in    Y0[58]      Y[2]
0      ▁fourth     B              both  0.409656 -0.395854
1       ▁fifth     C              both  0.398563 -0.376364
2       ▁third     B              both  0.389094 -0.390079
3       ▁sixth     B              both  0.382856 -0.351992
4     ▁seventh     C              both  0.366639 -0.321782
5      ▁second     B              both  0.285672 -0.318218
6      ▁Second     N              both  0.238102 -0.203027
7       ▁first     B              both  0.109397 -0.201186
8        Forth     C              both  0.133959 -0.087150
9           rd     C              both  0.131098 -0.107144
10       First     C              both  0.081993 -0.115525
11          th     B              both  0.108045 -0.083224
12  ▁secondary     N              both  0.096949 -0.093687
13          nd     N              both  0.095721 -0.071982
14     seconds     N              both  0.089400 -0.073504
15     ▁middle     B              both  0.081521 -0.079321
16         ▁IV     N              both  0.062735 -0.051477
17       ▁last     B  only transformed  0.000000 -0.117931
18       ▁next     C  only transformed  0.000000 -0.108809
19      ▁final     B  only transformed  0.000000 -0.085771
20   ▁nineteen     C  only transformed -0.000000  0.071350
21        Nine     C  only transformed -0.000000  0.067808
22     ▁Eleven     N  only transformed -0.000000  0.065136
23     ▁eleven     C  only transformed -0.000000  0.061883
24    ▁another     B  only transformed  0.000000 -0.059490
25       ▁Last     N  only transformed  0.000000 -0.059173
26     ▁latest     C  only transformed  0.000000 -0.054940
27        ▁Ten     N  only transformed -0.000000  0.054755
28  ▁inaugural     C  only transformed  0.000000 -0.052872
29           1     B  only transformed -0.000000  0.051745
30     Another     N  only transformed  0.000000 -0.045192

====================================================================================================
=== original 59 <-> transformed 7   Jaccard = 0.241   |cos(z0, unmap(z~))| = 0.642
====================================================================================================
  original rho-candidate 59: matched transformed feature 7 is NOT in F_C (best-Jaccard transformed partner: 7, J=0.241)
  both: 13   only original: 1   only transformed: 40

label             B   C   N
in
both              3   7   3
only original     0   0   1
only transformed  8  21  11

             token label                in    Y0[59]      Y[7]
0            ▁cast     C              both -0.495944 -0.404187
1            ▁Cast     N              both -0.469432 -0.313482
2             Cast     C              both -0.464085 -0.316705
3         ▁casting     C              both -0.411207 -0.335132
4           caster     N              both -0.258136 -0.151315
5          ▁actors     B              both -0.110944 -0.173905
6           ▁actor     B              both -0.097612 -0.162440
7           castle     C              both -0.153613 -0.093161
8         ▁actress     C              both -0.073600 -0.125044
9        ▁audition     B              both -0.079435 -0.104604
10      ▁broadcast     C              both -0.082697 -0.078019
11          asting     C              both -0.080575 -0.051249
12       ▁starring     N              both -0.065184 -0.078203
13             ast     N     only original -0.088499 -0.000000
14     ▁production     C  only transformed -0.000000 -0.233193
15      Production     C  only transformed -0.000000 -0.199024
16    ▁productions     C  only transformed -0.000000 -0.189862
17       ▁producer     B  only transformed -0.000000 -0.161646
18        ▁filming     C  only transformed -0.000000 -0.140296
19           ▁film     B  only transformed -0.000000 -0.129411
20       ▁produced     B  only transformed -0.000000 -0.125514
21     ▁characters     C  only transformed -0.000000 -0.114605
22          ▁films     B  only transformed  0.000000 -0.101460
23         ▁acting     C  only transformed -0.000000 -0.100777
24      ▁character     B  only transformed -0.000000 -0.098540
25        ▁Studios     C  only transformed -0.000000 -0.097254
26         ▁script     C  only transformed -0.000000 -0.097116
27          ▁movie     C  only transformed -0.000000 -0.093433
28       ▁director     B  only transformed -0.000000 -0.092615
29     ▁filmmaking     C  only transformed  0.000000 -0.091688
30      ▁streaming     C  only transformed -0.000000 -0.083382
31     ▁television     C  only transformed -0.000000 -0.080607
32      ▁Hollywood     C  only transformed -0.000000 -0.077045
33       ▁audience     C  only transformed -0.000000 -0.075719
34             ▁TV     C  only transformed -0.000000 -0.073795
35        ▁cinemat     N  only transformed -0.000000 -0.073102
36       ▁shooting     N  only transformed -0.000000 -0.072157
37   ▁performances     B  only transformed -0.000000 -0.070352
38          ▁roles     C  only transformed -0.000000 -0.069798
39       ▁Broadway     C  only transformed -0.000000 -0.068126
40      ▁audiences     C  only transformed -0.000000 -0.065066
41       ▁Director     N  only transformed -0.000000 -0.063986
42       ▁premiere     C  only transformed -0.000000 -0.061262
43     ▁rehearsals     N  only transformed -0.000000 -0.060497
44     ▁Television     N  only transformed -0.000000 -0.059105
45          ▁acted     N  only transformed -0.000000 -0.058773
46   ▁productivity     N  only transformed  0.000000 -0.054881
47           ▁role     B  only transformed  0.000000 -0.053378
48      ▁Directors     N  only transformed -0.000000 -0.053089
49    ▁manufacture     N  only transformed -0.000000 -0.052161
50  ▁Entertainment     C  only transformed -0.000000 -0.052052
51        ▁villain     C  only transformed -0.000000 -0.052008
52      ▁recording     N  only transformed -0.000000 -0.049975
53   ▁Broadcasting     N  only transformed -0.000000 -0.048034

====================================================================================================
=== original 62 <-> transformed 98   Jaccard = 0.584   |cos(z0, unmap(z~))| = 0.690
====================================================================================================
  original rho-candidate 62: matched transformed feature 98 is NOT in F_C (best-Jaccard transformed partner: 98, J=0.584)
  both: 66   only original: 15   only transformed: 32

label             B   C  N
in
both              9  56  1
only original     2   8  5
only transformed  6  21  5

              token label                in    Y0[62]     Y[98]
0          ▁stories     B              both  0.197203  0.235349
1            ▁story     B              both  0.192648  0.227876
2          ▁fiction     C              both  0.216938  0.217944
3            ▁tales     C              both  0.198822  0.213171
4        ▁fictional     C              both  0.193949  0.171717
5           fiction     C              both  0.175705  0.166776
6           ▁novels     C              both  0.147131  0.172095
7            ▁novel     B              both  0.133465  0.164603
8            ▁Tales     C              both  0.153828  0.162804
9        ▁narrative     C              both  0.157712  0.159239
10           ▁drama     N              both  0.158732  0.134863
11          ▁dramas     C              both  0.147446  0.120236
12            ▁saga     C              both  0.144424  0.141216
13      ▁characters     C              both  0.100991  0.142980
14        ▁thriller     C              both  0.139355  0.113802
15           ▁movie     C              both  0.137476  0.088111
16            ▁film     B              both  0.136829  0.083576
17         ▁romance     C              both  0.123014  0.135369
18           ▁films     B              both  0.130370  0.090101
19            ▁myth     C              both  0.128435  0.122297
20           ▁Novel     C              both  0.105936  0.123866
21       ▁character     B              both  0.080048  0.120924
22        ▁allegory     C              both  0.118966  0.114750
23         ▁fantasy     C              both  0.117603  0.116695
24       ▁portrayal     B              both  0.116359  0.094929
25        ▁novelist     C              both  0.116058  0.111530
26            ▁plot     C              both  0.114257  0.101685
27        ▁romances     C              both  0.108545  0.113496
28          ▁scenes     C              both  0.097837  0.110320
29       ▁adventure     C              both  0.105200  0.109479
30         ▁portray     C              both  0.108454  0.074536
31      ▁depictions     C              both  0.106828  0.076678
32          ▁legend     C              both  0.098622  0.105137
33           ▁humor     C              both  0.104120  0.094143
34       ▁depiction     C              both  0.103971  0.078349
35      ▁adventures     C              both  0.101600  0.103903
36       ▁imaginary     C              both  0.103888  0.089003
37        ▁depicted     C              both  0.103322  0.074274
38       ▁fairytale     C              both  0.101998  0.095311
39      ▁portraying     C              both  0.101423  0.071632
40          ▁imagin     C              both  0.099255  0.074905
41    ▁protagonists     C              both  0.099075  0.088938
42          ▁horror     C              both  0.097858  0.089598
43     ▁imagination     C              both  0.096839  0.092878
44       ▁depicting     C              both  0.093814  0.071151
45         ▁prequel     C              both  0.093542  0.078426
46        ▁mythical     C              both  0.091263  0.081406
47         ▁mystery     C              both  0.081230  0.088928
48          ▁humour     C              both  0.087948  0.080389
49           ▁jokes     B              both  0.087574  0.083961
50       ▁metaphors     C              both  0.085742  0.086055
51         ▁imagery     C              both  0.085191  0.071669
52            ▁hero     C              both  0.084416  0.076354
53          ▁script     C              both  0.080446  0.054853
54      ▁Chronicles     C              both  0.070173  0.080179
55          ▁sequel     C              both  0.078211  0.070422
56       ▁Adventure     C              both  0.077438  0.075781
57       ▁symbolism     C              both  0.075230  0.074715
58         ▁villain     C              both  0.074382  0.053686
59        ▁romantic     C              both  0.065312  0.072007
60         ▁clichés     C              both  0.071692  0.049468
61           ▁anime     C              both  0.070451  0.064164
62       ▁relatable     C              both  0.069401  0.048727
63          ▁heroic     C              both  0.067770  0.054860
64            ▁role     B              both  0.066216  0.053699
65           ▁roles     C              both  0.063508  0.051113
66           ▁actor     B     only original  0.104941  0.000000
67      ▁filmmaking     C     only original  0.097705  0.000000
68          ▁actors     B     only original  0.091855  0.000000
69       ▁Hollywood     C     only original  0.089772  0.000000
70         ▁filming     C     only original  0.089721  0.000000
71         ▁cinemat     N     only original  0.087143  0.000000
72         ▁actress     C     only original  0.084758  0.000000
73        ▁starring     N     only original  0.083970  0.000000
74          ▁acting     C     only original  0.071665  0.000000
75           ▁acted     N     only original  0.070660  0.000000
76          ▁action     N     only original  0.070027  0.000000
77       ▁harrowing     C     only original  0.063320  0.000000
78           action     C     only original  0.062438  0.000000
79       ▁dramatist     N     only original  0.061040  0.000000
80             ▁HBO     C     only original  0.058248  0.000000
81          ▁themes     C  only transformed  0.000000  0.127320
82           ▁theme     C  only transformed  0.000000  0.114485
83           ▁games     C  only transformed  0.000000  0.097406
84           themed     C  only transformed  0.000000  0.093472
85            ▁game     B  only transformed  0.000000  0.084724
86           ▁Games     N  only transformed  0.000000  0.080823
87      ▁literature     B  only transformed  0.000000  0.079161
88           ▁genre     B  only transformed  0.000000  0.077801
89        ▁literary     C  only transformed  0.000000  0.072163
90          ▁genres     C  only transformed  0.000000  0.071584
91          ▁dreams     B  only transformed  0.000000  0.069704
92          ▁series     B  only transformed  0.000000  0.063054
93       ▁franchise     C  only transformed  0.000000  0.061392
94            ▁Game     N  only transformed -0.000000  0.061147
95           ▁prose     C  only transformed  0.000000  0.059831
96        ▁universe     C  only transformed  0.000000  0.055847
97         ▁history     B  only transformed  0.000000  0.055479
98          ▁motifs     C  only transformed  0.000000  0.055301
99         ▁reality     C  only transformed  0.000000  0.055297
100       ▁dreaming     C  only transformed  0.000000  0.055050
101         ▁theory     C  only transformed  0.000000  0.054635
102          ▁songs     N  only transformed  0.000000  0.054589
103         ▁topics     C  only transformed  0.000000  0.054204
104       ▁creative     C  only transformed  0.000000  0.054047
105       ▁dialogue     N  only transformed  0.000000  0.052389
106            ▁fun     C  only transformed  0.000000  0.052214
107       ▁politics     C  only transformed  0.000000  0.051430
108    ▁inspiration     C  only transformed  0.000000  0.051224
109       ▁classics     C  only transformed  0.000000  0.049533
110  ▁characterized     N  only transformed  0.000000  0.048887
111       ▁inspired     C  only transformed  0.000000  0.048731
112       ▁memories     C  only transformed  0.000000  0.047216

====================================================================================================
=== original 67 <-> transformed 86   Jaccard = 0.927   |cos(z0, unmap(z~))| = 0.596
====================================================================================================
  original rho-candidate 67: matched transformed feature 86 is NOT in F_C (best-Jaccard transformed partner: 86, J=0.927)
  both: 102   only original: 2   only transformed: 6

label              B   C   N
in
both              11  74  17
only original      0   0   2
only transformed   2   4   0

              token label                in    Y0[67]     Y[86]
0            ▁gives     C              both -0.131270  0.145691
1            ▁takes     C              both -0.124787  0.139513
2             ▁goes     B              both -0.128561  0.136929
3            ▁comes     C              both -0.119407  0.136723
4           ▁allows     C              both -0.128063  0.136101
5          ▁teaches     C              both -0.136037  0.130675
6           ▁learns     C              both -0.134506  0.121036
7          ▁becomes     B              both -0.124716  0.133196
8               ▁is     B              both -0.073501  0.132090
9          ▁assumes     C              both -0.121612  0.131837
10           ▁tells     C              both -0.127678  0.129959
11        ▁delivers     C              both -0.124275  0.127841
12        ▁involves     C              both -0.112135  0.127615
13          ▁serves     C              both -0.108420  0.125640
14          ▁speaks     C              both -0.125350  0.124272
15           ▁feels     C              both -0.118665  0.123535
16       ▁undergoes     C              both -0.123094  0.112335
17         ▁appears     B              both -0.096834  0.123021
18           ▁makes     C              both -0.117913  0.122541
19         ▁extends     B              both -0.115618  0.122525
20          ▁enters     C              both -0.121124  0.108215
21        ▁contains     B              both -0.109530  0.120348
22          ▁weighs     N              both -0.119186  0.096830
23           ▁wants     C              both -0.095242  0.119113
24        ▁suggests     C              both -0.107677  0.118486
25    ▁incorporates     N              both -0.117856  0.104874
26        ▁includes     C              both -0.098893  0.116984
27         ▁manages     C              both -0.116528  0.106038
28         ▁follows     C              both -0.099403  0.116080
29           ▁looks     C              both -0.084541  0.115589
30            ▁sees     C              both -0.114696  0.115377
31         ▁engages     C              both -0.114949  0.097959
32             ▁has     B              both -0.079562  0.114450
33           ▁meets     C              both -0.114415  0.111561
34        ▁destroys     C              both -0.114350  0.090114
35         ▁carries     C              both -0.109165  0.114107
36        ▁consumes     N              both -0.113838  0.086959
37        ▁explains     C              both -0.113547  0.113170
38   ▁distinguishes     C              both -0.113142  0.105554
39           ▁lends     C              both -0.112785  0.105168
40         ▁differs     C              both -0.109530  0.112441
41          ▁exists     C              both -0.092893  0.112034
42           ▁emits     N              both -0.111976  0.080312
43          ▁offers     C              both -0.097582  0.111591
44       ▁describes     C              both -0.110527  0.111294
45           ▁holds     C              both -0.108915  0.110202
46       ▁publishes     N              both -0.109054  0.085240
47           ▁fills     N              both -0.108488  0.071803
48        ▁consists     N              both -0.096317  0.107747
49       ▁resembles     C              both -0.104071  0.107706
50         ▁focuses     C              both -0.107025  0.105775
51         ▁opposes     C              both -0.106097  0.101342
52         ▁refuses     C              both -0.104708  0.105943
53       ▁discovers     C              both -0.105499  0.101039
54            ▁owes     C              both -0.104909  0.099063
55           ▁plays     N              both -0.104856  0.094272
56         ▁reaches     C              both -0.104610  0.101333
57          ▁argues     C              both -0.096817  0.104082
58            ▁does     C              both -0.081330  0.101093
59           ▁leads     B              both -0.092133  0.100999
60           allows     C              both -0.100452  0.086454
61           ▁reads     C              both -0.100008  0.079203
62         ▁weakens     C              both -0.099786  0.078180
63         ▁resides     C              both -0.095497  0.099223
64           ▁rises     C              both -0.098689  0.079583
65         ▁intends     C              both -0.085760  0.097217
66           ▁loves     C              both -0.088787  0.096176
67          ▁stands     N              both -0.094834  0.090239
68      ▁progresses     C              both -0.093621  0.077923
69         ▁divides     C              both -0.092322  0.070156
70        ▁presents     N              both -0.085926  0.089227
71         ▁remains     N              both -0.085865  0.084355
72           ▁turns     B              both -0.085687  0.076476
73           ▁hides     C              both -0.083546  0.072713
74           ▁kills     C              both -0.081474  0.054005
75       ▁increases     C              both -0.080401  0.064533
76           ▁works     B              both -0.072161  0.080004
77           ▁Wants     C              both -0.079935  0.074214
78       ▁manifests     C              both -0.078310  0.066782
79          ▁covers     C              both -0.078226  0.075537
80           ▁likes     C              both -0.063236  0.077438
81            ▁lies     N              both -0.070919  0.075823
82          ▁leaves     C              both -0.075066  0.074709
83            means     C              both -0.063821  0.074630
84        ▁respects     C              both -0.074362  0.058784
85       ▁complains     N              both -0.074296  0.057368
86          ▁breaks     N              both -0.073474  0.044755
87            poses     C              both -0.071809  0.060409
88      ▁transforms     C              both -0.070981  0.049222
89            plays     C              both -0.070135  0.043305
90          ▁shares     N              both -0.069484  0.057018
91           ▁needs     N              both -0.059589  0.068563
92         ▁escapes     C              both -0.067305  0.049892
93         ▁defeats     C              both -0.065182  0.043354
94            ▁dies     C              both -0.064441  0.050701
95          ▁tastes     C              both -0.060256  0.062459
96           ▁faces     C              both -0.055032  0.060860
97          renders     C              both -0.058554  0.044546
98            ishes     C              both -0.057943  0.050505
99            ▁sets     B              both -0.056257  0.045032
100       ▁outlines     N              both -0.055721  0.045700
101          ▁rides     C              both -0.055043  0.043628
102          ▁feeds     N     only original -0.073494  0.000000
103          ▁flies     N     only original -0.055252  0.000000
104           ▁were     B  only transformed  0.000000 -0.074449
105          ▁lives     C  only transformed -0.000000  0.065244
106          ▁hosts     C  only transformed -0.000000  0.046745
107         ▁claims     B  only transformed -0.000000  0.042260
108       ▁displays     C  only transformed -0.000000  0.041913
109          ▁gains     C  only transformed -0.000000  0.041760

====================================================================================================
=== original 71 <-> transformed 71   Jaccard = 0.600   |cos(z0, unmap(z~))| = 0.882
====================================================================================================
  original rho-candidate 71: matched transformed feature 71 is NOT in F_C (best-Jaccard transformed partner: 71, J=0.600)
  both: 12   only original: 3   only transformed: 5

label             B  C  N
in
both              3  6  3
only original     2  1  0
only transformed  3  1  1

          token label                in    Y0[71]     Y[71]
0      ▁himself     C              both  0.488462  0.523508
1      ▁herself     C              both  0.462323  0.506151
2   ▁themselves     C              both  0.479205  0.416715
3       ▁myself     N              both  0.408376  0.348618
4          ▁him     B              both  0.171718  0.184506
5          ▁own     B              both  0.139266  0.177187
6           ▁me     C              both  0.120929  0.133346
7         ▁self     C              both  0.108325  0.130984
8          ▁his     B              both  0.062804  0.116911
9           ▁us     C              both  0.095332  0.111862
10       ▁alone     N              both  0.093987  0.078420
11           me     N              both  0.066983  0.066082
12        ▁them     B     only original  0.152544  0.000000
13        ▁Them     C     only original  0.147423  0.000000
14       ▁their     B     only original  0.068251 -0.000000
15        ▁they     B  only transformed  0.000000 -0.129226
16         They     B  only transformed  0.000000 -0.096870
17         ▁her     B  only transformed  0.000000  0.078850
18         selt     C  only transformed  0.000000  0.054412
19  ▁altogether     N  only transformed  0.000000  0.047228

====================================================================================================
=== original 73 <-> transformed 68   Jaccard = 0.650   |cos(z0, unmap(z~))| = 0.838
====================================================================================================
  original rho-candidate 73: matched transformed feature 68 is NOT in F_C (best-Jaccard transformed partner: 68, J=0.650)
  both: 26   only original: 1   only transformed: 13

label             B   C  N
in
both              5  18  3
only original     0   0  1
only transformed  1  12  0

           token label                in    Y0[73]     Y[68]
0          ▁book     B              both  0.388380  0.406083
1           book     C              both  0.361850  0.377495
2          ▁Book     B              both  0.371597  0.366000
3         ▁books     C              both  0.352544  0.357847
4         ▁Books     C              both  0.336889  0.326397
5    ▁bookstores     C              both  0.198719  0.192604
6        ▁novels     C              both  0.174522  0.153649
7         ▁novel     B              both  0.162098  0.138689
8      ▁textbook     C              both  0.161869  0.153375
9        ▁ebooks     C              both  0.155317  0.153398
10        ▁Novel     C              both  0.149361  0.116576
11        ▁album     N              both  0.146572  0.074961
12       ▁albums     N              both  0.135634  0.062401
13          Libr     C              both  0.129054  0.102926
14      ▁library     N              both  0.127717  0.091973
15      ▁Library     B              both  0.114356  0.078719
16      ▁chapter     C              both  0.094338  0.111432
17      ▁Chapter     C              both  0.097921  0.105714
18   ▁literature     B              both  0.098662  0.086078
19       ▁author     C              both  0.082501  0.091577
20     ▁novelist     C              both  0.090098  0.073764
21  ▁bestselling     C              both  0.073345  0.085372
22          ▁boo     C              both  0.084856  0.072468
23     ▁literary     C              both  0.082823  0.077913
24      ▁authors     C              both  0.068847  0.080957
25        ▁movie     C              both  0.074611  0.062295
26       ▁Albums     N     only original  0.121186  0.000000
27         ▁read     C  only transformed  0.000000  0.119405
28      ▁reading     B  only transformed  0.000000  0.114402
29        ▁reads     C  only transformed  0.000000  0.106877
30         ▁Read     C  only transformed  0.000000  0.092055
31      ▁Audible     C  only transformed  0.000000  0.066009
32        ▁pages     C  only transformed  0.000000  0.061077
33   ▁publishers     C  only transformed  0.000000  0.058953
34   ▁manuscript     C  only transformed  0.000000  0.056479
35       ▁volume     C  only transformed  0.000000  0.055084
36    ▁publisher     C  only transformed  0.000000  0.052520
37     ▁literacy     C  only transformed  0.000000  0.049777
38   ▁Scholastic     C  only transformed  0.000000  0.048885
39        ilogue     C  only transformed  0.000000  0.046617

====================================================================================================
=== original 78 <-> transformed 18   Jaccard = 0.049   |cos(z0, unmap(z~))| = 0.231
====================================================================================================
  original rho-candidate 78: matched transformed feature 18 is NOT in F_C (best-Jaccard transformed partner: 48, J=0.056)
  both: 4   only original: 28   only transformed: 49

label              B   C   N
in
both               0   3   1
only original      2  16  10
only transformed  22  18   9

            token label                in    Y0[78]     Y[18]
0         ▁denied     C              both  0.116579 -0.054416
1        ▁refuses     C              both  0.105425 -0.068158
2         ▁unable     C              both  0.077743 -0.103847
3      ▁inability     N              both  0.098256 -0.052620
4        ▁succeed     B     only original  0.345812 -0.000000
5     ▁successful     C     only original  0.337509  0.000000
6        ▁success     C     only original  0.322234 -0.000000
7      ▁succeeded     N     only original  0.320016 -0.000000
8         ▁failed     C     only original  0.291145 -0.000000
9     ▁succeeding     N     only original  0.276571  0.000000
10         failed     C     only original  0.269254 -0.000000
11      ▁rejected     C     only original  0.201087 -0.000000
12     ▁rejection     C     only original  0.194869 -0.000000
13      ▁accepted     N     only original  0.169073 -0.000000
14    ▁acceptance     C     only original  0.168351 -0.000000
15        ▁reject     C     only original  0.167939 -0.000000
16        ▁accept     C     only original  0.133983 -0.000000
17      ▁declined     C     only original  0.111975 -0.000000
18     ▁surviving     C     only original  0.093466  0.000000
19      ▁survived     N     only original  0.092041 -0.000000
20      ▁struggle     B     only original  0.091960 -0.000000
21    ▁attempting     N     only original  0.091386 -0.000000
22     ▁struggles     C     only original  0.089714 -0.000000
23       ▁defeats     C     only original  0.087057 -0.000000
24         ▁tried     C     only original  0.084773 -0.000000
25       ▁decline     C     only original  0.084296 -0.000000
26        ▁missed     N     only original  0.077338 -0.000000
27       ▁managed     N     only original  0.076145 -0.000000
28       ▁manages     C     only original  0.068298 -0.000000
29  ▁difficulties     N     only original  0.064911 -0.000000
30        ▁effort     N     only original  0.061397  0.000000
31     ▁endeavors     N     only original  0.060874 -0.000000
32            ▁no     B  only transformed  0.000000 -0.365299
33           ▁not     B  only transformed -0.000000 -0.308489
34          ▁none     C  only transformed  0.000000 -0.281346
35             no     B  only transformed  0.000000 -0.279140
36       ▁neither     C  only transformed  0.000000 -0.228383
37            ▁NO     N  only transformed  0.000000 -0.188808
38           ▁Not     N  only transformed -0.000000 -0.186883
39         ▁never     C  only transformed  0.000000 -0.182648
40           ▁all     B  only transformed -0.000000 -0.166066
41          ▁only     B  only transformed -0.000000 -0.151761
42            all     C  only transformed -0.000000 -0.151667
43        ▁cannot     C  only transformed  0.000000 -0.127289
44           ▁non     C  only transformed  0.000000 -0.127180
45              3     B  only transformed -0.000000 -0.125802
46              4     B  only transformed -0.000000 -0.124896
47              8     B  only transformed  0.000000 -0.124742
48              5     B  only transformed  0.000000 -0.124668
49              1     B  only transformed  0.000000 -0.124556
50              9     B  only transformed -0.000000 -0.123661
51           ▁nor     C  only transformed  0.000000 -0.123309
52              7     B  only transformed -0.000000 -0.122374
53              2     B  only transformed  0.000000 -0.121804
54              6     B  only transformed -0.000000 -0.121418
55       ▁without     C  only transformed  0.000000 -0.116932
56            All     B  only transformed -0.000000 -0.116388
57              0     B  only transformed  0.000000 -0.112664
58            non     C  only transformed  0.000000 -0.104859
59          ▁Only     N  only transformed -0.000000 -0.102073
60           alls     N  only transformed  0.000000 -0.097432
61         ▁senza     N  only transformed  0.000000 -0.097353
62       ▁lacking     C  only transformed  0.000000 -0.095130
63          ▁does     C  only transformed  0.000000 -0.087925
64          ▁less     B  only transformed  0.000000 -0.086364
65          ▁didn     N  only transformed  0.000000 -0.085516
66        ▁absent     C  only transformed  0.000000 -0.082863
67           ▁did     B  only transformed  0.000000 -0.077499
68       ▁Without     N  only transformed  0.000000 -0.077475
69            ▁do     C  only transformed -0.000000 -0.076984
70         ▁still     B  only transformed -0.000000 -0.073818
71           ▁few     C  only transformed -0.000000 -0.072412
72  ▁respectively     B  only transformed  0.000000  0.070967
73     ▁meanwhile     C  only transformed -0.000000  0.064448
74        ▁little     B  only transformed -0.000000 -0.062899
75           ▁far     C  only transformed -0.000000 -0.058939
76         ▁avoid     C  only transformed  0.000000 -0.055520
77       ▁refrain     C  only transformed  0.000000 -0.054609
78      ▁together     N  only transformed  0.000000  0.051820
79           ▁now     B  only transformed -0.000000 -0.051536
80            ▁ni     N  only transformed  0.000000 -0.051105

====================================================================================================
=== original 80 <-> transformed 87   Jaccard = 0.538   |cos(z0, unmap(z~))| = 0.840
====================================================================================================
  original rho-candidate 80: matched transformed feature 87 is NOT in F_C (best-Jaccard transformed partner: 87, J=0.538)
  both: 28   only original: 9   only transformed: 15

label              B   C  N
in
both               8  14  6
only original      4   2  3
only transformed  13   2  0

           token label                in    Y0[80]     Y[87]
0          ▁many     B              both -0.290086  0.339125
1       ▁various     B              both -0.294599  0.253296
2        Various     C              both -0.287632  0.241554
3           Many     C              both -0.237358  0.275668
4       ▁several     B              both -0.242387  0.275028
5          ▁Many     C              both -0.241223  0.271347
6      ▁numerous     N              both -0.269532  0.264675
7        ▁varied     C              both -0.211416  0.120063
8      ▁multiple     N              both -0.210310  0.150615
9       ▁diverse     B              both -0.205772  0.124527
10    ▁different     B              both -0.195339  0.136676
11      ▁variety     N              both -0.194738  0.092101
12       ▁dozens     C              both -0.181161  0.162958
13          ▁few     C              both -0.136495  0.180697
14         ▁some     B              both -0.139805  0.176550
15      ▁Variety     C              both -0.157862  0.057827
16       ▁others     B              both -0.145824  0.047627
17          Some     C              both -0.109748  0.144722
18    ▁diversity     C              both -0.141358  0.048806
19     ▁millions     C              both -0.109060  0.090537
20         ▁most     B              both -0.100377  0.104607
21         ▁tons     N              both -0.089706  0.053655
22         ▁much     C              both -0.075639  0.087279
23         ▁Most     N              both -0.086826  0.078090
24          most     C              both -0.077950  0.077366
25      ▁differs     C              both -0.077927  0.056832
26    ▁extensive     N              both -0.065737  0.045118
27       ▁almost     C              both -0.061568  0.059933
28        ▁other     B     only original -0.154993  0.000000
29         Other     C     only original -0.122284  0.000000
30      ▁another     B     only original -0.103916 -0.000000
31       Another     N     only original -0.083865 -0.000000
32        ▁multi     N     only original -0.076007  0.000000
33        ▁range     C     only original -0.071421  0.000000
34         ▁more     B     only original -0.066814  0.000000
35  ▁alternative     N     only original -0.066294  0.000000
36      ▁similar     B     only original -0.061352  0.000000
37             9     B  only transformed  0.000000 -0.147391
38             6     B  only transformed  0.000000 -0.147113
39             1     B  only transformed  0.000000 -0.146321
40             4     B  only transformed -0.000000 -0.145674
41             8     B  only transformed  0.000000 -0.144924
42             3     B  only transformed -0.000000 -0.144870
43             7     B  only transformed -0.000000 -0.144860
44             5     B  only transformed -0.000000 -0.142670
45             2     B  only transformed -0.000000 -0.138388
46             0     B  only transformed  0.000000 -0.122396
47        ▁often     C  only transformed -0.000000  0.064141
48       ▁number     B  only transformed -0.000000  0.054837
49   ▁frequently     C  only transformed -0.000000  0.051249
50           ome     B  only transformed -0.000000  0.047625
51          ▁two     B  only transformed -0.000000  0.045108

====================================================================================================
=== original 84 <-> transformed 25   Jaccard = 0.386   |cos(z0, unmap(z~))| = 0.511
====================================================================================================
  original rho-candidate 84: matched transformed feature 25 is NOT in F_C (best-Jaccard transformed partner: 25, J=0.386)
  both: 22   only original: 23   only transformed: 12

label              B   C  N
in
both               3  17  2
only original      4  10  9
only transformed  10   2  0

             token label                in    Y0[84]     Y[25]
0          ▁rather     C              both -0.126257 -0.365959
1           Rather     C              both -0.121595 -0.328693
2        ▁compared     C              both -0.308608 -0.257006
3         ▁instead     B              both -0.124326 -0.292615
4       ▁comparing     C              both -0.283712 -0.155280
5        Comparing     C              both -0.272066 -0.144851
6              ▁vs     C              both -0.209842 -0.266601
7    ▁similarities     C              both -0.231301 -0.057661
8        ▁contrast     C              both -0.221834 -0.138145
9         ▁opposed     C              both -0.181199 -0.219786
10          compar     C              both -0.207591 -0.115030
11        ▁against     B              both -0.112516 -0.189192
12           ▁than     B              both -0.103408 -0.186391
13        ▁likened     C              both -0.182843 -0.095012
14        ▁Against     C              both -0.103192 -0.173247
15         opposed     N              both -0.162598 -0.168302
16          Unlike     C              both -0.166447 -0.139101
17        ▁differs     C              both -0.144849 -0.087012
18          ▁juxta     C              both -0.136240 -0.082840
19        ▁opposes     C              both -0.118313 -0.115053
20  ▁distinguishes     C              both -0.101054 -0.054659
21      ▁replacing     N              both -0.090004 -0.046183
22      ▁parallels     C     only original -0.199436 -0.000000
23        ▁similar     B     only original -0.190533 -0.000000
24       ▁resemble     C     only original -0.158639 -0.000000
25      ▁resembles     C     only original -0.149903 -0.000000
26       ▁parallel     N     only original -0.143278 -0.000000
27      ▁identical     B     only original -0.138596  0.000000
28       Similarly     C     only original -0.110403  0.000000
29        ▁emulate     C     only original -0.103155 -0.000000
30      ▁competing     N     only original -0.099291 -0.000000
31        ▁matches     N     only original -0.094931 -0.000000
32           ▁same     B     only original -0.092413  0.000000
33          ▁match     N     only original -0.090829 -0.000000
34       ▁coincide     C     only original -0.089363  0.000000
35        ▁Wayback     N     only original -0.087670 -0.000000
36           ▁imit     C     only original -0.085814  0.000000
37     ▁concurrent     C     only original -0.084180 -0.000000
38       ▁competed     N     only original -0.081942 -0.000000
39    ▁superiority     C     only original -0.078485 -0.000000
40    ▁competitive     N     only original -0.074698 -0.000000
41       ▁replaced     N     only original -0.071690 -0.000000
42      ▁metaphors     C     only original -0.067099 -0.000000
43  ▁Distinguished     N     only original -0.062912 -0.000000
44            Like     B     only original -0.062024 -0.000000
45               3     B  only transformed  0.000000  0.151842
46               5     B  only transformed -0.000000  0.147561
47               2     B  only transformed  0.000000  0.147415
48               7     B  only transformed  0.000000  0.147231
49               4     B  only transformed -0.000000  0.145064
50               6     B  only transformed -0.000000  0.145061
51               8     B  only transformed -0.000000  0.144414
52               1     B  only transformed  0.000000  0.144302
53               0     B  only transformed  0.000000  0.136633
54               9     B  only transformed -0.000000  0.134553
55         ▁fairly     C  only transformed -0.000000 -0.064011
56       ▁somewhat     C  only transformed -0.000000 -0.057683

====================================================================================================
=== original 85 <-> transformed 52   Jaccard = 0.295   |cos(z0, unmap(z~))| = 0.583
====================================================================================================
  original rho-candidate 85: matched transformed feature 52 is NOT in F_C (best-Jaccard transformed partner: 52, J=0.295)
  both: 13   only original: 12   only transformed: 19

label              B  C  N
in
both               7  4  2
only original      6  4  2
only transformed  14  4  1

            token label                in    Y0[85]     Y[52]
0           ▁both     B              both  0.383417 -0.061871
1            both     N              both  0.380813 -0.062907
2          ▁every     C              both  0.231804 -0.333468
3           ▁each     B              both  0.279326 -0.318537
4           every     C              both  0.221916 -0.307059
5            ▁all     B              both  0.181121 -0.302391
6            Each     B              both  0.218512 -0.263601
7             all     C              both  0.170210 -0.262359
8             All     B              both  0.121880 -0.201854
9           ▁none     C              both  0.190043 -0.061972
10           ▁any     B              both  0.140505 -0.111609
11           alls     N              both  0.112172 -0.115149
12          ▁ever     B              both  0.083359 -0.092071
13       ▁neither     C     only original  0.376806  0.000000
14        ▁either     B     only original  0.278616 -0.000000
15            ▁no     B     only original  0.135235 -0.000000
16          ▁only     B     only original  0.116445 -0.000000
17  ▁respectively     B     only original  0.116336 -0.000000
18           ▁nor     C     only original  0.114977  0.000000
19      ▁anything     C     only original  0.107435 -0.000000
20         ▁never     C     only original  0.093923 -0.000000
21             no     B     only original  0.093209 -0.000000
22          ▁Only     N     only original  0.085167 -0.000000
23            ▁NO     N     only original  0.082902 -0.000000
24           ▁not     B     only original  0.076248  0.000000
25              5     B  only transformed -0.000000  0.196728
26              7     B  only transformed -0.000000  0.194495
27              6     B  only transformed -0.000000  0.192896
28              8     B  only transformed  0.000000  0.189876
29              3     B  only transformed  0.000000  0.187914
30              4     B  only transformed -0.000000  0.187337
31              2     B  only transformed  0.000000  0.185498
32              9     B  only transformed  0.000000  0.185149
33              1     B  only transformed  0.000000  0.183030
34              0     B  only transformed  0.000000  0.166538
35           ▁eve     C  only transformed  0.000000 -0.069001
36    ▁throughout     B  only transformed  0.000000 -0.061882
37         ▁whole     B  only transformed  0.000000 -0.060098
38    ▁individual     B  only transformed  0.000000 -0.053773
39          ▁even     B  only transformed  0.000000 -0.050698
40  ▁collectively     C  only transformed  0.000000 -0.048685
41    ▁altogether     N  only transformed  0.000000 -0.048501
42            ▁ev     C  only transformed  0.000000 -0.047079
43           volo     C  only transformed -0.000000 -0.044738

====================================================================================================
=== original 87 <-> transformed 88   Jaccard = 0.310   |cos(z0, unmap(z~))| = 0.718
====================================================================================================
  transformed concept feature 88: matched original feature 87 is IN F_C0 (best-Jaccard original partner: 87, J=0.310)
  original rho-candidate 87: matched transformed feature 88 is IN F_C (best-Jaccard transformed partner: 88, J=0.310)
  both: 27   only original: 26   only transformed: 34

label              B   C   N
in
both               0  27   0
only original      0   7  19
only transformed  11  23   0

              token label                in    Y0[87]     Y[88]
0           ffindor     C              both -0.334773 -0.310478
1            therin     C              both -0.251647 -0.259958
2         umbledore     C              both -0.250501 -0.212199
3          ▁Rowling     C              both -0.228620 -0.162695
4            demort     C              both -0.214367 -0.151681
5        ▁Voldemort     C              both -0.209508 -0.161648
6       ▁Dumbledore     C              both -0.209441 -0.188911
7          ▁Weasley     C              both -0.204552 -0.178177
8           ▁Malfoy     C              both -0.198630 -0.173265
9         ▁Hogwarts     C              both -0.194563 -0.179498
10         Hermione     C              both -0.189719 -0.163772
11           ▁Snape     C              both -0.181075 -0.135932
12        ▁Hermione     C              both -0.176337 -0.161442
13          ▁Potter     C              both -0.153993 -0.166467
14           Potter     C              both -0.148859 -0.142912
15           ▁Harry     C              both -0.124677 -0.148712
16            Harry     C              both -0.124393 -0.140369
17         ▁Severus     C              both -0.133529 -0.111156
18           ▁Draco     C              both -0.123219 -0.113829
19           ▁Ginny     C              both -0.115729 -0.100680
20              Hog     C              both -0.073698 -0.108963
21             ▁Gry     C              both -0.080851 -0.104352
22           ▁Lupin     C              both -0.101987 -0.072085
23             otts     C              both -0.072647 -0.095830
24        ▁Sherlock     C              both -0.094214 -0.058746
25           ▁Remus     C              both -0.086938 -0.073495
26          ▁Sirius     C              both -0.066154 -0.065989
27         ▁Kipling     C     only original -0.119487 -0.000000
28         ▁Beatles     C     only original -0.102212 -0.000000
29           cellor     N     only original -0.098149 -0.000000
30          condido     N     only original -0.097348 -0.000000
31  ▁Arrondissement     N     only original -0.096683 -0.000000
32            cidae     N     only original -0.094464 -0.000000
33          ▁Alamos     N     only original -0.091261 -0.000000
34           ▁Trump     C     only original -0.085880 -0.000000
35          ▁Nestlé     C     only original -0.085640 -0.000000
36             ompi     N     only original -0.085159 -0.000000
37        ▁Steelers     N     only original -0.081542 -0.000000
38           ▁tesla     N     only original -0.081415  0.000000
39            ▁Lego     C     only original -0.080935 -0.000000
40            lidae     N     only original -0.080864 -0.000000
41            ridae     N     only original -0.080720 -0.000000
42           iennes     N     only original -0.080277 -0.000000
43         ▁Ceramby     N     only original -0.079504 -0.000000
44    ▁Chhattisgarh     N     only original -0.079409 -0.000000
45         ▁Picasso     N     only original -0.077788 -0.000000
46      ▁Bloomsbury     C     only original -0.075447 -0.000000
47             ▁HBO     C     only original -0.074183 -0.000000
48          ▁Kinect     N     only original -0.073881 -0.000000
49           assins     N     only original -0.073579 -0.000000
50          ▁Reagan     N     only original -0.071193 -0.000000
51          ▁Lenovo     N     only original -0.062886  0.000000
52         ▁Haryana     N     only original -0.059986 -0.000000
53                2     B  only transformed  0.000000  0.172249
54                4     B  only transformed -0.000000  0.163704
55                3     B  only transformed  0.000000  0.158403
56                8     B  only transformed  0.000000  0.157508
57                6     B  only transformed  0.000000  0.154703
58                5     B  only transformed -0.000000  0.154513
59                1     B  only transformed  0.000000  0.153229
60                7     B  only transformed  0.000000  0.152949
61                9     B  only transformed -0.000000  0.144712
62                0     B  only transformed -0.000000  0.143212
63             ▁Hog     C  only transformed -0.000000 -0.097193
64            warts     C  only transformed -0.000000 -0.086719
65         ▁Granger     C  only transformed -0.000000 -0.072985
66            ▁wand     C  only transformed -0.000000 -0.068261
67             ▁Sly     C  only transformed -0.000000 -0.068012
68              ▁JK     C  only transformed -0.000000 -0.066945
69          ▁wizard     C  only transformed -0.000000 -0.066222
70             ▁Mug     B  only transformed -0.000000 -0.063299
71         ▁wizards     C  only transformed -0.000000 -0.062322
72             blet     C  only transformed -0.000000 -0.060788
73             ▁McG     C  only transformed -0.000000 -0.060375
74         ▁potions     C  only transformed -0.000000 -0.059631
75            ▁Grin     C  only transformed -0.000000 -0.058970
76              idd     C  only transformed -0.000000 -0.057946
77          ▁Merlin     C  only transformed -0.000000 -0.057543
78          ▁Riddle     C  only transformed -0.000000 -0.057011
79             ▁Ron     C  only transformed -0.000000 -0.056796
80            ▁Quir     C  only transformed -0.000000 -0.056406
81           wizard     C  only transformed -0.000000 -0.055944
82          ▁Holmes     C  only transformed -0.000000 -0.054985
83          ▁Wizard     C  only transformed -0.000000 -0.054313
84             ▁Hag     C  only transformed -0.000000 -0.053988
85              Row     C  only transformed -0.000000 -0.051296
86          ▁Cedric     C  only transformed -0.000000 -0.049141

====================================================================================================
=== original 88 <-> transformed 37   Jaccard = 0.621   |cos(z0, unmap(z~))| = 0.854
====================================================================================================
  original rho-candidate 88: matched transformed feature 37 is NOT in F_C (best-Jaccard transformed partner: 37, J=0.621)
  both: 18   only original: 7   only transformed: 4

label             B   C  N
in
both              4  11  3
only original     2   4  1
only transformed  2   0  2

          token label                in    Y0[88]     Y[37]
0         ▁part     B              both -0.399212 -0.474845
1          part     C              both -0.397594 -0.459243
2         ▁Part     N              both -0.372358 -0.414831
3        ▁parts     C              both -0.361804 -0.392588
4        ▁Parts     C              both -0.330321 -0.336345
5      ▁partial     C              both -0.157345 -0.088216
6     ▁sections     C              both -0.153308 -0.145984
7      ▁section     C              both -0.146475 -0.150359
8        ▁piece     N              both -0.130504 -0.072444
9       ▁pieces     B              both -0.128372 -0.061881
10  ▁components     N              both -0.122749 -0.095288
11     ▁segment     B              both -0.110381 -0.083059
12     ▁aspects     C              both -0.103340 -0.099235
13    ▁elements     C              both -0.085636 -0.072982
14     ▁Chapter     C              both -0.081722 -0.076228
15     ▁element     C              both -0.081083 -0.078587
16     ▁chapter     C              both -0.074981 -0.081071
17        ▁side     B              both -0.071116 -0.050374
18        ▁half     C     only original -0.204872 -0.000000
19         half     B     only original -0.194774 -0.000000
20        ▁Half     C     only original -0.187680  0.000000
21      ▁behalf     C     only original -0.074525 -0.000000
22         most     C     only original -0.068721 -0.000000
23        ▁most     B     only original -0.056543 -0.000000
24        ▁Most     N     only original -0.053437 -0.000000
25      ▁member     B  only transformed -0.000000 -0.059663
26     ▁members     B  only transformed -0.000000 -0.056149
27         ▁par     N  only transformed -0.000000 -0.048846
28      Members     N  only transformed -0.000000 -0.046415

====================================================================================================
=== original 91 <-> transformed 99   Jaccard = 0.078   |cos(z0, unmap(z~))| = 0.077
====================================================================================================
  original rho-candidate 91: matched transformed feature 99 is NOT in F_C (best-Jaccard transformed partner: 75, J=0.116)
  both: 5   only original: 25   only transformed: 34

label              B   C  N
in
both               2   3  0
only original      6  13  6
only transformed  14  13  7

            token label                in    Y0[91]     Y[99]
0         ▁launch     C              both  0.250648 -0.103932
1       ▁launched     B              both  0.234817 -0.082542
2          ▁debut     B              both  0.144107 -0.070073
3       ▁premiere     C              both  0.107860 -0.053156
4      ▁inaugural     C              both  0.097919 -0.056333
5   ▁announcement     C     only original  0.357304 -0.000000
6      ▁announced     B     only original  0.344847 -0.000000
7     ▁announcing     N     only original  0.334966  0.000000
8       ▁released     B     only original  0.274432 -0.000000
9        ▁release     B     only original  0.272963 -0.000000
10      ▁revealed     C     only original  0.174627  0.000000
11        ▁reveal     C     only original  0.168752 -0.000000
12     ▁statement     C     only original  0.168589  0.000000
13           ▁Ann     N     only original  0.159564 -0.000000
14          ▁news     C     only original  0.156547  0.000000
15      ▁declared     B     only original  0.148952 -0.000000
16     ▁unleashed     C     only original  0.140764 -0.000000
17    ▁statements     C     only original  0.135138 -0.000000
18          ▁News     N     only original  0.133504  0.000000
19           News     C     only original  0.130913  0.000000
20     ▁confirmed     C     only original  0.129100  0.000000
21    ▁introduced     N     only original  0.121506 -0.000000
22       ▁confirm     N     only original  0.114948  0.000000
23        ▁issued     C     only original  0.104206 -0.000000
24       ▁stating     B     only original  0.097992 -0.000000
25        ▁stated     C     only original  0.093398 -0.000000
26         ▁heral     C     only original  0.085696  0.000000
27     ▁published     B     only original  0.078957 -0.000000
28      ▁sentence     N     only original  0.076716 -0.000000
29        ▁saying     C     only original  0.074559  0.000000
30         ▁start     B  only transformed  0.000000 -0.312522
31          start     C  only transformed  0.000000 -0.282866
32           ▁she     B  only transformed -0.000000  0.269561
33           ▁her     B  only transformed  0.000000  0.268866
34      ▁starting     N  only transformed  0.000000 -0.258294
35     ▁beginning     B  only transformed  0.000000 -0.257485
36       ▁started     B  only transformed  0.000000 -0.229248
37         ▁begin     N  only transformed  0.000000 -0.228545
38            She     B  only transformed -0.000000  0.216142
39            her     C  only transformed  0.000000  0.210730
40            Her     N  only transformed  0.000000  0.192435
41           ▁She     N  only transformed  0.000000  0.192030
42       ▁herself     C  only transformed -0.000000  0.188901
43         ▁begun     N  only transformed  0.000000 -0.187804
44         ▁began     C  only transformed  0.000000 -0.186128
45           ▁Her     N  only transformed  0.000000  0.178631
46           ▁end     B  only transformed -0.000000 -0.124894
47     ▁inception     C  only transformed  0.000000 -0.111774
48         ▁first     B  only transformed  0.000000 -0.095774
49            ▁he     B  only transformed -0.000000  0.094812
50       ▁initial     C  only transformed  0.000000 -0.088159
51           ▁his     B  only transformed  0.000000  0.080235
52             He     B  only transformed -0.000000  0.078048
53            ▁He     B  only transformed -0.000000  0.069683
54           ▁him     B  only transformed -0.000000  0.068348
55            His     C  only transformed -0.000000  0.065108
56       ▁onwards     C  only transformed  0.000000 -0.063468
57         ▁ended     C  only transformed -0.000000 -0.063306
58           ▁His     C  only transformed -0.000000  0.061915
59          First     C  only transformed  0.000000 -0.060780
60     ▁initially     C  only transformed  0.000000 -0.059395
61          ▁Ende     N  only transformed -0.000000 -0.058997
62       ▁himself     C  only transformed  0.000000  0.053311
63       ▁opening     B  only transformed  0.000000 -0.052587

====================================================================================================
=== original 92 <-> transformed 24   Jaccard = 0.595   |cos(z0, unmap(z~))| = 0.823
====================================================================================================
  original rho-candidate 92: matched transformed feature 24 is NOT in F_C (best-Jaccard transformed partner: 24, J=0.595)
  both: 22   only original: 1   only transformed: 14

label             B   C  N
in
both              4  11  7
only original     0   0  1
only transformed  5   6  3

           token label                in    Y0[92]     Y[24]
0        ▁living     B              both -0.338555 -0.434189
1         ▁lived     C              both -0.359813 -0.360959
2          ▁live     B              both -0.334774 -0.344807
3         ▁lives     C              both -0.339258 -0.329321
4          lived     N              both -0.317639 -0.278552
5          ▁life     B              both -0.266926 -0.264249
6         ▁alive     C              both -0.254684 -0.254256
7           life     C              both -0.240406 -0.229717
8       ▁resided     N              both -0.189593 -0.153258
9       ▁resides     C              both -0.183103 -0.153617
10        ▁dwell     N              both -0.154334 -0.090046
11        ▁exist     C              both -0.149801 -0.117554
12       ▁exists     C              both -0.139065 -0.108555
13     ▁Lifetime     N              both -0.136713 -0.072457
14    ▁surviving     C              both -0.122697 -0.128054
15     ▁survived     N              both -0.118859 -0.114248
16         ▁born     N              both -0.106149 -0.071147
17          born     B              both -0.102136 -0.061101
18       ▁lively     C              both -0.098147 -0.094640
19      ▁careers     C              both -0.072703 -0.056285
20  ▁existential     C              both -0.071782 -0.052625
21        ▁liver     N              both -0.070896 -0.048473
22     breathing     N     only original -0.064820 -0.000000
23      ▁working     N  only transformed -0.000000 -0.079299
24         ▁real     C  only transformed -0.000000 -0.067516
25        ▁works     B  only transformed -0.000000 -0.062873
26       ▁worked     N  only transformed -0.000000 -0.060935
27         ▁dead     C  only transformed -0.000000 -0.058440
28  ▁functioning     C  only transformed -0.000000 -0.058309
29       ▁moving     C  only transformed -0.000000 -0.058134
30         ▁work     B  only transformed -0.000000 -0.056491
31      ▁married     B  only transformed -0.000000 -0.054326
32      ▁reality     C  only transformed -0.000000 -0.053704
33       ▁travel     C  only transformed -0.000000 -0.052527
34       ▁active     B  only transformed -0.000000 -0.050364
35         ▁stay     B  only transformed -0.000000 -0.049279
36     ▁workings     N  only transformed -0.000000 -0.044885

====================================================================================================
=== original 93 <-> transformed 93   Jaccard = 0.550   |cos(z0, unmap(z~))| = 0.913
====================================================================================================
  original rho-candidate 93: matched transformed feature 93 is NOT in F_C (best-Jaccard transformed partner: 93, J=0.550)
  both: 33   only original: 21   only transformed: 6

label              B   C  N
in
both              16  10  7
only original      6   9  6
only transformed   3   1  2

           token label                in    Y0[93]     Y[93]
0           ▁may     B              both  0.263956  0.298038
1         ▁might     C              both  0.276102  0.289913
2           ▁can     B              both  0.232024  0.279125
3         ▁could     B              both  0.262389  0.278917
4          ▁will     N              both  0.202303  0.272957
5         ▁would     B              both  0.222746  0.271293
6        ▁should     C              both  0.210139  0.240938
7           ▁are     B              both  0.132452  0.237510
8          ▁must     C              both  0.203304  0.229878
9            ▁is     B              both  0.129576  0.216678
10       ▁cannot     C              both  0.179192  0.185850
11         ▁need     C              both  0.170767  0.112064
12         ▁were     B              both  0.108710  0.168405
13       ▁likely     C              both  0.164061  0.064203
14          ▁has     B              both  0.132331  0.157238
15          ▁was     B              both  0.119178  0.153030
16         ▁does     C              both  0.133568  0.152391
17         ▁have     B              both  0.133068  0.152263
18          ▁did     B              both  0.143593  0.137787
19     ▁possibly     C              both  0.142386  0.066547
20        ▁needs     N              both  0.139097  0.075457
21          ▁won     B              both  0.126493  0.087880
22          ▁had     B              both  0.126465  0.110985
23         ▁didn     N              both  0.123569  0.066080
24           ▁do     C              both  0.096238  0.120332
25       ▁needed     B              both  0.110151  0.054761
26         ▁also     B              both  0.106460  0.048001
27          ▁May     N              both  0.104985  0.090841
28           May     N              both  0.099223  0.086042
29           Can     N              both  0.097111  0.095780
30          have     N              both  0.060903  0.084642
31       ▁seemed     C              both  0.078247  0.056301
32           ▁be     B              both  0.066904  0.056686
33        ▁still     B     only original  0.137532  0.000000
34     ▁possible     N     only original  0.121043  0.000000
35        ▁never     C     only original  0.112564  0.000000
36  ▁possibility     C     only original  0.110116  0.000000
37    ▁potential     C     only original  0.095792  0.000000
38     ▁actually     C     only original  0.092695  0.000000
39        ▁often     C     only original  0.089316  0.000000
40       ▁really     C     only original  0.088585  0.000000
41          ▁not     B     only original  0.087553  0.000000
42      ▁usually     N     only original  0.086087  0.000000
43      ▁already     C     only original  0.085570  0.000000
44         ▁only     B     only original  0.079297  0.000000
45     ▁expected     N     only original  0.077495  0.000000
46         Still     N     only original  0.077271  0.000000
47         ▁even     B     only original  0.075931  0.000000
48         ▁just     B     only original  0.074851 -0.000000
49      ▁chances     C     only original  0.074745  0.000000
50       ▁having     N     only original  0.073030  0.000000
51        ▁being     B     only original  0.072746  0.000000
52     ▁supposed     N     only original  0.071924  0.000000
53         ▁knew     C     only original  0.059729  0.000000
54            is     B  only transformed  0.000000  0.076265
55           ▁or     B  only transformed  0.000000  0.069482
56           ▁am     N  only transformed  0.000000  0.060814
57           ▁if     B  only transformed  0.000000  0.060555
58          ▁doe     C  only transformed  0.000000  0.054028
59         ▁habe     N  only transformed  0.000000  0.048218

====================================================================================================
=== original 98 <-> transformed 10   Jaccard = 0.364   |cos(z0, unmap(z~))| = 0.669
====================================================================================================
  original rho-candidate 98: matched transformed feature 10 is NOT in F_C (best-Jaccard transformed partner: 10, J=0.364)
  both: 24   only original: 8   only transformed: 34

label             B   C  N
in
both              3  17  4
only original     0   6  2
only transformed  4  23  7

          token label                in    Y0[98]     Y[10]
0         ▁love     C              both  0.415241 -0.340773
1         ▁Love     N              both  0.377194 -0.257163
2          Love     C              both  0.367233 -0.254472
3        ▁loves     C              both  0.344422 -0.301406
4        ▁loved     C              both  0.299137 -0.258556
5        ▁likes     C              both  0.191204 -0.278364
6         ▁like     B              both  0.100064 -0.248046
7          Like     B              both  0.091334 -0.201310
8        ▁wants     C              both  0.121246 -0.185023
9         ▁hope     C              both  0.168523 -0.158128
10       ▁Wants     C              both  0.127182 -0.162595
11        ▁Hope     N              both  0.153834 -0.085436
12     ▁dislike     C              both  0.139785 -0.136044
13         ▁joy     C              both  0.139144 -0.075501
14      ▁desire     C              both  0.139128 -0.125307
15         Wish     N              both  0.124408 -0.055924
16   ▁happiness     C              both  0.119699 -0.073483
17     ▁thought     C              both  0.070477 -0.117200
18     ▁romance     C              both  0.114587 -0.075901
19      ▁wished     N              both  0.102117 -0.072481
20   ▁favourite     C              both  0.098913 -0.082201
21    ▁romances     C              both  0.095671 -0.067250
22    ▁romantic     C              both  0.095324 -0.051844
23      ▁dreams     B              both  0.090746 -0.068786
24         ▁Joy     C     only original  0.112639 -0.000000
25  ▁enthusiasm     N     only original  0.091936 -0.000000
26     ▁excited     C     only original  0.079346 -0.000000
27    ▁dreaming     C     only original  0.072202 -0.000000
28         ▁pet     C     only original  0.071776 -0.000000
29       ▁eager     C     only original  0.070748 -0.000000
30     ▁embrace     N     only original  0.068895 -0.000000
31         ▁Pet     C     only original  0.063853 -0.000000
32        ▁need     C  only transformed  0.000000 -0.127072
33        ▁know     C  only transformed  0.000000 -0.125007
34       ▁needs     N  only transformed  0.000000 -0.122133
35        ▁knew     C  only transformed  0.000000 -0.109687
36     ▁believe     C  only transformed  0.000000 -0.106423
37       ▁think     C  only transformed  0.000000 -0.106264
38     ▁friends     B  only transformed  0.000000 -0.101604
39  ▁friendship     C  only transformed  0.000000 -0.095116
40       ▁trust     N  only transformed  0.000000 -0.094462
41      ▁expect     C  only transformed  0.000000 -0.093223
42      ▁friend     C  only transformed  0.000000 -0.093093
43  ▁interested     C  only transformed  0.000000 -0.087805
44   ▁interests     N  only transformed  0.000000 -0.086118
45      ▁needed     B  only transformed  0.000000 -0.082616
46  ▁understand     C  only transformed  0.000000 -0.079291
47     ▁willing     C  only transformed  0.000000 -0.074072
48       ▁faith     C  only transformed  0.000000 -0.072537
49     ▁intends     C  only transformed  0.000000 -0.071101
50      ▁tastes     C  only transformed  0.000000 -0.070183
51       Unlike     C  only transformed  0.000000 -0.069767
52          lik     N  only transformed  0.000000 -0.068687
53       ▁worth     C  only transformed  0.000000 -0.067996
54        trust     C  only transformed  0.000000 -0.066358
55       ▁truth     B  only transformed  0.000000 -0.063700
56   ▁knowledge     N  only transformed  0.000000 -0.063589
57      ▁really     C  only transformed  0.000000 -0.061523
58       ▁lives     C  only transformed  0.000000 -0.059190
59       ▁feels     C  only transformed  0.000000 -0.058363
60       ▁great     B  only transformed  0.000000 -0.055744
61       ▁looks     C  only transformed  0.000000 -0.055634
62    ▁expected     N  only transformed  0.000000 -0.054265
63     ▁likened     C  only transformed  0.000000 -0.053080
64        ▁good     C  only transformed  0.000000 -0.052907
65    ▁resulted     N  only transformed -0.000000  0.052523

#### Run summary → `RUN_DIR/summary.json`

Configuration (variant, `VWConfig`, whitening), $|V^*|$, relative errors and width statistics of both fits, $\rho_{\max}$, $F_C$
(judged, whitened fit) with each feature's width, `F_C0` (= $\rho\ge\tau$ candidates of the original fit, not judged), each $F_C$
feature's matched original partner (Jaccard, partner in `F_C0`?), and the number of concept-only tokens $F_C$ touches.

In [43]:
def write_summary(**extra) -> dict:
    """Write RUN_DIR/summary.json from the current state; `extra` adds or overrides fields."""
    eligible_cols = ((Y[F_C].abs() > 0).any(dim=0).numpy() & (codes == 1)) if F_C else np.zeros(len(vstar_ids), bool)
    summary = {
        "config": {"model": MODEL_NAME, "concept": CONCEPT, "variant": VARIANT, "vwconfig": CFG.to_dict(), "seed": SEED,
                   "background": BACKGROUND, "target": TARGET, "gamma": GAMMA, "eta": ETA, "eps_rel": EPS_REL,
                   "eps": float(bw.eps), "rank": RANK, "smoke": SMOKE, "n_target": len(target_ids)},
        "n_vstar": len(vstar_ids),
        "rel_err": {"original": rel_err0, "transformed": rel_err},
        "n_iter": {"original": fit0["n_iter"], "transformed": fit["n_iter"]},
        "widths": {"transformed": widths.tolist(), "original": widths0.tolist()},
        "F_C_widths": {str(f): int(widths[f]) for f in F_C},
        "rho_max": float(stats["ratio_abs"].max()),
        "rho_max_original": float(stats0["ratio_abs"].max()),
        "n_F_C": len(F_C),
        "F_C": F_C,
        "F_C0": F_C0,                     # rho >= tau candidates of the original fit (no judge)
        "F_C_matched": [{"feature": f, "partner": match1[f], "jaccard": float(J[match1[f], f]),
                         "partner_in_F_C0": match1[f] in F_C0, "cos_m": float(cos_m[f])} for f in F_C],
        "F_C0_matched": [{"feature": f0, "partner": match0[f0], "jaccard": float(J[f0, match0[f0]]),
                          "partner_in_F_C": match0[f0] in F_C} for f0 in F_C0],
        "matched_jaccard_median": float(np.median(J[rows0, cols1])),
        "n_edit": int(eligible_cols.sum()),
        **extra,
    }
    save_json(RUN_DIR / "summary.json", summary)
    print(f"wrote {RUN_DIR / 'summary.json'}: F_C={F_C} F_C0={F_C0} n_edit={summary['n_edit']} "
          f"rel_err={rel_err:.4f} (orig {rel_err0:.4f}) rho_max={summary['rho_max']:.2f}")
    return summary


summary = write_summary()

wrote runs/variable_width/Harry_Potter/rn/summary.json: F_C=[88] F_C0=[3, 6, 9, 11, 12, 14, 16, 18, 20, 22, 23, 24, 25, 28, 33, 35, 36, 38, 51, 52, 54, 58, 59, 62, 67, 71, 73, 78, 80, 84, 85, 87, 88, 91, 92, 93, 98] n_edit=50 rel_err=0.8529 (orig 0.9047) rho_max=287541.98